[Azure AD roles] Restricted management administrative unit properties (Beta)
microsoftgraph/microsoft-graph-docs pull request #16295
Opened 2022-03-24 20:52 UTC by rolyon

2022-03-24 21:34 UTC, opbld33 commented
Docs Build status updates of commit _[a0c348f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0c348f3015b2cbd77b9b68829268bdba8255f8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203242132055524-16295%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T21%3A34%3A21Z&sr=b&sp=r&sig=Ux6jb4F2b%2BygYkkJAXSJt7vHHwXW3NT8tng8oDfKsjA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 22:49 UTC, opbld32 commented
Docs Build status updates of commit _[67883db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67883db3b45efb4c14b8bf1f42bf78d087456949)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203312247179153-16295%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T22%3A49%3A29Z&sr=b&sp=r&sig=Ej0FBcwReqsrBJ6GIT11qUAtqubQGEFp70r6ZdayjKk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 22:58 UTC, opbld34 commented
Docs Build status updates of commit _[ff8bc1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff8bc1b6fd6a27b46fa0028177e9fc7b9deae659)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203312256159043-16295%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T22%3A58%3A16Z&sr=b&sp=r&sig=C20OIE0JSNR21Af5rnawF9qBt%2FD4ythFprutDR%2BISMs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 04:39 UTC, opbld32 commented
Docs Build status updates of commit _[c4b0cc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4b0cc1f664c1decf1b71d1bcaed828971a0376a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204010437324670-16295%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T04%3A39%3A22Z&sr=b&sp=r&sig=umtEoTZEoFOxJHdHGHK3vQmWv8rlFiXMDYY8vuOj7HU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 21:32 UTC, opbld32 commented
Docs Build status updates of commit _[19afa14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19afa14d6999cdfc1daa20309de37cbb2d0cdaa2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204042130190053-16295%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T21%3A32%3A20Z&sr=b&sp=r&sig=F%2BM5kvdwiub%2Bsbkk4rvqLIto1JSWiQRTUTIrSdx8ycQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 21:40 UTC, opbld34 commented
Docs Build status updates of commit _[6e81519](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e815199985631952e97d8f8d177bdbf28cc3ded)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204042137281661-16295%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T21%3A40%3A02Z&sr=b&sp=r&sig=X6kwXF6EfU2HnBbePTMI1%2BpPh8vld0oT6BgxBUWqKG4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 19:16 UTC, FaithOmbongi requested changes
Thank you @#for your work on this PR. 

- I've left suggestions to call out the role requirements where they apply and a couple to enhance the changelog descriptions.
- It seems from the schema that the isManagementRestricted property is also going live for applications and service principals. Can you confirm and include these in your PR?

A point of note though: In the [administrative units docs](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta), we don't mention that applications and service principals can be members of administrative units. If apps and service principals should be included in the list of possible members that can be added, retrieved, or removed from AUs, let's close that gap too.

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/resources/device.md
> +|isManagementRestricted|Boolean|`true` if the device should be treated as sensitive, which requires specific permissions to manage. Default value is `false`. Read-only.|
The API.md isn't clear on what these "special permissions" are. Kindly clarify/document if there are restrictions. For example, if this device isn't part of a restricted AU but is a restricted device, who can manage it? Is it still only Global Administrator and Privileged Role Administrator?

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/resources/group.md
> +| isManagementRestricted         | Boolean                                                                  | Indicates whether the group should be treated as sensitive, which requires specific permi
Same comment in the device mention

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
> +| isManagementRestricted| Boolean | `true` if the user should be treated as sensitive, which requires specific permissions to manage. Default value is `false`. Read-only. |
Same comment in the device mention

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/api/user-list.md
> +GET https://graph.microsoft.com/beta/users?$filter=isManagementRestricted eq true&$select=displayName,userPrincipalName
Q: Do you need special permissions/roles to successfully make this request?

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/api/group-get.md
> +GET https://graph.microsoft.com/beta/groups/aed0b780-965f-4149-85c5-a8c73e58brt6?$select=isManagementRestricted
Q: Do you need special permissions/roles to successfully make this request?

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/api/directory-post-administrativeunits.md
> +### Example 2: Create a restricted management administrative unit
I think it's a "restricted administrative unit" meaning its management is restricted - not a "restricted management administrative unit"

Let's call out the special role requirements
```suggestion
### Example 2: Create a restricted administrative unit
```

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/api/administrativeunit-update.md
> +The following example changes a restricted management administrative unit to a regular administrative unit.
Call out the role requirements

2022-04-07 19:16 UTC, FaithOmbongi commented on api-reference/beta/api/administrativeunit-get.md
> +GET https://graph.microsoft.com/beta/administrativeUnits/2sd35b05-ae71-48ab-9e7d-4r41a28te37d
Any role requirements for READ operations?

2022-04-07 19:16 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **IsMemberManagementRestricted** property to the [administrativeUnit](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta)
Suggestion to enhance the description. Please tweak where applicable.
```suggestion
          "Description": "Added the **isMemberManagementRestricted** property to the [administrativeUnit](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta) resource. Use this property to define administrative units whose management is restricted to a limited group of administrators with the appropriate permissions and specific Azure AD administrative roles.",
```

2022-04-07 19:16 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **IsManagementRestricted** property to the [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta) resource.",
Suggestions to enhance the descriptions.
```suggestion
          "Description": "Added the **isManagementRestricted** property to the [device](https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta) resource. Use this property to define devices whose management is restricted to a limited group of administrators with the appropriate permissions and specific Azure AD administrative roles.",
          "Target": "device"
        },
        { 
          "Id": "12f096a3-6bd8-49db-8753-24c9272a288b",
          "ApiChange": "Property",
          "ChangedApiName": "IsManagementRestricted",
          "ChangeType": "Addition",
          "Description": "Added the **isManagementRestricted** property to the [group](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta) resource. Use this property to define groups whose management is restricted to a limited group of administrators with the appropriate permissions and specific Azure AD administrative roles.",
          "Target": "group"
        },
        { 
          "Id": "12f096a3-6bd8-49db-8753-24c9272a288b",
          "ApiChange": "Property",
          "ChangedApiName": "IsManagementRestricted",
          "ChangeType": "Addition",
          "Description": "Added the **isManagementRestricted** property to the [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta) resource. Use this property to define users whose profile management is restricted to a limited group of administrators with the appropriate permissions and specific Azure AD administrative roles.",
```

2022-04-19 21:55 UTC, KaTabish commented on api-reference/beta/api/administrativeunit-get.md
> +GET https://graph.microsoft.com/beta/administrativeUnits/2sd35b05-ae71-48ab-9e7d-4r41a28te37d
No. Default user should be able to read.

2022-04-19 21:57 UTC, KaTabish commented on api-reference/beta/api/administrativeunit-update.md
> +The following example changes a restricted management administrative unit to a regular administrative unit.
Only Global Admins and Privileged Role admins are allowed to perform write operations on AUs.
This applies to all AU create/update/delete operations.

2022-04-19 22:00 UTC, KaTabish commented on api-reference/beta/api/directory-post-administrativeunits.md
> +### Example 2: Create a restricted management administrative unit
It is indeed called a "restricted management admin unit". The management of the AU is not restricted, but the management of the individual members of the AU is restricted.
No special role requirement other than what applies to AUs in general.

2022-04-19 22:00 UTC, KaTabish commented on api-reference/beta/api/group-get.md
> +GET https://graph.microsoft.com/beta/groups/aed0b780-965f-4149-85c5-a8c73e58brt6?$select=isManagementRestricted
No. Default user can read this.

2022-04-19 22:01 UTC, KaTabish commented on api-reference/beta/api/user-list.md
> +GET https://graph.microsoft.com/beta/users?$filter=isManagementRestricted eq true&$select=displayName,userPrincipalName
No

2022-04-19 22:34 UTC, KaTabish commented on api-reference/beta/resources/administrativeunit.md
> +|isMemberManagementRestricted|Boolean|`true` if members of this administrative unit should be treated as sensitive, which requires specific permissions to manage. Default value is `false`.|
Not sure I understand: "If the caller lacks these roles but has the permissions"?
Default users can read this value, so you don't have to be a GA/PRA to see it.

2022-04-19 22:40 UTC, KaTabish commented on api-reference/beta/resources/device.md
> +|isManagementRestricted|Boolean|`true` if the device should be treated as sensitive, which requires specific permissions to manage. Default value is `false`. Read-only.|
GA/PRA cannot manage restricted device. Also a device cannot be restricted if it isn't a member of a restricted AU.
I think we should change it to " 'true' if the device is a member of a restricted management admin unit, in which case it requires a role scoped to the restricted AU to manage "

2022-04-19 22:40 UTC, KaTabish commented on api-reference/beta/resources/group.md
> +| isManagementRestricted         | Boolean                                                                  | Indicates whether the group should be treated as sensitive, which requires specific permi
see above

2022-04-19 22:41 UTC, KaTabish commented on api-reference/beta/resources/user.md
> +| isManagementRestricted| Boolean | `true` if the user should be treated as sensitive, which requires specific permissions to manage. Default value is `false`. Read-only. |
see above

2022-04-19 23:57 UTC, KaTabish commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **IsManagementRestricted** property to the [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta) resource.",
I don't think we should say "use this property to define" as it cannot be directly controlled by end user.
We can use a common definition like "This property denotes objects whose management is restricted to admins scoped over restricted management admin units the object is a member of".

2022-04-20 00:02 UTC, KaTabish commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **IsMemberManagementRestricted** property to the [administrativeUnit](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta)
....to define admins units whose roles don't inherit from tenant level administrators, and management of individual member objects is limited to admins scoped over a restricted management admin unit.

2022-05-28 00:37 UTC, opbld33 commented
Docs Build status updates of commit _[39dd565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39dd565cb1088b70b7e34d6e9cdcbda6b5d1e986)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-5e611b97)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="eea99bea355d0a4253064eefdbbe7005-5e611b97"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md)
 - **Line 762, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205280034527566-16295/BuildReport?accessString=8bb41163063ff0712378680cbe7fd598cd5a33f39d878637a4b48c85a09240c3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-28 00:46 UTC, opbld32 commented
Docs Build status updates of commit _[7ef655b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ef655bc1f4c9c3a1aa866dfa6b7beaac6abe3c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205280044375396-16295/BuildReport?accessString=be26c84bf232b50df92b65e89192a2453333afcb80e9cb3623e0823fe209db91).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 04:56 UTC, opbld33 commented
Docs Build status updates of commit _[a3dbc74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3dbc7447848df72ec60a7e29b0e2d24726273cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206040454084742-16295/BuildReport?accessString=bdcff908f72306d4a36a435eb9b11cb1d7fa228393ceb4cd5caac91c196e48ab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 06:25 UTC, rolyon commented on api-reference/beta/api/administrativeunit-update.md
> +The following example changes a restricted management administrative unit to a regular administrative unit.
Prerequisite roles were added in a separate pull request:
https://github.com/microsoftgraph/microsoft-graph-docs/pull/17106

2022-06-06 06:25 UTC, rolyon commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **IsMemberManagementRestricted** property to the [administrativeUnit](https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta)
I dont think we should add specific info in the changelog that could out of date. Please see updated description in administrativeunit.md

2022-06-06 06:25 UTC, rolyon commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **IsManagementRestricted** property to the [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta) resource.",
I dont think we should add specific info in the changelog that could out of date. Please see updated descriptions in device.md, group.md, and user.md

2022-06-06 06:30 UTC, opbld32 commented
Docs Build status updates of commit _[a5251a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5251a6abfeaa01840bc1e367d6350e5cfecb383)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206060628272922-16295/BuildReport?accessString=2f9891a101cb90c616a474a049817314abba981a9018c07834025235c7516f9d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 06:52 UTC, rolyon commented
Hi @FaithOmbongi 
Can you review changes?
thanks

2022-06-07 15:53 UTC, FaithOmbongi commented on api-reference/beta/resources/group.md
> +| isManagementRestricted         | Boolean                                                                  | Indicates whether the group is a member of a restricted management administrative unit, i
SUGGESTION: Global for other resources that have this property - I got from Kamran's response that the AU isn't restricted - but it's management of the members of the AU that's restricted.
```suggestion
| isManagementRestricted         | Boolean                                                                  | Indicates whether the group is a member of a restricted management administrative unit, in which case it requires a role scoped to the administrative unit to manage. Default value is `false`. Read-only.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
```

2022-06-07 16:47 UTC, FaithOmbongi approved these changes
Hi @rolyon - I've left suggestions for minor fixes like using the proper property name casing + updates to the permissions descriptions. Otherwise, approved with suggestions.

2022-06-07 16:47 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +| _Directory.Write.Restricted_ |Manage all restricted resources  | Allows an app to manage restricted resources as per existing permissions of the app, on behalf of the signed-in user. | Yes | No |
Align these with the official description that's surfaced to devs and admins.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/14026935/172428140-f572f915-9a69-4523-a6a6-002561c4a302.png">

```suggestion
| _Directory.Write.Restricted_ |Manage restricted resources in the directory  | Allows the app to manage restricted resources based on the other permissions granted to the app, on behalf of the signed-in user. | Yes | No |
```

2022-06-07 16:47 UTC, FaithOmbongi commented on concepts/permissions-reference.md
> +| _Directory.Write.Restricted_ |Manage all restricted resources  | Allows an app to manage restricted resources as per existing permissions of the app, without a signed-in user. | Yes |
```suggestion
| _Directory.Write.Restricted_ |Manage restricted resources in the directory  | Allows the app to manage restricted resources based on the other permissions granted to the app, without a signed-in user. | Yes |
```

2022-06-08 19:49 UTC, KaTabish commented on api-reference/beta/resources/group.md
> +| isManagementRestricted         | Boolean                                                                  | Indicates whether the group is a member of a restricted management administrative unit, i
That's correct, but I think Robert has used "restricted" to refer to the type of AU (as the role has to be scoped to the RMAU and not just any AU).
Maybe reword as "in which case managing the group requires a role scoped to the restricted management admin unit"

2022-06-18 00:22 UTC, opbld30 commented
Docs Build status updates of commit _[82e6fd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82e6fd011bd50d4a4171eda4c9f2821523eaa903)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206180020047188-16295/BuildReport?accessString=7a247d03987023b8c2bf3aa57f6ba3033cfdb4c9ef156c4557ad321fab49c365).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-18 00:30 UTC, opbld32 commented
Docs Build status updates of commit _[2aac913](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2aac913a68624080c1a4b4af4da7755cc0c5affd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206180028195450-16295/BuildReport?accessString=1f76dbbf4ab6ecfab7256ce3b411fc2f85ebc30b0aa08ba28e3938b4e43a13d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 10:29 UTC, FaithOmbongi commented
Hi @rolyon - If there's no reason we should hold back this docs PR, please get it into a mergeable state and replace the **do not merge** with the **ready to merge** label.

2022-06-24 19:41 UTC, opbld32 commented
Docs Build status updates of commit _[aa8cdf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa8cdf9c9f4d1e6ccad1c2faf0fef45a979a832c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/administrativeunit-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/administrativeunit-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-update?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/directory-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/directory-post-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-16295) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-admin-units-restricted-management-beta/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-16295) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206241938568942-16295/BuildReport?accessString=b56232ffce77cb106f7e1ff498cf59f025c1afe1c2f77a7816220725040a0b30).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 19:44 UTC, rolyon commented
Hi @FaithOmbongi
This feature is still in progress.

2023-03-03 03:08 UTC, Lauragra commented
@rolyon , please resolve the merge conflicts before we merge this PR. I don't want to do it incorrectly. Thanks.

2023-05-25 14:15 UTC, FaithOmbongi requested changes
Hi @rolyon -

This PR has been on hold for a long while so took me a while to refresh my memory. I've reviewed it based on your last changes.

- Q: Is isManagementRestricted for devices, users, and groups also immutable? We currently indicate they are read-only.
- For group, user, and device entities, also add the properties to the "Request body" sections of the Create operations

2023-05-25 14:15 UTC, FaithOmbongi commented on api-reference/beta/api/directory-post-administrativeunits.md
>  If successful, this method returns a `201 Created` response code and an [administrativeUnit](../resources/administrativeunit.md) object in the response body.
Also update the "Request body" section above.

2023-05-25 14:15 UTC, FaithOmbongi commented on api-reference/beta/api/directory-post-administrativeunits.md
> +The following is an example creates a new administrative unit with a dynamic membership rule to include all users whose country is United States.
```suggestion
The following example creates a new administrative unit with a dynamic membership rule to include all users whose country is United States.
```

2023-05-25 14:15 UTC, FaithOmbongi commented on api-reference/beta/api/directory-post-administrativeunits.md
> +The following creates a new restricted management administrative unit. The `isMemberManagementRestricted` property is immutable, so cannot be changed later.
```suggestion
The following example creates a new restricted management administrative unit. The `isMemberManagementRestricted` property is immutable, so cannot be changed later.
```

2023-05-25 14:15 UTC, FaithOmbongi commented on api-reference/beta/api/administrativeunit-update.md
> +### Example 2: Update the display name of an administrative unit
You can update Example 1 to update both properties given they are simple types. Will save real estate space for other complex update operations in the future.

2023-05-25 22:51 UTC, rolyon commented on api-reference/beta/api/directory-post-administrativeunits.md
>  If successful, this method returns a `201 Created` response code and an [administrativeUnit](../resources/administrativeunit.md) object in the response body.
Made update. See https://github.com/microsoftgraph/microsoft-graph-docs/pull/16295/commits/9486830d99a1b2dc9a516ed1554d2550adab43b7

2023-05-25 22:59 UTC, rolyon commented
Hi @FaithOmbongi 

> * Q: Is isManagementRestricted for devices, users, and groups also immutable? We currently indicate they are read-only.
> * For group, user, and device entities, also add the properties to the "Request body" sections of the Create operations

* Checked with PM. Not immutable and can be changed.
* For Create operations, you can't set property with API, but property gets set when member is added.

2023-05-26 07:09 UTC, FaithOmbongi commented
> Hi @FaithOmbongi
> 
> > * Q: Is isManagementRestricted for devices, users, and groups also immutable? We currently indicate they are read-only.
> > * For group, user, and device entities, also add the properties to the "Request body" sections of the Create operations
> 
> * Checked with PM. Not immutable and can be changed.
> * For Create operations, you can't set property with API, but property gets set when member is added.

Ah, gotcha. Thanks for the clarification @rolyon

2023-05-26 07:10 UTC, FaithOmbongi approved these changes
LGTM, approved!

2023-06-10 00:24 UTC, merged