Add Alert related docs
microsoftgraph/microsoft-graph-docs pull request #16334
Opened 2022-03-29 07:46 UTC by zhishending

2022-03-29 07:50 UTC, opbld34 commented
Docs Build status updates of commit _[d5b692f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5b692f0f1bf753d0370bdf7379b4bdb407b9e3b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-c7e1f91ed1b460cc75d8748b82c62292-33a89ac2)
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-55adb0b664b9c178fca607b69dc14c14-33a89ac2)
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-ccc2126ad90418e93d33a913f524e202-33a89ac2)
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-118cc83728a4e79e33301e5263dfc0f1-33a89ac2)
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-ac5be392eb916259e24153bea5b20035-33a89ac2)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |

<a id="c7e1f91ed1b460cc75d8748b82c62292-33a89ac2"></a>
### [api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md)
 - **Line 48, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/alertrecord.md'.`````

<a id="55adb0b664b9c178fca607b69dc14c14-33a89ac2"></a>
### [api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md)
 - **Line 48, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/alertrule.md'.`````

<a id="ccc2126ad90418e93d33a913f524e202-33a89ac2"></a>
### [api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md)
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/devicemanagement-monitoring-post-alertrecords.md'.`````
 - **Lin [...]

2022-03-29 08:12 UTC, RuiHou105 requested changes
@zhishending  could you please 
1.update the changelog file
2.follow this [guidance ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211772/Content-review-process-summary)to create a roadmap work item and attach it in the PR description. Here is an [example](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/11551/).

2022-03-29 08:28 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +|alertRuleTemplate|alertRuleTemplate|The rule template of the alert event.The possible values are: `cloudPcProvisionScenario`, `cloudPcImageUploadScenario`, `cloudPcOnPremiseNetworkConnectionCheckSce
The type for property `alertRuleTemplate `is an enum, so please also show the enum alertRuleTemplate. You can refer to this [example ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/15416/files#diff-4c47ba8875401e7419e011f294b6a03fcdb96833252320b84209a29ec58a30f6), cloudpcsnapshot.md file line 34.

2022-03-29 08:31 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +|severity|ruleSeverityType|The severity of the alert event. Possible values are informational, warning, critical, unknown and unknownFutureValue. The possible values are: `unknown`, `informational`,
Same with alertRuleTemplate

2022-03-29 08:49 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +|status|alertStatusType|The status of the alert record. Possible values are: active, resolved and unknownFutureValue .The possible values are: `active`, `resolved`, `unknownFutureValue`.|
add the alertStatusType enum, following the example in previous comment.

2022-03-29 08:59 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-alertrule.md
> +|alertRuleTemplate|alertRuleTemplate|The rule template of the rule.The possible values are: `cloudPcProvisionScenario`, `cloudPcImageUploadScenario`, `cloudPcOnPremiseNetworkConnectionCheckScenario`,
alertRuleTemplate is an enum. Please add the enumeration down below.

2022-03-29 09:40 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-rulethreshold.md
> +|operator|operatorType|Indicates the built-in operator. The possible values are: `greaterOrEqual`, `equal`, `greater`, `less`, `lessOrEqual`, `notEqual`, `unknownFutureValue`.|
Please add aggregationType enum and operatorType enum.

2022-03-29 09:41 UTC, RuiHou105 commented on api-reference/beta/api/devicemanagement-alertrecord-get.md
> +>**Note:** The response object shown here might be shortened for readability.
As you already showed the response object, you can remove this extra note in all files.

2022-03-29 09:44 UTC, RuiHou105 commented on api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
> +      "@odata.type": "microsoft.graph.deviceManagement.portalNotification"
Could you please add detailed response here?

2022-03-29 09:46 UTC, RuiHou105 commented on api-reference/beta/api/devicemanagement-alertrule-update.md
> +Content-length: 457
Why?

2022-03-29 09:51 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-alertrule.md
> +**TODO: Add Description**
Updated in new commit.

2022-03-29 09:51 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +|alertRuleTemplate|alertRuleTemplate|The rule template of the alert event.The possible values are: `cloudPcProvisionScenario`, `cloudPcImageUploadScenario`, `cloudPcOnPremiseNetworkConnectionCheckSce
Thanks for this information. Updated all enums in this PR.

2022-03-29 09:52 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +|severity|ruleSeverityType|The severity of the alert event. Possible values are informational, warning, critical, unknown and unknownFutureValue. The possible values are: `unknown`, `informational`,
Updated.

2022-03-29 09:52 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +|status|alertStatusType|The status of the alert record. Possible values are: active, resolved and unknownFutureValue .The possible values are: `active`, `resolved`, `unknownFutureValue`.|
Updated.

2022-03-29 09:52 UTC, opbld30 commented
Docs Build status updates of commit _[725c8ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/725c8ec2112665af124b24b7a13b0bda2add474f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-118cc83728a4e79e33301e5263dfc0f1-412fb3ec)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-monitoring-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |

<a id="118cc83728a4e79e33301e5263dfc0f1-412fb3ec"></a>
### [api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/devicemanagement-monitoring-post-alertrules.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203290950519186-16334%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T09%3A52%3A57Z&sr=b&sp=r&sig=DO44mHnCzBu6c1%2BaIAA6nmLnbU6pUj9MAc0ozXUkm14%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or exte [...]

2022-03-30 08:13 UTC, opbld34 commented
Docs Build status updates of commit _[046ef73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/046ef734ce709bf39f0df8f570294d2e00552e52)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-118cc83728a4e79e33301e5263dfc0f1-d09f08b9)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-monitoring-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="118cc83728a4e79e33301e5263dfc0f1-d09f08b9"></a>
### [api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/devicemanagement-monitoring-post-alertrules.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203300809503345-16334%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T08%3A13%3A16Z&sr=b&sp=r&sig=NDmTqV93w3UOFiMzBBa7iyvDIlr%2FB5CYYpwQLDRN9WE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-u [...]

2022-03-30 09:04 UTC, zhishending commented on api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
> +      "@odata.type": "microsoft.graph.deviceManagement.portalNotification"
The response contains an array of portalNotification objects. I think this is accurate. The details of microsoft.graph.deviceManagement.portalNotification is included in resource files. Could you please elabrate what we need to add here?

2022-03-30 09:06 UTC, zhishending commented on api-reference/beta/api/devicemanagement-alertrule-update.md
> +Content-length: 457
Deleted content length. Not sure why it was auto generated. Thanks for catching this.

2022-03-30 09:07 UTC, zhishending commented on api-reference/beta/api/devicemanagement-alertrecord-get.md
> +>**Note:** The response object shown here might be shortened for readability.
Deleted all notes from API files.

2022-03-30 09:09 UTC, opbld34 commented
Docs Build status updates of commit _[2080b83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2080b83ca27de06c5eb0ae1761d73bd6752b062b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-118cc83728a4e79e33301e5263dfc0f1-b33886fc)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-monitoring-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="118cc83728a4e79e33301e5263dfc0f1-b33886fc"></a>
### [api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/devicemanagement-monitoring-post-alertrules.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203300906189743-16334%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T09%3A09%3A31Z&sr=b&sp=r&sig=72EVMlMuUcgJ7HMawLhtTHeZS1UTXIryNRy%2FD4gX6e0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-u [...]

2022-03-30 10:16 UTC, opbld32 commented
Docs Build status updates of commit _[2e27413](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e2741330fb0aefe7f34e6c744112028742005fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-118cc83728a4e79e33301e5263dfc0f1-eb3d7d61)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-monitoring-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="118cc83728a4e79e33301e5263dfc0f1-eb3d7d61"></a>
### [api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md)
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/devicemanagement-monitoring-post-alertrules.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca [...]

2022-03-31 03:40 UTC, opbld32 commented
Docs Build status updates of commit _[02e15aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02e15aad6fd8fc58d17415a4a2ee5e08eee0ac16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-monitoring-geteffectivepermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-monitoring-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203310338524774-16334%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T03%3A40%3A43Z&sr=b&sp=r&sig=J%2Be7%2F4WtW9YY%2FDxQ4YSwlR6XGaXozUkzf%2FbhaZPVTBo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-u [...]

2022-03-31 05:47 UTC, AshleyYangSZ requested changes

2022-03-31 05:47 UTC, AshleyYangSZ commented on api-reference/beta/api/devicemanagement-alertrecord-get.md
> +|Delegated (work or school account)|CloudPC.ReadWrite.All|
Should be like this CloudPC.Read.All, CloudPC.ReadWrite.All

2022-03-31 05:47 UTC, AshleyYangSZ commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +
Remove this.

2022-03-31 06:29 UTC, zhishending commented on api-reference/beta/api/devicemanagement-alertrecord-get.md
> +|Delegated (work or school account)|CloudPC.ReadWrite.All|
Updated in new commit.

2022-03-31 06:29 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +
Removed in new commit.

2022-03-31 06:29 UTC, opbld32 commented
Docs Build status updates of commit _[0437287](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0437287631c946bf43ccea3ded64782c3f3784d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203310627426674-16334%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T06%3A29%3A34Z&sr=b&sp=r&sig=OPCjjbr7hKPGFi5eUeuLEjA%2FPI%2FiPmtp95CE0YGpLMA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-11 07:49 UTC, opbld32 commented
Docs Build status updates of commit _[3479248](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34792484806fed1cf2b17160664fcb1e46c60982)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0ba6d1a6)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-0ba6d1a6"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml)
 - **Line 10305, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/devicemanagement-alertrecord'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204110747404100-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T07%3A49%3A43Z&sr=b&sp=r&sig=fmNpw1LfB9Grc4htIHDooyNJzGT96d2Hm5MBTYH7jgE%3D).

If you see b [...]

2022-04-11 08:43 UTC, opbld34 commented
Docs Build status updates of commit _[f104190](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f104190f5415f8e43f3a55c8ffa6a734fbe56913)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204110841213299-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T08%3A43%3A23Z&sr=b&sp=r&sig=6ijqYpNs8Jz3w7ymFzcbseRGuisLAmu7D0BpwkP3EeM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3 [...]

2022-04-11 09:42 UTC, opbld31 commented
Docs Build status updates of commit _[f761885](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f761885377feadf05c5c2685d5102908ac5a93d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204110941580415-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-12T09%3A42%3A33Z&sr=b&sp=r&sig=mus%2BPE%2BgyjoTTin88AcIFnkIJbDBPp4c7Smin0435EQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 06:49 UTC, opbld34 commented
Docs Build status updates of commit _[20e9eec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20e9eecf77f709f47c8b38b94028541c6d183b1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) | [Details](#user-content-ccc2126ad90418e93d33a913f524e202-4788ff67)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="ccc2126ad90418e93d33a913f524e202-4788ff67"></a>
### [api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md)
 - **Line 39, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#ruleSeverityType-values' in 'beta/resources/devicemanagement-alertrule.md', did you mean '#ruleseveritytype-values'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204120645562617-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T06%3A49%3A30Z&sr=b&sp=r&sig=g4ZiGttUT5giNE1tPim3myMdkSGfm [...]

2022-04-13 09:16 UTC, opbld30 commented
Docs Build status updates of commit _[653bde9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/653bde9986dd82da32e06b8cebd898324c479061)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204130913546953-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T09%3A16%3A55Z&sr=b&sp=r&sig=o5jd30M2zN%2BisWZzmbny4myhdJdGvhQCHm07j8ge2eA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19 [...]

2022-04-13 09:55 UTC, opbld33 commented
Docs Build status updates of commit _[667328e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/667328ecd30a14e63d0cc840627462a8989ac450)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204130952296894-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T09%3A55%3A43Z&sr=b&sp=r&sig=7WgI19CIyX6Z8f16G7obmbtWU0g%2Bzeri5O3HX%2FISrYQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/ [...]

2022-04-14 05:41 UTC, AshleyYangSZ commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +Inherits from [entity](../resources/entity.md).
Please remove this line.

2022-04-14 06:33 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +          - name: Set portal notification as sent
Missed href of this action.

2022-04-14 06:34 UTC, AshleyYangSZ commented on api-reference/beta/resources/devicemanagement-alertrule.md
> +Inherits from [entity](../resources/entity.md).
No need for this line.

2022-04-14 06:36 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Alert impact
What's your consideration of put these enum resources link here?

2022-04-14 06:37 UTC, AshleyYangSZ commented on changelog/Microsoft.DeviceManagement.Monitoring.json
> +            "Description": "Added the [deviceManagement](https://docs.microsoft.com/en-us/graph/api/resources/deviceManagement?view=graph-rest-beta) resource",
This changelog item seems not need.

2022-04-14 06:41 UTC, AshleyYangSZ commented on changelog/Microsoft.DeviceManagement.Monitoring.json
> +            "Target": "getEffectivePermissions"
We don't have this API currently. Could u help remove this?

2022-04-14 07:18 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +Inherits from [entity](../resources/entity.md).
Thanks for the great comments! Updated files according to all comments in new commit.

2022-04-14 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[e45a0a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e45a0a91972a28339e18d128aada1a63dcfad151)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204140718046411-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T07%3A20%3A30Z&sr=b&sp=r&sig=CAk6EDn%2FpvO8pLo7pL6bAGxBU9afGneiFfEFsce7A5U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19 [...]

2022-04-14 09:54 UTC, AshleyYangSZ approved these changes

2022-04-15 03:28 UTC, RuiHou105 commented on api-reference/beta/toc.yml
> +        - name: Alert recrod
typo: recrod -> record

2022-04-15 03:33 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-rulethreshold.md
> +<!--
Remove this unused part?

2022-04-15 03:38 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-notificationchannel.md
> +-->
Remove the unused part?

2022-04-15 03:45 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-alertrule.md
> +-->
Unused part?

2022-04-15 03:57 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-alertrecord.md
> +-->
What's this block line 79-84 used for?

2022-04-15 03:59 UTC, RuiHou105 requested changes
I left some minor comments. Please help resolve them. After this, you can add "Ready for content review " tag to trigger the review process.

2022-04-15 05:14 UTC, zhishending commented on api-reference/beta/toc.yml
> +        - name: Alert recrod
Nice catch! Fixed in new commit.

2022-04-15 05:16 UTC, opbld30 commented
Docs Build status updates of commit _[6667a92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6667a9220ba1dfb0b7c20cf771c2192910842a7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-16334) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertRelatedGraphDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204150514226556-16334%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T05%3A16%3A13Z&sr=b&sp=r&sig=2us7ClKVIGDF17ltDvHauHMwsnpzS1J4SDUc18BoSOM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3 [...]

2022-04-15 05:23 UTC, RuiHou105 approved these changes

2022-07-26 15:01 UTC, closed without merging