Enabling Expand Query Option for Channel List Message API
microsoftgraph/microsoft-graph-docs pull request #16350
Opened 2022-03-30 18:14 UTC by evanypark

2022-03-30 18:15 UTC, opbld33 commented
Docs Build status updates of commit _[0841abe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0841abe4593cc39ca89bf525652c2d951b0815f1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-b706ec16)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-b706ec16)

<a id="8525cd0db4658bc30812e0f65138efa3-b706ec16"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 297, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md'.`````
 - **Line 301, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md'.`````
 - **Line 305, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-2-java-snippets.md'.`````
 - **Line 288, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-b706ec16"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301814187934-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T18%3A15%3A51Z&sr=b&sp=r&sig=KEyeanA98HXuS5VgQgNPdlJLG139E38luZkdkpLJqd8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 18:19 UTC, opbld33 commented
Docs Build status updates of commit _[0ee33a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ee33a1031e9489fad9c63c1080790a989d63c99)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-e108c3bb)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-e108c3bb)

<a id="8525cd0db4658bc30812e0f65138efa3-e108c3bb"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 297, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md'.`````
 - **Line 301, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md'.`````
 - **Line 305, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-2-java-snippets.md'.`````
 - **Line 288, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-e108c3bb"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301817322627-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T18%3A19%3A10Z&sr=b&sp=r&sig=4HBGSj5gEnbT6d7UX2I2XnNN2gUKaT2Qy8ZbMF7Lg4g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 23:32 UTC, opbld32 commented
Docs Build status updates of commit _[cc33da5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc33da5c0f7aa49493fee60197bcfe6255b6cfec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-ac50e368)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-ac50e368"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012330329084-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T23%3A32%3A38Z&sr=b&sp=r&sig=qXaG15M%2FsfdxjA3mZZldWE1PLWvYP2%2B82dvKhXUWYQs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 23:56 UTC, opbld33 commented
Docs Build status updates of commit _[a600b48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a600b48593df7ec9ba05f95b51f61e422fb40f8a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-6eb37f68)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-6eb37f68)

<a id="8525cd0db4658bc30812e0f65138efa3-6eb37f68"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 298, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md'.`````
 - **Line 302, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md'.`````
 - **Line 306, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-2-java-snippets.md'.`````
 - **Line 289, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-6eb37f68"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012354037486-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T23%3A56%3A13Z&sr=b&sp=r&sig=8XiA6j3vLA9WWcBrZQJWqk9S0%2ByqfenT%2FLRMrxU2LKU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:06 UTC, opbld32 commented
Docs Build status updates of commit _[aefc039](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aefc0397628fa5090f212408639bf0e7a518c7a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-52df9787)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-52df9787)
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-listchannelmessages-2-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/includes/snippets/java/get-listchannelmessages-2-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-listchannelmessages-3-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/includes/snippets/csharp/get-listchannelmessages-3-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-listchannelmessages-3-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/includes/snippets/java/get-listchannelmessages-3-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-listchannelmessages-3-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/includes/snippets/javascript/get-listchannelmessages-3-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |

<a id="8525cd0db4658bc30812e0f65138efa3-52df9787"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 289, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-52df9787"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204020004087919-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-03T00%3A06%3A06Z&sr=b&sp=r&sig=yy1mWkn7IcNk2JmzFgKmK4U%2BXjmaHdhpWHv9lkWgAZ4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:14 UTC, opbld30 commented
Docs Build status updates of commit _[3573a5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3573a5bdfacbaaca9b0f5daf21314345780f6e22)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-6fbb8536)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-6fbb8536)
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/get-listchannelmessages-2-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/includes/snippets/java/get-listchannelmessages-2-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-listchannelmessages-3-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/includes/snippets/csharp/get-listchannelmessages-3-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-listchannelmessages-3-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/includes/snippets/java/get-listchannelmessages-3-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-listchannelmessages-3-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/includes/snippets/javascript/get-listchannelmessages-3-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="8525cd0db4658bc30812e0f65138efa3-6fbb8536"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 289, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-6fbb8536"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204020012477439-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-03T00%3A14%3A46Z&sr=b&sp=r&sig=dRJgrz%2F7lGJE1wEklEpRWJNqesrU3Inrk3HdExmhqT4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 03:05 UTC, RamjotSingh approved these changes

2022-04-05 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[418cd8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/418cd8cd73dbbfdff44715298b04df447e1067d4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-56970a1e)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-56970a1e)

<a id="8525cd0db4658bc30812e0f65138efa3-56970a1e"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 298, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md'.`````
 - **Line 302, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md'.`````
 - **Line 306, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-2-java-snippets.md'.`````
 - **Line 289, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-56970a1e"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 475, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-3-csharp-snippets.md'.`````
 - **Line 479, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-3-javascript-snippets.md'.`````
 - **Line 483, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-3-java-snippets.md'.`````
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204051828552053-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T18%3A31%3A08Z&sr=b&sp=r&sig=VAPSICEKeQNl772Y17jJ74mnbROCfVYCAtTuAFEbvaA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 19:10 UTC, opbld30 commented
Docs Build status updates of commit _[e2dab9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2dab9de29ece21591e8e7cbfc0b56bae5dbdf16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-80732250)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-80732250)
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="8525cd0db4658bc30812e0f65138efa3-80732250"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 289, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-80732250"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 466, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204051908284249-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T19%3A10%3A41Z&sr=b&sp=r&sig=rwlNDbTe2WCQgbqBjWS1w%2FCwCHxaKLF%2F0OJHpD%2FGG0g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 19:52 UTC, isvargasmsft commented on api-reference/beta/api/channel-list-messages.md
>  ## Example
Line 71: please revise to Examples, in plural.

2022-04-06 19:53 UTC, isvargasmsft commented on api-reference/beta/api/channel-list-messages.md
> +# [HTTP](#tab/http)
Line 289: please remove this line. Tabs are automatically generated.

2022-04-06 19:54 UTC, isvargasmsft commented on api-reference/beta/api/channel-list-messages.md
> +```msgraph-interactive
Line 294: Please replace `msgraph-interactive` with `http`. These tabs are automatically generated.

2022-04-06 19:59 UTC, isvargasmsft commented on api-reference/beta/api/chatmessage-delta.md
> +> **Note:** For `$expand` query parameter, please refer to example 3 in [GET /teams/{team-id}/channels/{channel-id}/messages](channel-list-messages.md).
Line 75: please revise for simplicity to: "... please refer to [List channel messages] (insert here the link with # to example 3)

Is it example 3 or 2?

2022-04-06 20:01 UTC, isvargasmsft commented on api-reference/v1.0/api/channel-list-messages.md
> +### Example 3: Request with expand query option on replies
Why isn't example 2 of this topic reflected in the beta topic as well?

2022-04-06 20:02 UTC, isvargasmsft commented on api-reference/beta/api/channel-list-messages.md
> +# [HTTP](#tab/http)
Please apply to the v1 topic as well.

2022-04-06 20:02 UTC, isvargasmsft commented on api-reference/beta/api/channel-list-messages.md
> +```msgraph-interactive
Please apply to the v1 topic as well.

2022-04-06 20:02 UTC, isvargasmsft commented on api-reference/beta/api/chatmessage-delta.md
> +> **Note:** For `$expand` query parameter, please refer to example 3 in [GET /teams/{team-id}/channels/{channel-id}/messages](channel-list-messages.md).
Please apply to the v1 topic as well.

2022-04-06 20:16 UTC, isvargasmsft requested changes
Hello @evanypark, 

Thank you very much for your work in this PR. 

Please take a look at a few comments regarding consistency and simplicity. Please apply the comments to both beta and v1 files. 

Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac

2022-04-07 06:10 UTC, evanypark commented on api-reference/beta/api/chatmessage-delta.md
> +> **Note:** For `$expand` query parameter, please refer to example 3 in [GET /teams/{team-id}/channels/{channel-id}/messages](channel-list-messages.md).
@isvargasmsft What would the link look like for a section inside external file?

2022-04-07 06:10 UTC, evanypark commented on api-reference/v1.0/api/channel-list-messages.md
> +### Example 3: Request with expand query option on replies
was probably left out , adding to beta

2022-04-07 06:18 UTC, opbld31 commented
Docs Build status updates of commit _[0e6c2ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e6c2ec87456c1592099593f2f333d886cb765a9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-79be978f)
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :warning:Warning | | [Details](#user-content-52bea74b54c19ddfdbdd45afcfd2c831-79be978f)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-79be978f)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :warning:Warning | | [Details](#user-content-e54ac4fbc637933f5a76ace9fc71faab-79be978f)

<a id="8525cd0db4658bc30812e0f65138efa3-79be978f"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 301, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md'.`````
 - **Line 305, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md'.`````
 - **Line 309, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-2-java-snippets.md'.`````
 - **Line 290, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 477, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="52bea74b54c19ddfdbdd45afcfd2c831-79be978f"></a>
### [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md)
 - **Line 75, Column 60**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Example-3:-Request-with-expand-query-option-on-replies' in 'beta/api/channel-list-messages.md', did you mean '#example-3-request-with-expand-query-option-on-replies'?`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-79be978f"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 464, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e54ac4fbc637933f5a76ace9fc71faab-79be978f"></a>
### [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md)
 - **Line 74, Column 60**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Example-3:-Request-with-expand-query-option-on-replies' in 'v1.0/api/channel-list-messages.md', did you mean '#example-3-request-with-expand-query-option-on-replies'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204070616214717-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T06%3A18%3A15Z&sr=b&sp=r&sig=ORucjN%2FEBRp5SBZKrnvitfx1VV4jX2g%2B03MboaiGet4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 18:55 UTC, opbld33 commented
Docs Build status updates of commit _[41bb138](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41bb13849facec57a280387198af0576afdd59e8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :x:Error | | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-4836d4a5)
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :warning:Warning | | [Details](#user-content-52bea74b54c19ddfdbdd45afcfd2c831-4836d4a5)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-4836d4a5)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :warning:Warning | | [Details](#user-content-e54ac4fbc637933f5a76ace9fc71faab-4836d4a5)

<a id="8525cd0db4658bc30812e0f65138efa3-4836d4a5"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 301, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-listchannelmessages-2-csharp-snippets.md'.`````
 - **Line 305, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-listchannelmessages-2-javascript-snippets.md'.`````
 - **Line 309, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-listchannelmessages-2-java-snippets.md'.`````
 - **Line 290, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 477, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="52bea74b54c19ddfdbdd45afcfd2c831-4836d4a5"></a>
### [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md)
 - **Line 75, Column 60**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Example-3:-Request-with-expand-query-option-on-replies' in 'beta/api/channel-list-messages.md', did you mean '#example-3-request-with-expand-query-option-on-replies'?`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-4836d4a5"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 464, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e54ac4fbc637933f5a76ace9fc71faab-4836d4a5"></a>
### [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md)
 - **Line 74, Column 60**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Example-3:-Request-with-expand-query-option-on-replies' in 'v1.0/api/channel-list-messages.md', did you mean '#example-3-request-with-expand-query-option-on-replies'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204071853225849-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T18%3A55%3A25Z&sr=b&sp=r&sig=z3xW4C%2FF3HrNCQUW7TqTgEC9H6aymMrJ2qDB1gSkpL8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 19:14 UTC, opbld33 commented
Docs Build status updates of commit _[57adc81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57adc81f0277cf6b1bc5d04b9a8a89ed5d9fc28a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-24681ec3)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-24681ec3)
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="8525cd0db4658bc30812e0f65138efa3-24681ec3"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md)
 - **Line 290, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````
 - **Line 290, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-24681ec3"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 464, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204071913003672-16350%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T19%3A14%3A53Z&sr=b&sp=r&sig=Un5G8cQubGzPcCJMRU7d%2BvugVsk8NN23Vi%2FGbHzzJ%2Fw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 16:16 UTC, opbld30 commented
Docs Build status updates of commit _[49de0ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49de0ad1d2e5106543c9738629eb904c6ec1076a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-bdd73646)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-bdd73646"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 464, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081612585784-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T16%3A16%3A31Z&sr=b&sp=r&sig=ZGxTR2p27eFMbXjc3C8T1GkY6Ys%2FciecY4q4NYTNYHw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 17:49 UTC, opbld34 commented
Docs Build status updates of commit _[44c72d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44c72d95b392a5b160e77258d9b5303fa97e547e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-79d79dad)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-79d79dad"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081746074807-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T17%3A49%3A38Z&sr=b&sp=r&sig=kSApCfbA0MUCXT1Yk9ZsLtiYCvkaJ6LuKalrWzqh8JA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 19:09 UTC, opbld30 commented
Docs Build status updates of commit _[3ab94c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ab94c796fa4156735246dd009cf87cad87f779b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-5794bae6)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-5794bae6"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081906143472-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T19%3A09%3A28Z&sr=b&sp=r&sig=NmCYZxqh02O2jxQPTP00RoAmqtJjSPp1UWDs5bZBNkE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 19:21 UTC, isvargasmsft approved these changes

2022-04-09 06:49 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "fef256b6-cd3f-4ee8-89c6-7063f7068cab",
Lines 7-11:
The ChangedApiName should be an API element in the Microsoft Graph API. In this case, the API element that's impacted by this change is the replies nav property of chatMessage, when listing channel messages that are replies.

You can specify those lines of the changelist record as follows:
ApiChange: "Relationship",
ChangedApiName: "replies",
ChangeType: "Addition",
Description: "Added support for `$expand` on the **replies** relationship when [listing channel messages](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0) that are replies.",
Target: "chatMessage"

You can take a look at example 17 in this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples

2022-04-09 06:50 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "3580c1e4-e1bb-4611-843c-42e851863c3f",
Lines 25-29:
Please see my comment for the similar update in the beta version (lines 7-11).

2022-04-09 07:06 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
> +| [$expand](/graph/query-parameters#expand)  | Currently supports **replies** only. If a channel message contains more than 1000 replies, replies@odata.nextLink will be provided for pagination.|
Line 51:
Please rephrase for clarity - use active voice to make it clearer who/what provides the nextLink and what the customer can do in that case.
For instance:
"You can apply `$expand` on only channel messages that are replies. By default, a response can include up to 1000 replies. For an operation that expands channel messages with more than 1000 replies, use the request URL returned in `replies@odata.nextLink` to get the next page of replies."

2022-04-09 07:18 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
> +| [$top](/graph/query-parameters#top-parameter)| Controls the number of items per response. Maximum allowed `$top` value is 50. |
Line 50:
Please clarify "items" and the behavior of $top.
I think "items" here means the number of channel messages returned per page?
FYI Microsoft docs use the Microsoft Voice which should be friendly, clear, and direct. Rather than just saying "this is how we designed this", in the docs, we want to phrase our descriptions as "this is what / how you can use our design to get your task done".
So I suggest you can rephrase this way please:
"Apply `$top` to specify the number of channel messages returned per page in the response. The maximum page size is 50 channel messages."

2022-04-09 07:21 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
> +| [$top](/graph/query-parameters#top-parameter)| Controls the number of items per response. Maximum allowed `$top` value is 50. |
BTW, is there a default page size? It would be helpful to state it here, because specifying `$top` should be optional.

2022-04-09 07:26 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
This comment applies to how in general, you should please document support for a query parameter - in addition to documenting the support in the related operation topics like this one, you should update the description of the property or nav property in the parent resource topic. 
In this case for $expand, please update the description for the replies nav property in the chatmessage.md topic and add a separate sentence like "Supports `$expand`."
Take a look at the descriptions in the "Relationships" section of user.md.

2022-04-09 07:35 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
> +            "replies@odata.nextLink": "https://graph.microsoft.com/v1.0/teams/fbe2bf47-16c8-47cf-b4a5-4b9b187c508b/channels/19:4a95f7d8db4c4e7fae857bcebe0623e6@thread.tacv2/messages/1616963377068/rep
Line 525:
Can you confirm if this nextLink line should be there?
Your line 51 in the same topic says:
"If a channel message contains more than 1000 replies, replies@odata.nextLink will be provided for pagination."

Here, the example response includes so far 3 replies. Where does the example request specify some page size for the number of replies per page?

2022-04-09 07:40 UTC, angelgolfer-ms requested changes
Hi @evanypark ,
@isvargasmsft requested me to clarify how to specify the changelog for the updates in this PR. I took a quick look at what your PR does, and added a few other comments as well. Please take a look. Please apply the same comments to both v1 and beta versions of your updates.
And to clarify, @isvargasmsft is the reviewer to cover the entire PR.

2022-04-11 18:41 UTC, evanypark commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "fef256b6-cd3f-4ee8-89c6-7063f7068cab",
shouldn't the target be channelMessage?

2022-04-11 18:45 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
> +| [$top](/graph/query-parameters#top-parameter)| Controls the number of items per response. Maximum allowed `$top` value is 50. |
Default is set to 20 for channel messages

2022-04-11 18:49 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
I think that might be misleading.
Expand is only available when applied on replies property for GET channel messages API. 
It isn't enabled anywhere else

2022-04-11 18:50 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
> +            "replies@odata.nextLink": "https://graph.microsoft.com/v1.0/teams/fbe2bf47-16c8-47cf-b4a5-4b9b187c508b/channels/19:4a95f7d8db4c4e7fae857bcebe0623e6@thread.tacv2/messages/1616963377068/rep
Correct, the actual response shouldn't contain next link unless it has more than 1000 replies, but I wanted to still provide an example with nextlink, even if the replies count was less than that. 
Any idea on how I should do that?

2022-04-11 19:43 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
I've added "Supports $expand for channel messages"

2022-04-11 19:43 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
> +| [$top](/graph/query-parameters#top-parameter)| Controls the number of items per response. Maximum allowed `$top` value is 50. |
Added line saying default is set to 20

2022-04-11 19:43 UTC, opbld31 commented
Docs Build status updates of commit _[34afb0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34afb0b398efc090e5728aa4f5e484b548618a20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-1ea04686)
[concepts/bookingsbusiness-business-rules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/concepts/bookingsbusiness-business-rules.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/bookingsbusiness-business-rules?branch=pr-en-us-16350) | [Details](#user-content-4d213286934f78bf1f900c62c288365d-1ea04686)
[.openpublishing.publish.config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/api/bookingappointment-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingappointment-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-cancel?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingappointment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingappointment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-update?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-delete?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-getstaffavailability.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-getstaffavailability.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-getstaffavailability?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingcustomer-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomer-delete?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingcustomer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomer-get?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingcustomer-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomer-update?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/bookingservice- [...]

2022-04-13 23:13 UTC, opbld32 commented
Docs Build status updates of commit _[5adc05b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5adc05b52ee5ac420a68c2b9a2e6140aa37b2263)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-353c9a1a)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-353c9a1a"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204132311363067-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T23%3A13%3A44Z&sr=b&sp=r&sig=2qdfN4uAoSQzBSMFA%2FhGopAgQ0tk44d0EiFTK8Aidb8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 23:40 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
Yes, that's right, specific to this PR and the current support for $expand, we should point out the support is only for channel messages.

2022-04-14 01:25 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
> +            "replies@odata.nextLink": "https://graph.microsoft.com/v1.0/teams/fbe2bf47-16c8-47cf-b4a5-4b9b187c508b/channels/19:4a95f7d8db4c4e7fae857bcebe0623e6@thread.tacv2/messages/1616963377068/rep
I see. For example 3, I updated the descriptions in the "Request" and "Response" sub-sections. I also updated the request URL to include $top for the # of channel messages (of 1).
I made the similar updates in both the beta and v1 versions of the example.
Please take a look at my (upcoming) commit. If you see anything I overlooked, please let me know.

2022-04-14 01:42 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "fef256b6-cd3f-4ee8-89c6-7063f7068cab",
No, the Target and ChangedApiName properties should be names of API elements defined in the Microsoft Graph API. You can see in the changelog CDK topic (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog) for the kinds of API elements that you can assign to each of these properties.

In this case, we're adding further capability (being able to expand the properties of chatMessage resources) to chatMessage resources that are accessible through the replies navigation property of a channel message. So the ApiChange is "Relationship", the ChangedApiName is the name of that relationship "replies", and Target is the parent resource of the replies nav property "chatMessage". 

These properties in the changelist record JSON were not designed to sufficiently define every type of change that can happen to the APIs. In your case, you need to further describe the support as currently applicable to only chatMessage resources that are replies to channel messages.

2022-04-14 01:46 UTC, angelgolfer-ms requested changes
Hi @evanypark , thanks for incorporating some feedback from the last round.
I responded to some of your comments and questions. I also updated the descriptions of example 3 directly in this PR. Please take a look.

2022-04-14 03:23 UTC, opbld30 commented
Docs Build status updates of commit _[d49f844](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d49f844ea048c8ed79399ef1caede22ab2915dd4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-b4e7cdfa)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-b4e7cdfa"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204140321574439-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T03%3A23%3A53Z&sr=b&sp=r&sig=cg%2BH6KVNjEB2kUzfyOB2JHQS0drp3sQOtKaOJ4c8prc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 03:25 UTC, opbld31 commented
Docs Build status updates of commit _[319b573](https://github.com/microsoftgraph/microsoft-graph-docs/commits/319b573b1d6434b9cf8338e806d565a2fbe340a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-b8f9d8a4)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-b8f9d8a4"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204140322237982-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T03%3A25%3A52Z&sr=b&sp=r&sig=WZM6qFhtbXlf4JfHkYcig8PeX50ptd9DAFfO0C47QYM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 03:26 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
>  The following is an example of the request.
@angelgolfer-ms, Not necessarily, if there are only 3 messages. it will return 3 messages even without specifying $top=3.
Also, the first example was for request without optional query parameters.

For example 2 and 3 it does makes sense, so I will add them

2022-04-14 07:26 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-list-messages.md
>  The following is an example of the request.
@evanypark , then what is the @odata.nextLink for on line 131 of the response for example 1? More channel messages to return, is that right?

2022-04-14 18:33 UTC, evanypark commented on api-reference/beta/api/channel-list-messages.md
>  The following is an example of the request.
I've added $top query options to Example title.
It will match with the actual response users will be getting.

2022-04-14 18:34 UTC, evanypark commented
@angelgolfer-ms I've applied identified updates from the comments.
Let me know if you find any other changes to be need :)

2022-04-14 18:36 UTC, opbld32 commented
Docs Build status updates of commit _[5946de5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5946de5a43ca6e05f9bb881f51525ddfb27f4f6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) | [Details](#user-content-52bea74b54c19ddfdbdd45afcfd2c831-e35ebea3)
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-e35ebea3)
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-e54ac4fbc637933f5a76ace9fc71faab-e35ebea3)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="52bea74b54c19ddfdbdd45afcfd2c831-e35ebea3"></a>
### [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md)
 - **Line 75, Column 60**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-3-request-with-expand-query-option-on-replies' in 'beta/api/channel-list-messages.md'.`````

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-e35ebea3"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="e54ac4fbc637933f5a76ace9fc71faab-e35ebea3"></a>
### [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md)
 - **Line 74, Column 60**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-3-request-with-expand-query-option-on-replies' in 'v1.0/api/channel-list-messages.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204141834185398-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T18%3A36%3A21Z&sr=b&sp=r&sig=zaHoo5HekDDgnlp72fvcHRdzfueIyXS3SMvpmzsAq60%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 07:11 UTC, opbld31 commented
Docs Build status updates of commit _[c8f314c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8f314c136c6f8c8af69c242907ad1284f97f7d5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-aeac3b90)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-aeac3b90"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204150708516957-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T07%3A11%3A10Z&sr=b&sp=r&sig=3QbUIdfpuH0Bg6NgaSYoqpaDUeuij6XbX4bTpCFXJwo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 07:13 UTC, opbld30 commented
Docs Build status updates of commit _[cbe3c7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbe3c7c45884d10c003b4bdabb9ec7100b570ab6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-af7a6aef)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-af7a6aef"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204150710262826-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T07%3A13%3A06Z&sr=b&sp=r&sig=QOLT9XpDRzsiv6ev7qAUIKxRO1Zvsa5HoL2d4Dj1YWQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 07:21 UTC, angelgolfer-ms requested changes
@evanypark , thanks for incorporating the updates to the examples, per the last review iteration.
Please also update the changelog json, also per my comments in the last review iteration.
After that, I think we should be complete with content review.

2022-04-18 18:00 UTC, evanypark commented
> @evanypark , thanks for incorporating the updates to the examples, per the last review iteration.
> Please also update the changelog json, also per my comments in the last review iteration.
> After that, I think we should be complete with content review.

2022-04-18 18:01 UTC, opbld32 commented
Docs Build status updates of commit _[0f8d328](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f8d3282e7c2e37ee98dd07d76839124f5f6d5ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-af6600df)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-af6600df"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204181759302571-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T18%3A01%3A19Z&sr=b&sp=r&sig=rL70urOQT4TRGP7nXaWThqIp9wx6cYr87O6OhgmuWo8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 18:01 UTC, evanypark commented
s

2022-04-18 21:09 UTC, opbld30 commented
Docs Build status updates of commit _[e6b2f98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6b2f989d5f60a2fb38019102a41be7d4daa85ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) | [Details](#user-content-d44ce2a63d5feaf51483fb7de6f0f49f-d7772b62)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="d44ce2a63d5feaf51483fb7de6f0f49f-d7772b62"></a>
### [api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md)
 - **Line 277, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204182107062331-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T21%3A09%3A44Z&sr=b&sp=r&sig=B4RogAWAKsIsLie19Gyf0EBVc5cbmawU08bSQF9wYA0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 21:53 UTC, angelgolfer-ms commented on api-reference/v1.0/api/channel-list-messages.md
>  ## Examples
@evanypark , as I try to wrap up my part of the review so that you can publish, there's this build warning for line 277 of the v1 version of channel-list-messages.md, which is about the language-based snippets for example 2:
"Line 277, Column 1: [Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)] Tab group with different tab id set." I suspect this build warning has been around before this PR, but nonetheless, in general, we should minimize build warnings whenever we check in.

If you look at the linked docs for that warning, it seems the cause for the warning is, you have only 4 (HTTP, C#, JavaScript, and Java) languages specified for the code snippets, but example 1 has all 7, and all these "tab groups" should support the same number of languages and in the same order. Do you see a reason why for example 2, there would be problem generating code snippets for Objective-C, Go, and Powershell?

So since we're updating the request for example 2 by adding ?$top=3 (btw I am adding it on your behalf to the v1 version, you added it to the beta version but not the v1 version of examples 1 and 2), the code snippets should be regenerated anyway on the weekly update after you publish this PR. In that case, on your behalf, I am going to just delete the  lines for the language-based code snippets so to remove the build warning.

If on the other hand, there's a real reason that code snippets in Objective-C, Go, and Powershell would not work, then after publishing this PR and the code snippet generator tool inserts (non-working) code snippets for these languages for example 2, the next thing you should do is to remove the lines for the code snippets inserted for these languages, for example 2. By then, the tool will have generated the code snippets in the beta topic as well, so you'll have to delete the lines for example 2 in the beta topic too.

The CDK topic about code snippets is here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211752/Generate-code-snippets

Let me know on Teams if you have further questions on this. Meanwhile, I'm going to delete these lines in the v1 topic, wrap up my review, and approve this PR.

2022-04-18 22:46 UTC, opbld33 commented
Docs Build status updates of commit _[4aa3e45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4aa3e4567bd0069e52e536f84c41bb94a19e8ce5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204182244464945-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T22%3A46%3A22Z&sr=b&sp=r&sig=YCHavFk1QIMEzcEx%2FGRAH2WGa%2FnfyX3cK4WYfmhlVrs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 23:05 UTC, angelgolfer-ms approved these changes
@evanypark , thanks for updating the changelog JSON.
Please take a look at a comment and a commit I did today. I have approved this PR, but let me know if you have any further questions especially regarding today's comment.
Please follow step 8 in the [content workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow) to get this PR published.

2022-05-09 18:45 UTC, opbld33 commented
Docs Build status updates of commit _[3b5f293](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b5f293df9361f63fc7190da6e84303a652b2b75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091843260372-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T18%3A45%3A51Z&sr=b&sp=r&sig=lTvDOA8pAG31wGR6Xy4fMaRBt%2B7cf0PIvlf9CnuG39M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 02:46 UTC, opbld33 commented
Docs Build status updates of commit _[c1d7641](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1d764126b32a5904f7b6602ccd7754dd2cc7750)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16350) (graph-rest-beta) |
[api-reference/v1.0/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-16350) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-03-28-channelListMessagesExpand/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205100244523361-16350%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-10T02%3A46%3A36Z&sr=b&sp=r&sig=A0QNW0kvdPbn6sN1XFag1eE6bF2qyRD6SrHb8LOcbLc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 02:51 UTC, merged