Adding "emailuser" to TeamworkUserIdentity
microsoftgraph/microsoft-graph-docs pull request #16351
Opened 2022-03-30 18:58 UTC by sumanac

Adding "emailuser" to TeamworkUserIdentity

2022-03-30 19:00 UTC, opbld34 commented
Docs Build status updates of commit _[3400ead](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3400eade8606a6ed8a74db87cf56ef468345ff21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301858143549-16351%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T19%3A00%3A05Z&sr=b&sp=r&sig=1%2FqdhGQ5XH%2FKqbW7NfT77ES4Y2WDAVMEmeNSYg5Z8Vs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 19:07 UTC, sumanac commented on api-reference/beta/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
Was this property missing from beta for any reasons? I added it. I can remove it if this was intentional.

2022-03-30 19:45 UTC, AkJo commented on api-reference/beta/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
Are we not describing the meaning of these userIdentityTypes somewhere?

2022-03-30 19:45 UTC, AkJo approved these changes

2022-03-30 19:47 UTC, RamjotSingh requested changes

2022-03-30 19:47 UTC, RamjotSingh commented on api-reference/beta/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
`unknownFutureValue` was removed because beta never get it.

2022-03-31 17:31 UTC, sumanac commented on api-reference/beta/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
Removed from beta.

2022-03-31 17:32 UTC, opbld30 commented
Docs Build status updates of commit _[2d55b65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d55b6511157f6d6d681fffb6f746815baf99e9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311730344721-16351%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T17%3A32%3A42Z&sr=b&sp=r&sig=BL%2BWse9bOAyWqC2p5Tm9xM339wYF%2FxcZJY0aZbMSh8Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 19:05 UTC, RamjotSingh approved these changes

2022-04-01 20:37 UTC, opbld30 commented
Docs Build status updates of commit _[b217607](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b217607803275bd5dd378984cb826fd9b324715a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012035143298-16351%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T20%3A37%3A36Z&sr=b&sp=r&sig=rZqbdXNbezxYnh%2FDnY%2BIz32O%2BOhcToBr9iQRqB8nptM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 20:56 UTC, opbld31 commented
Docs Build status updates of commit _[f05f1e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f05f1e85a855f82c2f03e0ed5546dd22bf14c12c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012054165944-16351%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T20%3A56%3A10Z&sr=b&sp=r&sig=zuiQo0JEA7i9%2FTTNZmMfmcKDbmUmSlp0PVNJzQV%2FrxM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 20:57 UTC, opbld31 commented
Docs Build status updates of commit _[1c71c51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c71c51bd16bc0e7443b453ebd62522ee269bdb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012054589956-16351%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T20%3A57%3A53Z&sr=b&sp=r&sig=LvrpEfeoskKi49bdq3qon8YglOJgVaUh9kUQPAs3ex0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 21:01 UTC, Lauragra approved these changes

2022-04-01 21:02 UTC, opbld34 commented
Docs Build status updates of commit _[4467066](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4467066806e41db1f12d0a32aaf580236e91b12c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204012100382076-16351%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T21%3A02%3A54Z&sr=b&sp=r&sig=BcFhfGPw6h3OURBoiAOm0fMST9HkqqrIyu9yfOQ2AQ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 02:21 UTC, opbld33 commented
Docs Build status updates of commit _[30c21a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30c21a7c85f96710ff29ef4847bbb00dd35712b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-16351) (graph-rest-beta) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/api-reference/v1.0/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-1.0&branch=pr-en-us-16351) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/addemailusertoidentity/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204190219132909-16351%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T02%3A21%3A09Z&sr=b&sp=r&sig=MzLS94FLODs12mMnJQZQXRbs7Xbn9cGH6r4a%2Fe2b2xM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 02:23 UTC, merged