unified RBAC: add EM in v1.0
microsoftgraph/microsoft-graph-docs pull request #16354
Opened 2022-03-30 19:14 UTC by markwahl-msft

Currently the beta unified RBAC docs mentions directory and entitlement management as providers across all the relevant APIs.  The v1.0 mention entitlement management as an application, but not in the API calls for role definitions and role assignments.  Today those v1.0 only mention the directory provider.

2022-03-30 19:15 UTC, opbld33 commented
Docs Build status updates of commit _[8207132](https://github.com/markwahl-msft/microsoft-graph-docs/commits/8207132b0ba25ffb4b16c3ce6743832c27feeb4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301914244067-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T19%3A15%3A58Z&sr=b&sp=r&sig=wrzPwPtKeCpJp3bmg1jpCUeBM3Gmc3OenDX%2BNiKZbMs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 19:32 UTC, opbld34 commented
Docs Build status updates of commit _[c993312](https://github.com/markwahl-msft/microsoft-graph-docs/commits/c99331266fe480a4680befb9d1e2cd00cc3604c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301931035761-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T19%3A32%3A54Z&sr=b&sp=r&sig=DdfruVWZCmGbSQ3En3%2BqsmtVM1U5yQxRnQnUD6mBGJY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 09:15 UTC, FaithOmbongi requested changes
Thank you @markwahl-msft for closing this gap in the v1.0 docs. I've left a few suggestions for consideration.

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-list-roleassignments.md
> +This operation requires the `$filter` query parameter to query specific instances of role assignments. You can filter on the `roleDefinitionId` or `principalId` properties, or for the entitlement man
Is this accurate?
```suggestion
This operation requires the `$filter` query parameter to query role assignments for the supported RBAC providers.
+ For the directory provider, you must filter on either the **roleDefinitionId** or **principalId** properties. The **roleDefinitionId** property can be either a role object ID or a value for the **templateId** property.
+ For the entitlement management provider, you must filter by the **appScopeId** property. 

For general information, see [OData query parameters](/graph/query-parameters).
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-list-roleassignments.md
> +### Example 3: Request using $filter for role assignments on an access package catalog and expand principal
```suggestion
### Example 3: Request using $filter for role assignments on an access package catalog and expand the principal object
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
>  |Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All |
- I support your goal with the updated intro statement. However, for consistency right now, I suggest we maintain the current boilerplate text. There's an initiative to have a repo-wide update to this text so we can advise customers about best practices like you've intended.
- Same request about Directory.ReadWrite unless there are objections.

```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).

### For the directory (Azure AD) provider

|Permission type      | Permissions (from least to most privileged)              |
|:--------------------|:---------------------------------------------------------|
|Delegated (work or school account) | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory    |
|Delegated (personal Microsoft account) | Not supported.    |
|Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory |
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +### For the Directory (Azure AD) provider
Same comment
```suggestion

One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).

### For the directory (Azure AD) provider
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +### Example 4: Create a role assignment at access package catalog scope
```suggestion
### Example 4: Create a role assignment with access package catalog scope
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/unifiedroleassignment-delete.md
> +### For the Entitlement management provider
Same comment
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).

### For the directory (Azure AD) provider

| Permission type                        | Permissions (from least to most privileged) |
|:---------------------------------------|:--------------------------------------------|
| Delegated (work or school account)     | RoleManagement.ReadWrite.Directory |
| Delegated (personal Microsoft account) | Not supported. |
| Application                            | RoleManagement.ReadWrite.Directory |

### For the entitlement management provider
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/unifiedroleassignment-get.md
>  |Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All |
Same comment, same request
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).

### For the directory (Azure AD) provider

|Permission type      | Permissions (from least to most privileged)              |
|:--------------------|:---------------------------------------------------------|
|Delegated (work or school account) | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory   |
|Delegated (personal Microsoft account) | Not supported.    |
|Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory |
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/unifiedroledefinition-get.md
>  |Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All |
Same comment, same suggestion
```suggestion
One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).

### For the directory (Azure AD) provider

|Permission type      | Permissions (from least to most privileged)              |
|:--------------------|:---------------------------------------------------------|
|Delegated (work or school account) | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory    |
|Delegated (personal Microsoft account) | Not supported.    |
|Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory |
```

2022-03-31 09:15 UTC, FaithOmbongi commented on api-reference/v1.0/resources/entitlementmanagement-overview.md
> +In addition, role assignments for entitlement management-specific roles can be managed through entitlement management [role definitions](unifiedroledefinition.md).
```suggestion
In addition, you can manage role assignments for entitlement management-specific roles through entitlement management [role definitions](unifiedroledefinition.md).
```

2022-03-31 15:18 UTC, opbld33 commented
Docs Build status updates of commit _[f91e50c](https://github.com/markwahl-msft/microsoft-graph-docs/commits/f91e50c7d3ffcba9f05db58286ebac6e5e537e74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311516449401-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T15%3A18%3A38Z&sr=b&sp=r&sig=%2FxDhNrBarKLU5yt6SlOX8lFSrbLRi1dma1pmEgDLUhY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 15:20 UTC, opbld30 commented
Docs Build status updates of commit _[d3493d8](https://github.com/markwahl-msft/microsoft-graph-docs/commits/d3493d8db8f4443b216cfd898037bc9c3ed9b1ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311518255400-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T15%3A20%3A46Z&sr=b&sp=r&sig=taZ%2FkffJg1rjH2RtqBSC%2B%2BIgm9s3tx29DkcvAzhnhOg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 15:23 UTC, opbld34 commented
Docs Build status updates of commit _[8bf9161](https://github.com/markwahl-msft/microsoft-graph-docs/commits/8bf9161f8d91e5621d10799372b3f5fd08dbb157)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311520258898-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T15%3A23%3A18Z&sr=b&sp=r&sig=pkyqtwUknQwL1FoExuuZ2kKfrt24Ckf8XdplKsxxSnQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 15:36 UTC, opbld30 commented
Docs Build status updates of commit _[6236bf5](https://github.com/markwahl-msft/microsoft-graph-docs/commits/6236bf51d0f947d4f9ac26f97b420c0e23f47423)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311534193157-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T15%3A36%3A03Z&sr=b&sp=r&sig=rUFht7p2DMLDlryDMRuIVbqvoL3J%2FhZL18FGozoQi4M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 15:41 UTC, markwahl-msft commented on api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
>  |Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All |
Sure, I am rolling back the intro statement. I would suggest though that we not introduce changes to the directory permissions list in *this* PR, as I was intending this PR to document the EM provider.  I'd prefer that changes to the directory provider behavior be orchestrated by @abhijeetsinha or his colleagues in a distinct PR.

2022-03-31 15:46 UTC, opbld33 commented
Docs Build status updates of commit _[6ab164f](https://github.com/markwahl-msft/microsoft-graph-docs/commits/6ab164fa729281301ecccf9b20fe7b577bb24ed8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203311544226928-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T15%3A46%3A08Z&sr=b&sp=r&sig=o3fzbL4X8Alb3ddiDzP8NOuU61wcGAZSiCth2J0%2BAKQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 15:24 UTC, opbld34 commented
Docs Build status updates of commit _[2b1e838](https://github.com/markwahl-msft/microsoft-graph-docs/commits/2b1e8381cdafec5b57ad1ee1593ced7a18f23e02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em1-rbac/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-16354) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204011522404821-16354%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T15%3A24%3A28Z&sr=b&sp=r&sig=pJ82KVSbrbXqHb9kMoPH1wogPvJa%2Bj09oJeokxlkNQA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 16:44 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
>  |Application | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All |
gotcha. Not a problem - we'll handle that through a distinct PR.

2022-04-01 16:45 UTC, FaithOmbongi approved these changes
Thank you @markwahl-msft for raising this PR to close this doc gap. Approved.

2022-04-01 22:42 UTC, merged