Q3 small signin updates
microsoftgraph/microsoft-graph-docs pull request #16383
Opened 2022-04-01 08:21 UTC by besiler

Added
* Clientcredentialtype property to signins
* RemoteDesktopToken to incomingtokentype
* Confirmcompromised API
* Confirmsafe API

2022-04-01 08:23 UTC, opbld34 commented
Docs Build status updates of commit _[bc579f1](https://github.com/besiler/microsoft-graph-docs/commits/bc579f1796af86de0be6c10f281a98756511499e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-confirmcompromised.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-confirmsafe.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmsafe.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204010821277627-16383%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T08%3A23%3A27Z&sr=b&sp=r&sig=28f3BvtU7ZC7QbDftJ%2BeoKpN4bXKoUbShgEITNHQfUM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 18:31 UTC, FaithOmbongi requested changes
Thank you @besiler for your work on this PR. I've left suggestions for some minor fixes and please surface the new APIs in the TOC.

2022-04-05 18:31 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          "Target": "confirmSafe"
```suggestion
          "Description": "Added the [confirmCompromised](https://docs.microsoft.com/en-us/graph/api/confirmCompromised?view=graph-rest-beta) method to the [signin](https://docs.microsoft.com/en-us/graph/api/signin?view=graph-rest-beta) resource.",
          "Target": "signIn"
        },
        {
          "Id": "6a60b3dd-cb30-4a9b-8b94-9197e17d4ba5",
          "ApiChange": "Method",
          "ChangedApiName": "confirmSafe",
          "ChangeType": "Addition",
          "Description": "Added the [confirmSafe](https://docs.microsoft.com/en-us/graph/api/confirmSafe?view=graph-rest-beta) method to the [signIn](https://docs.microsoft.com/en-us/graph/api/signin?view=graph-rest-beta) resource.",
          "Target": "signIn"
```

2022-04-05 18:31 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
```suggestion
      "WorkloadArea": "Reports",
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmcompromised.md
> +description: "Allows you to mark Azure AD log events as risky for Azure AD Identity Protection."
I think not explicitly mentioning sign ins infers this action is also for other log types.
```suggestion
description: "Allows you to mark Azure AD sign in events as risky for Azure AD Identity Protection."
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmcompromised.md
> +This API allows admins to mark an event in the Azure AD logs as risky. Events marked as risky by an admin are immediately flagged as high risk in Azure AD Identity Protection, overriding previous ris
Suggestion to remove the last 2 sentences. Those will be catered for in the Request body and Response sections below.
```suggestion
Allows admins to mark an event in the Azure AD sign in logs as risky. Events marked as risky by an admin are immediately flagged as high risk in Azure AD Identity Protection, overriding previous risk states. Admins can confirm that events flagged as risky by Azure AD Identity Protection are in fact risky or they can mark unflagged events as risky. 
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmcompromised.md
> +Content-length: 42
Let's remove this.
```suggestion
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmcompromised.md
> +>**Note:** The response object shown here might be shortened for readability.
```suggestion
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmsafe.md
> +description: "Allows you to mark Azure AD log events as safe for Azure AD Identity Protection"
```suggestion
description: "Allows you to mark Azure AD sign in events as safe for Azure AD Identity Protection."
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmsafe.md
> +This API allows admins to mark an event in the Azure AD logs as safe. Admins can either mark that events flagged as risky by Azure AD Identity Protection are in fact safe or can mark unflagged events
```suggestion
Allows admins to mark an event in Azure AD sign in logs as safe. Admins can either mark as safe the events flagged as risky by Azure AD Identity Protection or they can mark unflagged events as safe.
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmsafe.md
> +|requestIds|String collection|The requestIds of the events that should be marked safe for Azure AD Identity Protection.|
I think you're referring to the values in the **id** property?
```suggestion
|requestIds|String collection|The IDs of the sign in events that should be marked safe for Azure AD Identity Protection.|
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmcompromised.md
> +|requestIds|String collection|The requestIds of the events that should be marked risky for Azure AD Identity Protection.|
I believe you're referring to the value in the **id** property?
```suggestion
|requestIds|String collection|The IDs of the sign in events that should be marked risky for Azure AD Identity Protection.|
```

2022-04-05 18:31 UTC, FaithOmbongi commented on api-reference/beta/api/signin-confirmsafe.md
> +Content-length: 42
```suggestion
```

2022-04-05 18:33 UTC, FaithOmbongi requested changes
Thank you @besiler for your work on this PR. I've left suggestions for some minor fixes and please surface the new APIs in the TOC.

2022-04-06 00:25 UTC, besiler commented on api-reference/beta/api/signin-confirmcompromised.md
> +|requestIds|String collection|The requestIds of the events that should be marked risky for Azure AD Identity Protection.|
Yep, that's correct

2022-04-06 00:30 UTC, opbld32 commented
Docs Build status updates of commit _[c0f4fe4](https://github.com/besiler/microsoft-graph-docs/commits/c0f4fe4f9ce423316d5023fd86d725db32d91fde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-confirmcompromised.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-confirmsafe.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmsafe.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204060028137848-16383%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T00%3A30%3A20Z&sr=b&sp=r&sig=XUUEPSLD%2B%2FFB8NJc5%2FCyMmrJHjrRy8cMQ79HlBeLrmE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 00:45 UTC, besiler commented
> Thank you @besiler for your work on this PR. I've left suggestions for some minor fixes and please surface the new APIs in the TOC.

How do I add the new APIs to the TOC? If you have a wiki doc or something I can look at to add them, that would help!

I looked at the TOC file under beta > breadcrumb > toc but don't see much on how I would add the new APIs.

![image](https://user-images.githubusercontent.com/69605773/161873635-87806c0b-6706-4fe4-8d31-376875855ef8.png)

2022-04-06 08:09 UTC, FaithOmbongi commented
> 

Hi @besiler

2022-04-06 08:12 UTC, opbld33 commented
Docs Build status updates of commit _[c0f4fe4](https://github.com/besiler/microsoft-graph-docs/commits/c0f4fe4f9ce423316d5023fd86d725db32d91fde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-confirmcompromised.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-confirmsafe.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmsafe.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204060809288732-16383%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T08%3A12%3A11Z&sr=b&sp=r&sig=ckp92uu%2FKNA1K%2FR9lYoLjprgNkv5DOApW8RJ%2BPfZB7A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 17:58 UTC, opbld33 commented
Docs Build status updates of commit _[262c664](https://github.com/besiler/microsoft-graph-docs/commits/262c6643b0735d34c8ad515fa2c9c2ff77b728d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-confirmcompromised.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-confirmsafe.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmsafe.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204141755523935-16383%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T17%3A58%3A58Z&sr=b&sp=r&sig=%2F%2FPYHCL2%2B4ybsXkVmg5%2FJU6iV8fY8idqzn8Phw9xeis%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 18:10 UTC, FaithOmbongi approved these changes
Thank you @besiler for your work on this PR. Approved.

2022-04-14 18:12 UTC, opbld30 commented
Docs Build status updates of commit _[37b199d](https://github.com/besiler/microsoft-graph-docs/commits/37b199d5340fb878f77a535ec6e5dde22bb9864e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-confirmcompromised.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-confirmsafe.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmsafe.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204141809033005-16383%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T18%3A12%3A21Z&sr=b&sp=r&sig=ppu6V%2Fwu1f9GQ8a%2F4N2eAAi5oydMQmthHxjjQZfZflA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 19:58 UTC, opbld31 commented
Docs Build status updates of commit _[b5acd2f](https://github.com/besiler/microsoft-graph-docs/commits/b5acd2f23df721fd962a7c53a16ec64c85c0eff3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-confirmcompromised.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmcompromised.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-confirmsafe.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-confirmsafe.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmsafe?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-confirmcompromised?view=graph-rest-beta&branch=pr-en-us-16383) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q3signin/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204141956147717-16383%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T19%3A58%3A17Z&sr=b&sp=r&sig=iB7f7doMAA1A6RwWF9rcHFBg36kHNrVd1P5SbEn8Hbw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 20:01 UTC, merged