Associate checklistitem and categories to todotask
microsoftgraph/microsoft-graph-docs pull request #16384
Opened 2022-04-01 10:05 UTC by avijityadav

ChecklistItem was earlier added to baseTask resource. Now, after discussion, we decided to bring checklistItem support to todoTask resource. Also, we are bringing categories support on todoTask resource.

Also, we don't want users to user the new tasks workload as it is prone to major breaking changes and it might even be deprecated from Graph beta, so moving it down a level in TOC and marking it experimental.

2022-04-01 10:07 UTC, opbld34 commented
Docs Build status updates of commit _[5f3fbc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f3fbc64638dfb65c68b871bdedd165c3c0ea44b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b5bcb5fe)
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/task.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-4246afff2fb8bd65658b689411a2aec4-b5bcb5fe)
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-b5bcb5fe"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/toc.yml)
 - **Line 15523, Column 9**: **[Warning: yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 15523, Column 9**: **[Warning: yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="4246afff2fb8bd65658b689411a2aec4-b5bcb5fe"></a>
### [api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/task.md)
 - **Line 33, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/basetask-list-checklistitems.md'.`````
 - **Line 34, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/basetask-post-checklistitems.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204011006000160-16384%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T10%3A07%3A51Z&sr=b&sp=r&sig=2RIVJiwBOPSvkpkcRAdvXqtRWtlf4aWaCDdkgzwjNjc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 10:14 UTC, opbld32 commented
Docs Build status updates of commit _[0688d67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0688d677de5adfa84128f73cd31cb2cd9ac58137)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6dd0e306)
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-6dd0e306"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/toc.yml)
 - **Line 15523, Column 9**: **[Warning: yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````
 - **Line 15523, Column 9**: **[Warning: yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204011012518514-16384%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T10%3A14%3A40Z&sr=b&sp=r&sig=dH8YYhvGJBVW0vysZYpIAil9Y0LluKlLa%2BUAu7I%2BkYk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-13 15:21 UTC, opbld33 commented
Docs Build status updates of commit _[4968734](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49687345e1b5d2609c7b59a1890dd986da766038)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204131519474922-16384%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-14T15%3A21%3A44Z&sr=b&sp=r&sig=ArOKIL9IsymnbOp8uS2SBI0P3OE1jRsKgUKHlLTFIzs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 04:53 UTC, opbld31 commented
Docs Build status updates of commit _[093f294](https://github.com/microsoftgraph/microsoft-graph-docs/commits/093f294473d3d1d60b6705e9572f5e96486c96d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :x:Error | | [Details](#user-content-b4508e0802b23d06330a8f931bc922a1-1df90467)
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :x:Error | | [Details](#user-content-b8384403c9272800b8087bc95490a40c-1df90467)
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :x:Error | | [Details](#user-content-637e78be2da32bfd99589a940d7b0b75-1df90467)
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-list-checklistitems.md) | :x:Error | | [Details](#user-content-292dd5c3c2c9744fac2b081f9010ba84-1df90467)
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :x:Error | | [Details](#user-content-f0477c106edf8a45f62c75e922a89148-1df90467)

<a id="b4508e0802b23d06330a8f931bc922a1-1df90467"></a>
### [api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md)
 - **Line 61, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-checklistitem-csharp-snippets.md'.`````
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-checklistitem-javascript-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-checklistitem-objc-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-checklistitem-java-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-checklistitem-go-snippets.md'.`````

<a id="b8384403c9272800b8087bc95490a40c-1df90467"></a>
### [api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-checklistitem-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-checklistitem-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-checklistitem-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-checklistitem-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-checklistitem-go-snippets.md'.`````

<a id="637e78be2da32bfd99589a940d7b0b75-1df90467"></a>
### [api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md)
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-checklistitem-javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-checklistitem-csharp-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-checklistitem-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/update-checklistitem-java-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/update-checklistitem-go-snippets.md'.`````

<a id="292dd5c3c2c9744fac2b081f9010ba84-1df90467"></a>
### [api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-list-checklistitems.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-checklistitem-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-checklistitem-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-checklistitem-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-checklistitem-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-checklistitem-go-snippets.md'.`````

<a id="f0477c106edf8a45f62c75e922a89148-1df90467"></a>
### [api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md)
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-checklistitem-from--javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-checklistitem-from--csharp-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-checklistitem-from--objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-checklistitem-from--java-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-checklistitem-from--go-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280451381027-16384%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T04%3A53%3A36Z&sr=b&sp=r&sig=AHE7xXToE7esH7zt6xiwbcoG0rTNZ%2Bpbah%2FU7wno3RE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-va [...]

2022-04-28 05:31 UTC, opbld34 commented
Docs Build status updates of commit _[c27b495](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c27b4950680131043b823542a2010e116dcfc80a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/v1.0/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullR [...]

2022-05-14 03:20 UTC, angelgolfer-ms commented on api-reference/beta/resources/task.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the linkedResource_v2 resources from the linkedResources navigat
Lines 33 and 34:
(a) First, a basic question - what is the purpose of the task entity? Based on the CSDL and the published docs for the baseTask set of APIs, the task entity doesn't seem to serve any purpose in the API. All the CRUD operations for the baseTask set of APIs use the baseTask entity, not the task entity. 
Since baseTask (and baseTaskList) are defined to be abstract, and the task and taskList resources simply inherit from them (but are not abstract), did you guys mean to define CRUD operations that use these non-abstract task and taskList? But somehow you defined CRUD operations for the abstract resources baseTask and baseTaskList?

2022-05-14 03:23 UTC, angelgolfer-ms commented on api-reference/beta/resources/task.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the linkedResource_v2 resources from the linkedResources navigat
(b) Since the task and taskList entities aren't used in existing APIs, and they inherit from baseTask and baseTaskList which are to be deprecated, then I assume task and taskList are to be deprecated too.

If that's the case, can you please append "(deprecated)" to the topic titles for task.md and tasklist.md?

2022-05-14 03:25 UTC, angelgolfer-ms commented on api-reference/beta/resources/task.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the linkedResource_v2 resources from the linkedResources navigat
(c) And if it's true that task.md and tasklist.md are to be deprecated, then let's not bother to make the changes in line 33 and 34.

2022-05-14 04:59 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>              href: api/opentypeextension-get.md
Lines 15497-15509:
Since we're going to mark the baseTask set of APIs as deprecated (in line 15478), but the checklistItem API is remaining active with updates to expose list and create operations for todoTask, let's not include the checklistItem set of API under the node for the baseTask set of APIs. If you do so, then technically you shouldn't mark "(experimental)" or "(deprecated)" at the node level in line 15478.

2022-05-14 05:22 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>              href: api/opentypeextension-get.md
Lines 15493-15496:
A few questions related to the create and get operations of open type extensions:
(a) What are you doing with the "tasks" nav property of the user entity?
In the beta metadata, the tasks nav property is of the type tasks, which has a lists nav property defined to be a collection of baseTaskList.
But your CSDL for this PR didn't include any updates to any of the above.
Does that mean you want the create and get open type extension operations to work with baseTaskList and baseTask?

(b) If you're NOT updating any of the above, then you'd need to call out in the create and get open type extension topics that the baseTask set of APIs is being deprecated.

(c) If on the other hand, you're going to redefine in the CSDL the tasks entity to have nav properties alltasks and lists being collections of todoTask and todoTaskList respectively, then you'd need to please update the 2 topics opentypeextension-post-opentypeextension.md and opentypeextension-get.md. There are links that point to baseTask and baseTaskList in those 2 topics; you need to change those link to point to todoTask and todoTaskList instead.

2022-05-14 05:52 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>          - name: Linked resource
Line 15510 (node "Linked resource"):
FYI I am going to label this node as "Linked resource v2" for clarity.
This is necessary if we're going to label the set of APIs for baseTask as "(deprecated)" (or like you have it right now, as "(experimental)").
The actual linkedResource API is not deprecated (nor experimental).

2022-05-14 05:56 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>          - name: Task
Lines 15469-15472:
This comment is about including the topics for create and get operations of open type extensions under the node for baseTaskList.
Please see the [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16384/files#r872933054) below and apply the similar here.

2022-05-14 06:15 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>          items:
Line 15445:
As we discussed and agreed on 5/12, the node for the baseTask set of APIs should be marked as "(deprecated)", and not "(experimental)".
FYI I'm going to make this change in your PR, so that I can fine-tune the TOC to make the swap of the 2 sets of APIs easier to follow, especially for existing customers who were aware of the last major TOC change in Dec. 2021.

At the moment, I find how we have been labelling the 2 sets of APIs in the TOC disorienting. It's not just at the parent node level. It's disorienting at the resource and API level as well. I feel there's a need to differentiate the TOC labels for todoTask and baseTask and not label them both in the TOC as "Task". The same goes for the TOC labels for their CRUD topics. In Dec. we should have made the differentiation in the TOC (but we didn't). And now with the swap, it's even more necessary to show the difference in the TOC labels. Otherwise, for existing customers who have lived through the change in Dec. and going through this swap now in May, they'll have to make special efforts to remember where we moved their cheese!

2022-05-14 08:36 UTC, opbld32 commented
Docs Build status updates of commit _[edd086e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edd086eaa35acddf572ced2d64e2a73cfcc89dbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/v1.0/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[changelog/Microsoft.Todo.json](htt [...]

2022-05-14 08:52 UTC, opbld32 commented
Docs Build status updates of commit _[5664efc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5664efcffbda734cb11106879584dff00106d530)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/v1.0/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[changelog/Microsoft.Todo.json](htt [...]

2022-05-16 07:56 UTC, opbld30 commented
Docs Build status updates of commit _[c76ef6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c76ef6e18c52744a7424c0d2616bfbf49711d0de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-5959c52b)
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasks-overview?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/v1.0/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2022-05-16 08:16 UTC, opbld31 commented
Docs Build status updates of commit _[a809dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a809dfee5dd5bfe98d810010c7bbab755aa1e894)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-1a2dde59)
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasks-overview?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/v1.0/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2022-05-16 08:25 UTC, opbld32 commented
Docs Build status updates of commit _[d52ce9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d52ce9e72e45dedf8f71bd34421be332b82e1b38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-317a5427)
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/basetasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/basetasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/basetasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/checklistitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/checklistitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/checklistitem?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/task.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/task?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasklist?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/tasks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tasks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tasks-overview?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/v1.0/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/v1.0/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-checklistitems?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.c [...]

2022-05-17 01:30 UTC, opbld33 commented
Docs Build status updates of commit _[cc577cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc577ccfec30fa0ee6ba24fbd8e90c05a64fee7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-174285a1)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasks-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasks-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasks-list-lists?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasks-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasks-post-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasks-post-lists?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tod [...]

2022-05-17 05:00 UTC, opbld30 commented
Docs Build status updates of commit _[d112267](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d11226798e8af330cd6f3ebb450c4c460b26e80b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-46629b23)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasks-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasks-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasks-list-lists?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/tasks-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tasks-post-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasks-post-lists?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/todotask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tod [...]

2022-05-17 05:09 UTC, angelgolfer-ms requested changes
Hi @avijityadav , I made a bunch of updates directly to the beta version files in your PR mainly to make the 2 versions of to-do API clearer. Can you please take a look at the topics in this PR in the beta version on the staging site, as well as my comments in the PR? There are action items for you there.

Specifically, can you take a look at the todo-deprecate-basetaskapi.md file that has the deprecation note? 
I understand you're not going to be able to determine this week when the baseTask set of API will stop returning data and be removed. That's unconventional, but I think the second best thing we can do is to tell customers by when there will be a date. In general, we can't leave that deprecation period open-ended and expect existing customers  to take action in time for your team to remove that API set down the road. So can you confirm in that deprecation note,  (a) we are  targeting announcing that deprecation on 5/20 by publishing this PR (which is kind of ambitious) and (b) you can update the deprecation note by 6/30 (or a date you specify)?

As a heads-up, I haven't yet looked at the integration of the checklistItem API and category property closely to call that content reviewed. I will do that tomorrow.

And once we agree on I/we have done to beta is appropriate, then please prepare to apply the similar (where applicable) to v1 later this week in the PR.

2022-05-17 17:38 UTC, avijityadav commented on api-reference/beta/resources/task.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the linkedResource_v2 resources from the linkedResources navigat
Replying to your questions in order
(a) We followed it from attachment API documentation, we had attachment as an abstract entity and we have fileAttachment, itemAttachment, referenceAttachment as derived entity but CRUD operations are defined on attachments in the documentation. 

(b) Sure Angela, Once I hear from API council , I will add the deprecated tag and the notice.

(c) Task and tasklist can be marked deprecated but it does not change their relationship with checklistitems. User can still "Create checklistItem" that refers to the todoTask. In fact, checklistItem for todoTask is the same as checklistItem for task.

2022-05-17 17:43 UTC, avijityadav commented on api-reference/beta/toc.yml
>              href: api/opentypeextension-get.md
Got it, We can remove checklistItem from here as they are not deprecated.

2022-05-17 17:49 UTC, avijityadav commented on api-reference/beta/toc.yml
>              href: api/opentypeextension-get.md
But I agree with your point, since we are deprecating baseTask and baseTaskList, we should remove their reference.

2022-05-17 18:11 UTC, opbld31 commented
Docs Build status updates of commit _[9c74fbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c74fbf9dd28b5319ac2f084a29cd2e8c2419d44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-2a415d3d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2a415d3d)
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-2a415d3d)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-r [...]

2022-05-18 19:10 UTC, opbld33 commented
Docs Build status updates of commit _[26eb320](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26eb320838289dcbe3279aed8fe7111efd8c0f69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-f93c30f6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f93c30f6)
[api-reference/beta/includes/todo-deprecate-basetaskapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/todo-deprecate-basetaskapi.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-13a36b8788050e19d24b501ee5f0bd69-f93c30f6)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-r [...]

2022-05-19 00:55 UTC, opbld30 commented
Docs Build status updates of commit _[ec81815](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec81815cbceaea3fabefc86a9783c1beb7695e89)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-2ef17f9c)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2ef17f9c)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/subscription-post-subscriptions.m [...]

2022-05-19 05:52 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>              href: api/opentypeextension-get.md
Hi @avijityadav , since you updated the POST (opentypeextension-post-opentypeextension.md) and GET (opentypeextension-get.md) topics to have their table in the Permissions section to link to todoTask and todoTaskList instead, then to be complete, please follow up on these related items:

(i) Update the beta metadata per (a) in my [comment above.](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16384#discussion_r872933054). That's so the syntax in the CRUD operation topics for open type extensions for your API would still be correct. (Of course the API would behave the same as specified in the syntax.)

(ii) Other than the POST and GET topics, we actually need to update the following topics as well for openTypeExtension:
   - resource topic (opentypeextension.md) - tables in the "Permissions" and "Methods" sections
   - PATCH topic (opentypeextension-update.md)
   - DELETE topic (opentypeextension-delete.md)

2022-05-19 06:06 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: resources/task.md
Before line 15416:
I think you deleted one too many line here - the line to display the task resource in the TOC is now gone.
FYI I am going to add that back:
name: Task

2022-05-19 06:16 UTC, angelgolfer-ms commented on api-reference/beta/resources/basetask.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the **linkedResource_v2** resources from the linkedResources nav
Lines 32 and 33:
I think the Methods table for baseTask should not show the "list" and "create" operations for checklistItem, now that you updated checklistItem to work with todoTask. These operations don't have anything to do with baseTask anymore.
So technically, your team could have decided to mirror a checklistItem_v2, like what you did for linkedResource before, to not make checklistItem straddle between baseTask (before) and todoTask (now). 

But we're not doing that. So for what your team has decided - because checklistItem doesn't work with baseTask anymore, then it would be confusing that those operations remain in the Methods table for baseTask and when customers click those method topics, then they find the topics have nothing to do with baseTask.

FYI I'm going to remove lines 32 and 33. Let me know if you see differently.

2022-05-19 06:30 UTC, angelgolfer-ms commented on api-reference/beta/resources/basetask.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the **linkedResource_v2** resources from the linkedResources nav
I have a question:
Come to think of it, because you made checklistItem first work with baseTask, customers could have created some checklistItem instances with some baseTask resources.
Then when we release this version of checklistItem that no longer works with baseTask and only with todoTask, what are those customers supposed to do to migrate their checklistItem instances on pre-existing baseTask resources onto todoTask resources? They won't be able to call GET checklistItem on baseTask anymore, so essentially those earlier checklistItem instances are not accessible by code anymore, is that right?

2022-05-19 07:24 UTC, angelgolfer-ms commented on api-reference/beta/resources/subscription.md
>  - A [user][] in Azure Active Directory.
@avijityadav , thanks for making updates to change notifications topics as well. Please also update webhooks.md in the /resources folder. That's the API overview under the "Change notifications" node in the reference section.

2022-05-19 08:19 UTC, angelgolfer-ms commented on changelog/Microsoft.Todo.json
> +     },
@avijityadav , we need to add changelist record JSON for each of the following as well:

- Deprecation of baseTaskList resource and its CRUD operations.
- Deprecation of wellKnownTaskList resource.
- Deprecation of wellKnownListName_v2 enumeration.
- Deprecation of delta function for baseTaskList.
- Deprecation of the CRUD operations for opentypeextension on baseTaskList.
- Deprecation of baseTask resource and its CRUD operations.
- Deprecation of delta function for baseTask.
- Deprecation of the CRUD operations for opentypeextension on baseTask.
- Deprecation of the CRUD operations for subscription on baseTask.

Unfortunately, because deprecation is not something that's noted in a CSDL, Graph Studio doesn't generate the changelist records for these, so you'll have to do it manually.

2022-05-19 09:25 UTC, opbld31 commented
Docs Build status updates of commit _[7a43a44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a43a4487e99dc4934ebd8e967be570c4b873a57)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-f67225dd)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) [...]

2022-05-19 09:25 UTC, angelgolfer-ms commented on api-reference/beta/resources/basetask.md
>  |[List linkedResources](../api/basetask-list-linkedresources.md)|[linkedResource_v2](../resources/linkedresource_v2.md) collection|Get the **linkedResource_v2** resources from the linkedResources nav
Ok, per our Teams chat, lines 32-33 should have links to go to the topics basetask-post-checklistitems.md and basetask-list-checklistitems.md. Please re-create those topics.
To answer my own last comment above, the code that supports checklistitem for baseTask still exists. Existing customers can make use of that code during the deprecation period to help update their apps and data to use todoTask instead.

2022-05-19 20:57 UTC, opbld33 commented
Docs Build status updates of commit _[32dd88b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32dd88bc92bc61285ae082d44b7ce7bf968bb2e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-fd3dee3e)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) [...]

2022-05-20 21:37 UTC, angelgolfer-ms commented
@avijityadav , I set the **changes requested** label for my Github comments and our Teams discussion about 1.5 days ago. Please ping me on Teams when your updates are complete so that I can take a look at this PR again. Thanks.

2022-05-23 19:45 UTC, opbld33 commented
Docs Build status updates of commit _[222e228](https://github.com/microsoftgraph/microsoft-graph-docs/commits/222e228e40c40ef6c6d433fad57f00989c1b76c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-10cff59f)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) [...]

2022-05-25 10:45 UTC, opbld33 commented
Docs Build status updates of commit _[bbc259f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbc259f4d7d6883125cbd5e425538cf09c2d109e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-cb97dab1)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-e6ec7cd1e89464ee233e6b72b378c4b4-cb97dab1)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/micro [...]

2022-05-25 11:26 UTC, opbld31 commented
Docs Build status updates of commit _[8e9ba4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e9ba4f92663239811110dbdf6849e687ac2e670)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-8c8125d3)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main [...]

2022-05-26 08:18 UTC, opbld33 commented
Docs Build status updates of commit _[e71bfc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e71bfc13a64e6be230fd09bfc74817bba15c0d56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-d54f894f)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main [...]

2022-05-26 09:27 UTC, opbld31 commented
Docs Build status updates of commit _[ae2fcc3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae2fcc32d2bd28aa03ce0be6a9cd7ec1f47791a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-e327bfc3)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta [...]

2022-05-27 02:58 UTC, opbld33 commented
Docs Build status updates of commit _[eca26a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eca26a60c7492629488bb1834a0f8b5b7d001118)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) | [Details](#user-content-f947c3cd50805c7bde7f2410f32a81c7-08321ad3)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta [...]

2022-05-27 03:11 UTC, opbld34 commented
Docs Build status updates of commit _[47ea33d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47ea33da2524fe2a6b7e63850174b2fdcf5c805f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-update.md) | :white_check_ [...]

2022-05-27 08:21 UTC, opbld34 commented
Docs Build status updates of commit _[952d495](https://github.com/microsoftgraph/microsoft-graph-docs/commits/952d4955db1a058f260c0aa1194ba35a5e78fdca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-c9f1c7b7508370356ac277b98d3ff55f-9395b7e2)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeexte [...]

2022-05-27 08:37 UTC, opbld30 commented
Docs Build status updates of commit _[2a0cf38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a0cf384506e8ae4e767606b08a45101f1de7546)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-c9f1c7b7508370356ac277b98d3ff55f-ce5f7ce1)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeexte [...]

2022-05-27 08:48 UTC, opbld33 commented
Docs Build status updates of commit _[40b56ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40b56ca663458ef35491f8201bb516ac3c72db8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-update.md) | :white_check_ [...]

2022-05-27 08:50 UTC, opbld33 commented
Docs Build status updates of commit _[80a56e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80a56e959b0b8c83891d7b85f8436efae86c1ad0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-update.md) | :white_check_ [...]

2022-05-27 09:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/todotask.md
>  |completedDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone that the task was finished.|
This comment is for the list and get operation examples for todotask.md:
@avijityadav , can you update examples for the create, list, and get operations  that include the  categories property and example values?

2022-05-27 09:28 UTC, opbld31 commented
Docs Build status updates of commit _[60808f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60808f78c1581baf8df89131ddc278175207ed25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-update.md) | :white_check_ [...]

2022-05-27 09:28 UTC, angelgolfer-ms requested changes
Hi @avijityadav , thanks for incorporating my comments from a week ago.
FYI I did a bunch of updates in your PR, and added a comment. 
Of note is I added a second deprecation note for beta topics that are shared between baseTask or baseTaskList with other resources that are not deprecated, e.g., checklistItem.md. subscription.md in beta.
At your earliest convenience today, can you please take a look at the [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16384#discussion_r883428651) and my commits? I will still be able to respond to you if I see them on Friday afternoon. Hopefully I can approve the PR by EOD Friday, and you can then set the PR to ready for merge in time for publishing on Monday, to match with the dates for deprecation.

2022-05-27 09:50 UTC, opbld34 commented
Docs Build status updates of commit _[f6c8100](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6c81006b9b15835d319f3e859a3db039ab50290)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-list-tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-9ad5058d0a933e0aa600b1bc75bf05b4-5ce94371)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-openty [...]

2022-05-28 00:30 UTC, angelgolfer-ms commented on api-reference/beta/api/todotask-update.md
>  |completedDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone that the task was finished.|
@avijityadav , is the categories properties always included in the response?
If so, can you update the example in the PATCH topic to include that property as well please?

And apply the similar to the v1 topic please?

2022-05-28 00:32 UTC, angelgolfer-ms requested changes
Hi @avijityadav , thanks for updating the examples.
If the categories property is included in the PATCH operation response by default, can you include that property in the example please?

Thanks!

2022-05-28 03:16 UTC, avijityadav commented on api-reference/beta/api/todotask-update.md
>  |completedDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone that the task was finished.|
Yes, Angela, Have updated it.

2022-05-28 03:31 UTC, opbld31 commented
Docs Build status updates of commit _[73680c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73680c235bad5eb2607d5b12112fbf54c3b324db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-list-tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-9ad5058d0a933e0aa600b1bc75bf05b4-67df9af1)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-openty [...]

2022-05-28 05:32 UTC, angelgolfer-ms approved these changes
Looks good to be published! Please set the label **ready to merge** on the PR so that @Lauragra can publish it on the next work day. Thanks!

2022-06-01 03:24 UTC, opbld32 commented
Docs Build status updates of commit _[ae7cf88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae7cf88b3f7af04fe9227551641f2400b5ebccac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-list-tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-9ad5058d0a933e0aa600b1bc75bf05b4-a9390778)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-openty [...]

2022-06-01 03:34 UTC, opbld33 commented
Docs Build status updates of commit _[ea0bc14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea0bc142bc366cba297aec01bf65becc117364c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-list-tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-9ad5058d0a933e0aa600b1bc75bf05b4-ce41c6c2)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-openty [...]

2022-06-01 03:44 UTC, opbld31 commented
Docs Build status updates of commit _[dbedbf0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbedbf0a3217791f732525c3c2e0f7b8f606876a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/todotasklist-list-tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-16384) (>= graph-rest-1.0) | [Details](#user-content-9ad5058d0a933e0aa600b1bc75bf05b4-dc999a40)
[api-reference/beta/api/basetask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-list-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todoupdates/api-reference/beta/api/basetask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-move.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-move?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-checklistitems.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-checklistitems.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-checklistitems?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetask-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-delta?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-list-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/basetasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/basetasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/basetasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/checklistitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/checklistitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/checklistitem-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/linkedresource_v2-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/linkedresource_v2-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource_v2-update?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-16384) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-openty [...]

2022-06-01 04:07 UTC, merged