Update onpremisespublishing.md
microsoftgraph/microsoft-graph-docs pull request #16404
Opened 2022-04-04 19:42 UTC by dhruvinrshah

Document change to add isStateSessionEnabled property to the onPremisesPublishing API doc.

2022-04-04 19:44 UTC, opbld34 commented
Docs Build status updates of commit _[a04d7c7](https://github.com/dhruvinrshah/microsoft-graph-docs/commits/a04d7c7b85faac5e8eebcea8d986a109da563fbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/dhruvinrshah/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16404) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204041942474697-16404%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T19%3A44%3A53Z&sr=b&sp=r&sig=Fd%2BEujL20cvreyhhV3eZITtNgMMX318aSGAdvwfIGiU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 02:55 UTC, Lauragra commented
@dhruvinrshah , please follow the Get started steps to set yourself up to be a contributor. This change will also require an update to the changelog.

2022-04-08 09:05 UTC, FaithOmbongi requested changes
Thank you @dhruvinrshah for your work on this PR. I've left suggestions for minor changes.

2022-04-08 09:05 UTC, FaithOmbongi commented on api-reference/beta/resources/onpremisespublishing.md
> +|isStateSessionEnabled|Boolean| Indicates if state parameter validation is enabled during Authorization Code Grant flow. For all new apps, the property will be true by default. For all existing apps,
- Some tweaks to the description and suggestions.
- I'm assuming that if this property isn't yet live and I create an app today, the value for my app will be `false`. So the default `true` value will be enforced for all new apps created after some month and/or date - please let's indicate that enforcement date (I've added `{ }` placeholder suggestions.)

```suggestion
|isStateSessionEnabled|Boolean| Indicates whether validation of the **state** parameter when the client uses the OAuth 2.0 authorization code grant flow is enabled. This setting allows admins to specify whether they want to enable CSRF protection for their apps. For all new apps created after {please enter the enforcement Month and/or date}, the property will be `true` by default. For all apps created prior to {date/month}, it is set to `false`. |
```

2022-04-08 16:17 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **isStateSessionEnabled** property to [onPremisesPublishing](https://docs.microsoft.com/en-us/graph/api/resources/onPremisesPublishing?view=graph-rest-beta) resour
Suggestion to enhance the changelog.
```suggestion
          "Description": "Added the **isStateSessionEnabled** property to the [onPremisesPublishing](https://docs.microsoft.com/en-us/graph/api/resources/onPremisesPublishing?view=graph-rest-beta) resource. Use this property to enable or disable validation of the **state** parameter for apps that use the OAuth 2.0 authorization code grant flow.",
```

2022-04-08 16:30 UTC, dhruvinrshah commented on api-reference/beta/resources/onpremisespublishing.md
> +|isStateSessionEnabled|Boolean| Indicates if state parameter validation is enabled during Authorization Code Grant flow. For all new apps, the property will be true by default. For all existing apps,
We were going to co-ordinate the updates/merge to the docs and code release to overlap so as to avoid any confusion. Kindly confirm if we still need to add particular date?

2022-04-08 16:46 UTC, opbld30 commented
Docs Build status updates of commit _[ea0d677](https://github.com/dhruvinrshah/microsoft-graph-docs/commits/ea0d677fc11d87c802b46fcfe52fd58f8546894d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/dhruvinrshah/microsoft-graph-docs/blob/patch-2/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16404) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/dhruvinrshah/microsoft-graph-docs/blob/patch-2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204081644485611-16404%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T16%3A46%3A29Z&sr=b&sp=r&sig=m4%2BmAB2tmIrgP19USwLWNanujVoTZ25wIG66Elijh1A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 17:16 UTC, FaithOmbongi commented on api-reference/beta/resources/onpremisespublishing.md
> +|isStateSessionEnabled|Boolean| Indicates if state parameter validation is enabled during Authorization Code Grant flow. For all new apps, the property will be true by default. For all existing apps,
No need to have an exact date. The month will do.

2022-04-29 13:58 UTC, dhruvinrshah commented on api-reference/beta/resources/onpremisespublishing.md
> +|isStateSessionEnabled|Boolean| Indicates if state parameter validation is enabled during Authorization Code Grant flow. For all new apps, the property will be true by default. For all existing apps,
Hi Faith,

Kindly let me know if below is acceptable?  

"Indicates whether validation of the **state** parameter when the client uses the OAuth 2.0 authorization code grant flow is enabled. This setting allows admins to specify whether they want to enable CSRF protection for their apps."

2022-05-04 16:15 UTC, FaithOmbongi commented on api-reference/beta/resources/onpremisespublishing.md
> +|isStateSessionEnabled|Boolean| Indicates if state parameter validation is enabled during Authorization Code Grant flow. For all new apps, the property will be true by default. For all existing apps,
> Hi Faith,
> 
> Kindly let me know if below is acceptable?
> 
> "Indicates whether validation of the **state** parameter when the client uses the OAuth 2.0 authorization code grant flow is enabled. This setting allows admins to specify whether they want to enable CSRF protection for their apps."

Sounds good, @dhruvinrshah.

2022-05-05 17:46 UTC, dhruvinrshah commented on api-reference/beta/resources/onpremisespublishing.md
> +|isStateSessionEnabled|Boolean| Indicates if state parameter validation is enabled during Authorization Code Grant flow. For all new apps, the property will be true by default. For all existing apps,
> > Hi Faith,
> > Kindly let me know if below is acceptable?
> > "Indicates whether validation of the **state** parameter when the client uses the OAuth 2.0 authorization code grant flow is enabled. This setting allows admins to specify whether they want to enable CSRF protection for their apps."
> 
> Sounds good, @dhruvinrshah.

@FaithOmbongi : Committed the required changes .. ty!

2022-05-05 18:13 UTC, FaithOmbongi approved these changes

2022-05-05 20:06 UTC, opbld31 commented
Docs Build status updates of commit _[60a7005](https://github.com/dhruvinrshah/microsoft-graph-docs/commits/60a7005541a6d8dc850d2b792aa3b664d5ed79a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16404) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/dhruvinrshah/microsoft-graph-docs/blob/patch-2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052004346542-16404%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T20%3A06%3A42Z&sr=b&sp=r&sig=JPv%2F1kXzB8PSxXQnsYqne3Z8AS4LEiq9ZxsoE0Jt9Lc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 04:09 UTC, opbld30 commented
Docs Build status updates of commit _[dfe4a5e](https://github.com/dhruvinrshah/microsoft-graph-docs/commits/dfe4a5ea95dfa953dc8fab0d92c14b95449f42eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16404) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/dhruvinrshah/microsoft-graph-docs/blob/patch-2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205060405593868-16404%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T04%3A09%3A18Z&sr=b&sp=r&sig=LrMXrBIHSyI3RH9pD8ANieJ%2Fn758lp%2FOZLLkRN%2F2unU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 04:10 UTC, merged