entitlement management: add additionalAccess query API for separation of duties analysis
microsoftgraph/microsoft-graph-docs pull request #16495
Opened 2022-04-12 00:45 UTC by markwahl-msft

2022-04-12 00:47 UTC, opbld32 commented
Docs Build status updates of commit _[00aba0f](https://github.com/markwahl-msft/microsoft-graph-docs/commits/00aba0fdef6d35777983979002cd90233d50d6ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204120045129272-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T00%3A47%3A20Z&sr=b&sp=r&sig=GoPDLcvwI4PR6pUfu8mst1jk1GWbON5mOtLLLLoL0hE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 00:57 UTC, opbld34 commented
Docs Build status updates of commit _[3d3247d](https://github.com/markwahl-msft/microsoft-graph-docs/commits/3d3247d5a794af4d2ecd63c62c821b73e07a2aa0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204120055593572-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T00%3A57%3A33Z&sr=b&sp=r&sig=WlG9xRBagpIfvw6RH%2F2OiXCL8YeBpS0RRUAPjTkSCus%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 15:14 UTC, opbld33 commented
Docs Build status updates of commit _[36e3ad5](https://github.com/markwahl-msft/microsoft-graph-docs/commits/36e3ad569f1abea9370796707e66774ae72067a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204121511483609-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T15%3A14%3A40Z&sr=b&sp=r&sig=eiHyiQy5Tf5jJu%2Bg1KX8OdPb1aAoBOLwpYRP7nlbAX4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 20:00 UTC, opbld31 commented
Docs Build status updates of commit _[caa0e2a](https://github.com/markwahl-msft/microsoft-graph-docs/commits/caa0e2a33782e265220432dd008ae06ed96e9c6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-04.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-04.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-04?branch=pr-en-us-16495) | [Details](#user-content-7a262add4d39da6e734ada62359d017d-b1585b42)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-b1585b42)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16495) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-b1585b42)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16495) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-b1585b42)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16495) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-b1585b42)
[concepts/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-01.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-01?branch=pr-en-us-16495) | [Details](#user-content-369c8945d629ff719bcdc2119dac2ff7-b1585b42)
[concepts/data-connect-quickstart-02.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-02.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-02?branch=pr-en-us-16495) | [Details](#user-content-38c98686334a186496079b022f8ac4b2-b1585b42)
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16495) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-b1585b42)
[concepts/data-connect-quickstart-03.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-03.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-03?branch=pr-en-us-16495) | [Details](#user-content-7db385b8a4b22670a3acd8da69bf8a33-b1585b42)
[api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-remoteassistance-allowedremoteassistanceactions?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) | [Details](#user-content-dd051a7be8ae777c0d0a1d7c8bb481ba-b1585b42)
[concepts/connecting-external-content-build-quickstart-01-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-01-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-01-intro?branch=pr-en-us-16495) | [Details](#user-content-456d16c7db1174de4cba15bd98e0be21-b1585b42)
[concepts/connecting-external-content-build-quickstart-07-surface-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-07-surface-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-07-surface-data?branch=pr-en-us-16495) | [Details](#user-content-cc96779f1a77351d8397d2723ad58e5a-b1585b42)
[concepts/connecting-external-content-build-quickstart-03-build-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-03-build-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-03-build-app?branch=pr-en-us-16495) | [Details](#user-content-75c9d80b83e078d88064d6e03fce904f-b1585b42)
[concepts/connecting-external-content-build-quickstart-05-create-db.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-05-create-db.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-05-create-db?branch=pr-en-us-16495) | [Details](#user-content-8cf4b2b28399a08f993779830baa3e93-b1585b42)
[concepts/connecting-external-content-build-quickstart-04-configure-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-04-configure-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-04-configure-app?branch=pr-en-us-16495) | [Details](#user-content-a00e640699abfd9f250b6eac4dd922d8-b1585b42)
[concepts/connecting-external-content-build-quickstart-06-run-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-06-run-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-06-run-app?branch=pr-en-us-16495) | [Details](#user-content-e1a26798586da77894d1265baca82f59-b1585b42)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16495) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-b1585b42)
[concepts/connecting-external-content-build-quickstart-02-register-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-02-register-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-02-register-app?branch=pr-en-us-16495) | [Details](#user-content-bf7e7fc2e1488b8379519bb1bf990026-b1585b42)
[concepts/connecting-external-content-build-quickstart-08-search-results.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-08-search-results.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-08-search-results?branch=pr-en-us-16495) | [Details](#user-content-bc12a081a7d1a693b726f60cccb50b5d-b1585b42)
[concepts/connecting-external-content-build-quickstart-09-summary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-09-summary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-09-summary?branch=pr-en-us-16495) | [Details](#user-content-22f9745b47bcf4aef74b68a012876aba-b1585b42)
[api-reference/beta/api/accessreviewpolicy [...]

2022-04-26 19:55 UTC, FaithOmbongi requested changes
Thank you @markwahl-msft for your work on this PR. I've left suggestions for descriptions that need more clarity. Please confirm whether the suggested changes are technically accurate.

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +In [Azure AD Entitlement Management](../resources/entitlementmanagement-overview.md), retrieve a collection of [accessPackageAssignment](../resources/accesspackageassignment.md) objects that indicate
Same comment+Q as in the metadata - Looking at the syntax and the rest of the query patterns below, sounds like the API checks both through the specified IDs. Please confirm if this suggestion is technically correct.
```suggestion
In [Azure AD Entitlement Management](../resources/entitlementmanagement-overview.md), retrieve a collection of [accessPackageAssignment](../resources/accesspackageassignment.md) objects that indicate access to a specified access package and an incompatible access package. This can be used to prepare to configure the incompatible access packages for a specific access package.
```

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +GET /identityGovernance/entitlementManagement/accessPackageAssignments/additionalAccess(accessPackageId=`parameterValue`,incompatibleAccessPackageId=`parameterValue`)
```suggestion
GET /identityGovernance/entitlementManagement/accessPackageAssignments/additionalAccess(accessPackageId='parameterValue',incompatibleAccessPackageId='parameterValue')
```

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +The following table shows the parameters that can be used with this function.
The API.md indicates that the function parameters are mandatory.
```suggestion
The following table shows the parameters that must be supplied with this function.
```

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +If successful, this method returns a `200 OK` response code and an [accessPackageAssignment](../resources/accesspackageassignment.md) collection in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and a collection of [accessPackageAssignment](../resources/accesspackageassignment.md) objects in the response body.
```

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +When a result set spans multiple pages, Microsoft Graph returns that page with an `@odata.nextLink` property in the response that contains a URL to the next page of results. If that property is prese
Sounds like the API also supports optional query parameters, probably `$top` and `$select` to start us off. Please feel free to add an "Optional query parameters" H2 section after the "Function parameters" section and before the "Request headers" section.

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +}
Please share a real and "whole" response object. This sample indicates there aren't any instances of the assignments - so the response object should probably look different anyway.

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignment.md
> +| [additionalAccess](../api/accesspackageassignment-additionalaccess.md) [accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignment**
Same Q - Is this technically correct?
```suggestion
| [additionalAccess](../api/accesspackageassignment-additionalaccess.md) [accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignment** objects for users who have assignments to incompatible access packages.|
```

2022-04-26 19:55 UTC, FaithOmbongi commented on api-reference/beta/resources/entitlementmanagement-overview.md
> +| [additionalAccess](../api/accesspackageassignment-additionalaccess.md) [accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignment**
Same Q
```suggestion
| [additionalAccess](../api/accesspackageassignment-additionalaccess.md) [accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignment** objects for users who have assignments to incompatible access packages.|
```

2022-04-28 18:42 UTC, opbld32 commented
Docs Build status updates of commit _[e1c9b91](https://github.com/markwahl-msft/microsoft-graph-docs/commits/e1c9b919ae9662d6c53f69e3a775f9ecdcf2f69d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281831148261-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T18%3A42%3A18Z&sr=b&sp=r&sig=CL2lJ1Yuo1l58VtN%2F5uCQxymKnnOlytIh8%2FaC3EvicY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 18:51 UTC, opbld30 commented
Docs Build status updates of commit _[a437940](https://github.com/markwahl-msft/microsoft-graph-docs/commits/a4379404b388c63e65a021106ea062d9332edfa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281832591827-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T18%3A51%3A30Z&sr=b&sp=r&sig=zO5ZOQsBHIeHWbMHM%2F5f3tqlXgGVNrU8pUKrqNWrgTQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 18:54 UTC, opbld31 commented
Docs Build status updates of commit _[98b42cd](https://github.com/markwahl-msft/microsoft-graph-docs/commits/98b42cd5726baa313e79e84294df8ef26b658afa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281833459038-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T18%3A54%3A13Z&sr=b&sp=r&sig=FyT51LjCm7hVhqZ%2BvLMuO8g16efYaePVQsji9R%2BsU1o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 18:56 UTC, opbld33 commented
Docs Build status updates of commit _[d11ede4](https://github.com/markwahl-msft/microsoft-graph-docs/commits/d11ede401f6887828988e94df2f0e91855eb9662)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281850515704-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T18%3A56%3A35Z&sr=b&sp=r&sig=W6ZgEalyI8iuG%2B%2B2Lg0NXLuikquf%2BQoTiIMGICScpq8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 19:00 UTC, opbld34 commented
Docs Build status updates of commit _[edd595e](https://github.com/markwahl-msft/microsoft-graph-docs/commits/edd595e1884b9e968d0c0e0ed59feb93842a2262)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281858021625-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T19%3A00%3A17Z&sr=b&sp=r&sig=HxncaRFVwKKllqfe5aUjwyP8w%2FBgXSFgOr%2BuSJbK7L4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 19:00 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +| incompatibleAccessPackageId | String | Returns the assignments for users who also have assignments to another, incompatible, access package. |
updated to mark both as required.

2022-04-28 19:00 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignment-additionalaccess.md
> +}
added

2022-04-28 19:11 UTC, opbld31 commented
Docs Build status updates of commit _[2dccfd9](https://github.com/markwahl-msft/microsoft-graph-docs/commits/2dccfd946d64ba2d81ef6433f171a37ef8867f39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281905547721-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T19%3A11%3A28Z&sr=b&sp=r&sig=sbqPJuFB8LcWWqPKuP8BWx2Eff3jzGDxK2CsddIPtBc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 19:13 UTC, opbld34 commented
Docs Build status updates of commit _[f2545c3](https://github.com/markwahl-msft/microsoft-graph-docs/commits/f2545c3bb90afad3d73b3a5c85e9b3ba59d09122)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281906392916-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T19%3A13%3A45Z&sr=b&sp=r&sig=9HxzopWL4kpfuDeXhu1WCDHVDtABCeuu9krtCxD%2FvNQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 19:31 UTC, FaithOmbongi approved these changes

2022-04-29 02:12 UTC, opbld32 commented
Docs Build status updates of commit _[0ce9e84](https://github.com/markwahl-msft/microsoft-graph-docs/commits/0ce9e84d8cdc5a2fb8dfe425dd42ba6c93a8df90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/api-reference/beta/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-16495) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-emb-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204290209177475-16495%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T02%3A12%3A36Z&sr=b&sp=r&sig=sN9BqbAPRA7VKsvE6oYaBWsg8SMJtNqTk9xwAZCF7us%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 02:19 UTC, merged