Do Not Merge: Moving place type workspaces to public beta
microsoftgraph/microsoft-graph-docs pull request #16504
Opened 2022-04-12 19:00 UTC by slister1001

Updating place, room, roomList, and workspace related documentation to help us bring workspace documentation to public beta.

2022-04-12 19:02 UTC, opbld33 commented
Docs Build status updates of commit _[e4337ad](https://github.com/slister1001/microsoft-graph-docs/commits/e4337ad36b14e7cc421290327ed420a5b5f95b8c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-b1abcf61974b01c4e659557b10a30cb1-626a6455)
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-10eba85b9ff363757cbafc4269e5e11b-626a6455)
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-c9d03e80f109c768115cb82873558f70-626a6455)
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

<a id="b1abcf61974b01c4e659557b10a30cb1-626a6455"></a>
### [api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md)
 - **Line 161, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="10eba85b9ff363757cbafc4269e5e11b-626a6455"></a>
### [api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md)
 - **Line 237, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````
 - **Line 362, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 453, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="c9d03e80f109c768115cb82873558f70-626a6455"></a>
### [api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Outlook'.`````
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204121900190208-16504%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T19%3A02%3A23Z&sr=b&sp=r&sig=RtAUGMcIzuGmuDx4hTTIxnxL9EVz4g0RjXGOUqGl3lI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 20:54 UTC, opbld31 commented
Docs Build status updates of commit _[1e21b36](https://github.com/slister1001/microsoft-graph-docs/commits/1e21b36a651acd1f70c3204e2b509ff09ae5f657)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-b1abcf61974b01c4e659557b10a30cb1-18d94156)
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-10eba85b9ff363757cbafc4269e5e11b-18d94156)
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-c9d03e80f109c768115cb82873558f70-18d94156)
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

<a id="b1abcf61974b01c4e659557b10a30cb1-18d94156"></a>
### [api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md)
 - **Line 160, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="10eba85b9ff363757cbafc4269e5e11b-18d94156"></a>
### [api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md)
 - **Line 235, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````
 - **Line 424, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 514, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="c9d03e80f109c768115cb82873558f70-18d94156"></a>
### [api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Outlook'.`````
 - **Line 186, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204122052439270-16504%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T20%3A54%3A32Z&sr=b&sp=r&sig=Kyqh45XfUFqrpmgv2D%2FZcQN0Drz9ZFUn9aklnNvuio0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-12 21:05 UTC, opbld30 commented
Docs Build status updates of commit _[6ea6666](https://github.com/slister1001/microsoft-graph-docs/commits/6ea6666e015305f6108c0eea258418f0fd3a8a30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204122104069860-16504%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T21%3A05%3A58Z&sr=b&sp=r&sig=5z61NwFDebnLu7HfDMk3xMPPIxRFoK91V4YDNiIil2k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 02:02 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.Places.json
> +          "Description": "Removed the **spaces** relationship from [roomList](https://docs.microsoft.com/en-us/graph/api/resources/roomList?view=graph-rest-beta) resource.",
Lines 5-12:
The current public beta metadata doesn't have a spaces nav property in roomList, and the published docs don't have that either.
Was this changelist record generated by Graph Studio?
Either way, from the customers' perspective, this doesn't apply. Please remove these lines.

2022-05-05 02:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/roomlist.md
> +Represents a group of [room](room.md) and [workspace](workspace.md) objects defined in the tenant.
Can a roomlist include a combination of rooms and workspace resources? 
A roomlist doesn't have to be homogenous (only room resources or only workspace resources), is that right?

2022-05-05 02:09 UTC, angelgolfer-ms commented on api-reference/beta/resources/place.md
> +Exchange Online administrators can organize either meeting rooms or work spaces in a tenant into room lists. Using the places API, you can get all the room lists, rooms, or work spaces in the tenant,
Line 19:
The "either... or" indicates that a roomlist can have only rooms, or only work spaces, but not a mix. Can you confirm please?

2022-05-05 02:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/place.md
> -The [findRooms](../api/user-findrooms.md) and [findRoomLists](../api/user-findroomlists.md) functions support similar lookup for rooms and room lists in a tenant. The following is a comparison betwee
Lines 23-32:
Regarding findRooms and findRoomLists, they are still in the beta metadata and their docs still present them as beta API. So from the customers' perspective, nothing has changed since they got into beta.
Is there a better defined plan and timeline for their deprecation?

Meanwhile, without updating their docs, customers may still perceive them as a choice for similar use cases. We should keep the comparison section here until we're well into messaging their deprecation.

2022-05-05 02:21 UTC, angelgolfer-ms reviewed
Hi @slister1001 , I was responding to your internal ping on Teams and clarified what we need to prepare for a content review. I quickly browsed through your PR anyway and added a few comments.
Can you please provide what's needed per my Teams message for a proper content review?
Also, it would be helpful if you make clarifications per my comments in the PR.

Thanks.

2022-05-05 17:42 UTC, slister1001 commented on changelog/Microsoft.Exchange.Places.json
> +          "Description": "Removed the **spaces** relationship from [roomList](https://docs.microsoft.com/en-us/graph/api/resources/roomList?view=graph-rest-beta) resource.",
Yes, it was generated by Graph Studio based on changes made on my branch in the Workloads repo. I will remove these lines regardless.

2022-05-05 17:47 UTC, slister1001 commented on api-reference/beta/resources/place.md
> +Exchange Online administrators can organize either meeting rooms or work spaces in a tenant into room lists. Using the places API, you can get all the room lists, rooms, or work spaces in the tenant,
A roomlist can have both rooms and workspaces, I will update this line to reflect that.

2022-05-05 17:48 UTC, slister1001 commented on api-reference/beta/resources/place.md
> -The [findRooms](../api/user-findrooms.md) and [findRoomLists](../api/user-findroomlists.md) functions support similar lookup for rooms and room lists in a tenant. The following is a comparison betwee
I will keep the comparison section included in here. We are discussing a more concrete timeline for deprecation of these APIs, it has been in our backlog for some time now.

2022-05-05 20:43 UTC, opbld33 commented
Docs Build status updates of commit _[4302ef6](https://github.com/slister1001/microsoft-graph-docs/commits/4302ef6550ef468341d46e727477a11c06de9f5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052041327293-16504%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T20%3A43%3A51Z&sr=b&sp=r&sig=vRU3dl7e6lMhWiNzOw4LJKQubVxAgc%2FYIm5hper4MPg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 04:48 UTC, angelgolfer-ms commented on api-reference/beta/resources/place.md
> +Exchange Online administrators can organize meeting rooms and work spaces in a tenant into room lists. Using the places API, you can get all the room lists, rooms, or work spaces in the tenant, or ge
Line 19 and GLOBAL:
I just verified, and FYI, per Microsoft Writing Style Guide, when using the words "work" and "space" together in natural language, please use the term "workspace" with no space between them. 
See https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36451.

Related: when referring to the resource name, it's also "workspace", one word, except that you would apply a link to that topic workspace.md on first reference, or in subsequent references, style the word bold.

2022-05-10 06:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/place.md
> +Exchange Online administrators can organize meeting rooms and work spaces in a tenant into room lists. Using the places API, you can get all the room lists, rooms, or work spaces in the tenant, or ge
FYI I searched and replaced the use of "work space" (two words) in natural language in your PR by "workspace" (one word).
For a more consistent learning experience for customers, I also replaced the use of "work space" (two words) as values for displayName and nickname in your examples.

2022-05-10 06:46 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.Places.json
> +          "ChangedApiName": "workspaces",
Line 7:
Since this changelist record is about adding a nav property, ApiChange should be "Relationship".
See example 3 in the [changelog ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples) topic in the onboarding docs.

2022-05-10 06:50 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.Places.json
> +          "ChangedApiName": "workspaces",
Can you confirm if line 7 was what's generated by Graph Studio?
If that's the case, that's a bug we need to file for Graph Studio.

2022-05-10 07:20 UTC, angelgolfer-ms commented on api-reference/beta/resources/roomlist.md
> +Represents a group of [room](room.md) and [workspace](workspace.md) objects defined in the tenant.
Like this:
"Represents a group of [room](room.md) or [workspace](workspace.md) resources defined in the tenant. A **roomList** can contain a mix of **room** and **workspace** resources. " 
Use "or" in the first sentence.  Then add a sentence to state a roomList can contain both types.

2022-05-10 07:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/roomlist.md
> +Represents a group of [room](room.md) and [workspace](workspace.md) objects defined in the tenant.
FYI to reduce the churn, I updated line 16 on your behalf.

2022-05-10 07:48 UTC, angelgolfer-ms commented on api-reference/beta/api/place-list.md
Line 16:
The "for example" sentence has gotten a bit hard to parse; usually a sentence to give examples should include no more than 3 examples. In this context, I think it's worthwhile to list what is actually supported (rather than saying "for example").

2022-05-10 07:50 UTC, angelgolfer-ms commented on api-reference/beta/api/place-list.md
FYI I included a bullet list which basically reflects the examples in this topic, and links to each example for convenience for the customers. The bullet list would be easier to scan, and the links to examples can promote learning.

2022-05-10 07:51 UTC, angelgolfer-ms commented on api-reference/beta/api/place-list.md
> +All **room**, **workspace** and **roomList** are derived from the **place** object.
Line 24:
FYI I removed the "all". "All" can be ambiguous for Loc in this context. We simply want to say, each of those resources is derived from place.

2022-05-10 07:55 UTC, angelgolfer-ms commented on api-reference/beta/api/place-list.md
>  ## Permissions
FYI, I am adding back the sentence you deleted above back to the place-list.md topic, for reasons described in my previous pass:

"Compared with the [findRooms](../api/user-findrooms.md) and [findRoomLists](../api/user-findroomlists.md) functions, this operation returns a richer payload for rooms and room lists. See [details](../resources/place.md#using-the-places-api) for how they compare."

2022-05-10 08:06 UTC, opbld32 commented
Docs Build status updates of commit _[255c7e8](https://github.com/slister1001/microsoft-graph-docs/commits/255c7e8417c88e79544cbe0c967aa1743075384d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205100804084204-16504/BuildReport?accessString=bf786b8d3b7c1c6ff1e56ed78f9875c5e15ce6faff2dbfe398e611e8af0760ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 08:09 UTC, opbld33 commented
Docs Build status updates of commit _[88c1448](https://github.com/slister1001/microsoft-graph-docs/commits/88c14487c82f76a9f7e40b0c1bc2d5be47ecc90a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205100804269250-16504/BuildReport?accessString=cb064ad03c54478d283ba89d2f55ad75a8ba3359e743c326c3f224ac332d82e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 08:14 UTC, angelgolfer-ms requested changes
@slister1001 , I went ahead to go over your incorporation last week, thanks for doing that.
I also made some changes directly to your PR. Please feel free to take a look at my commit and let me know if you notice any issues or have any questions,

In the interest of time (as we're so close to Build), this time I reviewed your PR without first confirming what's in the api.md and CSDL files. That's usually not a reliable practice. Once you specify their location in an internal roadmap item, I'll take a look to make sure my understanding is consistent with those files. Please ping me on Teams once you have the roadmap item ready.

2022-05-12 04:46 UTC, opbld32 commented
Docs Build status updates of commit _[dfc61b6](https://github.com/slister1001/microsoft-graph-docs/commits/dfc61b65d572ec8486e9432e5c5d6e41e5e61b37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120444403227-16504/BuildReport?accessString=17a2fa4a2c2c15d2fcb1828e52804779a137c426a73be9da77fb9725cad79191).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 04:48 UTC, opbld31 commented
Docs Build status updates of commit _[b0e6c82](https://github.com/slister1001/microsoft-graph-docs/commits/b0e6c82820a91bc0b6427134d092ed6f0daa38c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120445019834-16504/BuildReport?accessString=7ce30366aee95e447e8c793d8f8e9021f716789f8ccbb0eb9da499851dfca2df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 04:54 UTC, angelgolfer-ms approved these changes
Hi @slister1001 ,
On you behalf, I addressed this [comment ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16504/files#r868872246) that I had left 2 days ago, so that we can wrap up this PR.
On your end, I still need you to confirm this other [comment ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16504/files#r868875500)to see if we need to file a bug for Graph Studio.



And after you do so, when your API is available to customers, you should please follow step 8 of the [content workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=workflow-for-internal-contributors-to-add-new-content-or-update-content), so that the docs can be published as well.

2022-05-12 15:59 UTC, slister1001 commented on changelog/Microsoft.Exchange.Places.json
> +          "ChangedApiName": "workspaces",
Yes, I can confirm that line 7 and the entirety of the changelog was generated by Graph Studio

2022-06-30 21:44 UTC, opbld33 commented
Docs Build status updates of commit _[825b4da](https://github.com/slister1001/microsoft-graph-docs/commits/825b4da9f077132561020afd6b98e691e0dcbc1d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-03686778)

<a id="03686778"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206302143359550-16504/BuildReport?accessString=d1fcc9a62873b3e38bda28b5cb2877152605e01eaaa1264eaf6f67669e37607e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 08:59 UTC, angelgolfer-ms commented on api-reference/beta/api/place-list.md
> +<!-- {
@slister1001 , I don't know how we missed this before, but can you address the following comments to all the new examples you added in this PR? 

I'm going to use this example 2 in place-list.md to describe what should be done:
There are lines like 244, 253 though 263, that you don't have to and shouldn't add; so please delete them. These lines are for the tabbed, language-specific code snippets that correspond to the REST API request. There's an automated weekly snippet update for all the new examples or modified examples that have been merged into main. As part of the weekly snippet update, any new examples, or existing examples that have been modified, would get 


Line 244: Delete th

2022-08-03 21:55 UTC, opbld31 commented
Docs Build status updates of commit _[63d194a](https://github.com/slister1001/microsoft-graph-docs/commits/63d194a6ba809d0e4fcfa123b4e17282c9e29a5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-b1abcf61974b01c4e659557b10a30cb1-df28b976)
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-10eba85b9ff363757cbafc4269e5e11b-df28b976)
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-c9d03e80f109c768115cb82873558f70-df28b976)
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

<a id="b1abcf61974b01c4e659557b10a30cb1-df28b976"></a>
### [api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md)
 - **Line 161, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="10eba85b9ff363757cbafc4269e5e11b-df28b976"></a>
### [api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md)
 - **Line 245, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````
 - **Line 519, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="c9d03e80f109c768115cb82873558f70-df28b976"></a>
### [api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md)
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208032152594847-16504/BuildReport?accessString=b30f7b05b230fe02f98789b2afb3d3a9d9d828328ac633ffeb0d0227933cbb4a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 21:58 UTC, angelgolfer-ms requested changes
@slister1001 , please address my comment about the lines you inserted to support upcoming code snippet for your new examples.

2022-08-04 02:02 UTC, opbld30 commented
Docs Build status updates of commit _[1f18ca9](https://github.com/slister1001/microsoft-graph-docs/commits/1f18ca9ae0965bd7b40f09b13e3a0b548cf426e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-b1abcf61974b01c4e659557b10a30cb1-de19e904)
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-c9d03e80f109c768115cb82873558f70-de19e904)
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

<a id="b1abcf61974b01c4e659557b10a30cb1-de19e904"></a>
### [api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md)
 - **Line 161, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="c9d03e80f109c768115cb82873558f70-de19e904"></a>
### [api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md)
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208040200244167-16504/BuildReport?accessString=9f94dc0b7f9ee6670b42a78edc7cbc3abf78b89c5a66f695bb04432f37213c1a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 02:04 UTC, opbld31 commented
Docs Build status updates of commit _[00462bd](https://github.com/slister1001/microsoft-graph-docs/commits/00462bdf71fb9b85a548d6433ed34274e5628cb5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) | [Details](#user-content-c9d03e80f109c768115cb82873558f70-6d9e954b)
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

<a id="c9d03e80f109c768115cb82873558f70-6d9e954b"></a>
### [api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md)
 - **Line 187, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208040202181560-16504/BuildReport?accessString=01d648ba30e5280f237c43b52cf0cadc30c4017c84e89aaa9fce71ce1e513272).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 02:07 UTC, opbld34 commented
Docs Build status updates of commit _[3b5d487](https://github.com/slister1001/microsoft-graph-docs/commits/3b5d4877b6034bce4608a5cd098ba9c7163b29f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208040205149652-16504/BuildReport?accessString=8168a732fe9fbce11a607d1a5cacb661f01885bb23ba3926a685877f5225d30a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 08:44 UTC, angelgolfer-ms requested changes
@slister1001 , it seems like you misunderstood my last comment about the code snippet lines. My comment applies to only the new examples you're adding to place-get.md, place-list.md, and place-update.md. My comment doesn't apply to the pre-existing examples, so please revert the changes to the pre-existing examples. If you don't do that, conceivably there can be a week or so lapse before the code snippet tool re-inserts the code snippets for various languages.

2022-08-05 18:21 UTC, opbld30 commented
Docs Build status updates of commit _[ffd1814](https://github.com/slister1001/microsoft-graph-docs/commits/ffd1814bbcb09dafd1bc0a42ed1238486f0f283a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208051819417847-16504/BuildReport?accessString=386d5c429806bac90828d4e289e38900a731dadeea2c157480a40f0914bd3d36).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 18:43 UTC, opbld34 commented
Docs Build status updates of commit _[6969d48](https://github.com/slister1001/microsoft-graph-docs/commits/6969d483feb640f509ecb3127e4e7def80033f7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208051841549973-16504/BuildReport?accessString=64d6b747e32e3c112941283e71beb3eb1d233d7343c16b26f35a0e1c64d2e78a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 18:53 UTC, opbld32 commented
Docs Build status updates of commit _[93bcfe1](https://github.com/slister1001/microsoft-graph-docs/commits/93bcfe1913eae69815fd8eac3fa55e098b0bbb27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208051850163739-16504/BuildReport?accessString=edfe3f744c3fa7faad1ed8064ee63a92271bffd27a5dd38ed34c381636d70ae1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-06 09:11 UTC, angelgolfer-ms commented on api-reference/beta/api/place-get.md
>    "name": "get_room"
After line 71:
FYI I inserted a sampleKeys property to specify the ID value 3162F1E1-C4C0-604B-51D8-91DA78989EB1 in your example request. It's something we recently started enforcing. It's for the Try-it experience. You can read up on sampleKeys in this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211782/Set-up-for-API-Doctor-validation?anchor=json-element-descriptions

2022-08-06 09:12 UTC, angelgolfer-ms commented on api-reference/beta/api/place-get.md
>    "name": "get_room"
FYI I added sampleKeys preceding every example request in place-get.md and place-update.md that has an ID value.

2022-08-06 09:17 UTC, opbld30 commented
Docs Build status updates of commit _[a502270](https://github.com/slister1001/microsoft-graph-docs/commits/a50227075e3ca04edae99c00fef5b30c252dbf1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208060914376869-16504/BuildReport?accessString=dc543191f8105b919e947bc66c359be08c26325c0be3624efaf1e8dc199b0a01).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-06 09:19 UTC, opbld30 commented
Docs Build status updates of commit _[e5023e6](https://github.com/slister1001/microsoft-graph-docs/commits/e5023e6c1528ce33be4b592b3b9838112b2b35a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208060915406537-16504/BuildReport?accessString=2632baac8e752201fd34a8aa7bed8b8ca61bade25c8dd882868a786532346547).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-06 09:23 UTC, angelgolfer-ms approved these changes
Please see the comments I added as FYI. I'm setting this PR to content review complete. Please set the PR to ready to merge so that the PR will be published on the next work day.

2022-08-10 04:24 UTC, opbld33 commented
Docs Build status updates of commit _[200dc98](https://github.com/slister1001/microsoft-graph-docs/commits/200dc98b018e354de0730252661092d5e0eba358)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208100423004115-16504/BuildReport?accessString=579468f9854ec7db00ae8ca0fbdfa2fc2d9e3aa29e2376375674d69bc2570f09).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 01:49 UTC, opbld33 commented
Docs Build status updates of commit _[4bd1d2e](https://github.com/slister1001/microsoft-graph-docs/commits/4bd1d2ef34fec380720616c51a361aa4f994bafc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208110147506327-16504/BuildReport?accessString=446e9ffb748a15a759a4a07ab0e9156b09ccb77333fdefe753d85bcdaa2306ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 01:58 UTC, opbld34 commented
Docs Build status updates of commit _[b1eaa79](https://github.com/slister1001/microsoft-graph-docs/commits/b1eaa79bb87b4194187fffad4dedf953a7e54a9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208110156133787-16504/BuildReport?accessString=454c4c075ae5fc31fc8d5cfa66a0b2cb4960b4ddfe9a8b47d5d1ce2596988bac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 02:35 UTC, opbld30 commented
Docs Build status updates of commit _[3ca11a5](https://github.com/slister1001/microsoft-graph-docs/commits/3ca11a53432d22434ffb8ee2877e454a28ae1bca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208110233356796-16504/BuildReport?accessString=5605edceda34b3f1525621af5cd1964f4ac9a295486dbd33a35829cf8084ecc6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 02:39 UTC, opbld34 commented
Docs Build status updates of commit _[a2554bb](https://github.com/slister1001/microsoft-graph-docs/commits/a2554bb72a5cba3bf244e0b094bf5f94b085c3fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208110235085142-16504/BuildReport?accessString=34f555b7ab83637c37dff06942dbf277d6824e05847e56c6108cdfc01dc63431).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 02:41 UTC, opbld33 commented
Docs Build status updates of commit _[59bfcdc](https://github.com/slister1001/microsoft-graph-docs/commits/59bfcdc6fdd038158e46251ebdd5edf1d9da9cd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/place-get.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-list.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/api/place-update.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/api/place-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/place.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/place.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/roomlist.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/roomlist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/roomlist?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[api-reference/beta/resources/workspace.md](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/api-reference/beta/resources/workspace.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/workspace?view=graph-rest-beta&branch=pr-en-us-16504) (graph-rest-beta) |
[changelog/Microsoft.Exchange.Places.json](https://github.com/slister1001/microsoft-graph-docs/blob/workspace-updates/changelog/Microsoft.Exchange.Places.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208110236589378-16504/BuildReport?accessString=0d915b5c9dd429b10e24e2a198975c747b4789080b3e57dd2b1aad9028099432).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 02:48 UTC, merged