Doc updates for allow resource data to be included in user context subscriptions for Microsoft Teams
microsoftgraph/microsoft-graph-docs pull request #16510
Opened 2022-04-12 23:05 UTC by eddie-lee-msft

Doc updates for allow resource data to be included in user context subscriptions for Microsoft Teams

2022-04-12 23:07 UTC, opbld31 commented
Docs Build status updates of commit _[5ed3bb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ed3bb0c47d39d441534b1ee490835f7f0d1a2d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204122305549062-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T23%3A07%3A41Z&sr=b&sp=r&sig=YuapQkTmuf8wmor0eGe%2BnxDI%2B8C41D5eXtRRY%2BHiX9o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 20:10 UTC, AkJo commented on api-reference/includes/teams-subscription-notes.md
> +**chatMessage** subscriptions can be specified to include resource data. If specified to include resource data, [encryption](/graph/webhooks-with-resource-data) is required. The subscription creation
You should perhaps add the following here to make it more obvious what a person must do to include resource data.

(**includeResourceData** must be `true`)

2022-04-25 20:11 UTC, AkJo commented on api-reference/includes/teams-subscription-notes.md
> +**chatMessage** subscriptions can be specified to include resource data. If specified to include resource data, [encryption](/graph/webhooks-with-resource-data) is required. The subscription creation
If specified to include resource data (**includeResourceData** set to true), then [encryption](/graph/webhooks-with-resource-data) is required. T

2022-04-25 21:17 UTC, eddie-lee-msft commented on api-reference/includes/teams-subscription-notes.md
> +**chatMessage** subscriptions can be specified to include resource data. If specified to include resource data, [encryption](/graph/webhooks-with-resource-data) is required. The subscription creation
Done

2022-04-25 21:19 UTC, opbld34 commented
Docs Build status updates of commit _[de9aebe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de9aebee224cef4548d3581805ece85c9ef46911)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252117057253-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T21%3A19%3A33Z&sr=b&sp=r&sig=wc%2BfR5YHnIc%2FN8tWPLttnJJUvBxxR8iMMNDBqygQRe8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 21:52 UTC, opbld31 commented
Docs Build status updates of commit _[61c5008](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61c5008cd315f7f0f2f0a393d41968174f81cd5e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cf3e527a)

<a id="cf3e527a"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252151568144-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T21%3A52%3A25Z&sr=b&sp=r&sig=CPXbJFvcKIkoBvUzw4HtOUiUkJMUrOP0I1KwyaoTKM8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 22:08 UTC, opbld34 commented
Docs Build status updates of commit _[19ed653](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19ed653135769f1ef3496c1655cb2e5d24017438)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252206076551-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T22%3A08%3A12Z&sr=b&sp=r&sig=WHS%2Frv60BYP6drjyrW%2BAgaPRpmOaa6PdN78VovtkoIU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 17:45 UTC, opbld31 commented
Docs Build status updates of commit _[370f9a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/370f9a413785f8a3c2de7ac97fcef2a2ae1ed27a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204261728356061-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T17%3A45%3A32Z&sr=b&sp=r&sig=m7m3g%2FnKAI8pRQ24laOnP0xk0lj3yB3WEgs86foDc3c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 00:29 UTC, angelgolfer-ms commented on api-reference/includes/teams-subscription-notes.md
@eddie-lee-msft , related to the changes in line 12:
Am I correct in deducing that for chatMessage, you want to set straight both delegated and application permissions support notifications with resource data now?
If that is the supported behavior, then can you confirm ONLY creating subscription (with resource data) to chatMessage resources **using application permission** falls into "protected API" category (i.e., need to request prior permission), but using delegated permission does not? 

(I see your sentence is "... you MAY need to request access".)

If delegated permissions do NOT require requesting prior access, then I strongly suggest you clarify this in line 12. Something like:
"Before creating a chatMessage subscription with application permissions, make sure to request access to the chatMessage data. For details, see Protected APIs in..."
The reason is these conditions that are up to the customer to decide for their scenarios - such as do they want resource data, can they just use delegated permission, or do they need to use application permission - they further add burden to the customer when creating a subscription. So it would be helpful for the docs to be more prescriptive / clear, than using "may..."

On the other hand, if it turns out delegated permissions also require requesting prior access, then please remove the "may", and update the "Protected APIs in Microsoft Teams" topic, which currently lists scenarios using only application permissions. 

Or, is there a more complicated decision tree involved here other than delegated vs application permissions? If so, please elaborate here and we can decide whether to bring it up here or in the "Protected API in Microsoft Teams" topic.



to create subscription to chatMessage "Protected APIs in Microsoft Teams"?

2022-04-27 01:08 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "notifications",
Lines 4950 and 4968:
FYI when we specify the "ApiChange" as "Resource", we are saying that the change is applied to a resource that is / should be named in the "ChangedApiName" property. In this changelog update, that's not appropriate because "notifications" isn't a resource name for our subject in question (notifications for resource changes).

FYI the appropriate way to update the changelog is to note the behavioral change to the POST operation of the subscription entity. Something like this, for each of beta and v1.0 version.

          "Id": "e473f528-d700-4803-9985-6db1bde5c1ab",
          "ApiChange": "Method",
          "ChangedApiName": "POST",
          "ChangeType": "Addition",
          "Description": "Added support for [subscribing to notifications](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta) with resource data in delegated context for [chatMessage](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta) resources in a [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) or [channel](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta).",
          "Target": "subscription"

2022-04-27 01:11 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "notifications",
BTW, I noticed your changelog description (lines 4952 and 4970) say "teams, channels, and chats".
I thought the change is in subscribing to change notifications for chatMessage, just from looking at the other updates currently in this PR.
Do you think the docs are clear for what you listed ("teams, channels, and chats")?
I just wanted to have you confirm first before we trace through the docs to see where clarification or update is necessary.

2022-04-27 06:41 UTC, angelgolfer-ms requested changes
Hi @eddie-lee-msft , @Danielabom who's your content reviewer asked me a question on the changelog for this PR, hence I entered a few comments, some outside of the context of the changelog. Please take a look. If you have questions, please ping me on Teams.

2022-04-27 07:26 UTC, AkJo approved these changes

2022-04-27 17:41 UTC, eddie-lee-msft commented on api-reference/includes/teams-subscription-notes.md
You are right. Requesting Protected API access is only relevant in application context. I will make a change with your suggestion.

2022-04-27 17:49 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "notifications",
@angelgolfer-ms, I probably should have given more context in the description of this PR.

We are enabling change notifications with resource data in delegated context for every Microsoft Teams resource type that is supported in user context today. You can see those here: https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http. Any resource that has "chats", "teams", or "channels" in it that has support in delegated context is affected by this enablement. One example is "/teams/{id}/channels/{id}/messages". One non-example is "/chats/getAllMessages" because it is not supported in delegated context.

Now, you might be curious why this PR has such few changes. I looked through all the docs in the current state, and the large majority of them **already mention** that resource data is supported for those resources, without **any** mention of a specific context. Rather it is mentioned in a generic manner. One such example is here: https://docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership. You will see that there is mention that resource data is allowed, but nothing about specific contexts.

If there is any place I have missed, please do let me know.

2022-04-27 17:52 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "notifications",
Also given above context, please let me know what the appropriate changelog addition should be. I wasn't sure myself.

2022-04-27 20:25 UTC, eddie-lee-msft commented on api-reference/includes/teams-subscription-notes.md
Added the clarification

2022-04-27 20:28 UTC, opbld30 commented
Docs Build status updates of commit _[b156669](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b156669484939a142e285b7e673e697f056fc7ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204272024392715-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T20%3A28%3A14Z&sr=b&sp=r&sig=uZEyP2isUsiz1kyKG1AHCXA5UjXMohjxEFKTA%2FFBjl8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 05:04 UTC, opbld30 commented
Docs Build status updates of commit _[03f182d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03f182d3fa13df859352afff528eb274ee72b174)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280501349807-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T05%3A04%3A10Z&sr=b&sp=r&sig=Y40kGsf0vVeFUfsXj2%2Bc0KdlJDBVuj7nZrhIHm1nATs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 05:17 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "notifications",
Thanks, @eddie-lee-msft , for the clarification.
I traced through the current 5 Teams concept topics for change notifications and agree for the purpose of this PR, we've documented all the use cases (resources) which allow subscribing to rich notifications using delegated permissions (and application permissions).

Please update your changelist records for this PR as follows, for each of beta and v1:

```
     "Id": "e473f528-d700-4803-9985-6db1bde5c1ab",
      "ApiChange": "Method",
      "ChangedApiName": "POST",
      "ChangeType": "Addition",
      "Description": "Added support for [subscribing to notifications](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta) with resource data in delegated context for [chatMessage](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta) resources in a specified [channel](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta) or [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta).",
      "Target": "subscription"
```

As described in my earlier comment in this thread, the appropriate angle is to focus on the additive (we're supporting delegated perms in addition to the previous support of application perms) change to the behavior of the POST operation of the subscription entity.

2022-04-28 08:54 UTC, angelgolfer-ms requested changes
Hi @eddie-lee-msft , I verified the explanation in your reply, thanks. I also adjusted my comment about the changelist records, please take a look.
As a side effect of going through the related topics, I noticed there are a few things that over time, authors have been missing some facts about Teams notifications. I included a list in an email. It would be good if you or your team can align the various topics for Teams.

2022-04-28 17:40 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "notifications",
Changelog has been updated with your suggestion.

2022-04-28 17:51 UTC, opbld31 commented
Docs Build status updates of commit _[4ca37d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ca37d8ce24e9cee8c2e1177070a541beb10c4a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281740186578-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T17%3A51%3A37Z&sr=b&sp=r&sig=mC1oUhQwa3I8r%2F1zHjYbBKDaFnJ2jDohQ9T6%2FYbcMFI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 20:36 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "subscription"
Oh, @eddie-lee-msft , please make the links in line 4970 to point to v1.0, not beta.

2022-04-28 20:47 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +          "Target": "subscription"
Whoops, fixed.

2022-04-28 20:51 UTC, opbld30 commented
Docs Build status updates of commit _[0a852d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a852d7f1fb806592403404e62b644ab303652ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204282047328011-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T20%3A51%3A44Z&sr=b&sp=r&sig=g2QPyRJoAOdYtlEpx05VUw2wFY0KQd2A6UiPOzclHnE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 21:12 UTC, angelgolfer-ms approved these changes
PR looks good, thanks!

2022-04-29 02:16 UTC, opbld33 commented
Docs Build status updates of commit _[8302ef6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8302ef64e3a7d14155e7fb87d823ef279a8b2609)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204290211128166-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T02%3A16%3A16Z&sr=b&sp=r&sig=Ap7VfM63N%2FbOnhFieYsdiMUKzwUMeYZzGW4zxDoJI14%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 02:19 UTC, opbld34 commented
Docs Build status updates of commit _[9ba589c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ba589c0be1fe39c86a14b88d099af4c9cdabfd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16510) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16510) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/EnableRichNotificationsForUserContextSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16510) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204290212240014-16510%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T02%3A19%3A16Z&sr=b&sp=r&sig=9u5vNN8Sp%2FdByEKrMvh%2FxC5J%2FhXn3e%2FrLCMDSIB2DkY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-29 02:20 UTC, merged