Update onpremisespublishing.md
microsoftgraph/microsoft-graph-docs pull request #16556
Opened 2022-04-18 23:11 UTC by dhruvinrshah

Document change to add onPremisesApplicationSegments property to the onPremisesPublishing API doc.

2022-04-18 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[1867ca4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1867ca478480da9c053c597c84afd3794669541c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-dae6106e)

<a id="349a98d540ddf811f1da1205fd2aef0f-dae6106e"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 41, Column 35**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onpremisesapplicationsegments.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204182311599301-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T23%3A14%3A35Z&sr=b&sp=r&sig=p2yMbun6xbCqlRgdl3sYB7nLd7uWFBES5ME30dhSp8o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 19:21 UTC, opbld34 commented
Docs Build status updates of commit _[3acc4f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3acc4f3de8903374c8f01393aab1c09084085bd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-30d15407)
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="349a98d540ddf811f1da1205fd2aef0f-30d15407"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 41, Column 35**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onpremisesapplicationsegments.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204191918554901-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T19%3A21%3A06Z&sr=b&sp=r&sig=qV88HbUixeLLwS2Gsi7%2FbvFuGlTv2Cvf5EinZPezWzk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 20:20 UTC, opbld32 commented
Docs Build status updates of commit _[f9c3904](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9c39044c3e2db16173356d4cd66de0a3949a063)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-9fa55da8a5a61902572108b5a6fa8d55-3d3909f9)
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-3d3909f9)
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9fa55da8a5a61902572108b5a6fa8d55-3d3909f9"></a>
### [api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md)
 - **Line 16, Column 38**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onPremisesApplicationSegment.md'.`````

<a id="349a98d540ddf811f1da1205fd2aef0f-3d3909f9"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 41, Column 35**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onpremisesapplicationsegments.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192018437303-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T20%3A20%3A41Z&sr=b&sp=r&sig=ku0Y1nyGwj%2F%2FhZOqAg77ySzhIW9cxdqHZQd8TObCQYA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 22:58 UTC, opbld30 commented
Docs Build status updates of commit _[e4d14be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4d14be76acc3640bed2c663686b539696b213f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-349a98d540ddf811f1da1205fd2aef0f-ef03e597)
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-9fa55da8a5a61902572108b5a6fa8d55-ef03e597)
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-d8c8128135a9e82a2a6758df01af0d62-ef03e597)
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="349a98d540ddf811f1da1205fd2aef0f-ef03e597"></a>
### [api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md)
 - **Line 41, Column 35**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'onpremisesapplicationsegments.md'.`````

<a id="9fa55da8a5a61902572108b5a6fa8d55-ef03e597"></a>
### [api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

<a id="d8c8128135a9e82a2a6758df01af0d62-ef03e597"></a>
### [api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192255450295-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T22%3A57%3A59Z&sr=b&sp=r&sig=a8gQlxoRUsAWickt6xGaYEV4x4UmspSAmK8ACRlNSAg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 23:08 UTC, opbld32 commented
Docs Build status updates of commit _[a5706f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5706f3172243955fe01d7880a6103b877d37e04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-9fa55da8a5a61902572108b5a6fa8d55-95fe6374)
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-d8c8128135a9e82a2a6758df01af0d62-95fe6374)
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9fa55da8a5a61902572108b5a6fa8d55-95fe6374"></a>
### [api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

<a id="d8c8128135a9e82a2a6758df01af0d62-95fe6374"></a>
### [api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192305107077-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T23%3A08%3A03Z&sr=b&sp=r&sig=fTGbClXdief0JJiFfDjW2oHkre5UbCvZ%2BCy4RiNa7YQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 23:10 UTC, opbld31 commented
Docs Build status updates of commit _[3b6e2b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b6e2b899daecba2241dd9cd59a89fdee5a92a41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-9fa55da8a5a61902572108b5a6fa8d55-ed57c766)
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-d8c8128135a9e82a2a6758df01af0d62-ed57c766)
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9fa55da8a5a61902572108b5a6fa8d55-ed57c766"></a>
### [api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

<a id="d8c8128135a9e82a2a6758df01af0d62-ed57c766"></a>
### [api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192308226763-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T23%3A10%3A29Z&sr=b&sp=r&sig=l%2Bp9oYauWEKbjI3kXMhyIsBnRwLUMo4FILhGZNlE6kk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 23:19 UTC, opbld32 commented
Docs Build status updates of commit _[2989940](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29899402d41cb1acd09c3b00cae4c9a17cae13bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-9fa55da8a5a61902572108b5a6fa8d55-724df573)
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) | [Details](#user-content-d8c8128135a9e82a2a6758df01af0d62-724df573)
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9fa55da8a5a61902572108b5a6fa8d55-724df573"></a>
### [api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

<a id="d8c8128135a9e82a2a6758df01af0d62-724df573"></a>
### [api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents the CORS settings for an on-premises application segment published via Application Proxy.' is duplicated in 'beta/resources/corsConfiguration.md(3,14)', 'beta/resources/onPremisesApplicationSegment.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192317168910-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T23%3A19%3A06Z&sr=b&sp=r&sig=44GaNSZgFxexYx5OhMtDgwVP4A63OTwNf0bADTmQCVU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 23:26 UTC, opbld32 commented
Docs Build status updates of commit _[1d8b988](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d8b988c17c943c1e14b30a6373e37b7afad22ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192324238871-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T23%3A26%3A35Z&sr=b&sp=r&sig=Jkjl1ua4Wpa5%2F0fD%2BzzBTkcUu8%2BXnSCvltKPYYL6Ngs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 23:34 UTC, opbld33 commented
Docs Build status updates of commit _[2ad100d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ad100d2951d13da68c08e07a404ac55d870d7d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192333056125-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T23%3A34%3A50Z&sr=b&sp=r&sig=sXzN%2FpxiF2UVU9Xqbk8HQmTPoKhUHThQBsJAYkh2KiA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 23:36 UTC, opbld33 commented
Docs Build status updates of commit _[3743db3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3743db3753cc470ca8b4d6e6c79e23bb94df5b26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onPremisesApplicationSegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onPremisesApplicationSegment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204192334366268-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T23%3A36%3A41Z&sr=b&sp=r&sig=tKMWm%2BqbpSgXQI4asnoVd0uSyKP2bhJuKE8wD1SWkQc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 15:49 UTC, FaithOmbongi requested changes
Thank you @dhruvinrshah for your work on this PR.

- I've made suggestions for minor fixes. Please verify they are technically correct.
- Plus, I understand the new property is updatable. Please include it in the table of updatable properties (Request body section) in the [Update application](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&tabs=http#request-body) topic.

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onpremisespublishing.md
> +|onPremisesApplicationSegments | [onPremisesApplicationSegments](onPremisesApplicationSegment.md) collection| Represents the application segment collection for a on-premises wildcard application. |
```suggestion
|onPremisesApplicationSegments | [onPremisesApplicationSegment](onPremisesApplicationSegment.md) collection| Represents the application segment collection for an on-premises wildcard application.  |
```

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onPremisesApplicationSegment.md
> +---
Change the file name to lowercase characters

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onPremisesApplicationSegment.md
> +Represents [onPremisesApplicationSegment](onPremisesApplicationSegment.md) object when publishing an on-premises wildcard application with Azure AD Application Proxy. This resource is used for settin
Same Q as in the metadata
```suggestion
Represents the configuration for wildcard application publishing through Azure AD Application Proxy. This provides an efficient way to configure many on-premises applications with the same settings. Use this resource to configure the **onPremisesApplicationSegments** property for a particular wildcard application.
```

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onPremisesApplicationSegment.md
> +|corsConfigurations|[corsConfiguration](corsConfiguration.md) Collection|CORS Rule definition for particular application segment.|
```suggestion
|alternateUrl|String|If you are configuring a traffic manager in front of multiple App Proxy application segments, the **alternateUrl** is the user-friendly URL that will point to the traffic manager.|
|corsConfigurations|[corsConfiguration](corsConfiguration.md) Collection|CORS rule definition for particular application segment.|
```

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onPremisesApplicationSegment.md
> +|internalUrl|String |The internal url of the application segment. For example, https://intranet/.|
Minor formatting
```suggestion
|externalUrl|String |The published external url for the application segment. For example, `https://intranet.contoso.com/`.|
|internalUrl|String |The internal url of the application segment. For example, `https://intranet/`.|
```

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onPremisesApplicationSegment.md
> +  "baseType": null
```suggestion
```

2022-04-26 15:49 UTC, FaithOmbongi commented on api-reference/beta/resources/onPremisesApplicationSegment.md
> +}
Always include the @odata.type. Copied from the stubs.
```suggestion
{
  "@odata.type": "#microsoft.graph.onPremisesApplicationSegment",
  "externalUrl": "String",
  "internalUrl": "String",
  "alternateUrl": "String",
  "corsConfigurations": [
    {
      "@odata.type": "microsoft.graph.corsConfiguration"
    }
  ]
}
```

2022-05-05 22:06 UTC, opbld33 commented
Docs Build status updates of commit _[b149a69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b149a69427f0f1ceec44393fe6fe3f3bfb5110d4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-305c848d)

<a id="305c848d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052206054639-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A06%3A43Z&sr=b&sp=r&sig=e3pA4VTlJBipSJFxIDWs9Qp5j6%2Bl3j%2BkSBS%2B0F8JfCc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:08 UTC, opbld31 commented
Docs Build status updates of commit _[201d218](https://github.com/microsoftgraph/microsoft-graph-docs/commits/201d2183c7bce692e9d6c110aeeb7a4299a56ea0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9a9e2161)

<a id="9a9e2161"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052207348676-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A08%3A04Z&sr=b&sp=r&sig=8vvWufYitag9wxELDVLBk9C4UHu9Bp0pqgWAl%2FjWk1Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:09 UTC, opbld30 commented
Docs Build status updates of commit _[9b06ba3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b06ba32cca944b0534d9c7bb1f5db3c675a7df9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b5196fc6)

<a id="b5196fc6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052208401538-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A09%3A08Z&sr=b&sp=r&sig=t6zQZRpHO65QNhwtKWvUn9uO4hKUDUOcuCZEDV5G708%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:10 UTC, opbld34 commented
Docs Build status updates of commit _[8d9d59a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d9d59aa6e130d91284a0538f54fc04dac7566b2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-afdb4c68)

<a id="afdb4c68"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052209347481-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A10%3A10Z&sr=b&sp=r&sig=grxauLVzbBseGLR1Gcp7wguR79VLrhN%2BFnnZajS45A8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:11 UTC, dhruvinrshah commented on api-reference/beta/resources/onpremisespublishing.md
> +|onPremisesApplicationSegments | [onPremisesApplicationSegments](onPremisesApplicationSegment.md) collection| Represents the application segment collection for a on-premises wildcard application. |
Since a collection can have multiple application segments would it make sense to use plural "onPremisesApplicationSegments" ??

2022-05-05 22:13 UTC, opbld32 commented
Docs Build status updates of commit _[a24b9aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a24b9aabc03dfdad1604fc2d6a84f5f0b7f8c13b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-46b7abf7)

<a id="46b7abf7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052212442314-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A13%3A09Z&sr=b&sp=r&sig=tDtTQbk7RGaa6XVUuZkbbuPrfXARFCpG04sSwoojhvA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:14 UTC, opbld34 commented
Docs Build status updates of commit _[94d23f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94d23f6110db47458b0662be9949b80435c75f8a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b490c53d)

<a id="b490c53d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052213021024-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A14%3A04Z&sr=b&sp=r&sig=JI4PAE9raGRLFZB4LZobX7OSFj%2Bw85vwC9cO6Etymrc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:14 UTC, opbld33 commented
Docs Build status updates of commit _[7db8608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7db86082255310fafd179ade21edc069cc9fc307)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0d1c506b)

<a id="0d1c506b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052213390481-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A14%3A40Z&sr=b&sp=r&sig=Jw0XpZ%2Bw1FVwO1LIPFb8%2BqAwJKJfKzQUXamWHDz2Vmc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:15 UTC, opbld32 commented
Docs Build status updates of commit _[9e88b3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e88b3a134916f614092b2a531cbd7cd35021188)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-652381c9)

<a id="652381c9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052214178366-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A15%3A28Z&sr=b&sp=r&sig=quItuO3vyeRGDdkitzNpRPiU6Y4vVfP0%2FviJNOUlyX8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:16 UTC, opbld30 commented
Docs Build status updates of commit _[b3b250e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3b250ec5f656b93f4ca20742ff506ad90354904)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-586843a5)

<a id="586843a5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052215018357-16556%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T22%3A16%3A14Z&sr=b&sp=r&sig=vy7qi3KDqrTVd4IWXqFhr82c42heZP98t3J1JobC2vk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 22:21 UTC, dhruvinrshah commented
> Thank you @dhruvinrshah for your work on this PR.
> 
> * I've made suggestions for minor fixes. Please verify they are technically correct.
> * Plus, I understand the new property is updatable. Please include it in the table of updatable properties (Request body section) in the [Update application](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&tabs=http#request-body) topic.

This is a property under parent "OnPremisesPublishing" which is already listed as updatable property.


onPremisesPublishing | onPremisesPublishing | Represents the set of properties for configuring Azure AD Application Proxy for an on-premises application. This property can only be set after the application has been created and cannot be updated in the same request as other application properties.

2022-06-24 10:08 UTC, FaithOmbongi commented
Heads up @dhruvinrshah - I see the schema for these changes is already live and this PR continues to attract merge conflicts.  Please resolve the issues so the PR becomes mergeable?

2022-08-29 11:28 UTC, FaithOmbongi approved these changes

2022-08-30 02:15 UTC, opbld31 commented
Docs Build status updates of commit _[eb3b418](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb3b41835d629ad91f5cfc4abcc37237471e0d2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300213191198-16556/BuildReport?accessString=e225cb2b9d788e959233423517f1c97ab3b608d6b180360fb9270f37e67d6678).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 02:18 UTC, opbld30 commented
Docs Build status updates of commit _[440d1af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/440d1afe09c9d2d1ac46f68f339d137adf47fe47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/corsconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/corsconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/corsconfiguration?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisesapplicationsegment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisesapplicationsegment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisesapplicationsegment?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[api-reference/beta/resources/onpremisespublishing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/api-reference/beta/resources/onpremisespublishing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onpremisespublishing?view=graph-rest-beta&branch=pr-en-us-16556) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/dhruvinrshah-patch-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300214149491-16556/BuildReport?accessString=82b444b1a7bd1ec9ed584bcb8a4b156eec76782ab364c43ab7eff77760aa3eac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 02:22 UTC, merged