Add documents for device delta
microsoftgraph/microsoft-graph-docs pull request #16565
Opened 2022-04-19 16:53 UTC by msdhou

This change included all the required documents for the new device delta API.

2022-04-19 16:55 UTC, opbld30 commented
Docs Build status updates of commit _[298e862](https://github.com/msdhou/microsoft-graph-docs/commits/298e862a3efd04996dbeaaa8dd85fa7e8133cea2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-11f8076b)

<a id="11f8076b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204191653543305-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T16%3A55%3A38Z&sr=b&sp=r&sig=uyb3iIePDXzcSoi5HT7va7FPrQkBLBJkEw24uvARBUQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 17:01 UTC, opbld33 commented
Docs Build status updates of commit _[29e77b5](https://github.com/msdhou/microsoft-graph-docs/commits/29e77b58dd70772dddfbb1567d7184fed64b5f9f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-8417e257)
[api-reference/v1.0/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-8417e257)
[api-reference/beta/resources/device.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-8417e257"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````
 - **Line 28, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/device-list' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/device-list' will be broken in isolated environments. Replace with a relative link.`````

<a id="c737893372c2f56288a79889f7c03505-8417e257"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````
 - **Line 28, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/device-list' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/device-list' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204191659153506-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T17%3A01%3A03Z&sr=b&sp=r&sig=MRYs4N9DPrmTrbs7yVtwooee%2BSiHOz3ADgenGY0lNnI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 00:28 UTC, Lauragra commented
@msdhou , please follow the Get started steps to set yourself up to be a contributor to the repo so that you can follow our content workflow for review and publishing. Thanks.

2022-05-05 21:57 UTC, opbld34 commented
Docs Build status updates of commit _[835a317](https://github.com/msdhou/microsoft-graph-docs/commits/835a3171807b002f2f1edf73aa64ba55006a7048)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-6033621e)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-6033621e)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-6033621e"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-6033621e"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205052155147975-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T21%3A57%3A46Z&sr=b&sp=r&sig=TM%2BfbtZ4dpoQc1J0z8OYt6qS2vytnbagCuP5iW2YsqI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 16:13 UTC, opbld32 commented
Docs Build status updates of commit _[7d93a56](https://github.com/msdhou/microsoft-graph-docs/commits/7d93a56e593c455f789885d20f024293e0abb908)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-164159ca)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-164159ca)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-164159ca"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-164159ca"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205061611245031-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T16%3A13%3A44Z&sr=b&sp=r&sig=7NtOd5HfsZaNd3ZcQdAMgYGO7a4GAMPass6m0znl2qE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 16:36 UTC, opbld33 commented
Docs Build status updates of commit _[9b0b6cc](https://github.com/msdhou/microsoft-graph-docs/commits/9b0b6cc7568c3659c08f21242de6ceedd115a539)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-a62af104)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-a62af104)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-a62af104"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-a62af104"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205061634082240-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T16%3A36%3A07Z&sr=b&sp=r&sig=u9k%2FIL50Un9zo6NfjmVC8JS6gziyTjFMiThGvJBZveg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 18:35 UTC, opbld33 commented
Docs Build status updates of commit _[2e30c39](https://github.com/msdhou/microsoft-graph-docs/commits/2e30c392acfdad41fd7e5858286c1ca2532dfed3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-18d66547)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-18d66547)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-18d66547"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-18d66547"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091831458923-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T18%3A35%3A23Z&sr=b&sp=r&sig=qsyKx1waeEBxQP5i%2Fy6j4X%2FMaI5yclPu3k4y5SZhClo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 18:51 UTC, opbld33 commented
Docs Build status updates of commit _[2ff736b](https://github.com/msdhou/microsoft-graph-docs/commits/2ff736bbf16f39d82f1ce5a371d128a2a9342a50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-63b0f73d)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-63b0f73d)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-63b0f73d"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-63b0f73d"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091849361012-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T18%3A51%3A49Z&sr=b&sp=r&sig=0kKpacuL7B68%2FetDq2iziDWraKJuVmGtkbVho6ra89o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 19:01 UTC, opbld32 commented
Docs Build status updates of commit _[b7ecd37](https://github.com/msdhou/microsoft-graph-docs/commits/b7ecd3716eec4c980f9b4e75a7cf5f030f7835a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-12b74e80)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-12b74e80)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-12b74e80"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-12b74e80"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091850521046-16565%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T19%3A01%3A22Z&sr=b&sp=r&sig=cOTbj58r4bly5RzP1O0WHy05vTFXmS8HEjqxr3rdP%2B8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 19:19 UTC, FaithOmbongi requested changes
Hi @msdhou - remember to add the changelog and update the ms.prod to "directory-management" to clear up the warnings in your PR.

2022-05-24 19:53 UTC, opbld31 commented
Docs Build status updates of commit _[b10ad20](https://github.com/msdhou/microsoft-graph-docs/commits/b10ad20710c0e7f7fe3029beeefd255603bbf5b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) | [Details](#user-content-8626c9354e6264d256a7f37f8528d1f3-e3a601da)
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) | [Details](#user-content-c737893372c2f56288a79889f7c03505-e3a601da)
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

<a id="8626c9354e6264d256a7f37f8528d1f3-e3a601da"></a>
### [api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

<a id="c737893372c2f56288a79889f7c03505-e3a601da"></a>
### [api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'devices'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205241944484735-16565/BuildReport?accessString=282af16c7d6b823ebd4de481b028644e0aa543e0fd20bd0619af8887845aafa0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-25 00:04 UTC, opbld34 commented
Docs Build status updates of commit _[f8f9812](https://github.com/msdhou/microsoft-graph-docs/commits/f8f9812912f630b4b9ad990c18bed6acdf3ef9a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/api/device-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205250002093025-16565/BuildReport?accessString=9ab08b0edc2c28c63dbe9479abed98250fe620c122e7f2d9fb23a53943bf519a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 23:32 UTC, opbld30 commented
Docs Build status updates of commit _[8cde099](https://github.com/msdhou/microsoft-graph-docs/commits/8cde099f2cbf9f030ac1f76d33b1d121588f02ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/api/device-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/api/device-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/device.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-overview.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207182329559426-16565/BuildReport?accessString=b580b491226f3ce09f4e1bd9284670f244e49212e1bff5ebc1c2cc805b5a87bc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 09:21 UTC, opbld33 commented
Docs Build status updates of commit _[ba3959f](https://github.com/msdhou/microsoft-graph-docs/commits/ba3959f855e673c79e5cbde37fcc757eaacc78d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/api/device-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-beta&branch=pr-en-us-16565) (graph-rest-beta) |
[api-reference/v1.0/api/device-delta.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/api/device-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/device.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-delta?view=graph-rest-1.0&branch=pr-en-us-16565) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-overview.md](https://github.com/msdhou/microsoft-graph-docs/blob/device-delta/concepts/delta-query-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-16565) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190919111700-16565/BuildReport?accessString=ed6bf0452f2cfc008cea3287dd0adcf44929a399d11b1abbbefb69f8b0669417).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 18:15 UTC, FaithOmbongi approved these changes

2023-03-03 03:27 UTC, merged