Updated SDKs overview
microsoftgraph/microsoft-graph-docs pull request #16585
Opened 2022-04-20 22:38 UTC by Linda-Editor

Updated list of languages to point to GitHub repos instead of Get started pages. Also did a copy edit pass.

2022-04-20 22:40 UTC, opbld34 commented
Docs Build status updates of commit _[3cfc73c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3cfc73cf33c0728aeed7e434a0aa0c1542eb95a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/linda-editor-sdk-overview/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-16585) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204202238272534-16585%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T22%3A40%3A14Z&sr=b&sp=r&sig=t97qVNTumvTrLrm7xMBiKq0rPQS97aqi3k5wu19Obe8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 23:04 UTC, Lauragra commented on concepts/sdks/sdks-overview.md
> +## Additional resources
FYI, we use "See also" instead of Additional resources in the Graph docs for voice/tone.

2022-04-20 23:08 UTC, Lauragra commented on concepts/sdks/sdks-overview.md
> +* For a list of SDKs and samples for Microsoft Graph, see the [Microsoft Graph resources page](https://developer.microsoft.com/en-us/graph/gallery/?filterBy=Samples,SDKs).
Maybe we should remove SDKs from this sentence and update the link to this: https://developer.microsoft.com/en-us/graph/gallery/?filterBy=Samples. We're including the SDKs here in this topic so we don't need to link to the gallery for the SDKs.

I should also make sure that the SDKs in the gallery line up with the list we have in this topic.

2022-04-21 15:52 UTC, Linda-Editor commented on concepts/sdks/sdks-overview.md
> +## Additional resources
Done

2022-04-21 15:52 UTC, opbld31 commented
Docs Build status updates of commit _[1d00263](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d002635f595253bbcc575df17a045b44d8abf46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/linda-editor-sdk-overview/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-16585) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204211549490962-16585%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T15%3A52%3A17Z&sr=b&sp=r&sig=8hO60EuEXDwHIbKLl56H%2BW%2FC6IVnxuwyk5IJFdOEbXo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 16:07 UTC, jasonjoh requested changes

2022-04-21 18:52 UTC, Linda-Editor commented on concepts/sdks/sdks-overview.md
> +- [TypeScript](https://github.com/microsoftgraph/msgraph-sdk-typescript)
Done

2022-04-21 18:54 UTC, opbld32 commented
Docs Build status updates of commit _[d04990c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d04990c6f43bd0b363a21c93beb86cfdce2693c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/sdks/sdks-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/linda-editor-sdk-overview/concepts/sdks/sdks-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/sdks/sdks-overview?branch=pr-en-us-16585) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204211852026545-16585%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T18%3A54%3A24Z&sr=b&sp=r&sig=smSnXIumJfUH2exhUg9FRErfBpFA4z8sAtTcfpUfIKI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 02:11 UTC, merged