AR scoping for direct vs transitive group members
microsoftgraph/microsoft-graph-docs pull request #16583
Opened 2022-04-20 18:55 UTC by FaithOmbongi

2022-04-20 18:58 UTC, opbld30 commented
Docs Build status updates of commit _[2d8f297](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d8f2974cb296057d62fc1ff7e2c1387993d9912)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-16583) | [Details](#user-content-f6520df0844c6aa340c79b43d533fa6d-0617894a)

<a id="f6520df0844c6aa340c79b43d533fa6d-0617894a"></a>
### [concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md)
 - **Line 255, Column 239**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-5-review-all-guest-users-assigned-to-all-teams' in 'accessreviews-scope-concept.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204201855490152-16583%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T18%3A58%3A54Z&sr=b&sp=r&sig=83%2BSCGFfOUky3GVHyd0YOwsDQYq1NjnhYd7OhkVnnYo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 19:09 UTC, opbld33 commented
Docs Build status updates of commit _[7543479](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7543479324112433edf7a52b434433629fe670da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-16583) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204201905537326-16583%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T19%3A09%3A00Z&sr=b&sp=r&sig=2ESqWa1tgtdDtGCaicYL7A%2Ba8ftOxIwoGyJEFc4BwFc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 17:21 UTC, opbld32 commented
Docs Build status updates of commit _[4ea666a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ea666a00481f5716cd0852346f72580c2cd1aae)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c8f695d)

<a id="5c8f695d"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221720327076-16583%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T17%3A21%3A16Z&sr=b&sp=r&sig=VAYmBJqJ0BGJ0Ub6a%2BVRSp6mzMfbm2NaVO61fwLKIOI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 18:30 UTC, isabelleatmsft requested changes

2022-04-22 18:30 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +The following example scopes the review to only direct members of the group who are users.
```suggestion
The following example creates a review of each Microsoft 365 group that contains guest users. For the review instance on each group, the review is scoped to only direct members of the group who are users.
```

2022-04-22 18:30 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +### Example 4: Review all users and groups assigned to all groups
Shouldn't this be "Assigned to a group", not all groups? If so, I'm thinking we switch the order of ex 3 and ex 4.

2022-04-22 18:30 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +### Example 7: Review all inactive guest users assigned to all Microsoft 365 groups
Nit: does this need to be it's own example? what if we added two parts to ex 5 - part 1 is all guest users assigned to all m365 groups, and part 2 is all INACTIVE guest users assigned to all m365 groups.

same feedback for example 8 and example 6

2022-04-22 18:30 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +### Example 9: Review all assignment to Entitlement Management access packages
Nit: here is where we jump from reviews of groups to reviews of access packages, then privileged roles. I wonder if we should add headers to make it clearer?

2022-04-22 18:30 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +### Example 11: Review all users assigned to a privileged role (all active and eligible assignments included)
Nit: what if we combined ex 11,12,13 in to one 3 part example, like i suggested above for inactive users?

2022-04-22 18:36 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +### Example 4: Review all users and groups assigned to all groups
ACK. Corrected.

2022-04-22 18:38 UTC, opbld33 commented
Docs Build status updates of commit _[67f22e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67f22e8d11f369490207da146ea2d1d4eb8fc2fb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-16583) | [Details](#user-content-f6520df0844c6aa340c79b43d533fa6d-b71564ba)
[concepts/data-connect-quickstart-04.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-04.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-04?branch=pr-en-us-16583) | [Details](#user-content-7a262add4d39da6e734ada62359d017d-b71564ba)
[api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-remoteassistance-allowedremoteassistanceactions?view=graph-rest-beta&branch=pr-en-us-16583) (graph-rest-beta) | [Details](#user-content-dd051a7be8ae777c0d0a1d7c8bb481ba-b71564ba)
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16583) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-b71564ba)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16583) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-b71564ba)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-b71564ba)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16583) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-b71564ba)
[concepts/data-connect-quickstart-03.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-03.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-03?branch=pr-en-us-16583) | [Details](#user-content-7db385b8a4b22670a3acd8da69bf8a33-b71564ba)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16583) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-b71564ba)
[concepts/data-connect-quickstart-02.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-02.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-02?branch=pr-en-us-16583) | [Details](#user-content-38c98686334a186496079b022f8ac4b2-b71564ba)
[concepts/connecting-external-content-build-quickstart-04-configure-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-04-configure-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-04-configure-app?branch=pr-en-us-16583) | [Details](#user-content-a00e640699abfd9f250b6eac4dd922d8-b71564ba)
[concepts/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-01.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-01?branch=pr-en-us-16583) | [Details](#user-content-369c8945d629ff719bcdc2119dac2ff7-b71564ba)
[concepts/connecting-external-content-build-quickstart-02-register-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-02-register-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-02-register-app?branch=pr-en-us-16583) | [Details](#user-content-bf7e7fc2e1488b8379519bb1bf990026-b71564ba)
[concepts/connecting-external-content-build-quickstart-06-run-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-06-run-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-06-run-app?branch=pr-en-us-16583) | [Details](#user-content-e1a26798586da77894d1265baca82f59-b71564ba)
[concepts/connecting-external-content-build-quickstart-05-create-db.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-05-create-db.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-05-create-db?branch=pr-en-us-16583) | [Details](#user-content-8cf4b2b28399a08f993779830baa3e93-b71564ba)
[concepts/connecting-external-content-build-quickstart-09-summary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-09-summary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-09-summary?branch=pr-en-us-16583) | [Details](#user-content-22f9745b47bcf4aef74b68a012876aba-b71564ba)
[concepts/connecting-external-content-build-quickstart-08-search-results.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-08-search-results.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-08-search-results?branch=pr-en-us-16583) | [Details](#user-content-bc12a081a7d1a693b726f60cccb50b5d-b71564ba)
[concepts/connecting-external-content-build-quickstart-07-surface-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-07-surface-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-07-surface-data?branch=pr-en-us-16583) | [Details](#user-content-cc96779f1a77351d8397d2723ad58e5a-b71564ba)
[concepts/connecting-external-content-build-quickstart-03-build-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-03-build-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-03-build-app?branch=pr-en-us-16583) | [Details](#user-content-75c9d80b83e078d88064d6e03fce904f-b71564ba)
[concepts/connecting-external-content-build-quickstart-01-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-01-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-01-intro?branch=pr-en-us-16583) | [Details](#user-content-456d16c7db1174de4cba15bd98e0be21-b71564ba)
[concepts/data-connect-quickstart-08.m [...]

2022-04-22 18:43 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +### Example 7: Review all inactive guest users assigned to all Microsoft 365 groups
Agreed. Great suggestion. Applied.

2022-04-22 18:49 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +### Example 11: Review all users assigned to a privileged role (all active and eligible assignments included)
Sounds good. Applied.

2022-04-22 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[7cab88d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cab88db2f74ba71ecf202d33612c54eff178f0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-16583) | [Details](#user-content-f6520df0844c6aa340c79b43d533fa6d-64d3699d)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-64d3699d)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16583) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-64d3699d)
[api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-remoteassistance-allowedremoteassistanceactions?view=graph-rest-beta&branch=pr-en-us-16583) (graph-rest-beta) | [Details](#user-content-dd051a7be8ae777c0d0a1d7c8bb481ba-64d3699d)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16583) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-64d3699d)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16583) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-64d3699d)
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-16583) (graph-rest-beta) | [Details](#user-content-4b4cde67ab6990d14f4f235249feffee-64d3699d)
[api-reference/v1.0/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewhistorydefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-1.0&branch=pr-en-us-16583) (>= graph-rest-1.0) | [Details](#user-content-2f09786af2b98accaf18ad2155a131d0-64d3699d)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16583) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-64d3699d)
[concepts/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-01.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-01?branch=pr-en-us-16583) | [Details](#user-content-369c8945d629ff719bcdc2119dac2ff7-64d3699d)
[concepts/connecting-external-content-build-quickstart-05-create-db.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-05-create-db.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-05-create-db?branch=pr-en-us-16583) | [Details](#user-content-8cf4b2b28399a08f993779830baa3e93-64d3699d)
[concepts/connecting-external-content-build-quickstart-04-configure-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-04-configure-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-04-configure-app?branch=pr-en-us-16583) | [Details](#user-content-a00e640699abfd9f250b6eac4dd922d8-64d3699d)
[concepts/connecting-external-content-build-quickstart-03-build-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-03-build-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-03-build-app?branch=pr-en-us-16583) | [Details](#user-content-75c9d80b83e078d88064d6e03fce904f-64d3699d)
[concepts/connecting-external-content-build-quickstart-08-search-results.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-08-search-results.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-08-search-results?branch=pr-en-us-16583) | [Details](#user-content-bc12a081a7d1a693b726f60cccb50b5d-64d3699d)
[concepts/connecting-external-content-build-quickstart-09-summary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-09-summary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-09-summary?branch=pr-en-us-16583) | [Details](#user-content-22f9745b47bcf4aef74b68a012876aba-64d3699d)
[concepts/data-connect-quickstart-02.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-02.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-02?branch=pr-en-us-16583) | [Details](#user-content-38c98686334a186496079b022f8ac4b2-64d3699d)
[concepts/data-connect-quickstart-03.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-03.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-03?branch=pr-en-us-16583) | [Details](#user-content-7db385b8a4b22670a3acd8da69bf8a33-64d3699d)
[concepts/connecting-external-content-build-quickstart-01-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-01-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-01-intro?branch=pr-en-us-16583) | [Details](#user-content-456d16c7db1174de4cba15bd98e0be21-64d3699d)
[concepts/connecting-external-content-build-quickstart-02-register-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-02-register-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-02-register-app?branch=pr-en-us-16583) | [Details](#user-content-bf7e7fc2e1488b8379519bb1bf990026-64d3699d)
[concepts/data-connect-quickstart-04.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-04.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-04?branch=pr-en-us-16583) | [Details](#user-content-7a262add4d39da6e734ada62359d017d-64d3699d)
[concepts/connecting-external-conten [...]

2022-04-22 18:57 UTC, opbld31 commented
Docs Build status updates of commit _[7f06931](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f069311f58f1e9cd5d876cc8256af4b0cd1d99b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-16583) | [Details](#user-content-f6520df0844c6aa340c79b43d533fa6d-5d6838ba)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16583) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-5d6838ba)
[concepts/connecting-external-content-build-quickstart-07-surface-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-07-surface-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-07-surface-data?branch=pr-en-us-16583) | [Details](#user-content-cc96779f1a77351d8397d2723ad58e5a-5d6838ba)
[api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-remoteassistance-allowedremoteassistanceactions?view=graph-rest-beta&branch=pr-en-us-16583) (graph-rest-beta) | [Details](#user-content-dd051a7be8ae777c0d0a1d7c8bb481ba-5d6838ba)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-5d6838ba)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16583) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-5d6838ba)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16583) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-5d6838ba)
[concepts/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-01.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-01?branch=pr-en-us-16583) | [Details](#user-content-369c8945d629ff719bcdc2119dac2ff7-5d6838ba)
[concepts/data-connect-quickstart-02.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-02.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-02?branch=pr-en-us-16583) | [Details](#user-content-38c98686334a186496079b022f8ac4b2-5d6838ba)
[concepts/connecting-external-content-build-quickstart-08-search-results.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-08-search-results.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-08-search-results?branch=pr-en-us-16583) | [Details](#user-content-bc12a081a7d1a693b726f60cccb50b5d-5d6838ba)
[concepts/data-connect-quickstart-04.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-04.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-04?branch=pr-en-us-16583) | [Details](#user-content-7a262add4d39da6e734ada62359d017d-5d6838ba)
[concepts/connecting-external-content-build-quickstart-01-intro.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-01-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-01-intro?branch=pr-en-us-16583) | [Details](#user-content-456d16c7db1174de4cba15bd98e0be21-5d6838ba)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16583) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-5d6838ba)
[concepts/data-connect-quickstart-03.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-03.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-03?branch=pr-en-us-16583) | [Details](#user-content-7db385b8a4b22670a3acd8da69bf8a33-5d6838ba)
[concepts/connecting-external-content-build-quickstart-05-create-db.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-05-create-db.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-05-create-db?branch=pr-en-us-16583) | [Details](#user-content-8cf4b2b28399a08f993779830baa3e93-5d6838ba)
[concepts/connecting-external-content-build-quickstart-04-configure-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-04-configure-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-04-configure-app?branch=pr-en-us-16583) | [Details](#user-content-a00e640699abfd9f250b6eac4dd922d8-5d6838ba)
[concepts/connecting-external-content-build-quickstart-09-summary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-09-summary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-09-summary?branch=pr-en-us-16583) | [Details](#user-content-22f9745b47bcf4aef74b68a012876aba-5d6838ba)
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16583) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-5d6838ba)
[concepts/connecting-external-content-build-quickstart-06-run-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-06-run-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-06-run-app?branch=pr-en-us-16583) | [Details](#user-content-e1a26798586da77894d1265baca82f59-5d6838ba)
[concepts/connecting-external-content-build-quickstart-02-register-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-02-register-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-02-register-app?branch=pr-en-us-16583) | [Details](#user-content-bf7e7fc2e1488b8379519bb1bf990026-5d6838ba)
[concepts/connecting-external-content-build-quickstart-03-build-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob [...]

2022-04-22 19:58 UTC, isabelleatmsft approved these changes

2022-04-26 03:43 UTC, merged