Bulk reprovision add response
microsoftgraph/microsoft-graph-docs pull request #16589
Opened 2022-04-21 03:30 UTC by xumzheng

Add Bulk reprovision response for the API

2022-04-21 03:32 UTC, opbld32 commented
Docs Build status updates of commit _[d1f0981](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1f0981f0e446f5556c8f6eb5efd86d77d9f4e96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) | [Details](#user-content-879fd3bbbf51720e239aa65a1d9f184e-f24fad5a)

<a id="879fd3bbbf51720e239aa65a1d9f184e-f24fad5a"></a>
### [api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md)
 - **Line 111, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210330369098-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A32%3A10Z&sr=b&sp=r&sig=6QnLwy90n%2Fn8Es9FnYvc%2FbyE%2BBHJrMWpDzJy3EU%2FGNw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 03:34 UTC, opbld33 commented
Docs Build status updates of commit _[3cd1c57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3cd1c577807025f907488d7d600fbcd67a309ae1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210332520234-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A34%3A33Z&sr=b&sp=r&sig=mu6ulikD%2B1cAdYxuJkxQIB2r2NUM18az%2BkzFcx54o8M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 04:30 UTC, opbld32 commented
Docs Build status updates of commit _[573afcc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/573afcca541e7763e7a484e18e07c1c9332d3f20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210427165499-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T04%3A30%3A28Z&sr=b&sp=r&sig=ENQVH%2F77Phlr9yKx1r1%2B1Ml456NmP3W3tFITK7TuQXM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 05:21 UTC, opbld34 commented
Docs Build status updates of commit _[1957a50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1957a508aff5860d85b8a05364b0d02307e6747d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210519200535-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T05%3A21%3A18Z&sr=b&sp=r&sig=n49G%2FQUOgcVr2aLC%2BSnRItVtXHyJOSXelpTxs1jxyUs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 05:23 UTC, opbld31 commented
Docs Build status updates of commit _[fdbf14f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdbf14fddde9fee716edf3ee2ac127e2060792b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210520445752-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T05%3A23%3A08Z&sr=b&sp=r&sig=BQQaS17B7v7P%2FOs89w0xMfBsJbcVBe5khBCr2ApxWHw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 05:43 UTC, opbld33 commented
Docs Build status updates of commit _[ad44e34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad44e34737bd9e762c6261db0089d86aac0f1677)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210541165664-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T05%3A43%3A22Z&sr=b&sp=r&sig=I8BE6RH8W4Xls4XTd%2BJVA8dfveevKsd2xTiXRumxFeo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 06:10 UTC, opbld34 commented
Docs Build status updates of commit _[c444465](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c444465871e92cbd96aca517aa141c3470cdac94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210608362710-16589%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T06%3A10%3A31Z&sr=b&sp=r&sig=6svxvalAvovLm%2Frlhj6GMCVJNE1aldlxjPH0TbB4Okg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:08 UTC, RuiHou105 requested changes
@xumzheng please create a roadmap workitem and attach the workitem number in the description. Here is an example https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/12481/.

 If you don't have access to this repo, you can: 
Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-04-25 05:45 UTC, xumzheng commented
> @xumzheng please create a roadmap workitem and attach the workitem number in the description. Here is an example https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/12481/.
> 
> If you don't have access to this repo, you can: Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) . Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

@RuiHou105 Added it to the first comment.
For convenience, paste it here too
Roadmap work item no: 13986

2022-04-25 05:58 UTC, AshleyYangSZ approved these changes

2022-04-26 06:15 UTC, RuiHou105 approved these changes

2022-05-11 06:48 UTC, RuiHou105 commented
@Lauragra , @JarbasHorst , as the graph schema already went alive, so could you please help review this PR? Thanks!

2022-05-12 02:14 UTC, Lauragra approved these changes

2022-05-12 02:16 UTC, opbld31 commented
Docs Build status updates of commit _[e0aa9b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0aa9b5690e6318ce8604d9d68c0e2f61df3376b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120213452242-16589/BuildReport?accessString=5097694cd20b128c0ceef9f3236f657146e365d357ee39d0cba683deb1dfc4bc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:37 UTC, opbld34 commented
Docs Build status updates of commit _[ad8a104](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad8a104db5c01edb1d698d94ce49c52d21735698)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/manageddevice-bulkreprovisioncloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/manageddevice-bulkreprovisioncloudpc?view=graph-rest-beta&branch=pr-en-us-16589) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xumzheng/BulkReprovisionAddResponse/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120334488264-16589/BuildReport?accessString=8e73f7966fa44579d98d53f5d9fe59caf7ca88ff56ac9543d9e9c9a3cae05ce7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:40 UTC, merged