Azure AD reporting: Adding defaultMethod to Auth Methods report and sessionControlsNotSatisfied to applied CA
microsoftgraph/microsoft-graph-docs pull request #16590
Opened 2022-04-21 03:33 UTC by besiler

Added

- SessionControlNotSatisified to appliedConditionalAccessPolicy
- defaultMethod to auth method report

2022-04-21 03:35 UTC, opbld30 commented
Docs Build status updates of commit _[3f8261d](https://github.com/besiler/microsoft-graph-docs/commits/3f8261df47124e3b3f105d3743cc227cb2f1014c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-444f559d)
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-444f559d"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204210333393707-16590%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T03%3A35%3A17Z&sr=b&sp=r&sig=PL%2FTPy2%2BKTp5ko5Ek2JO3QLW0lIvk0om%2FmpsbXopHds%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 18:54 UTC, FaithOmbongi requested changes
Thank you @besiler for your work on this PR. A few fixes plus add the two new properties to the respective JSON representation sections.

2022-04-27 18:54 UTC, FaithOmbongi commented on api-reference/beta/resources/userregistrationdetails.md
> +|defaultMethod|String|The method the user or admin selected as default for performing multi-factor authentication for the user.|
Is it only for MFA?

2022-04-27 18:54 UTC, FaithOmbongi commented on api-reference/beta/resources/userregistrationdetails.md
> +|defaultMethod|String|The method the user or admin selected as default for performing multi-factor authentication for the user.|
Is it only for MFA?

2022-04-27 18:54 UTC, FaithOmbongi commented on api-reference/beta/resources/userregistrationdetails.md
>  |isMfaRegistered|Boolean|Whether the user has registered a strong authentication method for multi-factor authentication. The method may not necessarily be allowed by the [authentication methods polic
Please add the method to the JSON representation

2022-04-27 18:54 UTC, FaithOmbongi commented on api-reference/beta/resources/appliedconditionalaccesspolicy.md
> +|sessionControlsNotSatisfied|String collection|Refers to the session controls that a sign-in activity did not satisfy. (Example: “Application enforced Restrictions”).||
Please also ad this new property to the JSON representation
```suggestion
|sessionControlsNotSatisfied|String collection|Refers to the session controls that a sign-in activity did not satisfy. (Example: `Application enforced Restrictions`).||
```

2022-04-27 18:54 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
Minor fixes
```suggestion
          "Description": "Added the **sessionControlsNotSatisfied** property to the [appliedConditionalAccessPolicy](https://docs.microsoft.com/en-us/graph/api/resources/appliedConditionalAccessPolicy?view=graph-rest-beta) resource.",
          "Target": "appliedConditionalAccessPolicy"
        }
      ],
      "Id": "3e4f113d-2b6b-4bb1-9cd7-24fa265f5e2a",
      "Cloud": "Prod",
      "Version": "beta",
      "CreatedDateTime": "2022-04-18T23:23:47.3148004Z",
      "WorkloadArea": "Reports",
```

2022-04-27 18:54 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
Minor fixes
```suggestion
          "Description": "Added the **defaultMethod** property to the [userRegistrationDetails](https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationDetails?view=graph-rest-beta) resource.",
          "Target": "userRegistrationDetails"
        }
      ],
      "Id": "5527244c-2c92-4dea-ba34-b18e3a7c3ba2",
      "Cloud": "Prod",
      "Version": "beta",
      "CreatedDateTime": "2022-04-18T21:35:40.9738581Z",
      "WorkloadArea": "Reports",
```

2022-04-28 00:19 UTC, besiler commented on api-reference/beta/resources/userregistrationdetails.md
> +|defaultMethod|String|The method the user or admin selected as default for performing multi-factor authentication for the user.|
Yes, I think the concept of "default" only applies to MFA, even though the auth methods are used more broadly. The MFA team refers to it that way in the existing Graph docs: https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0

![image](https://user-images.githubusercontent.com/69605773/165651693-a11eb248-4cc2-4721-abe1-64d540931138.png)

2022-04-28 00:25 UTC, opbld30 commented
Docs Build status updates of commit _[7a00e2d](https://github.com/besiler/microsoft-graph-docs/commits/7a00e2d941009719cb8da697f1de5116adec4694)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-7a2c93ee)
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-7a2c93ee"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280021467675-16590%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T00%3A25%3A32Z&sr=b&sp=r&sig=DncKJlKGaCg8%2Fx96yU0Z11HWhxG0Tx4B9ptiPooq95M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 00:35 UTC, besiler commented on api-reference/beta/resources/userregistrationdetails.md
>  |isMfaRegistered|Boolean|Whether the user has registered a strong authentication method for multi-factor authentication. The method may not necessarily be allowed by the [authentication methods polic
Added

2022-04-28 00:38 UTC, opbld30 commented
Docs Build status updates of commit _[34876b0](https://github.com/besiler/microsoft-graph-docs/commits/34876b0918b272b3ab551851e2f742b6f1d02efb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-b5fd2ee3)
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-b5fd2ee3"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204280035015146-16590%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T00%3A38%3A44Z&sr=b&sp=r&sig=bqUwwVnVbZCN4dziUR%2BVT4L1ta1uKFSjBjsAIHsvWXo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 00:43 UTC, besiler commented
@FaithOmbongi resolved the questions/suggestions above, but the Graph review team has asked us to do defaultMethod as an enum instead. I'll make that change once the devs have a new PR with changelog etc. 

For now, we should keep this PR marked as not ready to merge please

2022-05-10 21:00 UTC, opbld34 commented
Docs Build status updates of commit _[4289010](https://github.com/besiler/microsoft-graph-docs/commits/4289010bbb024db0d9e5ed9dc51d5c4729a74828)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-843a6383)
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/api/userregistrationdetails-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/userregistrationdetails-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userregistrationdetails-get?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-843a6383"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205102056490257-16590/BuildReport?accessString=58941645a65bb1f1ab1c8ba550b8a29977bd2738fda3a714872bbad4588d39e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 21:09 UTC, besiler commented
@FaithOmbongi I updated defaultMfaMethod to an enum based on guidance from the Graph architects. This should be ready to merge if you don't have further comments

2022-05-10 21:09 UTC, opbld33 commented
Docs Build status updates of commit _[4c4f09c](https://github.com/besiler/microsoft-graph-docs/commits/4c4f09c10d448844fd67950c5e626a9fff5b1fa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-afbf84ee)
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/api/userregistrationdetails-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/userregistrationdetails-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userregistrationdetails-get?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-afbf84ee"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205102105406810-16590/BuildReport?accessString=886c4ab912ecd33a7725df711a950ad2daa7ce6e1b1a49f7e13e501ec7891cc3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 10:36 UTC, FaithOmbongi approved these changes
Hi @besiler - Changes look good. Added one suggestion to resolve the Build warning. Otherwise, approved.

2022-05-26 00:37 UTC, opbld30 commented
Docs Build status updates of commit _[3b93f67](https://github.com/besiler/microsoft-graph-docs/commits/3b93f6738fe2bd2e43c3b218950a1a9aa45d397e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/api/userregistrationdetails-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/userregistrationdetails-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userregistrationdetails-get?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205260027262352-16590/BuildReport?accessString=91d68d4b5ad005b8bb1a13a98714db28604f2ce61ebc698b73a86556dfa061ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-26 04:16 UTC, opbld33 commented
Docs Build status updates of commit _[5656e1e](https://github.com/besiler/microsoft-graph-docs/commits/5656e1ea31dc55a87d9bee089f8db210255d1114)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/api/userregistrationdetails-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/userregistrationdetails-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userregistrationdetails-get?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/userregistrationdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta&branch=pr-en-us-16590) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-Q42022/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205260414189560-16590/BuildReport?accessString=9ef26fd4a12b8bbaea320cde5bf7e0d510092f5af4d5771d944fbe2034fc09b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-26 04:20 UTC, merged