Added new property for Entity credentialuserregistrationssummary.
microsoftgraph/microsoft-graph-docs pull request #16605
Opened 2022-04-21 22:35 UTC by puzzle7k

Updated the doc for Entity credentialuserregistrationssummary.

We are adding one more property named "mfaExcludedUserCount".

2022-04-21 22:37 UTC, opbld30 commented
Docs Build status updates of commit _[be93d33](https://github.com/puzzle7k/microsoft-graph-docs/commits/be93d33ebdada8a45f53340188e269c8ac6e11e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-get?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-credentialuserregistrationssummary?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204212235486369-16605%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T22%3A37%3A31Z&sr=b&sp=r&sig=2olaFYHbH1Fo%2BZzJem%2BZFI5dlSfF%2B5mw9hSGD%2BxXrBQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 17:38 UTC, opbld32 commented
Docs Build status updates of commit _[5142e52](https://github.com/puzzle7k/microsoft-graph-docs/commits/5142e529273310b934d85d4065ac897526b4f6c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-get?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-credentialuserregistrationssummary?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/puzzle7k/microsoft-graph-docs/blob/dev/kimz_m365LH/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251735170470-16605%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T17%3A38%3A41Z&sr=b&sp=r&sig=AXeOq09ABb53SUWAqilGNcK08X1JDxwv%2Fe8PqqSX7dw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-27 18:11 UTC, Danielabom commented on changelog/Microsoft.MultiTenantPlatform.json
> +                "Description": "Added the **mfaExcludedUserCount** property to the [credentialUserRegistrationsSummary](https://docs.microsoft.com/en-us/graph/api/resources/managedTenants-credentialU
When we add links in our page, locale shouldn't be hard-coded in the URL. Please update it.

2022-04-27 18:25 UTC, puzzle7k commented on changelog/Microsoft.MultiTenantPlatform.json
> +                "Description": "Added the **mfaExcludedUserCount** property to the [credentialUserRegistrationsSummary](https://docs.microsoft.com/en-us/graph/api/resources/managedTenants-credentialU
Fixed.

2022-04-27 20:12 UTC, Danielabom commented on api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md
> +|mfaExcludedUserCount|Int32|The number of users in the MFA Exclusion Security Group (M365 Lighthouse - MFA Exclusions). Optional. Read-only.|
Please use multi-factor authentication like in line 30 and remove the capital letters from the words "Exclusion, Security Group, and Exclusions.

2022-04-27 20:13 UTC, Danielabom requested changes
Hi, this PR is in great shape, just some minor comments. 
Please address them accordingly. Thanks!

2022-04-27 20:54 UTC, puzzle7k commented on api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md
> +|mfaExcludedUserCount|Int32|The number of users in the MFA Exclusion Security Group (M365 Lighthouse - MFA Exclusions). Optional. Read-only.|
Fixed.  

I keep the capital letter in the word "Exclusions" since "M365 Lighthouse - MFA Exclusions" is the group name.

2022-04-27 20:56 UTC, opbld32 commented
Docs Build status updates of commit _[320e044](https://github.com/puzzle7k/microsoft-graph-docs/commits/320e04467004544c286d4fcd10000691fc6bbcc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-get?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-credentialuserregistrationssummary?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/puzzle7k/microsoft-graph-docs/blob/dev/kimz_m365LH/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204272053359779-16605%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T20%3A56%3A16Z&sr=b&sp=r&sig=EFGqGfnghlmTulBldolfS4K2HhXWVimbXPdzaOZt%2BNs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 14:31 UTC, Danielabom approved these changes

2022-04-30 00:12 UTC, opbld31 commented
Docs Build status updates of commit _[b09df17](https://github.com/puzzle7k/microsoft-graph-docs/commits/b09df1768086d57f37abb7b266e8121f570a975a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-get?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/managedtenants-credentialuserregistrationssummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-credentialuserregistrationssummary?view=graph-rest-beta&branch=pr-en-us-16605) (graph-rest-beta) |
[changelog/Microsoft.MultiTenantPlatform.json](https://github.com/puzzle7k/microsoft-graph-docs/blob/dev/kimz_m365LH/changelog/Microsoft.MultiTenantPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204300008469346-16605%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-31T00%3A12%3A02Z&sr=b&sp=r&sig=qc%2FpTlb3Eumo5a%2FmEMY9VLYTNMN2YtM2sC1C5AWWGsE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 17:09 UTC, Danielabom approved these changes
Changes look good. Thanks!

2022-06-03 02:22 UTC, opbld34 commented
Docs Build status updates of commit _[060c807](https://github.com/puzzle7k/microsoft-graph-docs/commits/060c807bcf8f324781ece02561059d94aa517b90)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4621b3c7)

<a id="4621b3c7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206030219573042-16605/BuildReport?accessString=2d3865c121ce3373a08c7a6dad52c38d6c44748ef8f2495939f6e95a4c408038).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 04:01 UTC, merged