Delta Queries V1.0 Documentation
microsoftgraph/microsoft-graph-docs pull request #16618
Opened 2022-04-22 15:00 UTC by adarshgh

Delta Queries Documentation for Graph V1.0 based off beta.
Added two new files for delta assignments and delta categories.
Added Get Delta in tables necessary under resource folder.

2022-04-22 15:01 UTC, opbld30 commented
Docs Build status updates of commit _[2f98b0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f98b0f7112d86fb318592ad5c0ef2e550fa1770)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationassignment-delta.md) | :x:Error | | [Details](#user-content-70987e81d122f8151fed510a57c0ecbd-cd9b1d95)
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationcategory-delta.md) | :x:Error | | [Details](#user-content-568cbd011fdb63f3d034a5ecdeca90ef-cd9b1d95)
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :bulb:Suggestion | | [Details](#user-content-8ab1e5dc4e719fd194c2ad760dda591a-cd9b1d95)

<a id="70987e81d122f8151fed510a57c0ecbd-cd9b1d95"></a>
### [api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationassignment-delta.md)
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-assignments-delta-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-assignments-delta-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-assignments-delta-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-assignments-delta-java-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-assignments-delta-go-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-assignments-delta-powershell-snippets.md'.`````
 - **Line 237, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-assignments-delta-csharp-snippets.md'.`````
 - **Line 241, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-assignments-delta-javascript-snippets.md'.`````
 - **Line 245, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-assignments-delta-objc-snippets.md'.`````
 - **Line 249, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-assignments-delta-java-snippets.md'.`````
 - **Line 253, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-assignments-delta-go-snippets.md'.`````
 - **Line 257, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-assignments-delta-powershell-snippets.md'.`````
 - **Line 398, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-assignments-delta-csharp-snippets.md'.`````
 - **Line 402, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-assignments-delta-javascript-snippets.md'.`````
 - **Line 406, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-assignments-delta-objc-snippets.md'.`````
 - **Line 410, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-assignments-delta-java-snippets.md'.`````
 - **Line 414, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-assignments-delta-go-snippets.md'.`````
 - **Line 418, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-assignments-delta-powershell-snippets.md'.`````

<a id="568cbd011fdb63f3d034a5ecdeca90ef-cd9b1d95"></a>
### [api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationcategory-delta.md)
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-classcategories-delta-csharp-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-classcategories-delta-javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-classcategories-delta-objc-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-classcategories-delta-java-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-classcategories-delta-go-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-classcategories-delta-powershell-snippets.md'.`````
 - **Line 160, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-classcategories-delta-csharp-snippets.md'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221500105435-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T15%3A01%3A52Z&sr=b&sp=r&sig=LPfz6YWtXQM48b5VcaoB0YkLm0HUz7MTrHfN4LbfI5Y%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 15:39 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +---
same here, not needed

2022-04-22 15:39 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +---
remove

2022-04-22 15:40 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +---
remove

2022-04-22 15:40 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +---
remove

2022-04-22 15:40 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +# [C#](#tab/csharp)
remove

2022-04-22 15:52 UTC, opbld34 commented
Docs Build status updates of commit _[dd261a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd261a31843654978c73c68ddd234b8512dbeda4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationassignment-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-70987e81d122f8151fed510a57c0ecbd-9f60c637)
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationcategory-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-568cbd011fdb63f3d034a5ecdeca90ef-9f60c637)
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-8ab1e5dc4e719fd194c2ad760dda591a-9f60c637)
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |

<a id="70987e81d122f8151fed510a57c0ecbd-9f60c637"></a>
### [api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationassignment-delta.md)
 - **Line 67, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 3).`````

<a id="568cbd011fdb63f3d034a5ecdeca90ef-9f60c637"></a>
### [api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationcategory-delta.md)
 - **Line 63, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 3).`````

<a id="8ab1e5dc4e719fd194c2ad760dda591a-9f60c637"></a>
### [api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221549420079-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T15%3A52%3A35Z&sr=b&sp=r&sig=Oc%2BjWIRz4iWoMbOwIRUHtEkHk9ErYqdeY7PMUs5vBzo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 17:24 UTC, opbld34 commented
Docs Build status updates of commit _[83e6f29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83e6f29df4871957f4c206f168866d3497b13055)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-77c34939)

<a id="77c34939"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221723486785-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T17%3A24%3A27Z&sr=b&sp=r&sig=bKMX4g7nm2c%2BpjtmHZMSPjh%2BwpC6309b1VwNVuKdR7A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 17:28 UTC, opbld30 commented
Docs Build status updates of commit _[96e7241](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96e724199adaa710d98d3025bba05a25385a0fd4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5d27eb72)

<a id="5d27eb72"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221728005919-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T17%3A28%3A40Z&sr=b&sp=r&sig=Oi2pN6zDdnTH9hHQYGYxa%2FZGcVCkdXdJfF7bkxCXkPE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 17:31 UTC, opbld34 commented
Docs Build status updates of commit _[65e38fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65e38fd45ae65d92b0f63743af057ef6a0876ae1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1156bb68)

<a id="1156bb68"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221730362487-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T17%3A31%3A10Z&sr=b&sp=r&sig=5Eqrt%2B8R3b26VKjYBAmLNO1nmf8H1Wy0k954hNhxSn8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 18:01 UTC, opbld31 commented
Docs Build status updates of commit _[e89e40d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e89e40d7755049f2c1989fdcd7dc14b20074031d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6511e41c)

<a id="6511e41c"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221800177554-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T18%3A01%3A01Z&sr=b&sp=r&sig=mVKcSRW6%2BspDd6PX9OQ%2B97nzYIH8JTSC3DdkXx4pozA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 19:08 UTC, opbld32 commented
Docs Build status updates of commit _[b10ed2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b10ed2f824c5510747e6aab0e85b3a9bd6a464bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationassignment-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-70987e81d122f8151fed510a57c0ecbd-224cd28f)
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationcategory-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-568cbd011fdb63f3d034a5ecdeca90ef-224cd28f)
[concepts/connecting-external-content-build-quickstart-07-surface-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-07-surface-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-07-surface-data?branch=pr-en-us-16618) | [Details](#user-content-cc96779f1a77351d8397d2723ad58e5a-224cd28f)
[api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-remoteassistance-allowedremoteassistanceactions?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) | [Details](#user-content-dd051a7be8ae777c0d0a1d7c8bb481ba-224cd28f)
[api-reference/v1.0/api/accesspackage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accesspackage-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-update?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-7199f613a6a30997343949881ca127cb-224cd28f)
[concepts/data-connect-quickstart-02.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-02.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-02?branch=pr-en-us-16618) | [Details](#user-content-38c98686334a186496079b022f8ac4b2-224cd28f)
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16618) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-224cd28f)
[concepts/connecting-external-content-build-quickstart-08-search-results.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-08-search-results.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-08-search-results?branch=pr-en-us-16618) | [Details](#user-content-bc12a081a7d1a693b726f60cccb50b5d-224cd28f)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16618) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-224cd28f)
[concepts/data-connect-quickstart-03.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-03.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-03?branch=pr-en-us-16618) | [Details](#user-content-7db385b8a4b22670a3acd8da69bf8a33-224cd28f)
[concepts/data-connect-quickstart-04.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-04.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-04?branch=pr-en-us-16618) | [Details](#user-content-7a262add4d39da6e734ada62359d017d-224cd28f)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-224cd28f)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16618) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-224cd28f)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16618) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-224cd28f)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16618) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-224cd28f)
[concepts/connecting-external-content-build-quickstart-09-summary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-09-summary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-09-summary?branch=pr-en-us-16618) | [Details](#user-content-22f9745b47bcf4aef74b68a012876aba-224cd28f)
[concepts/connecting-external-content-build-quickstart-06-run-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-06-run-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-06-run-app?branch=pr-en-us-16618) | [Details](#user-content-e1a26798586da77894d1265baca82f59-224cd28f)
[concepts/connecting-external-content-build-quickstart-04-configure-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-04-configure-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-04-configure-app?branch=pr-en-us-16618) | [Details](#user-content-a00e640699abfd9f250b6eac4dd922d8-224cd28f)
[concepts/connecting-external-content-build-quickstart-03-build-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-03-build-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-03-build-app?branch=pr-en-us-16618) | [Details](#user-content-75c9d80b83e078d88064d6e03fce904f-224cd28f)
[concepts/connecting-external-content-build-quickstart-02-register-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-02-register-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-02-register-app?branch=pr-en-us-16618) | [Details](#user-content-bf7e7fc2e1488b8379519bb1bf990026-224cd28f)
[concepts/connecting-external [...]

2022-04-22 21:12 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-delta.md
> +```
GLobal: please remove the tabs (ie line 63) and replace msgraph-interactive with http. Apply to all changes in this PR.

2022-04-22 21:13 UTC, isvargasmsft commented on api-reference/v1.0/resources/educationclass.md
> +| [Get delta](../api/educationclass-delta.md)                                 | [educationClass](educationclass.md) collection | Get incremental changes for **educationClasses**.
Please use the action's actual name (Delta in this case). Apply to the other sections in this PR.

2022-04-22 21:14 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-delta.md
> +---
Missing in this PR:
Changelog and TOC entries.

2022-04-22 21:15 UTC, isvargasmsft requested changes
Please add the changelog and TOC entries for the 2 new delta operations.

2022-04-28 17:33 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +```
done for all pages in PR

2022-04-28 18:41 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +---
done

2022-04-28 18:49 UTC, cristobal-buenrostro commented on api-reference/v1.0/resources/educationclass.md
> +| [Get delta](../api/educationclass-delta.md)                                 | [educationClass](educationclass.md) collection | Get incremental changes for **educationClasses**.
Can we keep the name? to have consistency against beta.
https://docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-beta

2022-04-28 18:56 UTC, opbld34 commented
Docs Build status updates of commit _[090f20e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/090f20eff068d63d270bd2f6b51907a339c1fbed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-8ab1e5dc4e719fd194c2ad760dda591a-91256a71)
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="8ab1e5dc4e719fd194c2ad760dda591a-91256a71"></a>
### [api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281853148219-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T18%3A56%3A43Z&sr=b&sp=r&sig=%2BAcCuhr8eJDzWdpQgjj1lSeji2Tpp2RfzKSAT%2B1JtCY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 19:24 UTC, cristobal-buenrostro commented on api-reference/v1.0/resources/educationclass.md
> +| [Get delta](../api/educationclass-delta.md)                                 | [educationClass](educationclass.md) collection | Get incremental changes for **educationClasses**.
done, changed for beta as well

2022-04-28 19:26 UTC, opbld33 commented
Docs Build status updates of commit _[431fb8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/431fb8b3ea3ca9f2dd7ee3824f90590f8ace928d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-8ab1e5dc4e719fd194c2ad760dda591a-df9063a5)
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="8ab1e5dc4e719fd194c2ad760dda591a-df9063a5"></a>
### [api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281924464788-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T19%3A26%3A31Z&sr=b&sp=r&sig=r8j9DQq5L6lc%2BTJ6LnOc64OwweyzfPS%2Bg%2By8UqxdzMk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 17:29 UTC, opbld30 commented
Docs Build status updates of commit _[33f62fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33f62fdd605d6bde58e2dc4014ee85c02f82f728)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-8ab1e5dc4e719fd194c2ad760dda591a-2205eeae)
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="8ab1e5dc4e719fd194c2ad760dda591a-2205eeae"></a>
### [api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205021727523344-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T17%3A29%3A47Z&sr=b&sp=r&sig=eUh1tkm9i0st6vdHVkcWSFPBmct%2Bsc0lC0BJje9axwA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 17:52 UTC, isvargasmsft approved these changes

2022-05-02 19:36 UTC, zoexi commented
nit: but I see that other delta api doc pages have the delta page title as "Get delta" instead of just "delta"

2022-05-02 19:44 UTC, zoexi commented on api-reference/beta/resources/educationclass.md
> +| [Delta](../api/educationclass-delta.md)                                 | [educationClass](educationclass.md) collection | Get incremental changes for **educationClasses**.
Just making sure this change is intentional - because this API is not owned by Assignments team

2022-05-03 00:59 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationclass.md
> +| [Delta](../api/educationclass-delta.md)                                 | [educationClass](educationclass.md) collection | Get incremental changes for **educationClasses**.
yes, I did it, was requested by content reviewer.

2022-05-05 04:13 UTC, Lauragra commented on api-reference/beta/resources/educationassignment.md
> +|[Delta](../api/educationassignment-delta.md)|[educationAssignment](../resources/educationassignment.md) collection|Get an **educationAssignment** object collection with delta query support.|
Our standard is to use a verb for delta functions, so for consistency we would want to use "Get delta" here and in the TOC. What was the reason for changing it to just Delta? Also, please use the summary statement in the method topic for the description here; this description isn't very clear/intuitive.

2022-05-05 04:13 UTC, Lauragra commented on api-reference/v1.0/api/educationcategory-delta.md
> +> This method doesn't return deleted categories.
Please add a summary description for this method.

2022-05-05 04:14 UTC, Lauragra commented on api-reference/beta/resources/educationcategory.md
> +|[Delta](../api/educationcategory-delta.md)|[educationCategory](../resources/educationcategory.md) collection|Get a list of **educationCategory** objects that belongs to this class with delta query s
Please use the summary statement that you use for the method topic for the description here.

2022-05-05 04:15 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-delta.md
> +This method does not support the `$expand`, `$orderby`, `$search`, and `$filter` OData query parameters.
Is this a comprehensive list of all the possible query parameters? It might be clearer just to have the statement about which parameter IS supported. So, delete this sentence, unless there's a specific reason to call out that these specifically are not supported?

2022-05-05 04:17 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-delta.md
> +Use the `$top` parameter to specify the number of assignments to be returned. The parameter is optional but use it preferably when you have a long list of assignments; otherwise, you will get all the
For readability, let's make the second sentence two sentences:
The parameter is optional. Use it when you have a long list of assignments; otherwise, you will get all the assignments in the class.

2022-05-05 04:18 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-delta.md
> +>**Note:** You must continue using the `@odata.deltaLink` to get the newly created or modified assignments since the initial Delta call.
Please lowercase Delta.

2022-05-05 04:20 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-delta.md
> +>Sometimes the delta response will be very large in which case an `@odata.nextLink` will be returned to continue fetching changes until you hit an `@odata.deltaLink` again.
Revise this text as follows:
>**Note:** The delta response might be large, in which case an `@odata.nextLink` is returned. Continue fetching changes until you hit an `@odata.deltaLink` again.

2022-05-05 04:20 UTC, Lauragra commented on api-reference/v1.0/api/educationcategory-delta.md
> +This method does not support the `$expand`, `$orderby`, `$search`, and `$filter` OData query parameters.
Same comment here - might be clearer to just state which parameter is supported.

2022-05-05 04:21 UTC, Lauragra commented on api-reference/v1.0/api/educationcategory-delta.md
> +Use the `$top` parameter to specify the number of categories to be returned. The parameter is optional but use it preferably when you have a long list of categories, otherwise you will get all the ca
Please apply the same edits as requested for the previous method topic.

2022-05-05 04:22 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-delta.md
> +>**Note:** You must continue using the `@odata.nextLink` value for the consequent calls until you get the `@odata.deltaLink` property in the response.
Change "consequent" to "subsequent".

2022-05-07 15:54 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +This method does not support the `$expand`, `$orderby`, `$search`, and `$filter` OData query parameters.
deleted

2022-05-07 15:58 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +This method does not support the `$expand`, `$orderby`, `$search`, and `$filter` OData query parameters.
done

2022-05-07 16:01 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +> This method doesn't return deleted categories.
done

2022-05-07 16:02 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +Use the `$top` parameter to specify the number of assignments to be returned. The parameter is optional but use it preferably when you have a long list of assignments; otherwise, you will get all the
done

2022-05-07 16:04 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationcategory-delta.md
> +Use the `$top` parameter to specify the number of categories to be returned. The parameter is optional but use it preferably when you have a long list of categories, otherwise you will get all the ca
done

2022-05-07 16:05 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +>**Note:** You must continue using the `@odata.nextLink` value for the consequent calls until you get the `@odata.deltaLink` property in the response.
done

2022-05-07 16:05 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +>**Note:** You must continue using the `@odata.deltaLink` to get the newly created or modified assignments since the initial Delta call.
done

2022-05-07 16:05 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationassignment-delta.md
> +>Sometimes the delta response will be very large in which case an `@odata.nextLink` will be returned to continue fetching changes until you hit an `@odata.deltaLink` again.
done

2022-05-07 16:06 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationcategory.md
> +|[Delta](../api/educationcategory-delta.md)|[educationCategory](../resources/educationcategory.md) collection|Get a list of **educationCategory** objects that belongs to this class with delta query s
done

2022-05-07 16:06 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationassignment.md
> +|[Delta](../api/educationassignment-delta.md)|[educationAssignment](../resources/educationassignment.md) collection|Get an **educationAssignment** object collection with delta query support.|
done

2022-05-07 16:09 UTC, opbld31 commented
Docs Build status updates of commit _[d5ce3df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5ce3df002c20a6f0194485555faedba146d139f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) | [Details](#user-content-8ab1e5dc4e719fd194c2ad760dda591a-7a9e77b3)
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="8ab1e5dc4e719fd194c2ad760dda591a-7a9e77b3"></a>
### [api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md)
 - **Line 20, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205071607224058-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-07T16%3A09%3A39Z&sr=b&sp=r&sig=3%2FVSAa5Lk%2FmX3%2F32qqmpfuNNbt2Aizk5MFxRgo5WJ%2B8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-07 16:27 UTC, opbld31 commented
Docs Build status updates of commit _[f08d305](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f08d30515318f24bf4902ddc660549c9a82d6bd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205071625270053-16618%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-07T16%3A27%3A35Z&sr=b&sp=r&sig=FozV0SGRtjU3alAlEPKFDx%2BpMR8b%2BWpMt9aEvz7j%2F2o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 02:49 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Delta
These TOC entries should be changed back to "Get delta".

2022-05-10 02:50 UTC, Lauragra commented on api-reference/v1.0/resources/educationassignment.md
> +|[Delta](../api/educationassignment-delta.md)|[educationAssignment](../resources/educationassignment.md) collection|Get an **educationAssignment** object collection with delta query support.|
Please use Get delta here as well, and use the description from the delta method topic.

2022-05-10 02:50 UTC, Lauragra commented on api-reference/v1.0/resources/educationcategory.md
> +|[Delta](../api/educationcategory-delta.md)|[educationCategory](../resources/educationcategory.md) collection|Get a list of **educationCategory** objects that belongs to this class with delta query s
Get delta, and update the description.

2022-05-10 02:51 UTC, Lauragra commented on api-reference/v1.0/resources/educationclass.md
> +| [Delta](../api/educationclass-delta.md)                  | [educationClass](educationclass.md) collection              | Get incremental changes for **educationClasses**.
Get delta

2022-05-12 03:38 UTC, opbld34 commented
Docs Build status updates of commit _[47d626d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47d626d88bd36ad1bacc74ee3cfe0fabdbbae13a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120336469677-16618/BuildReport?accessString=a108d225d81b3a20d42121f7fa28e83909ed013d4d0ac3f50c82ce22beb141b9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:41 UTC, opbld32 commented
Docs Build status updates of commit _[e487e22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e487e22d7a1f0c4b59af1d9d53ea7ee67328defe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120339089134-16618/BuildReport?accessString=22e5aeae71a3857b6443bc3d7b9ac4042dbab94156a9b10d70d127ed5e0e827d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:43 UTC, opbld33 commented
Docs Build status updates of commit _[3b54146](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b5414667c5cc4fa4ae908d611364333e4f60db0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120340043696-16618/BuildReport?accessString=5657bb61c34c1695571139c91df4fe703ead504b07fe72c7929e341f8c0ad55b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:45 UTC, opbld31 commented
Docs Build status updates of commit _[dda63a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dda63a1528cfccbadc4565d57ffa0887bf49d43f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120343352021-16618/BuildReport?accessString=31de87f3ac883d91e08b92d76825b905bd15c7539c5679f332298eb6a85e9c0c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 03:47 UTC, merged

2022-05-12 03:47 UTC, opbld32 commented
Docs Build status updates of commit _[aa330a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa330a4df53967e85b70bbccc47ecd15f491dc46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-16618) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationassignment-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/api-reference/v1.0/api/educationcategory-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/educationclass.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/educationclass.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationclass?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delta?view=graph-rest-1.0&branch=pr-en-us-16618) (>= graph-rest-1.0) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/deltav1coverage/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120342429662-16618/BuildReport?accessString=8c4632b7d1d54e98cc1654b16bb749f8f816c89fccfab2364231a3bee25286c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>