validation: multiple-fixes-1
microsoftgraph/microsoft-graph-docs pull request #16619
Opened 2022-04-22 15:14 UTC by MelanieHom

2022-04-22 15:16 UTC, opbld30 commented
Docs Build status updates of commit _[0cb65b0](https://github.com/MelanieHom/microsoft-graph-docs/commits/0cb65b0a32a4484c8060a5c0c833128d454386d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-1c4206b3)
[includes/outlook-mailbox-type-support.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/includes/outlook-mailbox-type-support.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) | [Details](#user-content-1558be61e5e7edb2ce900bae389de3fd-1c4206b3)
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-events?branch=pr-en-us-16619) |

<a id="462cb190caa986bcf66d33f9afbe5616-1c4206b3"></a>
### [concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Universal Print is a modern print solution that organizations can use to manage their print infrastructure through cloud services from Microsoft.' is duplicated in 'universal-print-concept-overview.md(3,14)', 'upload-data-to-upload-session.md(3,14)'.`````

<a id="1558be61e5e7edb2ce900bae389de3fd-1c4206b3"></a>
### [includes/outlook-mailbox-type-support.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/includes/outlook-mailbox-type-support.md)
 - **Line 12, Column 206**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /policy-and-compliance/in-place-archiving/in-place-archiving?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221514169510-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T15%3A16%3A03Z&sr=b&sp=r&sig=iQ%2Bnf2kGUCMwoyFc7uYljpqBmdh%2Bzcm5QrHsfzM2p5A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 15:23 UTC, opbld32 commented
Docs Build status updates of commit _[9677ffd](https://github.com/MelanieHom/microsoft-graph-docs/commits/9677ffda33f2e01f0fe0d3ce7dd62b4dba53d785)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-events?branch=pr-en-us-16619) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221521312150-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T15%3A23%3A35Z&sr=b&sp=r&sig=94GF0SwABN87N%2B8HRNJJizwx9%2FtlZOohJE3ic68HLQA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 16:10 UTC, opbld32 commented
Docs Build status updates of commit _[b53c6fd](https://github.com/MelanieHom/microsoft-graph-docs/commits/b53c6fde54dead04467e086cac7f0ab15ae67aee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-events?branch=pr-en-us-16619) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221608569071-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A10%3A55Z&sr=b&sp=r&sig=rg8MP0gmmAMOe8WoWjv2DlwtwsMBMLRsFC9smkofzio%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 16:34 UTC, opbld34 commented
Docs Build status updates of commit _[f3e0d88](https://github.com/MelanieHom/microsoft-graph-docs/commits/f3e0d8845a01c308597d72a3d40d393c716362ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) | [Details](#user-content-539eba24f50f3f0b74d1133833fbdb04-e4e8c8e2)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) |
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

<a id="539eba24f50f3f0b74d1133833fbdb04-e4e8c8e2"></a>
### [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md)
 - **Line 11, Column 13**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 16, Column 22**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 17, Column 7**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/group-list?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 112, Column 10**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/team-get?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 161, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-list-joinedteams?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 162, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/group-list?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221632494050-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A34%3A49Z&sr=b&sp=r&sig=8wVdHWzhn01zH4FCoSw44m7FWMHOhvoDw6zPpPY%2Fz2w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 16:48 UTC, opbld32 commented
Docs Build status updates of commit _[9909af2](https://github.com/MelanieHom/microsoft-graph-docs/commits/9909af2a8c882609f4dd0a614dd7a4b81bceb1f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) | [Details](#user-content-539eba24f50f3f0b74d1133833fbdb04-702d8eef)
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) |
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

<a id="539eba24f50f3f0b74d1133833fbdb04-702d8eef"></a>
### [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md)
 - **Line 11, Column 13**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 16, Column 22**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 17, Column 7**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/group-list?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 112, Column 10**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/team-get?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 161, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-list-joinedteams?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 162, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/group-list?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221646195429-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A48%3A29Z&sr=b&sp=r&sig=J1xRhL6oxDBLyIdttFTvOV9eHeQCVzJh%2Bwhxu%2F%2FkgzY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 16:52 UTC, opbld32 commented
Docs Build status updates of commit _[08a3057](https://github.com/MelanieHom/microsoft-graph-docs/commits/08a305736fb8011b157ce7a103319805a0fa560c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) |
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) |
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221650259646-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A52%3A22Z&sr=b&sp=r&sig=S0pkbN%2F58jK%2Bmx4YZZgGVLLrD1OSgvlaZjkidl9goeA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 19:37 UTC, MelanieHom commented
@Lauragra 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-04-25 12:50 UTC, jasonjoh requested changes

2022-04-25 12:50 UTC, jasonjoh commented on concepts/data-connect-quickstart-05.md
> +description: Learn how to create an Azure Data Factory pipeline using Microsoft Graph data connect to extract data from Microsoft 365 to an Azure Storage account
This change should be reverted. These are include files for a tutorial. The H1 you added is duplicated (for example, see https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16619&tabs=Microsoft365&tutorial-step=6)

2022-04-25 12:50 UTC, jasonjoh commented on concepts/data-connect-quickstart-06.md
> +title: Microsoft Graph Data Connect tutorial - Managing requests with PowerShell and the Microsoft 365 Admin Center
This change should be reverted. These are include files for a tutorial. The H1 you added is duplicated (for example, see https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16619&tabs=Microsoft365&tutorial-step=6)

2022-04-25 12:50 UTC, jasonjoh commented on concepts/data-connect-quickstart-07.md
> +title: Microsoft Graph Data Connect tutorial - Building an ASP.NET project
This change should be reverted. These are include files for a tutorial. The H1 you added is duplicated (for example, see https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16619&tabs=Microsoft365&tutorial-step=6)

2022-04-25 12:50 UTC, jasonjoh commented on concepts/data-connect-quickstart-08.md
> +title: Microsoft Graph Data Connect tutorial - Complete
This change should be reverted. These are include files for a tutorial. The H1 you added is duplicated (for example, see https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16619&tabs=Microsoft365&tutorial-step=6)

2022-04-25 14:58 UTC, opbld32 commented
Docs Build status updates of commit _[b2a29e1](https://github.com/MelanieHom/microsoft-graph-docs/commits/b2a29e1dbafa92df0515780d65535675025a7bbf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16619) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-adc7b1c8)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16619) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-adc7b1c8)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-adc7b1c8)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-adc7b1c8)
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

<a id="49ba6bc1bc76869c94c591e675946bf5-adc7b1c8"></a>
### [concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="efaec4ecee56faad79a6080b7afaf381-adc7b1c8"></a>
### [concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="18b11290095a06a8895c9d5be67624cb-adc7b1c8"></a>
### [concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="3eb5fcfb4d44090659d6da03424fc701-adc7b1c8"></a>
### [concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204251454162151-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T14%3A58%3A15Z&sr=b&sp=r&sig=oMkdin0rcR69lcK0OlGhWV6J1ZYA19091M6tDzMOidM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-25 15:18 UTC, MelanieHom commented on concepts/data-connect-quickstart-05.md
> +description: Learn how to create an Azure Data Factory pipeline using Microsoft Graph data connect to extract data from Microsoft 365 to an Azure Storage account
H1 removed and metadata updated.

2022-04-26 16:19 UTC, opbld31 commented
Docs Build status updates of commit _[3193c03](https://github.com/MelanieHom/microsoft-graph-docs/commits/3193c032f6432732ef8353a8d77e814e6e336476)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16619) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-f560b69b)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16619) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-f560b69b)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-f560b69b)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-f560b69b)
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

<a id="49ba6bc1bc76869c94c591e675946bf5-f560b69b"></a>
### [concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="efaec4ecee56faad79a6080b7afaf381-f560b69b"></a>
### [concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="18b11290095a06a8895c9d5be67624cb-f560b69b"></a>
### [concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="3eb5fcfb4d44090659d6da03424fc701-f560b69b"></a>
### [concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204261616468290-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T16%3A19%3A11Z&sr=b&sp=r&sig=M%2B%2FjSuqdq%2F4BbKiTn1KViEzgMAWYfccQBbNBiqzEwjA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 16:27 UTC, opbld31 commented
Docs Build status updates of commit _[6950719](https://github.com/MelanieHom/microsoft-graph-docs/commits/6950719afa7341bf766dbb64ce4a459f00e7ca93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16619) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-625e234d)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16619) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-625e234d)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-625e234d)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-625e234d)
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

<a id="49ba6bc1bc76869c94c591e675946bf5-625e234d"></a>
### [concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````

<a id="efaec4ecee56faad79a6080b7afaf381-625e234d"></a>
### [concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````

<a id="18b11290095a06a8895c9d5be67624cb-625e234d"></a>
### [concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````

<a id="3eb5fcfb4d44090659d6da03424fc701-625e234d"></a>
### [concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204261623589399-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T16%3A27%3A36Z&sr=b&sp=r&sig=bXmpbqJc3XnHhvb0lGJl56DW%2FtQ2CjbG6ODSq9wG6Mg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?group [...]

2022-04-26 16:32 UTC, MelanieHom commented
> Those tutorial topics are still broken:
> 
> ![image](https://user-images.githubusercontent.com/8966342/165340687-84fea849-1451-4407-9cf4-4fc0e419cabe.png)
> 
> I think the `title` metdata may be causing this. It's not needed in an include file.

The title metadata has been removed. Let me know if this is okay before I do the same with the other PRs. Thanks!

2022-04-27 13:08 UTC, jasonjoh commented
Well, I don't know why, but it's still showing double titles. You can check it here: https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16619&tabs=Microsoft365&tutorial-step=6

You might want to just revert all your changes to the quickstart files. I'm pretty sure those descriptions don't get included in the built HTML - they come from the YAML file.

2022-04-27 13:34 UTC, jasonjoh commented
If you're trying to resolve validation warnings in the include files, a better fix is to move them into an "includes" subfolder. A similar fix was done for the connector tutorial in https://github.com/microsoftgraph/microsoft-graph-docs/pull/16621.

2022-04-27 16:12 UTC, opbld31 commented
Docs Build status updates of commit _[1fa80f9](https://github.com/MelanieHom/microsoft-graph-docs/commits/1fa80f941b90d956af1f85ab49d236800f1319ec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16619) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-f93aa1fe)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16619) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-f93aa1fe)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16619) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-f93aa1fe)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16619) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-f93aa1fe)
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

<a id="49ba6bc1bc76869c94c591e675946bf5-f93aa1fe"></a>
### [concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="efaec4ecee56faad79a6080b7afaf381-f93aa1fe"></a>
### [concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="18b11290095a06a8895c9d5be67624cb-f93aa1fe"></a>
### [concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="3eb5fcfb4d44090659d6da03424fc701-f93aa1fe"></a>
### [concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 2, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204271610145288-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T16%3A12%3A35Z&sr=b&sp=r&sig=sHcnUSaOHE9Qt1nF5tS%2BVyeYIrPiMKqkKriDdrQ1mw0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written [...]

2022-04-28 13:43 UTC, jasonjoh approved these changes

2022-04-28 13:46 UTC, opbld32 commented
Docs Build status updates of commit _[153c925](https://github.com/MelanieHom/microsoft-graph-docs/commits/153c92594bd24247bd7639805195f3e4fb7f4f23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281343455442-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T13%3A46%3A42Z&sr=b&sp=r&sig=ZQhNJf0Be5OXlKGjmSOPWcU1XZ50kPeznupSFvC33sQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 13:48 UTC, opbld33 commented
Docs Build status updates of commit _[bd1020f](https://github.com/MelanieHom/microsoft-graph-docs/commits/bd1020f03eb7743cb23d6b95fcd85215bb191b8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281345267745-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T13%3A48%3A41Z&sr=b&sp=r&sig=OQLKFbgtGzMNVOHQfrjEbHKYvXWdzoigXQyFNF1tHJo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 13:59 UTC, opbld31 commented
Docs Build status updates of commit _[f7a4c10](https://github.com/MelanieHom/microsoft-graph-docs/commits/f7a4c10838a7e5791c34a3bbc660c4a3d30b0f3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-large-attachments.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |
[concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-list-all-teams?branch=pr-en-us-16619) |
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-16619) |
[concepts/upload-data-to-upload-session.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/concepts/upload-data-to-upload-session.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16619) |
[includes/outlook-mailbox-type-support.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/outlook-mailbox-type-support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-16619) |
[includes/snippets/snippets-sdk-documentation-link.md](https://github.com/MelanieHom/microsoft-graph-docs/blob/multiple-fixes-1/includes/snippets/snippets-sdk-documentation-link.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-16619) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281349397202-16619%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T13%3A59%3A53Z&sr=b&sp=r&sig=EJ7VKAfS49Lbx7uL0niDnPC%2BMn1phGCXH9JcR%2FDmqso%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 14:20 UTC, merged