Teams App Resource Documentation
microsoftgraph/microsoft-graph-docs pull request #16616
Opened 2022-04-22 14:07 UTC by adarshgh

Adding documentation for Team App Resource Type. Added a resource page and incorporated the resource in assignment resources page.

2022-04-22 14:09 UTC, opbld30 commented
Docs Build status updates of commit _[53b83e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53b83e00f2944fad314e006be80eb3cdd6685b12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221407324575-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T14%3A09%3A17Z&sr=b&sp=r&sig=Upm99pn7RCTq2VJfZdp1CYh7jwGkdkpaUIaZRjJcudo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 15:56 UTC, opbld33 commented
Docs Build status updates of commit _[d6d5eb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6d5eb65e6a176ef162e34e8feeab39716a4090f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221554444575-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T15%3A56%3A50Z&sr=b&sp=r&sig=PPaQ3ujaahtYGnQlod9smDi0KSLZHw5aRpLZKBqmG%2FY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 16:17 UTC, opbld32 commented
Docs Build status updates of commit _[dfd8cc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfd8cc821e574b394e8b4357f761e5026a13a912)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204221615267657-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A17%3A29Z&sr=b&sp=r&sig=yvdpmfJ5Du43atF9LFZotHd81twtdHCfa9A01v5Bdfg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 19:42 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-post-resources.md
> +```http
I removed the tabs as these are automatically generated. Please keep this in mind for future PRs.

2022-04-22 19:43 UTC, opbld34 commented
Docs Build status updates of commit _[f74a7c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f74a7c85790d812a7e481849dfd0867fe5dae3b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-quickstart-05.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-05.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-05?branch=pr-en-us-16616) | [Details](#user-content-49ba6bc1bc76869c94c591e675946bf5-e2238861)
[concepts/connecting-external-content-build-quickstart-05-create-db.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-05-create-db.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-05-create-db?branch=pr-en-us-16616) | [Details](#user-content-8cf4b2b28399a08f993779830baa3e93-e2238861)
[api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-remoteassistance-allowedremoteassistanceactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-remoteassistance-allowedremoteassistanceactions?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) | [Details](#user-content-dd051a7be8ae777c0d0a1d7c8bb481ba-e2238861)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-e2238861)
[concepts/data-connect-quickstart-06.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-06.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-06?branch=pr-en-us-16616) | [Details](#user-content-efaec4ecee56faad79a6080b7afaf381-e2238861)
[concepts/data-connect-quickstart-07.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-07.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-07?branch=pr-en-us-16616) | [Details](#user-content-18b11290095a06a8895c9d5be67624cb-e2238861)
[concepts/connecting-external-content-build-quickstart-03-build-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-03-build-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-03-build-app?branch=pr-en-us-16616) | [Details](#user-content-75c9d80b83e078d88064d6e03fce904f-e2238861)
[concepts/data-connect-quickstart-02.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-02.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-02?branch=pr-en-us-16616) | [Details](#user-content-38c98686334a186496079b022f8ac4b2-e2238861)
[concepts/data-connect-quickstart-08.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-08.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-08?branch=pr-en-us-16616) | [Details](#user-content-3eb5fcfb4d44090659d6da03424fc701-e2238861)
[concepts/data-connect-quickstart-03.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-03.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-03?branch=pr-en-us-16616) | [Details](#user-content-7db385b8a4b22670a3acd8da69bf8a33-e2238861)
[concepts/data-connect-quickstart-04.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-04.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-04?branch=pr-en-us-16616) | [Details](#user-content-7a262add4d39da6e734ada62359d017d-e2238861)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-16616) | [Details](#user-content-462cb190caa986bcf66d33f9afbe5616-e2238861)
[concepts/connecting-external-content-build-quickstart-06-run-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-06-run-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-06-run-app?branch=pr-en-us-16616) | [Details](#user-content-e1a26798586da77894d1265baca82f59-e2238861)
[concepts/connecting-external-content-build-quickstart-02-register-app.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-02-register-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-02-register-app?branch=pr-en-us-16616) | [Details](#user-content-bf7e7fc2e1488b8379519bb1bf990026-e2238861)
[concepts/connecting-external-content-build-quickstart-08-search-results.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-08-search-results.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-08-search-results?branch=pr-en-us-16616) | [Details](#user-content-bc12a081a7d1a693b726f60cccb50b5d-e2238861)
[concepts/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-quickstart-01.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart-01?branch=pr-en-us-16616) | [Details](#user-content-369c8945d629ff719bcdc2119dac2ff7-e2238861)
[concepts/connecting-external-content-build-quickstart-09-summary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-09-summary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-09-summary?branch=pr-en-us-16616) | [Details](#user-content-22f9745b47bcf4aef74b68a012876aba-e2238861)
[concepts/connecting-external-content-build-quickstart-07-surface-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-build-quickstart-07-surface-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart-07-surface-data?branch=pr-en-us-16616) | [Details](#user-content-cc96779f1a77351d8397d2723ad58e5a-e2238861)
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) | [Details](#user-content-eb35fe5074ded7ba58df4876b9940d89-e2238861)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) | [Details](#user-content-683dc2417ba09f7c179da6e89732b800-e2238861)
[concepts/connecting-external-content-build-quickstart-04-configure [...]

2022-04-25 19:24 UTC, isvargasmsft commented on api-reference/beta/resources/educationteamsappresource.md
> +---
missing in this PR: Changelog entry for the new complex type.

2022-04-25 19:30 UTC, isvargasmsft commented on api-reference/beta/resources/educationteamsappresource.md
> +|webUrl|string|URL for the app resource that can be opened in the browser|
please include all the inherited properties.

2022-04-25 19:30 UTC, isvargasmsft commented on api-reference/beta/resources/educationteamsappresource.md
> +|webUrl|string|URL for the app resource that can be opened in the browser|
Apply to the json representation section as well.

2022-04-26 15:07 UTC, isvargasmsft requested changes
Hello Cristobal, 

Thank you for working in this PR. Please review:
1. Add a changelog entry for the new complex type. 
2. Include the inherited properties in the properties table. 
3. Let's work on a better description for the new complex type. 

Kind regards, 

Isaac

2022-04-28 19:41 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationteamsappresource.md
> +|webUrl|string|URL for the app resource that can be opened in the browser|
done

2022-04-28 19:41 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationteamsappresource.md
> +---
added

2022-04-28 19:48 UTC, opbld33 commented
Docs Build status updates of commit _[0fabcb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fabcb381d24bb30bd35b397403402c6e54f74eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281946126278-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T19%3A48%3A21Z&sr=b&sp=r&sig=ADa0m19OYpI%2BzI2UVaKsbY4spgNutlg1WZwgz9It9II%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 21:50 UTC, isvargasmsft commented on api-reference/beta/resources/educationteamsappresource.md
> +|lastModifiedDateTime|DateTimeOffset|The date and time when the resource was last modified. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. Fo
Please indicate in the description if the property is inherited from educationResource. Just add at the end: Inherited from educationResource.

2022-05-02 22:04 UTC, opbld32 commented
Docs Build status updates of commit _[096b472](https://github.com/microsoftgraph/microsoft-graph-docs/commits/096b472cc0594ca92979e745ea572b8f5252a3a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205022202537663-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T22%3A04%3A53Z&sr=b&sp=r&sig=TQFJtv3cirUqMRsg9YYsEV2VUID2pO5K%2B%2B8Egjfd0YI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 22:09 UTC, isvargasmsft approved these changes

2022-05-02 22:10 UTC, opbld34 commented
Docs Build status updates of commit _[354b86c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/354b86cce7dae00dc41c75959a01cce80162bbb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205022208593887-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T22%3A10%3A58Z&sr=b&sp=r&sig=32snd1h%2BdlKjJ1J37YH1EmDwsZ6J6B3U%2FBwFszrmJwI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 04:04 UTC, opbld32 commented
Docs Build status updates of commit _[6f40ad3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f40ad36623b8a0331c4be93e091db3938dd1f90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205050402224058-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T04%3A04%3A34Z&sr=b&sp=r&sig=b%2FoUaEcRZ3qc8D1aybnCw9b7xK78K%2FhPZligKxS%2FyA8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 04:07 UTC, Lauragra commented on api-reference/beta/resources/educationteamsappresource.md
> +Represents a Microsoft Teams application to submit to an [assignment](educationassignment.md). This resource allows users to use those resources through the governing application; for example, YouTub
Is this description clear? I'm not sure I understand how an application is submitted to an assignment. Would it make sense to state that the Teams application is submitted "as" an assignment? Also, what do we mean by "governing application", and what does "those resources" refers to?

Please clarify this summary statement a bit.

2022-05-05 04:08 UTC, Lauragra commented on api-reference/beta/resources/educationteamsappresource.md
> +|appId|string|Teams App ID of the application|
Please add a period to the end of each description.

2022-05-07 16:59 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationteamsappresource.md
> +|appId|string|Teams App ID of the application|
done

2022-05-07 17:37 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationteamsappresource.md
> +Represents a Microsoft Teams application to submit to an [assignment](educationassignment.md). This resource allows users to use those resources through the governing application; for example, YouTub
description updated with more details.
App is not submitted as an assignment, app is loaded as a resource into and assignment, similar to any other resource (word, excel, powerpoint, etc).
Those resources can be since a quiz, video, lecture, test, whiteboard, many different type of resources that can be used on the apps and can vary, but all that info dependes on the partner who is providing the app, I think that is out of the scope of MSFT docs, each partner has their website and show their apps capabilities and resources, we only allow to attach the app into the assignment.

2022-05-07 17:40 UTC, opbld31 commented
Docs Build status updates of commit _[7dd2c8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dd2c8f7e531c9d8564e8adad50a14f9dbf5206b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205071738257598-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-07T17%3A40%3A34Z&sr=b&sp=r&sig=V1noCMq7XNBIAVNaUKoCphMrwedWNav2TDVz1wvsUdk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 19:54 UTC, opbld33 commented
Docs Build status updates of commit _[01992e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01992e2f3583f900a104ca4dabe14f6938e88ac8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091950166591-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T19%3A54%3A16Z&sr=b&sp=r&sig=B%2FS%2BhN%2FSx9KY%2FeGKnwF8N8nHpBc8%2B4wtc6sqnuVJxBs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 22:13 UTC, opbld30 commented
Docs Build status updates of commit _[360c58a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/360c58a39eb036dac23f056d9aad7c096f1586f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205092209599066-16616%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T22%3A13%3A46Z&sr=b&sp=r&sig=TYG9A0FIf8vQDL1jhQwC8Bvgf7QHsNqWJq9%2BJPDPbEk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-10 20:20 UTC, isvargasmsft approved these changes

2022-05-12 16:41 UTC, isvargasmsft commented
@cristobal-buenrostro please fix the conflicts in the changelog file before adding the ready to merge label.

2022-05-16 15:22 UTC, opbld32 commented
Docs Build status updates of commit _[d60f2c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d60f2c130499ba8565a87b214a9d1b7bfa3f854a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205161517405861-16616/BuildReport?accessString=863130df323397904c16f69330bd0accb5ce5f57372c90aa6898074a31747889).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 04:11 UTC, opbld30 commented
Docs Build status updates of commit _[8a40ccb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a40ccb92d82a4c9ab7853c78820ab8a0b3c3c98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205170409161001-16616/BuildReport?accessString=75ef1f44b0ffec38dd00bb8362bb3f76b3648c7284c789692fb17a4fcb472adb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 04:14 UTC, opbld30 commented
Docs Build status updates of commit _[cefa2f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cefa2f502e3d6d54aa7610d442b425a099980d22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205170411548361-16616/BuildReport?accessString=c4a9b5c458c748db65b8a6b5963fcf765bccd2d14e8aa5cf48ea98019071423e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-17 04:14 UTC, Lauragra commented on api-reference/beta/resources/educationteamsappresource.md
> +An education resource that corresponds to an [installed Microsoft Teams app](teamsappinstallation.md) that allows education service users to share assignments on the Teams client, as supported by a c
Is it going to be clear to users what we mean by a "governing application"? What is the relationship between the installed Teams app and the governing application? In this sentence, we seem to be talking about three different apps - the installed app, Teams (application), and a "governing" app.

2022-05-17 20:42 UTC, cristobal-buenrostro commented on api-reference/beta/resources/educationteamsappresource.md
> +An education resource that corresponds to an [installed Microsoft Teams app](teamsappinstallation.md) that allows education service users to share assignments on the Teams client, as supported by a c
the developer of this feature helped me to revise the text.

2022-05-17 20:45 UTC, opbld30 commented
Docs Build status updates of commit _[17c338f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17c338f37dacf1af74c56dcb19db273714ef82d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205172043272126-16616/BuildReport?accessString=8b80be1f43082189a35a54323d0e9251dad87352de7633d3959d7cca0599b337).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 03:59 UTC, Lauragra approved these changes

2022-05-18 04:02 UTC, opbld34 commented
Docs Build status updates of commit _[37fcb46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37fcb46686f1d88b3fb5aae7eedd8e0cc842ef95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[api-reference/beta/resources/educationteamsappresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationteamsappresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationteamsappresource?view=graph-rest-beta&branch=pr-en-us-16616) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-adarshh/teamsappresource/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205180400052674-16616/BuildReport?accessString=6cb724dd8f28e0f68992e199299165db9b8c7cbb65bb62cb15e25213df33f35e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 04:07 UTC, merged