Change updateDomainPassword method using from "Patch"to "Post"
microsoftgraph/microsoft-graph-docs pull request #16631
Opened 2022-04-24 06:32 UTC by Emma0727

2022-04-24 06:35 UTC, opbld30 commented
Docs Build status updates of commit _[4458b56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4458b5638509d470a26efc99902c7866755f3674)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/cloudpconpremisesconnection-updateaddomainpassword-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/api-reference/beta/includes/snippets/objc/cloudpconpremisesconnection-updateaddomainpassword-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204240632168914-16631%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-25T06%3A35%3A22Z&sr=b&sp=r&sig=%2BtDBMH%2Ftsr4MeSnglqnHMUGWlNveSL5Y3ZFNuy8jrxo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 06:13 UTC, opbld34 commented
Docs Build status updates of commit _[4c6537f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c6537f596504cede6f1f55b8400f0e548b0b1c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/cloudpconpremisesconnection-updateaddomainpassword-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/api-reference/beta/includes/snippets/objc/cloudpconpremisesconnection-updateaddomainpassword-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205050611315158-16631%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T06%3A13%3A36Z&sr=b&sp=r&sig=%2BMYP%2BQuZWTp0jweS9VYqYwz8F0tCP309Rk5E1WcpNaw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 06:14 UTC, RuiHou105 commented on api-reference/beta/includes/snippets/objc/cloudpconpremisesconnection-updateaddomainpassword-objc-snippets.md
> -[urlRequest setHTTPMethod:@"PATCH"];
No need to update these snippet files. Actually these files are generated/updated automatically by their tools.

2022-05-05 06:18 UTC, RuiHou105 requested changes
1.please resolve comments. Thanks.

2.Please create a roadmap workitem and then attach it into the description. Here is an example https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/12535/. If you don't have access, please follow these steps to get access first:

Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-05-05 06:42 UTC, opbld32 commented
Docs Build status updates of commit _[09413df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09413dfe1e2046a67d70209cc45319f404c8f87b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205050640027580-16631%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T06%3A42%3A03Z&sr=b&sp=r&sig=I1b9YEgq69VYFce1JOD9kgyn1oDTQSsxbp0UkeVPxBI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 06:45 UTC, Emma0727 commented on api-reference/beta/includes/snippets/objc/cloudpconpremisesconnection-updateaddomainpassword-objc-snippets.md
> -[urlRequest setHTTPMethod:@"PATCH"];
thanks, just revert the change in snappet file.

2022-05-05 12:22 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
>  -->
Please add notification here to indicate that this API will support both POST and PATCH for a month, and will finally switch to PATCH by the end of June.

2022-05-06 09:16 UTC, opbld32 commented
Docs Build status updates of commit _[fb969da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb969da922a78b8c21740f340d61acfb571753e7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-0648ff7c69a67275acaef6b29d52deea-ab68523f)

<a id="0648ff7c69a67275acaef6b29d52deea-ab68523f"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md)
 - **Line 20, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205060914566492-16631%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T09%3A16%3A58Z&sr=b&sp=r&sig=Nz4RfsDcrT%2B9O4tVTOceNC8DN7crWtFVN8iHYgdBIbo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 09:26 UTC, opbld30 commented
Docs Build status updates of commit _[35a9a15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35a9a158525d2e43d3d3269d14e324086fd1876d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205060924140451-16631%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T09%3A26%3A22Z&sr=b&sp=r&sig=JxwthUqO7S6naSGjFQ6RaD9qmVVwmFeyE%2FE%2BkohLsac%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 09:52 UTC, Emma0727 commented on api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
>  -->
Added

2022-05-06 10:05 UTC, opbld33 commented
Docs Build status updates of commit _[fc36953](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc36953ebb59bd765083f750e9997f025b52e4a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205061003119005-16631%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T10%3A05%3A05Z&sr=b&sp=r&sig=a4lMve4wKYLv9qLCRji%2FKpw%2BlplluWozMh2v5g1OfXU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 02:35 UTC, RuiHou105 approved these changes

2022-05-11 05:38 UTC, opbld31 commented
Docs Build status updates of commit _[d9f5c0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9f5c0a216d261fae7f993a1810b4fe26f70842f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205110536324615-16631/BuildReport?accessString=514a9b862e74a60e3e67a5d7fb015aafb9289fe5213c24e6ebee9010130ec185).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 05:43 UTC, RuiHou105 commented
@Lauragra  @JarbasHorst Could you please help review this PR ?  Thanks!

2022-05-18 03:50 UTC, isvargasmsft commented
Hello @Emma0727, @RuiHou105, @AshleyYangSZ; this scenario qualifies as a deprecation. Please remove the custom note and follow the guidelines for deprecation here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs?anchor=deprecate-content-for-a-method

2022-05-18 03:51 UTC, isvargasmsft requested changes
Please follow the deprecation process here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211775/Deprecate-docs?anchor=deprecate-content-for-a-method

2022-05-19 10:00 UTC, opbld31 commented
Docs Build status updates of commit _[a105c87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a105c87d3d563201a0f4da713018431c1d8dbab1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated)?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-bd1235e1b379fde2adf6d68cc7516fe3-4d01e51f)
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-0648ff7c69a67275acaef6b29d52deea-4d01e51f)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated)?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

<a id="bd1235e1b379fde2adf6d68cc7516fe3-4d01e51f"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcOnPremisesConnection: updateAdDomainPassword' is duplicated with other articles: 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(10,1), beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the Active Directory domain password for a successful Azure network connection. This API is supported when the onPremisesConnection's type is hybridAzureADJoin.' is duplicated in 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(3,14)', 'beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(3,14)'.`````

<a id="0648ff7c69a67275acaef6b29d52deea-4d01e51f"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcOnPremisesConnection: updateAdDomainPassword' is duplicated with other articles: 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(10,1), beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the Active Directory domain password for a successful Azure network connection. This API is supported when the onPremisesConnection's type is hybridAzureADJoin.' is duplicated in 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(3,14)', 'beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190958067148-16631/BuildReport?accessString=fa36c5258025571ff218cdc9d91e1dc899cf481afb2298efa56b999036c86cf6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 10:03 UTC, AshleyYangSZ approved these changes

2022-05-19 10:06 UTC, opbld31 commented
Docs Build status updates of commit _[56a2eee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56a2eee6d9922207b7113ee8f4dfcd0eab6a23a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated)?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-bd1235e1b379fde2adf6d68cc7516fe3-d44b3675)
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-0648ff7c69a67275acaef6b29d52deea-d44b3675)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated)?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

<a id="bd1235e1b379fde2adf6d68cc7516fe3-d44b3675"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcOnPremisesConnection: updateAdDomainPassword' is duplicated with other articles: 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(10,1), beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the Active Directory domain password for a successful Azure network connection. This API is supported when the onPremisesConnection's type is hybridAzureADJoin.' is duplicated in 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(3,14)', 'beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(3,14)'.`````

<a id="0648ff7c69a67275acaef6b29d52deea-d44b3675"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcOnPremisesConnection: updateAdDomainPassword' is duplicated with other articles: 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(10,1), beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the Active Directory domain password for a successful Azure network connection. This API is supported when the onPremisesConnection's type is hybridAzureADJoin.' is duplicated in 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(3,14)', 'beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205191003087386-16631/BuildReport?accessString=71a0fad39d2b237a89e293cbc9505f3487b17d19e8f6a7eef07ebd63a186c128).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 14:43 UTC, opbld34 commented
Docs Build status updates of commit _[ffdc83e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffdc83e812020a8f1316cb69a3f468046f347548)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated)?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-bd1235e1b379fde2adf6d68cc7516fe3-71497c40)
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) | [Details](#user-content-0648ff7c69a67275acaef6b29d52deea-71497c40)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated)?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

<a id="bd1235e1b379fde2adf6d68cc7516fe3-71497c40"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the Active Directory domain password for a successful Azure network connection. This API is supported when the onPremisesConnection's type is hybridAzureADJoin.' is duplicated in 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(3,14)', 'beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(3,14)'.`````

<a id="0648ff7c69a67275acaef6b29d52deea-71497c40"></a>
### [api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the Active Directory domain password for a successful Azure network connection. This API is supported when the onPremisesConnection's type is hybridAzureADJoin.' is duplicated in 'beta/api/cloudpconpremisesconnection-updateaddomainpassword(deprecated).md(3,14)', 'beta/api/cloudpconpremisesconnection-updateaddomainpassword.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205191441262036-16631/BuildReport?accessString=4b9f2db9a8072bb6595a190cdb5c2d963086046befe3760f80135bc4749400e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 22:13 UTC, opbld33 commented
Docs Build status updates of commit _[88e1d7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88e1d7c940420a98d7d45554271288dd43561253)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205192210236046-16631/BuildReport?accessString=cfc0e6b34f1c35e462e3bc2218beb4d62a6e764b1783973605509ae5f568b966).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 22:18 UTC, opbld31 commented
Docs Build status updates of commit _[244f071](https://github.com/microsoftgraph/microsoft-graph-docs/commits/244f0717b49f273f4c1a52d74489f262a4467b1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205192215508357-16631/BuildReport?accessString=f4bcf411e983b9a0e87b2a375a0a4e37dbd7c0fcb8039034c8d16eebed054de7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 22:26 UTC, opbld32 commented
Docs Build status updates of commit _[0e61659](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e616590eb0fe15b583b8abd7ed3590593f05e08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205192224348209-16631/BuildReport?accessString=47a9c46c88275222760b7433b2862353bcb7f4e43ec6d59d8180bc75149dbc8e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 04:08 UTC, opbld30 commented
Docs Build status updates of commit _[fb85657](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb85657eca80e74bb95b094a4539b7d9631e5a3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205200406204575-16631/BuildReport?accessString=0ce87c53379f1ae268fbcdce4589904284ea2308301ef1bd17c7f1dc389da6a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 04:13 UTC, opbld33 commented
Docs Build status updates of commit _[51484f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51484f95f4e842e084a4b5ac33008fbfcdc9391e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205200411310663-16631/BuildReport?accessString=a3fbb127387782ca60a41d4fd3e94b743b18819f0721bf2436c39518afdcf9ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 07:00 UTC, opbld31 commented
Docs Build status updates of commit _[f66b961](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f66b9611c89345b8bb80a53374089c6b072e864d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205200650124578-16631/BuildReport?accessString=9b51ffe16a00c316854087e366760c133792eb08d0eda1690dc29cf920dbf4ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 13:20 UTC, isvargasmsft approved these changes
@Lauragra, would you be so kind to take a look at the changelog entry for this deprecation, please? 

I just want to make sure it's appropriate. 

Kind regards, 

Isaac

2022-05-24 02:31 UTC, opbld30 commented
Docs Build status updates of commit _[0116d23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0116d23c427b7da1d39ebba7fcc3595942cd9668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240229321992-16631/BuildReport?accessString=52aec234f4521616a992e1064e8dd137d23e8363c0e0ee2269fbbcdee8feb448).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 02:33 UTC, Lauragra commented on api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
> +POST /deviceManagement/virtualEndpoint/onPremisesConnections/{Id}/UpdateAdDomainPassword
To be clear, I think we should keep both the POST and PATCH syntax in the topic until the deprecation period is over, but call out that the PATCH syntax is deprecated.

2022-05-24 02:34 UTC, Lauragra commented on api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md
> +> Use POST for this operation. The PATCH method for this API will be deprecated after June 2022.
I suggest revising this note as follows:
The PATCH syntax for this action is deprecated and will stop working after June 2022. We recommend that you use POST going forward.

2022-05-24 02:39 UTC, opbld31 commented
Docs Build status updates of commit _[f1d4689](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1d4689421f63cc6ed7af0bb7308e568bbaf4f86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240236480770-16631/BuildReport?accessString=cdfac4c9439339b91a55e2ff8f94ebe17fc218a849e9a268923eda74acc74f57).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 17:30 UTC, isvargasmsft commented
@Emma0727 I took the liberty of implementing Laura's feedback. 

Please take a look and add the label "ready to merge" again if you are ok with the changes.

2022-06-01 17:34 UTC, opbld30 commented
Docs Build status updates of commit _[e498988](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4989882ab1fa021cf0785275445acfd3b5e7ddb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206011731076825-16631/BuildReport?accessString=503df6e220c8ace072ab2f50909dd7ad886a41165ec79145c351381cce6a777f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 03:41 UTC, opbld34 commented
Docs Build status updates of commit _[8661ef5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8661ef5015ee2cc92dd31ef981cf57f101888874)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-16631) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-04-20-wenyqiu/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206020339251302-16631/BuildReport?accessString=936d21fdf605963b092984efe2ab7094d1176191391488254b06f7bc9e198679).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 02:20 UTC, Lauragra approved these changes

2022-06-03 02:21 UTC, merged