Sumanac/pinnedmessage
microsoftgraph/microsoft-graph-docs pull request #16653
Opened 2022-04-25 22:06 UTC by sumanac

2022-04-25 22:09 UTC, opbld32 commented
Docs Build status updates of commit _[29da10e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29da10eb90efad5c5e6a249dd2da8db521818377)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinned-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinned-message.md) | :x:Error | | [Details](#user-content-1ed6a29af0796a05739ff023211ca4d2-f7d41222)
[api-reference/beta/api/chat-list-pinned-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinned-messages.md) | :x:Error | | [Details](#user-content-5167318c6d2dda03b838763970e2d9c2-f7d41222)
[api-reference/beta/api/chat-post-pinned-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinned-message.md) | :x:Error | | [Details](#user-content-01b5f591b14463ba1493fb9e1791f849-f7d41222)
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :warning:Warning | | [Details](#user-content-68335f3173540f38214cd52c1bcba0d1-f7d41222)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-0817dce4456c16725d5333633847d38f-f7d41222)

<a id="1ed6a29af0796a05739ff023211ca4d2-f7d41222"></a>
### [api-reference/beta/api/chat-delete-pinned-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinned-message.md)
 - **Line 62, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/unpin_message_from_chat-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/unpin_message_from_chat-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/unpin_message_from_chat-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/unpin_message_from_chat-java-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/unpin_message_from_chat-go-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/unpin_message_from_chat-powershell-snippets.md'.`````

<a id="5167318c6d2dda03b838763970e2d9c2-f7d41222"></a>
### [api-reference/beta/api/chat-list-pinned-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinned-messages.md)
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-pinned-messages-in-chat-csharp-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-pinned-messages-in-chat-javascript-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-pinned-messages-in-chat-objc-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-pinned-messages-in-chat-java-snippets.md'.`````
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-pinned-messages-in-chat-go-snippets.md'.`````
 - **Line 90, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-pinned-messages-in-chat-powershell-snippets.md'.`````

<a id="01b5f591b14463ba1493fb9e1791f849-f7d41222"></a>
### [api-reference/beta/api/chat-post-pinned-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinned-message.md)
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/post-pinnedchatmessages-1-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/post-pinnedchatmessages-1-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/post-pinnedchatmessages-1-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/post-pinnedchatmessages-1-java-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/post-pinnedchatmessages-1-go-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/post-pinnedchatmessages-1-powershell-snippets.md'.`````

<a id="68335f3173540f38214cd52c1bcba0d1-f7d41222"></a>
### [api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning: yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chat-list-pinnedMessages.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/pinnedmessage-update.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/pinnedmessage-delete.md'.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="0817dce4456c16725d5333633847d38f-f7d41222"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15525, Column 7**: **[Warning: yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204252206198850-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T22%3A09%3A19Z&sr=b&sp=r&sig=zL68qcxDadQW6g6wXu0nADCTKHLGwjC65TkNyDR6W9E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

** [...]

2022-04-28 17:12 UTC, opbld30 commented
Docs Build status updates of commit _[38c7a7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38c7a7ea58049024abe500acac9b77840b7a5afd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-16cb8d59)
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-16cb8d59"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15566, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-post-pinnedmessage.md'.`````
 - **Line 15568, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-delete-pinnedmessage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281709278337-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T17%3A12%3A25Z&sr=b&sp=r&sig=p9PRXBjwpn8nqJcFqBEQpCXMpKdTztIJWueHUV%2FbEaA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-28 17:19 UTC, opbld33 commented
Docs Build status updates of commit _[5684b28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5684b28de05fee21e17638cd00342583525d2e26)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-eb066225)
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-eb066225"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15566, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-post-pinnedmessage.md'.`````
 - **Line 15568, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-delete-pinnedmessage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281713075687-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T17%3A19%3A09Z&sr=b&sp=r&sig=88rlygnUVYHiJB9VpENW42bzNfg0XexxliqdLd%2FXrPk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 20:31 UTC, eddie-lee-msft requested changes
please also update the changelog.

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/toc.yml
> +        - name: List of pinned messages for a chat
List pinned messages in a chat

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +# List pinnedChatMessageInfoes
List pinned messages in a chat

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +### Example1: List all the pinned messages in the chat
Space between "example" and the number, here and everywhere else

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +GET https://graph.microsoft.com/beta/chats/{chatsId}/pinnedMessages
Some examples use "chatId" while others use an actual ID. Not sure which is most appropriate - maybe the latter since I see other docs doing that?

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-delete-pinnedmessages.md
> +# Delete pinnedChatMessageInfo
Unpin a message from a chat

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-delete-pinnedmessages.md
> +DELETE /chats/{chatsId}/pinnedMessages/{pinnedChatMessageInfoId}/$ref
{chat-id} to keep consistent with others?

also, maybe it could be {pinned-chat-message-id} for the other one?

btw is $ref always required?

2022-05-09 20:31 UTC, eddie-lee-msft commented on api-reference/beta/resources/pinnedChatMessageInfo.md
> +Represents an individual pinned message in a [channel](channel.md) or [chat](chat.md) entity.
should we mention channel if the api is only available for chat for now?

2022-05-09 21:23 UTC, opbld31 commented
Docs Build status updates of commit _[5164f97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5164f970388bd2bbb74097f608a473b643ae6af9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-47dc9e78)
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-47dc9e78"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15311, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-post-pinnedmessage.md'.`````
 - **Line 15313, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-delete-pinnedmessage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205092121193278-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T21%3A23%3A21Z&sr=b&sp=r&sig=3Wk0BQobxla78RJw%2BeYNlaXp9FxOYPk3QAJFiDKQSJU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 21:24 UTC, sumanac commented on api-reference/beta/api/chat-delete-pinnedmessages.md
> +DELETE /chats/{chatsId}/pinnedMessages/{pinnedChatMessageInfoId}/$ref
it was form autogenerated. removed.

2022-05-09 21:28 UTC, sumanac commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +GET https://graph.microsoft.com/beta/chats/{chatsId}/pinnedMessages
I know. It was because of some doc stub. I kept it both to get feedback. Thanks!

2022-05-09 21:28 UTC, opbld34 commented
Docs Build status updates of commit _[66ec96a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66ec96a9778e361794d902ef9315b10a27c3e91c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b40bd347)
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-b40bd347"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15311, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-post-pinnedmessage.md'.`````
 - **Line 15313, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chat-delete-pinnedmessage.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205092126451191-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T21%3A28%3A53Z&sr=b&sp=r&sig=qw0Gwm4K9lTc4CTqOb%2F2PBcGkj2iPHKAin98kdnOJvI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 21:29 UTC, sumanac commented on api-reference/beta/resources/pinnedChatMessageInfo.md
> +Represents an individual pinned message in a [channel](channel.md) or [chat](chat.md) entity.
I removed it for now. Same reason I kept it to get additional feedback which way to go.

2022-05-09 21:36 UTC, sumanac commented
> please also update the changelog.

added

2022-05-09 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[05f9782](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05f9782284e63013c0481b9cda3bbb56d019b6b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205092140175285-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T21%3A42%3A19Z&sr=b&sp=r&sig=kh2iGHDm8IhbOIXDlt0X6Xsb34b9zGTtJKQ3GsaKBOE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 21:54 UTC, opbld34 commented
Docs Build status updates of commit _[f8254ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8254ada911325c5d394bbe9fc3ffc177f732f10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205092146405072-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T21%3A54%3A40Z&sr=b&sp=r&sig=0YzalTxJon%2FyFtSGqegXuzWKyYd78KafiRFm1usF6Q4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 21:56 UTC, opbld32 commented
Docs Build status updates of commit _[9502fd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9502fd2fa6836aceb1bf0f7c143b48c9d4ea865f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205092151375116-16653%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T21%3A56%3A31Z&sr=b&sp=r&sig=Pc8XOseSOnmvlF5wZHFI1zkFAaZGGMC1T5FRBv3CJmM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 22:34 UTC, eddie-lee-msft approved these changes
Two things related to changelog. Otherwise looks good to me.

2022-05-09 22:34 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "GraphSvc"
I have been adding updates to change log in the .Core json instead of .GraphSvc json. But I'm not sure if it matters.

2022-05-09 22:34 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.GraphSvc.json
> +              "Description": "Added the **pinnedMessages** relationship to the [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource.",
Do we need to add updates for specific APIs you're exposing as well or just the new resources?

2022-05-10 22:51 UTC, JarbasHorst commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +GET https://graph.microsoft.com/beta/chats/{chat-id}/pinnedMessages
For clarity, please replace the placeholder {chat-id}, with a real-looking ID. Examples with real-looking values help customers understand the API better. That's also the consistency bar for Microsoft Graph API docs.

2022-05-10 22:51 UTC, JarbasHorst commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +### Example 1: List all the pinned messages in the chat
Please, add an introductory sentence to this heading. Suggested revision:

- The following examples shows a request that lists all the pinned messages in a chat.

Same for Example 2.

2022-05-10 22:51 UTC, JarbasHorst commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +description: "Retrieve list of pinned message info of a chat."
For clarity, I recommend you to rephrase this description. Suggested revision:

line 3: Get a list of pinned messages in a chat.

line 15: Get a list of \[pinned messages\](../resources/pinnedChatMessageInfo.md) in a [chat](../resources/chat.md).

2022-05-10 22:54 UTC, JarbasHorst commented
Hello @sumanac, I reviewed your PR and left some comments. Please, take a look when you will have time. 

Please, to avoid merge conflicts, please merge PR [16843](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16843) into your branch to include my fixes and before addressing my comments.

Also, can you please share with me a pointer to the CSDL and api.md files for this PR?

2022-05-18 17:48 UTC, sumanac commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "GraphSvc"
I added because that's where the change log showed up in CSDL PR. But I had to change the sub area to GraphSvc because it is not Shift. Then I had to update all "SubArea" because I started getting validation errors when keeping it empty after the change. 

https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/5998045?_a=files&path=/Changelog/5998045-schema-update-for-pinned-messages/Microsoft.Teams.GraphSvc.json

2022-05-18 17:49 UTC, sumanac commented on changelog/Microsoft.Teams.GraphSvc.json
> +              "Description": "Added the **pinnedMessages** relationship to the [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource.",
I am doing both. Therefore, kept both api and resource names.

2022-05-18 18:02 UTC, sumanac commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +GET https://graph.microsoft.com/beta/chats/{chat-id}/pinnedMessages
updated

2022-05-18 18:03 UTC, sumanac commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +description: "Retrieve list of pinned message info of a chat."
updated

2022-05-18 18:09 UTC, opbld31 commented
Docs Build status updates of commit _[ed67e93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed67e9344e3e3ec7a16b0439e9a16113981e8521)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181800534988-16653/BuildReport?accessString=b77df0e1ad9793432f9fe5620845134845de280f544ae4cb99188efd5dd27cbb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 18:37 UTC, opbld31 commented
Docs Build status updates of commit _[09a1027](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09a102792fe59ac15dad301938433d5b7adc444c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181835415995-16653/BuildReport?accessString=7c610fbcb0ce8a06dce3f9db3dddaadb116a98384d900432bd7d84677bfcf7ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 18:44 UTC, opbld32 commented
Docs Build status updates of commit _[1c02b33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c02b3319982693e736fca78dcc1a67e76117426)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181841328655-16653/BuildReport?accessString=90a0d550e971cee6a9afd880250ca0f12508b0f6259d58cff0a65e6dc267f6dd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 19:23 UTC, opbld31 commented
Docs Build status updates of commit _[7024d68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7024d686f8045e60efa8d3e9bbd3ca7eaf5169f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181921564977-16653/BuildReport?accessString=b9f451babcf6f29992cf858a4e848418134b737b24af458b8574adc107225808).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 19:31 UTC, RamjotSingh commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "GraphSvc"
Move to .Core for now and the SubArea is wrong too I believe. Please refer to the .Core file

2022-05-18 20:24 UTC, opbld33 commented
Docs Build status updates of commit _[1502a56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1502a563c53cd7ae51d73de3b141f93aaf0d390f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205182022510825-16653/BuildReport?accessString=b375b4edd73e1f9d25116a08e7fa597f48a0bd3e17a1ea2c39bae117a3cfcef9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 01:45 UTC, sumanac commented on api-reference/beta/api/chat-delete-pinnedmessages.md
> +---
Pin and unpin are the actions (quite similar to create and delete). PinnedChatMessageInfo is only to display information for a pinned message when is used to get list of pinned messages in a chat. The CRUD is not happening on PinnedChatMessageInfo.
If you see the POST and DELETE operation, it is on the chat message/message resource and not on PinnedChatMessageInfo  resource. 

chat/id/messages for POST
chat/id/message/id for DELETE

This is the response for next few comments as well. Please feel free to ping me to discuss about this> schema changes are already in prod. I would like to merge these changes, so our customers can start using the api.

2022-05-20 02:08 UTC, sumanac commented on api-reference/beta/api/chat-delete-pinnedmessages.md
> +title: "Unpin a message from a chat"
This is not pinnedChatMessageInfo. This is deleting a pinned message or unpin a message. We are using from a chat because there will be unpin a message from a channel.

2022-05-20 02:08 UTC, opbld31 commented
Docs Build status updates of commit _[bd0b6c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd0b6c57b4d895e2defabac288a9d2fb21d7d3a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedChatMessageInfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedChatMessageInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205200156405295-16653/BuildReport?accessString=aa4d2bd3bbec89c724d0b8628dbc745aeb499b6dd340a873fd12cfb78b50bb80).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 02:09 UTC, sumanac commented on api-reference/beta/api/chat-list-pinnedmessages.md
> +title: "List pinned messages in a chat"
I like to keep in a chat to provide the scope that it is the list of pinned messages in a chat. There will be pinned messages in a channel etc.

2022-05-20 02:10 UTC, sumanac commented on api-reference/beta/api/chat-post-pinnedmessages.md
> +title: "Pin a message in a chat"
Again, it is not creating a pinned message. :) It is pinning a message, As I explained above. like to keep it "in a chat" to differentiate between chat and channel pinned msg.

2022-05-20 02:12 UTC, sumanac commented on api-reference/beta/toc.yml
> +        - name: List pinned messages in a chat
Ok to change toc names. since these are showing up under "Chat" resource.

2022-05-22 01:13 UTC, opbld30 commented
Docs Build status updates of commit _[0bb49bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bb49bdde11d10d85aead9d5699a665db85bff74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205220111197964-16653/BuildReport?accessString=d7755bbcd08b0ce837b1b1c3268b784247e6f58e122a829c72fbdfeb574c81c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 02:53 UTC, opbld32 commented
Docs Build status updates of commit _[2674d5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2674d5ff152615259490ac9d5cf60f5a29af0930)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240251050163-16653/BuildReport?accessString=c5c862e153a1a7585b6e737c8a0c09f6d6a87e44a02049b8c244196970d43d8c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 03:07 UTC, opbld33 commented
Docs Build status updates of commit _[48078d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48078d47d501aa5a20a0922d4ef2927197f856a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240305360986-16653/BuildReport?accessString=46382d3173012284c9e554c2151f90a450834979a5da0887d66f91246ffb7e29).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 03:10 UTC, opbld34 commented
Docs Build status updates of commit _[cab9688](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cab9688f8b451a0382de7544c97b31cb608ef957)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240308225571-16653/BuildReport?accessString=a6755f7229ecda62a2c9ff8ab783d816b7b14625be1f49aef5a452ee3608f000).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 03:19 UTC, opbld30 commented
Docs Build status updates of commit _[20f752b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20f752ba18a632ae6aa77759e06fd6ebd131849e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240309591511-16653/BuildReport?accessString=84179d88994a1fb3f54b377ecdaf016b04ea8c20b5ccfc880e607df568d1e533).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 03:22 UTC, opbld32 commented
Docs Build status updates of commit _[b418022](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b418022213f552d9b3fa2ba122da32b7af4934e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-16653) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/pinnedmessage/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205240310333377-16653/BuildReport?accessString=0b31d3186b539ef0245736f0bb90c1c018a12a34155de33b0b26ed99777eb4f8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 03:29 UTC, Lauragra approved these changes

2022-05-24 03:29 UTC, merged