[CloudPC] Add connectivityStatus to CloudPc Entity
microsoftgraph/microsoft-graph-docs pull request #16685
Opened 2022-04-27 04:43 UTC by yayang3

2022-04-27 04:45 UTC, opbld33 commented
Docs Build status updates of commit _[07d7c1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07d7c1ca1e3f1d310a3453374dab51ba10f7339c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-b0e754085984eb60b3d99c7cf18d32fb-73927fa4)
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcconnectivityevent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-1cddfe5e921f424e0edbfa151bf8a515-73927fa4)
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcconnectivityresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-40c61195a0770720547ad0032a1c50ed-73927fa4)
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpchealthcheckitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-c7ad15e2967037e3ee93be5793384751-73927fa4)
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-reboot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-596fb9ecd709020569d00111e216334b-73927fa4)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |

<a id="b0e754085984eb60b3d99c7cf18d32fb-73927fa4"></a>
### [api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPC: reboot' is duplicated with other articles: 'beta/api/cloudpc-getcloudpcconnectivityhistory.md(10,1), beta/api/cloudpc-reboot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="1cddfe5e921f424e0edbfa151bf8a515-73927fa4"></a>
### [api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcconnectivityevent.md)
 - **Line 23, Column 14**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcConnectivityEventResult-values' in 'beta/resources/cloudpcconnectivityevent.md', did you mean '#cloudpcconnectivityeventresult-values'?`````
 - **Line 24, Column 12**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcConnectivityEventType-values' in 'beta/resources/cloudpcconnectivityevent.md', did you mean '#cloudpcconnectivityeventtype-values'?`````
 - **Line 56, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="40c61195a0770720547ad0032a1c50ed-73927fa4"></a>
### [api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcconnectivityresult.md)
 - **Line 22, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcConnectivityStatus-values' in 'beta/resources/cloudpcconnectivityresult.md', did you mean '#cloudpcconnectivitystatus-values'?`````
 - **Line 45, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="c7ad15e2967037e3ee93be5793384751-73927fa4"></a>
### [api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpchealthcheckitem.md)
 - **Line 24, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#../resources/cloudpcconnectivityevent.md#cloudPcConnectivityEventResult-values' in 'beta/resources/cloudpchealthcheckitem.md'.`````
 - **Line 36, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="596fb9ecd709020569d00111e216334b-73927fa4"></a>
### [api-reference/beta/api/cloudpc-reboot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-reboot.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPC: reboot' is duplicated with other articles: 'beta/api/cloudpc-getcloudpcconnectivityhistory.md(10,1), beta/api/cloudpc-reboot.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204270443466366-16685%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T04%3A45%3A41Z&sr=b&sp=r&sig=IGG1CAed1DpJTxMDugrh6xPcROBsIW3iQVs%2Bn4pwjSo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning [...]

2022-04-27 05:00 UTC, opbld34 commented
Docs Build status updates of commit _[135beb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/135beb055095b4e36e5d2b297127919b3e4a8144)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpchealthcheckitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-c7ad15e2967037e3ee93be5793384751-21d0f869)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |

<a id="c7ad15e2967037e3ee93be5793384751-21d0f869"></a>
### [api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpchealthcheckitem.md)
 - **Line 24, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#../resources/cloudpcconnectivityevent.md#cloudpcconnectivityeventresult-values' in 'beta/resources/cloudpchealthcheckitem.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204270451069793-16685%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T05%3A00%3A18Z&sr=b&sp=r&sig=0MlA6zxAB2r%2ByrwTcJ5lFoeRi3oG1K03p%2F9tSUpJIfE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 03:24 UTC, opbld31 commented
Docs Build status updates of commit _[a8e7e5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8e7e5d697f31646195e5fa2ea564a18037f08f4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-33a05650)

<a id="33a05650"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205160323576777-16685/BuildReport?accessString=24345d00f523f70905616b5eda4022aa84fa39ca9a636f8cf5011ecd7e00a307).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 03:44 UTC, opbld33 commented
Docs Build status updates of commit _[c597d2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c597d2b27a061eb5d992a31200103ad372700380)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7939c407)

<a id="7939c407"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205160344227708-16685/BuildReport?accessString=6405ed045a1d469b65901ed418dc03b2fc1e9d47d337233a15e26e35ff9c3e67).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 03:46 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpc.md
> +|connectivityResult|[cloudPcConnectivityResult](../resources/cloudpcconnectivityresult.md)|The connectivity health check result of a cloud pc, including the updated timestamp and whether the cloud pc
Please update: cloud pc -> Cloud PC

2022-06-30 03:49 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcconnectivityresult.md
> +|unknown|0|The cloud pc connectivity status is unknown.|
In the description of this file, you should describe as `Cloud PC`, not `cloud pc`. Please help correct :)

2022-06-30 05:09 UTC, RuiHou105 requested changes
Hi @yayang3 ,

1.In your PR, please correct the description from `cloud pc` to `Cloud PC`.

2.Please create a roadmap workitem and attach the work item number in this PR. Here is an [example]([Feature 14460](https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460): [DEVICES AND APPS][CLOUD PC] Add regionStatus to cloudPcSupportedRegion). If you don't have access, please do this firstly:
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

3.I see the build is failed. Not sure if your Github account has permissions. Please check. Thanks.

2022-06-30 09:21 UTC, AshleyYangSZ requested changes

2022-06-30 09:22 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/cloudPCs/9ec90ff8-fd63-4fb9-ab5a-aa4fdcc43ec9/getCloudPcConnectivityHistory
And please make the build pass.

2022-07-06 08:56 UTC, opbld32 commented
Docs Build status updates of commit _[6cda1dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cda1dc7e7e3d4122a20c4f621d1de19f7036d23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) | [Details](#user-content-c7ad15e2967037e3ee93be5793384751-b20c40f1)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="c7ad15e2967037e3ee93be5793384751-b20c40f1"></a>
### [api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md)
 - **Line 24, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#../resources/cloudpcconnectivityevent.md#cloudpcconnectivityeventresult-values' in 'beta/resources/cloudpchealthcheckitem.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207060854046766-16685/BuildReport?accessString=6a599ab6695d230f4e0a44bd3c2ff5425b9168dda1071d3562b1755bb00c1e73).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 06:38 UTC, opbld32 commented
Docs Build status updates of commit _[a30be43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a30be4398ef7614694f68fb9aa76d1ff1a53de32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110635573786-16685/BuildReport?accessString=9079aa519e19d2fbadfa8f6100806320cd9b52e595ff0ea759c5c7a68b849167).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 07:08 UTC, opbld33 commented
Docs Build status updates of commit _[2bd4cd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bd4cd75ff8e98b7f257fbe3b20e102a079f9cd3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110705344043-16685/BuildReport?accessString=972a7a5c45332c0fcea9e4e4b677fe046c739a6d609cc405a36574630174931b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 03:26 UTC, AshleyYangSZ approved these changes

2022-07-18 03:35 UTC, RuiHou105 approved these changes

2022-07-20 15:53 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcconnectivityevent.md
> +Represents the details of Cloud PC connectivity event.
Would please explain a bit further what is a connectivity event?

2022-07-20 16:16 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcconnectivityevent.md
> +|unknownFutureValue|999|Evolvable enumeration sentinel value. Do not use.|
Would you be so kind to provide a bit more details on the description of each of these members, please? Just using the names does not clarify the scenarios each member covers.

2022-07-20 16:31 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcconnectivityresult.md
> +Represents the details of the Cloud PC connectivity status.
Would you be so kind to explain a bit further what this resource is for? What represents a connectivity status and how is it related to the connectivity result?

2022-07-20 16:40 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md
> +
Doesn't this function support any function parameters? If so, please include an H2 for Function parameters.

2022-07-20 16:40 UTC, opbld31 commented
Docs Build status updates of commit _[899685e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/899685efbf97287ada5cf51f48b41d2fbfec9804)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207201637285174-16685/BuildReport?accessString=cc46776cf78957bf72e1f296ada426b6190f7dc13c73e193daa1f4d637eacd3b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 16:44 UTC, isvargasmsft requested changes
Hello @yayang3, 

Very complete work in this PR, thank you very much. 

Would you be so kind to explain a bit more in the descriptions of the resources, please?

Thank you very much!

Isaac

2022-07-22 03:08 UTC, yayang3 commented on api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md
> +
no, it doesn't

2022-07-27 08:27 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcconnectivityevent.md
> +Represents the details of Cloud PC connectivity event.
@yayang3 I think isvargasmsft hopes you could add the explain in the doc.

2022-07-27 09:53 UTC, opbld30 commented
Docs Build status updates of commit _[375ce70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/375ce705db07f0b09a86171eed658886d316ad45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207270949493086-16685/BuildReport?accessString=d7f2c8c09fb1d822d10b9cc9e0d63cf69e3e45c9621f36c1ad3f19647e62efc3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 14:36 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-get.md
> +      ]
@yayang3 this one is pending :)

2022-08-10 16:34 UTC, opbld32 commented
Docs Build status updates of commit _[151be64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/151be64412f1e1b092f167983bd5e1ba4825aff1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101631063000-16685/BuildReport?accessString=13381d56a4350a2d0bf0b74cee9821105e6ee5b61051bfce3347e13d6b81a5dd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 16:45 UTC, opbld33 commented
Docs Build status updates of commit _[7d6038a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d6038acd167a53de8e514f14aa610a53b3b34a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101643055412-16685/BuildReport?accessString=fd9fd296922a90f69a701418ca33167b6fd12906483924e85324e75871e9cfca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 03:47 UTC, yayang3 commented on api-reference/beta/api/cloudpc-get.md
> +      ]
Sorry I missed this. user-list-cloudpcs operation won't return this property, so we don't need to update that:)

2022-08-12 13:43 UTC, isvargasmsft approved these changes

2022-08-15 07:57 UTC, RuiHou105 commented
Hi @Lauragra , this PR is ready for final review. Could you please help review/ approve it? Thanks ahead!

2022-08-16 03:34 UTC, opbld31 commented
Docs Build status updates of commit _[eeb4733](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeb4733ec1754290979c0046a8a9640724fcb49b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160332457088-16685/BuildReport?accessString=d6150b7a4b3fcbd61abb2ad988ae1e9fbe7db88e1ab9e918c3b6683320e5f696).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:37 UTC, opbld32 commented
Docs Build status updates of commit _[ad4ef36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad4ef36d1b8044a3ebba4f8b969f514da3c0acb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160334037072-16685/BuildReport?accessString=c007be671ee304c0ddc55f9275857319f73407a4b732ede8a14d5384112f2da6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:39 UTC, opbld31 commented
Docs Build status updates of commit _[bc0e83c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc0e83cb7040a72f39d6129b9cb89c3b53e1d80e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/api/cloudpc-getcloudpcconnectivityhistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-getcloudpcconnectivityhistory?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityevent?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcconnectivityresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpcconnectivityresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcconnectivityresult?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/resources/cloudpchealthcheckitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/resources/cloudpchealthcheckitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpchealthcheckitem?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-16685) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yayang3/addConnectivityAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160335437316-16685/BuildReport?accessString=ebd0630e55ae20dddb5266d3e662ba82f3c281cc1227e4c2681388ca1ae0d099).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:40 UTC, merged