Fercobo msft dataset updates
microsoftgraph/microsoft-graph-docs pull request #16717
Opened 2022-04-28 17:45 UTC by fercobo-msft

Adding Teams datasets.

2022-04-28 17:59 UTC, opbld31 commented
Docs Build status updates of commit _[08ed589](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08ed589921c71bfdd5d3dca493565c402b2ec27c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202204281746012120-16717%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T17%3A59%3A32Z&sr=b&sp=r&sig=cBsWKy3jFFWSWGnb8ZRx1gyV1cUMfsg78KhkfydEd4U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 14:58 UTC, opbld30 commented
Docs Build status updates of commit _[a324fc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a324fc8c493720c8608002685585ad3634fe6cec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a67e3a97)

<a id="a67e3a97"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205161457324938-16717/BuildReport?accessString=16a8d418a1ae8ccf31fb6c9d63c2bec76a5054fe01674ed5ec42bb65309d5ebc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 18:02 UTC, David1997sb commented
This PR has been open since Jan and I have not received the pending datasets (SharepointSitesDataset_v0_Preview, and TeamsStandardChannelMessages) please tag me when this information is available. I will be closing the workitem associated with it [Substrate Docs Stories Board - Boards (visualstudio.com)](https://o365exchange.visualstudio.com/DefaultCollection/O365%20Sandbox/_boards/board/t/Substrate%20Docs/Stories/?workitem=2582223) and I can reopen it when the information of the datasets is shared with me.
@NikCharlebois

2022-07-29 20:46 UTC, opbld31 commented
Docs Build status updates of commit _[eeae4cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeae4cfb3dc45d595bbc57b2a516c7e2283a1fd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-eec3aa83)

<a id="b517e725ee2a7e4a3af152bafa212b43-eec3aa83"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 25, Column 84**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 25, Column 106**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 26, Column 84**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 26, Column 106**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 27, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 27, Column 103**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 47, Column 114**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 56, Column 109**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 56, Column 131**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 57, Column 100**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 57, Column 122**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 58, Column 164**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 58, Column 186**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 74, Column 95**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 74, Column 117**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'TBD'.`````
 - **Line 55, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 73, Column 106**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 73, Column 142**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292044533485-16717/BuildReport?accessString=254b638cd3f815e95f8e36e1608c6104be3a6784c7daa8a7e2ae70f2a2ad096f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 22:24 UTC, opbld33 commented
Docs Build status updates of commit _[fe6e0de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe6e0de351c80e40bdf61089fce30db72b0d2498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-3011b816)

<a id="b517e725ee2a7e4a3af152bafa212b43-3011b816"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 55, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292222036454-16717/BuildReport?accessString=ed9b23812de8ebe528d384b4d0cfa9457e85dcdab79ca659ffc5970e41bd9ed1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 22:26 UTC, opbld31 commented
Docs Build status updates of commit _[beda433](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beda43309589d6c714beb201c9d67e654180ae05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-47bfc1c9)

<a id="b517e725ee2a7e4a3af152bafa212b43-47bfc1c9"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 55, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292222242910-16717/BuildReport?accessString=4b17d13d1cb7f3fb58ce0b2be35352f094d89e8bc4db75242569cad52069a2c1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 22:28 UTC, opbld30 commented
Docs Build status updates of commit _[fbd3637](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbd3637d410ae71d66f287aa50f94ca50f988774)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-a581d1fc)

<a id="b517e725ee2a7e4a3af152bafa212b43-a581d1fc"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 53, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292227124886-16717/BuildReport?accessString=ab9c84ccd0d83b559df4905067e200157d9c5994d63a2a2d850bf61ff8d58ef9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 22:31 UTC, opbld34 commented
Docs Build status updates of commit _[f4cc4fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4cc4fbd9959a43a5a403456b3d1f868d67a9a02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-80c29c9a)

<a id="b517e725ee2a7e4a3af152bafa212b43-80c29c9a"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 53, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292230023879-16717/BuildReport?accessString=63efc025d688ee7f0fe8f16ab29224bec2d40af3a5b828c97186703d880826ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 22:58 UTC, opbld33 commented
Docs Build status updates of commit _[2e90cf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e90cf24c1e353f2665a673a2ea62e0155ed2fc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-5f40e14c)

<a id="b517e725ee2a7e4a3af152bafa212b43-5f40e14c"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292256219180-16717/BuildReport?accessString=9c496e7267626fe1600f7cc9ae1ed345f16fbaab6a6171717b21a7f7e72dee14).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 17:22 UTC, opbld34 commented
Docs Build status updates of commit _[ea8033f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea8033f90b88ee1d0f5aa908e024ed9e054ef08b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-a123e32b)

<a id="b517e725ee2a7e4a3af152bafa212b43-a123e32b"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 15, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 78, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Dataset name | Description | Sample and Schema | Billing |
|--|--|--|--|
| DocumentSharingDataset_v0_Preview | Contains information about sharing permissions of documents. | <ul><li> Sample</li><li>Schema</li></ul> | Free (under preview only). These datasets will be available to those in Preview. You will need to join the Graph TAP program using the signup form at https://aka.ms/GraphTAPForm  and request to join the Preview.  |
| SharePointSitesDataset_v0_Preview | Contains information about SharePoint sites. | <ul><li> Sample</li><li>Schema</li></ul> | Free (under preview only). These datasets will be available to those in Preview. You will need to join the Graph TAP program using the signup form at https://aka.ms/GraphTAPForm  and request to join the Preview.  |
|SharePointGroupsDataset_v0_Preview | Contains SharePoint group information, including details about group members.   | <ul><li> Sample</li><li>Schema</li></ul> | Free (under preview only). These datasets will be available to those in Preview. You will need to join the Graph TAP program using the signup form at https://aka.ms/GraphTAPForm  and request to join the Preview. |') are not allowed. You can only have one top-level heading.
`````
 - **Line 53, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031720387840-16717/BuildReport?accessString=796cd93f5ff113c1bb348c268cd8290dfea5680b1c58f87742b71a84b779b1eb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[e2b4042](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2b4042ee85637a649b8ba4feb56274aced6a662)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-134fd213)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-134fd213"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031853008018-16717/BuildReport?accessString=2b252cf00f13298a5b962529af5e07e4687b148f06a33badcee50789946e94ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 23:22 UTC, rimisra2 reviewed
Hey David, please make sure that the comma after pipelines is removed in the data-connect-pam file. Thanks!

2022-08-04 20:38 UTC, opbld32 commented
Docs Build status updates of commit _[bff8ba2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bff8ba20512a1227a3f178c4ec81d1185f6f0992)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-097165ab)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-097165ab"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 231**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042036555131-16717/BuildReport?accessString=66556bda4d607951ded57620daff40138a08c3e8ab4dfa8372a454b735e73de2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 20:41 UTC, opbld33 commented
Docs Build status updates of commit _[1e29449](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e2944950a0cfde6449430b67d2d86ce97c951c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-dfafc176)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-dfafc176"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 231**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042037153200-16717/BuildReport?accessString=be5479fd2744101015e59f601ad383213ef874db45c9019a8b8ad553b87a7ef4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:09 UTC, opbld34 commented
Docs Build status updates of commit _[88afe81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88afe816f9d3c4572fc4f0864c5dd334c18674ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-d3daa453)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-d3daa453"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 231**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042107472153-16717/BuildReport?accessString=3c04460c7cc150ab484aeb39f943720008c401a3104b610f20985b59a0d8d58d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:28 UTC, opbld31 commented
Docs Build status updates of commit _[78a2867](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78a2867b7dc7c2a078a31a2bcda435fc522a1459)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-ed6cce03)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-ed6cce03"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 231**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042126082704-16717/BuildReport?accessString=f55617574d258bb2cd125c5e8b2bfbf04343e7d64e023d7c71d5c6f4f1022da9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:48 UTC, opbld34 commented
Docs Build status updates of commit _[8f36394](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f3639451dc9b7fa32a7f6f2f4904c195de8ebaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-b3f70d83)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-b3f70d83"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 83**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 120**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042146308074-16717/BuildReport?accessString=d5681915401182fb8a244a0a3dcbef091c21af3cf2d9329051ef296e3ac0e1ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 22:06 UTC, opbld32 commented
Docs Build status updates of commit _[3417918](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34179189ed29282f91f9dd2f00ba5e80779d576c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-408275e4)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-408275e4"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 52, Column 126**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'NO' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 83**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 120**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042203311247-16717/BuildReport?accessString=ecd032aa952a2f76adfec42cc979745f09ff7cf107c2c62c64486c64ecdf6dee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 04:40 UTC, opbld34 commented
Docs Build status updates of commit _[1cd5acd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cd5acd9a601f895bc72c21addf92afdea5c9d82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) | [Details](#user-content-b517e725ee2a7e4a3af152bafa212b43-9b647d86)
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

<a id="b517e725ee2a7e4a3af152bafa212b43-9b647d86"></a>
### [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md)
 - **Line 81, Column 83**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 81, Column 120**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'PENDING' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208050438271138-16717/BuildReport?accessString=c6c248e33e5b589186260a522ddf286d4e4a0baa9e56efc2eb8b8e766ebbfcd0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 18:26 UTC, rimisra2 approved these changes

2022-08-05 23:06 UTC, opbld32 commented
Docs Build status updates of commit _[96d5616](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96d5616ab3f65f12e214210d7e745fd29c416e15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208052303434299-16717/BuildReport?accessString=d19c1dfa6aa52b85535507171619196cc82b18ed010a81b410fe33867ded5770).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 23:08 UTC, opbld31 commented
Docs Build status updates of commit _[dc12dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc12dfeb9ccd59e261c598e75245e55b21e45462)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208052304331271-16717/BuildReport?accessString=033ae9e68edaf0640b90e483832356aac31b9f4a0708e3625e984d04e20ce6fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 17:44 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +| BasicDataset_v0.TeamStandardChannelMessages_v0 | Contains a Teams standard channel messages details. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledata
```suggestion
| BasicDataset_v0.TeamStandardChannelMessages_v0 | Contains a Teams standard channel message details. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets/BasicDataSet_v0.TeamsStandardChannelMessages_v0.json)</li><li>[Schema](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/TeamsStandardChannelMessages_v0.md)</li></ul> | [Paid](https://azure.microsoft.com/pricing/details/graph-data-connect/) |
```

2022-08-09 17:45 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +| BasicDataSet_v0.TeamsStandardChannelMessages_v0  | Contains channel posts, and messages from Standard Channels in Teams.    | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutio
```suggestion
| BasicDataSet_v0.TeamsStandardChannelMessages_v0  | Contains channel posts and messages from Standard Channels in Teams.    | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets/BasicDataSet_v0.TeamsStandardChannelMessages_v0.json)</li><li>[Schema](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/BasicDataSet_v0.TeamsStandardChannelMessages_v0%20.md)</li></ul> | [Paid](https://azure.microsoft.com/pricing/details/graph-data-connect/) |
```

2022-08-09 17:48 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +| BasicDataSet_v0.GroupOwners_v0 | Contains the Teams Chat Group owners details. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets/GroupOwners_v0.js
```suggestion
| BasicDataSet_v0.GroupOwners_v0 | Contains the Teams Chat Group owners' details. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets/GroupOwners_v0.json)</li><li>[Schema](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/GroupOwners_v0.md)</li></ul> | [Free](https://azure.microsoft.com/pricing/details/graph-data-connect/) |
```

2022-08-09 17:57 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +Please consider that these datasets are available after 48 hours (about 2 days). For instance, you can query data for 07/01 starting on 07/03. 
```suggestion
Please consider that these datasets are available after 48 hours (about two days). For instance, you can query data for 07/01 starting on 07/03.  
```

2022-08-09 17:59 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +This data is available for only the past 21 days (about 3 weeks). For instance, if you would like to query data for 07/01, you can do so from 07/03 to 07/24. 
The data available is from the last 21 days (about three weeks). For instance, if you would like to query data for 07/01, you can do so from 07/03 to 07/24.

2022-08-09 18:01 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +| DocumentSharingDataset_v0_Preview | Contains information about sharing permissions of documents. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets
```suggestion
| DocumentSharingDataset_v0_Preview | Contains information about sharing permissions of documents. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets/DocumentSharingDataset_v0_Preview.json)</li><li>[Schema](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/DocumentSharingDataset_v0_Preview.md)</li></ul> | [Free (under preview only)](https://azure.microsoft.com/pricing/details/graph-data-connect/). These datasets will be available to those in Preview. You must join the Graph TAP program using the signup form at https://aka.ms/GraphTAPForm  and request to join the Preview.  |
```

2022-08-09 18:02 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +| DocumentSharingDataset_v0_Preview | Contains information about sharing permissions of documents. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets
```suggestion
| DocumentSharingDataset_v0_Preview | Contains information about sharing permissions of documents. | <ul><li> [Sample](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/sampledatasets/DocumentSharingDataset_v0_Preview.json)</li><li>[Schema](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/DocumentSharingDataset_v0_Preview.md)</li></ul> | [Free (under preview only)](https://azure.microsoft.com/pricing/details/graph-data-connect/). These datasets will be available to those in Preview. You must join the Graph TAP program using the signup form at https://aka.ms/GraphTAPForm  and request to join the Preview.  |
```

2022-08-09 18:03 UTC, Danielabom commented on concepts/data-connect-datasets.md
> +|VivaInsightsDataSet_v0  | Contains SharePoint group information, including details about group members.   | <ul><li> [Sample](https://github.com/niblak/dataconnect-solutions/blob/vivaarmtemplates/sa
```suggestion
|VivaInsightsDataSet_v0  | Contains SharePoint group information, including details about group members.   | <ul><li> [Sample](https://github.com/niblak/dataconnect-solutions/blob/vivaarmtemplates/sampledatasets/VivaInsightsDataset_v0.json)</li><li>[Schema](https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/SharePointGroupsDataset_v0_Preview.md)</li></ul> | [Free (under preview only)](https://azure.microsoft.com/pricing/details/graph-data-connect/). These datasets will be available to those in Preview. You must join the Graph TAP program using the signup form at https://aka.ms/GraphTAPForm  and request to join the Preview. |
```

2022-08-09 18:40 UTC, opbld32 commented
Docs Build status updates of commit _[1162b67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1162b670238d9d6e49b71658ff18cb37793a7288)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091837532083-16717/BuildReport?accessString=91d5f1b51e51a30f87236e157e6078f893b6fa4c2f0b5e7fd57755feba01405d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 18:41 UTC, David1997sb commented on concepts/data-connect-datasets.md
> +This data is available for only the past 21 days (about 3 weeks). For instance, if you would like to query data for 07/01, you can do so from 07/03 to 07/24. 
Changes applied.

2022-08-09 18:42 UTC, opbld32 commented
Docs Build status updates of commit _[be2eb0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be2eb0b8e11132944233f4c6e5752058619e3e19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091838437964-16717/BuildReport?accessString=505056d5a079e407d84759effefa084e92b7ae4d29ed49d0a7e18bbbb7e11502).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[8c373c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c373c1718040d2ea26205d3b30dfee617abcdf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091841181858-16717/BuildReport?accessString=879b0083ec720eaf8a88cd84511cb83f0d28b661686e6bccf10bf8a56a908b11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 19:32 UTC, David1997sb commented
@Danielabom please proceed with your review. All your feedback has been addressed.

2022-08-09 20:14 UTC, Danielabom commented on concepts/data-connect-faq.md
> +When creating the Synapse or Data Factory pipeline, you have to provide a service principal to the Microsoft 365 linked service. In Azure, a service principal is a security identity that represents a
Please make sure you use the official product/service name. For example: Azure Synapse.

2022-08-09 20:16 UTC, Danielabom commented on concepts/data-connect-pam.md
> +* If the Azure Synapse or Azure Data Factory pipeline or copy activity's name change, a new approval request is triggered. For example, a new approval is required if the data table or set of columns
A new approval request is triggered if the Azure Synapse or Azure Data Factory pipeline or copy activity's name change. For example, a new approval is required if the data table or set of columns that the copy activity is accessing changes.

2022-08-09 20:19 UTC, Danielabom requested changes
Hi @David1997sb , thank you for working on this PR. Please review my comments.

2022-08-09 21:06 UTC, David1997sb commented on concepts/data-connect-pam.md
> +* If the Azure Synapse or Azure Data Factory pipeline or copy activity's name change, a new approval request is triggered. For example, a new approval is required if the data table or set of columns
Done

2022-08-09 21:06 UTC, David1997sb commented on concepts/data-connect-faq.md
> +When creating the Synapse or Data Factory pipeline, you have to provide a service principal to the Microsoft 365 linked service. In Azure, a service principal is a security identity that represents a
Done

2022-08-09 21:08 UTC, opbld34 commented
Docs Build status updates of commit _[722b728](https://github.com/microsoftgraph/microsoft-graph-docs/commits/722b728d5f5d7660a32c9ba974c13cfa71f4f4b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092106101717-16717/BuildReport?accessString=c96559dc71d03094cbea30e4009795e6306d77c742e1471815b89ec0f790cca1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 21:11 UTC, opbld32 commented
Docs Build status updates of commit _[24e12f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24e12f3c0e2c32820baab1c663c250d87974e8cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092106305936-16717/BuildReport?accessString=ecf7da077fda8d0c6efa2ff960c4b4c4a7635e70eb7618d12c43d1c43afa22ac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 22:07 UTC, David1997sb commented
Feedback addressed @Danielabom

2022-08-09 22:11 UTC, Danielabom commented on concepts/data-connect-pam.md
> +* If the Azure Synapse or Azure Data Factory pipeline or copy activity's name change, a new approval request is triggered if the Azure Synapse or Azure Data Factory pipeline or copy activity's name c
Hi @David1997sb, my suggestion was: 
```suggestion
*  A new approval request is triggered if the Azure Synapse or Azure Data Factory pipeline or copy activity's name change. For example, a new approval is required if the data table or set of columns that the copy activity is accessing changes.
```

2022-08-09 23:08 UTC, opbld33 commented
Docs Build status updates of commit _[20cba57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20cba57bbb07e70a819704ffc448486c94638e00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092306535071-16717/BuildReport?accessString=b93b84a1043b8521aed4ec8a489c11d3c2330133d9082ed9a7037c32377493c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 15:05 UTC, Danielabom approved these changes
Changes look good. Thanks, @David1997sb

2022-08-10 16:21 UTC, David1997sb approved these changes

2022-08-11 02:50 UTC, opbld32 commented
Docs Build status updates of commit _[f2ab10f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2ab10f270f42444d12adf283df383fa7c8283e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-datasets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-datasets?branch=pr-en-us-16717) |
[concepts/data-connect-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-faq.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-faq?branch=pr-en-us-16717) |
[concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/concepts/data-connect-pam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-pam?branch=pr-en-us-16717) |
[includes/data-connect-quickstart-01.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fercobo-msft-dataset-updates/includes/data-connect-quickstart-01.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-quickstart?branch=pr-en-us-16717) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208110248114500-16717/BuildReport?accessString=97225237cbb76c4b21253f695b5cbce2797630fb0f05c17a87cad039e2814351).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 02:52 UTC, merged