Documentation changes for enabling subscriptions in v1.0
microsoftgraph/microsoft-graph-docs pull request #16724
Opened 2022-04-28 21:08 UTC by abshar-teams

Documentation changes for enabling Teams & channels subscriptions in v1.0

2022-04-29 20:17 UTC, eddie-lee-msft commented
There are some things missing from this PR:

- You need to update all the v1.0 subscription CRUD files with the newly supported resources: https://docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&tabs=http
- v1.0 'subscription.md' file needs to be updated with the newly supported resources
- beta 'subscription.md' file has some asterisks that need to be removed since some of those resources are now supported in v1.0
- v1.0 'webhooks.md' file needs to be updated

2022-04-29 20:19 UTC, eddie-lee-msft requested changes
See my other comment

2022-05-02 20:38 UTC, opbld30 commented
Docs Build status updates of commit _[63aa2ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63aa2caa982415126186933b93c9923724fe2875)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205022034159338-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T20%3A38%3A10Z&sr=b&sp=r&sig=4OhpTjaNHeK%2BA2ImwxPxTtDZ7r6hx1rhyrXiO6mnkg0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 20:53 UTC, opbld31 commented
Docs Build status updates of commit _[31ee77b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31ee77b0fb65209d98b87125b0926c57ddb2c61e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205022051146044-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T20%3A53%3A16Z&sr=b&sp=r&sig=k4u0VX30CmdiFli7uh1D0%2B0EvuGod9%2BTkvQZPMypZkc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 00:28 UTC, opbld30 commented
Docs Build status updates of commit _[5cac129](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cac12970cba4edb51ebdae0c1cc79364a61589b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205030026164844-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T00%3A28%3A39Z&sr=b&sp=r&sig=F47yPtbp1U0NUaoKTAxl0Baals1rmMvSJ3t9LJPBX9Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 01:06 UTC, opbld31 commented
Docs Build status updates of commit _[dfe8828](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfe8828ad2e4ad426999f956444846254c716b39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205030103562022-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T01%3A06%3A01Z&sr=b&sp=r&sig=mKRZRT0xkkcJiQ0j333jRBsedMjXNh4mqRepxt0Ot9s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 01:15 UTC, opbld34 commented
Docs Build status updates of commit _[08506b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08506b07ca7bf319419bb79d2f9a8ef879b74f37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205030113253148-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T01%3A15%3A32Z&sr=b&sp=r&sig=ymPmBqi1c05EaZv9%2FZ%2F4F3gPFiW2lzQneK2MBjtscdU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 18:21 UTC, eddie-lee-msft requested changes

2022-05-03 18:21 UTC, eddie-lee-msft commented on api-reference/v1.0/resources/subscription.md
> +- A [conversationMember](./conversationmember.md) in a team, channel, or chat in Microsoft Teams.
Remove mention of chat cuz that's only in beta still

2022-05-03 18:21 UTC, eddie-lee-msft commented on api-reference/v1.0/resources/subscription.md
> +- A [channel](./channel.md) in Microsoft Teams.
Can you update the "Maximum length of subscription per resource type" section below as well?

2022-05-04 03:32 UTC, abshar-teams commented on api-reference/v1.0/resources/subscription.md
> +- A [conversationMember](./conversationmember.md) in a team, channel, or chat in Microsoft Teams.
good catch

2022-05-04 03:34 UTC, opbld30 commented
Docs Build status updates of commit _[1247a3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1247a3e7a501d86752689c0298e55e7d715d424e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205040332085349-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T03%3A34%3A35Z&sr=b&sp=r&sig=RiLEVXG%2Fg76lVzzP%2B6HGYPB%2B4Rd4Hzi4WviBhBBXppA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 17:55 UTC, eddie-lee-msft approved these changes

2022-05-04 18:02 UTC, eddie-lee-msft commented on concepts/teams-changenotifications-team-and-channel.md
>  |Delegated (work or school account) | Team.ReadBasic.All, TeamSettings.Read.All, TeamSettings.ReadWrite.All | beta |
also what about the /teams resource? I am seeing mention of beta, but isn't that in v1 now too?

2022-05-04 20:18 UTC, abshar-teams commented on concepts/teams-changenotifications-team-and-channel.md
>  |Delegated (work or school account) | Team.ReadBasic.All, TeamSettings.Read.All, TeamSettings.ReadWrite.All | beta |
Ahh. Stupid miss from my side

2022-05-04 20:20 UTC, opbld34 commented
Docs Build status updates of commit _[bb57cc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb57cc0585a512c25846b5779338740e8eb3fbb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205042018270819-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T20%3A20%3A55Z&sr=b&sp=r&sig=7twEGvWjj7EFuFglXz4I%2FL2b4FlvkxefxaidYa6GKjE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 21:21 UTC, opbld30 commented
Docs Build status updates of commit _[3bcf63a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bcf63ad13ebffd3dee9e31c82be295c31018ee1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205042119058313-16724%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T21%3A21%3A10Z&sr=b&sp=r&sig=O3rL%2BMroGFD%2Fi40r93HpchsxDwHC4PV7doO%2FC53yHpU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-05 00:03 UTC, eddie-lee-msft approved these changes

2022-05-10 23:58 UTC, opbld31 commented
Docs Build status updates of commit _[1445f83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1445f83b421b09e332eb39cfbfbf4668049f5f4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205102355436491-16724/BuildReport?accessString=1c3a1b367a17daa80e9f4881cc601e38ac7fbfa63824816ed323fae88d51a0e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 00:26 UTC, opbld33 commented
Docs Build status updates of commit _[1db3e4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1db3e4d94699bd2e2fd063fcb8e48abcf71481d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205110022456650-16724/BuildReport?accessString=388ed9c8eac29acfe8b4c3a08cb6fdc11dbe2e27c0c9b762b473aedd51f7d855).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 19:08 UTC, opbld32 commented
Docs Build status updates of commit _[41ee217](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41ee217eb0be0cccc52797a168119cc555580ab9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121905578846-16724/BuildReport?accessString=f27a17f46efcdb946d1046cfde9e0c386cd2740075c104d84dc4f1331d414bee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-23 22:19 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/webhooks.md
>  | Teams [chatMessage][] | Changes to chat messages in all channels in all teams:<br>`/teams/getAllMessages` <br>Changes to chat messages in a specific channel:<br>`/teams/{id}/channels/{id}/messages`
@abshar-teams , does chatMessage in v1 support this (as described in the beta version of this file):
Changes to chat messages in all chats a particular user is part of:
/users/{id}/chats/getAllMessages

2022-05-23 22:25 UTC, angelgolfer-ms commented
@abshar-teams , just a heads-up, @isvargasmsft (your PR reviewer) asked me a question on this PR, and as I'm looking through it, I'm making a few comments as well. @isvargasmsft can help follow through any questions you may have on our comments.

2022-05-23 22:50 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/webhooks.md
@abshar-teams , in going through the existing topics about change notifications that apply to Teams resources as well, I noticed this topic is also a bit out-of-date for Teams' support:
https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#supported-resources

The topic is missing a few Teams resources that support rich notifications. Can you please update the topic as well?

2022-05-23 23:01 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/webhooks.md
> +| Teams [team][] | Changes to any team in the tenant:<br>`/teams` <br>Changes to a specific team:<br>`/teams/{id}` | Yes |
@abshar-teams , FYI if you need to edit a table, it's always a good idea to look at the table display on the staging site. For this topic, the staged topic is here (click  the "View" link returned as part of a opbldxx comment in Github): https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724 

You'd notice that the newline you added to form line 37 messed up the table row for conversationMember.
Please don't make that a new line.

2022-05-23 23:16 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-team-and-channel.md
The following comment applies to the entire topic: @abshar-teams , do you foresee that in the scope of supporting change notifications for the team and channel resources, will there be further scenarios, in addition to any team (or channel) in tenant, and a specific team (or specific channel)? Perhaps not?

Looks like with this API update, at least for these currently documented scenarios, v1 and beta are in parity. We should just remove that "Supported versions" column in each of the tables in this topic.

FYI by default, customers can assume our conceptual content apply to both v1 and beta. Where there is non-parity support in a conceptual topic, depending on the actual content for the non-parity support, we mark the corresponding title/section title/bullet item/table cell and so on, with "(preview)". 

For customers to learn this doc versioning mechanism, we uphold it consistently across the docs so that customers don't have to second-guess.

2022-05-23 23:18 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-team-and-channel.md
>  ### Example
For all the examples in this topic, please make sure they show the use of the v1.0 endpoint, not beta.

2022-05-23 23:22 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/webhooks.md
>  | Teams [chatMessage][] | Changes to chat messages in all channels in all teams:<br>`/teams/getAllMessages` <br>Changes to chat messages in a specific channel:<br>`/teams/{id}/channels/{id}/messages`
Please confirm per my last question.

I see that you left this example as beta only too, which would be consistent if that remains beta only.
https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?view=graph-rest-1.0&branch=pr-en-us-16724#subscribe-to-changes-at-the-user-level

2022-05-23 23:36 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-chat.md
>  |:--------------------|:---------------------------------------------------------|:-------------------|
Per my explanation in the teams-changenotifications-team-and-channel.md topic, please remove the "Supported versions" column in each table in this topic. 
Please also update your examples to access the v1.0 endpoint, not beta.

2022-05-23 23:36 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-chatMembership.md
>  |:--------------------|:---------------------------------------------------------|:-------------------|
Per my explanation in the teams-changenotifications-team-and-channel.md topic, please remove the "Supported versions" column in each table in this topic. 
Please also update your examples to access the v1.0 endpoint, not beta.

2022-05-23 23:36 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-teamMembership.md
Per my explanation in the teams-changenotifications-team-and-channel.md topic, please remove the "Supported versions" column in each table in this topic. 
Please also update your examples to access the v1.0 endpoint, not beta.

2022-05-23 23:51 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-team-and-channel.md
>  ### Example
This comment applies to the teams-changenotifications-chatmessage.md, which you haven't included in this PR.
To make that topic consistent with the rest of the docs in terms of the versioning mechanism in concept topics, please do the following in that topic:

(a) If it's true that subscriptions to  /users/{user-id}/chats/getAllMessages is still only available in beta, then append "(preview)" to the section title in line 259, like this:
 "Subscribe to changes at the user level (preview)"

If you want to, you can add a statement at the top of that section that the support is only available in the beta endpoint. 
We keep the examples in that sub-section accessing the beta endpoint.

(b) For all the tables in that topic, please remove the "Supported in version" table column, including the section with the title "Subscribe to changes at the user level (preview)".

(c) For the sections that apply to both v1 and beta, please update the examples to access the v1.0 endpoint.

2022-05-24 00:27 UTC, angelgolfer-ms commented on api-reference/v1.0/api/subscription-list.md
> +|[channel](../resources/channel.md) (/teams/{id}/channels) | Channel.ReadBasic.All, ChannelSettings.Read.All, Subscription.Read.All  | Not supported | Channel.ReadBasic.All, ChannelSettings.Read.All
This comment is for line 33:
Is this scenario supported in v1? 
/users/{id}/chats/getAllMessages

There are other topics in this PR that identify or assume that scenario is beta only.
Please make sure to remove this line if this scenario is supported in only beta.

2022-05-24 02:16 UTC, isvargasmsft commented on api-reference/v1.0/resources/webhooks.md
> +| Teams [team][] | Changes to any team in the tenant:<br>`/teams` <br>Changes to a specific team:<br>`/teams/{id}` | Yes |
Please organize this table in alphabetical order, similar to what's in the beta topic.

2022-05-24 02:30 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Enabled support for [teams and channel notifications](https://docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?view=graph-rest-1.0), [team and chann
2 comments here:
(a) To follow the existing support for the changelog JSON, please add a changelist record for each of the GET, PATCH, and DELETE operations as well. You can have the list and get (single subscription) operations in the same changelist record; just provide the corresponding links in the description.

(b) Please make the description for the changelist record specific to the operation(s). Using line 4988 as an example, you can say:
```
"Enabled change notifications support to [create]({link to "create" topic}) a subscription for [teams and channels]({link to concept topic}), [team and channel membership]({link to concept topic}), [chats]({link to concept topic}), and [chat membership]({link to concept topic})."
```

2022-05-24 02:44 UTC, angelgolfer-ms requested changes
Hi @abshar-teams , thanks for the PR. As mentioned earlier, @isvargasmsft looped me in for a question on the changelog. In order to answer him, I had to go through your PR, and hence you see a few comments from me. Please take a look and incorporate them. 

As @isvargasmsft is the reviewer for this PR, he might have additional comments for you. I reviewed what I needed to answer the initial question, so my review is not necessarily complete.

If you have specific questions about the versioning mechanism we use in the docs, please ping me on Teams. For other questions, @isvargasmsft can help follow up. Thanks!

2022-06-01 21:36 UTC, abshar-teams commented on api-reference/v1.0/resources/webhooks.md
>  | Teams [chatMessage][] | Changes to chat messages in all channels in all teams:<br>`/teams/getAllMessages` <br>Changes to chat messages in a specific channel:<br>`/teams/{id}/channels/{id}/messages`
chatMesssage is supported in v1, but not the users/id/chats/getAllMessages subscription.
Also, the current PR is not dealing with any 'message' specific subscriptions, just the teams,channels and members

2022-06-01 21:57 UTC, abshar-teams commented on api-reference/v1.0/resources/webhooks.md
> +| Teams [team][] | Changes to any team in the tenant:<br>`/teams` <br>Changes to a specific team:<br>`/teams/{id}` | Yes |
Thanks for pointing out this.
yes, i realized it when i started using markup editor extension with Visual Studio code.

2022-06-01 23:30 UTC, abshar-teams commented on api-reference/v1.0/api/subscription-list.md
> +|[channel](../resources/channel.md) (/teams/{id}/channels) | Channel.ReadBasic.All, ChannelSettings.Read.All, Subscription.Read.All  | Not supported | Channel.ReadBasic.All, ChannelSettings.Read.All
removed this line since its only available in v1.0

2022-06-01 23:39 UTC, abshar-teams commented on concepts/teams-changenotifications-team-and-channel.md
v1.0 and beta are the only 2 versions i can think of. I agree that it doesn't make sense to have a supported version column with both versions and especially when almost all the resources are available in both versions.
So, i have removed this column from all the tables. For the ones which are available in only beta (there is only one), i just added preview in the heading

2022-06-01 23:52 UTC, opbld32 commented
Docs Build status updates of commit _[6af3e4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6af3e4f4345a6855c0ca23f8c5785ba6fcdbb123)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-16724) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-16724) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-16724) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abshar-teams/gaNotifications/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-16724) |
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks-with-resource-data.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-16724) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-16724) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206012350192305-16724/BuildReport?accessString=65a4b86a02f630ad422d1583d8c21d8d4ea0e1778564637a3271d24a5c3e7bb0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2 [...]

2022-06-03 21:09 UTC, isvargasmsft approved these changes

2022-06-04 02:02 UTC, merged