Update outlook-change-notifications-overview.md
microsoftgraph/microsoft-graph-docs pull request #16731
Opened 2022-04-29 14:26 UTC by abheek-das

Removing Mail.ReadBasic from application permission scope list, as it's not supported today.

2022-05-05 01:32 UTC, angelgolfer-ms commented on concepts/outlook-change-notifications-overview.md
> +|[message](/graph/api/resources/message) | Changes to all messages in a user's mailbox: <br>`/me/messages`<br>`/users/{id}/messages`<br>Changes to messages in a user's mailFolder:<br>`/users/{id}/mai
Hi @abheek-das !
(Just did an extensive review of change notifications docs for Teams, so I just picked yours close to the top of the review queue to review as well!)
Hey this error of including Mail.ReadBasic as an application permission for change notifications for message, is not limited to this concept topic, unfortunately!
Can you please apply the fix to each of the 5 CRUD operations for the subscription resource, for both v1 and beta?

Thanks!

2022-05-05 01:34 UTC, angelgolfer-ms requested changes
Thanks, @abheek-das , for this fix. Please apply the similar fix to a few related topics, per my comment.

2022-05-09 07:21 UTC, abheek-das commented on concepts/outlook-change-notifications-overview.md
> +|[message](/graph/api/resources/message) | Changes to all messages in a user's mailbox: <br>`/me/messages`<br>`/users/{id}/messages`<br>Changes to messages in a user's mailFolder:<br>`/users/{id}/mai
Thanks @angelgolfer-ms , I have made the change in all the 10 files - both Beta & v1.0.

2022-05-09 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[245eb87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/245eb879808236c75d931e257b489e66dd78d747)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090712057665-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A26%3A45Z&sr=b&sp=r&sig=8Glu8uZ%2Beeiiv1veN446PKdPlOOPZiMx6yaplBxfHVc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:28 UTC, opbld33 commented
Docs Build status updates of commit _[be34143](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be341436bef65c0a1e406f5927eff3be46c9f0f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090713489940-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A28%3A42Z&sr=b&sp=r&sig=uMHI9vuRBIHWUC9Rqh6n5hlmDWiN9M3PhN6aupl3L3s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:30 UTC, opbld31 commented
Docs Build status updates of commit _[b8f4279](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8f4279f07167842886e49fb03db62c5d8d7dcb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090718366132-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A30%3A44Z&sr=b&sp=r&sig=Qp0bop173EFkIwu6AUa7%2BkGFWu9xJOO0qcpDJYF7JTg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:32 UTC, opbld31 commented
Docs Build status updates of commit _[50d999a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50d999a86ebe9eeb638488167c14b3f0655ec193)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090712555541-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A32%3A36Z&sr=b&sp=r&sig=jhmKWfXDcRUehRY57ksqrp0vB6ri8W41JpvopVHQg0E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:34 UTC, opbld32 commented
Docs Build status updates of commit _[f4e9288](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4e9288f3b6400d4c2b7fd36fc2e3fd128ca885c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090714575533-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A34%3A56Z&sr=b&sp=r&sig=nU6xwEUb%2B%2Bawu%2FXw5xowGxcNGZoYKe4U%2BHsRd81AooU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:37 UTC, opbld31 commented
Docs Build status updates of commit _[718fd3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/718fd3fb2384dc720d85b9136d6f86f619cab1ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090713246940-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A37%3A26Z&sr=b&sp=r&sig=QFHsfEPnWoTlHBo4dmU9JQrHd22STx0Gm4zqCZDTZ3Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:49 UTC, opbld30 commented
Docs Build status updates of commit _[076810d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/076810deebec9f15187cab2c3f9fad09a3232c6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090717098602-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A49%3A27Z&sr=b&sp=r&sig=2VRZ6Dvf42EP%2FGtDKC6eDST4l79J3rzLvn9tcCTk9Sw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 07:51 UTC, opbld31 commented
Docs Build status updates of commit _[f09f782](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f09f7828eaf149d6a8c779166f71a215b956bbce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090717334764-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T07%3A51%3A43Z&sr=b&sp=r&sig=1vhWhA7VSHejghqKCOgxEM0LQxXDLLEmR08S%2FuFX4Zw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 08:05 UTC, opbld34 commented
Docs Build status updates of commit _[f8bc645](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8bc645b39537347df37fbcc4104cad10b84cc61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090717550294-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T08%3A05%3A15Z&sr=b&sp=r&sig=Z4Bw9apxIfJfpE6HqR4FTVlInx0eoKl5mNoedL28WF8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 08:09 UTC, opbld30 commented
Docs Build status updates of commit _[afc3339](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afc333929f529c0c5a0edf0777a9f11770c973dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205090718163688-16731%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T08%3A09%3A53Z&sr=b&sp=r&sig=s0j9JT7DtBtVzmnzyz2vGxWmh3FFLbh0QFwXSvqNV%2FE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 06:37 UTC, opbld32 commented
Docs Build status updates of commit _[7f1a24c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f1a24c946b7dee6d75ffb92f816d79d79f7181f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205200630494810-16731/BuildReport?accessString=410db5823a1da4b239224116511873fd51d79a9a9034ec33339a4fc301c8353f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-25 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[653eda2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/653eda2dc212c3b02238bd8efa3ea755c643ee83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205250724201092-16731/BuildReport?accessString=a6af26c5a6a854efcdcac05d2c15dc18ebe24c1b9d03dc68e43f840b0b79bda3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-14 08:22 UTC, opbld32 commented
Docs Build status updates of commit _[78c186e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78c186e18eb6745be04b145d5f7852c4f585e30a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-16731) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-16731) (>= graph-rest-1.0) |
[concepts/outlook-change-notifications-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-rn-minor-fix/concepts/outlook-change-notifications-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-change-notifications-overview?branch=pr-en-us-16731) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206140819283053-16731/BuildReport?accessString=01a59c0f646dc3b105b870636e8387b29b50680cb2cb8769c565287ef1128a5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 02:12 UTC, merged