Updating EWS parity documentation of EWS to Graph APIs
microsoftgraph/microsoft-graph-docs pull request #16742
Opened 2022-05-02 10:23 UTC by sumithra-maran

Updating EWS parity documentation of EWS to Graph APIs.

2022-05-02 10:27 UTC, opbld34 commented
Docs Build status updates of commit _[5e5f21c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e5f21c8544eb0c7b182f92917b71a4b4fbf52dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-overview?branch=pr-en-us-16742) | [Details](#user-content-7bcc86a7eb27fe98ee326b10e4cbb86f-fe406f08)
[concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-authentication?branch=pr-en-us-16742) |

<a id="7bcc86a7eb27fe98ee326b10e4cbb86f-fe406f08"></a>
### [concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md)
 - **Line 20, Column 78**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/permissions-reference' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/sdks/sdks-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 78**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/permissions-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 141**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/sdks/sdks-overview' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205021023486222-16742%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T10%3A27%3A03Z&sr=b&sp=r&sig=0OSw0%2BuD4Pjb1ED2upezgDa%2FD5D7JS4c%2FTNGISPlaJM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 13:02 UTC, jasonjoh requested changes

2022-05-03 13:02 UTC, jasonjoh commented on concepts/migrate-exchange-web-services-overview.md
> +Microsoft Graph has stricter security and governance policies with OAuth and [granular scoping to limit data access](https://docs.microsoft.com/en-us/graph/permissions-reference) in a mailbox as oppo
Remove the `https://docs.microsoft.com/en-us` portion of the URL here to make it a relative URL. This will allow links in localized versions to work correctly.

2022-05-03 13:02 UTC, jasonjoh commented on concepts/migrate-exchange-web-services-authentication.md
> +With Microsoft Graph, there are no service accounts. Instead, permissions are granted to applications directly. The application authenticates using [client credentials flow](auth-v2-service.md) with
We can't say `MS Graph`. It has to be `Microsoft Graph`.

2022-05-03 13:02 UTC, jasonjoh commented on concepts/migrate-exchange-web-services-overview.md
> +Microsoft Graph offers [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) to discover and test APIs easily and quickly, [SDKs](https://docs.microsoft.com/en-us/graph/sdks/sdks-ove
Same note about making this relative URL.

2022-05-06 07:51 UTC, opbld34 commented
Docs Build status updates of commit _[9bf5eb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bf5eb59ce5bdccaa9d93d46f71bd575c34c894e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping?branch=pr-en-us-16742) | [Details](#user-content-476b1906fc56f2a21b9e455306f3a662-7c45a181)
[concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-overview?branch=pr-en-us-16742) | [Details](#user-content-7bcc86a7eb27fe98ee326b10e4cbb86f-7c45a181)
[concepts/migrate-exchange-web-services-authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-authentication?branch=pr-en-us-16742) |

<a id="476b1906fc56f2a21b9e455306f3a662-7c45a181"></a>
### [concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md)
 - **Line 128, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="7bcc86a7eb27fe98ee326b10e4cbb86f-7c45a181"></a>
### [concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md)
 - **Line 20, Column 78**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/permissions-reference' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/sdks/sdks-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 78**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/permissions-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 141**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/sdks/sdks-overview' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205060749056861-16742%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T07%3A51%3A16Z&sr=b&sp=r&sig=1U7mZ95uZ43%2BgNdNXvhQDMrROLHZVn99Uq8n9wRmDcs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 07:58 UTC, opbld30 commented
Docs Build status updates of commit _[a41c08a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a41c08a25a7a490f9de2cc06b9ec92876c24f7fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-overview?branch=pr-en-us-16742) | [Details](#user-content-7bcc86a7eb27fe98ee326b10e4cbb86f-5a8d1399)
[concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-authentication?branch=pr-en-us-16742) |

<a id="7bcc86a7eb27fe98ee326b10e4cbb86f-5a8d1399"></a>
### [concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md)
 - **Line 20, Column 78**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/permissions-reference' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/sdks/sdks-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 78**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/permissions-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 141**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/sdks/sdks-overview' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205060756008155-16742%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T07%3A58%3A06Z&sr=b&sp=r&sig=sSWPtIonDUH5Y%2BJKV952lXYhccCuPPFeZrcaZdwGLcU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 18:09 UTC, sumithra-maran commented on concepts/migrate-exchange-web-services-authentication.md
> +With Microsoft Graph, there are no service accounts. Instead, permissions are granted to applications directly. The application authenticates using [client credentials flow](auth-v2-service.md) with
Updated.

2022-05-18 18:09 UTC, sumithra-maran commented on concepts/migrate-exchange-web-services-overview.md
> +Microsoft Graph offers [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) to discover and test APIs easily and quickly, [SDKs](https://docs.microsoft.com/en-us/graph/sdks/sdks-ove
Updated.

2022-05-18 18:09 UTC, sumithra-maran commented on concepts/migrate-exchange-web-services-overview.md
> +Microsoft Graph has stricter security and governance policies with OAuth and [granular scoping to limit data access](https://docs.microsoft.com/en-us/graph/permissions-reference) in a mailbox as oppo
updated

2022-05-18 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[f9b3086](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9b30863279c4b7f4aa95401a342bd3f355da655)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-authentication?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-authentication.md.bak](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md.bak) | :white_check_mark:Succeeded | |
[concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-overview?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-overview.md.bak](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-overview.md.bak) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181815477533-16742/BuildReport?accessString=6d9b88b7d6cd7ebab977fe0231edcd1fb5d84846ac457a64120dbda1d2e1b0e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 18:46 UTC, opbld33 commented
Docs Build status updates of commit _[f2153b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2153b982b577b951f2c6875f5df30b9fc86053a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-authentication?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-overview?branch=pr-en-us-16742) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181844070587-16742/BuildReport?accessString=822f5ca79b41dd7353c106c568e3aebc88b2fc2347fe2fe23273607bb36a97e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[00181c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00181c0b55ffa99e5d1fb301073311acd22f9349)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-exchange-web-services-api-mapping.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-api-mapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/smaran_migrateewsdocchanges/concepts/migrate-exchange-web-services-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-authentication?branch=pr-en-us-16742) |
[concepts/migrate-exchange-web-services-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-exchange-web-services-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/migrate-exchange-web-services-overview?branch=pr-en-us-16742) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181853453820-16742/BuildReport?accessString=dc87b7e452c15dc163f3f67fcf55246c3632b6c4b2d00b5ae96bb019b6aa7211).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 18:57 UTC, merged