Move XTAP APIs to v1.0
microsoftgraph/microsoft-graph-docs pull request #16750
Opened 2022-05-02 23:32 UTC by jkdouglas

v1.0 prep

2022-05-02 23:34 UTC, opbld34 commented
Docs Build status updates of commit _[b00031a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b00031a3b725315774d409637c8e81edc3093ab2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :x:Error | | [Details](#user-content-ee650f9246bdbfc854569817177f8a92-8be1f966)
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :x:Error | | [Details](#user-content-ba3975891a91ee099337ae2a75e4c060-8be1f966)
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :x:Error | | [Details](#user-content-494788cb870a4593ceef960b6ae116c7-8be1f966)

<a id="ee650f9246bdbfc854569817177f8a92-8be1f966"></a>
### [api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md)
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-crosstenantaccesspolicyconfigurationpartner-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-crosstenantaccesspolicyconfigurationpartner-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-crosstenantaccesspolicyconfigurationpartner-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-crosstenantaccesspolicyconfigurationpartner-java-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-crosstenantaccesspolicyconfigurationpartner-go-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-crosstenantaccesspolicyconfigurationpartner-powershell-snippets.md'.`````

<a id="ba3975891a91ee099337ae2a75e4c060-8be1f966"></a>
### [api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md)
 - **Line 112, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-crosstenantaccesspolicyconfigurationpartner-from--csharp-snippets.md'.`````
 - **Line 116, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-crosstenantaccesspolicyconfigurationpartner-from--javascript-snippets.md'.`````
 - **Line 120, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-crosstenantaccesspolicyconfigurationpartner-from--objc-snippets.md'.`````
 - **Line 124, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-crosstenantaccesspolicyconfigurationpartner-from--java-snippets.md'.`````
 - **Line 128, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-crosstenantaccesspolicyconfigurationpartner-from--go-snippets.md'.`````
 - **Line 132, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-crosstenantaccesspolicyconfigurationpartner-from--powershell-snippets.md'.`````

<a id="494788cb870a4593ceef960b6ae116c7-8be1f966"></a>
### [api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-update.md)
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-crosstenantaccesspolicy-csharp-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-crosstenantaccesspolicy-javascript-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-crosstenantaccesspolicy-objc-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/update-crosstenantaccesspolicy-java-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/update-crosstenantaccesspolicy-go-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/update-crosstenantaccesspolicy-powershell-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205022332147910-16750%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T23%3A34%3A06Z&sr=b&sp=r&sig=%2B5uYFNnm5AW%2FrZjA1GpI0SvD%2FwnSalHOULkgH%2FORw7Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 23:39 UTC, jkdouglas commented
@FaithOmbongi - this is a copy/paste from our current Beta docs. Hopefully the review should be light. I don't think we have a CSDL PR yet, but as soon as we do I will link it here.

2022-05-02 23:39 UTC, opbld30 commented
Docs Build status updates of commit _[b9f7ad6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9f7ad6ef74a46e7b60172fb06b3dd8a283adaf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/m [...]

2022-06-14 15:54 UTC, opbld33 commented
Docs Build status updates of commit _[2020e94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2020e9418de499fbbff37ea5ea3ddb75bad06399)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicytarge [...]

2022-06-22 17:15 UTC, opbld32 commented
Docs Build status updates of commit _[c2e4056](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2e4056cf530a1a31436e0a7451352f279eb1b94)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f0b23180)

<a id="f0b23180"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221714289156-16750/BuildReport?accessString=9c9b59ee61fc0e4f93e0e2c95539da59e9c565781138509224bc406642d52778).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 17:26 UTC, jkdouglas commented
@FaithOmbongi - this is a light PR to bring the XTAP beta docs over to v1.0. Can you please review at your convenience?

2022-06-22 17:27 UTC, opbld34 commented
Docs Build status updates of commit _[4ef9a90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ef9a9077525f2c53f781595acde2b7523abd85f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2022-06-23 19:22 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        {
Add an entry for tenantRelationshipAccessPolicyBase resource type.

2022-06-23 19:24 UTC, FaithOmbongi requested changes
Hi @jkdouglas - I've gone with the assumption that the v1.0 will be exactly as the beta API except the allowedCloudEndpoints property. I hope my assumption is right.

2 gaps:

- Add a changelog entry for tenantRelationshipAccessPolicyBase.
- Document the crossTenantAccessPolicy relationship in the policyroot.md file and add a related changelog entry.

2022-06-27 17:55 UTC, jkdouglas commented
> Hi @jkdouglas - I've gone with the assumption that the v1.0 will be exactly as the beta API except the allowedCloudEndpoints property. I hope my assumption is right.
> 
> 2 gaps:
> 
> * Add a changelog entry for tenantRelationshipAccessPolicyBase.
> * Document the crossTenantAccessPolicy relationship in the policyroot.md file and add a related changelog entry.

@FaithOmbongi - could you review the 2 changes you requested and make sure I covered them? I added changelogs for each and added the relationship for crossTenantAccessPolicy in policyroot.

2022-06-27 17:58 UTC, opbld33 commented
Docs Build status updates of commit _[8fc732b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fc732b5c9009a858f8ac9aa1715b8827fc2d546)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2022-06-27 21:26 UTC, opbld33 commented
Docs Build status updates of commit _[35e952f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35e952f794108bc224cc5e7fc8e0323853562800)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyinboundtrust.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2022-06-29 16:55 UTC, opbld31 commented
Docs Build status updates of commit _[de14ea0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de14ea06f336a3acd198d75542ca0ee21e20a6ea)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-15cde625)

<a id="15cde625"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206291654521525-16750/BuildReport?accessString=f3f20e341bc4fcb696e1aa354f9a89d2a45cb9fba97c30f4aa6880c159d04f1c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-01 04:35 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +                - name: Cross-tenant access (preview)
Why do we have this entry with (preview) appended in the v1.0 TOC? I think we need to delete line 5141. Also, please remove the (preview) from the Cross-tenant access node in the toc.yml file in the /beta folder,

2022-07-01 16:10 UTC, jkdouglas commented on api-reference/v1.0/toc.yml
> +                - name: Cross-tenant access (preview)
I think it was a typo. I went ahead and removed the (preview) tag and updated the TOC for both v1.0 and beta.

2022-07-01 16:11 UTC, opbld32 commented
Docs Build status updates of commit _[25ce4b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25ce4b8835ed2d7ccff473a81c60fd5b8c1fb01a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-56911d5e)
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-16750) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/api/crosstenantaccesspolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-update?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyb2bsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyb2bsetting?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0&branch=pr-en-us-16750) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-move-to-v1/api-reference/v1.0/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cross [...]

2022-07-01 16:33 UTC, merged