Chalie teamstemplates graph api doc
microsoftgraph/microsoft-graph-docs pull request #16827
Opened 2022-05-10 00:57 UTC by charlieforce

2022-05-10 01:07 UTC, opbld31 commented
Docs Build status updates of commit _[8bfbb1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bfbb1dd38330ca733ef3a38fdf016ba54c6ddbb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamtemplate-delete-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-delete-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-delete-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-1b7de049da9becff62a3de81740666a7-351b1418)
[api-reference/beta/api/teamtemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-aefe302e8cce133a1170f751285999cd-351b1418)
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-list-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-915ee9077f25089f52996eb993a9e5fa-351b1418)
[api-reference/beta/api/teamtemplate-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-post-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-post-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-e5c699e8821cb60add746d3901ddc391-351b1418)
[api-reference/beta/api/teamtemplate-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-db34c866485b8a38d15b83b5c9d1bbb6-351b1418)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-271608dac4b75247d7fd1e6d4b77ea66-351b1418)
[api-reference/beta/api/teamtemplatedefinition-post-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-post-teamdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-post-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f93b64c7998696a6fcddd9906049dc7e-351b1418)
[api-reference/beta/api/teamtemplatedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-014cabca2a0adad1ffc1018106239196-351b1418)
[api-reference/beta/api/teamwork-delete-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-delete-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-delete-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-66aca8338ef7d834fe68ddb0e76db3be-351b1418)
[api-reference/beta/api/teamwork-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-01a21d678c2f39d61294a9227e7d7074-351b1418)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-bf61c7e7a84d07c1864e60b7197bbcc5-351b1418)
[api-reference/beta/api/teamwork-post-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-post-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-post-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-dc1d6e3b0d97b95e2620fdf91dfa1167-351b1418)
[api-reference/beta/api/teamwork-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-35546e93e706d08d0ecf95cff379b872-351b1418)
[api-reference/beta/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-joinedteams.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-3a7a637eee7758bc5cff219e75d8bf13-351b1418)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-351b1418)
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-492055e68b2345246662d0a56e1030d7-351b1418)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-351b1418)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-351b1418)
[api-reference/beta/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/conversationmember-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-70440f580b2962cbc5f748232bd70365-351b1418)
[api-reference/beta/resources/emailfileassessmentrequest [...]

2022-05-20 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[0fa72ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fa72acdfcce50dfc4bed8166020d9323778f766)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamtemplate-delete-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-delete-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-delete-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-1b7de049da9becff62a3de81740666a7-dd0d0465)
[api-reference/beta/api/teamtemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-aefe302e8cce133a1170f751285999cd-dd0d0465)
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-list-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-915ee9077f25089f52996eb993a9e5fa-dd0d0465)
[api-reference/beta/api/teamtemplate-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-post-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-post-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-e5c699e8821cb60add746d3901ddc391-dd0d0465)
[api-reference/beta/api/teamtemplate-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-db34c866485b8a38d15b83b5c9d1bbb6-dd0d0465)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-271608dac4b75247d7fd1e6d4b77ea66-dd0d0465)
[api-reference/beta/api/teamtemplatedefinition-post-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-post-teamdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-post-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f93b64c7998696a6fcddd9906049dc7e-dd0d0465)
[api-reference/beta/api/teamtemplatedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-014cabca2a0adad1ffc1018106239196-dd0d0465)
[api-reference/beta/api/teamwork-delete-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-delete-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-delete-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-66aca8338ef7d834fe68ddb0e76db3be-dd0d0465)
[api-reference/beta/api/teamwork-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-01a21d678c2f39d61294a9227e7d7074-dd0d0465)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-bf61c7e7a84d07c1864e60b7197bbcc5-dd0d0465)
[api-reference/beta/api/teamwork-post-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-post-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-post-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-dc1d6e3b0d97b95e2620fdf91dfa1167-dd0d0465)
[api-reference/beta/api/teamwork-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-35546e93e706d08d0ecf95cff379b872-dd0d0465)
[api-reference/beta/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-joinedteams.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-3a7a637eee7758bc5cff219e75d8bf13-dd0d0465)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-dd0d0465)
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-492055e68b2345246662d0a56e1030d7-dd0d0465)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-dd0d0465)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-dd0d0465)
[api-reference/beta/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/conversationmember-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-70440f580b2962cbc5f748232bd70365-dd0d0465)
[api-reference/beta/resources/urlassessmentrequest.md](h [...]

2022-05-20 21:48 UTC, opbld30 commented
Docs Build status updates of commit _[83453c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83453c1aeb3467cb6a34ef989b5b07f01511014f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamtemplate-delete-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-delete-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-delete-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-1b7de049da9becff62a3de81740666a7-85e8d228)
[api-reference/beta/api/teamtemplate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-aefe302e8cce133a1170f751285999cd-85e8d228)
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-list-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-915ee9077f25089f52996eb993a9e5fa-85e8d228)
[api-reference/beta/api/teamtemplate-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-post-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-post-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-e5c699e8821cb60add746d3901ddc391-85e8d228)
[api-reference/beta/api/teamtemplate-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplate-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-db34c866485b8a38d15b83b5c9d1bbb6-85e8d228)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-271608dac4b75247d7fd1e6d4b77ea66-85e8d228)
[api-reference/beta/api/teamtemplatedefinition-post-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-post-teamdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-post-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f93b64c7998696a6fcddd9906049dc7e-85e8d228)
[api-reference/beta/api/teamtemplatedefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamtemplatedefinition-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-014cabca2a0adad1ffc1018106239196-85e8d228)
[api-reference/beta/api/teamwork-delete-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-delete-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-delete-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-66aca8338ef7d834fe68ddb0e76db3be-85e8d228)
[api-reference/beta/api/teamwork-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-01a21d678c2f39d61294a9227e7d7074-85e8d228)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-bf61c7e7a84d07c1864e60b7197bbcc5-85e8d228)
[api-reference/beta/api/teamwork-post-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-post-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-post-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-dc1d6e3b0d97b95e2620fdf91dfa1167-85e8d228)
[api-reference/beta/api/teamwork-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-35546e93e706d08d0ecf95cff379b872-85e8d228)
[api-reference/beta/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-joinedteams.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-3a7a637eee7758bc5cff219e75d8bf13-85e8d228)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-85e8d228)
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-492055e68b2345246662d0a56e1030d7-85e8d228)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-85e8d228)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-85e8d228)
[api-reference/beta/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/conversationmember-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-70440f580b2962cbc5f748232bd70365-85e8d228)
[api-reference/beta/resources/fileassessmentrequest.md]( [...]

2022-05-24 22:09 UTC, opbld32 commented
Docs Build status updates of commit _[aa234ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa234ec1b1f9b07ae751a559ce9cc82071d261b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-bf61c7e7a84d07c1864e60b7197bbcc5-e6478687)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-e6478687)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-e6478687)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-e6478687)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-e6478687)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="bf61c7e7a84d07c1864e60b7197bbcc5-e6478687"></a>
### [api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md)
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````
 - **Line 52, Column 60**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-e6478687"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 117, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-templates-list.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-e6478687"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 145, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-templates-list.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="f2ad1bce904975eec0f2459988ab4537-e6478687"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-e6478687"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-get.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-update.md'.`````
 - **Line 26, Column 62**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-post-teamtemplates.md'.`````
 - **Line 27, Column 63**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````
 - **Line 38, Column 16**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** [...]

2022-05-25 18:31 UTC, isvargasmsft commented on api-reference/beta/resources/teamtemplatedefinition.md
> +# teamTemplateDefinition resource type
Topic title and file name: they should match the name in the CSDL. In this case, teamTemplate.
So, the file name should be teamtemplate.md and the topic title teamTemplate resource type. 

Guidelines here: 
Topic title: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title
File name: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming

2022-05-25 18:35 UTC, isvargasmsft commented on api-reference/beta/resources/teamstemplate.md
>  ## See also
File name and topic title of this document: According to the CSDL, the entity is called teamtemplate, but in the docs we have the title and file name in plural: teamstemplate. Could you please update the documentation to reflect the real name of the entity in singular?

2022-05-25 19:11 UTC, isvargasmsft requested changes
Hello @charlieforce,

Thank you very much for your contribution to the repo. 

I left some comments regarding consistency. Please let me know if you have questions. 

Kind regards, 

Isaac

2022-05-25 19:24 UTC, opbld31 commented
Docs Build status updates of commit _[7854f67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7854f678f8a03492e71bf2658984e87f6ec259aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-bf61c7e7a84d07c1864e60b7197bbcc5-233ac844)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-233ac844)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-233ac844)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-233ac844)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-233ac844)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="bf61c7e7a84d07c1864e60b7197bbcc5-233ac844"></a>
### [api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md)
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````
 - **Line 52, Column 60**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-233ac844"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 95, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-templates-list.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-233ac844"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 120, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-templates-list.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="f2ad1bce904975eec0f2459988ab4537-233ac844"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-233ac844"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````
 - **Line 23, Column 62**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-get.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-post-teamtemplates.md'.`````
 - **Line 25, Column 63**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/teamtemplate.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-update.md'.`````
 - **Line 37, Column 16**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]**  [...]

2022-06-13 16:31 UTC, isvargasmsft commented on changelog/Microsoft.Teams.Core.json
> +        },
This entity is missing a resource topic.

2022-06-13 17:01 UTC, opbld32 commented
Docs Build status updates of commit _[d930a08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d930a08201a0feb65e3b68919bf4d177efb89417)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-8751e032)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-8751e032)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-8751e032)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-8751e032)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0a5be47aa2d12d953d007473a1625a70-8751e032"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 95, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-templates-list.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-8751e032"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 120, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-templates-list.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="f2ad1bce904975eec0f2459988ab4537-8751e032"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-8751e032"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-get.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-post-teamtemplates.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-update.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206131659214640-16827/BuildReport?accessString=d582dd6c8b939a22c3bf3ec06d049a9d5920436f0cde039103cc4fe075855a7d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [in [...]

2022-06-13 17:25 UTC, opbld31 commented
Docs Build status updates of commit _[04d0df2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04d0df2eb1c847f810d0227d1693f85229dd0bc3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-ae2b86e3)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-ae2b86e3)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-ae2b86e3)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-ae2b86e3)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-ae2b86e3"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-ae2b86e3"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-get.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-post-teamtemplates.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-update.md'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-ae2b86e3"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-ae2b86e3"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206131722193044-16827/BuildReport?accessString=81d8061e7e2860b54d42a29632812f3f6002d433f892313a82750af1a9971397).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https: [...]

2022-06-13 18:00 UTC, opbld31 commented
Docs Build status updates of commit _[d8c1ab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8c1ab9d4bfbc0ddfe680975e2c745c74ea31613)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-9f5b2166)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-9f5b2166)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-9f5b2166)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-9f5b2166)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-9f5b2166"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-9f5b2166"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-get.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-post-teamtemplates.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-update.md'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-9f5b2166"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-9f5b2166"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206131757340643-16827/BuildReport?accessString=703d88a15b7316fc035a16d5db9e8a6cea20387d729891faf8cac1fc1f897567).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https: [...]

2022-06-13 18:07 UTC, opbld30 commented
Docs Build status updates of commit _[c05d008](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c05d0080f833c449046310861b7ec1d527649e7a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-6b2eb414)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-6b2eb414)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-6b2eb414)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-6b2eb414)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-6b2eb414"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-6b2eb414"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-6b2eb414"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-6b2eb414"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206131803239918-16827/BuildReport?accessString=df1b60c29b44f9a453aa50d4bcd20056f29f30867405c3478934cad66be9fc54).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 18:20 UTC, opbld31 commented
Docs Build status updates of commit _[e895920](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8959209d64f67a094a200490faaaf1e0ccef16c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-963dd14d)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-963dd14d)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-963dd14d)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-963dd14d)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-963dd14d"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-963dd14d"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-963dd14d"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-963dd14d"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206131816385738-16827/BuildReport?accessString=d87f0d6ee7ea23da5bfa6a0560db5878fb2ba6332318efc626d029164344f87a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 20:10 UTC, isvargasmsft commented on api-reference/beta/resources/teamtemplatedefinition.md
> +|audience|teamTemplateAudience|Describes the audience the team template is available to.The possible values are: `organization`, `user`, `public`, `unknownFutureValue`.|
```suggestion
|audience|teamTemplateAudience|Describes the audience the team template is available to. The possible values are: `organization`, `user`, `public`, `unknownFutureValue`.|
```

2022-06-13 20:48 UTC, isvargasmsft commented on api-reference/beta/resources/teamwork.md
> +|teamTemplates|[teamTemplate](../resources/teamtemplate.md) collection|**TODO: Add Description**|
Please remember to add a description to this relationship in line 34.

2022-06-13 20:55 UTC, isvargasmsft commented on api-reference/beta/api/teamwork-list-teamtemplates.md
> +---
General question:

According to the CSDL, the new navigation property called teamtemplates in the teamwork entity has a type of teamtemplate. However, in the api.md this entity (teamtemplate) doesn't have CRUD operations (Get, List, etc). 

On the other hand, according to the api.md, the teamTemplateDefinition entity supports Get and List. But I don't see a List operation for this entity. 

Could you please clarify?

2022-06-13 21:20 UTC, isvargasmsft requested changes
Hello Charlie, 

Really nice meeting you and thanks for the work in this PR. 

Place take a look at a couple of inconsistencies I pointed to in the comments. Specially, please clarify the List operations in this PR.

I need to understand which operation belongs to which resource to properly review the rest. 

Please ping me on the side if you have questions. 

Kind regards, 

Isaac

2022-06-13 23:26 UTC, opbld34 commented
Docs Build status updates of commit _[e75f723](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e75f723377ad1aff3630de57d059254cb5aabba2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-3dc5b7cc)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-3dc5b7cc)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-3dc5b7cc)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-3dc5b7cc)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-3dc5b7cc"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-3dc5b7cc"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-3dc5b7cc"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-3dc5b7cc"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206132324096812-16827/BuildReport?accessString=c693a48f2242fae288a8b9f49b02901bc959a3eeeefb46e961653efe88b74501).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 23:27 UTC, charlieforce commented on api-reference/beta/api/teamwork-list-teamtemplates.md
> +---
I confirmed with the team and:

teamTemplate does have Get and List. The call for teamTemplateDefinition are the same than those fro teamTemplate except they include the $expand=definitions parameter at the end

So if I do:

GET /beta/teamwork/teamTemplates

I will get all of the teamTemplates available for the user. But if I call 

⁠GET /beta/teamwork/teamTemplates?$expand=definitions

I'll get the teamTemplateDefinitions

There are also no inheritance between the 2 entities..
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABMMAAAFpCAYAAACRVu8UAAAgAElEQVR4AezdX28cx53o/fMyMq+Cl4JvDARY3xE4N2s8F9EuFivAwPogQODZi8C52DECxYISEwTxBIRhSqvHh0cQs/AIoY+iQJSOGIh5NjS4hEHa1Im4xxkJlE0mDxGT8GGYww1+D6q7qruqume6Z7pneqbna0DmTP+pP5+qrun+TXXPfxL+QwABBBBAAAEEEEAAAQQQQAABBBBAYEoE/tOU1JNqIoAAAggggAACCCCAAAIIIIAAAgggIATD6AQIIIAAAggggAACCCCAAAIIIIAAAlMjQDBsapqaiiKAAAIIIIAAAggggAACCCCAAAIIEAyjDyCAAAIIIIAAAggggAACCCCAAAIITI0AwbCpaWoqigACCCCAAAIIIIAAAggggAACCCBAMIw+gAACCCCAAAIIIIAAAggggAACCCAwNQIEw6amqakoAggggAACCCCAAAIIIIAAAggggADBMPoAAggggAACCCCAAAIIIIAAAggggMDUCBAMm5qmpqIIIIAAAggggAACCCCAAAIIIIAAAgMFw9pvNKTRSP935e7RaFS35ruWodGYl63RlCLKZWtOeYw+36gAvEAAAQQQQAABBBBAAAEEEEAAAQQQyBQYKBh29OkTebKh/t2Ut1RQ7B9v6vdPZPfL88xMS9ng+FmU573rr0uj8bpcWzXleiYnpWSSP5F+gmEnW4vy1l+/Jfe+zJ8+WyKAAAIIIIAAAggggAACCCCAAAIIFBcYKBgWZ7sl8yoYNjfqeVhxCdSro7tXpNG4Iu0Kg0v9BMPGobyuIO8QQAABBBBAAAEEEEAAAQQQQACB6RAYQjDsXJ7dfUcuf3tGGo0ZefVv35GHLwzmiWzdeFuva0jjlcvyzoPneqUJrD2U3Rtvyqszav0VufnZuZx/dlPeDNK7JJd/+FDMHibV1ODS8ZYsfm9WLqlg3Suz8taNXTFz1kzg6qGV7hW1/ptdufkPr8pMoyGXvmOV+8u2XGk05Mq/PLPKdlneufsskWYYFuxezzBv6xbTN9oS3Fj6zTNp//ByWO+ZV1PraerLXwQQQAABBBBAAAEEEEAAAQQQQACBwQRKD4Y9v/umzDRm5dqj53JytCu3vzsjjdlF2Q3Ktys3/+m2bL04iddFM7p0MGzmdbn2i2fyfP+eXJttSOOvZuX1792UrRfP5cnc5SDAdm3DhLXCSieCYd9syfxsQ2a+e1t2j07k+aNrMtuYkbcfhDdPhgGpGXn9+j159uKZ3PvRrDQar8nsX78lN7eey/ONebncaMjMj56EwS4dDHvtry7Ltbu78vzFrrT1PvNbYVlMgC0MhvWo5zcn8mw5nMl2++mJnJyo/Z9LO3C6Jg9fnMjRZ7flzZmGzL4fqg3WtOyFAAIIIIAAAggggAACCCCAAAIIIOALlBwM25X5mYa89lMriPPZorzWmJH5T/2sRUQ/BH8+iCDpYNj37kXP+3q+HD4L7Pbv9L5H9+RNNUPLe0i/Hww7Wn1TGo235N6xyfNEHn6/IY3v3gtmYYWBK2v9727L642GvL5s5pwdyb3vNqRhZm2ZYJhdr/Mn8o4KmC2EdXWDYSZf/depZ8ptnZ/Oy0zjNVn8LN5v9/3XpDEzr4OI8XJeIYAAAggggAACCCCAAAIIIIAAAggMLlBuMEwHjdJ+aTIMeJ3Is1/clHe+97q8/tfh7YhqWycYZj1/zA9yiYQBs6xgWBiYsm5FNL98qYNbicCVuQ3SCrIF23jBMDdfc1tnOBfMTbNXPZPBsLCeKeXl1ykH79nsiQACCCCAAAIIIIAAAggggAACCKQIlBsMk3Bm2Oz7W3Jyom4BjP+dX4g8v6Nuc7wii1vPg3Xnm/MyjGBYODPsbbn3ZZx/WJa0WxpFJGcwLJ45JiLH94Jf0nxN38poB8N61zMZDJNgZtisLG6llzel3ViEAAIIIIAAAggggAACCCCAAAIIIDCAQMnBsHPZXZiVxsxlmX/0TI5OTuRo/6Hc/OnD4PbE3QX1UH31UPwjOXmxJTfVc7KGMDNMvrwXPnPrB/r5ZCfPZevuNbmtb9W0A1eBWc5g2MwrV2R+43lQ9ts/UM8ZuyzmFk47zd71FAmDda/JO6vPZHdzV47Od8NnnP3tvDzcP5KTkyN59uimLD4KHq0/QLOyCwIIIIAAAggggAACCCCAAAIIIIBAmkDJwTCVxYls/fQtmX0lvO1v5tuX5e07+pccXzyUd75zKQiAXfrOvDxZvTacYJiInO+35Z2/NbdiXpLZ783Lky9DAjtwFSzJGQy7cuuh3P7HMM2Zb78pNz8NH8iv0nDS7FlPEVG/WvmGdvjHMFAo9q9fBr/C+bbc/sz9oYCw9PwfAQQQQAABBBBAAAEEEEAAAQQQQGBQgYLBsEGznbD9UoJlE1YDiosAAggggAACCCCAAAIIIIAAAgggICIEw/J0A4JheZTYBgEEEEAAAQQQQAABBBBAAAEEEBh7AYJheZqIYFgeJbZBAAEEEEAAAQQQQAABBBBAAAEExl6AYNjYNxEFRAABBBBAAAEEEEAAAQQQQAABBBAoS4BgWFmSpIMAAggggAACCCCAAAIIIIAAAgggMPYCBMPGvokoIAIIIIAAAggggAACCCCAAAIIIIBAWQIEw8qSJB0EEEAAAQQQQAABBBBAAAEEEEAAgbEXIBg29k1EARFAAAEEEEAAAQQQQAABBBBAAAEEyhIgGFaWJOkggAACCCCAAAIIIIAAAggggAACCIy9AMGwsW8iCogAAggggAACCCCAAAIIIIAAAgggUJYAwbCyJEkHAQQQQAABBBBAAAEEEEAAAQQQQGDsBQiGjX0TUUAEEEAAAQQQQAABBBBAAAEEEEAAgbIECIaVJUk6CCCAAAIIIIAAAggggAACCCCAAAJjL0AwbOybiAIigAACCCCAAAIIIIAAAggggAACCJQlQDCsLEnSQQABBBBAAAEEEEAAAQQQQAABBBAYewGCYWPfRBQQAQQQQAABBBBAAAEEEEAAAQQQQKAsAYJhZUmSDgIIIIAAAggggAACCCCAAAIIIIDA2AsMFAzbmmtIo5H2b162RlHlL9tyJTX/hly5ezSKEug8jqT9RkPmR1LpEVaroqyCfjU3PMyju1ekUWL6ZZS37DINpemC4+2KtL8cSurpiW7N6zFmBGOKyuuNtoQjR7/HdL/bp1e3+9ItmW/0YR+NjWoftW/+8SmrPwd9NXLqXuIy16gyjWp8zap/mfXqL62wj6nP3Fyfb05/7i8ntp4wAdp6whqM4iKAAAIIIIDAOAkMFAyLKzDsC8E4p66vKj0Z7Kf+fV7Udq0wKwYVGMfAU1VlqirffG034mPFGUMyjukg2GQH6DK2z1fhHlv1Y1FuWVRwKFfwpUfpC61KWBdKbWJ3zjpWE+ud/jyx1e5a8ER9u245/BWVl6WPtq68rMNvDnJAAAEEEEAAAQT6EiAY1heXv3E/F5/9XNT6+fC+DIFxvBioqkxV5ZurHUcdBHEuKDOO6UTZMrbPVeFeG/UzbvSzba88w3VVB8NUH600GJdNNJItstohcSw7/XkkRRxpJon6jjR3N7PKy9JHW1deVpeOdwgggAACCCCAQOUCQwiGhReH0W2Uzm1p6mLNur3SvuVGn9RtqVvZgm30rUFqudnHSUvbpZ0M2vs4txjpi8Wt+DbL8GLLLpc968NcXNrr7VuW/Athr+4NnVZwAZ1e7+AE1dTPbJ/WLXQ92/oWVXPrUK/9g9t+TNq+tVmu/tquiYt9EfckWpvc1e1i9vXqGF/EeiZm+5Q6JvOJzeL0/B3ttmlYt7v52/n1UOu9fRP+btnnt3Td9e2CbnlFpJuB0x/d2TaJNPxid0uzZ9lNv7TrF/dbp19Yt9EFZbH6heljoVO8vymznY7fPm5a1jHVpR9H1fasor7ZbXmwo24Xv09GiaoXbls27LbWZcq8TTK1DL2twyLY7eC2v1PE4I1bzit324nbJFNtvX4S3vZpyhbmktVuZn3SyhqL7XGkQB9UJUqtRwSiyt4tX3XoJm9tTfucCOvUDm5nb5jPAs/K9PO4/roQqe1tCqj7nPVZ4vQpVUT7cQKOm0kjKx+3L0Tlt3Z38jDHsraJP0u9MV7t79QtPratpKOXTh5WPdz2s29nTdr0/pwNCuScG/jjiSmMUxZT32Blj2PMqat7/Jk2j9MNxyq7bmWWpd/8zPZ2eaIxMWCzjwP/mIrbJK5f+Jlq+rz/GditrsafvwgggAACCCCAQJ0ESg6GhSfv8QmVezGmTsD9k7DovT5hNftGJ38meBJcwKSctOsT/+hJYUE6yYvvcL0+YTYn9NFFkdneL785wTbrzUWEee/V78u2zEfPLEtLyy1/UEdTFnNxaOrr9zLtE3mZ7bvt77kcbW2Fz0QK0rHL4ZUzMDH1CwthTsjDd9rELmeibbakHTh4aeuAhF0Hu5p2Purk3fQFdXG+tRW1sL1LcFEXpxeWLX7vbmqnby4C4jz0hUTk6ZfdXNzGdk56XQ3Ufpan1z+dNNzi6uBanJ8qc+ga1jOr7PbFeXAxFNUtLTB4JO0589ws30LlF5cjKLN9Ier1qWB9t7yCbeOLNL/KwXu/D3rpm2BNXP+UPukn3OvYVOlH5Q3bvVsfCgOeVntGQbZ4mWvt90nX0i1mzj4XldVvRz9tty652s06rt1j0A9AhfWK28DvM2HeXftgoo233OdNOm3Sq16+WVqd475r+k7cvluypR9T6ByLeftc1Ba6vsbPKb9INP66Da6DUsny2a6JdvDScMqt1gVlt8bPwNo65oL1cX91A4te4l3rkTVeWF9M6PzjvuC3WdiX7DaxxxuvRN6XM0GFvWfjuf0lc/y1xrLg2LWfzeZbeYVJ2OsAcbe6+MdgVn5m+7g/eHZO+/RqE3+syHbzqspbBBBAAAEEEECgdgLlBsP8CxzFpU7WzAWCx+ec5DsndWaWTfIiIT7J1Il5+zlpBpuok0eTjnuSbC6M4hNN/4TR314lGJ6MhuWwX3uVM8GqqO5+Wmn7qm2sixQ7Sa+ebjnMhtb+avuUtJI+3kVuShu6J/x+PcIgkW1oSpMMHPTuD3Y+wUVCZBelmPkitX56Lzv99AtAq24pDt1mSKnke+XrFtrKI9FHvC2dgKC1LtEXghJYAauUvuXVx7Gwko5eOttnldnOz35tUlP7636dWnaznf7r5N3F1knHLZ+XWupbp/5OWmnlt5LwypZ6HNrbOGmH6ai8cx8vwcW1Gb/SymbZOtuqvNztnToHRem9PtGn7brYryMeux3ctINNbJfgtalXlED0QuVtj/VOWRLpeGOmKpseO7rVOc3f3tbJz5TKqbNdV72BvV69Nn3e7J/yNzufLv3fSssud7DYLofezs7Hfh2uVm3VpS1y1sMd632bsC/Y5k6ZU8qr1tvbW9VNBsP62t8tm1MOlUmivu72djnU69T9owBpuLVdl9TtnX7i5pfY3pTR5JFS96iM9nEyQFmjdHiBAAIIIIAAAgjUVKDcYFhwIhnf2hbdtmJO3KJZFPE20Qlv4qROnRTaFzkpF1eqUZz9wm2ifBO3fLknmsHu3kWXe/KZ3N7dJ1kmdaHh5B8FdPy01Htv2+B9j4uSyDEoRfb+UXuYNJPlVSk5FzLeCbRa3dukS5pBEa1bXO26OvUIShD8z80nvAgMLLtsH+6ZbPOoT8VJJ9L387LTCi7CnX5lEnLbME6jh4HaNTC129q0h29r8lF/u6cZ59tt+5R9vXZNTSPqL6as5vjrVm+Tv51fRr9OdTXp6L9OWe20re2cbdzyWVs5L7sem06ZuuRnUnLyVQtTtre2CZztvm9eR+OCSdgfy8xyu24ZtiMMhqX2H8eit0tQu8Ap7Gt24CsMOpu+px3UtnocUHlHx3iiz+q+a21rAmNG1LRZMLZY7RDXKaXsamerXf3AeJC2049MYEWVJz7e4zKoV3nyKTsYFubpfEbpPum2gVXSyNirR7S893ihUlLHnp1+bK3HQHNc2H+ttrFK430e5djf6mdhveN62OUI8rD6WZinffzZpQhf+/sH7+06mNe6Lv72QZ9yPt/c/BLbq2ztMnbtc36bJD9rssqarC1LEEAAAQQQQACBegmUGwyzT9ISTskTf+cbav+kLriwsy+IkvsHWXj7+SfdbjHcE021zt/ePflMbu9ewLhlcuqTK4gUn5S75Ux559UzLEfO/YOLgXBbv4xBTna7Bdva7v5JdNIkNU2VsJ1uSpX8Ra59vDZY7lwwmHWuv1ratSx+eyQ81d4qPW2q1jvBWHMxHJvb5e2ab8LT9bPTMLUyf7ummVX2tItsrxyJfP00ne2zymy3g2VoKmL/9fOx15nXTt5d2lRtE/UJt3wmGfuvb+nU3ymTXRc7Bf3aK5s7HqRso9LuclGfSD2Rtt/nMmxHGAxzv4QwNbHLl+KYVr9gV9V+cbDEaRuTdHRs2nlkjzHpaUWJBuOFaR97W7+/BHtk9TmnH8V5hEG0eNyw1qSPV04+Xfq/lYhd7mBxSjns+qjXdmDKSqr3y6D9rPExOv5MPzWfG8nj0c/TKXM/x4g/jqsS99o/0efcsjnlUGl59qlBT0spsX+vsqSVPSO/RPqmvsbebmv7tamL9RmWSCujrFY1eYkAAggggAACCNRSoNxgmL4Ij761d8jck9DwJNN6rol/IjdgMCx5m4NdCL8MeYJh7sOHgxNKcyLqBB38i7/wvbnQSjupdtOyy5nyOuGjg1RRWdx9ju7OS1s/6N3JW6XjzFQIyxm3mTKyLpaCiwnbIGkYmtsXe+bZVn7abhn9d/HJuvvsk/QLb7W3X5aw7HFd3Bzi9M2+Vv8zFyqRZzItdUFn2znpJVy1gd9u3nZOGm5x9S07aa7JsgXpRGX3+6J/seoHOLu8jy6kXOdkmd383LJ4lfI9vNXBW/8C1jMzAai4nd3yJZN0y2f2j45Np0z+tl5qftmcMUBv62wTtlW+4EOyXVP7XNTOXtkSx4Nbl1ztZgXuVN6xsQ46RHkny+q2u5t3UFLbxXl+pL2tem33+biOKv0rc/NWEFStC/d1yhnvkphFFIwZVh1tE/t1ckzz80npc1Y/6jr+WmULXmb27fKDYb0/I90CdquHY2XGzi7jhUqxZzAs6LfWZ45bhMQ7P+/wc6DL/labBAl53om0VB+N+nhQcuv280RR0vuX/fnp7dJvfsH2zue1N55Y9fPTDvc1AcrkGN/TLThW049Dr0q8RQABBBBAAAEEJlag5GCYcghP1uzbMMyFYHhyFk/fn7cvtqyTulBTpROfyJmLHpNWJJ7YT5/0mdsT1N/o5DZ5AZN9kn5F2uZX6oI0e5QpONE29bsi83NXnFkhUf2j8oQXCbZVdIEeVVC/SKmnWhNeLJs8raCVUxbvQsFbl7iQtNe/0ZbgV8miC8ikYVBCex/nYqB7f/CraJ/Mu/Wyzd29IlPdNk6fcjfte [...]

2022-06-13 23:35 UTC, opbld33 commented
Docs Build status updates of commit _[42f6156](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42f6156bcb33fac59cbeb101beb051c4d094752b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-6b9c28e5)
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2c0daa4844a83424af0052bdd430814-6b9c28e5)
[api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0a5be47aa2d12d953d007473a1625a70-6b9c28e5)
[api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-templateteamdefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-b0fef88d9d04af7f8db99da22b61a2b0-6b9c28e5)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-6b9c28e5"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 35, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/intune-identityset.md'.`````

<a id="f2c0daa4844a83424af0052bdd430814-6b9c28e5"></a>
### [api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Teamwork'.`````

<a id="0a5be47aa2d12d953d007473a1625a70-6b9c28e5"></a>
### [api-reference/beta/api/teamwork-templatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templatedefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

<a id="b0fef88d9d04af7f8db99da22b61a2b0-6b9c28e5"></a>
### [api-reference/beta/api/teamwork-templateteamdefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-templateteamdefinition-get.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a teamTemplate object.' is duplicated in 'beta/api/teamwork-templatedefinition-get.md(3,14)', 'beta/api/teamwork-templateteamdefinition-get.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206132333116554-16827/BuildReport?accessString=3900cc1e699c6286db3e2463e5bfe331aededc9bb08ff7aabbd82a1d3fe51328).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 20:46 UTC, isvargasmsft commented on api-reference/beta/api/teamwork-list-teamtemplates.md
> +This method supports the `$expand`, `$filter`, and `$skipToken` [OData query parameter](/graph/query-parameters) to customize the response.
Please clarify which properties can be filtered.

2022-06-15 22:12 UTC, opbld33 commented
Docs Build status updates of commit _[12d6c8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12d6c8d8e69291576caa347e3f56d342cfeda1a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206152208472095-16827/BuildReport?accessString=0e76c661e87536dfcbd0bf90e3f177a7f4bde147c45ef97cbf10c34af8bceed8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 23:03 UTC, opbld32 commented
Docs Build status updates of commit _[f02a713](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f02a71354503427a0ece15a61458ee8ef66ee759)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206152259151636-16827/BuildReport?accessString=e8c4fb59a1c390b3f9a353730a406544fb5efe29a8040bac19dea77916e1a7af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 23:12 UTC, opbld30 commented
Docs Build status updates of commit _[3446952](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34469522186fe93f014bf618d35891571f35c612)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206152309179068-16827/BuildReport?accessString=4572d5336444a660fb93de29b1fdeac2109a51417cde1a15136863f9cffafd37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 23:14 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +              href: resources/teamtemplatedefinition.md
Let's add a node for each entity and under each entity add the supported CRUD operations. Example:

Team templates
 - List 
 - List definitions
 Team template definitions
- List
- Get 
- Get team definition

2022-06-15 23:16 UTC, isvargasmsft requested changes
Please address some final details in the comments and in the TOC.

2022-06-15 23:34 UTC, paoladelhierro commented on api-reference/beta/api/teamwork-teamtemplatedefinition-get.md
> +GET /teamwork/teamTemplates/{teamTemplateId}/definitions/{compositeTeamTemplateId}
Can you please change compositeTeamTemplateId to teamTemplateDefinitionId, I believe compositeTeamTemplateId is more of an internal name for it and it is not defined in the docs

2022-06-15 23:36 UTC, paoladelhierro commented on api-reference/beta/resources/teamtemplatedefinition.md
> +|id|String|Encoded64 of `templateId` + `tenant` + `locale` for the team template. Inherited from [entity](../resources/entity.md).|
The id is the Encodec64 of tempalteId + **audience** + locale

2022-06-16 02:31 UTC, opbld30 commented
Docs Build status updates of commit _[2ee1d79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ee1d79d5d952b4e05b89970c039717bd30e36dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206160228491844-16827/BuildReport?accessString=765bdbf92be93b5229d7a49f13cfc3e4fc985a50f325aabd175f756438b38195).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 02:39 UTC, opbld33 commented
Docs Build status updates of commit _[864fd82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/864fd8277c7952f9a17554ab144ac4fb505f1bd1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b9a0378c)
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-b9a0378c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15392, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-let-teamdefinition.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206160235528057-16827/BuildReport?accessString=4c4d2cff75c83b9fc49d64cb1125f7bf65c9049cb1fec273b6b5f6d39ef289ec).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 02:42 UTC, opbld33 commented
Docs Build status updates of commit _[f87789b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f87789b3bb67da0dcb9d82ff3d9d0ca6c9e53450)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206160240142626-16827/BuildReport?accessString=43079fb3e2fd80521640dbfa9f76d8f20622169622ca64dc01a3940bf6849709).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 02:44 UTC, opbld30 commented
Docs Build status updates of commit _[4bbb00a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bbb00a72c4d9ed166f18d8c0c15b5a6e8ad5ebe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206160241535763-16827/BuildReport?accessString=390e6072727de0b63c9ce0c1ff2790aa7a4c188662e6eee2978f1d6d6ddc5c01).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 03:00 UTC, isvargasmsft approved these changes

2022-06-16 03:03 UTC, isvargasmsft commented
@Lauragra, would you be so kind to take a look at the TOC structure, the List definitions topic (the HTTP request is very similar to the List teamTemplates) and to the file name of the Get teamDefinitions topic (the navigation property is not a collection but a single element, so not sure if it's treated like a List or a regular Get operation in terms of file naming and topic title). 

Thank you!

2022-06-17 04:52 UTC, Lauragra commented on api-reference/beta/api/teamwork-teamtemplate-list-definitions.md
> +title: "List definitions"
Why are the file names in this PR preceded with "teamwork"? Generally we use the prefix for APIs that are in a subnamespace, but these APIs are in the microsoft.graph namespace.

2022-06-17 04:56 UTC, opbld32 commented
Docs Build status updates of commit _[7037658](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7037658a4a9d6497683541f3e08b14eaae32949c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206170453464322-16827/BuildReport?accessString=c96576e942277bccdfd30ec13113fbfcd7b5338c052346d42630f20b2d7c5fe3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 04:56 UTC, Lauragra commented on api-reference/beta/resources/teamtemplatedefinition.md
> +|teamDefinition|[team](../resources/team.md)|Collection of [channel](../resources/channel.md) objects. A channel represents a topic, and therefore a logical isolation of discussion, within a team.|
Is this the right description for the teamDefinition navigation property?

2022-06-17 04:58 UTC, Lauragra commented on api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md
> +Read the properties of the [team](../resources/team.md) of a [teamTemplateDefinition](../resources/teamstemplate.md) object.
Does this description make sense? It seems unclear. Would this be accurate:
Get the properties of the [team](../resources/team.md) associated with a [teamDefinition](../resources/teamstemplate.md) object.

2022-06-17 05:00 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +|teamTemplates|[teamtemplate](../resources/teamtemplate.md) collection| The teams templates|
Is this description sufficient? Would a better description be "The templates associated with a team."?

2022-06-17 17:34 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Team templates
Please make this singular.

2022-06-17 18:08 UTC, Lauragra commented
> @Lauragra, would you be so kind to take a look at the TOC structure, the List definitions topic (the HTTP request is very similar to the List teamTemplates) and to the file name of the Get teamDefinitions topic (the navigation property is not a collection but a single element, so not sure if it's treated like a List or a regular Get operation in terms of file naming and topic title).
> 
> Thank you!

@isvargasmsft , I made some comments on this PR; let me know if there are other open questions? Thanks.

2022-06-27 19:23 UTC, isvargasmsft commented
@charlieforce, what is the status of this PR? Please let us know if you have questions regarding the comments above.

2022-07-05 16:01 UTC, opbld31 commented
Docs Build status updates of commit _[2cd36ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cd36ec9a871a45c9518a3a66c0c04e510867659)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9b0326e9)

<a id="9b0326e9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051600462563-16827/BuildReport?accessString=b850e971cb16ca55a0e00cb501a401e24095bfb7217b92169b88a32d29e04b30).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 14:25 UTC, opbld32 commented
Docs Build status updates of commit _[5fd8a15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fd8a159d4b3bddb0eec18b71bd98b5bc33dbbd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207061422406044-16827/BuildReport?accessString=51b172fb6d7d897d6c936f9bc151a27b26f887e8e89e095b25756d8516997795).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 22:13 UTC, opbld31 commented
Docs Build status updates of commit _[0b3643f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b3643f66f8e28f9affca7f5c86f2e7129d0864e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-492055e68b2345246662d0a56e1030d7-6b85c060)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-6b85c060)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6b85c060)
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="492055e68b2345246662d0a56e1030d7-6b85c060"></a>
### [api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````

<a id="f2ad1bce904975eec0f2459988ab4537-6b85c060"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````

<a id="0817dce4456c16725d5333633847d38f-6b85c060"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15476, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15482, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062211364360-16827/BuildReport?accessString=ef6a6492954a87f6ec1d134b621670dbaa0a789a8490c9591fdeb22f07513d10).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 22:18 UTC, opbld30 commented
Docs Build status updates of commit _[7619ef1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7619ef1b5e4e0d2b544f4fd8fc70c85c836199e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-492055e68b2345246662d0a56e1030d7-b8e60307)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-b8e60307)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b8e60307)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="492055e68b2345246662d0a56e1030d7-b8e60307"></a>
### [api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````

<a id="f2ad1bce904975eec0f2459988ab4537-b8e60307"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplatedefinition-get.md'.`````
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````

<a id="0817dce4456c16725d5333633847d38f-b8e60307"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15476, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15482, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15484, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062216034981-16827/BuildReport?accessString=0ef5b10c9d4e90cf60f217c5c8ef8dc00be83f21477baf7fcc5e875e8c96e120).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question  [...]

2022-07-06 22:21 UTC, opbld34 commented
Docs Build status updates of commit _[289ed79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/289ed79556efb145e7b132100d4bac584edf3fd8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a8630df4)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a8630df4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15476, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15482, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15484, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-get.md'.`````
 - **Line 15486, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-list-teamdefinition.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062218179022-16827/BuildReport?accessString=04f7a077c60816039780483eb8f9c611bba8318e55ca78ca46bacf5dc0b74db1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 22:23 UTC, opbld32 commented
Docs Build status updates of commit _[1d4cc0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d4cc0d38ff71a65c63a9fce22b371cc3b33998d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-f0daafcb)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f0daafcb)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f2ad1bce904975eec0f2459988ab4537-f0daafcb"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplatedefinition-get.md'.`````
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 25, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplatedefinition-list-teamdefinition.md'.`````

<a id="0817dce4456c16725d5333633847d38f-f0daafcb"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15476, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15482, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15484, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-get.md'.`````
 - **Line 15486, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-list-teamdefinition.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062217296667-16827/BuildReport?accessString=431dbe2ec546c259ee65b14cc8ed19f0973e9cc694acc9a74ec2498cfa9526a5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the d [...]

2022-07-06 22:26 UTC, opbld30 commented
Docs Build status updates of commit _[30d1d5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30d1d5d8e41df36052ec6fc2d131b70caff9826e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-492055e68b2345246662d0a56e1030d7-5254b9de)
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-f2ad1bce904975eec0f2459988ab4537-5254b9de)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5254b9de)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="492055e68b2345246662d0a56e1030d7-5254b9de"></a>
### [api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md)
 - **Line 22, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````

<a id="f2ad1bce904975eec0f2459988ab4537-5254b9de"></a>
### [api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplatedefinition-get.md'.`````
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 25, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamwork-teamtemplatedefinition-list-teamdefinition.md'.`````

<a id="0817dce4456c16725d5333633847d38f-5254b9de"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15476, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15482, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplate-list-definitions.md'.`````
 - **Line 15484, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-get.md'.`````
 - **Line 15486, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamwork-teamtemplatedefinition-list-teamdefinition.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062216420002-16827/BuildReport?accessString=84c3deffd7491d65e6b494bb2449f3447dc1cc24f8970fc6781989ed312fc6f6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735 [...]

2022-07-06 22:28 UTC, opbld31 commented
Docs Build status updates of commit _[6b84703](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b847031905a3c9708965e7f91ccf09a56c4c852)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062226233365-16827/BuildReport?accessString=af0fb4907728aee285e6d39fb79dd22afbe82dbf6940ff7b23fe32e24cbe24c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 03:38 UTC, Lauragra commented on api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md
> +title: "Get teamDefinition"
The file name has list but the title here uses get. If this is a get operation, please update the file name to use get.

2022-07-07 03:42 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +|[List teamTemplates](../api/teamwork-list-teamtemplates.md)|[teamTemplate](../resources/teamtemplate.md) collection|Get the teamTemplate resources from the teamTemplates navigation property.|
Please update the description column to match the description of the method: Get the list of [teamsTemplate](../resources/teamstemplate.md) objects that are available for the tenant.

2022-07-07 03:46 UTC, opbld32 commented
Docs Build status updates of commit _[e2667cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2667cd2b30d541d07d8116b7d9d214afee2e862)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-list-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-list-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207070344366104-16827/BuildReport?accessString=760972e9a64986722f47257d03cd10bf516a6540adea0d94a44ec9a70f6f148e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 03:51 UTC, Lauragra commented on api-reference/beta/api/teamwork-list-teamtemplates.md
> +title: "List teamTemplates"
Global: In the title we are using "teamTemplates" but in the summary description, we refer to "teamsTemplate" and link to a resource topic named "teamsTemplate". Are there really two different resources named "teamTemplate" and "teamsTemplate", or is something misnamed? In any event, please verify that the references in titles, descriptions, and file names are all consistent.

2022-07-07 03:52 UTC, Lauragra commented on api-reference/beta/resources/teamwork.md
> +|teamTemplates|[teamtemplate](../resources/teamtemplate.md) collection| The templates associated with a team.|
Please verify the nav property name and type name here per my earlier comment on the list operation topic.

2022-07-07 16:58 UTC, opbld31 commented
Docs Build status updates of commit _[3357179](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33571793d1875bb7b49cbddd85a0509bbed51ed4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4c5317f9)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-4c5317f9"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15572, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamtemplatedefinition-list-teamdefinition.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207071654185755-16827/BuildReport?accessString=8af3d9b56a8c9f4baba5dd3945c9d5bffd4e932b859251eec52bb3a21250c1a3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 17:00 UTC, opbld32 commented
Docs Build status updates of commit _[a2cfeca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2cfeca83b094cd15e3fba1f98d41e9ce6b2b362)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f4db383c)
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-f4db383c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml)
 - **Line 15572, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/teamtemplatedefinition-list-teamdefinition.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207071656213434-16827/BuildReport?accessString=898bde7ee5b2ccfff664b33775050d569db597cc7fe660fb80a6f02ac13b7cb9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 03:25 UTC, opbld33 commented
Docs Build status updates of commit _[bb25ccb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb25ccbcdc1da52af2c8ff261c8e62e4608ad6b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamtemplatedefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplatedefinition-get-teamdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get-teamdefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamtemplate-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamtemplate-list-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplate-list-definitions?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/api/teamwork-list-teamtemplates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamstemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamstemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplate?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamtemplatedefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamtemplatedefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamtemplatedefinition?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamtemplatedefinition-get?view=graph-rest-beta&branch=pr-en-us-16827) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Chalie-Teamstemplates-Graph-API-doc/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207080323059171-16827/BuildReport?accessString=6593d85d7e1e2e94184bf3097671d4d35e70a930537450cb66e1b681ec6a076b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 03:48 UTC, merged