Users/komalpandey/adding missing attributes
microsoftgraph/microsoft-graph-docs pull request #16824
Opened 2022-05-09 19:12 UTC by komalPandey152

2022-05-09 19:14 UTC, opbld34 commented
Docs Build status updates of commit _[cd5b512](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd5b51205cea9523f78eafa2e68c328fd91fa7eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202205091912240180-16824%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T19%3A14%3A36Z&sr=b&sp=r&sig=lSj%2FIkbYVDmdn3fkWNytkpw3u%2FgTT5qjDT99WFSWpLI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d7 [...]

2022-05-18 16:32 UTC, isvargasmsft commented on api-reference/beta/resources/bookingappointment.md
>  | Property	   | Type	|Description|
Line 28: For the Update method, in the return type column we state that the method returns a bookingAppointment object, Yet, the method topic says otherwise. Would you be so kind to confirm which topic is right and update accordingly?

2022-05-18 16:39 UTC, opbld31 commented
Docs Build status updates of commit _[a9a2f0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9a2f0a1675c2e87c7ee0d0b4a2a9ea8128709bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181637213133-16824/BuildReport?accessString=196780266fb64f612889d45f08a9d130c5261280421d390558791c098af63066).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching [...]

2022-05-18 16:41 UTC, isvargasmsft commented on api-reference/beta/resources/bookingservice.md
>  |description|String|A text description for the service.|
Line 27: For the Update method of this resource we are also stating that it returns an object when the method topic says otherwise. Please check and update accordingly.

2022-05-18 16:44 UTC, isvargasmsft commented on api-reference/beta/resources/bookingstaffmember.md
>  |displayName|String|The name of the staff member, as displayed to customers. Required.|
Line 35: Same problem with the return type of the Update operation. Please check.

2022-05-18 16:47 UTC, isvargasmsft commented on api-reference/beta/resources/bookingstaffmember.md
>  ```
Missing in this PR:
Changelog entries for the new properties and enum members. 
Updates to add the new enum members to the documentation.

2022-05-18 16:49 UTC, isvargasmsft requested changes
Hello @komalPandey152, 

Thank you very much for the good work in this PR. 

Please take a look at 2 main issues:
1. Some update operations have a wrong return type in either the methods section or in the method topic. Please check and update accordingly. 
2. There are some missing elements in this PR. Please include changelog records and add the 2 new members to the bookingStaffRole enumeration. 

Feel free to ping me on the side if you have questions. 

Kind regards, 

Isaac

2022-05-18 16:53 UTC, opbld33 commented
Docs Build status updates of commit _[f88f1e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f88f1e77bd00379f62bedb140229b310c6e2cd7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181642563455-16824/BuildReport?accessString=7f483c66c3692255e0fb19b3a7947c0fc8e56a55aa646a59443111886e84b59c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching [...]

2022-05-19 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[9386a16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9386a16d4fdef9a7e94fcf9e6d4509a2a9eb65a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/komalpandey/addingMissingAttributes/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190718340288-16824/BuildReport?accessString=67093e0115d58365840545843163698af8a82d0af581452788301d325e8ee7a5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written [...]

2022-05-19 07:48 UTC, opbld31 commented
Docs Build status updates of commit _[6f77019](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f77019bd760d38ebfa6e7f4590e35750b3b7bae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/komalpandey/addingMissingAttributes/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190746523657-16824/BuildReport?accessString=f3e0c289e9352d73ef4c017ad8b152619fb0c6687d1d99f4452a6cec7e1d384c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written [...]

2022-05-30 11:11 UTC, opbld34 commented
Docs Build status updates of commit _[9903f72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9903f7260742c0be1bf1dce759eab6a702e0551a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingstaffmember?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[changelog/Microsoft.Bookings.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/komalpandey/addingMissingAttributes/changelog/Microsoft.Bookings.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205301107415011-16824/BuildReport?accessString=df946e2878d43b3840825341ef6a8325d65ae3a6ba939f16c89c8854f0e05441).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written [...]

2022-06-08 06:33 UTC, opbld34 commented
Docs Build status updates of commit _[9ee4a19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ee4a192c6c00f88a3d231ca40e377b689a8c0ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomer?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2022-06-13 05:48 UTC, komalPandey152 commented
Hello @isvargasmsft, I have addressed the comments, Please review this PR

2022-06-15 14:02 UTC, isvargasmsft commented on api-reference/beta/resources/bookingstaffmember.md
> +|role|bookingStaffRole| The role of the staff member in the business. Possible values are: `guest`, `administrator`, `viewer`, `externalGuest`, `scheduler`, `member` and `unknownFutureValue`. Require
Line 47: this is an evolvable enumeration that contains values after unknownFutureValue. Hence, we want to let customers know they should use the proper header to access those values.

Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations?anchor=step-3%3A-add-clarification-if-one-or-more-members-follow-unknownfuturevalue

```suggestion
|role|bookingStaffRole| The role of the staff member in the business. Possible values are: `guest`, `administrator`, `viewer`, `externalGuest`, `unknownFutureValue`, `scheduler` and `member`. Note that you must use the `Prefer: include-unknown-enum-members` request header to get the following value(s) in this `[evolvable enum](/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations)`: `scheduler`, `member`. Required. |
```

2022-06-15 14:12 UTC, opbld31 commented
Docs Build status updates of commit _[ef53a5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef53a5e98a47679f1abecbbdc660463ae93910cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomer?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2022-06-15 14:21 UTC, isvargasmsft requested changes
Hello @komalPandey152, 

Thank you very much for addressing the feedback. 

Just a couple of final comments:
1. Please clarify the extra changelist you are adding to the changelog. I can't see those 2 changes in the CSDL. If this was a mistake, please delete them. If the tool autogenerated them, please let me know to open a bug with the changelog generation team. 
2. I also left a suggestion to fix the description of the evolvable enumeration bookingStaffRole. According to the CSDL the new members go after unknownFutureValue, hence the clarification to add the proper headers is due. 

In addition, please note I took the liberty of adding the 2 new members to the enum definition. Please take a look for future reference. 

Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac

2022-06-16 06:13 UTC, komalPandey152 commented on changelog/Microsoft.Bookings.json
> +      }
These are the CSDL changes for other changeLog items 
 https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6107247
 https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6110848

2022-06-16 06:16 UTC, opbld32 commented
Docs Build status updates of commit _[5c77a38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c77a382c9316b127629e89e285604957e46dfac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomer?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2022-06-16 06:22 UTC, komalPandey152 commented on api-reference/beta/resources/enums.md
> +|teamMember|
Changing this teamMember to member

2022-06-16 06:36 UTC, opbld30 commented
Docs Build status updates of commit _[1649689](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16496895ced2d334dcdcf9ab86945719c0359499)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomer?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2022-06-16 11:32 UTC, isvargasmsft approved these changes

2022-06-18 01:14 UTC, opbld32 commented
Docs Build status updates of commit _[304d51b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/304d51baa1435d38491024bcfda026ed030d8358)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingappointment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingappointment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-calendarview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-calendarview?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-list-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-list-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-appointments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-appointments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-appointments?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-bookingbusinesses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-bookingbusinesses?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-post-staffmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-post-staffmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-post-staffmembers?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingbusiness-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingbusiness-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingservice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingservice-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingservice-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-get?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/api/bookingstaffmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/bookingstaffmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingstaffmember-update?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingappointment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingappointment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingappointment?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingbusiness.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingbusiness.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingbusiness?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomer?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomerinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomerinformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomerinformation?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingcustomquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingcustomquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingcustomquestion?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookingservice?view=graph-rest-beta&branch=pr-en-us-16824) (graph-rest-beta) |
[api-reference/beta/resources/bookingstaffmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/bookingstaffmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2022-06-18 01:17 UTC, merged