add domain promote
microsoftgraph/microsoft-graph-docs pull request #16837
Opened 2022-05-10 14:02 UTC by franqq

2022-05-10 14:06 UTC, opbld32 commented
Docs Build status updates of commit _[516c8e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/516c8e01bfd3b7f931386e5d0e09783c707ce68d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :x:Error | | [Details](#user-content-80ad21c5357eb13bd166aa7340bfa687-f9904289)

<a id="80ad21c5357eb13bd166aa7340bfa687-f9904289"></a>
### [api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md)
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/domain-promote-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/domain-promote-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/domain-promote-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/domain-promote-java-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/domain-promote-go-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/domain-promote-powershell-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205101402163544-16837/BuildReport?accessString=efa0cda803e59b19b591452515d29b48ade4ad774da54514bc8887d70b6b5119).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 13:16 UTC, opbld31 commented
Docs Build status updates of commit _[6f93193](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f93193379db11eec4267904012d5a9e3be56710)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205111314056062-16837/BuildReport?accessString=561c922897e90c3608648e3b1a5896ec6e8fe09ef8c28bb7feeac4ec1c9a1628).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 14:01 UTC, opbld31 commented
Docs Build status updates of commit _[634ee95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/634ee95b4abb980cae7aec206305dd91f8e15d7d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f132344d)
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-f132344d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 11277, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 11277, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 11278, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11278, Column 13**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205111359075873-16837/BuildReport?accessString=5aea6aedbef58ad45acaeac90d435b9589dd1432c57da95a257e454e18eb4d1e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 05:50 UTC, opbld30 commented
Docs Build status updates of commit _[f70d232](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f70d2326a19bbcec630a9dfba70ebae84f79f37a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205120548005633-16837/BuildReport?accessString=c52c9a25f633e0a356c12dc524a7a7dffe090b0a8fd699b02933f520b5dd6067).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-12 14:52 UTC, opbld33 commented
Docs Build status updates of commit _[73986b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73986b7099a783092ae76d18f425108d63310cf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121440558081-16837/BuildReport?accessString=20cfe24fdbc19bbcfc108d4a134b1ec63c527ebf63413967537c4de461e6b93c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-16 08:43 UTC, Mwongela approved these changes

2022-05-26 12:11 UTC, FaithOmbongi requested changes
Thank you @franqq for your work on this PR. A few fixes and the following feedback items:
+ GLOBAL: Please remove all snippets from this PR. The snippets are autogenerated and will be auto-instered after this PR is merged and the docs are published.
+ Please add the changelog. You should find the changelog stub was autogenerated in your schema PR.

2022-05-26 12:11 UTC, FaithOmbongi commented on api-reference/beta/api/domain-promote.md
> +Note: The response object shown here might be shortened for readability.
```suggestion
>Note: The response object shown here might be shortened for readability.
```

2022-05-26 12:11 UTC, FaithOmbongi commented on api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md
> +---
GLOBAL: Delete all snippets. They are autogenerated and autoinserted into the docs once the docs are live.

2022-05-30 20:52 UTC, opbld30 commented
Docs Build status updates of commit _[aa5a357](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa5a3574818a97c760fc1ff9e823a71bde007dc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302048303167-16837/BuildReport?accessString=159dbbd18238825292375f342d642784c47a6902d2a1536f229adc81f17172ae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:03 UTC, opbld30 commented
Docs Build status updates of commit _[be08309](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be083091bebc88a23f9102421179928b065387bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302049088889-16837/BuildReport?accessString=8a1b22b6249ebcf5c13eb4df12c961bdc898b00667ebf85bcfb2626ac2bcb45b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:16 UTC, opbld32 commented
Docs Build status updates of commit _[0f789c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f789c4ded06e7788489852785765fbf59386299)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302056043119-16837/BuildReport?accessString=db132227a497ec2094fc4498a68a46bdc05b582690a3f810e6ec6c419afa03f6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:28 UTC, opbld30 commented
Docs Build status updates of commit _[ac09574](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac095744fbced1dbfa974d415fb109821d769721)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302055470655-16837/BuildReport?accessString=b7dd70e61a009da30cf41eefe7333527a6575f0c61ba1d1f153aa83da5b1356d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:34 UTC, opbld30 commented
Docs Build status updates of commit _[4fd2c5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fd2c5db4feda4aa461d6a80bcaf2e0ecde62c62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302056420300-16837/BuildReport?accessString=e95326c479e77687969bee173ce4a968053fd2e8856eb0d9ee827f5edd284c1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:42 UTC, opbld33 commented
Docs Build status updates of commit _[98bc55b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98bc55ba9f33ce65999175fb00d97c8a698a9e90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302055070740-16837/BuildReport?accessString=c2cdce116a6db4dcb04a57872028765b3fde0461f85b3d726a839035f32272a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:49 UTC, opbld34 commented
Docs Build status updates of commit _[dc22d40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc22d40df8cac5e276252c46fad46c008a671d2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302055246199-16837/BuildReport?accessString=14e1328a2ae339da0dab253b8d4ae69b8c25362b90c688abf991c246878d2da7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:52 UTC, opbld31 commented
Docs Build status updates of commit _[30b9557](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30b95574e87dfb02cb074aba8e04de9e47689f16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302101049806-16837/BuildReport?accessString=0329228e65a1069153f220b0a4a8197de5e9834d014435ab2afe49eb8ba2215a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:56 UTC, opbld32 commented
Docs Build status updates of commit _[ecac3fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecac3fbd3b05f7c4da67ce7061a2b12054278c1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302050339355-16837/BuildReport?accessString=0f34a6c83532f22e83ecc5c130e13bdc463d2cd9883432b56b8ec000a6fe8d9e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 21:59 UTC, opbld31 commented
Docs Build status updates of commit _[e48a743](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e48a74346d34366ee0e7916516e2674e7624e269)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302054467137-16837/BuildReport?accessString=babc35f5a3181bc619988c6be08a1e342db870bcb6e4b0f5d326cae4676dd195).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 22:04 UTC, opbld32 commented
Docs Build status updates of commit _[915b822](https://github.com/microsoftgraph/microsoft-graph-docs/commits/915b822c9d0db2c7bb411008eeb3dea41c38e3a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302105066796-16837/BuildReport?accessString=ceb3944d59cad77628a262ce1b18fa3f910bf5dfe5a01f4442e273118ce4f4b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 22:09 UTC, opbld33 commented
Docs Build status updates of commit _[1bdecdd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bdecdd9f9f5f8cd8e126a96a89ce92329af1181)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/csharp/domain-promote-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/go/domain-promote-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/java/domain-promote-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/javascript/domain-promote-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/objc/domain-promote-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/api-reference/beta/includes/snippets/powershell/domain-promote-powershell-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205302053517972-16837/BuildReport?accessString=6b9f2451969084f192dd42682e51a7e0e279a044094908d1e6de99c233e7a0d3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 10:44 UTC, FaithOmbongi requested changes
Hi @franqq, you're only missing the changelog. Please add the changelog entry and the PR will be good to go.

2022-06-03 12:45 UTC, opbld34 commented
Docs Build status updates of commit _[dbbcc5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbbcc5db765a0a58ed44e1109d44c0ea292ea242)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-eb35fe5074ded7ba58df4876b9940d89-e4a2fa9b)
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-9b86bc10b7f0bbfef1108130886dceec-e4a2fa9b)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-e4a2fa9b)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-e4a2fa9b)
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-e4a2fa9b)
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-eddab72315328aed485ddded01053ea9-e4a2fa9b)
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/driveitem-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-9b3f3fc062b654be6970943846061d30-e4a2fa9b)
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-c4be6a9188f3d1b14c0203392de83417-e4a2fa9b)
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-fc2eb492c12ff8f0217d4d103e2217b8-e4a2fa9b)
[api-reference/beta/api/identityproviderbase-availableprovidertypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/identityproviderbase-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-e086a3d9313b758ba1b1270edc4c5fa5-e4a2fa9b)
[api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-androidfotaservice-devicemanagementreports-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-071f216eb06cd43b5347cfb78c1bce87-e4a2fa9b)
[api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-androidfotaservice-devicemanagementreports-update?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-1112a0331cde9863d3ec9199b1d164f3-e4a2fa9b)
[api-reference/beta/api/intune-mam-windowsmanagedappprotection-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-mam-windowsmanagedappprotection-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-mam-windowsmanagedappprotection-assign?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-8ff559faa89849f1fe2c2699ff985e1c-e4a2fa9b)
[api-reference/beta/api/intune-mam-windowsmanagedappprotection-targetapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-mam-windowsmanagedappprotection-targetapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-mam-windowsmanagedappprotection-targetapps?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-4d45884e43c1f9cf7ee5d17d65f4e901-e4a2fa9b)
[api-reference/beta/api/multivaluelegacyextendedproperty-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/multivaluelegacyextendedproperty-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/multivaluelegacyextendedproperty-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-e1d682ce28f2033938097dd047e171d1-e4a2fa9b)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-e4a2fa9b)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-e4a2fa9b)
[api-reference/beta/api/participant-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/participant-invite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-invite?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-3ed043899dad7a172a6addfe46a50bef-e4a2fa9b)
[api- [...]

2022-06-03 16:27 UTC, opbld34 commented
Docs Build status updates of commit _[03a6de1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03a6de145d23209fb7d9ab2b115cdbc365070607)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-eb35fe5074ded7ba58df4876b9940d89-0b0197ef)
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-9b86bc10b7f0bbfef1108130886dceec-0b0197ef)
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-e30bfc4483d25f5d699faf9a3fedfd93-0b0197ef)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-8525cd0db4658bc30812e0f65138efa3-0b0197ef)
[api-reference/beta/api/delegatedadminrelationship-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/delegatedadminrelationship-list-operations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/delegatedadminrelationship-list-operations?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-be2d04933afe218fc740a8d37684730d-0b0197ef)
[api-reference/beta/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-eddab72315328aed485ddded01053ea9-0b0197ef)
[api-reference/beta/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/driveitem-delta.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-9b3f3fc062b654be6970943846061d30-0b0197ef)
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationassignment-post-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-c4be6a9188f3d1b14c0203392de83417-0b0197ef)
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/educationsubmission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-fc2eb492c12ff8f0217d4d103e2217b8-0b0197ef)
[api-reference/beta/api/identityproviderbase-availableprovidertypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/identityproviderbase-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-e086a3d9313b758ba1b1270edc4c5fa5-0b0197ef)
[api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-androidfotaservice-devicemanagementreports-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-071f216eb06cd43b5347cfb78c1bce87-0b0197ef)
[api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-androidfotaservice-devicemanagementreports-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-androidfotaservice-devicemanagementreports-update?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-1112a0331cde9863d3ec9199b1d164f3-0b0197ef)
[api-reference/beta/api/intune-mam-windowsmanagedappprotection-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-mam-windowsmanagedappprotection-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-mam-windowsmanagedappprotection-assign?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-8ff559faa89849f1fe2c2699ff985e1c-0b0197ef)
[api-reference/beta/api/intune-mam-windowsmanagedappprotection-targetapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-mam-windowsmanagedappprotection-targetapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-mam-windowsmanagedappprotection-targetapps?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-4d45884e43c1f9cf7ee5d17d65f4e901-0b0197ef)
[api-reference/beta/api/multivaluelegacyextendedproperty-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/multivaluelegacyextendedproperty-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/multivaluelegacyextendedproperty-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-e1d682ce28f2033938097dd047e171d1-0b0197ef)
[api-reference/beta/api/organizationalbranding-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organizationalbranding-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-get?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-7a3ff4d0a9b5e523e426549db1076fde-0b0197ef)
[api-reference/beta/api/organizationalbranding-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/organizationalbranding-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-07280cc683676b06b71713506b889387-0b0197ef)
[api-reference/beta/api/participant-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/participant-invite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/participant-invite?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-3ed043899dad7a172a6addfe46a50bef-0b0197ef)
[api- [...]

2022-06-03 17:18 UTC, opbld34 commented
Docs Build status updates of commit _[5e0ebc3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e0ebc39b231fb4b66772da536521d20be0be8ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031715306209-16837/BuildReport?accessString=5fffbb84cc2203c088d9f3e9528dff13da53882fe3f916cc506b4d4386577bcd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:29 UTC, FaithOmbongi approved these changes
Thank you @franqq for your work on this PR. Approved with suggestions for minor fixes.

2022-06-03 17:29 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "promote"
GS bug.
```suggestion
          "Description": "Added the [promote](https://docs.microsoft.com/en-us/graph/api/promote?view=graph-rest-beta) method to the [domain](https://docs.microsoft.com/en-us/graph/api/domain?view=graph-rest-beta) resource.",
          "Target": "domain"
```

2022-06-03 17:29 UTC, FaithOmbongi commented on api-reference/beta/api/domain-promote.md
> +##### Request
nit
```suggestion
### Request
```

2022-06-03 17:29 UTC, FaithOmbongi commented on api-reference/beta/api/domain-promote.md
> +<!-- uuid: 8fcb5dbc-d5aa-4681-8e31-b001d5168d79
Fixed incorrect block formatting
```suggestion
```http
POST https://graph.microsoft.com/beta/domains/contoso.com/promote
```

### Response
<!-- {
  "blockType": "response",
  "truncated": true,
  "value": true
} -->
```http
HTTP/1.1 200 OK
Content-type: text/plain

true
```


<!-- uuid: 8fcb5dbc-d5aa-4681-8e31-b001d5168d79
```

2022-06-03 17:38 UTC, opbld31 commented
Docs Build status updates of commit _[2d61b47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d61b47f7498cb85c8ba30cb04dc962cc34880e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031735038526-16837/BuildReport?accessString=40c2d33c61377298c3b7e023969bb81fab47f0afa68efb4ef0cfd1b9fe3524de).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:40 UTC, opbld30 commented
Docs Build status updates of commit _[3fc909b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fc909bd05b711c13d5bdca8be02a21c23afc72e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031736565663-16837/BuildReport?accessString=3f44f2cc1f3b1de67c8854709b892583a5dfa04d5b4b60695482da5477ba584e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:44 UTC, opbld31 commented
Docs Build status updates of commit _[a2b128d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2b128d93a537b25bb346a609a371f3a64140d02)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) | [Details](#user-content-80ad21c5357eb13bd166aa7340bfa687-2a7b64c0)
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="80ad21c5357eb13bd166aa7340bfa687-2a7b64c0"></a>
### [api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md)
 - **Line 58, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031737354183-16837/BuildReport?accessString=4fd56eaf9bea5e417c5abe26a5dba43089c03317bb97e2ca4f337c90d052d915).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:46 UTC, opbld31 commented
Docs Build status updates of commit _[0ca37bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ca37bf92feef508dafe172c1814d61f49e9eef7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031743568697-16837/BuildReport?accessString=9c34df96a3af57249ab8e25049728c46f31467cbbbef4118cd6bcdf2c68c76ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:49 UTC, opbld30 commented
Docs Build status updates of commit _[f892984](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f892984e5c354e3fca1578d571b99ed6e52a1232)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031746495656-16837/BuildReport?accessString=d0ea9fcfbca259ada04cd08090f4251829249c03b5ef3f2633347c74b30fc609).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 17:56 UTC, opbld32 commented
Docs Build status updates of commit _[b1cad39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1cad39c68ada02415980855ae21055509de841d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031754050077-16837/BuildReport?accessString=61e7a1738122eb1fb186fb4a1b00065009daa19c8d95d6f6afdbf61f5a83e8f3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 18:05 UTC, opbld33 commented
Docs Build status updates of commit _[7422d25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7422d25ce0aedf4e2c3d533ab7128280bc38cadc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031803083126-16837/BuildReport?accessString=1fbbdfa2dd2d8a41cc41164aee38b3b7379bd243d17fa145dff51c0db0717e7c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 18:22 UTC, FaithOmbongi commented on api-reference/beta/api/domain-promote.md
> +```
@millicentachieng, this section is the cause of the API doctor error. Not sure of the best way to represent a Boolean response object without using suppressions. Could you assist to resolve it?

2022-06-03 18:22 UTC, FaithOmbongi commented
Hi @franqq, The PR has a validation error and @millicentachieng will help us fix it before you can replace the **do not merge** with the **ready to merge** label. 

@millicentachieng, kindly advise on how to resolve the API doctor error without using suppressions.

2022-06-06 09:24 UTC, opbld33 commented
Docs Build status updates of commit _[09bf2c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09bf2c58892ff2a75cf1fd8095cc2b8eb96366df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206060921442716-16837/BuildReport?accessString=f8f518dda077a4b9e69a67de759be40496dda13fd4c4b4ce8970a29ae3a1bdd7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 16:29 UTC, FaithOmbongi commented on api-reference/beta/api/domain-promote.md
> +If successful, this method returns `200 OK`.
Minor fix. However, I think this statement without the type of response object is incomplete, even though it seemed to resolve the API doctor bug. I've asked Millicent for her input just in case.
```suggestion
If successful, this method returns a `200 OK` response code.
```

2022-06-06 17:01 UTC, millicentachieng commented on api-reference/beta/api/domain-promote.md
> +```
@FaithOmbongi, please see if adding `"@odata.type": "boolean"` in the response metadata resolves the error.

2022-06-06 17:57 UTC, FaithOmbongi commented on api-reference/beta/api/domain-promote.md
> +```
cc @franqq, FYA👆🏾

2022-06-06 18:20 UTC, opbld31 commented
Docs Build status updates of commit _[85576fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85576fdac540c817eabcafaad5b6b298643b75ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206061816382681-16837/BuildReport?accessString=cedea1acd4638408a589d8ba33a2a71e6507d527fbe907eb485978c8adbdffd5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 19:14 UTC, opbld33 commented
Docs Build status updates of commit _[34bea03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34bea031f4a476f2cde08ea94c56994edeb34b15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206061912526917-16837/BuildReport?accessString=9ebc578aa165219e3ceffd8d325c87764568a570db5a0d4e67c94909c0f0f963).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 23:54 UTC, eketo-msft approved these changes

2022-06-07 03:01 UTC, opbld30 commented
Docs Build status updates of commit _[e2d68ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2d68eae8b129ce2bcb0f96ddbdc5aad3e62e449)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206070258497086-16837/BuildReport?accessString=54144b6604746d56948e13c9afb7691232250bb346ce4aae27d9562ef14ef5a7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 03:03 UTC, opbld34 commented
Docs Build status updates of commit _[eb78891](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb78891d843df79d27f4d00c077cb43eff8c846a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206070300295426-16837/BuildReport?accessString=05ad4fc1666cf9bc567822ef6dddea993f46f97aee56dfebef232655e9a09ceb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 03:06 UTC, opbld34 commented
Docs Build status updates of commit _[d922eba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d922eba313d47e6652291f747d409c57b199d6c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/domain-promote.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-promote.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/resources/domain.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/domain.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/domain?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/domain-promote?view=graph-rest-beta&branch=pr-en-us-16837) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-domain-promote/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206070302135919-16837/BuildReport?accessString=7a127fb3f4648ea38c90cbf3628b37eb0b81b1385c17952561172c8ea8eec5b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 03:09 UTC, merged