Added Support for editing properties of message in user context.
microsoftgraph/microsoft-graph-docs pull request #16836
Opened 2022-05-10 13:33 UTC by sumitgupta3

These changes are to enable doc updates for editing a chat message in user context.
Earlier we were able to edit only policyViolation in application context.

2022-05-10 13:40 UTC, opbld31 commented
Docs Build status updates of commit _[f5011f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5011f4ae9cd00e93dd79e1c50a16aa80f71082a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-16836) (>= graph-rest-1.0) | [Details](#user-content-f3f226ecc0e3921bbcccfd3010fe3f91-75bc1bff)

<a id="f3f226ecc0e3921bbcccfd3010fe3f91-75bc1bff"></a>
### [api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-update.md)
 - **Line 155, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 4).`````
 - **Line 155, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205101333485999-16836/BuildReport?accessString=d0ac32e5aa3b2f3b7cec238cb8d30926d27f76123760323ddb48f5817463bbd3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 19:18 UTC, opbld31 commented
Docs Build status updates of commit _[f7f7ac8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7f7ac839a73e536587e6cc385e8f92a349b2a48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-16836) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181916404392-16836/BuildReport?accessString=deed45cd8aeaf378d5c827b62aa528c50c461f435f986cff5515c1abcb3321ab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 19:29 UTC, opbld32 commented
Docs Build status updates of commit _[ae1cd91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae1cd91815c326f92f7e4ad028c589d83b3ce568)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-16836) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181927209076-16836/BuildReport?accessString=4e77d54d28b52e31dc21a757900f560188c2f36e16291b529952d84965a37000).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 19:33 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
> +## Request body in application context
Instead of creating separate H2s for application and delegation context, let's clarify in the same H2. For example:
H2 Request body
For applications using delegated permissions:
Information here.

For applications using application permissions:
Info here. 

H2 Response
Similar as above. 

H2 Examples
H3 Example 1: Description. 
H4 Request
H4 Response
H3 Example 2: Description

and so on.

2022-05-18 19:36 UTC, isvargasmsft requested changes
Hello @sumitgupta3, 

Thank you very much for the updates in this PR. 

Please avoid creating separate H2s to differentiate between delegated and application permissions. Instead, let's use a single H2 and differentiate the information inside the H2. 


I took the liberty of fixing some API Doctor errors. In summary, we should always leave a blank line between the headers and the body of a request, and in the example 2 there was an extra }. 

Thank you!

Isaac

2022-05-28 07:50 UTC, opbld30 commented
Docs Build status updates of commit _[d2ab409](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2ab4090831e686821a595ca0c2674fd59a34b95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-16836) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205280739018603-16836/BuildReport?accessString=f5e96cfdbe5e9034f21b00102bcbe61c770232393ce9afd750caa0d8be099c2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 14:37 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
>  ---
I noticed we are updating a v1 topic but not the beta topic. Please confirm which version is this update for.

2022-06-01 04:21 UTC, sumitgupta3 commented on api-reference/v1.0/api/chatmessage-update.md
>  ---
Thanks this was really helpful, I made changes for wrong file and have updated it now.

2022-06-01 04:23 UTC, opbld31 commented
Docs Build status updates of commit _[6142b36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6142b3653f9da626ff5d5a93cd3536038b0b0ce6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16836) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010418034757-16836/BuildReport?accessString=98d597f9254b9fc1a93483d0388dd880385456edd213db9af5180622b66f8d11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 04:29 UTC, opbld33 commented
Docs Build status updates of commit _[6ed7d58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ed7d5864275af4a1a894f1a179f1fa27274f083)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16836) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010425207654-16836/BuildReport?accessString=15b8714a25663806a6958789b916e3f11ea0f49884ebbc2e027ccdb21af4f08e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 16:34 UTC, opbld30 commented
Docs Build status updates of commit _[b013c01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b013c0194e634b74d6c1ce5d17c16a01ba40da34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16836) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206011632495865-16836/BuildReport?accessString=2e40cfa4a8b2974423f680bf9022faac9f8383b9f898eb7b0edf65b6ad5febde).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 16:47 UTC, opbld31 commented
Docs Build status updates of commit _[93cfbcf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93cfbcff4c18318a3ad83294cb1628ff194537a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16836) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206011644356674-16836/BuildReport?accessString=0c68f626033d443bfc490e3d7487dec4c629727f84c9b717bc46def6470e2e6a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 02:50 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update.md
> +Properties of a message except **policyViolation** can be updated using delegated permissions (user context).
Suggested revision for this sentence:
With the exception of the **policyViolation** property, all properties of a message can be updated using delegated permissions.

2022-06-10 02:53 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update.md
> +Only the **policyViolation** property of a **chatMessage** can be updated using application permissions.
Then we can revise this as follows:
Only the **policyViolation** property of a **chatMessage** can be updated in application permissions scenarios.

2022-06-10 02:56 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update.md
> +For applications using delegated permissions:
Please change "using" to "that use", per the Microsoft Writing Style Guide.

2022-06-10 03:01 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update.md
> +### Example 2: Update any property of a message in user context
I suggest instead of "in user context", for consistency, using "by using delegated permissions".

2022-06-10 03:01 UTC, Lauragra commented on api-reference/beta/api/chatmessage-update.md
> +### Example 1: Update policyViolation in application context
Suggest changing "in application context" to "by using application permissions".

2022-06-10 12:38 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-update.md
> +### Example 1: Update policyViolation in application context
Ok

2022-06-10 12:38 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-update.md
> +### Example 2: Update any property of a message in user context
Ok

2022-06-10 12:39 UTC, sumitgupta3 commented on api-reference/beta/api/chatmessage-update.md
> +For applications using delegated permissions:
Ok

2022-06-10 17:01 UTC, Lauragra approved these changes

2022-06-10 17:03 UTC, opbld32 commented
Docs Build status updates of commit _[f198aed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f198aed8ac2d3f9b2a7b8e27b6e0718528f94d9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16836) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206101701114581-16836/BuildReport?accessString=d02765a3a58a1e4328db3195eed78402a882bddfa3f150a47bddd2988cbccd8c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 03:42 UTC, merged