Move phone and email authentication methods from beta to v1.0
microsoftgraph/microsoft-graph-docs pull request #16840
Opened 2022-05-10 21:37 UTC by mmcla

Moving phone and email authentication methods from beta to v1.0, also made a few minor corrections in existing beta docs.

2022-05-10 21:40 UTC, opbld31 commented
Docs Build status updates of commit _[6ce4e2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ce4e2fc31f2702e665fc888f40327b8f02d0715)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :x:Error | | [Details](#user-content-1812180dba2993fec03d9c778ed17349-9988b545)
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :x:Error | | [Details](#user-content-4f965a3bd778e86abea9b124606f3a41-9988b545)
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :x:Error | | [Details](#user-content-539294e0da0c5cfb103a982b7424fbc6-9988b545)
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :x:Error | | [Details](#user-content-220d268cd9c8749e7b955485c8a86091-9988b545)
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :x:Error | | [Details](#user-content-cb7e069b913614273db7740a47b162e8-9988b545)
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :x:Error | | [Details](#user-content-902deb80915a489c80fe297223acdb0f-9988b545)
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :x:Error | | [Details](#user-content-c29396cb81ec0a2e38dc0c31ea9bd33e-9988b545)
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :x:Error | | [Details](#user-content-15fb7a148065b0e5e7eb90dc27dde3d2-9988b545)
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :x:Error | | [Details](#user-content-a852b6cea71d087cdb63e5ffe4a9e8d2-9988b545)
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :x:Error | | [Details](#user-content-6c5b9ddda05ff6432a635f663027e15d-9988b545)
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :x:Error | | [Details](#user-content-16d838c1e86fb6ef4e0fea9e28af7af0-9988b545)
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :x:Error | | [Details](#user-content-f024bf83e39387ff671404295a7500e9-9988b545)
[api-reference/v1.0/api/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod.md) | :warning:Warning | | [Details](#user-content-b87ea86cbc559c7ed67dc06165bc689b-9988b545)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | | [Details](#user-content-8d6126a826a1c08289fc3e3fa561ad6b-9988b545)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9988b545)

<a id="1812180dba2993fec03d9c778ed17349-9988b545"></a>
### [api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md)
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-phonemethods-csharp-snippets.md'.`````
 - **Line 90, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-phonemethods-javascript-snippets.md'.`````
 - **Line 94, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-phonemethods-objc-snippets.md'.`````
 - **Line 98, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-phonemethods-java-snippets.md'.`````
 - **Line 102, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-phonemethods-go-snippets.md'.`````
 - **Line 106, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-phonemethods-powershell-snippets.md'.`````
 - **Line 14, Column 20**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/phoneauthenticationmethod.md'.`````
 - **Line 68, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/phoneauthenticationmethod.md'.`````

<a id="4f965a3bd778e86abea9b124606f3a41-9988b545"></a>
### [api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md)
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-phoneauthenticationmethod-from-authentication-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-phoneauthenticationmethod-from-authentication-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-phoneauthenticationmethod-from-authentication-objc-snippets.md'.`````
 - **Line 109, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-phoneauthenticationmethod-from-authentication-java-snippets.md'.`````
 - **Line 113, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-phoneauthenticationmethod-from-authentication-go-snippets.md'.`````
 - **Line 117, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-phoneauthenticationmethod-from-authentication-powershell-snippets.md'.`````
 - **Line 14, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/phoneauthenticationmethod.md'.`````
 - **Line 64, Column 56**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/phoneauthenticationmethod.md'.`````
 - **Line 73, Co [...]

2022-05-10 23:10 UTC, opbld33 commented
Docs Build status updates of commit _[6a614c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a614c87465f4e4b3e6b2dd07e656fa98f29d11b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :x:Error | | [Details](#user-content-1812180dba2993fec03d9c778ed17349-7d673153)
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :x:Error | | [Details](#user-content-4f965a3bd778e86abea9b124606f3a41-7d673153)
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :x:Error | | [Details](#user-content-539294e0da0c5cfb103a982b7424fbc6-7d673153)
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :x:Error | | [Details](#user-content-220d268cd9c8749e7b955485c8a86091-7d673153)
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :x:Error | | [Details](#user-content-cb7e069b913614273db7740a47b162e8-7d673153)
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :x:Error | | [Details](#user-content-902deb80915a489c80fe297223acdb0f-7d673153)
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :x:Error | | [Details](#user-content-c29396cb81ec0a2e38dc0c31ea9bd33e-7d673153)
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :x:Error | | [Details](#user-content-15fb7a148065b0e5e7eb90dc27dde3d2-7d673153)
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :x:Error | | [Details](#user-content-a852b6cea71d087cdb63e5ffe4a9e8d2-7d673153)
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :x:Error | | [Details](#user-content-6c5b9ddda05ff6432a635f663027e15d-7d673153)
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :x:Error | | [Details](#user-content-16d838c1e86fb6ef4e0fea9e28af7af0-7d673153)
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :x:Error | | [Details](#user-content-f024bf83e39387ff671404295a7500e9-7d673153)

<a id="1812180dba2993fec03d9c778ed17349-7d673153"></a>
### [api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md)
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-phonemethods-csharp-snippets.md'.`````
 - **Line 90, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-phonemethods-javascript-snippets.md'.`````
 - **Line 94, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-phonemethods-objc-snippets.md'.`````
 - **Line 98, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-phonemethods-java-snippets.md'.`````
 - **Line 102, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-phonemethods-go-snippets.md'.`````
 - **Line 106, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-phonemethods-powershell-snippets.md'.`````

<a id="4f965a3bd778e86abea9b124606f3a41-7d673153"></a>
### [api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md)
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-phoneauthenticationmethod-from-authentication-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-phoneauthenticationmethod-from-authentication-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-phoneauthenticationmethod-from-authentication-objc-snippets.md'.`````
 - **Line 109, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-phoneauthenticationmethod-from-authentication-java-snippets.md'.`````
 - **Line 113, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-phoneauthenticationmethod-from-authentication-go-snippets.md'.`````
 - **Line 117, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-phoneauthenticationmethod-from-authentication-powershell-snippets.md'.`````

<a id="539294e0da0c5cfb103a982b7424fbc6-7d673153"></a>
### [api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md)
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-emailauthenticationmethod-csharp-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-emailauthenticationmethod-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-emailauthenticationmethod-objc-snippets.md'.`````
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-emailauthenticationmethod-java-snippets.md'.`````
 - **Line 90, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-emailauthenticationmethod-go-snippets.md'.`````
 - **Line 94, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-emailauthenticationmethod-powershell-snippets.md'.`````

<a id="220d268cd9c8749e7b955485c8a86091-7d673153"></a>
### [api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md)
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-emailauthenticationmethod-1-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid [...]

2022-05-11 06:50 UTC, andres-canello commented
Only comment is if you want to use this PR to update wording on the overview page for Default and Require re-register. Also, it'd be great to remove passwordlessMicrosoftAuthenticatorAuthenticationMethod :)

2022-05-11 15:58 UTC, opbld32 commented
Docs Build status updates of commit _[9c26951](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c26951a371625bc4f04d0102f227813bb649a9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205111556164502-16840/BuildReport?accessString=a8618c43760f359cc4cecc6cf04ef37ed237d34599f4fbb681a699eb150636e8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see t [...]

2022-05-11 16:05 UTC, opbld34 commented
Docs Build status updates of commit _[9fbf2ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fbf2ab308c0979dc32cbe6586d57b1fe134fca8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/re [...]

2022-05-11 16:15 UTC, mmcla commented
> Only comment is if you want to use this PR to update wording on the overview page for Default and Require re-register. Also, it'd be great to remove passwordlessMicrosoftAuthenticatorAuthenticationMethod :)

@andres-canello, I've added the require re-reg item but chose not to address Default and the deprecation in this PR.

2022-05-11 17:57 UTC, opbld34 commented
Docs Build status updates of commit _[f657e09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f657e098abe6635e25083659b1cb47d188c686be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/res [...]

2022-05-11 18:49 UTC, opbld33 commented
Docs Build status updates of commit _[8b2e208](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b2e20806b4ae360dfccd894760b9e9ce197d9df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/res [...]

2022-05-25 19:02 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md
> +description: "Enable SMS sign-in for a mobile phone."
```suggestion
description: "Enable SMS sign-in for a mobile phone number registered to a user."
```

2022-05-25 19:02 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md
> +Enable SMS sign-in for an existing `mobile` phone number. To be successfully enabled:
```suggestion
Enable SMS sign-in for an existing `mobile` phone number registered to a user. To be successfully enabled:
```

2022-05-25 19:02 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-05-25 19:04 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md
> +If successful, this method returns a `200 OK` response code. It does not return anything in the response body.
```suggestion
If successful, this method returns a `204 No Content` response code. It does not return anything in the response body.
```

2022-05-25 19:04 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md
> +HTTP/1.1 200 OK
```suggestion
HTTP/1.1 204 No Content
```

2022-05-25 19:04 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md
> +description: "Disable SMS sign-in for a mobile phone"
```suggestion
description: "Disable SMS sign-in for a mobile phone registered to a user."
```

2022-05-25 19:05 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md
> +>**Note:** The number will no longer be available for SMS sign-in, which can prevent your user from signing in.
```suggestion
Disable SMS sign-in for an existing `mobile` phone number registered to a user. The number will no longer be available for SMS sign-in, which can prevent your user from signing in.
```

2022-05-25 19:06 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-05-25 19:06 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md
> +If successful, this method returns a `200 OK` response code. It does not return anything in the response body.
Hope this is correct?
```suggestion
If successful, this method returns a `204 No Content` response code. It does not return anything in the response body.
```

2022-05-25 19:07 UTC, FaithOmbongi commented on api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md
> +HTTP/1.1 200 OK
```suggestion
HTTP/1.1 204 No Content
```

2022-05-25 19:08 UTC, FaithOmbongi commented on api-reference/v1.0/resources/softwareoathauthenticationmethod.md
> +description: "A representation of a Software OATH token registered to a user. Software OATH is a multi-factor authentication method."
```suggestion
description: "Represents a Software OATH token registered to a user. Software OATH is a multi-factor authentication method."
```

2022-05-25 19:10 UTC, FaithOmbongi commented on api-reference/v1.0/resources/softwareoathauthenticationmethod.md
> +A representation of a software OATH token registered to a user. A software OATH token is a software-based number generator that uses the OATH Time-Based One Time Password (TOTP) standard for multi-fa
```suggestion
Represents a software OATH token registered to a user. A software OATH token is a software-based number generator that uses the OATH Time-Based One Time Password (TOTP) standard for multi-factor authentication. This API will not return Microsoft Authenticator authentication method entities, though it will return an entity if Microsoft Authenticator was set up via the third-party software authenticator flow.
```

2022-05-25 19:12 UTC, FaithOmbongi commented on api-reference/v1.0/api/authentication-list-softwareoathmethods.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-05-25 19:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/authentication-list-softwareoathmethods.md
> +      "secretKey": "String"
You mentioned in the property description that this is always `null`?
```suggestion
      "secretKey": null
```

2022-05-25 19:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md
> +description: "Deletes a softwareOathAuthenticationMethod object."
```suggestion
description: "Deletes a user's softwareOathAuthenticationMethod object."
```

2022-05-25 19:15 UTC, FaithOmbongi commented on api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-05-25 19:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/softwareoathauthenticationmethod-get.md
> +description: "Read the properties and relationships of a softwareOathAuthenticationMethod object."
```suggestion
description: "Retrieve a user's softwareOathAuthenticationMethod object and is properties."
```

2022-05-25 19:17 UTC, FaithOmbongi commented on api-reference/v1.0/api/softwareoathauthenticationmethod-get.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-05-25 19:17 UTC, FaithOmbongi commented on api-reference/v1.0/api/softwareoathauthenticationmethod-get.md
> +    "secretKey": "String"
```suggestion
    "secretKey": null
```

2022-05-25 19:29 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
Suggestions for enhancement and linking to the respective resource files.
Also add the 3 changelog objects for the 3 relationships you're going to add to the [authentication](https://docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0) resource.
```suggestion
        {
          "Id": "cf98cee8-873f-424f-9a0b-c683ea38a660",
          "ApiChange": "Resource",
          "ChangedApiName": "emailAuthenticationMethod",
          "ChangeType": "Addition",
          "Description": "Added the [emailAuthenticationMethod](https://docs.microsoft.com/en-us/graph/api/resources/emailAuthenticationMethod?view=graph-rest-1.0) resource and related methods. Use this resource and associated methods to manage a user's email authentication method for self-service password reset (SSPR).",
          "Target": "emailAuthenticationMethod"
        },
        {
          "Id": "51cc8ef6-7798-4344-b6ee-e48543e5a50a",
          "ApiChange": "Resource",
          "ChangedApiName": "phoneAuthenticationMethod",
          "ChangeType": "Addition",
          "Description": "Added the [phoneAuthenticationMethod](https://docs.microsoft.com/en-us/graph/api/resources/phoneAuthenticationMethod?view=graph-rest-1.0) resource and associated methods. Use this resource and associated methods to manage a user's phone numbers used for authentication.",
          "Target": "phoneAuthenticationMethod"
        },
        {
          "Id": "ae0b4038-ef8b-48e7-b711-c52dbde06cf8",
          "ApiChange": "Resource",
          "ChangedApiName": "softwareOathAuthenticationMethod",
          "ChangeType": "Addition",
          "Description": "Added the [softwareOathAuthenticationMethod]((https://docs.microsoft.com/en-us/graph/api/resources/phoneAuthenticationMethod?view=graph-rest-1.0) resource and associated methods. Use this resource and associated methods to manage the Software OATH token registered to a user.",
          "Target": "softwareOathAuthenticationMethod"
        }
```

2022-06-03 18:48 UTC, opbld30 commented
Docs Build status updates of commit _[dd9ab00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd9ab00d26c13d6dfea8718de7bf13fee813c32c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | [...]

2022-06-03 18:49 UTC, mmcla commented on api-reference/v1.0/api/authentication-post-phonemethods.md
> +title: "Create phoneAuthenticationMethod"
No, this only creates a single method entity.

2022-06-03 22:34 UTC, mmcla commented on api-reference/v1.0/api/authentication-post-phonemethods.md
> +# Create phoneAuthenticationMethod
Same as above - this creates a method, not a collection.

2022-06-03 22:34 UTC, opbld33 commented
Docs Build status updates of commit _[654a26a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/654a26a35f4eef2688ad8fa0d054cfd65e1e6ad5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | [...]

2022-06-03 22:41 UTC, opbld34 commented
Docs Build status updates of commit _[8c89551](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c89551892abfd570c27a80ef53e3177c58115a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | [...]

2022-06-03 22:44 UTC, opbld31 commented
Docs Build status updates of commit _[4bdb178](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4bdb1781eac02621191be3cb472cd9b35d2cc9f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | [...]

2022-06-03 23:08 UTC, opbld31 commented
Docs Build status updates of commit _[584dff9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/584dff9722c1d7f8f85131a6bd207176eedb198a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-26b8d4a2)
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main [...]

2022-06-03 23:12 UTC, opbld32 commented
Docs Build status updates of commit _[e7cf376](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7cf376f4c2ca608fb67bf66a23953347c6e875c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-f0ef5479)
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main [...]

2022-06-03 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[c5d5efc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5d5efcbb09ef7a4c3bd1123e863dcab20d21cf1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-6fdbb8df)
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main [...]

2022-06-03 23:26 UTC, opbld33 commented
Docs Build status updates of commit _[fc323c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc323c70ba7f9c3482ddad407eda2d93647cc206)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-f024bf83e39387ff671404295a7500e9-98498420)
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-98498420)
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https:// [...]

2022-06-03 23:29 UTC, opbld33 commented
Docs Build status updates of commit _[211b8b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/211b8b376a5dc39d9075941631f76c4fd3a22f30)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-f024bf83e39387ff671404295a7500e9-66d036eb)
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-66d036eb)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-66d036eb)
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-9c4a6d8092cd86e24a16a5500cead9bf-66d036eb)
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssign [...]

2022-06-03 23:33 UTC, opbld32 commented
Docs Build status updates of commit _[36ae4bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36ae4bcd90ef709e71b663cb9dde0b7ba9ffd91a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-907eb3f7)

<a id="907eb3f7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206032332319703-16840/BuildReport?accessString=6bb6a8d260273cf3ca389bea02595e3b5daab060bca59b5064cb7de1562a9786).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 23:39 UTC, opbld33 commented
Docs Build status updates of commit _[2bc0d84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bc0d84d22872f16fa24d93e5ff133400e3ec403)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9c03f7c3)

<a id="9c03f7c3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206032338329110-16840/BuildReport?accessString=1068960b9883ddad47b1a484881b1a6eba89da3350d2ecacb04e8aba70b5d0b0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 23:48 UTC, opbld31 commented
Docs Build status updates of commit _[33d211c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33d211ce9c2dc3e3925e47df0315b7e77df923b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0b26f0184b88adbba71dd89ca5bd99d5-b07a03c6)
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-f024bf83e39387ff671404295a7500e9-b07a03c6)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-8d6126a826a1c08289fc3e3fa561ad6b-b07a03c6)
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-b07a03c6)
[api-reference/v1.0/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-7b1f2a28543215c3e27c49f14e184e97-b07a03c6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b07a03c6)
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-9c4a6d8092cd86e24a16a5500cead9bf-b07a03c6)
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emaila [...]

2022-06-03 23:50 UTC, opbld34 commented
Docs Build status updates of commit _[1d1d874](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d1d8741934082d18c89a1bdfa686eb6fe418ba1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0b26f0184b88adbba71dd89ca5bd99d5-19834ed9)
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-f024bf83e39387ff671404295a7500e9-19834ed9)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-8d6126a826a1c08289fc3e3fa561ad6b-19834ed9)
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-19834ed9)
[api-reference/v1.0/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-7b1f2a28543215c3e27c49f14e184e97-19834ed9)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-19834ed9)
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-9c4a6d8092cd86e24a16a5500cead9bf-19834ed9)
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emaila [...]

2022-06-03 23:53 UTC, opbld31 commented
Docs Build status updates of commit _[080a0fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/080a0fe4d4606a5a9c3c28db317e0899250a5d8e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0b26f0184b88adbba71dd89ca5bd99d5-f872f83e)
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-f024bf83e39387ff671404295a7500e9-f872f83e)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-8d6126a826a1c08289fc3e3fa561ad6b-f872f83e)
[api-reference/v1.0/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-7b1f2a28543215c3e27c49f14e184e97-f872f83e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f872f83e)
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-9c4a6d8092cd86e24a16a5500cead9bf-f872f83e)
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr- [...]

2022-06-04 00:02 UTC, opbld32 commented
Docs Build status updates of commit _[7fd7dc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fd7dc0af576698072b0e8395027616325824d22)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) | [Details](#user-content-0b26f0184b88adbba71dd89ca5bd99d5-f8bdea0c)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-8d6126a826a1c08289fc3e3fa561ad6b-f8bdea0c)
[api-reference/v1.0/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/emailauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-07e15095c60c0e836140d8ba49d4f9dd-f8bdea0c)
[api-reference/v1.0/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/phoneauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-7b1f2a28543215c3e27c49f14e184e97-f8bdea0c)
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https [...]

2022-06-04 00:03 UTC, mmcla commented
@FaithOmbongi  I believe I've addressed all of your comments.

2022-06-04 00:14 UTC, opbld33 commented
Docs Build status updates of commit _[4916f88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4916f88741ff029770b628ec277d0a576e2f8251)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-48321b1e)
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-u [...]

2022-06-04 00:20 UTC, opbld30 commented
Docs Build status updates of commit _[491cfb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/491cfb0e5574ca700dd9e0e09d6e6d2f541e6a73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.micros [...]

2022-06-04 00:28 UTC, opbld33 commented
Docs Build status updates of commit _[51a5085](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51a50858ecfe0d97884dac3f1754d9c0ae3b396f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.micros [...]

2022-06-06 19:11 UTC, FaithOmbongi requested changes
Hi @mmcla - Thank you for addressing the initial round of review feedback. I've left a few suggestions for minor fixes before approval. Mostly fixing names and titles because the info is reused in other autogenerated docs like the PowerShell SDK docs and the OpenAPI descriptions.

2022-06-06 19:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Id": "cf98cee8-873f-424f-9a0b-c683ea38a660",
All the objects in this changelog should have the same ID. This allows customers to see all these objects when they share the anchor link to the changelog (which always contains the ID).

2022-06-06 19:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **emailAuthenticationMethod** navigation property to the [authentication](https://docs.microsoft.com/graph/api/resources/authentication) resource.",
The nav property name is emailMethods, not emailAuthenticationMethod
```suggestion
          "Description": "Added the **emailMethods** navigation property to the [authentication](https://docs.microsoft.com/graph/api/resources/authentication) resource.",
```

2022-06-06 19:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **phoneAuthenticationMethod** navigation property to the [authentication](https://docs.microsoft.com/graph/api/resources/authentication) resource.",
```suggestion
          "Description": "Added the **phoneMethods** navigation property to the [authentication](https://docs.microsoft.com/graph/api/resources/authentication) resource.",
```

2022-06-06 19:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **softwareOathAuthenticationMethod** navigation property to the [authentication](https://docs.microsoft.com/graph/api/resources/authentication) resource.",
```suggestion
          "Description": "Added the **softwareOathMethods** navigation property to the [authentication](https://docs.microsoft.com/graph/api/resources/authentication) resource.",
```

2022-06-06 19:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Id": "b5a1875e-c52b-44f0-be4c-7a316c68335d",
All 3 objects should have same ID for the same reason as above

2022-06-06 19:11 UTC, FaithOmbongi commented on api-reference/v1.0/api/authentication-list-emailmethods.md
> +# List emailAuthenticationMethods
nit: Title should follow the convention "List navigationPropertyName"
```suggestion
title: "List emailMethods"
description: "Get a list of the emailAuthenticationMethod objects for a user."
author: "mmcla"
ms.localizationpriority: medium
ms.prod: "identity-and-sign-in"
doc_type: "apiPageType"
---

# List emailMethods
```

2022-06-06 19:11 UTC, FaithOmbongi commented on api-reference/v1.0/api/authentication-post-emailmethods.md
> +# Create emailAuthenticationMethod
nit: Title should follow the convention "Create navigationPropertyName"
```suggestion
title: "Create emailMethod"
description: "Create a new emailAuthenticationMethod object for a user."
author: "mmcla"
ms.localizationpriority: medium
ms.prod: "identity-and-sign-in"
doc_type: "apiPageType"
---

# Create emailMethod
```

2022-06-06 19:11 UTC, FaithOmbongi commented on api-reference/v1.0/api/authentication-post-phonemethods.md
> +# Create phoneAuthenticationMethod
```suggestion
title: "Create phoneMethod"
description: "Add a new phone authentication method for a user."
ms.localizationpriority: medium
author: "mmcla"
ms.prod: "identity-and-sign-in"
doc_type: "apiPageType"
---

# Create phoneMethod
```

2022-06-22 22:27 UTC, opbld34 commented
Docs Build status updates of commit _[6814aac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6814aacf10e0ecf5d0f3869e3fedc5558c0e8409)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fd96cfff)

<a id="fd96cfff"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222226278053-16840/BuildReport?accessString=c978f7e3af3963f73b57e29822c841208a800dee939b063d8dd12e46abb9536a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:28 UTC, opbld32 commented
Docs Build status updates of commit _[e696090](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e69609099e3126d1e28b3c835feb706238e14251)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-df52a721)

<a id="df52a721"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222227320970-16840/BuildReport?accessString=2760895257cf16fbf0fe37ab9438c4d0d32a444d8f48009b936baf3f884b4296).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:29 UTC, opbld32 commented
Docs Build status updates of commit _[7cebb83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cebb834edfba14a91c11e453c983798705d2151)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d3708843)

<a id="d3708843"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222228100455-16840/BuildReport?accessString=0deb8a072376db10e35ad4d9c7b871badfcc3dc8fb1ac8adeb04f8f4068dd1b2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:29 UTC, opbld33 commented
Docs Build status updates of commit _[c2fd22c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2fd22c9b14962898c2d5a97a38c2a68d4e9a861)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-adc67004)

<a id="adc67004"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222229035702-16840/BuildReport?accessString=e3677409ca9458f75ee3b56b570d72b7501e55c5e47c8d6274580cf07bc36f13).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:31 UTC, opbld32 commented
Docs Build status updates of commit _[02348e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02348e13d7b0a85fb63b259b5d1c45cb85d0e5ac)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-831b962b)

<a id="831b962b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222229591293-16840/BuildReport?accessString=f662d7936388b089fb38e953e30bb47ab74eb72581b211a44c405aa741c31502).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:32 UTC, opbld31 commented
Docs Build status updates of commit _[bc68c48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc68c4862475886d56d58442237b6966eb09070f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e3165a1e)

<a id="e3165a1e"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222230211685-16840/BuildReport?accessString=e85948a2e2f208472f23700e5caf3c10181c84156b52ca1479dbdd5a7da503f0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:33 UTC, opbld34 commented
Docs Build status updates of commit _[26ce749](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26ce749d2cf43496dc8c5c453d2c87423ceadd6f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4fd90322)

<a id="4fd90322"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222228267157-16840/BuildReport?accessString=f71ba2f3b66f9447f3ca6eefaa6966405e069183b49dea7301516c4ec1215a4c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:38 UTC, opbld33 commented
Docs Build status updates of commit _[8a5b91e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a5b91e33f50b7dfebbd5305d0420554db09b7ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https: [...]

2022-06-22 22:40 UTC, mmcla commented
@FaithOmbongi, addressed all of your comments. Hopefully we're now done? We're blocked from release by this.

2022-06-23 17:42 UTC, opbld34 commented
Docs Build status updates of commit _[0a9cf8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a9cf8c18a528690699123fe122d347c875cd6c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https: [...]

2022-07-05 23:58 UTC, opbld32 commented
Docs Build status updates of commit _[2ea6191](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ea6191e41bac7c1f6ba1d7d1873c2d4f9abdc5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https: [...]

2022-08-09 01:08 UTC, opbld31 commented
Docs Build status updates of commit _[9aef6a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9aef6a6b41682a8f4afe7fffeef8318c98392ea0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-765d6c56)

<a id="765d6c56"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208090106212315-16840/BuildReport?accessString=4524db77b082145dd94bc4ca1fa4b13810411eb9bda2cc4a55e3962401921c92).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 16:43 UTC, opbld34 commented
Docs Build status updates of commit _[9b4f3a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b4f3a3dfa7cee6b41a345a163dc9785835904bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https: [...]

2022-08-10 16:54 UTC, opbld34 commented
Docs Build status updates of commit _[0f017e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f017e78cc2ff937252588233d2e25b48f5e740e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/api/phoneauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/api/phoneauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/emailauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/resources/phoneauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/resources/phoneauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/phoneauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-beta&branch=pr-en-us-16840) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-emailmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-emailmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-emailmethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/authentication-post-phonemethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/emailauthenticationmethod-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-disablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-phoneemailauthmethodupdates/api-reference/v1.0/api/phoneauthenticationmethod-enablesmssignin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-1.0&branch=pr-en-us-16840) (>= graph-rest-1.0) |
[api-reference/v1.0/api/phoneauthenticationmethod-get.md](https: [...]

2022-08-10 16:55 UTC, FaithOmbongi approved these changes

2022-08-11 02:51 UTC, merged