Adding enabled content experiences and compliance settings
microsoftgraph/microsoft-graph-docs pull request #16858
Opened 2022-05-11 20:48 UTC by emzho

Roadmap Item ID: 14127
API.md are both listed in the description for that roadmap item.

Documenting the enabledContentExperiences and complianceSettings properties.

2022-05-11 20:50 UTC, opbld32 commented
Docs Build status updates of commit _[260ba3f](https://github.com/emzho/microsoft-graph-docs/commits/260ba3f08daca66ad773e44292b2a9cc72178cd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205112048315315-16858/BuildReport?accessString=9ccda3ade87d639cc054ed682b33317f6e2a26969f2c52e47d60e84f1ec16bd0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 21:29 UTC, opbld34 commented
Docs Build status updates of commit _[cab74fe](https://github.com/emzho/microsoft-graph-docs/commits/cab74fe2382a07292a00235eef1fd3911aee0725)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205112126457584-16858/BuildReport?accessString=77749cdaca176043b72c4549e59a92d7489e024fbbfb6b8e51e714faa092c546).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 23:03 UTC, opbld34 commented
Docs Build status updates of commit _[953378a](https://github.com/emzho/microsoft-graph-docs/commits/953378ae560606d7ebf2bbfd46d6c466ea330744)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205112300403629-16858/BuildReport?accessString=d7b8415010faf75bffff6313f07747c2249bb5e679912ecf4d7954ed2c8b31c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 17:31 UTC, opbld32 commented
Docs Build status updates of commit _[7387376](https://github.com/emzho/microsoft-graph-docs/commits/7387376b544ee780ea232069110a79a19d62efd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205131726210057-16858/BuildReport?accessString=008ad0d0711dc07bdf01515c1dbbb35a75eb961cafb2f0299f652dfdbe66b6bc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 00:15 UTC, emzho commented on api-reference/beta/resources/externalconnectors-compliancesettings.md
> +
TO DO: @KumarSeetharaman74 to add a note for eDiscovery special Adaptive Card Library requirements for partners.

2022-05-18 00:25 UTC, emzho commented on api-reference/beta/resources/externalconnectors-externalconnection.md
> +| enabledContentExperiences | microsoft.graph.externalConnectors.contentExperienceType collection | The list of content experiences the connection will participate in. Possible values are `search` an
TO DO: make sure "Required" is the end decision for this property.

2022-05-18 16:26 UTC, opbld30 commented
Docs Build status updates of commit _[bb8584c](https://github.com/emzho/microsoft-graph-docs/commits/bb8584c4df9b0eac1b920517726d000b65f8432f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205181616564411-16858/BuildReport?accessString=20246827d527c4ab8d513696c723501538181254faf67f8809cace122d02780e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 19:19 UTC, josmoran-MSFT approved these changes

2022-06-21 22:54 UTC, Danielabom commented on changelog/Microsoft.Search.json
>        "CreatedDateTime": "2022-04-28T00:00:00",
Hi @emzho, I believe that the two properties added need a changelog entry. Thanks.

2022-06-21 22:55 UTC, Danielabom requested changes
Hi @emzho I added a comment to the changelog file. Please review it.

2022-06-21 23:09 UTC, emzho commented on changelog/Microsoft.Search.json
>        "CreatedDateTime": "2022-04-28T00:00:00",
Done. Thank you!

2022-06-21 23:09 UTC, opbld31 commented
Docs Build status updates of commit _[d8fff28](https://github.com/emzho/microsoft-graph-docs/commits/d8fff28c0936c4de1ebc44dc6f1266c246ec877c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206212307133653-16858/BuildReport?accessString=6f4287e8ab5b5a1038cb8686aea38422b1c8877c8fecbbf80d7ea3e8f50a1480).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 14:25 UTC, Danielabom approved these changes
@emzho, thanks for addressing my comments. Changes look good to me.

2022-07-13 23:47 UTC, opbld31 commented
Docs Build status updates of commit _[fd9e0f5](https://github.com/emzho/microsoft-graph-docs/commits/fd9e0f542cb8409409b7bc9a3cb1f89697c507ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207132345199976-16858/BuildReport?accessString=49ca7c1d4b572915969c610e2acb26e65de0f6fb0f9086988520b244bf14bdbb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 17:00 UTC, opbld31 commented
Docs Build status updates of commit _[ffa0865](https://github.com/emzho/microsoft-graph-docs/commits/ffa0865fbd73763f5a967fea4281ca8f54c152fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207141657379803-16858/BuildReport?accessString=d6e1b80aa4ddec73e6e4759a1a30199be702a59deeca3e22fc30b06f038e63c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 18:04 UTC, Danielabom approved these changes
Hi Emily, thank you for pointing me to the new change. 
Everything looks okay. Thanks.

2022-08-10 21:19 UTC, opbld30 commented
Docs Build status updates of commit _[5730916](https://github.com/emzho/microsoft-graph-docs/commits/57309166dac6d3eb2afbc944f90c49676e30b105)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208102117079483-16858/BuildReport?accessString=55c8a519d5bd1aef9c13c44a40b495feabe71ebe9a21ce7bcbe7a36d72173a9f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 21:28 UTC, opbld31 commented
Docs Build status updates of commit _[db950cb](https://github.com/emzho/microsoft-graph-docs/commits/db950cbb370e6a08e7d27e7930b7a5de499af727)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208102127015526-16858/BuildReport?accessString=11e1a6af8cac485075c24e20cf7775ca4d944073d170f909e139334823b86eca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 20:58 UTC, emzho commented on api-reference/beta/resources/externalconnectors-compliancesettings.md
> +> The eDiscovery result template is only supported for Adaptive Card version 1.2 or below. Please refer to the Compliance settings section of [Create, update, and delete connections](/graph/connectin
@KumarSeetharaman74 do we want to also call out the extra requirements here (not supporting markdown, not supporting data binding) or just edit it in the conceptual docs, which are linked already?

2022-09-27 03:07 UTC, Lauragra commented on api-reference/beta/resources/externalconnectors-compliancesettings.md
> +> The eDiscovery result template is only supported for Adaptive Card version 1.2 or below. Please refer to the Compliance settings section of [Create, update, and delete connections](/graph/connectin
Please verify this link; the article does have a "Compliance settings" section. Can you link directly to the section you intend?

2022-09-27 03:10 UTC, opbld30 commented
Docs Build status updates of commit _[5e0f211](https://github.com/emzho/microsoft-graph-docs/commits/5e0f211146594fd4e5be249a4eb75fab85b1852d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums-externalconnectors.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/enums-externalconnectors.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums-externalconnectors?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-compliancesettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-compliancesettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-compliancesettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-externalconnection.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-externalconnection.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-externalconnection?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[api-reference/beta/resources/externalconnectors-searchsettings.md](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/api-reference/beta/resources/externalconnectors-searchsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/externalconnectors-searchsettings?view=graph-rest-beta&branch=pr-en-us-16858) (graph-rest-beta) |
[changelog/Microsoft.Search.json](https://github.com/emzho/microsoft-graph-docs/blob/users/emzho/addEnabledContentExpDocs/changelog/Microsoft.Search.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209270307143557-16858/BuildReport?accessString=ae4ba0c11b64604319337c9ae6bfcde1d4e3d0b59e433c95dd30de66b778c434).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 16:16 UTC, emzho commented on api-reference/beta/resources/externalconnectors-compliancesettings.md
> +> The eDiscovery result template is only supported for Adaptive Card version 1.2 or below. Please refer to the Compliance settings section of [Create, update, and delete connections](/graph/connectin
Hi, I assume you meant that it does NOT have a compliance settings section. The PR #17288 which was queued for merge also, added this section. Sorry! I guess the other one has to come first.

2022-10-03 17:34 UTC, Lauragra approved these changes

2022-10-04 02:00 UTC, merged