Export API-Add message history support
microsoftgraph/microsoft-graph-docs pull request #16857
Opened 2022-05-11 20:32 UTC by AGLIU123

Teams Export APIs allow users to export 1:1, group chat, meeting chats and channel messages from Microsoft Teams.
In order to provide better user experience and for compliance purpose, we are now providing message history information to customer. (Currently only reaction information is included).

2022-05-11 20:34 UTC, opbld34 commented
Docs Build status updates of commit _[3fcd2be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fcd2be2bfe980449d49f6b6e2d20b88713eee0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205112032349982-16857/BuildReport?accessString=89bb82aa7ee11b798a2f85f1c9339fdcd9a4e6c87cddf03ba6163f033a559888).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 20:36 UTC, opbld33 commented
Docs Build status updates of commit _[398548f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/398548f1aef4a4bd30d24fff94a0ebcf9dfc54e5)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205112033521880-16857/BuildReport?accessString=5b5021c47f129ce04e4f0258147b76e267a57c40e08bf7d2d5616b34e97c8475).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 17:47 UTC, AGLIU123 commented
Waiting for dependency's change.

2022-10-21 03:27 UTC, opbld30 commented
Learn Build status updates of commit _[331fb2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/331fb2c034ec57a0983c3aa026c8aa2f08aa275d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210210325084228-16857/BuildReport?accessString=aacc479e4c82ca833021cfc4cd2432cb06cdb69a89a31bcedcc042a4e5982c71).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 03:45 UTC, opbld30 commented
Learn Build status updates of commit _[a64393b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a64393b39da94cf90e4701a2cbe500fccffe1fae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210210342427488-16857/BuildReport?accessString=6fd97b88baf8054b5f78a8e35ccb8c08d8f6df621bc500e8709241b719886c86).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 22:24 UTC, opbld32 commented
Learn Build status updates of commit _[e02324f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e02324fd9578a7d64cee6d7359f559bb400f1cbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211082222127189-16857/BuildReport?accessString=29ea1aa7c58d52a0d3feb58e16c7577bfd29ef7563aa63b4df6714fc68b64ab3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-11 15:26 UTC, isvargasmsft commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +
Please add the definition of the new enumeration chatMessageActions. You can either define it in the enums.md file or in this topic, bellow the Properties table. 
Please follow the guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211747/Enumerations

Use either Option 1 or 2 according to your best judgement.

2022-11-11 15:49 UTC, isvargasmsft commented on api-reference/beta/api/chat-list-messages.md
> +            "messageHistory": []
Please also add these updates (add the new property to the response) to the examples in the following topics:

- https://learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http
- https://learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&tabs=http
- https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http
- https://learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&tabs=http

2022-11-11 15:54 UTC, opbld31 commented
Learn Build status updates of commit _[f81575d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f81575d1bc7a0daef6c0519f5a46956a4f1f6d8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211111551268326-16857/BuildReport?accessString=d188a280d7176cc7ec8d9a6fd44d99e3936ca4383993668a7bfdff9709d88deb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-11 15:54 UTC, isvargasmsft commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +|modifiedDateTime|DateTimeOffset|The message modification date time.|
Suggestion:
```suggestion
|modifiedDateTime|DateTimeOffset|The date and time when the message was modified. |
```

2022-11-11 15:57 UTC, isvargasmsft commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +|reaction|[chatMessageReaction](../resources/chatmessagereaction.md)|The reaction in the modified message.|
What kind of reaction are we referring to? The emojis reactions? What confuses me is the use of the article "the". 

Suggestion:
```suggestion
|reaction|[chatMessageReaction](../resources/chatmessagereaction.md)| Any reaction to the modified message. |
```

2022-11-11 16:00 UTC, isvargasmsft requested changes
Hello @AGLIU123, 

Thank you very much for your work in this PR. It was very complete overall. 

Please take a look at a few comments we left on completeness and voice. We left a few suggestions for you, please let us know if you have questions. 

Feel free to ping us on the side anytime. 

Kind regards, 

Isaac and Mike

2022-11-11 19:37 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +
Thanks for the comment. Added the enumeration chatMessageActions to enums.md.

2022-11-11 19:38 UTC, AGLIU123 commented on api-reference/beta/api/chat-list-messages.md
> +            "messageHistory": []
Added the change to the docs.

2022-11-11 19:41 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +|reaction|[chatMessageReaction](../resources/chatmessagereaction.md)|The reaction in the modified message.|
Use "the" because this reaction is specific to the message which is just changed, and only one reaction will be changed every time. :)

2022-11-11 19:42 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessage.md
> +|messageHistory|[chatMessageHistoryItem](../resources/chatmessagehistoryitem.md) collection|List of message edition history.|
Added more details in the description.

2022-11-11 19:43 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +|modifiedDateTime|DateTimeOffset|The message modification date time.|
Changed, thanks!

2022-11-11 19:49 UTC, opbld33 commented
Learn Build status updates of commit _[2eb6641](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eb6641d2cc03b39cf63661086e07d5952dfd779)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211111936135499-16857/BuildReport?accessString=bbb0a9bbbe9407defcfd12364540383e01ed8f51c3524f76c5ae58d4f6862d47).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-16 21:45 UTC, AGLIU123 commented
@isvargasmsft I have made some changes based on the comments, and wondering could you help to review the PR please? Thank you in advance!

2022-11-17 14:04 UTC, opbld30 commented
Learn Build status updates of commit _[acc6c88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acc6c88d9cf7e796e9cc477995f6dbf388705a64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211171355024788-16857/BuildReport?accessString=b7d3837f30055e681db64de5125df303a3a1998416d4c49468d4837adb9d973c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 14:05 UTC, isvargasmsft commented on api-reference/beta/resources/chatmessage.md
> +|[Unset reaction to a message in channel](../api/chatmessage-unsetreaction.md)|None| Unset reaction to a message in a channel.|
@AGLIU123 I noticed the Methods table of this resource has wrong values in the return types in both the beta and v1 documents. The methods Update, Delete, Undo deletetion, set reaccion and unset reaccion, doesn't return a response body, hence the correct value should be "None".

I made these 4 changes for visibility but, could you please open a PR to fix this for both beta and v1?

2022-11-17 14:05 UTC, isvargasmsft commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "CreatedDateTime": "2022-10-20T22:13:37.3506829Z",
```suggestion
          "CreatedDateTime": "2022-11-17T22:13:37.3506829Z",
```

2022-11-17 14:07 UTC, isvargasmsft approved these changes
Hello @AGLIU123, 

I noticed the Methods table of the chatMessage resource has wrong values in the return types in both the beta and v1 documents. The methods Update, Delete, Undo deletion, set reaccion and unset reaccion, doesn't return a response body, hence the correct value should be "None".

I made these 4 changes for visibility but, could you please open a PR to fix this for both beta and v1?

2022-11-17 14:20 UTC, opbld33 commented
Learn Build status updates of commit _[277c3c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/277c3c61276eb9fe50b9489e0d1c2a7011303a63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211171402303553-16857/BuildReport?accessString=fc17e458940489799d2e53c0ba6d0718d5b1e1daa59b6c1a9b8c17884b932607).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-17 16:10 UTC, opbld30 commented
Learn Build status updates of commit _[e69b235](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e69b2350150413a60e070bfd2aef12b6caa7666f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211171607546369-16857/BuildReport?accessString=c97eb66456727ceb773618c2f82d9e7ea924e46d6ef3adea06db66d5a955f023).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-18 00:37 UTC, Lauragra commented on api-reference/beta/resources/chatmessage.md
> +|messageHistory|[chatMessageHistoryItem](../resources/chatmessagehistoryitem.md) collection|List of message edition history, including modification time, actions for the message (like reactionAdded a
What do we mean by "message edition"? Would an accurate revision here be:

The activity history of a message item, including modification time and actions, such as **reactionAdded**, **reactionRemoved**), or reaction changes, on the message.

2022-11-18 00:38 UTC, Lauragra commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +Represents the edition history of a message in a chat or a channel.
Do messages have "editions", or can the description here simply be "Represents activity history information for a message in a chat or a channel."

2022-11-18 00:39 UTC, Lauragra commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +|actions|chatMessageActions|The message edition action.The possible values are: `reactionAdded`, `reactionRemoved`, `actionUndefined`, `unknownFutureValue`.|
Same question here about the use of "edition". Also please add the missing space after the period.

2022-11-18 00:40 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
I don't think this subarea is accurate; this is general to chat messages, right? Not specific to Shifts. So we can leave SubArea blank.

2022-11-18 00:40 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the `messageHistory` property to the [chatMessage](https://learn.microsoft.com/en-us/graph/api/resources/chatMessage?view=graph-rest-beta) resource.",
Please format property names as bold instead of inline code.

2022-11-23 16:57 UTC, isvargasmsft commented
Hi @AGLIU123, 

Please address Laura's comments and add the label "ready to merge" when complete.

2022-11-29 19:49 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessage.md
> +|messageHistory|[chatMessageHistoryItem](../resources/chatmessagehistoryitem.md) collection|List of message edition history, including modification time, actions for the message (like reactionAdded a
Thank you for the suggestion, and changed. :)

2022-11-29 19:51 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +Represents the edition history of a message in a chat or a channel.
The "edition" here means "modification", but in case confusion, I have changed it to "activity history".

2022-11-29 19:51 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessagehistoryitem.md
> +|actions|chatMessageActions|The message edition action.The possible values are: `reactionAdded`, `reactionRemoved`, `actionUndefined`, `unknownFutureValue`.|
Thanks for the comment and I just changed.

2022-11-29 19:52 UTC, opbld31 commented
Learn Build status updates of commit _[b3f49d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3f49d32a03e76006e09e47125e78d6ac2814078)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211291942019887-16857/BuildReport?accessString=a2804a921f60bc145dcde823be6b959fdcc3665b09605aac7cc7fe23675b5b9b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-29 19:52 UTC, AGLIU123 commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
Changed it to blank.

2022-11-29 19:53 UTC, AGLIU123 commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the `messageHistory` property to the [chatMessage](https://learn.microsoft.com/en-us/graph/api/resources/chatMessage?view=graph-rest-beta) resource.",
Changed to bold.

2022-11-29 19:57 UTC, AGLIU123 commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
Changed to blank.

2022-11-29 20:54 UTC, AGLIU123 commented
Hi @Lauragra, @isvargasmsft, thank you for the comments and suggestions. I have just made some changes and wondering could you help to review them please? Thanks!

2022-11-29 20:57 UTC, AGLIU123 commented on api-reference/beta/resources/chatmessage.md
> +|[Unset reaction to a message in channel](../api/chatmessage-unsetreaction.md)|None| Unset reaction to a message in a channel.|
Hi @isvargasmsft, thanks for the comments, I'll check with the owners of the files above and either them or me will change the files.

2022-12-01 03:13 UTC, opbld32 commented
Learn Build status updates of commit _[4b409e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b409e8e36a70e3bfb66f08656785ce60bbaac2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehistoryitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/chatmessagehistoryitem.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chatmessagehistoryitem?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-16857) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-11-export-api-add-message-history-support/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202212010310475305-16857/BuildReport?accessString=0f6e9aba3024f21fd117a0a23bab07ee945709f7d9729490bc7f2c7e86bcb843).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-01 03:15 UTC, merged