Updates to language tags and example requests
microsoftgraph/microsoft-graph-docs pull request #16873
Opened 2022-05-12 18:11 UTC by jakeost-msft

2022-05-12 18:13 UTC, opbld31 commented
Docs Build status updates of commit _[aabdf9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aabdf9a3c34b961f22d588aa1a1b4f31c2949e8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-bookmark?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-qna?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205121811099545-16873/BuildReport?accessString=accd3cfd69034ef5b44c0a4bb8aca7ec52b1051490c5caa2b97192546fd83087).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-13 20:42 UTC, angelgolfer-ms reviewed
Hi @jakeost-msft , was there a specific reason you decided to use lower case for the region subtag?
The [overview](https://docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview) topic refers to RFC 4646. I suppose initially you're following the recommendations of [Section 2.1](https://docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview), which states even though these tag and subtag values are to be treated as case insensitive, the recommendation is consistent case formatting to help users in general. For that purpose and this recommendation - "all non-initial two-letter subtags are uppercase" - your initial treatment is appropriate.
Can you please clarify before I close on this PR?

2022-05-13 21:00 UTC, jakeost-msft commented
> Hi @jakeost-msft , was there a specific reason you decided to use lower case for the region subtag? The [overview](https://docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview) topic refers to RFC 4646. I suppose initially you're following the recommendations of [Section 2.1](https://docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview), which states even though these tag and subtag values are to be treated as case insensitive, the recommendation is to apply consistent case formatting (consistent with RFC 4646 recommendations) to help users in general. For that purpose and the RFC recommendation - "all non-initial two-letter subtags are uppercase" - your initial treatment is appropriate. Can you please clarify before I close on this PR?

@angelgolfer-ms 
Yes, the reason for the change is because we are actually dependent on this formatting: [BingSupportedMarkets](https://office.visualstudio.com/OC/_search?action=contents&text=BingSupportedMarkets&type=code&lp=code-Project&filters=ProjectFilters%7BOC%7DRepositoryFilters%7BM365AdminServices%7D&pageSize=25&result=DefaultCollection/OC/M365AdminServices/GBmain//src/M365AdminServices/SearchSettingsService/Validation/ValidationConstants.cs)

I'm not sure if that is public facing or if we should change the wording regarding RFC 4646. I would appreciate any insight you can provide. Thanks!

2022-05-14 02:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-bookmark.md
> +|languageTags|String collection|A list of language names that are geographically specific and that this bookmark can be viewed in. Each language tag value follows the pattern {language}-{REGION}. As
Line 41:
If you must require lower case for a region value, then please change {language}-{REGION} to {language}-{region}.

2022-05-14 02:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-qna.md
> +|languageTags|String collection|A list of language names that are geographically specific and that this QnA can be viewed in. Each language tag value follows the pattern {language}-{REGION}. As an ex
Line 40:
If you must require lower case for a region value, then please change {language}-{REGION} to {language}-{region}.

2022-05-14 02:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-api-answers-overview.md
Please see my message on Teams.

For line 28:
If you must require lower case for a region value, then please change the last sentence in line 28 to:
"For information on the supported values for {language} and {region}, see [RFC 4646](https://datatracker.ietf.org/doc/html/rfc4646)."

Then add the following in a separate paragraph:
"Note You must specify values for {language} and {region} in lower case."

2022-05-14 02:16 UTC, angelgolfer-ms requested changes
For interoperability based on RFC 4646, the best approach is to remove the requirement that the region subtag must be in lower case. After all, RFC 4646 states tags and subtags are case-insensitive.
If there are reasons you can't remove that requirement, then please see the comments I just added for additional changes in the docs.

2022-05-16 21:45 UTC, opbld31 commented
Docs Build status updates of commit _[e27714c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e27714ca4948b5411e98702fbe014870bab7f3f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-bookmark?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-qna?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205162143017732-16873/BuildReport?accessString=1811cb458acdf164ad0a8db71b2714f73dbe53d866ef1bdbc30a7f1a901d74bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 00:05 UTC, opbld33 commented
Docs Build status updates of commit _[dd1512c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd1512cce88ff5e8d1f3073d957a6cec3f9ef05c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-bookmark?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |
[api-reference/beta/resources/search-qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-qna?view=graph-rest-beta&branch=pr-en-us-16873) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190003058018-16873/BuildReport?accessString=2fbd6d1870901f69ea089deaaf1a79abb1151f8012d17e3292cc6e7d1080dfcf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 00:49 UTC, angelgolfer-ms approved these changes
Hi @jakeost-msft , I made an extra change to format the note in the API overview topic for effectiveness. I think this PR is good to be published. Please confirm so and set the label to ready to merge.

2022-05-20 03:29 UTC, merged