[M365 Lighthouse] - Audit events update
microsoftgraph/microsoft-graph-docs pull request #16896
Opened 2022-05-14 14:27 UTC by idwilliams

Correcting the HTTP request example for requesting a single audit event.

2022-05-14 14:29 UTC, opbld32 commented
Docs Build status updates of commit _[d92c0e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d92c0e7b491b3527b9bd38c8b24cdc083a91d2ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-auditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-auditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-auditevent-get?view=graph-rest-beta&branch=pr-en-us-16896) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205141427507959-16896/BuildReport?accessString=bdb57029794ebe7e998b0ee79241ab76824da4c04ac204d850f4844086f02616).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-18 03:55 UTC, isvargasmsft commented on api-reference/beta/api/managedtenants-auditevent-get.md
>  ```
Checking at the issue, the correction was due in line 62. Could you please clarify the change in the HTTP request?

2022-05-18 03:56 UTC, isvargasmsft requested changes
Please clarify the HTTP request change. According to the issue the correction was due in the example.

2022-06-01 17:35 UTC, isvargasmsft commented
Hello @idwilliams, 

What's the status of this PR? Please let me know if you have questions about my comments above.

Here to help!

2022-07-28 16:10 UTC, lramosvea commented
@idwilliams just a heads up on this PR so we can close https://github.com/microsoftgraph/microsoft-graph-docs/issues/16132. Thanks.

2022-08-03 13:37 UTC, idwilliams commented
@isvargasmsft the HTTP request was updated because the incorrect URI was used when the article was first published. All functionality for Microsoft 365 Lighthouse, should be prefixed with `/tenantRelationships/managedTenants`. So, this change is correct the URI to match what is available through the schema. Please let me know if you have any concerns or questions.

2022-08-03 13:39 UTC, idwilliams commented on api-reference/beta/api/managedtenants-auditevent-get.md
>  ```
Apologizes for the delay on this, the address in the documentation was incorrect. This update is to have it match what is available through the schema. Below I shared an additional comment with more context.

2022-08-03 13:40 UTC, opbld34 commented
Docs Build status updates of commit _[aada86d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aada86dc63437458ee8ef5e32dcf84e696a3f21f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-auditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/audit-events-update/api-reference/beta/api/managedtenants-auditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-auditevent-get?view=graph-rest-beta&branch=pr-en-us-16896) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031338045277-16896/BuildReport?accessString=ccc204f843c6ebd232698ff0f47a70e7b71b80619510dab37ad31e2584a7c797).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 16:31 UTC, isvargasmsft commented
> @isvargasmsft the HTTP request was updated because the incorrect URI was used when the article was first published. All functionality for Microsoft 365 Lighthouse, should be prefixed with `/tenantRelationships/managedTenants`. So, this change is correct the URI to match what is available through the schema. Please let me know if you have any concerns or questions.
> 
> To my knowledge the samples are automatically generated by tooling the team has in place. So, I did not update the sample only the HTTP request because as I understand it the sample will be corrected next time the tooling updates the samples.

Thank you very much for the clarification, @idwilliams. Regarding the examples, the tool generates the code snippets using the http URL in the example. Please update the http code blocks in the examples with the correct URL.

2022-08-03 16:37 UTC, isvargasmsft approved these changes

2022-08-03 16:38 UTC, opbld30 commented
Docs Build status updates of commit _[ff04218](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff0421888f8d54bcec7b8197c9d1e4b3d74d674d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-auditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/audit-events-update/api-reference/beta/api/managedtenants-auditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-auditevent-get?view=graph-rest-beta&branch=pr-en-us-16896) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031636292286-16896/BuildReport?accessString=5ef1f25ac525d19cadf8ed174bc6332220e4f12359fc361d9978c91ad0387f8a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 03:41 UTC, merged