Merge TAP Beta to V1.0
microsoftgraph/microsoft-graph-docs pull request #16909
Opened 2022-05-16 15:37 UTC by tilarso

updating docs to reflect TAP release from Beta to V1.0

2022-05-16 15:39 UTC, opbld30 commented
Docs Build status updates of commit _[161c0b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/161c0b9de1427e4e148a7e595e057632c6a78545)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-e7700780)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/tempor [...]

2022-05-19 20:49 UTC, opbld32 commented
Docs Build status updates of commit _[92f5b71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92f5b718fb32da7f8616530f5220b1422e1f390a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-5dfbc0c6)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodc [...]

2022-05-23 18:51 UTC, opbld32 commented
Docs Build status updates of commit _[bddef09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bddef0914e06d7e10c4e2a7a5c2be177851919a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-e6e05a73)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodc [...]

2022-06-01 21:09 UTC, opbld32 commented
Docs Build status updates of commit _[4fd2f2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fd2f2a6533b7a9c5e5a6bd0308ae1cbaee6277f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6ce95e70)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodc [...]

2022-06-01 21:11 UTC, opbld34 commented
Docs Build status updates of commit _[e04960f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e04960fd585e6ed9a5b666facddfa485612ada56)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-a7e24def)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-a7e24def"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 5016, Column 10**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206012107569827-16909/BuildReport?accessString=564e9f22a8053e2876ad144dca0d3314d6a321b36420c83bfe7279f215e1696a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 21:17 UTC, opbld30 commented
Docs Build status updates of commit _[499a6d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/499a6d53e441f4ace026f6bd6a5ed1bc84144bfa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1183046a)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-1183046a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 5016, Column 10**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206012108556425-16909/BuildReport?accessString=beaee707cafecd0dcd183daa50e6b6196e439afbe59b626e994474fa425f812d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 21:20 UTC, opbld32 commented
Docs Build status updates of commit _[e169341](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e16934151128a074d7a963c60e3659e6707485d6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d6e8a803)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-d6e8a803"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 5016, Column 10**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206012111564495-16909/BuildReport?accessString=828a1b47f5131cf9e605435906e414f50ee8268de0a6bd9656272b08b2fa3f52).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 21:22 UTC, opbld30 commented
Docs Build status updates of commit _[db17447](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db17447c9fa567ad72de4baa4869939a19fce71b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-97de333d)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodc [...]

2022-06-02 15:05 UTC, opbld33 commented
Docs Build status updates of commit _[973711b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/973711b913272c046426274fe2612274c4b2ed2e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0beb4285)
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :warning:Warning | | [Details](#user-content-b4baef261d747d033aceb1433893a08e-0beb4285)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-0beb4285"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 5016, Column 10**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="b4baef261d747d033aceb1433893a08e-0beb4285"></a>
### [api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md)
 - **Line 20, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authentication-list-temporaryaccesspassmethods.md'.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authentication-post-temporaryaccesspassmethods.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206021503317306-16909/BuildReport?accessString=58c32edab815f941448ced109907d6a2d279dc1b565d6f11821cdc4897c4c47e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 15:59 UTC, opbld34 commented
Docs Build status updates of commit _[fe08847](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe08847681b894877693bfa8ab750bb9f1bb5780)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-a70edbd4)
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :warning:Warning | | [Details](#user-content-a7f16ce9d33b775e3f8904232fc8408f-a70edbd4)
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :warning:Warning | | [Details](#user-content-b4baef261d747d033aceb1433893a08e-a70edbd4)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-a70edbd4"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 5016, Column 10**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="a7f16ce9d33b775e3f8904232fc8408f-a70edbd4"></a>
### [api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md)
 - **Line 74, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="b4baef261d747d033aceb1433893a08e-a70edbd4"></a>
### [api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md)
 - **Line 20, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authentication-list-temporaryaccesspassmethods.md'.`````
 - **Line 21, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authentication-post-temporaryaccesspassmethods.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206021557490082-16909/BuildReport?accessString=f06ff04080d6cbcf1c00e5fed2e29e2d68536c691de5c592e8b6d13fbd4a8902).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 16:45 UTC, tilarso commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +```
Got it. Will fix in the v1.0 doc.

2022-06-02 17:37 UTC, opbld30 commented
Docs Build status updates of commit _[9a74f63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a74f63ac507b7c1a7407c1fd6c37da0e59191f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-65973807e06e70d16ec407ed01f66ad8-261bae49)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodc [...]

2022-06-02 17:53 UTC, opbld32 commented
Docs Build status updates of commit _[1b76c29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b76c29544a09d344033d650db6abe0fc5df53a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-65973807e06e70d16ec407ed01f66ad8-38e37116)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-ove [...]

2022-06-03 17:20 UTC, FaithOmbongi requested changes
Hi @tilarso, Requested some minor fixes here and there, pointed out some that relate to the [API Doctor errors](https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=85081&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=24691) logged against your PR.

I've also pushed a commit to fix some sections in the GET policy and LIST method `beta` docs. I couldn't leave a comment in those sections.

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md
> +**Note:** The response object shown here might be shortened for readability.
```suggestion
>**Note:** The response object shown here might be shortened for readability.
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +### Response
```suggestion
## Response
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +**Note:** The response object shown here might be shortened for readability.
```suggestion
>**Note:** The response object shown here might be shortened for readability.
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +{
The spacing's important. Will auto-resolve 1 API Doctor error
```suggestion

{
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/resources/temporaryaccesspassauthenticationmethod.md
> +|lifetimeInMinutes|Int32|The lifetime of the Temporary Access Pass in minutes starting at startDateTime. Must be between 10 and 43200 inclusive (equivalent to 30 days).|
```suggestion
|lifetimeInMinutes|Int32|The lifetime of the Temporary Access Pass in minutes starting at **startDateTime**. Must be between 10 and 43200 inclusive (equivalent to 30 days).|
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md
> +|startDateTime|DateTimeOffset|Optional. The date and time when the temporaryAccessPass becomes available to use. If not specified, the Temporary Access Pass is available to use immediately after it's
Link fixes, will auto-resolve 2 API Doctor errors
```suggestion
|isUsableOnce|Boolean|Optional. Determines if the pass is limited to a one-time use. If `true`, the pass can be used once; if `false`, the pass can be used multiple times within its **lifetimeInMinutes** setting. A multi-use Temporary Access Pass (`isUsableOnce = false`), can only be created and used for sign-in if it is allowed by the  [Temporary Access Pass authentication method policy](../resources/temporaryaccesspassauthenticationmethodconfiguration.md).|
|lifetimeInMinutes|Int32|Optional. The lifetime of the temporaryAccessPass in minutes starting at creation time or at startDateTime, if set. Must be between 10 and 43200 (equivalent to 30 days). If not specified, the **defaultLifetimeInMinutes** setting in the [Temporary Access Pass authentication method policy](../resources/temporaryaccesspassauthenticationmethodconfiguration.md) is applied. |
|startDateTime|DateTimeOffset|Optional. The date and time when the temporaryAccessPass becomes available to use. If not specified, the Temporary Access Pass is available to use immediately after it's created.| 
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/temporaryAccessPass
Missing method. Will auto-resolve API Doctor error
```suggestion
GET https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/temporaryAccessPass
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +Content-Type: application/json
Missing protocol info
```suggestion
HTTP/1.1 200 OK
Content-Type: application/json
```

2022-06-03 17:20 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +```http
Missing HTML comment block - will auto-resolve 1 API Doctor error
```suggestion
<!-- {
  "blockType": "response",
  "truncated": true,
  "@odata.type": "microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration"
}
-->
```http
```

2022-06-03 17:24 UTC, opbld30 commented
Docs Build status updates of commit _[ff0c263](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff0c2633ad93aea337049e672742b36452e83904)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-65973807e06e70d16ec407ed01f66ad8-b064ae71)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationme [...]

2022-06-03 17:36 UTC, opbld33 commented
Docs Build status updates of commit _[e74e143](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e74e143243090e3dcaef97f8360a6fa7581241b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) | [Details](#user-content-65973807e06e70d16ec407ed01f66ad8-12123e62)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationme [...]

2022-06-08 07:34 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +PATCH https://graph.microsoft.com/v1.0/temporaryAccessPassAuthenticationMethodConfiguration
Hi @tilarso - This line could be the cause of the [API doctor error](https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=85415&view=logs&j=92a4755a-6173-591e-5c07-8dbe1165e937&t=c54bce61-9f10-5a6f-8d73-72139541958d&s=d654deb9-056d-50a2-1717-90c08683d50a).
```suggestion
PATCH https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/temporaryAccessPass
```

2022-06-08 15:04 UTC, opbld30 commented
Docs Build status updates of commit _[30e0c45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30e0c45dfb7a281690dce84f3b6fa172ab4a5f8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/mic [...]

2022-06-08 17:54 UTC, FaithOmbongi approved these changes
Hi @tilarso, I've left 2 additional suggestions to close minor gaps. Approved with suggestions.

2022-06-08 17:54 UTC, FaithOmbongi commented on api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +All properties of the object can be updated. For a list of properties, see [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md)
```suggestion
All properties and relationships of the object can be updated. For the list of properties and relationships, see [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md).
``

2022-06-09 02:22 UTC, opbld31 commented
Docs Build status updates of commit _[670133b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/670133b7bc5dc1cb8477acb9d211c41266b4c44f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethod-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-post?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-16909) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-post-temporaryaccesspassmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-post-temporaryaccesspassmethods?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/origin/tilarso-tap-v1/api-reference/v1.0/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-16909) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/mic [...]

2022-06-09 03:00 UTC, merged