[Window365] add new property in ANC payload
microsoftgraph/microsoft-graph-docs pull request #16976
Opened 2022-05-19 09:38 UTC by Sodaine

Roadmap workitem number: 14200

2022-05-19 10:04 UTC, AshleyYangSZ commented
@Sodaine Please include change-log in the PR.

2022-05-27 05:40 UTC, opbld31 commented
Docs Build status updates of commit _[98d3dd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98d3dd1f9ddc2896d69a8d768c4a0c23616e5b54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16976) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205270531241788-16976/BuildReport?accessString=d7630f47b3ef92f15d7b185f5a2941a53a0f96c78dc0035049da837f903b846f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-27 07:56 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +  "alternateResourceUrl": "string"
If this property returned by default, then you'd better add it to the related API examples.

2022-05-31 03:33 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|alternateResourceUrl|String|The interface URL of the partner service's resource that links to this on-premises connection. Returned only on `$select`.
I remember we already rename on-premises connection to Azure network connection right? So maybe here you cannot use the old naming on-premises. Please help update. Thanks!

2022-05-31 03:35 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +  "alternateResourceUrl": "string"
In the description, this property will only be returned with $select.

2022-05-31 03:37 UTC, RuiHou105 requested changes
@Sodaine  please help resolve comments in this PR. Thanks!

2022-05-31 03:55 UTC, Sodaine commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|alternateResourceUrl|String|The interface URL of the partner service's resource that links to this on-premises connection. Returned only on `$select`.
Thanks for catching it, updated!

2022-05-31 03:58 UTC, opbld31 commented
Docs Build status updates of commit _[2c949e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c949e072ddcaa867d3e826d8b84f9762b27f1de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16976) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-19-jiellia/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205310354362223-16976/BuildReport?accessString=31ca73ef1c41aed907e51878409a927a88f3749125e0b7c481ba029143491aff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-31 06:15 UTC, RuiHou105 approved these changes

2022-05-31 06:16 UTC, RuiHou105 commented
@Lauragra  @JarbasHorst , could you help review this PR when you got time? Thanks ahead :)

2022-05-31 18:33 UTC, Lauragra commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|alternateResourceUrl|String|The interface URL of the partner service's resource that links to this Azure network connection. Returned only on `$select`.
FYI, we list the properties in alphabetical order in the properties tables and in the JSON representation. Please alphabetize the properties here, and also be sure to add the missing | to the end of this table row. Currently the table is scrolling on the review site and I'm not sure why but let's see if that's the fix.

2022-05-31 18:34 UTC, Lauragra commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +  "alternateResourceUrl": "string"
Alphabetize the properties here, too.

2022-06-02 08:28 UTC, Sodaine commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|alternateResourceUrl|String|The interface URL of the partner service's resource that links to this Azure network connection. Returned only on `$select`.
updated

2022-06-02 08:29 UTC, opbld30 commented
Docs Build status updates of commit _[db950d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db950d176b0b97b13444fbfbb0aaa31c5a6b28b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16976) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-19-jiellia/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206020827051858-16976/BuildReport?accessString=89a66cb982dc870fbe2cda5e027b19f9d2c6935cfac19b3755538c23290752bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 22:45 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [17133](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17133) into this branch to include my final edits.

2022-06-03 03:50 UTC, opbld31 commented
Docs Build status updates of commit _[f5883b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5883b2e2523fc7e5af003fce5da49bb74871bea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16976) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-19-jiellia/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206030347441253-16976/BuildReport?accessString=48fa8dfdb4fd13285323b1afbdfb390e9fdea505798558cf62003ec50743053f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 03:25 UTC, Lauragra approved these changes

2022-06-20 07:25 UTC, RuiHou105 commented
Hi @Lauragra  as the graph schema went alive last week, now let's merge this PR. Thanks !

2022-06-20 23:44 UTC, opbld30 commented
Docs Build status updates of commit _[34ce3d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34ce3d0289d3b70515e5c605ec95360df140dd30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-16976) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2022-05-19-jiellia/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206202341394587-16976/BuildReport?accessString=6948ce931d7c3203784f29c92906e4691a6757b1ca842664473be06911038b2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 02:29 UTC, merged