Update add channel members graph documentation to display maximum bul…
microsoftgraph/microsoft-graph-docs pull request #16972
Opened 2022-05-19 06:10 UTC by kallu800

Update add channel members graph documentation to display maximum bulk membership size

2022-05-19 06:13 UTC, opbld30 commented
Docs Build status updates of commit _[e3c0dfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3c0dfd6325feacb3bfdf865b93e4e4ced6df198)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) | [Details](#user-content-085f4daef5dc63d70e26b30829c4bb30-d1b56b48)
[api-reference/beta/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) |

<a id="085f4daef5dc63d70e26b30829c4bb30-d1b56b48"></a>
### [api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md)
 - **Line 129, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190610368722-16972/BuildReport?accessString=741cf61ba4b89b0d1c1162b57b5fc45288e24560252a8191d27966406d317e6e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 07:15 UTC, opbld32 commented
Docs Build status updates of commit _[d319b0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d319b0b4a6abebef1551a7dc71145a9286f207cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) | [Details](#user-content-085f4daef5dc63d70e26b30829c4bb30-989cb7b2)
[api-reference/beta/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) |

<a id="085f4daef5dc63d70e26b30829c4bb30-989cb7b2"></a>
### [api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md)
 - **Line 129, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205190713329356-16972/BuildReport?accessString=46775b5265924a9b26f25e1c904b76b56a415f5105486116fb20cec21d584530).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 07:43 UTC, akhilkohlimicrosoft approved these changes

2022-05-19 12:04 UTC, shantanu1singh commented on api-reference/beta/resources/channel.md
> +|[Add channel member](../api/channel-post-members.md) | [conversationMember](conversationmember.md) | Add a member to a channel. Only supported for channels with a **membershipType** of `private` or
I don't think we should include the limit in this list. The primary API reference doc is sufficient.

2022-05-19 12:04 UTC, shantanu1singh commented on api-reference/v1.0/resources/channel.md
> +|[Add channel member](../api/channel-post-members.md) | [conversationMember](conversationmember.md) | Add a member to a channel. Only supported for `channel` with membershipType of `private`. A maxim
I don't think we should include the limit in this list. The primary API reference doc is sufficient.

2022-05-19 12:05 UTC, shantanu1singh commented on concepts/known-issues.md
> +A maximum of 200 members per request can be added to a channel.
Let's specify that it's only for private channels and give a link to the main API reference doc here as well.

2022-05-19 12:05 UTC, shantanu1singh commented on concepts/known-issues.md
> +A maximum of 200 members per request can be added to a channel.
Main/primary API reference doc being 'channel-post-members.md'

2022-05-19 12:06 UTC, shantanu1singh commented on api-reference/v1.0/api/channel-post-members.md
> +Add a [conversationMember](../resources/conversationmember.md) to a [channel](../resources/channel.md). This operation is allowed only for channels with a **membershipType** value of `private`. A max
Is the 200 limit only per request or private channels in *total* can only support 200 members?

2022-05-20 03:31 UTC, Lauragra commented
@kallu800 , please address the review feedback before you set the **ready to merge** label.

2022-05-20 05:43 UTC, opbld31 commented
Docs Build status updates of commit _[57e5f90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57e5f901117e431e2fe1773b7a838e15f75c243a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) | [Details](#user-content-085f4daef5dc63d70e26b30829c4bb30-45f0c232)
[api-reference/beta/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) |

<a id="085f4daef5dc63d70e26b30829c4bb30-45f0c232"></a>
### [api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md)
 - **Line 129, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205200540595193-16972/BuildReport?accessString=273ce192fbdae257906e862093a09dca6a1c3e4445bf688dadcd93ebecefc858).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 06:47 UTC, shantanu1singh commented on api-reference/beta/resources/channel.md
> +|[Add channel member](../api/channel-post-members.md) | [conversationMember](conversationmember.md) | Add a member to a channel. Only supported for channels with a **membershipType** of `private` or
Please restore the closing |  at the end.

2022-05-20 06:47 UTC, shantanu1singh commented on api-reference/v1.0/resources/channel.md
> +|[Add channel member](../api/channel-post-members.md) | [conversationMember](conversationmember.md) | Add a member to a channel. Only supported for `channel` with membershipType of `private`.
Please restore the closing |  at the end.

2022-05-20 06:51 UTC, shantanu1singh commented on api-reference/beta/api/channel-post-members.md
> +Add a [conversationMember](../resources/conversationmember.md) to a [channel](../resources/channel.md). This operation is allowed only for channels with a **membershipType** value of `private` or `sh
Is the limit only for private channels or shared channels too? Please clarify that here

2022-05-20 06:53 UTC, shantanu1singh commented on concepts/known-issues.md
> +A maximum of 200 members per request can be added to a private channel. Here is the link to the api reference doc : (/microsoft-graph-docs/api-reference/v1.0/api/channel-post-members.md) and (/micros
would recommend rewording to '...added to a private channel through the `POST /teams/{team-id}/channels/{channel-id}/members` request.'

I'll let @Lauragra or @isvargasmsft recommend the right framing.

2022-05-22 00:29 UTC, Lauragra commented on concepts/known-issues.md
> +A maximum of 200 members per request can be added to a private channel. Here is the link to the api reference doc : (/microsoft-graph-docs/api-reference/v1.0/api/channel-post-members.md) and (/micros
Revise the second sentence as:
For details, see [Add member to channel](/microsoft-graph-docs/api-reference/v1.0/api/channel-post-members).

2022-06-02 06:27 UTC, opbld32 commented
Docs Build status updates of commit _[ed4f406](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed4f406621c5f0dce9510424e55225058dcc3bed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) | [Details](#user-content-6c926f283a8c992067a0533675d12e17-9dd12e79)
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |

<a id="6c926f283a8c992067a0533675d12e17-9dd12e79"></a>
### [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md)
 - **Line 406, Column 142**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'channel-post.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206020625003718-16972/BuildReport?accessString=31618203e53c9142200cf975c982e2c33fa2143ecdd6b2f64a408c5e1c89d182).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 06:30 UTC, opbld32 commented
Docs Build status updates of commit _[d96f678](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d96f678e36cd81439bb2d19214c55233a2a5495e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) | [Details](#user-content-6c926f283a8c992067a0533675d12e17-c0b03cdb)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |

<a id="6c926f283a8c992067a0533675d12e17-c0b03cdb"></a>
### [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md)
 - **Line 406, Column 142**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'channel-post.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206020627420327-16972/BuildReport?accessString=65841276c05c36b2d5b7e5a8297bc16625fcd20ec6ddf7e413efcea55cdfc307).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 08:53 UTC, akhilkohlimicrosoft requested changes

2022-06-02 11:51 UTC, shantanu1singh requested changes

2022-06-02 11:51 UTC, shantanu1singh commented on concepts/known-issues.md
> +A maximum of 200 members can be added while creating a private channel through the POST /teams/{team-id}/channels request.. For details, see [Create Channel](channel-post.md).
Extra period after request

2022-06-02 11:51 UTC, shantanu1singh commented on concepts/known-issues.md
> +A maximum of 200 members can be added while creating a private channel through the POST /teams/{team-id}/channels request.. For details, see [Create Channel](channel-post.md).
enclose POST /teams/{team-id}/channels between ``.

`POST /teams/{team-id}/channels`

2022-06-02 11:51 UTC, shantanu1singh commented on concepts/known-issues.md
> +### Unable to add 200+ members while creating a private channel
maybe rephrase to 'Unable to add more than 200 members while creating a private channel' ?

2022-06-02 11:51 UTC, shantanu1singh commented on api-reference/beta/api/channel-post.md
> +Create a new [channel](../resources/channel.md) in a team, as specified in the request body. A maximum of 200 members can be added while creating a private channel.
Can we add this as a callout Note instead. Example:

> **Note:** The `$top` OData query parameter has a limit of 1000 alerts. We recommend that you include only `$top` and not `$skip` in your first GET query. You can use `@odata.nextLink` for pagination. If you need to use `$skip`, it has a limit of 500 alerts. For example, `/security/alerts?$top=10&$skip=500` will return a `200 OK` response code, but `/security/alerts?$top=10&$skip=501` will return a `400 Bad Request` response code. For more information, see [Microsoft Graph Security API error responses](../resources/security-error-codes.md).

2022-06-02 11:51 UTC, shantanu1singh commented on api-reference/beta/api/channel-post.md
> +Create a new [channel](../resources/channel.md) in a team, as specified in the request body. A maximum of 200 members can be added while creating a private channel.
You can refer to this on how to add that: https://github.com/microsoftgraph/microsoft-graph-docs/blob/d96f678e36cd81439bb2d19214c55233a2a5495e/api-reference/beta/api/alert-list.md

2022-06-03 04:31 UTC, opbld32 commented
Docs Build status updates of commit _[c8bb26a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8bb26a6086db7836a0df30bdc3bc73d28ac5499)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) | [Details](#user-content-6c926f283a8c992067a0533675d12e17-8b10f273)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |

<a id="6c926f283a8c992067a0533675d12e17-8b10f273"></a>
### [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md)
 - **Line 406, Column 143**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'channel-post.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206030428131845-16972/BuildReport?accessString=56dfe3b92006623a6cae0d8218520900d4c1d6eb61d13e238a7e3176b53ca891).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 05:01 UTC, akhilkohlimicrosoft approved these changes

2022-06-03 10:15 UTC, shantanu1singh commented on concepts/known-issues.md
> +A maximum of 200 members can be added while creating a private channel through the "POST /teams/{team-id}/channels" request. For details, see [Create Channel](channel-post.md).
Instead of the " character, use backticks ` to enclose POST /teams/...channels. That way you'll get the correct formatting

2022-06-03 10:16 UTC, shantanu1singh approved these changes
Left one minor comment. LGTM otherwise.

@Lauragra @isvargasmsft can either of you help review too?

2022-06-03 12:02 UTC, opbld34 commented
Docs Build status updates of commit _[5dfc78f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dfc78f1bfe22adde471d13fcfcd2454ba3abd93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-16972) | [Details](#user-content-6c926f283a8c992067a0533675d12e17-4ae65b8f)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |

<a id="6c926f283a8c992067a0533675d12e17-4ae65b8f"></a>
### [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md)
 - **Line 406, Column 143**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'channel-post.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206031200522305-16972/BuildReport?accessString=fdcab2844e2b94db62ebd8df139a75e0828155ccf89772cc8019c7297b571ed2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 13:23 UTC, akhilkohlimicrosoft approved these changes

2022-06-03 16:00 UTC, Lauragra commented on api-reference/beta/api/channel-post.md
> +> **Note:** A maximum of 200 members can be added while creating a private channel.
Suggested revision to the note text: "A private channel can have a maximum of 200 members."

Does this API also create channels that aren't private, and if so, is there a maximum number of members?

2022-06-03 16:01 UTC, Lauragra commented on concepts/known-issues.md
> +### Unable to add more than 200 members while creating a private channel
Suggested revision to the heading to be more clear/concise: Unable to add more than 200 members to a private channel

2022-06-06 09:03 UTC, kallu800 commented on api-reference/beta/api/channel-post.md
> +> **Note:** A maximum of 200 members can be added while creating a private channel.
So, at the creation of a private channel, you can add only upto 200 members in a request. A private channel can have a max of 200 members would be wrong as members can be added later using the AddMember api.

We checked this limit only for private channel.

2022-06-06 09:04 UTC, kallu800 commented on concepts/known-issues.md
> +A maximum of 200 members can be added while creating a private channel through the `POST /teams/{team-id}/channels` request. For details, see [Create Channel](channel-post.md).
Sure, I will remove my changes from this file.

2022-06-06 09:43 UTC, opbld31 commented
Docs Build status updates of commit _[23b61b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23b61b4c9871d63f1ea35a6afef77a7ea5cd2f93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206060941261994-16972/BuildReport?accessString=3a9a8ba2f4625ab0ab1fb72cf1bdecc447deb2f033fe6931f45818d8397f5985).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 02:39 UTC, Lauragra commented on api-reference/beta/api/channel-post.md
> +> **Note:** A maximum of 200 members can be added while creating a private channel.
Okay, suggested revision: "You can add a maximum of 200 members when you create a private channel."

2022-06-08 05:43 UTC, opbld30 commented
Docs Build status updates of commit _[e76f502](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e76f50246c568a1c010e9cd9159eb39a8bc65ccb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-16972) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-16972) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206080540547455-16972/BuildReport?accessString=c442e20b592addbebb9b037892b01dca2b158cc51bd260145c963197ad420e70).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 12:40 UTC, shantanu1singh approved these changes

2022-06-09 15:57 UTC, Lauragra approved these changes

2022-06-10 02:26 UTC, merged