User/vnagula/permissionchange
microsoftgraph/microsoft-graph-docs pull request #16979
Opened 2022-05-19 19:04 UTC by venkatnagula

Documentation change:

A user can get/cancel their own jobs without additional permissions. A user needs printer/printershare access only if they need to get/cancel other user jobs.

2022-05-19 19:07 UTC, opbld31 commented
Docs Build status updates of commit _[ccd138a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccd138ad00992741c7e1a8711e78104d66dfb98d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d31001825558b6df562feeea7182b7c3-34facfa7)
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-1b3b96c8580d3012046c86a0a8cb8a10-34facfa7)
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d31001825558b6df562feeea7182b7c3-34facfa7"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1b3b96c8580d3012046c86a0a8cb8a10-34facfa7"></a>
### [api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205191905086998-16979/BuildReport?accessString=5e7f912bccaab29a5b6a838c44a5423186a0a786da763bc8a67d8faa460d7ad6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 19:19 UTC, opbld32 commented
Docs Build status updates of commit _[bbdb7b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbdb7b40261fa9a298163a67cc8f40526e7900f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d31001825558b6df562feeea7182b7c3-4b5d79fc)
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d31001825558b6df562feeea7182b7c3-4b5d79fc"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205191917265680-16979/BuildReport?accessString=3eb5782bbf487bb8371957e2bd694632c18e4bd47df3ef785797c8de5406421a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-19 19:22 UTC, opbld31 commented
Docs Build status updates of commit _[b16f9ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b16f9bad26518ab3ab29c2c320b63756ccc7b54a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205191918064640-16979/BuildReport?accessString=b66e60cfe791f6d2ba0c16b31283b3786b10f2374197b33e4270652b8766844e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 20:08 UTC, braedenp-msft commented on api-reference/beta/api/printjob-cancel.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription. A user can cancel their own jobs or have a permission that grants [Get printer](pr
I'd recommend a slight change:

> In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription. Licensed users can cancel their own jobs, but the app must also have a permission that grants [Get printer](printer-get.md) access to cancel other users' jobs.

2022-05-20 21:35 UTC, opbld31 commented
Docs Build status updates of commit _[cab2259](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cab2259e4f80a96e36b6392565cd305b12e841f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205202132508803-16979/BuildReport?accessString=ce789184d231bc9aabc01a35acfb83e663651d5e468b1a0e7723ba0293045a63).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 21:38 UTC, opbld33 commented
Docs Build status updates of commit _[3ef7a30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ef7a308300d8237bd2a94e1f6b1926658960952)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-8a35262a)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-8a35262a"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205202133411005-16979/BuildReport?accessString=1b87e4cb389b6a513199ccd826dcb32850d0cfddd81a5cdba14d9b1da5ec733b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 21:40 UTC, opbld30 commented
Docs Build status updates of commit _[6552eb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6552eb46ca2cb492dfa5ceb0493e074c26863a96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-d934ec73)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-d934ec73)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-d934ec73"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-d934ec73"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205202137380656-16979/BuildReport?accessString=8575f7c50d302d31e153631a3a6d55071660c59b293a3df4e76505559239ef75).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-20 21:51 UTC, opbld34 commented
Docs Build status updates of commit _[94ad37e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94ad37ed5aabbf09ab34f0ef1f84c0726746a797)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-2a1b6877)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-2a1b6877)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-2a1b6877"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-2a1b6877"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205202133544281-16979/BuildReport?accessString=44da4af66177e51866fb2dc0461b2d76efd7f9a3da60c21728ab2c009e14b757).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:01 UTC, opbld33 commented
Docs Build status updates of commit _[f2ae445](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2ae4457911200af01ac9f6a1736d5e48bfb8dd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-681b8a7b)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-681b8a7b)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-681b8a7b"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-681b8a7b"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205241952441153-16979/BuildReport?accessString=5a171dfe402beec5326b2f3559b39b978477f828f992b18cd8d4598e13beffb3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:04 UTC, opbld32 commented
Docs Build status updates of commit _[4697447](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4697447169e5e5b7c1ac7de9953d8e6f9a5f5338)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-149665f2)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-149665f2)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-149665f2"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-149665f2"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205241954103754-16979/BuildReport?accessString=11e6e46b7914475d08c39d859543f1f5f329270e481738b45b0d00c88586c586).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:06 UTC, braedenp-msft approved these changes

2022-05-24 20:28 UTC, opbld30 commented
Docs Build status updates of commit _[8a8a410](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a8a410d27f56c32d3171661d4a4bce4e3b9f881)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-87039001)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-87039001)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-87039001"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-87039001"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205241953136285-16979/BuildReport?accessString=dfa0f84473c5278bdb44f2e21ccadc0ae6b5b0e18d764c6ab80a72d046e976e5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:36 UTC, opbld30 commented
Docs Build status updates of commit _[b29e1c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b29e1c23378e7be496224877db83a8ba2d716fde)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-bcb4e624)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-bcb4e624)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-bcb4e624"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-bcb4e624"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205241959563935-16979/BuildReport?accessString=7b513b9f9add7c82aea4adbc5e4bacccc9f5108c5240736adfeedcd25b36b435).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:43 UTC, opbld31 commented
Docs Build status updates of commit _[e6340b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6340b2ed9f289380afa3550e60ca97061933756)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-9769e3b9)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-9769e3b9)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-9769e3b9"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-9769e3b9"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205241953426792-16979/BuildReport?accessString=07a65af41ba5754e0e31078004bea5fc5cbf83edd5e607ad7febf987f95a04a0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:48 UTC, opbld33 commented
Docs Build status updates of commit _[92a4456](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92a44561b5492d471f44301ef014a90afe3efea6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-0ac33744)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-0ac33744)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-0ac33744"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-0ac33744"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205242000425522-16979/BuildReport?accessString=0d78a9a5cdc25db865356c28dcf89731a1715bb954f22a984de7ae1b35add2ec).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:54 UTC, opbld33 commented
Docs Build status updates of commit _[dcc7e64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcc7e64995f327ee87a510665bc9ac2bbf3273ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-bf91a523)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-bf91a523)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-bf91a523"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-bf91a523"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205242001149776-16979/BuildReport?accessString=b6fb6a84da6c266b4c4a7d0ff46c69c1a97577f9c9cacc52c3076fcb12b70a1d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 20:59 UTC, opbld32 commented
Docs Build status updates of commit _[62accfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62accfae7ed351cd94b6f1683c8d4697354cbadc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-8226a6f2)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-8226a6f2)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-8226a6f2"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-8226a6f2"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205242001384466-16979/BuildReport?accessString=cce86505ce1dc1b226e535eb7cab5c169f235442d06086ef7d388be6b4035b0f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-24 21:05 UTC, opbld33 commented
Docs Build status updates of commit _[420b17d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/420b17d856b12ae3105d842bea63da4ee4275a18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) | [Details](#user-content-d0afecd29797eedd61f722de571043e5-2684f0e5)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) | [Details](#user-content-ccb58b5a40d60e20b344e926af02fe82-2684f0e5)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

<a id="d0afecd29797eedd61f722de571043e5-2684f0e5"></a>
### [api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ccb58b5a40d60e20b344e926af02fe82-2684f0e5"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205242002027665-16979/BuildReport?accessString=d45bfbff9024e60facab1a7a418de8d29cecc9629c8980af8e182b8c5f4be644).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-25 11:45 UTC, nilakhan requested changes

2022-05-25 11:52 UTC, nilakhan commented on api-reference/beta/api/printjob-cancel.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription.
Cancel print job still requires Get Printer scope: 

https://microsoft.visualstudio.com/Universal%20Print/_git/UP.Service?path=/services/MPSGraph/src/Service/Helpers/SecurityScope/PFATTokenSecurityScopeHelper.cs&version=GBmaster&line=214&lineEnd=214&lineStartColumn=20&lineEndColumn=88&lineStyle=plain&_a=contents

2022-05-25 17:44 UTC, venkatnagula commented on api-reference/beta/api/printjob-cancel.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription. A user can cancel their own jobs or have a permission that grants [Get printer](pr
Can you point to the code where we are checking the permissions? I changed required scopes in Graph and IPPService code as well.  my commit https://microsoft.visualstudio.com/Universal%20Print/_git/UP.Service/commit/83b5eb76bc9b10bdf9f7fc8b4c9486a017156582

2022-05-25 17:48 UTC, venkatnagula commented on api-reference/beta/api/printjob-cancel.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription.
thanks for the link. I will fix the code to allow user to cancel their own jobs. I modified at certain places but not all it seems

2022-05-27 20:00 UTC, venkatnagula commented on api-reference/beta/api/printjob-get.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription. A user can get their own jobs or have a permission that grants [Get printer](print
outdate comment

2022-05-27 20:00 UTC, venkatnagula commented on api-reference/beta/api/printjob-cancel.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription.
fixed the code

2022-05-28 01:48 UTC, nilakhan approved these changes

2022-06-01 03:53 UTC, opbld32 commented
Docs Build status updates of commit _[fa74b82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa74b827e005750bf6f4f22d423f5ba67fbc6b72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010343546270-16979/BuildReport?accessString=545515036b54b1cbc1d234f12d8b4db7afe86f29c7a5d77541178f0258d9236c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 22:17 UTC, JarbasHorst commented
Hi @venkatnagula, I see that you have added the label "review requested" but I noticed that you haven't yet addressed the two open comments. Please, let me know if you have any questions regarding some of the feedback I provided.

2022-06-08 23:07 UTC, opbld31 commented
Docs Build status updates of commit _[0cd8b57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0cd8b574dbc3977ed9051567c02e1086a49ad760)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206082305119822-16979/BuildReport?accessString=c3226417cef911fa400d88b7e4789cf9e651ca7f466ad7263d47761ca682c678).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-08 23:16 UTC, braedenp-msft commented
> Hi @venkatnagula, I see that you have added the label "review requested" but I noticed that you haven't yet addressed the two open comments. Please, let me know if you have any questions regarding some of the feedback I provided.

@JarbasHorst Can you please check to make sure you published your review comments? I can't see them here.

If you already did, can you please link to them, because I can't seem to find them.

2022-06-08 23:20 UTC, JarbasHorst commented
Hello @venkatnagula, @braedenp-msft,
thank you very much for reaching out. Indeed, I forgot to push the review comments 😳 Sorry for that!

2022-06-08 23:22 UTC, braedenp-msft commented
> Hello @venkatnagula, @braedenp-msft, thank you very much for reaching out. Indeed, I forgot to publish the review comments 😳 Sorry for that! I've just published them. Please, take a look when you will have time.

No worries! Thanks for publishing them 😊

2022-06-10 23:43 UTC, opbld32 commented
Docs Build status updates of commit _[114a455](https://github.com/microsoftgraph/microsoft-graph-docs/commits/114a4554f64439488d83eddb9aec0462a5fa03ef)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-91d7a057)

<a id="91d7a057"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102343135124-16979/BuildReport?accessString=28fe5bcf8f90671666f3a0b40b8736787048aca679ff0993557c992e38a83c93).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:45 UTC, opbld30 commented
Docs Build status updates of commit _[d205d2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d205d2e3fd430ec6bdc7475c3d5d6cc5b9a9275f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d5f8b249)

<a id="d5f8b249"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102344386317-16979/BuildReport?accessString=2219658871cb3d44963f7716ef9c526a37d0cb8cc39b1f903e32a63aead36720).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:46 UTC, opbld34 commented
Docs Build status updates of commit _[04d2ef2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04d2ef2a4305c4f233b9c0ca54a1b0f7305adc58)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-36c876fe)

<a id="36c876fe"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102345190172-16979/BuildReport?accessString=6788fe5816ebb803393f229f701d1a47db313fb4458e0ea3d63b67182fca2320).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:46 UTC, opbld33 commented
Docs Build status updates of commit _[a7122ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7122efa2c2f8dea949f66356f3a40c868a1cf7c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9c5b3725)

<a id="9c5b3725"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102346087431-16979/BuildReport?accessString=f52ccc34f959a81be4286912a88fc54aee25d1797e3351f46bf6c70841a546ed).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:48 UTC, opbld34 commented
Docs Build status updates of commit _[92f0aa8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92f0aa88ea00c2062fb62a91b3f0d40131d954eb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f54beabb)

<a id="f54beabb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102348019034-16979/BuildReport?accessString=58ee8a2a69ee00b95ab3ff3f102a862c094c0780033ba2b6aca210a96e914a1a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:51 UTC, opbld30 commented
Docs Build status updates of commit _[2c4a453](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c4a453c191bea272ef15eb7fe336d25858f1f53)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cd9330b9)

<a id="cd9330b9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102349153756-16979/BuildReport?accessString=f37650b519c6e728c5664b02b16d9dde75e7debb502479dfa88a77ca09f48b43).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:55 UTC, opbld32 commented
Docs Build status updates of commit _[b0e1254](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0e1254147dcb9157510e803d7a8a6fcb2fdf78c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102352492283-16979/BuildReport?accessString=b28a164dc24f1c2851098f0954b0388e07e7eeb764b24d35f36d359d469da42d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 23:57 UTC, opbld32 commented
Docs Build status updates of commit _[f709e80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f709e8075b9b0f866cec846b28d0a33ebae759f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206102353348582-16979/BuildReport?accessString=1916c51a23d69f2ef33bd9bbb03ed2f05c62b714362ac56b7328bb5387132614).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 16:21 UTC, venkatnagula commented
> published

@JarbasHorst Can you take a look at the PR once again. I incorporated your feedback.

2022-06-13 23:10 UTC, opbld30 commented
Docs Build status updates of commit _[b6732f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6732f04a7491dc83490ee6e96f3c3e9d0d0de83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/beta/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-beta&branch=pr-en-us-16979) (graph-rest-beta) |
[api-reference/v1.0/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/printjob-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-get?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/archivedprintjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-16979) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206132307368113-16979/BuildReport?accessString=b83a573d60e71c82749cd3f3ae91a8029151e79734fd56321a7dfb926d59409c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 20:06 UTC, venkatnagula commented
> @Lauragra this PR is ready for final review. Please, merge PR [17227](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17227) into this branch to include my final edits.

Hi , Is there any pending things from my end to complete this PR ?

2022-06-17 05:08 UTC, Lauragra approved these changes

2022-06-18 01:13 UTC, merged