Update serviceprincipalriskdetection.md
microsoftgraph/microsoft-graph-docs pull request #16998
Opened 2022-05-20 20:42 UTC by CrysCyber

I am adding a new Enum to reflect a new detection

2022-05-20 20:44 UTC, opbld33 commented
Docs Build status updates of commit _[545fffd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/545fffd444d68197b56056f2afcbf88fe3a32139)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipalriskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/serviceprincipalriskdetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipalriskdetection?view=graph-rest-beta&branch=pr-en-us-16998) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205202042225360-16998/BuildReport?accessString=d05fd78f5ae3c144f0edb998e57b9ea38011e7ca10972cc889d1cf420e83240c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-22 01:03 UTC, Lauragra commented
@CrysCyber , is this PR ready for content review? You will need to include a changelog entry for the addition of the new enum member. For details, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog

2022-05-23 20:27 UTC, cloudhandler commented
@CrysCyber / @ebasseri to confirm- is it a new enum member or a new string? riskdetectiontype is a string for user riskdetections API?

2022-05-24 15:26 UTC, isvargasmsft commented on api-reference/beta/resources/serviceprincipalriskdetection.md
> +|riskEventType|String|The type of risk event detected. The possible values are:  `investigationsThreatIntelligence`, `generic`, `adminConfirmedServicePrincipalCompromised`, `suspiciousSignins`, `leak
Is this a brand new member? If so, please add a changelog entry as Laura suggested and also document the new member where the enum was defined: probably in the enums.md file.

2022-05-24 15:26 UTC, isvargasmsft requested changes
Please add the new member to the enum definition table and include a changelog entry.

2022-08-01 15:01 UTC, closed without merging