Kafen/multi stage review v1
microsoftgraph/microsoft-graph-docs pull request #17000
Opened 2022-05-20 21:55 UTC by kaiwenfeng4086

2022-05-20 22:02 UTC, opbld34 commented
Docs Build status updates of commit _[8cbd055](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cbd055107afb8fe4f2c971e4f727e718f5696fb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :x:Error | | [Details](#user-content-78ec3f67242cffa7307cf6340bf1eb66-3a9b8c05)
[api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :x:Error | | [Details](#user-content-27709dbe744836f74284952d99b8e5e9-3a9b8c05)
[api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md) | :x:Error | | [Details](#user-content-fcd89faf8ae5f6214164538f5e736769-3a9b8c05)
[api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewset-post-definitions.md) | :x:Error | | [Details](#user-content-cafaa2be3e5083f226ff3ae33bb39a1f-3a9b8c05)
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :x:Error | | [Details](#user-content-9e22ee5e9c99d3bbca710d0293840170-3a9b8c05)
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewstage-get.md) | :x:Error | | [Details](#user-content-eebf642db56d1119fedd38a1e4e8ac6d-3a9b8c05)
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :x:Error | | [Details](#user-content-b74abd12367a564e7ff451dbd09f2463-3a9b8c05)
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewstage-stop.md) | :x:Error | | [Details](#user-content-00047e82956bda3eea05dc6c4b76c86b-3a9b8c05)
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewstage-update.md) | :x:Error | | [Details](#user-content-36a6a122de4cb864a59d32ff17e7eb2b-3a9b8c05)
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-3a9b8c05)
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accessreviewstagesettings.md) | :warning:Warning | | [Details](#user-content-7a5d72afbf44ddae0a339236b735464a-3a9b8c05)
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/approval-list-stages.md) | :warning:Warning | | [Details](#user-content-3505bc7235c567409051f1687254b7f7-3a9b8c05)

<a id="78ec3f67242cffa7307cf6340bf1eb66-3a9b8c05"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewinstance-list-stages.md)
 - **Line 63, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-accessreviewstage-csharp-snippets.md'.`````
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-accessreviewstage-javascript-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-accessreviewstage-objc-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-accessreviewstage-java-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-accessreviewstage-go-snippets.md'.`````
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List stages - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/accessreviewinstance-list-stages.md(2,8), v1.0/api/approval-list-stages.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List stages' is duplicated with other articles: 'v1.0/api/accessreviewinstance-list-stages.md(10,1), v1.0/api/approval-list-stages.md(10,1)'. First level headings must be unique within a docset.`````

<a id="27709dbe744836f74284952d99b8e5e9-3a9b8c05"></a>
### [api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 180, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/accessreviewinstancedecisionitem-filterbycurrentuser-2-csharp-snippets.md'.`````
 - **Line 184, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/accessreviewinstancedecisionitem-filterbycurrentuser-2-javascript-snippets.md'.`````
 - **Line 188, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/accessreviewinstancedecisionitem-filterbycurrentuser-2-objc-snippets.md'.`````
 - **Line 192, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/accessreviewinstancedecisionitem-filterbycurrentuser-2-java-snippets.md'.`````
 - **Line 196, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/accessreviewinstancedecisionitem-filterbycurrentuser-2-go-snippets.md'.`````

<a id="fcd89faf8ae5f6214164538f5e736769-3a9b8c05"></a>
### [api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md)
 - **Line 163, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-accessreviewstage-accessreviewinstancedecisionitem-csharp-snippets.md'.`````
 - **Line 167, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-accessreviewstage-accessreviewinstancedecisionitem-javascript-snippets.md'.`````
 - **Line 171, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-accessreviewstage-accessreviewinstancedecisionitem-objc-snippets.md'.`````
 - **Line 175, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-accessreviewstage-accessreviewinstancedecisionitem-java-snippets.md'.`````
 - **Line 179, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-accessreviewstage-accessreviewinstancedecisionitem-go-snippets.md'.`````

<a id="cafaa2be3e5083f226ff3ae33bb39a1f-3a9b8c05"></a>
### [api-reference/v1.0/api/accessreviewset-p [...]

2022-05-31 21:09 UTC, zhusijia26 approved these changes

2022-06-06 17:36 UTC, FaithOmbongi requested changes
Hi @kaiwenfeng4086  - Thank you for yourwork in this PR.

I've left suggestions mostly for minor fixes. The major recurring problem to fix in all new API docs/new examples is imported snippets. Please remove from the v1.0 docs (and new examples) all code snippets that you imported from the beta docs. This is because code snippets are autogenerated after your docs go live and the specific lines will be inserted by the snippets generator. I've left a marker in one of the files marking sections that demarcate code snippets.

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewstagesettings.md
> +description: "In Azure AD access reviews, the accessReviewStageSettings represents the settings of the stages associated with a multi-stage access review."
```suggestion
description: "Represents the settings of the stages associated with a multi-stage access review."
```

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewstagesettings.md
> +|stageId|String|Unique identifier of the **accessReviewStageSettings**. The **stageId** will be used in **dependsOn** property to indicate the stage relationship. Required. |
```suggestion
|stageId|String|Unique identifier of the **accessReviewStageSettings** object. The **stageId** will be used by the **dependsOn** property to indicate the stage relationship. Required. |
```

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewinstance-list-stages.md
> +# [HTTP](#tab/http)
Global: This line will be inserted by the snippets generator
```suggestion
```

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewinstance-list-stages.md
> +---
Global: All these will be inserted by the snippets generator

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +# [HTTP](#tab/http)
Same comment about snippets

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md
> +---
Same comment about snippets

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
> +|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created se
```suggestion
|stageSettings|[accessReviewStageSettings](../resources/accessreviewstagesettings.md) collection| Defines how many stages each instance of an access review series will have. Stages will be created sequentially based on the **dependsOn** property. Each stage can have different set of reviewer, fallback reviewers and settings. <br/><br/>When this property is defined, its values are used instead of the corresponding values in the [accessReviewScheduleDefinition](../resources/accessreviewscheduledefinition.md) object and its **settings** property. Optional. |
```

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
>  [!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]
If some of the snippets aren't available, just delete what's there & new snippets will be generated in the weekly run

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
> +# [HTTP](#tab/http)
.

2022-06-06 17:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accessreviewset-post-definitions.md
> +
✂️

2022-06-06 17:36 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [accessReviewStage](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewStage?view=graph-rest-1.0) resource",
```suggestion
          "Description": "Added the [accessReviewStage](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewStage?view=graph-rest-1.0) resource and associated methods. Represents a stage in an [accessReviewInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta).",
```

2022-06-06 17:36 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the **stageSettings** property to the [accessReviewScheduleDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewScheduleDefinition?view=graph-r
```suggestion
          "Description": "Added the **stageSettings** property to the [accessReviewScheduleDefinition](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewScheduleDefinition?view=graph-rest-1.0) resource. Defines the stages and their settings in a multi-stage access review.",
```

2022-06-06 17:36 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Target": "filterByCurrentUser"
The action and function are covered by the "and associated methods" statement and don't need a separate mention,
```suggestion
```

2022-07-19 17:01 UTC, opbld34 commented
Docs Build status updates of commit _[fee5ecb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fee5ecb20043b3d92216d89ad6466d146ee7fbb7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-99c093a3)

<a id="99c093a3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207191700179147-17000/BuildReport?accessString=722b87d12e077875c33e774b3c6abe60643110a7e6897cc90aa846da8252c367).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 16:02 UTC, opbld30 commented
Docs Build status updates of commit _[da01608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da01608ce2695cf1484ef2c7ae5cd17a484fbe73)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :x:Error | | [Details](#user-content-27709dbe744836f74284952d99b8e5e9-06214dbd)
[api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md) | :x:Error | | [Details](#user-content-fcd89faf8ae5f6214164538f5e736769-06214dbd)
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :x:Error | | [Details](#user-content-78ec3f67242cffa7307cf6340bf1eb66-06214dbd)
[api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewset-post-definitions.md) | :x:Error | | [Details](#user-content-cafaa2be3e5083f226ff3ae33bb39a1f-06214dbd)
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :x:Error | | [Details](#user-content-9e22ee5e9c99d3bbca710d0293840170-06214dbd)
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md) | :x:Error | | [Details](#user-content-eebf642db56d1119fedd38a1e4e8ac6d-06214dbd)
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :x:Error | | [Details](#user-content-b74abd12367a564e7ff451dbd09f2463-06214dbd)
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md) | :x:Error | | [Details](#user-content-00047e82956bda3eea05dc6c4b76c86b-06214dbd)
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md) | :x:Error | | [Details](#user-content-36a6a122de4cb864a59d32ff17e7eb2b-06214dbd)
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/approval-list-stages.md) | :warning:Warning | | [Details](#user-content-3505bc7235c567409051f1687254b7f7-06214dbd)
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-06214dbd)
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstagesettings.md) | :warning:Warning | | [Details](#user-content-7a5d72afbf44ddae0a339236b735464a-06214dbd)

<a id="27709dbe744836f74284952d99b8e5e9-06214dbd"></a>
### [api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md)
 - **Line 185, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/accessreviewinstancedecisionitem-filterbycurrentuser-2-csharp-snippets.md'.`````
 - **Line 189, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/accessreviewinstancedecisionitem-filterbycurrentuser-2-javascript-snippets.md'.`````
 - **Line 193, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/accessreviewinstancedecisionitem-filterbycurrentuser-2-objc-snippets.md'.`````
 - **Line 197, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/accessreviewinstancedecisionitem-filterbycurrentuser-2-java-snippets.md'.`````
 - **Line 201, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/accessreviewinstancedecisionitem-filterbycurrentuser-2-go-snippets.md'.`````
 - **Line 175, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="fcd89faf8ae5f6214164538f5e736769-06214dbd"></a>
### [api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md)
 - **Line 168, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-accessreviewstage-accessreviewinstancedecisionitem-csharp-snippets.md'.`````
 - **Line 172, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-accessreviewstage-accessreviewinstancedecisionitem-javascript-snippets.md'.`````
 - **Line 176, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-accessreviewstage-accessreviewinstancedecisionitem-objc-snippets.md'.`````
 - **Line 180, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-accessreviewstage-accessreviewinstancedecisionitem-java-snippets.md'.`````
 - **Line 184, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-accessreviewstage-accessreviewinstancedecisionitem-go-snippets.md'.`````
 - **Line 158, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="78ec3f67242cffa7307cf6340bf1eb66-06214dbd"></a>
### [api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md)
 - **Line 62, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-accessreviewstage-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-accessreviewstage-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-accessreviewstage-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-accessreviewstage-java-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-accessreviewstage-go-snippets.md'.`````
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review [...]

2022-07-21 16:10 UTC, opbld33 commented
Docs Build status updates of commit _[7440565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7440565d499de7df4d1f20efc941377ce0372f18)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :x:Error | | [Details](#user-content-9e22ee5e9c99d3bbca710d0293840170-79377bda)
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md) | :x:Error | | [Details](#user-content-eebf642db56d1119fedd38a1e4e8ac6d-79377bda)
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :x:Error | | [Details](#user-content-b74abd12367a564e7ff451dbd09f2463-79377bda)
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md) | :x:Error | | [Details](#user-content-00047e82956bda3eea05dc6c4b76c86b-79377bda)
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md) | :x:Error | | [Details](#user-content-36a6a122de4cb864a59d32ff17e7eb2b-79377bda)
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :warning:Warning | | [Details](#user-content-78ec3f67242cffa7307cf6340bf1eb66-79377bda)
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/approval-list-stages.md) | :warning:Warning | | [Details](#user-content-3505bc7235c567409051f1687254b7f7-79377bda)
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-79377bda)
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstagesettings.md) | :warning:Warning | | [Details](#user-content-7a5d72afbf44ddae0a339236b735464a-79377bda)

<a id="9e22ee5e9c99d3bbca710d0293840170-79377bda"></a>
### [api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md)
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/accessreviewstage-filterbycurrentuser-csharp-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/accessreviewstage-filterbycurrentuser-javascript-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/accessreviewstage-filterbycurrentuser-objc-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/accessreviewstage-filterbycurrentuser-java-snippets.md'.`````
 - **Line 86, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/accessreviewstage-filterbycurrentuser-go-snippets.md'.`````

<a id="eebf642db56d1119fedd38a1e4e8ac6d-79377bda"></a>
### [api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md)
 - **Line 63, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-accessreviewstage-csharp-snippets.md'.`````
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-accessreviewstage-javascript-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-accessreviewstage-objc-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-accessreviewstage-java-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-accessreviewstage-go-snippets.md'.`````

<a id="b74abd12367a564e7ff451dbd09f2463-79377bda"></a>
### [api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md)
 - **Line 66, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-stage-accessreviewinstancedecisionitem-csharp-snippets.md'.`````
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-stage-accessreviewinstancedecisionitem-javascript-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-stage-accessreviewinstancedecisionitem-objc-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-stage-accessreviewinstancedecisionitem-java-snippets.md'.`````
 - **Line 82, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-stage-accessreviewinstancedecisionitem-go-snippets.md'.`````

<a id="00047e82956bda3eea05dc6c4b76c86b-79377bda"></a>
### [api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md)
 - **Line 62, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/accessreviewstage-stop-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/accessreviewstage-stop-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/accessreviewstage-stop-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/accessreviewstage-stop-java-snippets.md'.`````
 - **Line 78, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/accessreviewstage-stop-go-snippets.md'.`````

<a id="36a6a122de4cb864a59d32ff17e7eb2b-79377bda"></a>
### [api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md)
 - **Line 98, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-accessreviewstage-csharp-snippets.md'.`````
 - **Line 102, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-accessreviewstage-javascript-snippets.md'.`````
 - **Line 106, Column 1** [...]

2022-07-21 16:19 UTC, opbld34 commented
Docs Build status updates of commit _[22e3593](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22e3593b50fa910b88224c4972c97b3f93aeecc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) | [Details](#user-content-78ec3f67242cffa7307cf6340bf1eb66-6d17fb6a)
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/approval-list-stages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) | [Details](#user-content-3505bc7235c567409051f1687254b7f7-6d17fb6a)
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewinstance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) | [Details](#user-content-49b3d45645e9b2df44e5c28f034651f2-6d17fb6a)
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) | [Details](#user-content-7a5d72afbf44ddae0a339236b735464a-6d17fb6a)
[api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/m [...]

2022-07-21 16:39 UTC, opbld33 commented
Docs Build status updates of commit _[fb9ced2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb9ced2567b26100b62da59ec3e0dff8b058385e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-07-22 20:16 UTC, isabelleatmsft approved these changes

2022-07-25 08:33 UTC, FaithOmbongi approved these changes

2022-07-27 18:00 UTC, opbld32 commented
Docs Build status updates of commit _[50ce9a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50ce9a5289b061f65de58310bd595fc33c64311c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-07-28 00:16 UTC, opbld30 commented
Docs Build status updates of commit _[beea036](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beea036ce584604a1c0603dbbe52c8294235b5c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstancedecisionitem-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewinstance-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewinstance-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-get?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-list-decisions?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-stop.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-stop.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-stop?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accessreviewstage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/accessreviewstage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewstage-update?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/api/approval-list-stages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/api/approval-list-stages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/approval-list-stages?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstage?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewstagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/accessreviewstagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewstagesettings?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstancedecisionitem-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-17000) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/kafen/multiStageReview-v1/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-07-28 00:27 UTC, merged