Add api to get user's Cloud PC and add apis to operate Cloud PC
microsoftgraph/microsoft-graph-docs pull request #17010
Opened 2022-05-23 06:42 UTC by xinliu22

Introduce a new API to get a specific Cloud PC for the current user, 
along with 4 action APIs, including `reboot`, `rename`, `reprovision`, `troubleshoot`.

2022-05-23 06:44 UTC, opbld32 commented
Docs Build status updates of commit _[16d921a](https://github.com/xinliu22/microsoft-graph-docs/commits/16d921afe65057ff6dff1500d84b5d3ecdd4dc83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :x:Error | | [Details](#user-content-e0dedf298fb62f7ebc2ba6bf16580c9c-039bf287)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-0817dce4456c16725d5333633847d38f-039bf287)

<a id="e0dedf298fb62f7ebc2ba6bf16580c9c-039bf287"></a>
### [api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-troubleshoot-cloudpc.md)
 - **Line 70, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/user-snippets-sdk-documentation-link.md'.`````

<a id="0817dce4456c16725d5333633847d38f-039bf287"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 342, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/user-reprovsion-cloudpc.md'.`````
 - **Line 10000, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/user-reprovsion-cloudpc.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205230643020811-17010/BuildReport?accessString=6bee47d996e7a762ea42a01a74df0850168b10df85fa91dada902b9cb59cde3d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-23 06:52 UTC, opbld31 commented
Docs Build status updates of commit _[49c9178](https://github.com/xinliu22/microsoft-graph-docs/commits/49c9178cd49196461f08f0b0aab6ee8e7a1c940f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph [...]

2022-05-24 03:56 UTC, Lauragra commented
@xinliu22 , please follow the Get started steps to set yourself up to be a contributor to the repo so that you can follow our content workflow: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211776/Get-started

2022-06-06 03:03 UTC, opbld31 commented
Docs Build status updates of commit _[a079c18](https://github.com/xinliu22/microsoft-graph-docs/commits/a079c18bbe2e25613eeb62e294986fecaef96dd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph [...]

2022-06-06 03:14 UTC, opbld31 commented
Docs Build status updates of commit _[7e4d4cd](https://github.com/xinliu22/microsoft-graph-docs/commits/7e4d4cdf083b62205104a458ea49d704ac7680e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph [...]

2022-06-06 04:55 UTC, AshleyYangSZ requested changes

2022-06-06 04:55 UTC, AshleyYangSZ commented on api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
No need to add snippet of other language, which are generated automatically. Add please add change log to Microsoft.CloudManagedDesktop.json.

2022-06-21 05:41 UTC, opbld32 commented
Docs Build status updates of commit _[c24f5f8](https://github.com/xinliu22/microsoft-graph-docs/commits/c24f5f870302cc08b3e4d9db1556684af8f6fb6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reboot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-rename-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-reprovision-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/csharp/user-troubleshoot-cloudpc-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-get-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reboot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-rename-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-reprovision-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/go/user-troubleshoot-cloudpc-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-get-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reboot-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-rename-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/includes/snippets/java/user-reprovision-cloudpc-java-snippets.md) | :white_check_mark:Succeeded | [View](h [...]

2022-06-21 07:37 UTC, opbld31 commented
Docs Build status updates of commit _[9d2ec99](https://github.com/xinliu22/microsoft-graph-docs/commits/9d2ec9938c79e3a769f6e152cf5a5db9310037dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206210735032400-17010/BuildReport?accessString=ed2aa184aaa4c74334efa2e857ff392c226f807215e03590db808c3497c413aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 08:00 UTC, xinliu22 commented on api-reference/beta/includes/snippets/csharp/user-get-cloudpc-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
Done.

2022-06-21 08:01 UTC, opbld34 commented
Docs Build status updates of commit _[c43e75d](https://github.com/xinliu22/microsoft-graph-docs/commits/c43e75d56157bcde5e2888a10534d72e25340518)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206210758517382-17010/BuildReport?accessString=7f9d811dbf3e34e6be3a722d18daea68f06237364953dfe1dec2588919b5e85b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 09:18 UTC, AshleyYangSZ requested changes

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-get-cloudpc.md
> +GET https://graph.microsoft.com/beta/me/cloudPCs/662009bc-7732-4f6f-8726-25883518ffff
Please replace the example GUID to {id} here

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-reboot-cloudpc.md
> +| Application                            | Not supported.                              |
As you didn't add application permission here, I suppose the API will only support delegated permission right?

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-reboot-cloudpc.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/662009bc-7732-4f6f-8726-25883518ffff/reboot
The URL should be https://graph.microsoft.com/beta/me/cloudPCs/{id}/reboot

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-rename-cloudpc.md
> +| Delegated (work or school account)     | CloudPC.Read.All, CloudPC.ReadWrite.All     |
The API which has side effect in service side, should use CloudPC.ReadWrite.All permission.

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-rename-cloudpc.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/c2bbb5dd-2574-451b-a508-bbaa6ac48ace/rename
replace GUID with {id}

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-reprovision-cloudpc.md
> +| Delegated (work or school account)     | CloudPC.Read.All, CloudPC.ReadWrite.All     |
The API which has side effect in service side, should use CloudPC.ReadWrite.All permission.

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-reprovision-cloudpc.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/4b5ad5e0-6a0b-4ffc-818d-36bb23cf4dbd/reprovision
Replace GUID with {id}

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-troubleshoot-cloudpc.md
> +Troubleshoot a specific [cloudPC](../resources/cloudpc.md) device that is attributed to the signed-in user. Use this API to check the health status of the Cloud PC and the session host.
Perform troubleshooting on one of my [cloudPC](../resources/cloudpc.md). Use this API to check the health status of the Cloud PC.

Customer has no aware of the session host, so don't expose this term.

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-troubleshoot-cloudpc.md
> +| Delegated (work or school account)     | CloudPC.Read.All, CloudPC.ReadWrite.All     |
The API which has side effect in service side, should use CloudPC.ReadWrite.All permission.

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/api/user-troubleshoot-cloudpc.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/ff4eb6ab-d56a-4edf-90c1-baaec8dd6032/troubleshoot
Replace GUID with {id}

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Get
Get a CloudPC

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Reboot
Reboot a CloudPC

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Rename
Rename a CloudPC

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Reprovision
Reprovision a CloudPC

2022-06-30 09:18 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Troubleshoot
Troubleshoot a CloudPC

2022-06-30 09:52 UTC, RuiHou105 commented on api-reference/beta/api/user-get-cloudpc.md
> +# [HTTP](#tab/http)
Please remove this line `# [HTTP](#tab/http) `in all your files. As it will be generated by tool later. No need to manually add it.

2022-07-04 01:51 UTC, opbld30 commented
Docs Build status updates of commit _[fe29c7c](https://github.com/xinliu22/microsoft-graph-docs/commits/fe29c7cbb675748d1eb42683befd050dc6525b15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207040147167756-17010/BuildReport?accessString=2749aaa5819d3e3e656fbb85819d0eb72b98db05b1ebe410b244273117a564e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-04 01:52 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +GET https://graph.microsoft.com/beta/me/cloudPCs/662009bc-7732-4f6f-8726-25883518ffff
Removed this HTTP example part, thx!

2022-07-04 01:52 UTC, xinliu22 commented on api-reference/beta/api/user-reboot-cloudpc.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/662009bc-7732-4f6f-8726-25883518ffff/reboot
Removed this HTTP example part, thx!

2022-07-04 01:52 UTC, xinliu22 commented on api-reference/beta/api/user-rename-cloudpc.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/c2bbb5dd-2574-451b-a508-bbaa6ac48ace/rename
Removed this HTTP example part, thx!

2022-07-04 01:54 UTC, xinliu22 commented on api-reference/beta/api/user-rename-cloudpc.md
> +| Delegated (work or school account)     | CloudPC.Read.All, CloudPC.ReadWrite.All     |
Yes, `CloudPC.ReadWrite.All` permission is required, `CloudPC.Read.All` removed. Thx.

2022-07-04 01:56 UTC, xinliu22 commented on api-reference/beta/api/user-reboot-cloudpc.md
> +| Application                            | Not supported.                              |
Yes, only Delegated permission is supported by end-user APIs.

2022-07-04 01:56 UTC, xinliu22 commented on api-reference/beta/toc.yml
> +        - name: Get
Updated, thx.

2022-07-04 01:56 UTC, xinliu22 commented on api-reference/beta/toc.yml
> +        - name: Troubleshoot
Updated, thx.

2022-07-04 01:56 UTC, xinliu22 commented on api-reference/beta/toc.yml
> +        - name: Reprovision
Updated, thx.

2022-07-04 01:56 UTC, xinliu22 commented on api-reference/beta/toc.yml
> +        - name: Rename
Updated, thx.

2022-07-04 01:56 UTC, xinliu22 commented on api-reference/beta/toc.yml
> +        - name: Reboot
Updated, thx.

2022-07-04 01:57 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +# [HTTP](#tab/http)
All HTTP sections are removed, thx.

2022-07-04 07:45 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Id": "02d01ff0-4622-4e8c-b363-caa0fa50ec64",
All `Id `for your changelog should use the same one. So please use 02d01ff0-4622-4e8c-b363-caa0fa50ec64

2022-07-04 07:52 UTC, opbld33 commented
Docs Build status updates of commit _[5638dfe](https://github.com/xinliu22/microsoft-graph-docs/commits/5638dfed4a56661d42ea55f970a1deb2ce69ad05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207040749350444-17010/BuildReport?accessString=71d76ebb29c94fd9a24edb42632e71f0fa3b0aa0b24236b91ceb7b703dd12021).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-04 07:54 UTC, RuiHou105 requested changes
Hi @xinliu22 
1.Please resolve comments in this PR.

2.Please create a roadmap worktem and then attach the workitem number in this PR. Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/

If you don't have access, please do this firstly:
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-07-04 09:31 UTC, AshleyYangSZ commented on api-reference/beta/api/user-get-cloudpc.md
> +
Sorry, my mistake. You could use a GUID in the example http request. Please do not remove the example request here. Same comments for other APIs. Could you add the example back?

2022-07-04 09:43 UTC, opbld33 commented
Docs Build status updates of commit _[4ba3fec](https://github.com/xinliu22/microsoft-graph-docs/commits/4ba3fec0f5782bf94a16824f68974c2f6061817e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207040940258506-17010/BuildReport?accessString=0ae691ad5188e9734dc729f755ea35ea16ba91046ca9cf75b272bb96e3cebdbb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 01:58 UTC, opbld32 commented
Docs Build status updates of commit _[699d660](https://github.com/xinliu22/microsoft-graph-docs/commits/699d660324d7d73285d40868fed0dfba1ec047dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050156323529-17010/BuildReport?accessString=f15d63beca902cf5cdb135f650f0057bc943d9dd2497d800c5812f9f09424096).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 02:13 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +
They came back!

2022-07-05 02:13 UTC, xinliu22 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "Id": "02d01ff0-4622-4e8c-b363-caa0fa50ec64",
Done!

2022-07-05 02:30 UTC, RuiHou105 approved these changes

2022-07-05 03:14 UTC, AshleyYangSZ approved these changes

2022-07-19 05:34 UTC, AshleyYangSZ commented
@Danielabom  How about the review progress of this PR? Any comments are very welcomed.

2022-07-19 22:50 UTC, Danielabom commented on api-reference/beta/api/user-get-cloudpc.md
> +title: "Get a specific cloudPC for user"
I believe that like the other operations, it should be Cloud PC, right? Please check.

2022-07-19 22:58 UTC, Danielabom reviewed
Hi @xinliu22  and @AshleyYangSZ, I left a comment. I already reached out to Xin with a specific question, but I have one more question for you @AshleyYangSZ, please check the chat. Thank you, both, for working on this PR.

2022-07-20 03:11 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +title: "Get a specific cloudPC for user"
Seems there are many uses of these two terms, this may look a little bit confusing since we have no statements that they are interchangeable. 
@AshleyYangSZ, what do you think of renaming all "cloudPc" to "Cloud PC"?

2022-07-21 05:41 UTC, opbld32 commented
Docs Build status updates of commit _[faae159](https://github.com/xinliu22/microsoft-graph-docs/commits/faae1599207aa4b718d92b276bb2116360e4df82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207210539113984-17010/BuildReport?accessString=1e53cc6934e37ad4e8c248588664f62a8aa7bee395820a8996c082617d7ab562).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 05:41 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +title: "Get a specific cloudPC for user"
@Danielabom All "cloudPc" in end-user docs has been renamed to "Cloud PC" the one that other docs are using.

2022-07-21 18:09 UTC, Danielabom approved these changes
Changes look good. Thanks @xinliu22.

2022-07-22 02:32 UTC, xinliu22 commented
@Danielabom , @AshleyYangSZ , @RuiHou105, thank you all for helping review this PR, a pleasant collaboration.

2022-07-22 21:49 UTC, isvargasmsft commented on api-reference/beta/api/user-get-cloudpc.md
> +# [HTTP](#tab/http)
Global: Please remove these tabs. Code snippets are automatically generated:
```suggestion

```

2022-07-22 21:50 UTC, isvargasmsft commented on api-reference/beta/api/user-reboot-cloudpc.md
> +# [HTTP](#tab/http)
```suggestion

```

2022-07-22 21:50 UTC, isvargasmsft commented on api-reference/beta/api/user-rename-cloudpc.md
> +# [HTTP](#tab/http)
```suggestion

```

2022-07-22 21:50 UTC, isvargasmsft commented on api-reference/beta/api/user-reprovision-cloudpc.md
> +# [HTTP](#tab/http)
```suggestion

```

2022-07-22 21:50 UTC, isvargasmsft commented on api-reference/beta/api/user-troubleshoot-cloudpc.md
> +# [HTTP](#tab/http)
```suggestion

```

2022-07-22 21:53 UTC, isvargasmsft commented on api-reference/beta/api/user-get-cloudpc.md
> +---
Hello @xinliu22, were the file names and the new topics automatically generated or did you added them manually? 

If you added them manually, please follow the guidelines for file naming here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming

In addition, please let me confirm with the team if we create separate topics for the context of a user. I believe we should update existing topics instead and add the new HTTP requests and examples to the existing topics. But please allow me to confirm with the rest of the team. 

Kind regards,

Isaac

2022-07-22 23:22 UTC, angelgolfer-ms commented on api-reference/beta/api/user-list-cloudpcs.md
> +# List Cloud PCs
Line 10:
@xinliu22 , there's a reference topic title format we need to follow, and in the case of a list operation, the topic title format is "List {navigation property}". 
Unlike concept topics, reference topic titles are not free form. They need to be predictable so that Graph Studio can form link text that matches the destination ref topic title. 
The original topic title is correct. Please revert.

2022-07-22 23:24 UTC, angelgolfer-ms commented on api-reference/beta/api/user-list-cloudpcs.md
Line 15:
Was there a specific reason to change from the resource  name to natural language in the link text?
In reference docs, which is different from conceptual content, exposing the relevant API and resource names is important. 
In this case, the object for the list operation is the return type, relevant to the understanding of the operation. Please revert your change.

2022-07-22 23:45 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: List Cloud PCs
Lines 385 and 10491, and GLOBAL:
Please be aware that there are rules to name reference topics in the TOC as well. In the case of "list" operations, the TOC titles should follow "List {nav property name}".  CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=guidelines-and-examples
The original for the 2 lines I listed follow the rules. Please revert the changes.

2022-07-22 23:51 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Get a Cloud PC
Lines 387-398:
It's appropriate to expose these operations and methods under the Users >> Cloud PC node. However, with their TOC titles, please follow the current TOC titles used under Device and app management >> Cloud PC >> Cloud PC node. 
Keeping the TOC title format consistent, short, unambiguous, and scannable is the goal here.

2022-07-22 23:52 UTC, angelgolfer-ms commented on api-reference/beta/api/user-get-cloudpc.md
> +---
Thanks for bringing this subject to our attention, @isvargasmsft . Think I would comment here directly in case @xinliu22 would want to address this on the start of their work week after the weekend. The action item for @xinliu22 involves some reorganizing their content for the bulk of the topics in this PR.

@xinliu22 , please use the existing topics for the GET (cloudpc-get.md) operation, and the existing topics for the 4 methods.
Reasons:

- Consistency with the rest of the Microsoft Graph API docs. In general, Microsoft Graph provides that benefit of sharing resources across use cases, so that customers can learn once and apply the same approach. At the docs level, exposing use cases in the same reference topics helps customers discover them. An example is the profilePhoto resource. Customers use the same resource and methods for user photo, group photo, contact photo, and team photo. If you look at profilephoto.md and its operation topics such as GET (profilephoto-get.md), we describe this shared support, and include the corresponding syntax for each of user, group, contact, and team.
- In general, we can't just break out, form new reference topics, and name them however we see fit. Graph Studio needs to be able to know exactly what operations are supported, how their topics are titled to form the link text, and how their topic filenames are put together to form link destinations.

Like you have already done it, we expose these under the Users >> Cloud PC node in the TOC as well.

2022-07-22 23:56 UTC, angelgolfer-ms requested changes
Hi @xinliu22 ,
I added a few comments here initially to answer @isvargasmsft 's question about reusing the existing topics for the operations and methods in question.
As I scrolled to verify what's in the PR, I spotted some other issues, so for efficiency, I entered the comments here as well. My comments only cover what I happened to see, and I don't intend to review the entire PR.
Please continue to work with @isvargasmsft who remains the reviewer of this PR.
If you have any questions regarding my comments, please feel free to check with @isvargasmsft , or ping me on Teams. I won't be monitoring this PR.

2022-07-25 05:39 UTC, opbld32 commented
Docs Build status updates of commit _[14692ec](https://github.com/xinliu22/microsoft-graph-docs/commits/14692ecf8b9b6b9380e38dc1c73f0cd9868c8e57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-get-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-get-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reboot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reboot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reboot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-rename-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-rename-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-rename-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-reprovision-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-reprovision-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-reprovision-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/user-troubleshoot-cloudpc.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/user-troubleshoot-cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-troubleshoot-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/resources/cloudpclaunchinfo.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/resources/cloudpclaunchinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpclaunchinfo?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207250536501268-17010/BuildReport?accessString=542b0fa8b1a20c032353ea6dda63f57366201b47b7c8ae1c119da75693b2aadf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 06:08 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +---
Thank your comments, I'll go through the Graph guidance again and then update the PR.

2022-07-26 09:12 UTC, opbld30 commented
Docs Build status updates of commit _[fdbf025](https://github.com/xinliu22/microsoft-graph-docs/commits/fdbf02556f2c2044c50436553e83e73372c3ea61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207260910263624-17010/BuildReport?accessString=e94b395b041577c3d9e4db3647eaaa1d84711923204412bb8da9f377ab6d81f7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 11:23 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +# [HTTP](#tab/http)
Deleted the new topic file, please help review the changes in the existing topics. Thx.

2022-07-26 11:24 UTC, xinliu22 commented on api-reference/beta/api/user-reboot-cloudpc.md
> +# [HTTP](#tab/http)
Same as above.

2022-07-26 12:05 UTC, xinliu22 commented on api-reference/beta/api/user-get-cloudpc.md
> +---
Hello @isvargasmsft , after going through the guidelines, I finished adding the new APIs to the existing topics referring to the 'profilephoto.md', and update the TOC titles. 

Still have some questions: 
1. Should I have at least one example for every single API in the topic? Like the "HTTP request" section in "cloudpc-get.md", there are three APIs.
2. In the example section, will the Graph DevX tool generate snippets for manually added examples?

Regards,
Xin

2022-08-03 01:55 UTC, opbld33 commented
Docs Build status updates of commit _[331b535](https://github.com/xinliu22/microsoft-graph-docs/commits/331b535e88bebfd41ba61b0c20872da1134dd78a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030153278941-17010/BuildReport?accessString=c1ecf3470c4d2893a95dfef90d6a07cebc11d02a186f51be748fca4d20b209bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 16:11 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-get.md
> +GET /me/cloudPCs{id}
Typo:
```suggestion
GET /me/cloudPCs/{id}
```

2022-08-04 16:13 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-rename.md
> +### Example 1: Reboot the cloudPC for the administrator
Typo:
```suggestion
### Example 1: Rename the cloudPC for the administrator
```

2022-08-04 16:13 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-rename.md
> +### Example 2: Reboot the cloudPC for the signed-in user
Typo: 
```suggestion
### Example 2: Rename the cloudPC for the signed-in user
```

2022-08-04 16:14 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-rename.md
> +POST https://graph.microsoft.com/beta/me/cloudPCs/36bd4942-0ca8-11ed-861d-0242ac120002/reboot
Typo:
```suggestion
POST https://graph.microsoft.com/beta/me/cloudPCs/36bd4942-0ca8-11ed-861d-0242ac120002/rename
```

2022-08-04 16:15 UTC, isvargasmsft commented on api-reference/beta/api/cloudpc-reprovision.md
> +### Example 1: Reboot the cloudPC for the administrator
Typo:
```suggestion
### Example 1: Reprovision the cloudPC for the administrator
```

2022-08-04 16:20 UTC, opbld32 commented
Docs Build status updates of commit _[bb4fb2c](https://github.com/xinliu22/microsoft-graph-docs/commits/bb4fb2ca515652519bd7b9e5afa0bb55c504cb9b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-dfac824a)
[api-reference/beta/api/cloudpc-get.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-dfac824a"></a>
### [api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml)
 - **Line 15127, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208041618323450-17010/BuildReport?accessString=1fe8f62c41ae6280d1d0376b8b3d0a5430a7ec4751c54a167b7d65eb78df592a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 16:23 UTC, opbld33 commented
Docs Build status updates of commit _[667aead](https://github.com/xinliu22/microsoft-graph-docs/commits/667aeadcfab640a4a63693b6a8c3a69a1c03b833)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e5670765)
[api-reference/beta/api/cloudpc-get.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-e5670765"></a>
### [api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml)
 - **Line 15127, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208041619174687-17010/BuildReport?accessString=704b5f684a80e8380f8ef88398ae98daee471a6613330663e89c5fb528025d26).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 17:50 UTC, isvargasmsft approved these changes

2022-08-09 23:19 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpc-get.md
> +### To get the cloudPC for the administrator
@xinliu22 , for each of the 5 method topics in this PR where you split the permissions table into two, one "for the administrator" and one "for the signed-in user", this practice is inconsistent with other topics. 

Technically all application permissions require admin consent. Other APIs that support application permissions specify those permissions in the same table as delegated permissions for a signed-in user.

Can you clarify for me if your APIs are different from what I described above in the context of application permissions?

2022-08-09 23:35 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpc-get.md
> +### To get the cloudPC for the administrator
Please take a look at how this topic documents the various syntax lines and the perms each syntax should use for which purpose: https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http#permissions

Please ignore the line in the "Permissions" section, after the perms table, that says:

* This scenario is only supported for the following call: GET /users/{user-id | user-principal-name}/chats

I wouldn't normally suggest to have that asterisked line in the "Permissions" section. The "HTTP request" section should be able to fully describe what each syntax line does and with which perms.

2022-08-10 09:12 UTC, opbld34 commented
Docs Build status updates of commit _[3735f71](https://github.com/xinliu22/microsoft-graph-docs/commits/3735f71fa492bf8b60ae431127a8bb2eac49b99c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208100910425443-17010/BuildReport?accessString=a9b7f6c92630d256a7ca28170f76b5294465d39a5fc7aa077ee7d9ed230a15ea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 09:36 UTC, xinliu22 commented on api-reference/beta/api/cloudpc-get.md
> +### To get the cloudPC for the administrator
@angelgolfer-ms ,
Thanks your suggestions. 
Our Cloud PC APIs has nothing special against other topics. But I saw many APIs have more than one permission table, also the `profilephoto-get.md`, is there any details I missed? 

Since Cloud PC APIs share the same permissions, `CloudPC.Read.All` and `CloudPC.ReadWrite.All`, explain which permissions to use in "Http request" section could make the doc more readable and understandable, your suggestion is excellent!

2022-08-15 08:32 UTC, RuiHou105 commented
@angelgolfer-ms  please help review this PR again as the schema already went alive. Thanks!

2022-08-15 23:29 UTC, angelgolfer-ms approved these changes
Thanks for the updates, @xinliu22 .

2022-08-16 03:38 UTC, opbld30 commented
Docs Build status updates of commit _[889a00e](https://github.com/xinliu22/microsoft-graph-docs/commits/889a00efc64b43e6d8027e2541b7f213802349a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reboot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reboot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reboot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-rename.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-rename.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-rename?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-troubleshoot.md](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/api/cloudpc-troubleshoot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-troubleshoot?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-17010) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/xinliu22/microsoft-graph-docs/blob/2022-05-23-xinliu2-cloudpc-action-apis/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160336469125-17010/BuildReport?accessString=ab13fa2cc4372f00712fe50ba2500f808db63a3c445cdfcf1e1c33350dadaa15).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:42 UTC, merged