Adding event grid support
microsoftgraph/microsoft-graph-docs pull request #17082
Opened 2022-05-27 18:14 UTC by Jumaodhiss

We are adding Azure event Grid as a change notification delivery option

2022-05-27 18:17 UTC, opbld31 commented
Docs Build status updates of commit _[558724b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/558724b38d294434114195f08bbddde1e51ee249)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) | [Details](#user-content-e43c8657161bb13d599af6c21cee2292-24d9d113)

<a id="e43c8657161bb13d599af6c21cee2292-24d9d113"></a>
### [concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md)
 - **Line 198, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 202, Column 200**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 210, Column 146**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#enable-event-grid-resource-provider' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 212, Column 232**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#authorize-partner-to-create-a-partner-topic' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 259, Column 262**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#activate-a-partner-topic' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 262, Column 245**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#subscribe-to-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 198, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 202, Column 200**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 202, Column 200**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 210, Column 146**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#enable-event-grid-resource-provider' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 212, Column 232**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#authorize-partner-to-create-a-partner-topic' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 259, Column 262**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#activate-a-partner-topic' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 262, Column 245**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#subscribe-to-events' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205271814223240-17082/BuildReport?accessString=59e3bef84112d6c6c7e97dcb5ca9bafe3b49f606d1d6b03bfd39870c0ac309e3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 04:17 UTC, Lauragra commented
@FaithOmbongi , can you review and approve this one please? Thanks.

2022-06-02 12:22 UTC, FaithOmbongi requested changes
Hi @Jumaodhiss,

Haven't yet reviewed the PR but a few suggestions.
- Move all the info from line 196 into a separate conceptual article. You can end the article with a "Next steps" with info from line 187-194.
- Please resolve all warnings and suggestions - All links should be relative links. For example, instead of `https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid`, use `/azure/event-grid/compare-messaging-services#azure-event-grid`.

2022-06-02 12:22 UTC, FaithOmbongi commented on concepts/change-notifications-delivery.md
> +#### Creating the subscription
```suggestion
#### Create the subscription
```

2022-06-02 12:22 UTC, FaithOmbongi commented on concepts/change-notifications-delivery.md
> +## Using Azure Event Grid to receive change notifications (Preview)
I suggest you move everything from this line to a separate article dedicated to Event Hub/Grid. Similar to what's live in the TOC for cloud printing, Teams, and Outlook.
```suggestion
## Use Azure Event Grid to receive change notifications (Preview)
```

2022-06-06 16:31 UTC, opbld33 commented
Docs Build status updates of commit _[b54c376](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b54c3767daf5dcfaac78f8254f9b0a97cfdc4c65)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) | [Details](#user-content-e43c8657161bb13d599af6c21cee2292-693f67a3)
[concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-grid?branch=pr-en-us-17082) | [Details](#user-content-818e02322926edc8ccd44543122b1a3e-693f67a3)
[concepts/get-notifications-delivered-in-event-hub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-hub.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-hub?branch=pr-en-us-17082) | [Details](#user-content-8d7984a9dacd390477db0f3247f00135-693f67a3)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) |

<a id="e43c8657161bb13d599af6c21cee2292-693f67a3"></a>
### [concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````

<a id="818e02322926edc8ccd44543122b1a3e-693f67a3"></a>
### [concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 11, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 15, Column 200**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 146**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#enable-event-grid-resource-provider' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 25, Column 232**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#authorize-partner-to-create-a-partner-topic' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````
 - **Line 11, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 15, Column 200**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 15, Column 200**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 146**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#enable-event-grid-resource-provider' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 25, Column 232**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#authorize-partner-to-create-a-partner-topic' will be broken in isolated environments. Replace with a relative link.`````

<a id="8d7984a9dacd390477db0f3247f00135-693f67a3"></a>
### [concepts/get-notifications-delivered-in-event-hub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-hub.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [S [...]

2022-06-06 17:28 UTC, opbld34 commented
Docs Build status updates of commit _[17f5226](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17f5226f788160aa963a731679cfcce124592771)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) | [Details](#user-content-e43c8657161bb13d599af6c21cee2292-ef25d87d)
[concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-grid?branch=pr-en-us-17082) | [Details](#user-content-818e02322926edc8ccd44543122b1a3e-ef25d87d)
[concepts/get-notifications-delivered-in-event-hub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-hub.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-hub?branch=pr-en-us-17082) | [Details](#user-content-8d7984a9dacd390477db0f3247f00135-ef25d87d)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) |

<a id="e43c8657161bb13d599af6c21cee2292-ef25d87d"></a>
### [concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````

<a id="818e02322926edc8ccd44543122b1a3e-ef25d87d"></a>
### [concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 11, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 15, Column 200**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 146**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#enable-event-grid-resource-provider' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 25, Column 232**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#authorize-partner-to-create-a-partner-topic' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 72, Column 262**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#activate-a-partner-topic' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 75, Column 245**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events#subscribe-to-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````
 - **Line 11, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 15, Column 200**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 15, Column 200**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 146**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#enable-event- [...]

2022-06-08 05:48 UTC, opbld32 commented
Docs Build status updates of commit _[8bd5166](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bd516680794308c95ed4117e188bea59c7c8b23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) | [Details](#user-content-e43c8657161bb13d599af6c21cee2292-9cc33391)
[concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-grid?branch=pr-en-us-17082) | [Details](#user-content-818e02322926edc8ccd44543122b1a3e-9cc33391)
[concepts/get-notifications-delivered-in-event-hub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-hub.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-hub?branch=pr-en-us-17082) | [Details](#user-content-8d7984a9dacd390477db0f3247f00135-9cc33391)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) |

<a id="e43c8657161bb13d599af6c21cee2292-9cc33391"></a>
### [concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````

<a id="818e02322926edc8ccd44543122b1a3e-9cc33391"></a>
### [concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Jumaodhiss, jafernan' is not a valid GitHub ID.`````
 - **Line 11, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 11, Column 426**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#supported-resources' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 13, Column 4**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/azure-active-directory-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 4**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/outlook-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 89**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'partner-events-overview.md'.`````
 - **Line 20, Column 21**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````
 - **Line 11, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 11, Column 426**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#supported-resources' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 11, Column 426**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#supported-resources. Otherwise, remove the view parameter.`````
 - **Line 13, Column 4**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/azure-active-directory-events' will be broken in isolated [...]

2022-06-16 15:53 UTC, opbld31 commented
Docs Build status updates of commit _[807684f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/807684f0b4978661aac640dd12b7c553c51d3dd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) | [Details](#user-content-e43c8657161bb13d599af6c21cee2292-8dcfcfcc)
[concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-grid?branch=pr-en-us-17082) | [Details](#user-content-818e02322926edc8ccd44543122b1a3e-8dcfcfcc)
[concepts/get-notifications-delivered-in-event-hub.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-hub.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/get-notifications-delivered-in-event-hub?branch=pr-en-us-17082) | [Details](#user-content-8d7984a9dacd390477db0f3247f00135-8dcfcfcc)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notifications-delivery?branch=pr-en-us-17082) |

<a id="e43c8657161bb13d599af6c21cee2292-8dcfcfcc"></a>
### [concepts/change-notifications-delivery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````

<a id="818e02322926edc8ccd44543122b1a3e-8dcfcfcc"></a>
### [concepts/get-notifications-delivered-in-event-grid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/get-notifications-delivered-in-event-grid.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get change notifications delivered in different ways - Microsoft Graph' is duplicated in: 'change-notifications-delivery.md(2,8), get-notifications-delivered-in-event-grid.md(2,8), get-notifications-delivered-in-event-hub.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Jumaodhiss, jafernan' is not a valid GitHub ID.`````
 - **Line 11, Column 1**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 11, Column 426**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#supported-resources' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 13, Column 4**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/azure-active-directory-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 4**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/outlook-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 89**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'partner-events-overview.md'.`````
 - **Line 66, Column 21**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/event-grid/subscribe-to-partner-events' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Change notifications can be delivered via different technologies, including webhooks and Azure Event Hubs.' is duplicated in 'change-notifications-delivery.md(3,14)', 'get-notifications-delivered-in-event-grid.md(3,14)', 'get-notifications-delivered-in-event-hub.md(3,14)'.`````
 - **Line 11, Column 1**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/compare-messaging-services#azure-event-grid' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 11, Column 426**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#supported-resources' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 11, Column 426**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#supported-resources. Otherwise, remove the view parameter.`````
 - **Line 13, Column 4**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/event-grid/azure-active-directory-events' will be broken in isolated [...]

2022-08-23 15:01 UTC, closed without merging