Added managedBy,cloudPcGroupDisplayName,gracePeriodInHours,localAdmin…
microsoftgraph/microsoft-graph-docs pull request #17089
Opened 2022-05-29 09:17 UTC by youche-microsoft

2022-05-29 09:28 UTC, opbld31 commented
Docs Build status updates of commit _[7a056d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a056d20227db3fbb20048751d8d76fe608c30c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :x:Error | | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-2705fb31)

<a id="dadb46177cd34394b5f8c0102b5cbac7-2705fb31"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md)
 - **Line 239, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-cloudpcprovisioningpolicy-3-csharp-snippets.md'.`````
 - **Line 243, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-cloudpcprovisioningpolicy-3-javascript-snippets.md'.`````
 - **Line 247, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-cloudpcprovisioningpolicy-3-objc-snippets.md'.`````
 - **Line 251, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-cloudpcprovisioningpolicy-3-java-snippets.md'.`````
 - **Line 255, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-cloudpcprovisioningpolicy-3-go-snippets.md'.`````
 - **Line 259, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-cloudpcprovisioningpolicy-3-powershell-snippets.md'.`````
 - **Line 256, Column 1**: **[Warning: code-block-indented - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205290917428586-17089/BuildReport?accessString=d74668c18633e32147c31eb4ce624580281a230e50ede08f3f784db65c04c94f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 03:20 UTC, opbld31 commented
Docs Build status updates of commit _[147d472](https://github.com/microsoftgraph/microsoft-graph-docs/commits/147d472a8c6e0b063ddb104c5015907d7f5765f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-8e6461a7)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |

<a id="dadb46177cd34394b5f8c0102b5cbac7-8e6461a7"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205300312427308-17089/BuildReport?accessString=ec592f213fc2898d03b0dbc17951023b7e8240f56917eacad9d499639d837b73).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 03:48 UTC, opbld33 commented
Docs Build status updates of commit _[9a21367](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a21367ff4b4f5b3e70bcf90e2cd55af2eff2f31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-d767c577)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="dadb46177cd34394b5f8c0102b5cbac7-d767c577"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205300340003974-17089/BuildReport?accessString=5678c8dc63f8a445eb26d79a28385054a087d169aab045b20fc7da7863dac828).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-30 03:53 UTC, opbld33 commented
Docs Build status updates of commit _[127ca39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/127ca3923bf85a1336a67fabf6b92c58b9452f1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-0595ccf3)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="dadb46177cd34394b5f8c0102b5cbac7-0595ccf3"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205300344066293-17089/BuildReport?accessString=bf8ba0febf7b16f7c6631784f8f86ddb7be6bf40a0f71bdb63d9b590bdc83f7a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-31 03:22 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|managedBy|[cloudPcManagementService](#cloudpcmanagementservice-values)|Specifies which services manage the Azure network connection. Possible values are: `windows365`, `devBox` and `unknownFutureVal
You don't need to define the enum `cloudPcManagementService `again in line 50, as actually you reuse the enum resource [here ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/15792/files#diff-e5720e91111f17527fbeb78ecf90164278efa64ede434328fd79f46cca833b57)right? So please remove line 50 - 56 and update this type to `[microsoft.graph.cloudPcManagementService](../resources/cloudpconpremisesconnection.md#cloudpcmanagementservice-values)`

2022-05-31 03:27 UTC, RuiHou105 requested changes
@youche-microsoft  please help resolve comments in this PR. Thanks

2022-05-31 03:31 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "04b7a9f2-66ab-4ba4-8732-8f65c5f8a966",
In the changelog, these Ids should be the same. According to your graph schema PR, the generated changloe uses this one a896f747-29fd-4ca3-8dc8-15056e9dc255. So please use this one for the six Ids here.

2022-05-31 05:25 UTC, opbld34 commented
Docs Build status updates of commit _[a90fba0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a90fba0bf7bf0bf12d04effd87b1da44854bf2c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-1078803c)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="dadb46177cd34394b5f8c0102b5cbac7-1078803c"></a>
### [api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md)
 - **Line 228, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202205310518199839-17089/BuildReport?accessString=729a48041437c739ef3989cc33bb08b846aaeb23071e67636af12bcbbe6d6503).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-31 05:40 UTC, youche-microsoft commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|managedBy|[cloudPcManagementService](#cloudpcmanagementservice-values)|Specifies which services manage the Azure network connection. Possible values are: `windows365`, `devBox` and `unknownFutureVal
Fixed

2022-05-31 05:40 UTC, youche-microsoft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "04b7a9f2-66ab-4ba4-8732-8f65c5f8a966",
Fixed

2022-05-31 06:03 UTC, RuiHou105 approved these changes

2022-05-31 06:13 UTC, RuiHou105 commented
@JarbasHorst @Lauragra , please help review this PR when you got time. Thanks!

2022-05-31 23:23 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/provisioningPolicies/{id}?$select=id,description,displayName,displayName,domainJoinConfiguration,imageDisplayName,imageId,imageTy
For clarity, please replace the placeholder "{id}" with a real-looking ID.

2022-05-31 23:23 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +{
For clarity, please provide real-looking values in this response body. Examples with real-looking values in the, request URL, requests, and response bodies help customers understand the API better. That's also the consistency bar for Microsoft Graph API docs.

2022-05-31 23:26 UTC, JarbasHorst commented
Hello @youche-microsoft, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [17103](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17103) into your branch to include my fixes and before addressing my new comments.

2022-06-01 03:06 UTC, opbld33 commented
Docs Build status updates of commit _[c1cb40c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1cb40ce359e712593708168803cef4571810bfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010258366444-17089/BuildReport?accessString=aaca0bac9bc8eded1b334a29d116d896c6865b882d7c0e52f7d165baebff22f6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 03:27 UTC, youche-microsoft commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +  },
Fixed, thanks!

2022-06-01 03:28 UTC, youche-microsoft commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|managedBy|[microsoft.graph.cloudPcManagementService](../resources/cloudpconpremisesconnection.md#cloudpcmanagementservice-values)|Specifies which services manage the Azure network connection. Possib
Fixed, thanks!

2022-06-01 03:30 UTC, youche-microsoft commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +{
I've made some of the values more real-looking. Could you please take a look to see if they require further changes?

2022-06-01 03:35 UTC, opbld32 commented
Docs Build status updates of commit _[6285730](https://github.com/microsoftgraph/microsoft-graph-docs/commits/628573001cbb44d271d36499a7b70d8cbc332d83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010324364409-17089/BuildReport?accessString=949d879795b64fabcecfb5c9b4fcb87d698b3d6c1a50cb27b2245884564a29f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 03:54 UTC, AshleyYangSZ approved these changes

2022-06-01 03:58 UTC, opbld34 commented
Docs Build status updates of commit _[c46b6c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c46b6c82fc6d5ae8a9adba70e694073b3f190806)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206010349578442-17089/BuildReport?accessString=90e6d940fdf75ac3d45b7fbe4505ff9db78b62e12ae43705e74c528594109995).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-01 22:29 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +{
Look great, thanks :)

2022-06-01 22:43 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [17116](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17116) into this branch to include my final edits.

2022-06-01 23:05 UTC, opbld31 commented
Docs Build status updates of commit _[ba898cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba898cd898ecd685c4537aed85b61d5a3f30ef43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206012302540595-17089/BuildReport?accessString=cf84821f0fe3320ebfba3d9f2452917d3102ad0e94b38de42c0e613d5bfc2965).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-02 00:59 UTC, AshleyYangSZ commented
> @Lauragra this PR is ready for final review. Please, merge PR [17116](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17116) into this branch to include my final edits.

A reminder the corresponding schema will go alive at around Jun 9th. This PR couldn't be merged before that.

2022-06-02 03:51 UTC, Lauragra approved these changes

2022-06-20 07:23 UTC, RuiHou105 commented
@Lauragra  As the graph schema already went alive last week, let's merge this one. Thanks :)

2022-06-20 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[14efae7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14efae7c3127f06c358375cd42ebc0add7805591)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-17089) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cloudPc/provisioningPolicies/addManagedBy/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206202342305814-17089/BuildReport?accessString=8378a62d412682a4c54a79faf05dece9de0706536916ecf3425cff30f59d36ad).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 02:30 UTC, merged