Adding Teams App Settings resource and operations.
microsoftgraph/microsoft-graph-docs pull request #17129
Opened 2022-06-02 19:07 UTC by subray2014

2022-06-02 19:09 UTC, opbld33 commented
Docs Build status updates of commit _[d95abfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d95abfd5fe66cedff8911f805bed7752c6887d36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) | [Details](#user-content-0c2326c790994dca5048e6cd8a6b29b0-819587b4)
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0c2326c790994dca5048e6cd8a6b29b0-819587b4"></a>
### [api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206021907104860-17129/BuildReport?accessString=6d2ed83c886e0b31d49a2b11369085dde7aecc282d7dee4a8fbce35651e4b762).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 22:19 UTC, AkJo commented on api-reference/beta/api/teamsappsettings-update.md
> +## Examples
Please add a description to the example like here:
https://docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&tabs=http#examples

2022-06-16 00:00 UTC, opbld34 commented
Docs Build status updates of commit _[7e5c404](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e5c404a84aa7509ea1d11bdeb966f5380d9dfbc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) | [Details](#user-content-0c2326c790994dca5048e6cd8a6b29b0-edb2b1ee)
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0c2326c790994dca5048e6cd8a6b29b0-edb2b1ee"></a>
### [api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206152357011732-17129/BuildReport?accessString=3e3268973d69b06b097f4f9a4d69ffc8a3f1f3b0b9bf7333104ea14526411b4b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 06:03 UTC, AkJo commented on api-reference/beta/api/teamsappsettings-update.md
> +ms.prod: "**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**"
Do not forget to fill out these.

2022-06-16 06:04 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|isChatResourceSpecificConsentEnabled|Boolean|Indicates whether Chat Resource Specific Consent has been enabled for the tenant.|
Indicates whether resource-specific consent for chats/meetings has been enabled for the tenant.

2022-06-16 06:05 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +
Please add a 'see also' to RSC concept doc.

2022-06-16 06:07 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|[Get teamsAppSettings](../api/teamsappsettings-get.md)|[teamsAppSettings](../resources/teamsappsettings.md)|Read the properties and relationships of a [teamsAppSettings](../resources/teamsappsetting
I would expect a description more along the lines of what we have here:
https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0

Get the tenant-wide settings for all Teams apps in the tenant.

2022-06-16 06:08 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|[Update teamsAppSettings](../api/teamsappsettings-update.md)|[teamsAppSettings](../resources/teamsappsettings.md)|Update the properties of a [teamsAppSettings](../resources/teamsappsettings.md) obje
Update the tenant-wide settings for all Teams apps in the tenant.

2022-06-16 06:23 UTC, AkJo commented on api-reference/beta/api/teamsappsettings-update.md
> +
Add a 'see also' cross-link to RSC doc.

2022-06-16 06:23 UTC, AkJo commented on api-reference/beta/api/teamsappsettings-get.md
> +
Add a 'see also' cross-link to RSC doc.

2022-06-16 06:28 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|isChatResourceSpecificConsentEnabled|Boolean|Indicates whether Chat Resource Specific Consent has been enabled for the tenant.|
If set to true, allowed Teams apps that required resource-specific permissions can be installed inside chats and meetings.

Please paraphrase/format based on latest guidance from content writing team.

2022-06-16 06:29 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|isChatResourceSpecificConsentEnabled|Boolean|Indicates whether Chat Resource Specific Consent has been enabled for the tenant.|
If set to false, then the installation of any Teams app that requires resource-specific permissions to a chat or a meeting will be blocked.

2022-06-16 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[03deb34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03deb34251283111aeb7b6519544a11f9a62f1d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206161935567151-17129/BuildReport?accessString=d86e8fd3f3b232fd9c3a51beb1744cdf9e9636a18f8872e2ff4cb57eced43eca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 19:45 UTC, opbld32 commented
Docs Build status updates of commit _[51c063c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51c063c052bee33843ead2728a396f038877cc08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206161943198980-17129/BuildReport?accessString=fecc0a31dc97296e393d343a90f2e13b20db5e8e09bbd3f1389a521693698994).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 19:53 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +Represents tenant-wide settings for all [Teams apps](teamsapp.md). Organizations use Teams apps to connect with their customers, provide services, and share information. These settings include the ab
This seems out of place.

2022-06-16 19:53 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|isChatResourceSpecificConsentEnabled|Boolean|Indicates whether resource-specific consent fir chats/meetings has been enabled for the tenant. If true, allowed Teams apps that require resource-specifi
typo

2022-06-16 19:55 UTC, AkJo commented on api-reference/beta/resources/teamsAppSettings.md
> +|isChatResourceSpecificConsentEnabled|Boolean|Indicates whether resource-specific consent fir chats/meetings has been enabled for the tenant. If true, allowed Teams apps that require resource-specifi
Perhaps rephrase to>

If true, Teams apps that are allowed in the tenant and require resource-specific permissions can be installed inside chats and meetings. 


I will let the content writing team make the final call on this.

2022-06-16 19:57 UTC, AkJo commented on api-reference/beta/api/teamsappsettings-update.md
> +|isChatResourceSpecificConsentEnabled|Boolean|Indicates whether Chat Resource Specific Consent has been enabled for the tenant.|
It would make sense to copy over the description from the table inside teamsAppSettings file.

2022-06-16 19:58 UTC, AkJo commented on api-reference/beta/api/teamsappsettings-get.md
> +### Example 1: Enable Resource Specific Consent for chats
Enable installation of apps that require resource-specific consent in chats/meetings.

2022-06-16 21:47 UTC, opbld32 commented
Docs Build status updates of commit _[82de2fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82de2fa3a7534bb73d209f2bf57ba11e3162debf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206162145053483-17129/BuildReport?accessString=280f2bf982a40d017f1ec46321c844a6c1f5eac58eb76039823e51ed9fdf8b06).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 22:29 UTC, opbld30 commented
Docs Build status updates of commit _[04c3cd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04c3cd09dbafd4eba4f9be5fb378b8e72114094f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206162227079375-17129/BuildReport?accessString=b8db0635c794e29088676bb6829424b3dfaa4d58c0eba28e858b22a2025c8423).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 23:05 UTC, AkJo approved these changes

2022-06-27 21:48 UTC, AkJo commented on concepts/known-issues.md
> +
is currently being rolled out and might not be visible in Azure Portal yet.

2022-06-27 21:54 UTC, AkJo approved these changes

2022-06-28 03:03 UTC, opbld34 commented
Docs Build status updates of commit _[05653cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05653cd40a18eca65280bf583b6a25095da86cb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsAppSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamsAppSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17129) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206280300453786-17129/BuildReport?accessString=f350215c36cf10a163b905cf6e0aa74cbda1d68a9c6efa29b9d9ef5e910f357b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-28 16:24 UTC, Danielabom commented on api-reference/beta/api/teamsappsettings-get.md
> +### Request
Please change the request and response header to ####.

2022-06-28 16:24 UTC, Danielabom commented on api-reference/beta/api/teamsappsettings-get.md
> +### Response
Please change the request and response header to ####.

2022-06-28 16:26 UTC, Danielabom commented on api-reference/beta/api/teamsappsettings-update.md
> +### Response
In Examples, please change the request and response header to ####.

2022-06-28 16:30 UTC, Danielabom commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "ChangeType": "Addition",
Hi @subray2014, isn't this a relationship? Also, if it belongs to teamwork, shouldn't we update the teamwork resource file? Please double-check, thanks!

2022-06-28 16:56 UTC, Danielabom requested changes
Hi Subhajit, thank you for working on this PR. I added some comments, please review them.

2022-06-28 17:06 UTC, subray2014 commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "ChangeType": "Addition",
Unfortunately, there's no teamwork resource file and no APIs are supported on that particular node. I can take a followup item to see what we can add.

2022-06-29 20:26 UTC, Danielabom commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "ApiChange": "Resource",
Hi @subray2014, thank you for addressing my comments, just one last thing. The APi change should be "Relationship."

2022-06-29 20:28 UTC, Danielabom commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the [teamsAppSettings](https://docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta) resource",
The description should be 
```suggestion
          "Description": "Added the **teamsAppSettings** navigation property to the [teamsAppSettings](https://docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta) resource",
```

2022-06-29 20:30 UTC, Danielabom commented on concepts/known-issues.md
> +
Based on our chat, @subray2014 will address the permissions reference in a separate PR (once the permissions deployment is complete). This is likely to happen within the next 2-4 weeks. @Lauragra, I will follow-up. Thanks.

2022-06-29 20:35 UTC, subray2014 commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the [teamsAppSettings](https://docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta) resource",
"to the teamwork resource" right?

2022-06-29 20:47 UTC, Danielabom approved these changes
The changes are in place. Thank you for working on this PR @subray2014.

2022-07-01 04:26 UTC, Lauragra commented on api-reference/beta/resources/teamsAppSettings.md
> +title: "teamsAppSettings resource type"
All file names should be all lowercase; please rename this file to teamsappsettings.md.

2022-07-01 04:27 UTC, Lauragra commented on api-reference/beta/api/teamsappsettings-get.md
> +title: "Get teamsAppSettings"
Please surface the new resource type and methods in the TOC, so add entries in the toc.yml file in the /beta folder.

2022-07-02 01:15 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Teams app settings
It looks like you're surfacing these topics in the Teamwork node under Users, but I don't think these operations are specific to the signed-in user. Should they be surfaced under the Teamwork node, for example next to where we surface Teams apps: https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-beta&branch=pr-en-us-17129?

2022-07-02 05:52 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Teams app settings
You are right, that would be a mistake. These new entries should be here instead.
![image](https://user-images.githubusercontent.com/25969716/176988435-ad37164d-8541-4ae6-ba98-56b39a558fa4.png)

2022-07-05 17:03 UTC, subray2014 commented on api-reference/beta/toc.yml
> +        - name: Teams app settings
Adding this under the App node instead.

2022-07-05 17:08 UTC, opbld32 commented
Docs Build status updates of commit _[a44ec24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a44ec240e7ab53e7ee4ff9d7d4396f524e2210a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsappsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamsappsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17129) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051704424915-17129/BuildReport?accessString=b5458588a4e02ae86e2dfc41c46221fde99400c56402d62ad875b3f41d39beb8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 17:16 UTC, opbld30 commented
Docs Build status updates of commit _[2a6166f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a6166fbce0920728d4b47203e23abd617fa79ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsappsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamsappsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17129) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051714364370-17129/BuildReport?accessString=6ef149f256e234f6f1e1fe64a1b77a7d4799696793dea71973b2678e858c153c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 19:20 UTC, opbld34 commented
Docs Build status updates of commit _[8183a2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8183a2b420419a232c7c752060b875ca8c4f1a43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsappsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamsappsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17129) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051917595269-17129/BuildReport?accessString=67119f4e3e7cddfe26595a0ffdf302ee5e8dd66aa47d285ffb0c8307360ac616).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 03:11 UTC, opbld30 commented
Docs Build status updates of commit _[6d8ed24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d8ed245ec8314499adf26ca44eda99fb0d6dd6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsappsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamsappsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17129) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207060309317771-17129/BuildReport?accessString=b26a9d103bb561d40b9b017eee9d73cba16e8705e19637f4d91af60f6eb65c68).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 03:17 UTC, opbld30 commented
Docs Build status updates of commit _[56e07cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56e07cd0618e3c419f8e04da91617f42c94825ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/api/teamsappsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/api/teamsappsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-update?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamsappsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamsappsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappsettings?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/resources/teamwork.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/resources/teamwork.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwork?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappsettings-get?view=graph-rest-beta&branch=pr-en-us-17129) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/subray/teamsAppSettings/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17129) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207060315014506-17129/BuildReport?accessString=3d5a1025f9491942304303222d89545dba6fa1f688340beb407a815e8130558a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 03:18 UTC, merged