Skhalid ficapi updates
microsoftgraph/microsoft-graph-docs pull request #17162
Opened 2022-06-06 19:38 UTC by shahzad-khalid

Two updates:

1. Remove the default from audiences property of federated identity credentials. Instead provide suggested/recommended value when using Azure AD.
2. Remove the statement: "The federated identity credentials API is not available in national cloud deployments". FIC API is now supported in national clouds.

2022-06-06 19:40 UTC, opbld33 commented
Docs Build status updates of commit _[a74856e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a74856e6b8f189b4d2ea56148af73345f3e77b87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206061938149549-17162/BuildReport?accessString=11f272ab1f39e33bfc3e6d17d87479d00c292443a963cda5319c10f641a4e2c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 09:30 UTC, FaithOmbongi approved these changes
Thank you @shahzad-khalid for raising these fixes. Approved with suggestions for minor fixes.

2022-06-07 09:30 UTC, FaithOmbongi commented on api-reference/beta/api/application-post-federatedidentitycredentials.md
> +|audiences|String collection|Lists the audiences that can appear in the external token. This field is mandatory, This field is mandatory, and for Azure AD you should set its value to `api://AzureADTo
GLOBAL: suggestion
```suggestion
|audiences|String collection|Lists the audiences that can appear in the external token. This field is mandatory and should be set to `api://AzureADTokenExchange` for Azure AD. It says what Microsoft identity platform should accept in the `aud` claim in the incoming token. This value represents Azure AD in your external identity provider and has no fixed value across identity providers - you may need to create a new application registration in your identity provider to serve as the audience of this token. Required.|
```

2022-06-17 18:57 UTC, opbld30 commented
Docs Build status updates of commit _[74a40db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74a40db80cd456a8927cba93b600650d04c8189e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206171855065427-17162/BuildReport?accessString=bec0203309ad3223e7a02f4a3d0c6faa70f9bb5fcd95c22ea9439b23ac24100b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 18:59 UTC, opbld34 commented
Docs Build status updates of commit _[181c57e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/181c57e8231c0f94f98b12d07cec1dfd4ad412d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206171855436188-17162/BuildReport?accessString=1cab55c0f6018e25a5775817a7b810dd8eb913296f69df1c0d8a8b91b3db32d3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 22:17 UTC, opbld34 commented
Docs Build status updates of commit _[dcdb5de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcdb5de63c9fad48c641f22098bd8edf62c5d09a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206172213409062-17162/BuildReport?accessString=20a6f1781b15129c9de8b1f17f1fb3e09fd44b8b4c003ad55e1d94e78ca52a75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 22:21 UTC, shahzad-khalid commented
@FaithOmbongi I've made your suggested global change in rest of the docs. Please review/approve and merge into main. Thanks

2022-06-18 23:41 UTC, opbld31 commented
Docs Build status updates of commit _[599e657](https://github.com/microsoftgraph/microsoft-graph-docs/commits/599e657eb4cc079148da9701bfeada9bba12eafb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-58d0d738)
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-58d0d738"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 926, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredentials-overview.md'.`````
 - **Line 928, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredential.md'.`````
 - **Line 931, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-list-federatedidentitycredentials.md'.`````
 - **Line 933, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-post-federatedidentitycredentials.md'.`````
 - **Line 935, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/federatedidentitycredential-get.md'.`````
 - **Line 937, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/federatedidentitycredential-update.md'.`````
 - **Line 939, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/federatedidentitycredential-delete.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206182339248373-17162/BuildReport?accessString=dc58b79162cf918731e1742d5f2dfd37c55972f983606d4d6e350b027cf8eb59).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-18 23:53 UTC, opbld31 commented
Docs Build status updates of commit _[b37da0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b37da0eec5eab3838e6b32855e5cb662d616811f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-be47fce3)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-be47fce3)
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |

<a id="d0c3f8a959ad106bf1b7e6523204cf76-be47fce3"></a>
### [api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/application-list-federatedidentitycredentials.md'.`````
 - **Line 23, Column 95**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 23, Column 199**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/application-post-federatedidentitycredentials.md'.`````
 - **Line 24, Column 96**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 184**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-get.md'.`````
 - **Line 25, Column 79**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 197**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-update.md'.`````
 - **Line 26, Column 117**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-delete.md'.`````
 - **Line 27, Column 100**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-be47fce3"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 926, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredentials-overview.md'.`````
 - **Line 928, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredential.md'.`````
 - **Line 931, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-list-federatedidentitycredentials.md'.`````
 - **Line 933, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-post-federatedidentitycredentials.md'.`````
 - **Line 935, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/federatedidentitycredential-get.md'.`````
 - **Line 937, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/federatedidentitycredential-update.md'.`````
 - **Line 939, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: ' [...]

2022-06-19 00:03 UTC, opbld34 commented
Docs Build status updates of commit _[cc085ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc085ec5d29d85bd0f92a66da2762724254132e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-9076a0f7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9076a0f7)
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

<a id="d0c3f8a959ad106bf1b7e6523204cf76-9076a0f7"></a>
### [api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/application-list-federatedidentitycredentials.md'.`````
 - **Line 23, Column 95**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 23, Column 199**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/application-post-federatedidentitycredentials.md'.`````
 - **Line 24, Column 96**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 184**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-get.md'.`````
 - **Line 25, Column 79**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 197**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-update.md'.`````
 - **Line 26, Column 117**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-delete.md'.`````
 - **Line 27, Column 100**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-9076a0f7"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 926, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredentials-overview.md'.`````
 - **Line 928, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredential.md'.`````
 - **Line 931, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-list-federatedidentitycredentials.md'.`````
 - **Line 933, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-post-federatedidentitycredentials.md'.`````
 - **Line 935, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/federatedidentitycredential-get.md'.`````
 - **Line 937, Column 23**: **[Warning: file-not-found -  [...]

2022-06-19 00:11 UTC, opbld31 commented
Docs Build status updates of commit _[90d0354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90d0354694e264ae1a9eb68935f753a20dbceef5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-300196dc)
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-300196dc)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-300196dc)

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-300196dc"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````
 - **Line 14, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 42, Column 58**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 44, Column 80**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 57, Column 72**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="d0c3f8a959ad106bf1b7e6523204cf76-300196dc"></a>
### [api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md)
 - **Line 23, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/application-list-federatedidentitycredentials.md'.`````
 - **Line 23, Column 95**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 23, Column 199**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 96**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 184**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-get.md'.`````
 - **Line 25, Column 79**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 197**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 26, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-update.md'.`````
 - **Line 26, Column 117**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 27, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-delete.md'.`````
 - **Line 27, Column 100**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-300196dc"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 926, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredentials-overview.md'.`````
 - **Line 928, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/federatedidentitycredential.md'.`````
 - **Line 931, Column 23**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/application-list-federatedidentitycredentials.md'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190009212232-17162/BuildReport?accessStri [...]

2022-06-19 00:16 UTC, opbld33 commented
Docs Build status updates of commit _[6eeb6fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6eeb6fe637787cd7e53211502a3d69721249a1b9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-cea918ef)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-cea918ef)
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-cea918ef)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-cea918ef)

<a id="6eef1fbf820d230506d8df85a8bf3be5-cea918ef"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-cea918ef"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````
 - **Line 14, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 42, Column 58**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 44, Column 80**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 57, Column 72**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="d0c3f8a959ad106bf1b7e6523204cf76-cea918ef"></a>
### [api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md)
 - **Line 23, Column 95**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 23, Column 199**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 96**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 24, Column 184**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/federatedidentitycredential-get.md'.`````
 - **Line 25, Column 79**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 25, Column 197**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190014283880-17162/BuildReport?accessString=8800d5fd4b6ad287f6477da76062ce668e09c75bd66d20afc7823a36e12afa5f).

If you see build warnings/erro [...]

2022-06-19 00:21 UTC, opbld34 commented
Docs Build status updates of commit _[7a3b837](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a3b83704dae12dbb1e5154fe6d17f27881e2ef2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-d357d13b)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-d357d13b)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-d357d13b)
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-d357d13b)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d357d13b)

<a id="6eef1fbf820d230506d8df85a8bf3be5-d357d13b"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-d357d13b"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````
 - **Line 14, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 42, Column 58**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 44, Column 80**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 57, Column 72**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="b1d7805db5fd3230fdfaddfffde05131-d357d13b"></a>
### [api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md)
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-federatedidentitycredential-java-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-federatedidentitycredential-go-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 44**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190019198418-17162/BuildReport?accessString=68dc6590b25042885bece353c3ab92bf02576f0eb6b6d8023748ff4b079346d0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/he [...]

2022-06-19 00:23 UTC, opbld33 commented
Docs Build status updates of commit _[b0a44ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0a44cebe689ec5483c7e627c87311b64372dbbf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-2b37aafc)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-2b37aafc)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-2b37aafc)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-2b37aafc)
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-2b37aafc)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-2b37aafc)

<a id="6eef1fbf820d230506d8df85a8bf3be5-2b37aafc"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-2b37aafc"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````
 - **Line 14, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 42, Column 58**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 44, Column 80**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 57, Column 72**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-2b37aafc"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190020504146-17162/BuildReport?acc [...]

2022-06-19 00:26 UTC, opbld32 commented
Docs Build status updates of commit _[5b3bcde](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b3bcde93af9e1a7c36c092a2aeab7e411f9ab1f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-4264fcba)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-4264fcba)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-4264fcba)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-4264fcba)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-4264fcba)
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-4264fcba)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-4264fcba)

<a id="6eef1fbf820d230506d8df85a8bf3be5-4264fcba"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 49, Column 81**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-4264fcba"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````
 - **Line 14, Column 14**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 42, Column 58**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 44, Column 80**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````
 - **Line 57, Column 72**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-4264fcba"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````
 - **Line 14, Column 11**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/federatedidentitycredential.md'.`````

This comment li [...]

2022-06-19 05:05 UTC, opbld34 commented
Docs Build status updates of commit _[3b1a8eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b1a8eb381ee86b7c9b65bbcb11501c0519f958c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-89dd1644)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-89dd1644)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-89dd1644)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-89dd1644)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-89dd1644)
[api-reference/v1.0/api/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-d0c3f8a959ad106bf1b7e6523204cf76-89dd1644)
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :warning:Warning | | [Details](#user-content-f7358c5b58d96fcd8b41ea54b4f8f728-89dd1644)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-89dd1644)

<a id="6eef1fbf820d230506d8df85a8bf3be5-89dd1644"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-89dd1644"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-89dd1644"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````

<a id="b1d7805db5fd3230fdfaddfffde05131-89dd1644"></a>
### [api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md)
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-federatedidentitycredential-java-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-federatedidentitycredential-go-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-federatedidentitycredential-powershell-snippets.md'.`````

<a id="ab0ecf83df250e95d3c2e0968c08efaa-89dd1644"></a>
### [api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1 [...]

2022-06-19 05:07 UTC, opbld34 commented
Docs Build status updates of commit _[9e03259](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e032596f5ad4965819638d2d5bf4295f4a9c412)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-29e769b9)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-29e769b9)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-29e769b9)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-29e769b9)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-29e769b9)
[api-reference/v1.0/api/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredentials-overview.md) | :warning:Warning | | [Details](#user-content-fc69a3ff49607d7c323c1802f5530de3-29e769b9)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-29e769b9)

<a id="6eef1fbf820d230506d8df85a8bf3be5-29e769b9"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-29e769b9"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-29e769b9"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````

<a id="b1d7805db5fd3230fdfaddfffde05131-29e769b9"></a>
### [api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md)
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-federatedidentitycredential-java-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-federatedidentitycredential-go-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-federatedidentitycredential-powershell-snippets.md'.`````

<a id="ab0ecf83df250e95d3c2e0968c08efaa-29e769b9"></a>
### [api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md)
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-federatedidentitycredential-csharp-snippets.md'.`````

This comment lists only the first 25  [...]

2022-06-19 05:10 UTC, opbld34 commented
Docs Build status updates of commit _[d29b009](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d29b0096da7fe4d0c5a1c00e265165eb67f34374)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-4ed9f144)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-4ed9f144)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-4ed9f144)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-4ed9f144)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-4ed9f144)
[api-reference/v1.0/api/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredentials-overview.md) | :warning:Warning | | [Details](#user-content-fc69a3ff49607d7c323c1802f5530de3-4ed9f144)
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :warning:Warning | | [Details](#user-content-a5e639506313a33528fb39c2c28b4479-4ed9f144)

<a id="6eef1fbf820d230506d8df85a8bf3be5-4ed9f144"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-4ed9f144"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-4ed9f144"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````

<a id="b1d7805db5fd3230fdfaddfffde05131-4ed9f144"></a>
### [api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md)
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-federatedidentitycredential-java-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-federatedidentitycredential-go-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-federatedidentitycredential-powershell-snippets.md'.`````

<a id="ab0ecf83df250e95d3c2e0968c08efaa-4ed9f144"></a>
### [api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md)
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-federa [...]

2022-06-19 05:12 UTC, opbld30 commented
Docs Build status updates of commit _[1117194](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1117194eb7cdfcfc0ea34b2d4ecd5bf5f42c7829)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-bc6e6e57)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-bc6e6e57)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-bc6e6e57)
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :x:Error | | [Details](#user-content-b1d7805db5fd3230fdfaddfffde05131-bc6e6e57)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-bc6e6e57)

<a id="6eef1fbf820d230506d8df85a8bf3be5-bc6e6e57"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-bc6e6e57"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-bc6e6e57"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````

<a id="b1d7805db5fd3230fdfaddfffde05131-bc6e6e57"></a>
### [api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md)
 - **Line 67, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-federatedidentitycredential-java-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-federatedidentitycredential-go-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-federatedidentitycredential-powershell-snippets.md'.`````

<a id="ab0ecf83df250e95d3c2e0968c08efaa-bc6e6e57"></a>
### [api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md)
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-federatedidentitycredential-csharp-snippets.md'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190508006465-17162/BuildReport?accessString=5717be606944ad802f11faed495536b0cda47ff0e5a3cc642b068eb282486809).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [ [...]

2022-06-19 05:36 UTC, opbld34 commented
Docs Build status updates of commit _[6f7ecd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f7ecd83e6156075cdb0e244e1d1524d19c6948f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-b02f4fd3)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-b02f4fd3)
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :x:Error | | [Details](#user-content-c149da53cfe8c4b5662c9b9e1a8651b1-b02f4fd3)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-b02f4fd3)

<a id="6eef1fbf820d230506d8df85a8bf3be5-b02f4fd3"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-b02f4fd3"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

<a id="c149da53cfe8c4b5662c9b9e1a8651b1-b02f4fd3"></a>
### [api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/delete-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-federatedidentitycredential-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-federatedidentitycredential-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-federatedidentitycredential-powershell-snippets.md'.`````

<a id="ab0ecf83df250e95d3c2e0968c08efaa-b02f4fd3"></a>
### [api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md)
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 92, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 96, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 100, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/update-federatedidentitycredential-java-snippets.md'.`````
 - **Line 104, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/update-federatedidentitycredential-go-snippets.md'.`````
 - **Line 108, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/update-federatedidentitycredential-powershell-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190534447841-17162/BuildReport?accessString=7a384e1a90e033892fcf83782ab0e259336117dcb16af0c6a95626baf92285b5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-vali [...]

2022-06-19 05:39 UTC, opbld32 commented
Docs Build status updates of commit _[b87defa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b87defab6132cd29b4708d374949a9b1a5d2d595)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-509f0dcb)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-509f0dcb)
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :x:Error | | [Details](#user-content-ab0ecf83df250e95d3c2e0968c08efaa-509f0dcb)

<a id="6eef1fbf820d230506d8df85a8bf3be5-509f0dcb"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-509f0dcb"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

<a id="ab0ecf83df250e95d3c2e0968c08efaa-509f0dcb"></a>
### [api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md)
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 92, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 96, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 100, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/update-federatedidentitycredential-java-snippets.md'.`````
 - **Line 104, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/update-federatedidentitycredential-go-snippets.md'.`````
 - **Line 108, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/update-federatedidentitycredential-powershell-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190537350200-17162/BuildReport?accessString=63922241faad6b9b55c260f57ef28baff39f1a5ed9c538ae34731799c47c4ed9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-19 05:42 UTC, opbld30 commented
Docs Build status updates of commit _[2497a51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2497a516d1b90dac7929eff15ef24be02b40c494)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-6eef1fbf820d230506d8df85a8bf3be5-84845ad2)
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-84845ad2)

<a id="6eef1fbf820d230506d8df85a8bf3be5-84845ad2"></a>
### [api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md)
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-federatedidentitycredential-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-federatedidentitycredential-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/list-federatedidentitycredential-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-federatedidentitycredential-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-federatedidentitycredential-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-federatedidentitycredential-powershell-snippets.md'.`````

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-84845ad2"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190538586681-17162/BuildReport?accessString=dbe0dec7d42614a650e3de8603b1212e5d611ce337b90122741be79b884f26ee).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-19 05:44 UTC, opbld32 commented
Docs Build status updates of commit _[8d26b23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d26b235ff4f278cf747f55137e736d03a9c5cba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190541085216-17162/BuildReport?accessString=4125658284d740cb08ae1a8a3b534b4e9abcedc1c2ed0caa1f90582914502470).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-19 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[fc985ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc985caaefd1c92f60ccd7321646a33ecb39b76d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :x:Error | | [Details](#user-content-8ae4c9a727815ffd7935a34e3d5f9bf7-4379feed)

<a id="8ae4c9a727815ffd7935a34e3d5f9bf7-4379feed"></a>
### [api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-federatedidentitycredential-from--csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-federatedidentitycredential-from--javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-federatedidentitycredential-from--objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-federatedidentitycredential-from--java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/create-federatedidentitycredential-from--go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/create-federatedidentitycredential-from--powershell-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206190540083927-17162/BuildReport?accessString=8f31019f4a5eab3f577e9ca683f7328d9539d1f914e21babad1e5aab520b8459).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:46 UTC, opbld30 commented
Docs Build status updates of commit _[f9d2966](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9d2966c0d28783ebaa7126db3f2c6eec5fa143c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201844296088-17162/BuildReport?accessString=55f4e90ff956ed36ba6e1ded4526f0ff3434f598ad3197eb3ac53f0535fcd754).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:56 UTC, opbld33 commented
Docs Build status updates of commit _[45f5aac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45f5aac859ff3ee4a390470ecd83a1f4564da691)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201854318922-17162/BuildReport?accessString=52321b807b8abf6cc3007a64ad45df29385640f164277c3919012893180d0ece).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 18:59 UTC, opbld33 commented
Docs Build status updates of commit _[5cf358c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cf358c1029969f93eb6b2e3badfa1b11fd60d05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201855170531-17162/BuildReport?accessString=1667c85c21fe5eb419dcf51901b0434bfa036385be134d0c1b3c20e71567ab98).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:01 UTC, opbld31 commented
Docs Build status updates of commit _[1468ac0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1468ac0ed48bd1027df1abf03de07941de4012cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201858334017-17162/BuildReport?accessString=2825feac186795ac705f743810979920df7f7e48b39325b7bafd18ff15b596e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[1212e26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1212e26f5b624bd61ff1e319a50cdf2dab689108)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201910388067-17162/BuildReport?accessString=464de03b63d1845bae2a4f1f111586e7f0d8f6ff11bc6a12446319621abb613f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:16 UTC, opbld31 commented
Docs Build status updates of commit _[49b759c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49b759c563e45a598b95e31ee5b29c96aac1b7fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201913302305-17162/BuildReport?accessString=07ec19afa2f812278e34b942d160a0d2bb0ed2e7f88e95d0bd9215fb49634362).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 21:12 UTC, opbld34 commented
Docs Build status updates of commit _[6597c46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6597c46942759d93691e22f6f25cf96174148a53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206212110374097-17162/BuildReport?accessString=0faa52e2777ec763768efc830fb287b425d4de82e32c808ab886f7ec5919e752).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 23:50 UTC, opbld33 commented
Docs Build status updates of commit _[258b399](https://github.com/microsoftgraph/microsoft-graph-docs/commits/258b3996ef48786e001992c6db5057e02bf097fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206212347313974-17162/BuildReport?accessString=a3a9d2833ccdaf41ea3ac7f0e62dd7b8ed632cd26c22c2a66a2d62dd4ff0edd0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 23:59 UTC, opbld34 commented
Docs Build status updates of commit _[2fb4c97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fb4c97521f21d9132d1cb824f275b94776d7e02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206212357185130-17162/BuildReport?accessString=3e8d3a285fd96b644789e12e1482ad8e1e899b61ad5551a19ca07c90b4a85880).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:04 UTC, opbld32 commented
Docs Build status updates of commit _[68d2647](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68d2647ff28ff4777ec085136f479d99cbfb1bd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220001394598-17162/BuildReport?accessString=49e1aa6a3e7c401e8efcc6e993b9084d57b49041b0711dcb8dd82b0ddd9b96bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:09 UTC, opbld34 commented
Docs Build status updates of commit _[dfcb2b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfcb2b16c2fe7c85956ebb6453903fd94b090a5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220007090927-17162/BuildReport?accessString=32a6497ff7c7e92ccb95a4538e3c965d011b3f95a4d421f6764375c88b229aee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:11 UTC, opbld34 commented
Docs Build status updates of commit _[fc785fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc785fc07c6150df8933102a4f1da8168cbe1609)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220008277990-17162/BuildReport?accessString=62dcb07398420332dd74a0e3010d6e9c082372407c1c8cba4ad04c739bfa5783).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:14 UTC, opbld34 commented
Docs Build status updates of commit _[313bef6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/313bef6c5fd8489cef2614bc0b0a7692108a1937)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220011104209-17162/BuildReport?accessString=22bb60311631659e4c99b21f21c77bb41e0c24eea32e6283388cd3998b070d47).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 16:32 UTC, opbld30 commented
Docs Build status updates of commit _[e216b81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e216b815d276f6aa3e75a5f78059618ed31a79a0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3e1dd9c1)

<a id="3e1dd9c1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221632025024-17162/BuildReport?accessString=e66a7a3c99f6177cb4a1b47a43b3f9f5567a661faae76092167cef7299941211).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 16:34 UTC, opbld33 commented
Docs Build status updates of commit _[b5f0bb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5f0bb002f6a00ad6ebe64b10e347e47f9089364)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-00fd7fcb)

<a id="00fd7fcb"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221633375724-17162/BuildReport?accessString=80381c5f63f154d046fe5ed837748f3bf7ee81bb08a9ae05de54fcc8ebc7f6fe).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 17:02 UTC, opbld30 commented
Docs Build status updates of commit _[cf37da7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf37da73253930bb82f6cef86a844e778160f6ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221659549816-17162/BuildReport?accessString=1aef961106eb967da693371345f868d0bad01fcc0ace3037b7bb21985bc35c2a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 18:25 UTC, FaithOmbongi requested changes
Thank you @shahzad-khalid for your work in this PR.

- One gap: Please document the federatedIdentityCredentials relationship in the application.md file
- Sync: Please document in the beta docs the 600-character limit for some of the properties - for consistency and completeness

Otherwise, I've left additional suggestions for minor fixes.

2022-06-22 18:25 UTC, FaithOmbongi commented on api-reference/v1.0/api/federatedidentitycredential-update.md
> +The following table specifies the properties that can be updated.
Should be an INCLUDE for maintainability
```suggestion
[!INCLUDE [table-intro](../../includes/update-property-table-intro.md)]
```

2022-06-22 18:25 UTC, FaithOmbongi commented on api-reference/v1.0/api/federatedidentitycredential-update.md
> +|subject|String|<li>For Azure AD issuer, the `objectId` of the servicePrincipal (can represent a managed identity) that can impersonate the app. The object associated with this GUID needs to exist in
Could you also document apply these limits in the beta doc?

2022-06-22 18:25 UTC, FaithOmbongi commented on api-reference/v1.0/api/federatedidentitycredential-delete.md
> +description: "Deletes a federatedIdentityCredential object."
```suggestion
description: "Delete a federatedIdentityCredential object."
```

2022-06-22 18:25 UTC, FaithOmbongi commented on api-reference/v1.0/api/federatedidentitycredential-delete.md
> +Deletes a [federatedIdentityCredential](../resources/federatedidentitycredential.md) object from an application.
```suggestion
Delete a [federatedIdentityCredential](../resources/federatedidentitycredential.md) object from an application.
```

2022-06-22 18:25 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [federatedIdentityCredential](https://docs.microsoft.com/en-us/graph/api/resources/federatedIdentityCredential?view=graph-rest-1.0) resource",
Suggested enhancement
```suggestion
          "Description": "Added the [federatedIdentityCredential](https://docs.microsoft.com/en-us/graph/api/resources/federatedIdentityCredential?view=graph-rest-1.0) resource and associated methods. A federated identity credential is a secure method for managing an application's credentials that allows a tenant's cloud applications to access Azure AD without using secrets and certificates.",
```

2022-06-22 18:25 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "servicePrincipal"
Let's remove the servicePrincipal entry until we sort out what needs to be documented.
```suggestion
```

2022-06-22 18:25 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Directory management"
Minor fix
```suggestion
       "WorkloadArea": "Applications",
      "SubArea": ""
```

2022-06-22 18:46 UTC, opbld30 commented
Docs Build status updates of commit _[5f83a70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f83a70cf58300f53b6838678212a09eb49c0c71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221844074322-17162/BuildReport?accessString=bf864e110400fb112c89baa383a624428191e6280ba2a35be32af6a460627288).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 18:50 UTC, opbld30 commented
Docs Build status updates of commit _[b373d44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b373d44d05e6086bd84b9ab207bb760baaa7db86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221848114723-17162/BuildReport?accessString=40120eec1004df8221b1c120597d5f29a34671eb80847b07cf109d73b4f7a059).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 00:10 UTC, shahzad-khalid commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "servicePrincipal"
This service principal change log relationship entry is needed because it's part of the schema and the relationship between SP and FIC exists for a very special case of service principal - that is managed identities. In order to not create developer confusion, we decided to hold off on documenting the SP APIs publicly until we have more feedback. See below ADO task on that decision:

https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1801882

2022-06-23 00:14 UTC, opbld30 commented
Docs Build status updates of commit _[ab3a980](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab3a980e69a5063158520a9b621c2f33a6c4108c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230012210829-17162/BuildReport?accessString=5035b3634efd0553ecda30513e586ddb8b516202b8628a114f6d29f62d1f65fc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 00:16 UTC, opbld33 commented
Docs Build status updates of commit _[79c2ccb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79c2ccbc92436619c0b4bf7ce095f3f86d3d0653)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230012566502-17162/BuildReport?accessString=a6815cab6c77c98b65fb21c9061f90618be86f7740964931b2dd8880c34743e2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 00:18 UTC, opbld31 commented
Docs Build status updates of commit _[d6d479d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6d479d640f226cd7548dfdf977ee529a54833f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230013220882-17162/BuildReport?accessString=4907a77cdbba99bd083ea6b679abb57d15d2dbd250eae612996af0deb3527874).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 00:33 UTC, opbld30 commented
Docs Build status updates of commit _[deb776b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/deb776b7122b8c26077726170f04d8fd3b6d30cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230030149536-17162/BuildReport?accessString=c69693fccd4e8fa94f436887657a806555b65ace66a5070d8ba08609e0244a34).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 00:35 UTC, opbld32 commented
Docs Build status updates of commit _[3882bae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3882baefb2a9889becff8746caedcdeb00cf8547)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230033184117-17162/BuildReport?accessString=f393c451054ba175954076a38494b702f9bdf69827d4170e52c092bd1292c4e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 00:38 UTC, opbld31 commented
Docs Build status updates of commit _[6f1be31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f1be312c9a343af78ea8dff30d0aa81c2b5c91c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230036478793-17162/BuildReport?accessString=b27b06afa605daaa20a9be410c5987946d87a3a40a4dd4079391486dd841e5d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 09:16 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "servicePrincipal"
Hi @shahzad-khalid, If we're keeping this changelog entry, then please document the associated relationship to the serviceprincipal.md file.

2022-06-24 20:40 UTC, opbld32 commented
Docs Build status updates of commit _[92e90b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92e90b156b29ba3e3a630c7fc1c4293c4c927971)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242037400788-17162/BuildReport?accessString=2ce28d5da5117e782074e76ea28c5f7ee8524182d8c1c9c6df0983c2907cace9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 20:44 UTC, opbld31 commented
Docs Build status updates of commit _[30d5cf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30d5cf527e06d30fe63d117bb1cf10f7b42c033a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242041371407-17162/BuildReport?accessString=5ca84fd2062b9fc6060e1cef09bd79b07b91d4d51bc2660ba8c5b9dade63df23).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:28 UTC, opbld34 commented
Docs Build status updates of commit _[478837d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/478837d8630f319c1cefc36d39c37bff2fc0ca89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242125520133-17162/BuildReport?accessString=012d2749690004c149d7c404ab4e80879f1a2fb79176ab6f49aa7ca45bb626aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:30 UTC, opbld33 commented
Docs Build status updates of commit _[5c6d65f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c6d65fa5c4b78ef0823094827ea43a1420ed8fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242127343266-17162/BuildReport?accessString=cca0ac7af57c296186c1e64ca4e75f0fa9fc0e71d30172587780066b897466e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:32 UTC, opbld32 commented
Docs Build status updates of commit _[6bd2989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bd29899ae59e3a26be9f941571e1a09d33dfc31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242128191560-17162/BuildReport?accessString=73a972be28abe0c7c5850b98df6fa993541703c67c08c4e6cdb0edf864d27b93).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:35 UTC, opbld34 commented
Docs Build status updates of commit _[b8509c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8509c6e1469f691023c7737d9bed1376434eef0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242129419712-17162/BuildReport?accessString=b7abf8949f40255f3ed32b4da965768c65a3a78a5a392b2be0a347ed8b90397c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:38 UTC, opbld32 commented
Docs Build status updates of commit _[bc57161](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc571616077e1063f2913c919f46b376d8d509cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242133370658-17162/BuildReport?accessString=878949a1ce9ba1d64b98f7b04ab629de6624c221f23f98f7afb30f4ef28510c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-06-24 21:40 UTC, opbld32 commented
Docs Build status updates of commit _[7fb4da3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fb4da3d30e3bd4ee1b251295aebd4d5a46c30a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242132280654-17162/BuildReport?accessString=bf0082b3092acd91a7435c05197818c7b370a1e3ca954c297be75238d0253606).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-06-24 21:43 UTC, opbld31 commented
Docs Build status updates of commit _[972a7d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/972a7d178599c92356dd5e6a3dd97ab6200ef860)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242131363852-17162/BuildReport?accessString=6ff3b909bfc0a5ece16bdf3b8880d4d7d6067cdb796a2f059e05b5d1037b325b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-06-24 21:46 UTC, shahzad-khalid commented
@FaithOmbongi I've made all the changes you had requested. Please review.

2022-06-24 21:46 UTC, opbld33 commented
Docs Build status updates of commit _[a3908e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3908e8761d57917216e5476aa35de08ab844d9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242130274712-17162/BuildReport?accessString=d2091966c9e441ead5a11d04941281d83cf84df3e48e6018968448a050acb1ec).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:48 UTC, opbld34 commented
Docs Build status updates of commit _[8a1cee7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a1cee7a57ebfb4440198aa7ed396251fa43949e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242126313025-17162/BuildReport?accessString=64fa58876f7bd9deaeac9fb91f0cb80d26f85da201e77af93319a332405a37a9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 21:51 UTC, opbld31 commented
Docs Build status updates of commit _[a802e71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a802e717641da3e2964c6497ea2aacad281db745)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242134225761-17162/BuildReport?accessString=d30151b9efe0dfa8d132696f39e19c07105633c016dcd949e8d9973e59c1cd5c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-06-27 08:19 UTC, FaithOmbongi approved these changes
Hi @shahzad-khalid,
 Just one comment about the URLs, like this one:
```
/applications/{id}/federatedIdentityCredentials/{federatedIdentityCredentialId}
```

It's important to differentiate the two IDs hence we try to combine the resource name and id to achieve the differentiation. When we only say `{id}`, we hear from customers that they aren't sure which ID to use (even if the preceding object may be servicePrincal for example). So we use "applicationId", "applicationObjectId", "servicePrincipalId" etc to help them know the ID to use and by extension, where to get it.

This differentiation is especially required for application APIs where we have **id**, **appId** referring to different IDs - and the Azure portal calls the id -> **objectID**

I'd recommend for the FIC docs, the first ID becomes "applicationObjectId". E.g.

```
/applications/{applicationObjectId}/federatedIdentityCredentials/{federatedIdentityCredentialId}
```

2022-06-27 08:19 UTC, FaithOmbongi commented on api-reference/beta/api/federatedidentitycredential-update.md
> +PATCH /applications/{id}/federatedIdentityCredentials/{federatedIdentityCredentialId}
Hi @shahzad-khalid - The differentiation between the 2 IDs is important for customers to know which ID to use and where to get the ID for a particular path segment. Mostly applies where there is more than one ID in the URL. This differentiation is also useful in autogenerated SDKs like the MSGraph PowerShell SDK.

For example for the case of applications, we have **id**, **appId** which confuse customers.

2022-06-27 18:45 UTC, shahzad-khalid commented on api-reference/beta/api/federatedidentitycredential-update.md
> +PATCH /applications/{id}/federatedIdentityCredentials/{federatedIdentityCredentialId}
Hi Faith, As discussed over Teams, we decided not to introduce applicationObjectId to replace Id in the URLs. Instead you will add these changes to the api  docs to clarify:


1. add a boilerplate text before the code block in the HTTP request section of API files like [Get application - Microsoft Graph beta | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&tabs=http)


"Replace {id} with the id for the application object, also referred to as the Object ID in the Azure portal."


2. update the description of the id property in [application resource type - Microsoft Graph beta | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta) to "The unique identifier for the application object. This property is referred to as Object ID in the Azure portal."

2022-08-02 17:21 UTC, opbld32 commented
Docs Build status updates of commit _[f599234](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f599234c5dc02e8ea0dd4fcef8fad27d7c17ef1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021718328047-17162/BuildReport?accessString=b0273e87c6d98849c7943f15b184256239f99ee4551e1589b1aaeea29cbabea0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-08-03 02:52 UTC, opbld30 commented
Docs Build status updates of commit _[c8d484d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8d484d436ae0e76e635244e1e2d9f73c29ff73d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/beta/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/beta/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-beta&branch=pr-en-us-17162) (graph-rest-beta) |
[api-reference/v1.0/api/application-list-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/application-post-federatedidentitycredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-get?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/api/federatedidentitycredential-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/api/federatedidentitycredential-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-update?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredential.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredential?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/federatedidentitycredentials-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/federatedidentitycredentials-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/federatedidentitycredentials-overview?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-1.0&branch=pr-en-us-17162) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/skhalid-ficapi-updates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030249432176-17162/BuildReport?accessString=b8a62faa7c8472b3e45955b8fc6eda9157ba8998c3246ec128dc7831f25e3c7d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question i [...]

2022-08-03 02:54 UTC, merged