Fixed shared channel doc nconsistencies
microsoftgraph/microsoft-graph-docs pull request #17170
Opened 2022-06-07 07:02 UTC by devjha-ms

Fix shared channel doc inconsistencies as pointed out by Angela Chu-Hatoun in https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/2374934/

2022-06-07 07:06 UTC, opbld30 commented
Docs Build status updates of commit _[643f565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/643f565197214b77227d49a90b61a31c23f4be44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) | [Details](#user-content-f40773f858d6a9471004d2b675ca67b8-a3fe52a4)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-a3fe52a4)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a3fe52a4)
[api-reference/beta/api/team-delete-incomingchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/devjha-fix-shared-channel-doc-inconsistencies/api-reference/beta/api/team-delete-incomingchannel.md) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-17170) |

<a id="f40773f858d6a9471004d2b675ca67b8-a3fe52a4"></a>
### [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/channel.md)
 - **Line 50, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/team-delete-incomingchannels.md'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-a3fe52a4"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/team.md)
 - **Line 46, Column 2**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/team-delete-incomingchannels.md'.`````

<a id="0817dce4456c16725d5333633847d38f-a3fe52a4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 15208, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/team-delete-incomingchannels.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206070702348481-17170/BuildReport?accessString=df4b7c3e8719b9dee374e141e7a1aeab1d08d0a6384717e3721c8ba3034da2e8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 07:13 UTC, opbld33 commented
Docs Build status updates of commit _[2954780](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2954780f942d9ef03012c8f3038944cc9ebb64ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-delete-incomingchannels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/team-delete-incomingchannels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-incomingchannels?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-delete-incomingchannels?view=graph-rest-beta&branch=pr-en-us-17170) (graph-rest-beta) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-17170) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206070709528379-17170/BuildReport?accessString=1e99eef576dc1c7aa21b0b3858c0e6718c6dc0d0c57e6dd6b84f4096372dc891).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 11:34 UTC, akhilkohlimicrosoft approved these changes

2022-06-14 07:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/team.md
>  |channels|[channel](channel.md) collection|The collection of channels and messages associated with the team.|
@devjha-ms , can you add the missing group navigation property to the table as well?

2022-06-14 07:55 UTC, angelgolfer-ms requested changes
Hi @devjha-ms , thanks for following up with this PR. Please see my one comment.

2022-06-14 08:34 UTC, devjha-ms commented on api-reference/beta/resources/team.md
>  |channels|[channel](channel.md) collection|The collection of channels and messages associated with the team.|
Not added "group" in relationship as we don't expose /teams/{teamId}/group graph API.

2022-06-14 17:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/team.md
>  |channels|[channel](channel.md) collection|The collection of channels and messages associated with the team.|
@devjha-ms , further question to you offline on Teams, please take a look.

2022-06-16 03:28 UTC, angelgolfer-ms commented
@devjha-ms , per our Teams chat, I can approve this PR, but we should follow up on the group nav property of the team entity separately.

2022-06-16 03:29 UTC, angelgolfer-ms approved these changes

2022-06-18 01:13 UTC, merged