Add communications identity types
microsoftgraph/microsoft-graph-docs pull request #17181
Opened 2022-06-08 04:05 UTC by Hunterjet

Add communications identity types. Update some files referencing the endpointType enum.

2022-06-08 04:07 UTC, opbld30 commented
Docs Build status updates of commit _[57cabcf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57cabcf1e7b192d423430103b149cc47730e57c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azureCommunicationServicesUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/azureCommunicationServicesUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsApplicationIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationInstanceIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsApplicationInstanceIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsEncryptedIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsEncryptedIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206080405252155-17181/BuildReport?accessString=35bc300ba564d50553591105f6b4e29b722b1a637b7ff477b4ce8acc2db5d2cd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 19:58 UTC, mkhribech approved these changes

2022-06-15 00:35 UTC, opbld32 commented
Docs Build status updates of commit _[475cf79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/475cf790ab1df036bd6c5a3d3bc0ce9d14080171)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azureCommunicationServicesUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/azureCommunicationServicesUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsApplicationIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationInstanceIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsApplicationInstanceIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsEncryptedIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsEncryptedIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206150032466542-17181/BuildReport?accessString=7a1d355dd4ec72718b59627c762eae93aabc02c8d2892a673ba4f5c79305b6c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 20:45 UTC, opbld31 commented
Docs Build status updates of commit _[369d064](https://github.com/microsoftgraph/microsoft-graph-docs/commits/369d064f810562c8e4bb446a8cdf02565f08ca2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azureCommunicationServicesUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azureCommunicationServicesUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsApplicationIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationInstanceIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsApplicationInstanceIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsEncryptedIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsEncryptedIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292042442317-17181/BuildReport?accessString=82e7af3858a314f9b32e7294e68557b81ae61c06e268c21e464b3e7c3cfab843).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 20:59 UTC, opbld31 commented
Docs Build status updates of commit _[b51aabe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b51aabef8ce330baed56ca99b1eee972790f366e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsApplicationIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationInstanceIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsApplicationInstanceIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsEncryptedIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsEncryptedIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292055385939-17181/BuildReport?accessString=e8f67e972b03129662a5900eeeca11200372c955ef33fa9e3a0f5bb6b9301db7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:01 UTC, opbld33 commented
Docs Build status updates of commit _[99faa63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99faa63ef9f26b81baceabd3c4dc83fdb7132c1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationInstanceIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsApplicationInstanceIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsEncryptedIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsEncryptedIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292057570897-17181/BuildReport?accessString=cf7e3bce916e60c98bb1c715812525bf5bb889a711ef364af2e22cc5482d3314).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:04 UTC, opbld30 commented
Docs Build status updates of commit _[0f306e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f306e0ed18c64ab3fca4e5dc4b6a970e77886b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292059260531-17181/BuildReport?accessString=55a76d635b39c874ee6c609ed428ba33b3c381eda12957b46584d28e703b24e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:04 UTC, isvargasmsft commented on api-reference/beta/resources/communicationsidentityset.md
> +| endpointType | [endpointType](endpointType.md) | Type of endpoint the participant is using. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone`. |
We always add `unknownFutureValue` for evolvable enums. Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211749/Evolvable-enumerations

```suggestion
| endpointType | [endpointType](endpointType.md) | Type of endpoint the participant is using. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone` and `unknownFutureValue`. |
```

2022-06-29 21:06 UTC, isvargasmsft commented on api-reference/beta/resources/endpointtype.md
> +# endpointType resource type
I don't see any new (or pre-existing) resource types with this name in the CSDL. Only the preexisting enum. Could you please clarify this topic?

2022-06-29 21:06 UTC, opbld30 commented
Docs Build status updates of commit _[bbb0a35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbb0a352e8d289ccf9a1b6230ad957f33c0fe6e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsphoneidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsphoneidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292100063150-17181/BuildReport?accessString=dbef43a531cba2af5df2cea84aaa95851666d701f35a95a6e86c06f92696d720).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:08 UTC, isvargasmsft commented on api-reference/beta/resources/invitationparticipantinfo.md
> +| endpointType                       | endpointType                        | The type of endpoint. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone`. |
```suggestion
| endpointType                       | endpointType                        | The type of endpoint. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone` and `unknownFutureValue`. |
```

2022-06-29 21:09 UTC, isvargasmsft commented on api-reference/beta/resources/invitationparticipantinfo.md
> +  "endpointType": "default | voicemail | skypeForBusiness | skypeForBusinessVoipPhone",
In JSON representations, please use String for enum types. 
```suggestion
  "endpointType": "String",
```

2022-06-29 21:09 UTC, isvargasmsft commented on api-reference/beta/resources/participantinfo.md
> +  "endpointType": "default | voicemail | skypeForBusiness | skypeForBusinessVoipPhone",
```suggestion
  "endpointType": "String",
```

2022-06-29 21:10 UTC, opbld30 commented
Docs Build status updates of commit _[06a3810](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06a3810009186e55e7c3210c7ee10ef92acc2dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsphoneidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsphoneidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292100438619-17181/BuildReport?accessString=161f71d5cd8176ab23b7eccead04e607d8ad1799226f271da3908ef56f4ce59b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:11 UTC, isvargasmsft commented on api-reference/beta/resources/communicationsidentityset.md
> +  "endpointType": "default | voicemail | skypeForBusiness | skypeForBusinessVoipPhone"
```suggestion
  "endpointType": "String"
```

2022-06-29 21:12 UTC, opbld34 commented
Docs Build status updates of commit _[9f939e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f939e368f4ed4091bbb49f6807ac49a3c1cf36e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsphoneidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsphoneidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292100277479-17181/BuildReport?accessString=5e97e59e29e8a1a323924d1c19e02359593470d28c0647668ea0141822f457aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:15 UTC, opbld32 commented
Docs Build status updates of commit _[e626db2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e626db2ddc7b8397861c2371d9f60fd6af979f1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292059434690-17181/BuildReport?accessString=81c363d18398fc5d9b8ca6c3c18453b4a6f251ee46d02147639b5936545f4efd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:17 UTC, opbld33 commented
Docs Build status updates of commit _[29fb41a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29fb41a9ca9d967026381739b812f3ac4207bda3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292058586294-17181/BuildReport?accessString=1992dc271c19019e1c00cfc2d5a79a691ac3b62582586db5a89c1a285981cce8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:20 UTC, opbld31 commented
Docs Build status updates of commit _[9c134f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c134f477f4bc53c6b89af545ff072e466cbc970)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsApplicationInstanceIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsApplicationInstanceIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsGuestIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsGuestIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsIdentitySet.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsIdentitySet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsPhoneIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsPhoneIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsUserIdentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsUserIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292058250575-17181/BuildReport?accessString=54777935b4c14d52ceb71891db147134028987c5bef33816984bead4ed2dec37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:51 UTC, opbld34 commented
Docs Build status updates of commit _[2d1afd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d1afd0e8fc486862c827aea4ca845ec64b09498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsphoneidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsphoneidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/endpointtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/endpointtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/endpointtype?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206292148546136-17181/BuildReport?accessString=d65359fb366b6fa1f002c0ff3e37491d2598eeff4067977272d5fc504a72c246).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 21:53 UTC, isvargasmsft commented on api-reference/beta/resources/communicationsapplicationinstanceidentity.md
> +Represents the identity of an instance of an application. An application instance is a resource account created by **New-CsOnlineApplicationInstance**. For example, you might have multiple Call Queue
Do we have a reference link we can provide to give more context on what is **New-CsOnlineApplicationInstance**?

2022-06-29 21:59 UTC, isvargasmsft commented on api-reference/beta/resources/communicationsapplicationidentity.md
> +Represents the identity of an application.
Would you please add a bit more of context to this description?

2022-06-29 21:59 UTC, isvargasmsft commented on api-reference/beta/resources/communicationsuseridentity.md
> +Represents the identity of a user.
Would you please provide a bit more of context to this description as well?

2022-06-29 22:01 UTC, isvargasmsft requested changes
Hello @Hunterjet, 

Thank you very much for your work in this PR. Very complete in general. 

1. Please take a look at a few suggestions I left for consistency. 
2. Please clarify why we are adding a resource topic for endpointType. 
3. Please provide a bit more of context to 2 descriptions. 

Kind regards, 

Isaac

2022-07-06 21:48 UTC, Hunterjet commented on api-reference/beta/resources/communicationsidentityset.md
> +| endpointType | [endpointType](endpointType.md) | Type of endpoint the participant is using. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone`. |
Added.

2022-07-06 21:49 UTC, Hunterjet commented on api-reference/beta/resources/endpointtype.md
> +# endpointType resource type
My bad, this was from an earlier iteration. Removed the file.

2022-07-06 21:49 UTC, Hunterjet commented on api-reference/beta/resources/invitationparticipantinfo.md
> +| endpointType                       | endpointType                        | The type of endpoint. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone`. |
Added.

2022-07-06 21:49 UTC, Hunterjet commented on api-reference/beta/resources/participantinfo.md
> +| endpointType     | endpointType                          | The type of endpoint the participant is using. Possible values are: `default`, `voicemail`, `skypeForBusiness`, `skypeForBusinessVoipPhone
Added.

2022-07-06 21:49 UTC, Hunterjet commented on api-reference/beta/resources/communicationsidentityset.md
> +  "endpointType": "default | voicemail | skypeForBusiness | skypeForBusinessVoipPhone"
Fixed.

2022-07-06 21:50 UTC, Hunterjet commented on api-reference/beta/resources/communicationsapplicationinstanceidentity.md
> +Represents the identity of an instance of an application. An application instance is a resource account created by **New-CsOnlineApplicationInstance**. For example, you might have multiple Call Queue
Added link to the docs page for this cmdlet.

2022-07-06 21:50 UTC, Hunterjet commented on api-reference/beta/resources/communicationsapplicationidentity.md
> +Represents the identity of an application.
Added.

2022-07-06 21:50 UTC, Hunterjet commented on api-reference/beta/resources/communicationsuseridentity.md
> +Represents the identity of a user.
Added.

2022-07-12 20:55 UTC, isvargasmsft approved these changes

2022-07-12 20:56 UTC, isvargasmsft commented
@FaithOmbongi FYI I just reviewed this one :)

2022-07-20 01:58 UTC, opbld31 commented
Docs Build status updates of commit _[f545e95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f545e9535d1c5325162f1a711a184f697a6460c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) | [Details](#user-content-32b9c6a510520c1605140b36744b0b64-a51982db)
[api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsapplicationinstanceidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) | [Details](#user-content-b35dede82591ac658dc839014378a648-a51982db)
[api-reference/beta/resources/communicationsuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsuseridentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) | [Details](#user-content-cbd371b09ad7c77ab8f9f2bc028222da-a51982db)
[api-reference/beta/resources/azurecommunicationservicesuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/azurecommunicationservicesuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azurecommunicationservicesuseridentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsencryptedidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsencryptedidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsencryptedidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsguestidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsguestidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsguestidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsidentityset?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/communicationsphoneidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsphoneidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communicationsphoneidentity?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/invitationparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/invitationparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[api-reference/beta/resources/participantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/participantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/participantinfo?view=graph-rest-beta&branch=pr-en-us-17181) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="32b9c6a510520c1605140b36744b0b64-a51982db"></a>
### [api-reference/beta/resources/communicationsapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationidentity.md)
 - **Line 16, Column 141**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 141**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/active-directory/' will be broken in isolated environments. Replace with a relative link.`````

<a id="b35dede82591ac658dc839014378a648-a51982db"></a>
### [api-reference/beta/resources/communicationsapplicationinstanceidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsapplicationinstanceidentity.md)
 - **Line 16, Column 116**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineapplicationinstance' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 116**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineapplicationinstance' will be broken in isolated environments. Replace with a relative link.`````

<a id="cbd371b09ad7c77ab8f9f2bc028222da-a51982db"></a>
### [api-reference/beta/resources/communicationsuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/communications-identity/api-reference/beta/resources/communicationsuseridentity.md)
 - **Line 16, Column 46**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 46**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/active-directory/' will be broken in isolated environments. Replace with a relative link.`````

For more deta [...]

2022-07-20 02:12 UTC, merged