Update Microsoft Graph extensibility docs
microsoftgraph/microsoft-graph-docs pull request #17209
Opened 2022-06-10 16:06 UTC by FaithOmbongi

2022-06-10 16:14 UTC, opbld31 commented
Docs Build status updates of commit _[66081e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66081e2af1ee74ed0c5934567d3ff95f9c1448c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-0627894e)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-0627894e)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-0627894e)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-0627894e)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-0627894e)
[concepts/migrate-azure-ad-graph-feature-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-feature-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-feature-differences?branch=pr-en-us-17209) | [Details](#user-content-3334310a58f9a0269d2de2cb980a017e-0627894e)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-0627894e)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-0627894e)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-0627894e)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-0627894e)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionschemaproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resourc [...]

2022-06-10 16:47 UTC, opbld34 commented
Docs Build status updates of commit _[9763564](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9763564cfd3557d293134d3bca26e83ba84c7886)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-0677b0bc)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-0677b0bc)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-0677b0bc)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-0677b0bc)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-0677b0bc)
[concepts/migrate-azure-ad-graph-feature-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-feature-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-feature-differences?branch=pr-en-us-17209) | [Details](#user-content-3334310a58f9a0269d2de2cb980a017e-0677b0bc)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-0677b0bc)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-0677b0bc)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-0677b0bc)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-0677b0bc)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-0677b0bc)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionschemaproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaext [...]

2022-06-13 09:47 UTC, opbld33 commented
Docs Build status updates of commit _[0ceea51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ceea51f667f37709f8542e767dfb0bf70fc41e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-f9972578)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-f9972578)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-f9972578)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-f9972578)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-f9972578)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-f9972578)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-f9972578)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-f9972578)
[concepts/migrate-azure-ad-graph-feature-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-feature-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-feature-differences?branch=pr-en-us-17209) | [Details](#user-content-3334310a58f9a0269d2de2cb980a017e-f9972578)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-f9972578)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-f9972578)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionschemaproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaext [...]

2022-06-14 19:01 UTC, opbld32 commented
Docs Build status updates of commit _[e95821f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e95821fb41bc3ee42452e44bc35016b3c3288e6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-f40d32ca)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-f40d32ca)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-f40d32ca)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-f40d32ca)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-f40d32ca)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-f40d32ca)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-f40d32ca)
[concepts/migrate-azure-ad-graph-feature-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-feature-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-feature-differences?branch=pr-en-us-17209) | [Details](#user-content-3334310a58f9a0269d2de2cb980a017e-f40d32ca)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-f40d32ca)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-f40d32ca)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-f40d32ca)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-f40d32ca)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionschemaproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-06-14 19:46 UTC, opbld32 commented
Docs Build status updates of commit _[724d479](https://github.com/microsoftgraph/microsoft-graph-docs/commits/724d479a33fb1a2f8c20056d73a6732520de9f06)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-d9074a32)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-d9074a32)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-d9074a32)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-d9074a32)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-d9074a32)
[concepts/migrate-azure-ad-graph-feature-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-feature-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-feature-differences?branch=pr-en-us-17209) | [Details](#user-content-3334310a58f9a0269d2de2cb980a017e-d9074a32)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-d9074a32)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-d9074a32)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-d9074a32)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-d9074a32)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-d9074a32)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-d9074a32)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionschemaproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-06-17 17:26 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +##### Example: Extension attributes on a device object
Not sure this example adds much value and I would remove it.

2022-06-17 17:33 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +```http
Can we show the request - GET ../users?$select=id,displayName,{ext1},{ext2)

It looks ugly, and we should show that! That's one reason we changed things with Microsoft Graph

2022-06-20 09:31 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +##### Example: Extension attributes on a device object
Was hoping to get something more complete to show what customers might store as ext attr values for devices. I think deleting the example might be better because these samples only show how the objects are represented in the payload - the example of the user object will suffice for now.

2022-06-20 10:33 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +```http
Good suggestion. Done.

2022-06-20 10:34 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +```http
Good suggestion. Done.

I've also applied this suggestion to the other examples for completeness.

2022-06-20 10:37 UTC, opbld31 commented
Docs Build status updates of commit _[aa145a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa145a80c4154b8556bd9faa484cb229a7cefbbd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-eeff6259)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-eeff6259)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-eeff6259)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-eeff6259)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-eeff6259)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-eeff6259)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-eeff6259)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-eeff6259)
[concepts/migrate-azure-ad-graph-feature-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-feature-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-feature-differences?branch=pr-en-us-17209) | [Details](#user-content-3334310a58f9a0269d2de2cb980a017e-eeff6259)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-eeff6259)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-eeff6259)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-eeff6259)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/extensionschemaproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-06-20 10:38 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +        "@odata.type": "#microsoft.graph.ComplexExtensionValue",
Does this show up in the response?  If not, I would remove it.  I don't think it's required here.

2022-06-20 10:42 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +| Capability | Directory extensions | Schema extensions | Open extensions | Extension attributes 1-15 |
Nit:  The order of the columns here doesn't match the section ordering above.

2022-06-20 10:55 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +Unlike open extensions, you manage the [schema extension definitions](/graph/api/resources/schemaextension) and their data on the extended resource instance as separate sets of API operations. Becaus
This was an excessive addition by Angela IMHO.
I think this paragraph is fine (although the final sentence needs to be rounded off differently).  The additional bullets can be removed - it tells me nothing new - than simply saying CRUD is available as it does in the paragraph.  This is like **any** other resource - CRUD is done through POST, GET, PATCH and DELETE.

So I'd change the last sentence in the paragraph to:
Because schema extensions are accessible as complex types in instances of the targeted resources, you can perform CRUD operations on the targeted resource including the custom extension property to manage the extension data.

And then remove the bullets.

The only useful info is PATCHing the complex type to null to delete the data in the custom property.

2022-06-20 11:04 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +| Filterable | Yes | Yes | No | Yes |
Open type extensions have some limited filtering for Outlook resources (I think there's the ability to filter on whether resources have a named extension.  But you still cannot filter on the values of the open extension properties.

2022-06-20 11:44 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +| Sync data from on-premises using [AD connect][] | [Yes][ADConnect-YES] | No | No | Yes for Users |
Sync data from on-premises using [AD connect][]
->
Sync data from on-premises to extensions using [AD connect][]

2022-06-20 11:47 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +| Limits | <li>100 extension values across *all* types and *all* applications per resource instance | <li>Maximum of five definitions per owner app <br/><li> 100 extension values per resource instanc
Can we make the limit the same for Directory and Schema extensions?
"100 extension values per resource instance"?

Under Schema extensions it should say "100 extension values per resource instance, for Directory resources", as it only applies to directory resources.

2022-06-20 11:49 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +| Supported resource types | [user][] <br/> [group][] <!--<br/> [administrativeUnit][]--> <br/> [application][] <br/> [device][] <br/> [organization][] <br/> [servicePrincipal][] | [user][] <br/> [gr
The footnote for "event" should be the event in the Open Extensions column, I believe

2022-06-20 11:51 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +> You can manage all extensions when you're signed in with a work or school account. Additionally, you can manage extensions for the following resources when signed-in with a personal Microsoft accou
Please update:
Additionally, you can manage extensions for the following resources when signed-in with a personal Microsoft account:
->
Additionally, you can manage **open** extensions for the following resources when signed-in with a personal Microsoft account:

2022-06-20 11:54 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +The same [permissions](./permissions-reference.md) that are required to read from or write to a specific resource are also required to read from or write to any extensions data on that resource. For
The example is not a good one (for least privilege).  I would say

For example, for an app to update any user's profile with custom app data, the app must have been granted the *User.ReadWrite.All* permission.

I'd prefer change the permission to *User.ReadWrite* but I have a vague suspicion that doesn't work... :(

2022-06-20 12:22 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +| Supported resource types | [user][] <br/> [group][] <!--<br/> [administrativeUnit][]--> <br/> [application][] <br/> [device][] <br/> [organization][] <br/> [servicePrincipal][] | [user][] <br/> [gr
Are we sure that application and servicePrincipal are supported for Directory extensions?

2022-06-20 12:25 UTC, dkershaw10 commented on api-reference/v1.0/api/application-list-extensionproperty.md
>  ## Optional query parameters
Doesn't look like you made the same edit in /beta docs...

2022-06-20 12:33 UTC, dkershaw10 commented on api-reference/v1.0/api/schemaextension-post-schemaextensions.md
> +Schema extensions let you add strongly-typed custom data to a resource. The app that creates a schema extension is the owner app. Depending on the [state of the extension](/graph/api/resources/schema
Nit - again the text between beta and v1 is not consistent.

2022-06-20 12:38 UTC, dkershaw10 commented on api-reference/v1.0/api/user-get.md
> +### Retrieving extensions and custom data
Are we only adding this for the user resource type?
What about the other supported types?  Will we update the get and list API topics?

2022-06-20 13:50 UTC, dkershaw10 commented on api-reference/v1.0/resources/device.md
> +This resource is an open type that allows other properties to be passed in and lets you add your own data to custom properties using [extensions](/graph/extensibility-overview).
This text is different from the other resources on supported capabilities...

2022-06-20 13:53 UTC, dkershaw10 commented on api-reference/v1.0/resources/extensionproperty.md
> ++ [application](application.md) resources
In the overview, servicePrincipal is in the list of supported types, but not here.  I don't think servicePrincipal is supported, but happy to be proved wrong

2022-06-20 13:57 UTC, dkershaw10 commented on api-reference/v1.0/resources/extensionproperty.md
> +> Extensions created through Azure AD Graph (deprecated) and custom data sync from on-premises Active Directory using Azure AD Connect Sync are synced as directory extensions in Microsoft Graph.
```suggestion
> Extensions created through Azure AD Graph (deprecated) and custom data synchronized from on-premises Active Directory using Azure AD Connect Sync are represented as directory extensions in Microsoft Graph.
```

2022-06-20 14:50 UTC, dkershaw10 commented on api-reference/v1.0/toc.yml
> +        - name: Directory extensions
I know this is under application, but I wonder if the TOC should also put directory extensions under the Extensions top level area (in beta and v1) alongside open and schema extensions?

2022-06-20 14:59 UTC, dkershaw10 commented on api-reference/v1.0/resources/extensionschemaproperty.md
> +> **Note:** Multi-value properties are not supported.
This seems to suggest that multi-valued properties ARE supported for directory extensions.  However this note is not present in the directory extensions topic, nor is there any property in extensionProperty resource that indicates support for multi-valued extension properties

2022-06-21 15:04 UTC, dkershaw10 commented on api-reference/beta/resources/schemaextension.md
> +| InDevelopment | <ul><li>Initial state after creation. The owner app is still developing the schema extension. </li><li>In this state, any app in the same directory where the owner app is registered
There's another thing to add in here.  I'll try to write an additional bullet, but I'll also add an example for you, so that you can understand the scenario and maybe do a better job than me on the new bullet :)

In this state, only the owner app (as a multi-tenant app), when consented into another tenant (i.e. a different tenant from the one the app is registered in), can extend resource instances with this schema definition (as long as the app has permissions to that resource).

I create a multi-tenant application (in tenant A). This app calls /schemaExtensions to register an extension (ext1) for a particular type (say driveItem - I'm assuming for now it's a supported type for extensions). The extension stays in the "inDevelopment" state. This multi-tenant app is now acquired by tenant B. In the context of tenant B, the multi-tenant app can extend resource instances with ext1 (as long as the app has permissions to that resource)

2022-06-21 19:26 UTC, dkershaw10 commented on api-reference/v1.0/resources/schemaextension.md
> +|[List](../api/schemaextension-list.md) | [schemaExtension](schemaextension.md |List the available schemaExtension definitions and their properties.|
Return types for list, get, update are missing a closing parenthesis

2022-06-21 19:36 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +title: "Add custom properties to resources using extensions"
Not in this topic, but can you also fix migrate-azure-ad-graph-feature-differences as part of this PR please?

Under "Directory schema extensions"

1. Rename "Directory schema extensions" -> "Directory extensions"
2. First bullet has a busted link a [ instead of (
3. 3rd bullet: Read extension values using GET and $select.  We should indicate the $select is required on /users to see any directory extension values.
4. The last link in the section is a deep link that doesn't work.  The deep link should also go to Choose an extension type for your application IMHO.

2022-06-21 19:36 UTC, dkershaw10 requested changes
Done with my first pass.  Let me know if you have any questions...

2022-06-22 08:47 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +        "@odata.type": "#microsoft.graph.ComplexExtensionValue",
Confirmed - this @odata.type is returned in the response object.

2022-06-22 09:34 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +| Supported resource types | [user][] <br/> [group][] <!--<br/> [administrativeUnit][]--> <br/> [application][] <br/> [device][] <br/> [organization][] <br/> [servicePrincipal][] | [user][] <br/> [gr
Good catch. Fixed.

2022-06-22 09:39 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +Unlike open extensions, you manage the [schema extension definitions](/graph/api/resources/schemaextension) and their data on the extended resource instance as separate sets of API operations. Becaus
Agreed. Applied your suggestion.

2022-06-22 09:59 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +| Limits | <li>100 extension values across *all* types and *all* applications per resource instance | <li>Maximum of five definitions per owner app <br/><li> 100 extension values per resource instanc
Done.

2022-06-22 09:59 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +> You can manage all extensions when you're signed in with a work or school account. Additionally, you can manage extensions for the following resources when signed-in with a personal Microsoft accou
Done.

2022-06-23 10:07 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +| Filterable | Yes | Yes | No | Yes |
Sounds more like a $select than a $filter....I'll keep support for $filter as "No" for now.

2022-06-23 10:12 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +| Supported resource types | [user][] <br/> [group][] <!--<br/> [administrativeUnit][]--> <br/> [application][] <br/> [device][] <br/> [organization][] <br/> [servicePrincipal][] | [user][] <br/> [gr
Application - yes. SP - no. Pushing a fix.

2022-06-23 10:31 UTC, FaithOmbongi commented on concepts/extensibility-overview.md
> +The same [permissions](./permissions-reference.md) that are required to read from or write to a specific resource are also required to read from or write to any extensions data on that resource. For
Confirmed _User.ReadWrite_ isn't enough so applying you're 2nd sentence.

2022-06-23 11:44 UTC, FaithOmbongi commented on api-reference/v1.0/resources/extensionproperty.md
> ++ [application](application.md) resources
SP isn't supported - corrected the Overview doc

2022-06-23 11:58 UTC, FaithOmbongi commented on api-reference/v1.0/resources/extensionschemaproperty.md
> +> **Note:** Multi-value properties are not supported.
Makes sense. I guess the statement would have been suitable if at least one of the extension types supported definitions that can be collections.

2022-06-23 12:41 UTC, FaithOmbongi commented on api-reference/beta/resources/schemaextension.md
> +| InDevelopment | <ul><li>Initial state after creation. The owner app is still developing the schema extension. </li><li>In this state, any app in the same directory where the owner app is registered
Took me a while for it to click but I think I've got it: "For an owner app that's multi-tenant, only the instance of the owner app that's in a different directory from the home directory can extend resource instances with this schema definition (if the app has permissions to that resource)."

2022-06-23 13:19 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +        - name: Directory extensions
Had the same thought - I think this relocation will also help with discoverability through navigation which is currently overshadowed by the B2C doc reference that generates 50% of the current views.

2022-06-23 13:30 UTC, opbld30 commented
Docs Build status updates of commit _[c346c55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c346c55d44ceff709bea5a92a33ee2c9ca0029e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-3dda1fac)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-3dda1fac)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-3dda1fac)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-3dda1fac)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-3dda1fac)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-3dda1fac)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-3dda1fac)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-3dda1fac)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-3dda1fac)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-3dda1fac)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-3dda1fac)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-3dda1fac)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-3dda1fac)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-3dda1fac)
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/s [...]

2022-06-23 13:55 UTC, opbld33 commented
Docs Build status updates of commit _[2be6b8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2be6b8ad2f84d606bdc9493cee68afc5ff0d2347)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-d238a508)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-d238a508)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-d238a508)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-d238a508)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-d238a508)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-d238a508)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-d238a508)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-d238a508)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-d238a508)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-d238a508)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-d238a508)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-d238a508)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-d238a508)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-d238a508)
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/s [...]

2022-06-23 17:01 UTC, opbld31 commented
Docs Build status updates of commit _[6ff4218](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ff4218d0a8cb2dac13c7c2132e2f073c6fedcb1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-31f70741)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-31f70741)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-31f70741)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-31f70741)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-31f70741)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-31f70741)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-31f70741)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-31f70741)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-31f70741)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-31f70741)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-31f70741)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-31f70741)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-31f70741)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-31f70741)
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/s [...]

2022-06-24 08:11 UTC, opbld32 commented
Docs Build status updates of commit _[2a51a42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a51a42aebf87cc8d9a4263d6be168ef1676b87d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-829b7200)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-829b7200)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-829b7200)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-829b7200)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-829b7200)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-829b7200)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-829b7200)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-829b7200)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-829b7200)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-829b7200)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-829b7200)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-829b7200)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-829b7200)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-829b7200)
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/s [...]

2022-06-27 21:09 UTC, opbld32 commented
Docs Build status updates of commit _[feb1e82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/feb1e82f8e1050d6b3db9f8ae28b833920621e67)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-6a7e2924)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-6a7e2924)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-6a7e2924)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-6a7e2924)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-6a7e2924)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-6a7e2924)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-6a7e2924)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-6a7e2924)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-6a7e2924)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-6a7e2924)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-6a7e2924)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-6a7e2924)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-6a7e2924)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-6a7e2924)
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/s [...]

2022-06-28 09:38 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +    "owner": "da2d15ee-30c0-4732-8f5d-84158b8cb8aa",
owner isn't a required property, so I don't think we should show it.
It's only required for cases like creation using another app - like Graph Explorer.

2022-06-28 09:39 UTC, dkershaw10 commented on concepts/extensibility-overview.md
> +The request returns a `201 Created` response code and an [schemaExtension](/graph/api/resources/schemaextension) object in the response body
```suggestion
The request returns a `201 Created` response code and a [schemaExtension](/graph/api/resources/schemaextension) object in the response body
```

2022-06-28 10:02 UTC, dkershaw10 commented on api-reference/v1.0/resources/schemaextension.md
> ++ [servicePrincipal](/graph/api/resources/serviceprincipal)
I don't think servicePrincipal is supported for schema extensions.  I guess you are checking :)

2022-06-28 10:06 UTC, dkershaw10 commented on api-reference/v1.0/resources/schemaextension.md
> +| InDevelopment | <ul><li>Initial state after creation. The owner app is still developing the schema extension. </li><li>In this state, any app in the same directory where the owner app is registered
For the multi-tenant bullet, can we say that other apps in the other directory cannot read the extension data created by the multi-tenant app?

2022-06-28 10:09 UTC, dkershaw10 commented on api-reference/v1.0/resources/schemaextension.md
> +| InDevelopment | <ul><li>Initial state after creation. The owner app is still developing the schema extension. </li><li>In this state, any app in the same directory where the owner app is registered
Looks like we are missing an explicit bullet that says that "In this state the owner app can delete the schema extension definition". The second to last bullet kind of mentions it, but it's easy to miss.

2022-06-28 10:31 UTC, dkershaw10 approved these changes
I think this is the last of my comments.
Make those updates and I'm good to go.

2022-06-28 16:24 UTC, FaithOmbongi commented on api-reference/v1.0/resources/schemaextension.md
> ++ [servicePrincipal](/graph/api/resources/serviceprincipal)
Confirmed - not supported. Fixed.

2022-06-28 17:19 UTC, opbld32 commented
Docs Build status updates of commit _[4306e14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4306e1424d11a2d8db770830604726eacb4935f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-8d60da29)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-8d60da29)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-8d60da29)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-8d60da29)
[api-reference/v1.0/resources/extensionschemaproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/extensionschemaproperty.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/extensionschemaproperty?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-d5eee4d7da43b0c424a522ad1c881833-8d60da29)
[api-reference/v1.0/resources/schemaextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/schemaextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-fd39b2add639b4d7db28b084b2aa4484-8d60da29)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-8d60da29)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-8d60da29)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-8d60da29)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-8d60da29)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-8d60da29)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-8d60da29)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-8d60da29)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-8d60da29)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.m [...]

2022-06-28 17:45 UTC, opbld30 commented
Docs Build status updates of commit _[d2fb0bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2fb0bcc200f727d8f80dfd069f2e28c4b1dbd28)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-ac44d121)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-ac44d121)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-ac44d121)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-ac44d121)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-ac44d121)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-4c6b7dd378cee704addbb1fa66e6cda7-ac44d121)
[concepts/outlook-contacts-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-contacts-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-contacts-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-44981886460d087d09a5946997af483a-ac44d121)
[concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-create-send-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-create-send-messages?branch=pr-en-us-17209) | [Details](#user-content-c389270f569a8aab47cd688a73ca475d-ac44d121)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/outlook-mail-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-17209) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-ac44d121)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-ac44d121)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-ac44d121)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-ac44d121)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaex [...]

2022-06-28 18:11 UTC, opbld32 commented
Docs Build status updates of commit _[6e7b691](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e7b6910b75ffb6c71214d0197157a57af40268c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3f51603b)

<a id="3f51603b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206281810442195-17209/BuildReport?accessString=c7a761c738a33bf7c43d187b7ada31c99999384474886b7fe46d9d3f2f20893c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-28 19:00 UTC, opbld33 commented
Docs Build status updates of commit _[b79bb1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b79bb1d64756d1cd6de41ad0ad012afc11b5ef3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-cfc9669a)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-cfc9669a)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-cfc9669a)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-cfc9669a)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-cfc9669a)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-cfc9669a)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-cfc9669a)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-cfc9669a)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-be [...]

2022-06-28 19:13 UTC, opbld31 commented
Docs Build status updates of commit _[b1a89e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1a89e2fde636e13e69e299b6b88a5c4636b5546)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-72df970a)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-72df970a)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-72df970a)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-72df970a)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-72df970a)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-72df970a)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-72df970a)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-72df970a)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-be [...]

2022-06-28 19:31 UTC, opbld31 commented
Docs Build status updates of commit _[4a9b121](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a9b12199c8a602ab986aaaef574e7a05ff85488)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-1035e4df)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-1035e4df)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-1035e4df)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-1035e4df)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-47c7e4a3d6c3876212b67b5298d263ff-1035e4df)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-1035e4df)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-1035e4df)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-1035e4df)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-be [...]

2022-06-28 19:40 UTC, opbld31 commented
Docs Build status updates of commit _[1ed8711](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ed8711eb5024380425a84b8727355c6857cd358)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) | [Details](#user-content-1bbb0770ef43157a7d843e44fabd6f55-0d33ce49)
[api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/group-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-008bcb62d715ef03cead4e162dfd4af7-0d33ce49)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-c2db825c3d3a73c5164cc8c7a4393f57-0d33ce49)
[api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/api/user-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-10c86d8a88099690174c96beab1c9f0c-0d33ce49)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-17209) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-0d33ce49)
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/changelog-archive.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17209) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-0d33ce49)
[concepts/extensibility-open-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/concepts/extensibility-open-users.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-open-users?branch=pr-en-us-17209) | [Details](#user-content-6ff2b8ea6469a77c2364bc90128f266e-0d33ce49)
[api-reference/beta/api/administrativeunit-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/administrativeunit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/application-list-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/application-list-extensionproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-extensionproperty?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/directory-list-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/directory-list-administrativeunits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directory-list-administrativeunits?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/extensionproperty-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/extensionproperty-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/extensionproperty-delete?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/group-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/schemaextension-post-schemaextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/resources/administrativeunit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/msgraphExtensionsRefresh/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17209) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoft [...]

2022-06-29 06:58 UTC, FaithOmbongi commented
Still investigating how to use breadcrumbs and context files to force the docs portal to maintain context for the Overview article in the beta/v1.0 TOCs.

2022-06-30 02:59 UTC, merged