Adding new reports api details
microsoftgraph/microsoft-graph-docs pull request #17233
Opened 2022-06-14 06:35 UTC by yadavgaurav121

2022-06-14 06:38 UTC, opbld32 commented
Docs Build status updates of commit _[d8528bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8528bbc0e68bcfd0033ddb4aa8158a0230942f3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-security-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-security-getattacksimulationrepeatoffenders.md) | :x:Error | | [Details](#user-content-5076f0d7a5f9587dde34df475983f0b5-ae0bf858)
[api-reference/beta/api/reportroot-security-simulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-security-simulationsimulationusercoverage.md) | :x:Error | | [Details](#user-content-37eed0893eb8e4ab704c2eed8b7f04a9-ae0bf858)
[api-reference/beta/api/reportroot-security-simulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-security-simulationtrainingusercoverage.md) | :x:Error | | [Details](#user-content-1ea802877cff8c1a5f4022f3ed7129d6-ae0bf858)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-ae0bf858)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-ae0bf858)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-ae0bf858)

<a id="5076f0d7a5f9587dde34df475983f0b5-ae0bf858"></a>
### [api-reference/beta/api/reportroot-security-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-security-getattacksimulationrepeatoffenders.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-security-getattacksimulationrepeatoffenders-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-security-getattacksimulationrepeatoffenders-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-security-getattacksimulationrepeatoffenders-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-security-getattacksimulationrepeatoffenders-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/reportroot-security-getattacksimulationrepeatoffenders-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/reportroot-security-getattacksimulationrepeatoffenders-powershell-snippets.md'.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot: getAttackSimulationRepeatOffenders' is duplicated with other articles: 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(10,1), beta/api/reportroot-security-getattacksimulationrepeatoffenders.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/reportroot-security-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="37eed0893eb8e4ab704c2eed8b7f04a9-ae0bf858"></a>
### [api-reference/beta/api/reportroot-security-simulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-security-simulationsimulationusercoverage.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-security-getattacksimulationsimulationusercoverage-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-security-getattacksimulationsimulationusercoverage-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-security-getattacksimulationsimulationusercoverage-objc-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-security-getattacksimulationsimulationusercoverage-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/reportroot-security-getattacksimulationsimulationusercoverage-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/reportroot-security-getattacksimulationsimulationusercoverage-powershell-snippets.md'.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot: getAttackSimulationSimulationUserCoverage' is duplicated with other articles: 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(10,1), beta/api/reportroot-security-simulationsimulationusercoverage.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/reportroot-security-simulationsimulationusercoverage.md(3,14)'.`````

<a id="1ea802877cff8c1a5f4022f3ed7129d6-ae0bf858"></a>
### [api-reference/beta/api/reportroot-security-simulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-security-simulationtrainingusercoverage.md)
 - **Line 64, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-security-getattacksimulationtrainingusercoverage-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-security-getattacksimulationtrainingusercoverage-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-security-getattacksimulationtrainingusercoverage-objc-snippets [...]

2022-06-14 08:37 UTC, opbld32 commented
Docs Build status updates of commit _[da3b67d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da3b67de34698db64ae590babcf8537d6bfe4595)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-9691558d)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-9691558d)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-9691558d)
[api-reference/beta/api/securityreportsroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-update?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-28ebd33c8339a3bd94a98fb802faccd9-9691558d)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-cbf5279dad5f670ebdfcc4832a149ed3-9691558d)

<a id="595e76f17ce825cdc41a083fb6920c74-9691558d"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="16e75ade0dd13df69d52323c327d0f8d-9691558d"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-9691558d"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="28ebd33c8339a3bd94a98fb802faccd9-9691558d"></a>
### [api-reference/beta/api/securityreportsroot-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-update.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid [...]

2022-06-14 08:45 UTC, opbld33 commented
Docs Build status updates of commit _[5d4c358](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d4c35808e30c4aa17dbfd2041d262f82cf15733)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-331e2356)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-331e2356)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-331e2356)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-cbf5279dad5f670ebdfcc4832a149ed3-331e2356)

<a id="595e76f17ce825cdc41a083fb6920c74-331e2356"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="16e75ade0dd13df69d52323c327d0f8d-331e2356"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-331e2356"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="cbf5279dad5f670ebdfcc4832a149ed3-331e2356"></a>
### [api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod':  [...]

2022-06-15 08:59 UTC, opbld32 commented
Docs Build status updates of commit _[5a829e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a829e35ffad2debe012baf8ded83451a4b82bb5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-6fff8aa9)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-6fff8aa9)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-6fff8aa9)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-cbf5279dad5f670ebdfcc4832a149ed3-6fff8aa9)
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="595e76f17ce825cdc41a083fb6920c74-6fff8aa9"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="16e75ade0dd13df69d52323c327d0f8d-6fff8aa9"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-6fff8aa9"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="cbf5279dad5f670ebdfcc4832a149ed3-6fff8aa9"></a>
### [api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6,  [...]

2022-06-15 09:16 UTC, opbld32 commented
Docs Build status updates of commit _[f567d74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f567d7409ebc575f08565f116cf5b56b6adb77df)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :x:Error | | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-da6e098c)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-da6e098c)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-da6e098c)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :warning:Warning | | [Details](#user-content-cbf5279dad5f670ebdfcc4832a149ed3-da6e098c)

<a id="16e75ade0dd13df69d52323c327d0f8d-da6e098c"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 61, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/securityReportsRoot-getattacksimulationsimulationusercoverage-csharp-snippets.md'.`````
 - **Line 65, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/securityReportsRoot-getattacksimulationsimulationusercoverage-javascript-snippets.md'.`````
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/securityReportsRoot-getattacksimulationsimulationusercoverage-objc-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/securityReportsRoot-getattacksimulationsimulationusercoverage-java-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/securityReportsRoot-getattacksimulationsimulationusercoverage-go-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/securityReportsRoot-getattacksimulationsimulationusercoverage-powershell-snippets.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="595e76f17ce825cdc41a083fb6920c74-da6e098c"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-da6e098c"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="cbf5279dad5f670ebdfcc4832a149ed3-da6e098c"></a>
### [api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value [...]

2022-06-15 09:24 UTC, opbld31 commented
Docs Build status updates of commit _[58ffc4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58ffc4bb912c52a8d47d7ad18bf7c9a2ed6f9393)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-c363ddb4)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-c363ddb4)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-c363ddb4)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-cbf5279dad5f670ebdfcc4832a149ed3-c363ddb4)
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationsimulationusercoverage-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationsimulationusercoverage-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationsimulationusercoverage-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationsimulationusercoverage-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationsimulationusercoverage-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationsimulationusercoverage-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/javascript/securityreportroot-getattacksimulationsimulationusercoverage-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/javascript/securityreportroot-getattacksimulationsimulationusercoverage-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/objc/securityreportroot-getattacksimulationsimulationusercoverage-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/objc/securityreportroot-getattacksimulationsimulationusercoverage-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/snippets/powershell/securityreportroot-getattacksimulationsimulationusercoverage-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/powershell/securityreportroot-getattacksimulationsimulationusercoverage-powershell-snippets.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="595e76f17ce825cdc41a083fb6920c74-c363ddb4"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/resources/securityreportsroot.md(3,14)'.`````

<a id="16e75ade0dd13df69d52323c327d0f8d-c363ddb4"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Stu-MSFT' is not a valid GitHub ID.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-c363ddb4"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=API/Document/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com [...]

2022-06-15 09:41 UTC, opbld30 commented
Docs Build status updates of commit _[28f338c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28f338cb06b8b2ac6657fd07fb324eb3b5ccdcc0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-2255d2aa)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-2255d2aa)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-2255d2aa)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="16e75ade0dd13df69d52323c327d0f8d-2255d2aa"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'gauravyadav121' is not a valid GitHub ID.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="595e76f17ce825cdc41a083fb6920c74-2255d2aa"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-2255d2aa"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206150938530605-17233/BuildReport?accessString=4b989ce71b4ed04ced64cd80bf3102ed2350da7635b642b6b43e9ee181a15d40).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-15 09:44 UTC, opbld32 commented
Docs Build status updates of commit _[76a1cde](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76a1cde83dde661f2eaf620a50589925d4d00787)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-7374ce07)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-7374ce07)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-7374ce07)
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="595e76f17ce825cdc41a083fb6920c74-7374ce07"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="16e75ade0dd13df69d52323c327d0f8d-7374ce07"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="f9934af15d8bbafc3b75351f2eed8e3b-7374ce07"></a>
### [api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206150942365967-17233/BuildReport?accessString=9f36f16a1b8d972f1e070a377248dc5511e76d4bf08c72d9391a9f69db76805a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 05:19 UTC, angelgolfer-ms commented
Planning to walk through the content review with Steve and start the review the week of 7/5 (7/4 a US holiday).

2022-07-07 08:07 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md
> +author: "yadavgaurav121"
Line 4 and GLOBAL:
FYI the author field across all the topics for a workload should use the same value. I see that your team has Gopal-MSFT in that field for some of the earlier topics. Can you please decide with your team which one person should be in the author field? That person would get email notifications when customers open Github issues against topics for that workload. To decrease the chance that the person moves on to another project in the team and doesn't respond to customer issues, and to make it more sustainable to manage, we require workload teams to assign the field to only one value they agree upon.

2022-07-07 08:25 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md
> +title: "securityReportsRoot: getAttackSimulationRepeatOffenders"
@yadavgaurav121 , please see my questions on Teams regarding this set of APIs and the existing set with the same method names.

2022-07-07 08:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/securityreportsroot.md
> +|[getAttackSimulationSimulationUserCoverage](../api/securityreportsroot-getattacksimulationsimulationusercoverage.md)|[attackSimulationSimulationUserCoverage](../resources/attacksimulationsimulationu
Lines 24-26, and line 31:
Please fill in the description column for each of the 3 methods, and the id property.

GLOBAL:
Please search or look out for these "TODO:" strings to make sure you provide the necessary content.

2022-07-07 08:36 UTC, angelgolfer-ms requested changes
Hi @yadavgaurav121 , I made a quick first pass on this PR. Please see my comments in your PR and questions on Teams.
Thanks.

2022-07-08 05:38 UTC, opbld33 commented
Docs Build status updates of commit _[5a1e926](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a1e9260d84c98e541de68cc95214a8847b13253)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-ed99089a)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-ed99089a)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-ed99089a)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-ed99089a)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-ed99089a)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-ed99089a)
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationrepeatoffenders-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationrepeatoffenders-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationsimulationusercoverage-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationsimulationusercoverage-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationtrainingusercoverage-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationtrainingusercoverage-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationrepeatoffenders-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationrepeatoffenders-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationsimulationusercoverage-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationsimulationusercoverage-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationtrainingusercoverage-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationtrainingusercoverage-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationrepeatoffenders-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationrepeatoffenders-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationsimulationusercoverage-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationsimulationusercoverage-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationtrainingusercoverage-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationtrainingusercoverage-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-1 [...]

2022-07-08 05:42 UTC, yadavgaurav121 commented
@angelgolfer-ms Please have a look at updated pr. 
#feedback-addressed

2022-07-08 08:30 UTC, opbld34 commented
Docs Build status updates of commit _[81431d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81431d9e138f6f137530ced4fd9e376228373581)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-dda6077d)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-dda6077d)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-dda6077d)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-dda6077d)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-dda6077d)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-dda6077d)
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationrepeatoffenders-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationrepeatoffenders-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationsimulationusercoverage-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationsimulationusercoverage-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationtrainingusercoverage-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationtrainingusercoverage-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationrepeatoffenders-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationrepeatoffenders-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationsimulationusercoverage-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationsimulationusercoverage-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationtrainingusercoverage-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/go/securityreportroot-getattacksimulationtrainingusercoverage-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationrepeatoffenders-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationrepeatoffenders-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationsimulationusercoverage-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationsimulationusercoverage-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationtrainingusercoverage-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/snippets/java/securityreportroot-getattacksimulationtrainingusercoverage-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-1 [...]

2022-07-14 03:58 UTC, angelgolfer-ms commented on api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationrepeatoffenders-csharp-snippets.md
> +---
This comment applies to all the 6x3=18 files you included under the snippets folder:
Please delete these files from your PR. Authors don't have to and shouldn't update them.
After your PR is eventually published, there's a tool that runs every week that checks for any examples that have been added or that have the requests updated, and inserts these code snippet files automatically.

2022-07-14 04:04 UTC, yadavgaurav121 commented on api-reference/beta/includes/snippets/csharp/securityreportroot-getattacksimulationrepeatoffenders-csharp-snippets.md
> +---
sure, I'll remove their reference as well.

2022-07-14 04:11 UTC, opbld34 commented
Docs Build status updates of commit _[703e989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/703e989adbb439edce0115c72088afc69f96bdff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-e8cad1ef)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-e8cad1ef)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-e8cad1ef)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-e8cad1ef)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-e8cad1ef)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-e8cad1ef)
[api-reference/beta/includes/todo-deprecate-ast-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/todo-deprecate-ast-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-e8cad1ef"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-e8cad1ef"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-e8cad1ef"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-e8cad1ef"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-e8cad1ef"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/secu [...]

2022-07-14 04:12 UTC, angelgolfer-ms commented on api-reference/beta/includes/todo-deprecate-ast-reportapi.md
> +---
Can you rename this file to not use the "todo" file prefix? For example, use "attack-sim-deprecate-queryurl-reportapi.md"?

2022-07-16 05:42 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md
> +| Delegated (work or school account)     | Reports.Read.All                            |
I have one question and one comment about the permission Reports.Read.All:

(A) Is your API set continuing to use Reports.Read.All? 
Since you currently have published topics that use that permission, you need to do 2 things to catch up:

(a) In the Azure portal, the display string and description for that permission still mention only usage reports. Your reports are not usage reports. When you last published your attack simulation APIs and started using Reports.Read.All, you or your team should have made those updates in the Azure portal. For example, the display string on the portal still says "Read all usage reports". Your team should have updated that display string to say something to the effect of, "Read all usage reports and attack simulation report that use the /reports query URL segment."
The existing description on the portal needs a similar update to include your API as well.

(b) In the [permissions reference topic](https://docs.microsoft.com/en-us/graph/permissions-reference#reports-permissions) in the docs, you also need to make the similar updates to the display string and description.

2022-07-16 05:54 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md
> +| Delegated (work or school account)     | Reports.Read.All                            |
Similarly, you should please catch up and do the similar for the SecurityEvents.Read.All permission, even though this PR doesn't include topics that use that permission.
In the Azure portal and in the docs, the display string and description for SecurityEvents.Read.All refers to security events in an organization. These are real events used by the alert and secure score APIs. Please include attack simulation events to the display name and description to be clear. Doing so would also help expose your attack simulation feature to customers.

2022-07-16 06:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/securityreportroot.md
> +Provides the ability to launch a realistic phishing attack that organizations can learn from.
Line 16:
I think it would be clearer if the description says "... launch a simulated but realistic phishing attack..."

2022-07-16 06:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/securityreportroot.md
> +
This comment is about the actual resource name - is it (plural reports) securityReportsRoot, or (singular report) securityReportRoot?
Your api.md and CSDL files say the former (plural reports).

If it's the former, then please rename the file, and update lines 2 and 10, and anywhere you have links to the file.

2022-07-16 06:24 UTC, angelgolfer-ms commented on api-reference/beta/resources/securityreportroot.md
> +---
Please update the reportroot.md topic to include the security nav property in the "Relationships" section. Please add that property and maintain alphabetical order in that table.

2022-07-16 07:22 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getAttackSimulationRepeatOffenders?$skiptoken=+RID%3",
Line 78:
Is the nextLink really calling /reports/getAttackSimulationRepeatOffenders? Not /reports/security/getAttackSimulationRepeatOffenders?

2022-07-16 07:23 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getAttackSimulationSimulationUserCoverage?$skiptoken=rZDNasMwEIRfxei%2bRLFWtgRxwZKsYCil0J9rcCORGlI7yHLbvH3j0pQefCqew7LMsOzHbEL%2fkbRuV
Line 78:
Please confirm if the nextLink really calls /reports/getAttackSimulationSimulationUserCoverage and not /reports/security/getAttackSimulationSimulationUserCoverage.

2022-07-16 07:25 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getAttackSimulationTrainingUserCoverage?$skiptoken=+RID%3",
Line 79:
Similar question for the nextLink: please confirm if indeed that request calls /reports/getAttackSimulationTrainingUserCoverage and not /reports/security/getAttackSimulationTrainingUserCoverage.

2022-07-16 07:32 UTC, angelgolfer-ms commented on api-reference/beta/resources/securityreportroot.md
> +title: "securityReportRoot resource type"
Please also update the report-m365defender-reports-overview.md topic. There's a [table](https://docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta#what-kinds-of-data-do-the-reports-return) that needs to be updated to link to the 3 methods that use the /reports/security query URL segments.

2022-07-16 08:26 UTC, angelgolfer-ms commented on api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md
> +
Line 13: you already have line 17 that inserts the beta disclaimer boilerplate, you don't need this line. 
Line 15: that's a copy-and-paste error? This line doesn't look relevant.

I'll clean these 2 lines up for you on your behalf. I want to use this topic to experiment a better way of handling the deprecation of the /reports/getAttackSimulationRepeatOffenders endpoint. The way we have it right now - marking the entire topic reportroot-getattacksimulationrepeatoffenders.md as deprecated - forces customers to compare line by line the different between that earlier version of the method with the newer version securityreportroot-getattacksimulationrepeatoffenders.md. The deprecation note should point out what's actually different between the old and new.

2022-07-16 09:02 UTC, opbld34 commented
Docs Build status updates of commit _[aa01413](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa01413ed7d5ca78f4dc8b8a7254ecc9361b830c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :x:Error | | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-71977199)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :x:Error | | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-71977199)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-71977199)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-71977199)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-71977199)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-71977199)

<a id="3e197371ece25b644d2591b0dc62f62c-71977199"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/todo-deprecate-ast-reportapi.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-71977199"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/todo-deprecate-ast-reportapi.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="fb24c015ea72b88830889422e69d89cf-71977199"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-71977199"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-71977199"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="ea45024ed61ed8f121b9e63e92753acc-71977199"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160900316001-17233/BuildReport?accessString=0d513fdfa3de028468628fc346ed1fe240a6012c11ee383d66e0837c6e5081fa).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** [...]

2022-07-16 09:04 UTC, opbld30 commented
Docs Build status updates of commit _[378cd8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/378cd8b42729e8c7e800b6d685f8c6328392fb6b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :x:Error | | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-d8cb21ef)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :x:Error | | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-d8cb21ef)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-d8cb21ef)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-d8cb21ef)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-d8cb21ef)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-d8cb21ef)

<a id="3e197371ece25b644d2591b0dc62f62c-d8cb21ef"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/todo-deprecate-ast-reportapi.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-d8cb21ef"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 15, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/todo-deprecate-ast-reportapi.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="fb24c015ea72b88830889422e69d89cf-d8cb21ef"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-d8cb21ef"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-d8cb21ef"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="ea45024ed61ed8f121b9e63e92753acc-d8cb21ef"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160901097953-17233/BuildReport?accessString=130ed93e5ea5c5748e0f4a5818637f5243e0358670465cbe59d5cb2be41dab79).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** [...]

2022-07-16 09:13 UTC, opbld32 commented
Docs Build status updates of commit _[7e11a69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e11a695468902c8d2cb4397a091762be59a572d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-42e627c0)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-42e627c0)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-42e627c0)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-42e627c0)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-42e627c0)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-42e627c0)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-42e627c0"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-42e627c0"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-42e627c0"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-42e627c0"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-42e627c0"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-ref [...]

2022-07-16 09:33 UTC, opbld32 commented
Docs Build status updates of commit _[fc764ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc764ee726c78b2cd4a404aba6b97797a00af365)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-f2fd3aba)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-f2fd3aba)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-f2fd3aba)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-f2fd3aba)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-f2fd3aba)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-f2fd3aba)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-f2fd3aba"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-f2fd3aba"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-f2fd3aba"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-f2fd3aba"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-f2fd3aba"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-ref [...]

2022-07-16 09:43 UTC, opbld32 commented
Docs Build status updates of commit _[89e9ae1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89e9ae1173b197a6f0d5c15ee74370fff8a81619)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-9c8cac91)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-9c8cac91)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-9c8cac91)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-9c8cac91)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-9c8cac91)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-9c8cac91)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-9c8cac91"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-9c8cac91"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-9c8cac91"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-9c8cac91"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-9c8cac91"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-ref [...]

2022-07-16 10:11 UTC, opbld30 commented
Docs Build status updates of commit _[9ac00ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ac00efadcd2fe7f87b4aa863fa8d19b251e27ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-d00207c1)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-d00207c1)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-d00207c1)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-d00207c1)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-d00207c1)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-d00207c1)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-d00207c1"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-d00207c1"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-d00207c1"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="d499808cdd8961a75cd1b24c89704d75-d00207c1"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="c45e656e893b7e470c2664d8be8da6bf-d00207c1"></a>
### [api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-ref [...]

2022-07-16 10:12 UTC, angelgolfer-ms requested changes
Hi @yadavgaurav121 , I finished my pass.
I reorganized the way we mark the deprecation, and reworded the deprecation note. See my comment here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/17233#discussion_r922651303

I revised the changelist records and fixed the links you had there before.

I also added a few more comments, please take a look and address them.

2022-07-18 04:13 UTC, yadavgaurav121 commented on api-reference/beta/includes/todo-deprecate-ast-reportapi.md
> +---
updated it to ast-deprecate-queryurl-reportapi

2022-07-18 04:41 UTC, yadavgaurav121 commented on api-reference/beta/resources/securityreportroot.md
> +Provides the ability to launch a realistic phishing attack that organizations can learn from.
updated

2022-07-18 04:46 UTC, yadavgaurav121 commented on api-reference/beta/resources/securityreportroot.md
> +---
updated

2022-07-18 04:48 UTC, yadavgaurav121 commented on api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getAttackSimulationRepeatOffenders?$skiptoken=+RID%3",
updated

2022-07-18 04:49 UTC, yadavgaurav121 commented on api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getAttackSimulationSimulationUserCoverage?$skiptoken=rZDNasMwEIRfxei%2bRLFWtgRxwZKsYCil0J9rcCORGlI7yHLbvH3j0pQefCqew7LMsOzHbEL%2fkbRuV
updated

2022-07-18 04:49 UTC, yadavgaurav121 commented on api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getAttackSimulationTrainingUserCoverage?$skiptoken=+RID%3",
updated

2022-07-18 04:52 UTC, yadavgaurav121 commented on api-reference/beta/resources/securityreportroot.md
> +title: "securityReportRoot resource type"
updated

2022-07-18 05:25 UTC, yadavgaurav121 commented on api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md
> +| Delegated (work or school account)     | Reports.Read.All                            |
Currently we are using Reports.Read.All, SecurityEvents.Read.All. These permission will be replaced with AttackSimulation.Read.All which is AST specific with proper details. 
I will be raising the permission changes pr once this pr is complete. 

P.S Reports.Read.All, SecurityEvents.Read.All permission are not owned by our team and service wider purpose and next pr for new permission should resolve it for AST.

2022-07-18 05:53 UTC, yadavgaurav121 commented on api-reference/beta/resources/securityreportroot.md
> +
updated to securityReportsRoot

2022-07-18 05:54 UTC, opbld33 commented
Docs Build status updates of commit _[385ea4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/385ea4fdf305724db6270204c471bda84d0dd8d0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f22c2ce4)

<a id="f22c2ce4"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207180553382765-17233/BuildReport?accessString=7b5cfeace32cdad93b2cb3a77c7f974fe2585977f12bd2d528a0354862969183).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[8430b3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8430b3ab0182ee98a08269d49063a52234981bed)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-03ed7006)

<a id="03ed7006"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207180605221776-17233/BuildReport?accessString=6ce36aaa8603e429e035da1f2c7e8ba873cbf40136580edd1385c957efc3d65c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 06:08 UTC, yadavgaurav121 commented
@angelgolfer-ms Addressed the comments please have a look. 
P.S I am getting a strange build error over github related to merge to main which I am not getting over local. Please help me fix this.

2022-07-18 20:56 UTC, opbld32 commented
Docs Build status updates of commit _[4f688ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f688abcef70d69df0af4832627bbc0c5c7ab1d3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b989676b)

<a id="b989676b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207182055372470-17233/BuildReport?accessString=bda136e1d3ac80ec4ff0987d1d2792e7b03236c55bab5432c138433468adc306).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 21:15 UTC, opbld32 commented
Docs Build status updates of commit _[5694c97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5694c9756d3f2df7c3a2895b691dcfc8189f2ee6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-4b4bb884)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-4b4bb884)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-4b4bb884)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-4b4bb884)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-4b4bb884)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-4b4bb884)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-4b4bb884)
[api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-4b4bb884"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-4b4bb884"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-4b4bb884"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for [...]

2022-07-18 21:27 UTC, angelgolfer-ms commented on api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md
>  List [training coverage](../resources/attacksimulationtrainingusercoverage.md) for each user of a tenant in attack simulation and training campaigns.
Lines 15-19:
This is the second merge conflict you had, similar to the one in reportroot-getattachsimulationsimulationusercoverage.md. FYI I also resolved this merge conflict on your behalf.

2022-07-18 21:29 UTC, angelgolfer-ms commented on api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md
> +
FYI we don't need this note anymore, per my updates in my last [review](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17233#pullrequestreview-1040978116).

We should delete this file.
I would like you to confirm the contents in the caution note in attacksim-deprecate-uqeryurl-reportapi.md, especially the dates in that note.

2022-07-18 21:40 UTC, angelgolfer-ms commented on api-reference/beta/resources/report-m365defender-reports-overview.md
> +| Vulnerable repeat offenders in a tenant | [attackSimulationRepeatOffender](attacksimulationrepeatoffender.md) | [getAttackSimulationRepeatOffenders](../api/securityreportroot-getattacksimulationrep
Lines 43-45:
In your pass prior to my last [review](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17233#pullrequestreview-1040978116), what I found that was likely going to be confusing to customers was, the way we refer to the old topics and new topics, including the topic titles and their link text, is exactly the same. When customers are browsing, we can't expect them to discern the difference by hovering over or clicking the links.

In my [review](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17233#pullrequestreview-1040978116), I decided to alleviate confusion at that level by prioritizing on exposing the new topics and the way to access the APIs through the new endpoint, while bringing up in the same (new) topics that the old way and old endpoint is being deprecated.

So while we don't delete the old topics from the repo until the point that you remove those old APIs from your service, we only use See-also links to let customers go from the new topics to the old topics.

2022-07-18 21:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/report-m365defender-reports-overview.md
> +| Vulnerable repeat offenders in a tenant | [attackSimulationRepeatOffender](attacksimulationrepeatoffender.md) | [getAttackSimulationRepeatOffenders](../api/securityreportroot-getattacksimulationrep
For efficiency to cut out more iterations, FYI I am going ahead to delete lines 40-42.

BTW, I wonder if you have used the staging site to look at the doc experience? That could have helped you observe that level of confusion I was describing above. Start with the [API overview topic on the staging site](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233#what-kinds-of-data-do-the-reports-return).

2022-07-18 22:04 UTC, opbld33 commented
Docs Build status updates of commit _[e062acd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e062acd24a7b0e66c1990e2822ccbf7c57cbf4d6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-64e6cab4)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-64e6cab4)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-64e6cab4)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-64e6cab4)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-64e6cab4)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-64e6cab4)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-64e6cab4)
[api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-64e6cab4"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-64e6cab4"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-64e6cab4"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for [...]

2022-07-18 22:19 UTC, opbld34 commented
Docs Build status updates of commit _[8eb9e1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8eb9e1dea9880d79a8d76045d0564da3dce29559)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-5bbcb842)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-5bbcb842)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-5bbcb842)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-5bbcb842)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-5bbcb842)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-5bbcb842)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-5bbcb842)
[api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-5bbcb842"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-5bbcb842"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-5bbcb842"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for [...]

2022-07-19 04:09 UTC, yadavgaurav121 commented on api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md
> +
looks good. I have deleted the ast-deprecate-queryurl-reportapi.md

2022-07-19 04:11 UTC, yadavgaurav121 commented on api-reference/beta/resources/report-m365defender-reports-overview.md
> +| Vulnerable repeat offenders in a tenant | [attackSimulationRepeatOffender](attacksimulationrepeatoffender.md) | [getAttackSimulationRepeatOffenders](../api/securityreportroot-getattacksimulationrep
sounds good.

2022-07-19 04:13 UTC, yadavgaurav121 commented on api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md
> +<<<<<<< Updated upstream
Thanks @angelgolfer-ms

2022-07-20 05:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/reportroot.md
> +|securityReportsRoot|[securityReportsRoot](../resources/securityreportsroot.md) collection|Provides the ability to launch a realistic simulated phishing attack that organizations can learn from.|
Line 45:
@yadavgaurav121 , the nav property name is security.
I'll change it on your behalf so that we can wrap this up :-)

2022-07-20 05:55 UTC, opbld33 commented
Docs Build status updates of commit _[e0c2656](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0c2656222497e3ef8f267117653fbeba9951613)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-7b46e0e9)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-7b46e0e9)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-7b46e0e9)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-7b46e0e9)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-7b46e0e9)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-7b46e0e9)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-7b46e0e9)
[api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-7b46e0e9"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-7b46e0e9"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-7b46e0e9"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for [...]

2022-07-20 05:59 UTC, opbld33 commented
Docs Build status updates of commit _[a7f0e37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7f0e3707abd1628a90222582fc63bb8d2bc4504)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-2bbe7ead)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-2bbe7ead)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-2bbe7ead)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-2bbe7ead)
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-d499808cdd8961a75cd1b24c89704d75-2bbe7ead)
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-c45e656e893b7e470c2664d8be8da6bf-2bbe7ead)
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-ea45024ed61ed8f121b9e63e92753acc-2bbe7ead)
[api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | |
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-2bbe7ead"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-2bbe7ead"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-2bbe7ead"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for [...]

2022-07-20 07:00 UTC, angelgolfer-ms commented on api-reference/beta/includes/ast-deprecate-queryurl-reportapi.md
> +
Hm, it's still in your branch. 
I'll delete that file.

2022-07-20 07:05 UTC, angelgolfer-ms commented on api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md
> +title: "securityReportRoot: getAttackSimulationRepeatOffenders"
This comment is for each of the 3 method topics for securityReportsRoot:
FYI I renamed the files for the 3 method topics as well to include the second 's' in "securityReportsRoot", and updated their topic title, their TOC and any other links to these 3 topics.

2022-07-20 07:10 UTC, opbld34 commented
Docs Build status updates of commit _[e4e1bd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4e1bd1e35c3a4ee396ea98f4dd41759beed398a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-19904de8)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-19904de8)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-19904de8)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-19904de8)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-19904de8)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-19904de8)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-19904de8)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-19904de8"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-19904de8"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-19904de8"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3 [...]

2022-07-20 07:17 UTC, opbld34 commented
Docs Build status updates of commit _[2f264a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f264a9374b0412aa6451fa55d423dd2330b6d12)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-a982d421)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-a982d421)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-a982d421)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-a982d421)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-a982d421)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-a982d421)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-a982d421)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-a982d421"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-a982d421"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-a982d421"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3 [...]

2022-07-20 07:43 UTC, opbld30 commented
Docs Build status updates of commit _[252bd47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/252bd478f44c6bb32b7c04e4c81497ebb7b9a003)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-bff52513)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-bff52513)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-bff52513)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-bff52513)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-bff52513)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-bff52513)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-bff52513)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-bff52513"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-bff52513"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-bff52513"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3 [...]

2022-07-20 07:51 UTC, angelgolfer-ms approved these changes
I reviewed the topics again and made some more fixes directly in the PR so to wrap up the content review.

2022-07-20 22:10 UTC, opbld32 commented
Docs Build status updates of commit _[2252440](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2252440d0dd6ec2ea4004066638e499576461243)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/reportroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-36aca899975750795ed56a0b002db749-bb12d82a)
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-bb12d82a)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-bb12d82a)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-bb12d82a)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-bb12d82a)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-bb12d82a)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-bb12d82a)
[api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/includes/attacksim-deprecate-queryurl-reportapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/report-m365defender-reports-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/report-m365defender-reports-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report-m365defender-reports-overview?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/resources/securityreportsroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/securityreportsroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/securityreportsroot?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17233) (graph-rest-beta) |
[changelog/Microsoft.Security.AttackSimulation.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/changelog/Microsoft.Security.AttackSimulation.json) | :white_check_mark:Succeeded | |

<a id="36aca899975750795ed56a0b002db749-bb12d82a"></a>
### [api-reference/beta/resources/reportroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/resources/reportroot.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'reportRoot resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-shared-reportroot.md(2,8), beta/resources/reportroot.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'reportRoot resource type' is duplicated with other articles: 'beta/resources/intune-shared-reportroot.md(10,1), beta/resources/reportroot.md(10,1)'. First level headings must be unique within a docset.`````

<a id="fb24c015ea72b88830889422e69d89cf-bb12d82a"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-bb12d82a"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/reportpathchnage/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3 [...]

2022-07-20 22:31 UTC, merged