[Elm] [1.0] reprocess access package assignment
microsoftgraph/microsoft-graph-docs pull request #17231
Opened 2022-06-13 23:47 UTC by ajburnle

doc update because this api is now in 1.0

2022-06-13 23:50 UTC, opbld30 commented
Docs Build status updates of commit _[ee560e7](https://github.com/ajburnle/microsoft-graph-docs/commits/ee560e72af8b8a22b4623fd760293f65c3e50fc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206132347431757-17231/BuildReport?accessString=b477d4a4e78e3f9b1b16a3b02309c0f8ed3175d69299d5bce7f47ab86539848d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 02:27 UTC, opbld33 commented
Docs Build status updates of commit _[0ab716a](https://github.com/ajburnle/microsoft-graph-docs/commits/0ab716abf4a57aec561de98de1698530a372006e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) |
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206160223116971-17231/BuildReport?accessString=d1e07c4095f2160bea850a6a18eb922dd0a171ec61245dbf7b64ca401a88f561).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 18:15 UTC, ajburnle commented
@FaithOmbongi  @Lauragra it won't let me change the merge labels. Can you please review this pull request

2022-06-21 18:16 UTC, ajburnle commented
assign: @ajburnle

2022-06-21 18:17 UTC, ajburnle commented
reassign: @FaithOmbongi

2022-06-21 18:18 UTC, ajburnle commented
re-assign: @FaithOmbongi

2022-06-22 18:35 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +POST https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackageAssignments/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
This is the beta doc - so beta endpoint
```suggestion
POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignments/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
```

2022-06-22 18:45 UTC, FaithOmbongi requested changes
Thank you @ajburnle for your work in this PR. I've left suggestions for minor fixes.

One major discrepancy is the schema vs this PR - the released v1.0 schema doesn't contain any of the properties you've added to the two resources. Could you confirm why the difference between beta and v1.0?

2022-06-22 18:45 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +You can only reprocess a request up to 14 days from the time the original request was completed. For requests completed more than 14 days, you can't reprocess those requests. You will need to ask the
Suggestion
```suggestion
You can only reprocess a request within 14 days from the time the original request was completed. For requests completed more than 14 days, you will need to ask the users to cancel the request(s) and make a new request in the [MyAccess](http://myaccess.microsoft.com/) portal.
```

2022-06-22 18:45 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +POST https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
```suggestion
POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
```

2022-06-22 18:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageassignment.md
> +|schedule|[requestSchedule](requestschedule.md)| When the access assignment is to be in place. Read-only.|
Hmm - The schema for v1.0 looks different from the schema for beta in that only 4 properties are surfaced in v1.0. Could you confirm why the difference?

2022-06-22 18:45 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackageassignmentrequest.md
> +|requestState|String|One of `PendingApproval`, `Canceled`, `Denied`, `Delivering`, `Delivered`, `PartiallyDelivered`, `DeliveryFailed`, `Submitted` or `Scheduled`. Read-only.|
Property not in the v1.0 schema. Kindly confirm

2022-06-22 18:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackageassignment-reprocess.md
> +POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignments/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
This is the v1.0 doc
```suggestion
POST https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackageAssignments/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
```

2022-06-22 18:45 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md
> +POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
```suggestion
POST https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
```

2022-06-22 18:45 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "reprocess"
Fixed links
```suggestion
          "Description": "Added the [reprocess](https://docs.microsoft.com/en-us/graph/api/reprocess?view=graph-rest-1.0) method to the [accessPackageAssignment](https://docs.microsoft.com/en-us/graph/api/accessPackageAssignment?view=graph-rest-1.0) resource.",
          "Target": "accessPackageAssignment"
        },
        {
          "Id": "6c83378e-32f7-4a90-be50-fba95f7890ae",
          "ApiChange": "Method",
          "ChangedApiName": "reprocess",
          "ChangeType": "Addition",
          "Description": "Added the [reprocess](https://docs.microsoft.com/en-us/graph/api/reprocess?view=graph-rest-1.0) method to the [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/accessPackageAssignmentRequest?view=graph-rest-1.0) resource.",
          "Target": "accessPackageAssignmentRequest"
```

2022-06-22 18:45 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Identity governance"
```suggestion
      "SubArea": "Governance"
```

2022-06-22 22:41 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +POST https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackageAssignments/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
no we want it to be a 1.0 doc

2022-06-22 22:44 UTC, opbld32 commented
Docs Build status updates of commit _[f08a4fc](https://github.com/ajburnle/microsoft-graph-docs/commits/f08a4fc350cb98457ddb8654d58fb0219b24c73b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) |
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222242082712-17231/BuildReport?accessString=b466583cdfdbac42cd3614af1eb2010093aed30e33e07f56561a137ce468d73b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 22:53 UTC, opbld34 commented
Docs Build status updates of commit _[1eb237b](https://github.com/ajburnle/microsoft-graph-docs/commits/1eb237b586f2257a16ddce0c8c4c45b9cee5e6c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-ecf234c2)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-ecf234c2)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-ecf234c2)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ecf234c2)
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) | [Details](#user-content-28e735e747132d6f827e5a348d94304b-ecf234c2)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-ecf234c2"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-ecf234c2"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-ecf234c2"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-ecf234c2"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13126, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13172, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="28e735e747132d6f827e5a348d94304b-ecf234c2"></a>
### [api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md)
 - **Line 16, Column 227**: **[Warning: insecure-link - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://myaccess.microsoft.com/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222248286489-17231/BuildReport?accessString=19cdbec7a8617cbb779d1163e447da38bcf45ce5225421688ec49a48f66207c4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](htt [...]

2022-06-22 22:55 UTC, opbld31 commented
Docs Build status updates of commit _[f6a09a7](https://github.com/ajburnle/microsoft-graph-docs/commits/f6a09a7e57bb6ab4ea84663f0d3fd2cf89846a38)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-63d0a7b6)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-63d0a7b6)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-63d0a7b6)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-63d0a7b6)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-63d0a7b6"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-63d0a7b6"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-63d0a7b6"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-63d0a7b6"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13126, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13172, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222245161223-17231/BuildReport?accessString=2544292eb8ed784a77eef15a22e5de9d93962a9abddb28b2ae0cb89ce5329711).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86 [...]

2022-06-22 23:01 UTC, opbld33 commented
Docs Build status updates of commit _[04578d9](https://github.com/ajburnle/microsoft-graph-docs/commits/04578d9820c503b800e24cb24eda081f0f369871)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-cf18b409)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-cf18b409)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-cf18b409)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-cf18b409)
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) | [Details](#user-content-28e735e747132d6f827e5a348d94304b-cf18b409)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-cf18b409"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-cf18b409"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-cf18b409"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-cf18b409"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13126, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13172, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="28e735e747132d6f827e5a348d94304b-cf18b409"></a>
### [api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md)
 - **Line 16, Column 227**: **[Warning: insecure-link - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://myaccess.microsoft.com/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222258121714-17231/BuildReport?accessString=522848d8250139a9673018aba6f49506956295a7888c4be1abfa78b08c40a001).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](htt [...]

2022-06-22 23:48 UTC, opbld33 commented
Docs Build status updates of commit _[d55e5cd](https://github.com/ajburnle/microsoft-graph-docs/commits/d55e5cdab507042d3c80480fc3895c5bbdd649fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-812a737d)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-812a737d)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-812a737d)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-812a737d)
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) | [Details](#user-content-28e735e747132d6f827e5a348d94304b-812a737d)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-812a737d"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-812a737d"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-812a737d"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-812a737d"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13126, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13172, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="28e735e747132d6f827e5a348d94304b-812a737d"></a>
### [api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md)
 - **Line 16, Column 227**: **[Warning: insecure-link - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://myaccess.microsoft.com/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206222346097289-17231/BuildReport?accessString=d03d80724d06176cac9dd6c2069ca2d0210c2346a8980be06b5df23df967ddc3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](htt [...]

2022-06-23 00:09 UTC, opbld34 commented
Docs Build status updates of commit _[cab35d7](https://github.com/ajburnle/microsoft-graph-docs/commits/cab35d723572b3602006dcc5fa06475572a96f41)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-5688fa7e)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-5688fa7e)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-5688fa7e)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5688fa7e)
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) | [Details](#user-content-28e735e747132d6f827e5a348d94304b-5688fa7e)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-5688fa7e"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-5688fa7e"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-5688fa7e"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-5688fa7e"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13126, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13172, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="28e735e747132d6f827e5a348d94304b-5688fa7e"></a>
### [api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md)
 - **Line 16, Column 227**: **[Warning: insecure-link - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://myaccess.microsoft.com/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230007307462-17231/BuildReport?accessString=3bc463bb4776c7ccea78d4ab5b1ec05984ca9211ac2099bee1751bdca358a75a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](htt [...]

2022-06-23 00:28 UTC, opbld32 commented
Docs Build status updates of commit _[6b0596b](https://github.com/ajburnle/microsoft-graph-docs/commits/6b0596b72e65032702f804f5294abf9b154b795f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-0542bdec)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-0542bdec)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-0542bdec)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0542bdec)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-0542bdec"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-0542bdec"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-0542bdec"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-0542bdec"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13126, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13172, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230026169380-17231/BuildReport?accessString=45127ab024ce1183c5b64ee1da5d47cdc91f441ece78df80af6b730fb2605534).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86 [...]

2022-07-06 15:54 UTC, opbld31 commented
Docs Build status updates of commit _[7ce519c](https://github.com/ajburnle/microsoft-graph-docs/commits/7ce519c6c2349f773cf5b93091ad24593742d131)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-12988b449a6eeda642ddc254a42ee3eb-24e9255b)
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-7e44a4affbb9ca4036e9280ba8a4197b-24e9255b)
[api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-3d03c0b009127be4168d22de65038c37-24e9255b)
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17231) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-24e9255b)
[api-reference/v1.0/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-1.0&branch=pr-en-us-17231) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="12988b449a6eeda642ddc254a42ee3eb-24e9255b"></a>
### [api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignment.md)
 - **Line 24, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="7e44a4affbb9ca4036e9280ba8a4197b-24e9255b"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 28, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignmentrequest-reprocess.md'.`````

<a id="3d03c0b009127be4168d22de65038c37-24e9255b"></a>
### [api-reference/beta/resources/entitlementmanagement-overview.md](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/resources/entitlementmanagement-overview.md)
 - **Line 77, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackageassignment-reprocess.md'.`````

<a id="0817dce4456c16725d5333633847d38f-24e9255b"></a>
### [api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/elm-reprocess-api1.0/api-reference/beta/toc.yml)
 - **Line 13163, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignment-reprocess.md'.`````
 - **Line 13209, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accesspackageassignmentrequest-reprocess.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207061552248740-17231/BuildReport?accessString=439f53d9772eb2efc815e4c4d1d20bc2f5d9ced51b6207e6cd9eeda3974622da).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86 [...]

2022-07-08 13:22 UTC, FaithOmbongi commented
Hi @ajburnle - This PR has been overtaken by https://github.com/microsoftgraph/microsoft-graph-docs/pull/17585 I believe. Please close it.

2022-07-12 11:27 UTC, FaithOmbongi commented
> This PR has been overtaken by #17585 I believe. Please close it.

Closing this PR.

2022-07-12 11:27 UTC, closed without merging