added get/update team photo from beta to v1
microsoftgraph/microsoft-graph-docs pull request #17241
Opened 2022-06-14 10:45 UTC by sumitgupta3

Promoting Get / Update Team photo from beta to v1.

2022-06-14 10:47 UTC, opbld31 commented
Docs Build status updates of commit _[7fe4096](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fe4096c33326e7c3588a4271733cf51d7a87ffb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-get-photo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) | [Details](#user-content-ba2afdb0e1ec753562ac7331433027cf-2f4df06b)
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-update-photo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) | [Details](#user-content-195b1642c712da04ad51f7ca2ccc4887-2f4df06b)

<a id="ba2afdb0e1ec753562ac7331433027cf-2f4df06b"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-get-photo.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 12, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Get team photo') are not allowed. You can only have one top-level heading.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="195b1642c712da04ad51f7ca2ccc4887-2f4df06b"></a>
### [api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-update-photo.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 12, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Update team photo') are not allowed. You can only have one top-level heading.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206141045377053-17241/BuildReport?accessString=b6759172073472f7de1b89c62fb41de7b36a0d33fff8244c39a270f3701f098d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-26 17:45 UTC, opbld32 commented
Docs Build status updates of commit _[6120b18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6120b18c82376bf374bd5c309c1e9fb5d134a914)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) | [Details](#user-content-ba2afdb0e1ec753562ac7331433027cf-d2a1b5b1)
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) | [Details](#user-content-195b1642c712da04ad51f7ca2ccc4887-d2a1b5b1)

<a id="ba2afdb0e1ec753562ac7331433027cf-d2a1b5b1"></a>
### [api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 12, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Get team photo') are not allowed. You can only have one top-level heading.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="195b1642c712da04ad51f7ca2ccc4887-d2a1b5b1"></a>
### [api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 12, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Update team photo') are not allowed. You can only have one top-level heading.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206261743258110-17241/BuildReport?accessString=a97eae901b4ac6cb5d5c9a5ce6a73810701608e20460e439dc71695924e73d46).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 13:53 UTC, opbld30 commented
Docs Build status updates of commit _[e6b4393](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6b4393279417733a4cd4e8c92c36e6290da85d5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) | [Details](#user-content-195b1642c712da04ad51f7ca2ccc4887-b611a8b2)
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |

<a id="195b1642c712da04ad51f7ca2ccc4887-b611a8b2"></a>
### [api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 12, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Update team photo') are not allowed. You can only have one top-level heading.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206301351063357-17241/BuildReport?accessString=1049c951628d4bdcbc676616c82be53d657e690d485025aa339b8fb084bc2174).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 13:54 UTC, isvargasmsft commented on api-reference/v1.0/api/team-get-photo.md
> +---
Missing in this PR:
1. Resource topic for the new entity profilePhoto. 
2. Update to the team resource topic to include the new navigation property. 
3. Changelog entries for the new navigation property and the new entity. 
4. TOC entry for the new entity type profilePhoto and its methods. 

Please include all the above in this PR.

2022-06-30 13:56 UTC, opbld30 commented
Docs Build status updates of commit _[55f51d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55f51d7e080586e2c9ce4b809417e6640759ffa1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206301352049551-17241/BuildReport?accessString=3a914a58ea8f0d6b8c68bdd886e19bc633f26c6420b67dd53dc18efa0ab19269).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 14:02 UTC, isvargasmsft requested changes
Hello @sumitgupta3, 

Thank you very much for your work in this PR. 

I identified a few elements missing in the PR. Please take a look and add the label "review feedback addressed" once you have included them in the PR. 

Feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac

2022-07-05 07:25 UTC, sumitgupta3 commented on api-reference/v1.0/api/team-get-photo.md
> +---
1. profilePhoto is already there, I have added cases for team's profile photo but for user's profile photo was already there. Let me know if this is fine.
2. Navigation Property updated.
3. changelog added
4. TOC added

2022-07-05 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[ff8d258](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff8d258a84bc3ea745119dcf65224720b0f7473c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f747b301)

<a id="f747b301"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050724448238-17241/BuildReport?accessString=502313949f687ef6571b758988e722d0eae944a0c4b624301c3f9254e5db0753).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 07:37 UTC, opbld33 commented
Docs Build status updates of commit _[fdbe67c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdbe67c2aa486bf5cbc29709076e7d56983a0abc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d764f676)

<a id="d764f676"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050737222145-17241/BuildReport?accessString=fa042ff6949a33cd422e80a82e057976d3e95f4fbcc1f6c86c9b7ed9ae98323f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 07:40 UTC, opbld33 commented
Docs Build status updates of commit _[aa47374](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa4737404af9df6e5b7eebf59aea64ab125eb06b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bc846258)

<a id="bc846258"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050738150822-17241/BuildReport?accessString=433d575097093a4cef80c4d8156c83cb746e4164b442d5d0b3b6805e686636bb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 13:59 UTC, isvargasmsft commented on api-reference/v1.0/api/team-get-photo.md
> +# Get team photo
I noticed we already have Get and Update operations for this resource. In this case, I recommend adding a "team" section to these existing topics:
1. https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0
2. https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http

2022-07-05 14:00 UTC, isvargasmsft commented on api-reference/v1.0/api/team-get-photo.md
> +# Get team photo
In addition, please add both methods to the methods table in the team resource topic.

2022-07-05 14:04 UTC, isvargasmsft requested changes
Hello @sumitgupta3, 

I noticed we already have topics for both methods. In this case, please add the new sections for the team resource, including examples. 

Thanks!

2022-07-05 14:05 UTC, opbld31 commented
Docs Build status updates of commit _[c993b37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c993b371145d55cc1b5615ce8b3831f6992f4bcf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fd1fee27)

<a id="fd1fee27"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051403482711-17241/BuildReport?accessString=82f1c20d15d22182e86eb2f9ffeff1866c91a327611d814836a6e72145eed94a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 05:43 UTC, sumitgupta3 commented on api-reference/v1.0/api/team-get-photo.md
> +# Get team photo
This is get / update user photo that links you have shared. 
operations are performed on profile photo.

But,, I am making changes for Team Get / Update profile photo. 
IMO, We can not add in the links provided by you as they come under Users section. 

These Changes are for Team section. 

Please correct me if there is difference in understanding.

2022-07-12 14:42 UTC, opbld30 commented
Docs Build status updates of commit _[eed80be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eed80be04b53d588b58dc05ddce79a9bd77145a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121440097933-17241/BuildReport?accessString=c5195cf8b5e4d510a6694ca80695d3562079f1e5bd5b9300425abbf5146e3e19).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 19:21 UTC, opbld34 commented
Docs Build status updates of commit _[b123b00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b123b007575e0f73f4f32d5396e8d58a656573a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121918398736-17241/BuildReport?accessString=af9a8223142836304ecd85d94a93fe98ae9f0ff117eaf5b2ceab822849221d2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 19:52 UTC, isvargasmsft commented on api-reference/v1.0/api/team-update-photo.md
> +Binary data for the image
Line 73: Instead of this placeholder, could you please provide a real-looking example of the response? API Doctor will fail if we don't use real-looking info.

2022-07-13 06:02 UTC, opbld33 commented
Docs Build status updates of commit _[85b71b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85b71b953626b971216ed3a14c999cb992ccc898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130600181828-17241/BuildReport?accessString=85fb64c0184dcd2a565740fb4f349e04e58974579b56a771679d99562d969e0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 06:05 UTC, opbld32 commented
Docs Build status updates of commit _[e477873](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e47787347d18b375aa2d918a16aadea1e01bf1c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130601531801-17241/BuildReport?accessString=6800990ff461b8f68f04d9044581e0b37f966de5f16c4bdbd4ccf1b1285288e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 06:07 UTC, opbld32 commented
Docs Build status updates of commit _[174d54e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/174d54eb8b75dc1617b84a6797e6f19b50312aae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130604586190-17241/BuildReport?accessString=1563902b4ce8e1c12df8ff05b29ef241bf9f37cbdadf2707f0d8e74aef5615b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 06:13 UTC, opbld32 commented
Docs Build status updates of commit _[5253312](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5253312a0ef12a18241d9a5508ebc1ef5e43e2d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130610446110-17241/BuildReport?accessString=b229a603a158cc39080a2413558f186514225e5e5ec2f847af89675873e1c12c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 06:32 UTC, opbld32 commented
Docs Build status updates of commit _[08b5ddd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08b5ddd9c07f5a7dd80f1eb19a5355bcc14f1353)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130629488666-17241/BuildReport?accessString=a94b75f42f861a87ec9787c59a286a441b359a780a1c1a693a76be066b6e0ace).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 07:06 UTC, opbld32 commented
Docs Build status updates of commit _[63cb646](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63cb646c33168b257a0a6d96317f323be76f2a4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-f65b1a2e)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-f65b1a2e"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130704280408-17241/BuildReport?accessString=023b3285b4902a6001f3fd0a37cd2f019a80dd1c0077953cfbd68f0637fa1cfc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 07:09 UTC, opbld30 commented
Docs Build status updates of commit _[044375b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/044375be9b5eb4ac7c4998bb65ba6a9c79c30bd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-ea655faa)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-ea655faa)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-ea655faa"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-ea655faa"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130706469611-17241/BuildReport?accessString=328838e683b0f2636e03d0297829e631ee1e17cab5d078d57b3e3f563113255e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 15:45 UTC, isvargasmsft commented on api-reference/beta/api/profilephoto-get.md
> +Contains the binary data of the requested photo. The HTTP response code is 200.
Please use this same format of response in the other examples that would return binary data, both in beta and v1.

2022-07-13 15:54 UTC, opbld30 commented
Docs Build status updates of commit _[75e76bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75e76bb795bed3b863166223b694692507a2ba7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-0f97a713)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-0f97a713)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-0f97a713"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-0f97a713"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131552132455-17241/BuildReport?accessString=0f3cc5239dde07d93a3a69585d5717d8fe7c766746a476c9d7af6b9ae1d6160b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 20:45 UTC, isvargasmsft commented on api-reference/beta/api/profilephoto-get.md
> +### Example 4: Get the photo metadata
Please indicate this example is related to the team resource. 
```suggestion
### Example 4: Get the metadata of the team photo
```

2022-07-14 02:30 UTC, angelgolfer-ms commented on api-reference/beta/api/profilephoto-update.md
> +Update the photo for any user in the tenant, including the signed-in user or the specified group or contact or team. Because there
Line 16:
Please rephrase the first sentence for correct grammar and conciseness:
"Update the photo for the specified contact, group, team, or user in a tenant."

The second sentence should technically say "...the size of the photo you can update to must be under 8MB." Not "... you can add..."

2022-07-14 02:38 UTC, angelgolfer-ms commented on api-reference/beta/api/profilephoto-update.md
> +Update the photo for any user in the tenant, including the signed-in user or the specified group or contact or team. Because there
BTW, looks like profilephoto.md in the beta version is missing a mention about team photo from the release in Feb. Please update that file.

2022-07-14 05:38 UTC, sumitgupta3 commented on api-reference/beta/api/profilephoto-get.md
> +### Example 4: Get the photo metadata
done

2022-07-14 06:12 UTC, opbld33 commented
Docs Build status updates of commit _[2c47c26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c47c26856b94cb26c620b544fa5b8b0720b9b8c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-41c5a8cc)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-41c5a8cc)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-41c5a8cc"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-41c5a8cc"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207140610050269-17241/BuildReport?accessString=ab3c637d7f440d2adc665ba30446601bcc153ca71bd012d9e9ee3a4efc2a7212).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 21:03 UTC, opbld30 commented
Docs Build status updates of commit _[8918a3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8918a3baca047fa6c56a2ddb0bc51b103d51ebca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-f3e61b15)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-f3e61b15)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-f3e61b15"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-f3e61b15"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207142101014212-17241/BuildReport?accessString=e97bca34498186781f722351d2fe1abdec11ca093265a6ed2f6d3be2afc657a1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 21:36 UTC, opbld34 commented
Docs Build status updates of commit _[8c70fe8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c70fe893544105ab2cec4d7b1c8b520735f7e23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-93b27cc3)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-93b27cc3)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-93b27cc3"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-93b27cc3"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207142134039044-17241/BuildReport?accessString=5238b7d7ef5cfb206b71291d2ee048b0ca58b8eb68a6fceefc6fe5076d5e1a2c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 22:02 UTC, opbld32 commented
Docs Build status updates of commit _[8c70fe8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c70fe893544105ab2cec4d7b1c8b520735f7e23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-932c301d)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-932c301d)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-932c301d"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-932c301d"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207142200035094-17241/BuildReport?accessString=06adb4348d70551e3edb52224ecda98231f4027ac1647322af248f4311d25bd0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 22:14 UTC, isvargasmsft approved these changes

2022-07-16 04:01 UTC, Lauragra commented on api-reference/v1.0/api/profilephoto-update.md
> +### To update the profile photo of a team
This heading is out of place; should we delete it or was it intended to go somewhere else in the topic?

2022-07-16 04:01 UTC, Lauragra commented on api-reference/v1.0/api/profilephoto-update.md
> +If successful, this method returns a `204 NoContent` response code for updating a photo for the team.
This should be No Content (missing space).

2022-07-16 04:03 UTC, Lauragra commented on api-reference/v1.0/api/profilephoto-update.md
> +
We have two examples in this topic; please change the H2 to Examples, and then add the H3s: Example 1: <title>, Example 2: <title>.

2022-07-16 04:10 UTC, opbld32 commented
Docs Build status updates of commit _[41b0908](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41b0908529e3563a68b4a8281271abbbf9a8a756)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-0b22377c)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-0b22377c)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-0b22377c"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-0b22377c"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160408401634-17241/BuildReport?accessString=7e18c8d2b3b30414441b58ceb55db4b5b27a39f53b69d88961847c714faac204).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 04:14 UTC, opbld33 commented
Docs Build status updates of commit _[d158c67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d158c674e5b93998cdc000cb1adf374365acf21b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-2093128d)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-2093128d)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-2093128d"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-2093128d"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160411291654-17241/BuildReport?accessString=0a10c69934e42fb14ac612171254db9f500f19db289c49d515054a74d5d337ed).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 04:21 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
I don't think this SubArea applies. For the Shifts API, the value would be "Shifts", but I think this just applies to Teamwork generally, right?

2022-07-16 04:22 UTC, opbld34 commented
Docs Build status updates of commit _[67added](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67added85afdd2ecfd209b52118055bce5a72ec3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-79a294a0)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-79a294a0)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-79a294a0"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-79a294a0"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160419518692-17241/BuildReport?accessString=5cb307dfe1d89461213ebc4b984596d427eb0a9f50a3737a973c568e5d061f37).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 04:40 UTC, opbld32 commented
Docs Build status updates of commit _[65ac775](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65ac7756300689088562585fd1297a998a852400)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-6d1bf5f7)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-6d1bf5f7)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-6d1bf5f7"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-6d1bf5f7"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160438238850-17241/BuildReport?accessString=bef41876cc47d9606d0fd0931c8bcc0c806f3d8c4594477feba7f1e594da1462).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 04:42 UTC, opbld34 commented
Docs Build status updates of commit _[c3c89fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3c89fea2121baeec42c9dd230932b01935c5c91)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-eb816975)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-eb816975)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-eb816975"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-eb816975"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160438555821-17241/BuildReport?accessString=5f606ab802a2b7b50a994a0cbcb6d4cb920b2b4666697dffc0f5738cbf7c00dd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 19:29 UTC, opbld30 commented
Docs Build status updates of commit _[0b4b8f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b4b8f90e0c258565ce6f55778c82e3f067693be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-cfb4e16e)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-cfb4e16e)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-cfb4e16e"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-cfb4e16e"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207181927250103-17241/BuildReport?accessString=640918d7595af478035a0bddc6315eb22c5e6ab7d730c9eac2278beb637efc17).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 19:44 UTC, opbld34 commented
Docs Build status updates of commit _[7bbaec5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bbaec5b128e37573ead27df914197118f32784d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-87c82716)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-87c82716)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-87c82716"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-87c82716"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207181941271467-17241/BuildReport?accessString=6621135156de2683ea0bd3c0747554b237b35be4b405b901d7f78f330291dfdf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 19:46 UTC, opbld30 commented
Docs Build status updates of commit _[5f745bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f745bfccd7ad9709ed4933b7a0a295a3a75e7fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-f9048742)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-f9048742)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-f9048742"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-f9048742"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207181942518039-17241/BuildReport?accessString=c440988852f37bd0e0e3f30f4659dc6e3de16680a833c153ecbd50e6f66d7cbf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 19:52 UTC, opbld30 commented
Docs Build status updates of commit _[df3a4f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df3a4f31b21b8ecea384ba2681a80fed3f34bd33)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-120f02b3)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-120f02b3)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-120f02b3"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-120f02b3"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207181950300304-17241/BuildReport?accessString=53aa9c85a69f249d7e14b28147c8a4269ec0fb6c9a47a29941fed33b4ac9f192).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 20:07 UTC, isvargasmsft approved these changes

2022-07-19 02:07 UTC, opbld32 commented
Docs Build status updates of commit _[793cdaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/793cdaa5dab7707469256f1abf42a868d79a411c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog-archive?branch=pr-en-us-17241) | [Details](#user-content-79a03f6a91f1628c8841e2fa9f27731f-a192071f)
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md) | :bulb:Suggestion | | [Details](#user-content-4711ffc853c78fa0ae6d42c1909da798-a192071f)
[api-reference/beta/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta&branch=pr-en-us-17241) (graph-rest-beta) |
[api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/api/profilephoto-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/profilephoto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/profilephoto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0&branch=pr-en-us-17241) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="79a03f6a91f1628c8841e2fa9f27731f-a192071f"></a>
### [concepts/changelog-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/concepts/changelog-archive.md)
 - **Line 4792, Column 89**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4793, Column 156**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#3-schema-extensions' in 'extensibility-overview.md', did you mean '#schema-extensions'?`````
 - **Line 4800, Column 66**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#4-open-extensions' in 'extensibility-overview.md', did you mean '#open-extensions'?`````

<a id="4711ffc853c78fa0ae6d42c1909da798-a192071f"></a>
### [api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/teamphotov1/api-reference/beta/api/team-get-photo.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/beta/api/team-get-photo.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190204564677-17241/BuildReport?accessString=4f2320aa20e12b26898da3a962cbd3ff6c9000c6697d45c4d47f60c164ecd361).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 02:24 UTC, merged