Add passwordAuthenticationmethod and resetPassword to V1
microsoftgraph/microsoft-graph-docs pull request #17299
Opened 2022-06-17 00:29 UTC by zhvolosh

Adding the following to V1:
- passwordauthenticationmethod resource
- resetpassword
- operation resource
- get operation

Added properties to beta:
- operation resource
- updated passwordauthenticationmethod 'createdDateTime' property to be correct value

2022-06-17 00:31 UTC, opbld31 commented
Docs Build status updates of commit _[8f08355](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f08355345a69f615e83eb8f2b09701396f0f2d5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md) | :x:Error | | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-c4c45a8f)
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :x:Error | | [Details](#user-content-abad0ec8b6569257d30da7b998a35092-c4c45a8f)

<a id="87a0ad202480559d9ae2b0a30f21510d-c4c45a8f"></a>
### [api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md)
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-operation-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-operation-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-operation-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-operation-java-snippets.md'.`````
 - **Line 99, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-operation-go-snippets.md'.`````
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-operation-powershell-snippets.md'.`````

<a id="abad0ec8b6569257d30da7b998a35092-c4c45a8f"></a>
### [api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md)
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md'.`````
 - **Line 109, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md'.`````
 - **Line 113, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md'.`````
 - **Line 165, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md'.`````
 - **Line 169, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md'.`````
 - **Line 173, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md'.`````
 - **Line 177, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206170029167415-17299/BuildReport?accessString=56b80f5c2e6b9306a7f69bc1f4ff61a4e7c10423353021893ae39e0b0973a066).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 19:16 UTC, opbld34 commented
Docs Build status updates of commit _[67e1d25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67e1d2528cecec85d9c6b1cdaf2271d3cdb8a828)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md) | :x:Error | | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-30668bde)
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :x:Error | | [Details](#user-content-abad0ec8b6569257d30da7b998a35092-30668bde)

<a id="87a0ad202480559d9ae2b0a30f21510d-30668bde"></a>
### [api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md)
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-operation-powershell-snippets.md'.`````

<a id="abad0ec8b6569257d30da7b998a35092-30668bde"></a>
### [api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md)
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md'.`````
 - **Line 109, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md'.`````
 - **Line 113, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md'.`````
 - **Line 165, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md'.`````
 - **Line 169, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md'.`````
 - **Line 173, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md'.`````
 - **Line 177, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206171914204711-17299/BuildReport?accessString=2ba0301878f76a5d540fc524de79df03599a4257afbb85f403d22b136ecf61c7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 19:30 UTC, opbld30 commented
Docs Build status updates of commit _[deb183d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/deb183da5265e21516cbe381b4c763bd0336f350)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md) | :x:Error | | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-8af3569a)

<a id="87a0ad202480559d9ae2b0a30f21510d-8af3569a"></a>
### [api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md)
 - **Line 103, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-operation-powershell-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206171927580990-17299/BuildReport?accessString=20a6626512e041e813e6cb495e09e1dc5c3fdd54cedaa86c945332799ba952e8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-17 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[050146b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/050146b00a50cac6f056530d95124fe61034218f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0& [...]

2022-06-20 03:43 UTC, opbld34 commented
Docs Build status updates of commit _[824ebff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/824ebff86572843cc561f10c0960d79ea8d7c878)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0& [...]

2022-06-28 20:27 UTC, FaithOmbongi requested changes
Thank you @zhvolosh for your work in this PR. Some feedback:
- In **authentication.md**, document the two new relationships: **passwordAuthenticationMethod** and **operations**.
- You're missing the LIST and GET methods for passwordAuthentication.
- For long running operations, the correct resource file is longRunningOperation.md, not operation.md. Please undo the changes you've made to operation.md and update the correct file.
- The correct "Get longRunningOperation" file is **longRunningOperation-get.md**; Please undo the changes to the wrong file in this PR.
- You're missing the passwordResetResponse.md file
- Handling code snippets: Please remove all snippets and related lines. By related lines, I mean the following lines:

1. `# [HTTP](#tab/http)`
2. All the code snippets lines up to the closing `---` line
For example: in passwordauthenticationmethod-resetpassword.md, delete lines 155 and 164-180 (as per the time of posting this feedback)
**REASON**: Code snippets are autogenerated and auto-inserted into the files. They will be generated the Tuesday/Wednesday after you merge this PR.

2022-07-06 20:34 UTC, opbld32 commented
Docs Build status updates of commit _[ee7d3e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee7d3e8df83de96f1612d55141b2e94b63ae823e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f5486a88)

<a id="f5486a88"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062033425603-17299/BuildReport?accessString=6a39c8cc17f488a5456ac10bdc0f98670d986bed70355739a815b7fc77fc9b13).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[b60f44b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b60f44bafaf234ed6c5a7c594170591f5a29f9bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authenticationoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-3b435c3f)
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :bulb:Suggestion | | [Details](#user-content-1ff6f537f596d5e9155410aafa7459de-3b435c3f)
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemg [...]

2022-07-06 21:47 UTC, opbld33 commented
Docs Build status updates of commit _[27b622e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27b622e73ea27339c6084afb7a85c38d527f9c79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authenticationoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-5180c909)
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :bulb:Suggestion | | [Details](#user-content-1ff6f537f596d5e9155410aafa7459de-5180c909)
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemg [...]

2022-07-06 21:49 UTC, opbld34 commented
Docs Build status updates of commit _[6115d32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6115d326995bb4f62e63fe1667124ba0bdfd87c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authenticationoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-5ce1b55c)
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :bulb:Suggestion | | [Details](#user-content-1ff6f537f596d5e9155410aafa7459de-5ce1b55c)
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemg [...]

2022-07-06 21:52 UTC, opbld34 commented
Docs Build status updates of commit _[7f9ab81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f9ab819c5af21ce8164f5acb087300ab714ee76)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authenticationoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-87a0ad202480559d9ae2b0a30f21510d-e0ea995d)
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :bulb:Suggestion | | [Details](#user-content-1ff6f537f596d5e9155410aafa7459de-e0ea995d)
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemg [...]

2022-07-07 16:02 UTC, zhvolosh commented on api-reference/v1.0/resources/passwordauthenticationmethod.md
> +|[Reset password](../api/passwordauthenticationmethod-resetpassword.md)|None|Reset a user's password in the cloud and, if synced, on-premises.|
Added.

2022-07-07 16:05 UTC, opbld33 commented
Docs Build status updates of commit _[bf67fb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf67fb2a15c0570eb297f8b6f3f80be7831c4c28)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :x:Error | | [Details](#user-content-e30bd0b8b09625b1503c1990f0dc4ed0-410cb6ec)
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :warning:Warning | | [Details](#user-content-3b6a4cefe5301cbe283eec0977911a87-410cb6ec)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-410cb6ec)

<a id="e30bd0b8b09625b1503c1990f0dc4ed0-410cb6ec"></a>
### [api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-passwordmethods-csharp-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-passwordmethods-javascript-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-passwordmethods-objc-snippets.md'.`````
 - **Line 97, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-passwordmethods-java-snippets.md'.`````
 - **Line 101, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-passwordmethods-go-snippets.md'.`````
 - **Line 105, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-passwordmethods-powershell-snippets.md'.`````

<a id="3b6a4cefe5301cbe283eec0977911a87-410cb6ec"></a>
### [api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md)
 - **Line 15, Column 49**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/operation.md'.`````
 - **Line 65, Column 79**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/operation.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-410cb6ec"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml)
 - **Line 5090, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/authenticationoperation-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207071602117977-17299/BuildReport?accessString=4c29811fd13eb61b226f7546a49569f4c2986261d625b796ff1298b600c64885).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 16:24 UTC, opbld30 commented
Docs Build status updates of commit _[d18bb52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d18bb52de4ffe78477c5506535f89bfdc971ffc5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bcc10e7d)

<a id="bcc10e7d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207071623243169-17299/BuildReport?accessString=8a0135119bc8e538cfdec984b0109a1620da38aad8f6283d87e6960832215155).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-07 16:49 UTC, zhvolosh commented
@FaithOmbongi, quick question on one piece of the feedback - for removing code snippets - does that also include removing links as well? i.e. this error: Line 105, Column 1: [Error: include-not-found] Invalid include link: '../includes/snippets/powershell/get-passwordmethods-powershell-snippets.md'.

2022-07-08 09:08 UTC, FaithOmbongi commented
> @FaithOmbongi, quick question on one piece of the feedback - for removing code snippets - does that also include removing links as well? i.e. this error: Line 105, Column 1: [Error: include-not-found] Invalid include link: '../includes/snippets/powershell/get-passwordmethods-powershell-snippets.md'.

Hi @zhvolosh - Correct. Everything snippets-related that you copied from the beta docs should be resolved.
1. This line: `# [HTTP](#tab/http)`
2. All lines similar to these 👇🏾
```
# [C#](#tab/csharp)
[!INCLUDE [sample-code](../includes/snippets/csharp/get-passwordmethods-csharp-snippets.md)]
[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]

# [JavaScript](#tab/javascript)
[!INCLUDE [sample-code](../includes/snippets/javascript/get-passwordmethods-javascript-snippets.md)]
[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]

# [Objective-C](#tab/objc)
[!INCLUDE [sample-code](../includes/snippets/objc/get-passwordmethods-objc-snippets.md)]
[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]

# [Java](#tab/java)
[!INCLUDE [sample-code](../includes/snippets/java/get-passwordmethods-java-snippets.md)]
[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]

# [Go](#tab/go)
[!INCLUDE [sample-code](../includes/snippets/go/get-passwordmethods-go-snippets.md)]
[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]

# [PowerShell](#tab/powershell)
[!INCLUDE [sample-code](../includes/snippets/powershell/get-passwordmethods-powershell-snippets.md)]
[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]

---
````

2022-07-11 16:26 UTC, opbld32 commented
Docs Build status updates of commit _[008664a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/008664a0672500731b750e4251d04681919271a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fb320f30)

<a id="fb320f30"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111626141410-17299/BuildReport?accessString=a3856ef07f8ea6892a02b05087a36984f6fee470a7ad45fc1b009eb53b384467).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:30 UTC, opbld34 commented
Docs Build status updates of commit _[7e9bcaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e9bcaf7d3c8e33327ee1c9379da75bead0066ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8788c866)

<a id="8788c866"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111630104003-17299/BuildReport?accessString=4b65d88660b34aacb41052059b83ed865830aa1031c7d0843ab5e114e64fc820).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 16:37 UTC, opbld33 commented
Docs Build status updates of commit _[33354d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33354d4507c0d623067ba4b774e50ae51bebe1c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-3b6a4cefe5301cbe283eec0977911a87-6fc005f2)
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :bulb:Suggestion | | [Details](#user-content-1ff6f537f596d5e9155410aafa7459de-6fc005f2)
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/get-operation-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-adminprovided-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/go/get-operation-go-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/get-operation-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-adminprovided-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/get-operation-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/get-operation-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/powershell/get-operation-powershell-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/powershell/get-operation-powershell-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation [...]

2022-07-11 16:46 UTC, zhvolosh commented on changelog/Microsoft.DirectoryServices.json
> +        {
Changed to reflect longrunningoperation.md instead of operation.

2022-07-11 16:49 UTC, opbld33 commented
Docs Build status updates of commit _[2197879](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2197879637c16a3006be4e8dcc39d51f8c454452)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :bulb:Suggestion | | [Details](#user-content-1ff6f537f596d5e9155410aafa7459de-413f3a8f)
[api-reference/beta/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/operation?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/csharp/passwordauthenticationmethod-resetpassword-systemgenerated-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/java/passwordauthenticationmethod-resetpassword-systemgenerated-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-adminprovided-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/javascript/passwordauthenticationmethod-resetpassword-systemgenerated-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-adminprovided-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/includes/snippets/objc/passwordauthenticationmethod-resetpassword-systemgenerated-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ff6f537f596d5e9155410aafa7459de-413f3a8f"></a>
### [api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md)
 - **[Suggestion: file-not-redirected - [See documentation](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/file-not-redirected?branch=main)]** `````File api-reference/v1.0/resources/operation.md was deleted without redirection. To avoid broken links, add a redirection.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207111646385022-17299/BuildReport?accessString=7f3d2a720ebc8efcd4ec6d70eb073ed29bc04ba98e73de7613fb8d6464087112).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https:/ [...]

2022-07-11 16:51 UTC, zhvolosh commented
@FaithOmbongi I have addressed the changes. Will you take a look to re-review? Upon deleting the v1 operation.md file I get the above suggestion by the automatic checks - not sure best way to address.

2022-07-12 11:25 UTC, FaithOmbongi commented
Added to my re-review queue.

2022-07-15 06:27 UTC, opbld32 commented
Docs Build status updates of commit _[9ed5f7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ed5f7f95312b7daa23956af67fdab088ef3e79c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ab21aae2)

<a id="ab21aae2"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207150626466649-17299/BuildReport?accessString=3fdbeb3a44d39a052e53e562c1647fcfc34a7683242a4d41ad9cdd901bb9a147).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 06:53 UTC, FaithOmbongi requested changes
Hi @zhvolosh - I've proposed changes, mostly bumping changes that were pending from the previous review.

I'm not very sure about the schema changes related to you passwordauthenticationmethod-resetpassword so I've sought for more guidance. I will propose additional changes to the file depending on the feedback I'll get.

I've done a few quick fixes
- I've pushed a commit to delete the snippet files
- I've reset your changelog "changelog/Microsoft.DirectoryServices.json" and added a fresh changelog from the stubs. This should resolve the merge conflict
- I've reset the operation.md doc because it shouldn't be part of your changes - It's part of the OneNote workload

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/passwordauthenticationmethod-get.md
> +description: "Retrieve the properties and relationships of passwordauthenticationmethod object."
```suggestion
description: "Retrieve a user's passwordAuthenticationMethod object."
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/passwordauthenticationmethod-get.md
> +Retrieve the properties and relationships of a [password authentication method](../resources/passwordauthenticationmethod.md) object.
Same logic as the List doc suggestion
```suggestion
Retrieve a password that's registered to a user, represented by a [passwordAuthenticationMethod](../resources/passwordauthenticationmethod.md) object. For security, the password itself will never be returned in the object and the **password** property is always `null`.
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/passwordauthenticationmethod-get.md
> +* Authentication administrator (only sees masked phone numbers)
Same logic as the List doc
```suggestion
* Global Administrator
* Global Reader
* Privileged Authentication Administrator
* Authentication Administrator
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md
> +---
If we follow what's currently defined in the schema, this file should be named _authenticationmethod-resetpassword.md_;

However, I'm not very sure about whether the binding parameter for the action should really be **authenticationMethod**; so I've sought guidance from the area experts.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/14026935/179163422-0362190b-48d9-4438-a750-d1ed7766e83e.png">

I'll provide additional suggestions for this doc (mostly titles and file name) depending on the feedback I get.

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md
> +# [Java](#tab/java)
Snippets remnants to be removed as per the guidance
```suggestion
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/longrunningoperation.md
> +title: "long-running operation resource type"
```suggestion
title: "longRunningOperation resource type"
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/longrunningoperation.md
> +# Long running operation resource type
```suggestion
# longRunningOperation resource type
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/longrunningoperation.md
> +|statusDetail|String|Details on the status of the operation.|
```suggestion
|createdDateTime|DateTimeOffset|The start time of the operation.|
|id|String|The unique identifier of the operation |
|lastActionDateTime|DateTimeOffset|The time of the last action in the operation.|
|resourceLocation|String| URI of the resource that the operation is performed on. |
|status|longRunningOperationStatus|The status of the operation. The possible values are: `notStarted`, `running`, `succeeded`, `failed`, `unknownFutureValue`.|
|statusDetail|String|Details about the status of the operation.|
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/resources/longrunningoperation.md
> +  "id": "2d497bb-57bd-47a6-8749-5ccd0869f2bd",
Fix
```suggestion
<!-- {
  "blockType": "resource",
  "keyProperty": "id",
  "@odata.type": "microsoft.graph.longRunningOperation",
  "baseType": "microsoft.graph.entity",
  "openType": false
}
-->
``` json
{
  "@odata.type": "#microsoft.graph.longRunningOperation",
  "id": "String (identifier)",
  "createdDateTime": "String (timestamp)",
  "lastActionDateTime": "String (timestamp)",
  "resourceLocation": "String",
  "status": "String",
  "statusDetail": "String"
}
```
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/longrunningoperation-get.md
> +title: "Get authentication operation"
```suggestion
title: "Get longRunningOperation"
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/longrunningoperation-get.md
> +description: "Retrieve the properties and relationships of an operation object."
```suggestion
description: "Retrieve the status of a long-running operation."
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/longrunningoperation-get.md
> +# Get authentication operation
```suggestion
# Get longRunningOperation
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/longrunningoperation-get.md
> +`Succeeded` and `Failed` are terminal states.
Proposed a few tweaks because this is a shared resource type
```suggestion
Retrieve the status of a long-running operation, represented by a [longRunningOperation](../resources/longrunningoperation.md) object. A long-running operation is initiated when you [reset a user's password](passwordauthenticationmethod-resetpassword.md). This resource type is also the base type for the richLongRunningOperation object that represents the status of a long-running operation on a [site](../resources/site.md) or a [list](../resources/list.md).

The possible states of the long-running operation are `notStarted`, `running`, `succeeded`, `failed`, `unknownFutureValue` where `succeeded` and `failed` are terminal states.
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/longrunningoperation-get.md
> +* Authentication administrator
```suggestion
* Global Administrator
* Global Reader
* Privileged Authentication Administrator
* Authentication Administrator
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/api/longrunningoperation-get.md
> +If successful, this method returns a `200 OK` response code and the requested [operation](../resources/longrunningoperation.md) object in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and the requested [longRunningOperation](../resources/longrunningoperation.md) object in the response body.
```

2022-07-15 06:53 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +            - name: Reset
Surface the List and Get files in the TOC
```suggestion
            - name: List
              href: api/authentication-list-passwordmethods.md
            - name: Get
              href: api/passwordauthenticationmethod-get.md
            - name: Reset
```

2022-07-15 06:56 UTC, opbld32 commented
Docs Build status updates of commit _[24dff81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24dff81998ca796eb17e958b8960dc45686e0068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207150654167174-17299/BuildReport?accessString=28c953fee260456e760de929aac5dfcdb7520b462c0c19dfd32ae2568e04ec84).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 07:48 UTC, FaithOmbongi commented
Hi @zhvolosh - I understand that engineering will have to make some schema changes for the resetPassword action. Since that's going to be made first in beta to assess impact before being rolled out in v1.0, it may take a while.

I recommend that you address all the pending feedback in this PR so we'll be left with only the resetPassword documentation - which we'll get back to after the schema changes are rolled out in v1.0. I'll handle the fixes required for the beta docs at that time as well. Thanks.

2022-08-04 08:14 UTC, FaithOmbongi requested changes
Hi @zhvolosh - I've added two comments related to the passwordMethods doc. This is based on the conclusion of the email thread about the schema.

2022-08-04 08:14 UTC, FaithOmbongi commented on api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md
> +# passwordAuthenticationMethod: resetPassword
```suggestion
# authenticationMethod: resetPassword
```

2022-08-11 17:02 UTC, zhvolosh commented
@FaithOmbongi fixing conflicts and open issues today. Thanks!

2022-08-11 17:06 UTC, opbld31 commented
Docs Build status updates of commit _[c44ff33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c44ff33d5f73e0529367f1c4d1efa0ab627d40ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208111703475519-17299/BuildReport?accessString=e3ee9407b9958e440a1bf661ce845a073fa78a1401f1499e842b877f15de67b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 17:08 UTC, opbld30 commented
Docs Build status updates of commit _[700aa2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/700aa2df9f54fdaa7922169f5f0e4e3da65bb99c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208111706011556-17299/BuildReport?accessString=44619cad3136fbd2d1fcf3527551fdcfd4d7ff22ec3ffc939b3174c3a9c79a36).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 17:10 UTC, opbld34 commented
Docs Build status updates of commit _[affd280](https://github.com/microsoftgraph/microsoft-graph-docs/commits/affd280eef8eaf736ffc3f2b6a1557969582245a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208111706351376-17299/BuildReport?accessString=228bef9f654bd8bf732e2f4b00b7b358d459a0b9959a824ad3aef40cac04d54d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 17:35 UTC, zhvolosh commented on api-reference/v1.0/resources/authentication.md
> +|operation|[operation](../resources/longrunningoperation.md) collection|Represents the status of a long-running operation.|
I updated with alphabetical separate from the suggestion since it didn't let me commit the suggestion and have the long running operation and password authentication method changed.

2022-08-11 17:36 UTC, opbld34 commented
Docs Build status updates of commit _[e24b426](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e24b4269f771cfe59f3cd747598eb474aefa0ac9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208111735003396-17299/BuildReport?accessString=ab108cf2b81c5d61cffdf9881e7134498d6cff03a01b248b2d7ecec7903cda8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 20:26 UTC, zhvolosh commented
@FaithOmbongi - I have fixed the suggestions asked. I am unsure why the apidoctor check is failing - do you have any insight?

2022-08-12 10:38 UTC, FaithOmbongi commented
> @FaithOmbongi - I have fixed the suggestions asked. I am unsure why the apidoctor check is failing - do you have any insight?

@zhvolosh - It's failing because you're missing the longrunningoperation.md file. Please add this file and document the resource. Also, I see you still have quite a number of unresolved comments. Please use the [files changed view](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17299/files) to see all pending comments.

2022-08-12 16:22 UTC, opbld33 commented
Docs Build status updates of commit _[132812a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/132812a8be8eea20b43ffcf6efc78bbfe9f72dd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/operation.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121620062815-17299/BuildReport?accessString=d96d4b958f77e8af3ee251fddba0bd4c84620cb9821b1b386cea5a2cd68622d3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 16:32 UTC, zhvolosh commented
@FaithOmbongi my mistake, I had thought I resolved the files changed view. Should be committed now. As for the longrunningoperation.md, is this not the correct one? https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md

2022-08-12 17:50 UTC, opbld33 commented
Docs Build status updates of commit _[0cecf31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0cecf310c0f031321ca988612864af68c697b05d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/api/authenticationoperation-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) | [Details](#user-content-7f4767e4458b9f0fcf911f43fff93fc4-0c3a81ac)
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-83f6516704f1ff580a306b01d7057cc6-0c3a81ac)
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/passwordresetresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordresetresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordresetresponse?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |

<a id="7f4767e4458b9f0fcf911f43fff93fc4-0c3a81ac"></a>
### [api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/api/authenticationoperation-get.md)
 - **Line 16, Column 178**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'authenticationmethod-resetpassword.md'.`````

<a id="83f6516704f1ff580a306b01d7057cc6-0c3a81ac"></a>
### [api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'The status of a long-running operation.' is duplicated in 'v1.0/resources/longrunningoperation.md(3,14)', 'v1.0/resources/operation.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121748359736-17299/BuildReport?accessString=f78f4a91d66d77ad0b8a280963cd75f3f51c3a1e306a427db9ff7a172d9d1377).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 18:00 UTC, opbld33 commented
Docs Build status updates of commit _[ece199e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ece199ea8acce3d49640eece6e2f4e432982af0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/longrunningoperation?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) | [Details](#user-content-83f6516704f1ff580a306b01d7057cc6-4a05b68c)
[api-reference/beta/api/authenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/api/authenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/api/authenticationoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/api/authenticationoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationoperation-get?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-beta&branch=pr-en-us-17299) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-passwordmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authentication-list-passwordmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/authenticationmethod-resetpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/longrunningoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/longrunningoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/longrunningoperation-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/api/passwordauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/api/passwordauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/passwordresetresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/passwordresetresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordresetresponse?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-passwordmethods?view=graph-rest-1.0&branch=pr-en-us-17299) (>= graph-rest-1.0) |
[changelog/Microsoft.StrongAuthenticationAPI.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/changelog/Microsoft.StrongAuthenticationAPI.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.0522.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/redirects/.openpublishing.redirection.0522.json) | :white_check_mark:Succeeded | |

<a id="83f6516704f1ff580a306b01d7057cc6-4a05b68c"></a>
### [api-reference/v1.0/resources/longrunningoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhvolosh-resetpassword/api-reference/v1.0/resources/longrunningoperation.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'The status of a long-running operation.' is duplicated in 'v1.0/resources/longrunningoperation.md(3,14)', 'v1.0/resources/operation.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121758314168-17299/BuildReport?accessString=fd77c384e1901ad2885050ea383572846aab95323f0efd386c7278251e498459).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 18:06 UTC, FaithOmbongi approved these changes
Hi @zhvolosh - I've pushed a few commits to clean up some pending review feedback and approved the PR.

When you're ready to publish these docs, replace the **do not merge** label with the **ready to merge**.

2022-08-13 02:09 UTC, merged