Bizhao/supported region update
microsoftgraph/microsoft-graph-docs pull request #17301
Opened 2022-06-17 03:06 UTC by Meadow201317

Add CloudPC supported region status

2022-06-17 03:10 UTC, opbld31 commented
Docs Build status updates of commit _[85a15f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85a15f0a3b9622b6d8692e212cfc522d150fb56c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsupportedregion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) | [Details](#user-content-374ec5137a77d8312f16138d57ff780b-e0b26417)

<a id="374ec5137a77d8312f16138d57ff780b-e0b26417"></a>
### [api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/cloudpcsupportedregion.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'RuiHou105, Meadow201317' is not a valid GitHub ID.`````
 - **Line 30, Column 15**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudpcsupportedRegionstatus-values' in 'beta/resources/cloudpcsupportedregion.md', did you mean '#cloudpcsupportedregionstatus-values'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206170307006091-17301/BuildReport?accessString=06a7efabad7732d63f4d033f2ebfa3be1c427e28e2388e113522c3b16c1a1406).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 06:49 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionStatus|[cloudPcSupportedRegionStatus](#cloudpcsupportedRegionstatus-values)|The status of the supported region. Read-only.|
Please use lower case: `#cloudpcsupportedregionstatus-values`. Otherwise the build will fail.

2022-06-20 07:00 UTC, RuiHou105 requested changes
@Meadow201317 
1. Please update the `CloudManagedDesktop changelog`. You can find the needed content in your previous graph schema PR
![image](https://user-images.githubusercontent.com/77313233/174542496-727a26e6-0a8c-40a7-aade-3fce0064ac90.png)

2.Please update the response of list supported regions API in the `list-supportedregions... `file as you added a new property regionStatus.

3.Please resolve other comments in this PR. Thanks!

4.Please create a roadmap workitem and then attach the workitem number in this PR. Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/12472/ 

If you don't have access, please do this firstly to gain access:
- Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
- Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-06-21 02:18 UTC, Lauragra commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +author: "RuiHou105, Meadow201317"
Please just use one value here.

2022-06-21 03:29 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|regionStatus|[cloudPcSupportedRegionStatus](#cloudpcsupportedRegionstatus-values)|The status of the supported region. Read-only.|
Changed, thx!

2022-06-21 03:33 UTC, opbld31 commented
Docs Build status updates of commit _[beae102](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beae1021024482b966d2e8e14d51fcaf93c5ca75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206210330269672-17301/BuildReport?accessString=c0c4fa771447246e9352d6ba7fca932e2fa4217b47080a56c60a572860fe4545).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 03:36 UTC, opbld33 commented
Docs Build status updates of commit _[46abc36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46abc3634790828f37c8753c7d194de90bc90997)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206210330428017-17301/BuildReport?accessString=eb1683c6fdee631db05b579783aedd2b6cff23030e3846b2fa4a0e6b968267b9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 03:39 UTC, opbld33 commented
Docs Build status updates of commit _[beae102](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beae1021024482b966d2e8e14d51fcaf93c5ca75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206210330372727-17301/BuildReport?accessString=672da94b5aa69cdac7f64496f3bf49cf36bff75ab5e29862e8499ae41a25baed).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 03:26 UTC, Meadow201317 commented
Linked work item: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/

2022-06-22 09:59 UTC, opbld33 commented
Docs Build status updates of commit _[1107ca8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1107ca8737220423d8e95ab485646ff652597f0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220956134690-17301/BuildReport?accessString=807d8e8542656b780364af84520b842a627faf71b62df62c9da349ddd739cb3a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-27 02:38 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ChangeList": [
Hi @Meadow201317 , the changelog should include these two. Please follow them to correct here.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/77313233/175849584-67e91e0f-5b72-4e69-9d9e-3f5814b60e1c.png">

![image](https://user-images.githubusercontent.com/77313233/175849655-e7b84e08-d955-4821-b62c-9c069fad7568.png)

2022-06-30 05:52 UTC, opbld33 commented
Docs Build status updates of commit _[3806f43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3806f43a90b46adccf482e7e49f7dfa31b72ec19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206300549311514-17301/BuildReport?accessString=8c86c3cb9d137abcc112ec881eed4dd14aa3fa13c6d50341522a55476b8413bb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:55 UTC, RuiHou105 approved these changes

2022-06-30 07:56 UTC, RuiHou105 commented
Hi @Lauragra  @JarbasHorst  please help review this PR when you got time. Thanks!

2022-07-18 01:12 UTC, Meadow201317 commented
@MSFT-Jarbas Could you please review this PR? Thx!

2022-07-18 01:13 UTC, opbld33 commented
Docs Build status updates of commit _[82c8167](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82c8167538f5e188ed582390b19fbb9b47ce3795)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207180111188588-17301/BuildReport?accessString=f2a44508cda05a11176a70d4d20f0eefdaf1882e75c635404b88a83a546588fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 22:10 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [17720](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17720) into this branch to include my final edits.

2022-07-18 23:50 UTC, opbld30 commented
Docs Build status updates of commit _[e2e208a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2e208a3fddf4c284453ac07b2869c747f2dea0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207182347493046-17301/BuildReport?accessString=bbc152770313268c8bad209e368c79a4682fc4b608c697c69409b9bbffa54fda).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 04:42 UTC, Lauragra approved these changes

2022-07-20 22:07 UTC, opbld30 commented
Docs Build status updates of commit _[23754dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23754ddc304aaa3bb067497ee78b351dc0426535)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17301) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/supportedRegion_update/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207202205441335-17301/BuildReport?accessString=f43ef76559424ff865945971ba07097fdb219702a20f5e6088ceddb569c47644).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 22:31 UTC, merged