Mail api doc updates
microsoftgraph/microsoft-graph-docs pull request #17356
Opened 2022-06-20 08:22 UTC by abheek-das

1. Added filtering based on _changeType_ for /delta query on message resource.
2. Added missing details on _Prefer: outlook.timezone_ for createReply, reply, replyAll docs pages.
3. Added new concept page (concepts/outlook-things-to-know-about-send-mail.md) on actual steps involved in the backend before a mail is delivered to recipients.
4. Clarified that the _contentType_ of the attachment is optional and will be returned as null by default, when not set explicitly for _referenceAttachment_ and _itemAttachment_ resource types.
5. ~~Added a known issue with `$top` and the _/messages_ endpoint.~~

2022-06-20 08:24 UTC, opbld32 commented
Docs Build status updates of commit _[a5843ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5843ee094572b112f7037d78a8845a9fe838399)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-512483e8)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-512483e8)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-512483e8)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-512483e8)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-512483e8)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-512483e8)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-512483e8)

<a id="1792f64edf5350e52c87cb976a92cbda-512483e8"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 53, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````

<a id="dd929f79ef0957b4da9af765f60492ac-512483e8"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 55, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 55, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-512483e8"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````

<a id="244b59926eeb584c109a4d4138c4810e-512483e8"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/ [...]

2022-06-20 11:07 UTC, opbld32 commented
Docs Build status updates of commit _[1437637](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14376372365f54c2506f525c3ca12757872f36f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-fc0a7f0a)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-fc0a7f0a)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-fc0a7f0a)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-fc0a7f0a)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-fc0a7f0a)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-fc0a7f0a)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-fc0a7f0a)

<a id="1792f64edf5350e52c87cb976a92cbda-fc0a7f0a"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="dd929f79ef0957b4da9af765f60492ac-fc0a7f0a"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 55, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 55, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-fc0a7f0a"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````

<a id="244b59926eeb584c109a4d4138c4810e-fc0a7f0a"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 54, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 54, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph [...]

2022-06-20 11:10 UTC, opbld30 commented
Docs Build status updates of commit _[89ec8da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89ec8da177460b7dcced1f80e27e52026603cb17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-ba426c1f)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-ba426c1f)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-ba426c1f)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-ba426c1f)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-ba426c1f)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-ba426c1f)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-ba426c1f)

<a id="1792f64edf5350e52c87cb976a92cbda-ba426c1f"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="dd929f79ef0957b4da9af765f60492ac-ba426c1f"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-ba426c1f"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````

<a id="244b59926eeb584c109a4d4138c4810e-ba426c1f"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 54, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 54, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-ba426c1f"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line [...]

2022-06-20 11:12 UTC, opbld34 commented
Docs Build status updates of commit _[bb44df4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb44df4f78eef1ac11009d659e1db2056913d2e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-a929613a)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-a929613a)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-a929613a)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-a929613a)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-a929613a)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-a929613a)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-a929613a)

<a id="1792f64edf5350e52c87cb976a92cbda-a929613a"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="dd929f79ef0957b4da9af765f60492ac-a929613a"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-a929613a"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="244b59926eeb584c109a4d4138c4810e-a929613a"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 54, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 54, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-a929613a"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 50, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http. Otherwise, remove the view parameter.`````

<a id="c84a42636feb979c4caf40128482d4ed-a929613a"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' contains locale code 'en-us'. For localizabi [...]

2022-06-20 11:14 UTC, opbld30 commented
Docs Build status updates of commit _[31b742c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31b742c7f60ba3c9bc60b97e2777e8f46c774310)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-95bcd64f)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-95bcd64f)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-95bcd64f)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-95bcd64f)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-95bcd64f)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-95bcd64f)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-95bcd64f)

<a id="1792f64edf5350e52c87cb976a92cbda-95bcd64f"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="dd929f79ef0957b4da9af765f60492ac-95bcd64f"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-95bcd64f"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="244b59926eeb584c109a4d4138c4810e-95bcd64f"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-95bcd64f"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 50, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http. Otherwise, remove the view parameter.`````

<a id="c84a42636feb979c4caf40128482d4ed-95bcd64f"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 50, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http. Otherwise, remove the view parameter.`````

<a id="d6c249516094b2593b528b2399d648af-95bcd64f"></a>
### [concepts/outlook-things-to-know-a [...]

2022-06-20 11:16 UTC, opbld30 commented
Docs Build status updates of commit _[52a8759](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52a875971237011bd29229a2ab803270ce6e40d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-16bd7ce8)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-16bd7ce8)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-16bd7ce8)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-16bd7ce8)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-16bd7ce8)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-16bd7ce8)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |

<a id="dd929f79ef0957b4da9af765f60492ac-16bd7ce8"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-16bd7ce8"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="244b59926eeb584c109a4d4138c4810e-16bd7ce8"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-16bd7ce8"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="c84a42636feb979c4caf40128482d4ed-16bd7ce8"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="d6c249516094b2593b528b2399d648af-16bd7ce8"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you r [...]

2022-06-20 11:19 UTC, opbld33 commented
Docs Build status updates of commit _[70f98f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70f98f28327d524bc63b4399d2ec384dbef37b8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-f4d8a9e0)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-f4d8a9e0)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-f4d8a9e0)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-f4d8a9e0)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-f4d8a9e0)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |

<a id="801ba5298ddad3bdf72581ebf3dde762-f4d8a9e0"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="244b59926eeb584c109a4d4138c4810e-f4d8a9e0"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-f4d8a9e0"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="c84a42636feb979c4caf40128482d4ed-f4d8a9e0"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="d6c249516094b2593b528b2399d648af-f4d8a9e0"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201111149860-17356/BuildReport?accessString=339e6fb3731d26fb342bd85ae90009bbce [...]

2022-06-20 11:21 UTC, opbld31 commented
Docs Build status updates of commit _[b67301b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b67301b68f91bd914d649d783f83ee444a7bdc46)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-c5bef91c)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-c5bef91c)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-c5bef91c)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-c5bef91c)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |

<a id="244b59926eeb584c109a4d4138c4810e-c5bef91c"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-c5bef91c"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="c84a42636feb979c4caf40128482d4ed-c5bef91c"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="d6c249516094b2593b528b2399d648af-c5bef91c"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201111272861-17356/BuildReport?accessString=e475a7b381122143bbd5efb8e3dde2029c75115e026ac3c2a36162d405d6af01).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken [...]

2022-06-20 11:24 UTC, opbld30 commented
Docs Build status updates of commit _[d66f453](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d66f4530a9b4acd0c4f7592488d267fa486ead08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-cfe5e081)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-cfe5e081)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |

<a id="c84a42636feb979c4caf40128482d4ed-cfe5e081"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="d6c249516094b2593b528b2399d648af-cfe5e081"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201111498091-17356/BuildReport?accessString=65ee57f745c9e72aba59e36e96e86012a70b3677ba618f33ead388148ab642eb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 11:26 UTC, opbld30 commented
Docs Build status updates of commit _[168d5af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/168d5af8a73daf033daca762aaee22199a3f9da0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-97d6d370)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-97d6d370)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-97d6d370)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-97d6d370)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-97d6d370)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-97d6d370)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-97d6d370)

<a id="1792f64edf5350e52c87cb976a92cbda-97d6d370"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="dd929f79ef0957b4da9af765f60492ac-97d6d370"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-97d6d370"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="244b59926eeb584c109a4d4138c4810e-97d6d370"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-97d6d370"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="c84a42636feb979c4caf40128482d4ed-97d6d370"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 160**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 50, Column 160**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-v1.0&tabs=http. Otherwise, remove the view parameter.`````

<a id="d6c249516094b2593b528b2399d648af-97d6d370"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com [...]

2022-06-20 11:29 UTC, opbld30 commented
Docs Build status updates of commit _[5fca09d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fca09d6a7d89ba23bc9eae41e649644b46653fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-a9483471)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |

<a id="d6c249516094b2593b528b2399d648af-a9483471"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201111589368-17356/BuildReport?accessString=4ec00ab228646133262d5fcaa2dc03505d5cf5fcef62d5dfb0f192c88af1b646).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 11:35 UTC, opbld31 commented
Docs Build status updates of commit _[6798e1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6798e1dd6b5f80069d0ca53aa6b31721fb2f6c4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-1792f64edf5350e52c87cb976a92cbda-3ddb88ea)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-dd929f79ef0957b4da9af765f60492ac-3ddb88ea)
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) | [Details](#user-content-801ba5298ddad3bdf72581ebf3dde762-3ddb88ea)
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-244b59926eeb584c109a4d4138c4810e-3ddb88ea)
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-3ddb88ea)
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) | [Details](#user-content-c84a42636feb979c4caf40128482d4ed-3ddb88ea)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-3ddb88ea)

<a id="1792f64edf5350e52c87cb976a92cbda-3ddb88ea"></a>
### [api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md)
 - **Line 53, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="dd929f79ef0957b4da9af765f60492ac-3ddb88ea"></a>
### [api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md)
 - **Line 55, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="801ba5298ddad3bdf72581ebf3dde762-3ddb88ea"></a>
### [api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md)
 - **Line 52, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="244b59926eeb584c109a4d4138c4810e-3ddb88ea"></a>
### [api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md)
 - **Line 54, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="298103b5e4b06704ec34e9e939ac2ed0-3ddb88ea"></a>
### [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="c84a42636feb979c4caf40128482d4ed-3ddb88ea"></a>
### [api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md)
 - **Line 50, Column 160**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/outlookuser-supportedtimezones'.`````

<a id="d6c249516094b2593b528b2399d648af-3ddb88ea"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non [...]

2022-06-20 11:38 UTC, opbld32 commented
Docs Build status updates of commit _[2472673](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2472673257ec5c7e47c2fb9144958d7f9bcb1dd8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-6056d38e)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |

<a id="d6c249516094b2593b528b2399d648af-6056d38e"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201131056682-17356/BuildReport?accessString=2f7c9468f1c4a7d9d0b98f5c7bc392c982dcc1d0cf5bad8f6d70e6af78983be8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-erro [...]

2022-06-20 11:43 UTC, opbld30 commented
Docs Build status updates of commit _[21a01ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21a01ff293faadd431fcfd2ac80430fae28ff539)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-9086f88d)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |

<a id="d6c249516094b2593b528b2399d648af-9086f88d"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201129536342-17356/BuildReport?accessString=0889f9215d7acbc2fb985bff89c5f8f093a3b7246ca5dfa05be17a6bf78928c3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 11:46 UTC, opbld33 commented
Docs Build status updates of commit _[74697ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74697ea21496f02f5206624531ff86c6c6205862)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-06b69e8e)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |

<a id="d6c249516094b2593b528b2399d648af-06b69e8e"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201131272192-17356/BuildReport?accessString=509b9a3f3cdc1d9e118dea06b555112ffea27e0518e1d75acb188783bfbc1776).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or [...]

2022-06-20 12:29 UTC, opbld32 commented
Docs Build status updates of commit _[af89058](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af89058536e04f92d8724dfb9d077a2e56984344)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-ad84d756)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-ad84d756"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201225560191-17356/BuildReport?accessString=557b642ecb9bca5893ef20367e51de1f7366cffd228b2fed799b4ff5a3b11ef4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written  [...]

2022-06-20 12:47 UTC, opbld30 commented
Docs Build status updates of commit _[81cfd4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81cfd4d3dfa00763373eb908dff7d15dc87fb175)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-b01b1c84)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-b01b1c84"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206201245338730-17356/BuildReport?accessString=6c51f740d4dd29674d20730cd35a0e599f6ff4a1b759379b971b66d14ce6fd1b).

If you see build warnings/err [...]

2022-06-20 13:04 UTC, opbld30 commented
Docs Build status updates of commit _[5808675](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5808675901cd9fcca0c6f39335d1774aecd3b6d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-3814ff21)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-3814ff21"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to [...]

2022-06-20 13:14 UTC, opbld32 commented
Docs Build status updates of commit _[29f92da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29f92da7104bc34a935ac102724de7be47d1dc6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-92cb4fd6)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-92cb4fd6"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to [...]

2022-06-20 13:38 UTC, opbld34 commented
Docs Build status updates of commit _[bceea3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bceea3eaa7f4c3c7691aacf0064051dceb32a9eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-991e129b)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-991e129b"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 52, Column 33**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to [...]

2022-06-20 13:42 UTC, abheek-das commented
Hi @angelgolfer-ms, hope you are doing well! Could you please help review this PR and provide your feedback? I also wrote a new concept page (outlook-things-to-know-about-send-mail.md). Could you also help suggest what a good hierarchy would be, to put this under?

2022-06-23 11:36 UTC, opbld30 commented
Docs Build status updates of commit _[f34eec0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f34eec01ea6cf1dfe4d01c2344f9dac9341d4236)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-c1a5665a)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-c1a5665a"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will  [...]

2022-06-23 14:20 UTC, opbld34 commented
Docs Build status updates of commit _[ab351b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab351b11822cce04cb0d0e24c4efecbc2677449d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-219b329e)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-219b329e"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww. Otherwise, remove the view parameter.`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' will  [...]

2022-06-30 16:28 UTC, opbld31 commented
Docs Build status updates of commit _[f6a93f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6a93f4f2b5defb15555e44321d71bc58b4ac115)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-fd8d4ea3)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-fd8d4ea3"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-me [...]

2022-07-04 07:52 UTC, opbld32 commented
Docs Build status updates of commit _[b277b9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b277b9af9a81f697fa0a5b771f24c01a7ea3e31f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-7b52a715)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-7b52a715"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-me [...]

2022-07-11 06:21 UTC, opbld31 commented
Docs Build status updates of commit _[52ad0f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52ad0f8b0bf6b5771500309ad9d7024a38802200)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-96252367)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-96252367"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-me [...]

2022-07-15 05:52 UTC, opbld33 commented
Docs Build status updates of commit _[3750669](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3750669640c0c9d983743b4ed74ed8c83b7e12ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-79d034c4)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-79d034c4"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-me [...]

2022-07-18 10:12 UTC, opbld34 commented
Docs Build status updates of commit _[a8b66bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8b66bf7e54ce40efed8ca80ec8ff1107cea25aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-c790dcc9)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-c790dcc9"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-me [...]

2022-07-22 08:27 UTC, angelgolfer-ms commented on api-reference/v1.0/api/message-delta.md
Since changeType is another custom query options (aka query parameter in our docs' lingo), please add that to after line 64 in the query parameter table.

2022-07-22 08:29 UTC, angelgolfer-ms commented on api-reference/v1.0/api/message-delta.md
>  ## HTTP request
This comment is for the beta version of message-delta.md - since your changelog included the support for the beta version of message-delta.md, can you make the similar changes in that beta topic as well?

2022-07-22 08:35 UTC, angelgolfer-ms commented on api-reference/v1.0/api/message-delta.md
>  Tracking changes in messages incurs a round of one or more **delta** function calls. If you use any query parameter
Line 53:
Let's be a bit clearer since now we're adding another custom query option "changeType":
Can you update the second sentence in this paragraph to say:
"... If you use any query parameter that is an OData system query option or the custom query option `changeType` , you must specify it in the initial **delta** request."

2022-07-28 14:51 UTC, abheek-das commented on api-reference/v1.0/api/message-delta.md
Added

2022-07-28 14:54 UTC, opbld33 commented
Docs Build status updates of commit _[fdd0e00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdd0e000160b7695c013434bc22074b9b2ced3d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-19dbd1e6)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-19dbd1e6"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww`````
 - **Line 52, Column 33**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-me [...]

2022-07-28 14:58 UTC, abheek-das commented on api-reference/v1.0/api/message-delta.md
>  Tracking changes in messages incurs a round of one or more **delta** function calls. If you use any query parameter
Added.

2022-07-28 14:58 UTC, abheek-das commented on api-reference/v1.0/api/message-delta.md
>  ## HTTP request
Added.

2022-07-28 15:00 UTC, opbld32 commented
Docs Build status updates of commit _[e6f2966](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6f2966998d53651b8324dfb11e9fe44588c96b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-fb3a5e62)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-fb3a5e62"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver [...]

2022-07-28 15:05 UTC, opbld31 commented
Docs Build status updates of commit _[8e1b7de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e1b7de9d50a8e8a686cf8a2831f7516789e1597)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-e21ac470)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-e21ac470"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-07-28 18:43 UTC, opbld32 commented
Docs Build status updates of commit _[cf4f04c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf4f04ca4ca299f60a46d5d7c4a4869f0997448e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-412203cd)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-412203cd"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-01 04:41 UTC, opbld30 commented
Docs Build status updates of commit _[cd6ee22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd6ee22d94b4dc68efc392db1025e0b2a84c92c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-cf0293c9)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-cf0293c9"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-05 09:52 UTC, opbld31 commented
Docs Build status updates of commit _[3015533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3015533e1150af0d7a417854907c4f347c162ff2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-ca4b9849)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-ca4b9849"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-15 12:24 UTC, opbld32 commented
Docs Build status updates of commit _[4fa5b26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fa5b26f62e4a1acaf33d59561f1bc1decd3e3da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-60aa7163)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-60aa7163"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-17 09:43 UTC, opbld32 commented
Docs Build status updates of commit _[b1b6a03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1b6a03f910065ed17d5acd74bd7a9d740b486cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-5a12a878)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-5a12a878"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-18 08:38 UTC, angelgolfer-ms commented on api-reference/beta/api/message-delta.md
> +| changeType | string | A custom query filter to filter the delta response based on the changeType. Supported values are `created`, `updated` or `deleted`.|
Line 63:
At the end of the first sentence in the description, you mention "changeType". Do you mean "change type" (as in natural language) trying to explain what the query option "changeType" means? 
If we spell "changeType" as one word, we'd be implicitly saying this is some programmability term. I only know of 2 such usages - one is "changeType" property of the changeNotification complex type, which is technically a separate feature from delta query, the other is here the changeType customer query option.

2022-08-18 08:53 UTC, angelgolfer-ms commented on api-reference/beta/api/message-delta.md
>  ## HTTP request
Line 32:
FYI I flipped the order of lines 32 and 33 for you (to save us time reviewing this issue again).

2022-08-18 09:08 UTC, angelgolfer-ms commented on concepts/delta-query-messages.md
@abheek-das , I have a question and a comment, depending on the answer to the question.

Question: does this changeType query option assume there is an initial round of sync where all the messages in the folder are sync'd down?
It seems to me only that way would there be a point of reference that indicates whether a message is considered new, updated, or removed, right? 
Like, if there's no base line (no initial sync), what is being compared to such that a message can be considered updated?

2022-08-18 09:49 UTC, angelgolfer-ms commented on concepts/delta-query-messages.md
I think this is relevant because if a customer takes a holistic approach and starts from the concept overview topic, the customer may be aware that AAD resources that support delta support something called "[sync from now](https://docs.microsoft.com/en-us/graph/delta-query-overview?view=graph-rest-beta#use-delta-query-to-track-changes-in-a-resource-collection)".  
Sync from now saves customers the initial round of sync-ing data to the local store from the remote store. In the case of messages, even if one wants only changes of a certain type, the initial round still syncs down all the data from the remote store, is that right?

2022-08-18 09:58 UTC, angelgolfer-ms requested changes
Hi @abheek-das , I have only reviewed the content updates in this PR pertaining to delta query. In the interest of time, you can take a look at those comments first. I'll continue reviewing in the afternoon tomorrow.

2022-08-18 10:01 UTC, opbld33 commented
Docs Build status updates of commit _[7e103de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e103de42822cca4e764a0c6689bb86999111975)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-2fd74ede)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-2fd74ede"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-18 10:03 UTC, opbld30 commented
Docs Build status updates of commit _[8762e9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8762e9e1aafb7b5bfbd94168f4088392fef29069)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-a1302ac2)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-a1302ac2"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 00:48 UTC, opbld32 commented
Docs Build status updates of commit _[7582f2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7582f2cc3c089e730942158a139f1b219343b2d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-5e89325e)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-5e89325e"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 01:46 UTC, angelgolfer-ms commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
This comment is about support customizing the time zone for those 3 message methods that return a message resource - where, which property/properties would setting the time zone take effect?

Your description says "timezone in the email thread". That comes down to individual message objects in the email thread, because (unlike the COM object model) we don't expose a resource that represents an email thread. If that's the case, there are only 3 date/time-related properties in message - createDateTime, lastModifiedDateTime, sentDateTime - each of which we say the time zone is UTC: 
"The date and time information uses ISO 8601 format and is always in UTC time..."

If that's changing, then you'd please modify accordingly the descriptions of those 3 properties in message.md as well?

2022-08-19 02:09 UTC, angelgolfer-ms commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
BTW, assuming indeed that those properties no longer have to be in UTC, and, we're referring using the Prefer header to set the time zone of the 3 date/time properties in each message of an email thread, then, I'd suggest rephrasing the Prefer header description as follows:
"Sets the time zone for **createdDateTime**, **lastModifiedDateTime**, and **sentDateTimeproperties** of each message in the email thread. Values can be any of the [supportedTimeZones](outlookuser-supportedtimezones.md) configured for the user. If not specified, those date-time values are returned in UTC. Optional."

2022-08-19 02:10 UTC, angelgolfer-ms commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
Please make sure indeed we mean each message in the email thread? I just deduced from your existing description, I don't know the actual behavior.

Also, please note that we should use "time zone" as two words. I just checked how the style guide presents that term.

2022-08-19 02:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/itemattachment.md
> +|contentType|String|The content type of the attachment. Optional. Returned as `null` by default, when not set explicitly.|
This comment applies to the identical changes for contentType in itemattachment.md and referenceattachment.md:
Please leave the term "Optional." to the last thing in a description.

2022-08-19 05:31 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +        {
This comment applies to both changelist records for v1 and for beta:
Please see example 18 in the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog) topic to fix your changelist JSON.

2022-08-19 06:19 UTC, abheek-das commented on concepts/delta-query-messages.md
> Synchronizing message items in a local store can use the **delta** query for both the initial full synchronization along with subsequent incremental synchronizations. Typically, you would do an initial full synchronization of all the messages in a folder (for example, the user's Inbox), and then, get incremental changes to that folder periodically.
> 
> To get incremental changes of only a certain type - created, updated, or deleted since the initial sync - do an initial round of synchronization of all the messages in the folder, and then get incremental changes of the specific type in subsequent rounds. Specify the desired change type as a query option in the initial **delta** request; Microsoft Graph automatically encodes any OData and custom query options into the @odata.nextLink or @odata.deltaLink provided in the response.

Yes, that's the correct understanding - the initial round of sync is needed to establish baseline.


> So assuming that there still should _always_ be an initial sync, like before, then I think we need to clarify that at the top of this topic, specifically the second paragraph. Let's change the second paragraph to the following second and third paragraphs (the third paragraph is new):
> 
> "Synchronizing message items in a local store can use the **delta** query for both the initial full synchronization along with subsequent incremental synchronizations. Typically, you would do an initial full synchronization of all the messages in a folder (for example, the user's Inbox), and then, get incremental changes to that folder periodically.
> 
> To get incremental changes of only a certain type - created, updated, or deleted since the initial sync - do an initial round of synchronization of all the messages in the folder, and then get incremental changes of the specific type in subsequent rounds. Specify the desired change type as a query option in the initial **delta** request; Microsoft Graph automatically encodes any OData and custom query options into the @odata.nextLink or @odata.deltaLink provided in the response. "

I agree this makes things much clearer, I have updated the doc as per above.

> I think this is relevant because if a customer takes a holistic approach and starts from the [conceptual overview](https://docs.microsoft.com/en-us/graph/delta-query-overview?view=graph-rest-beta#use-delta-query-to-track-changes-in-a-resource-collection) topic, the customer may be aware that AAD resources that support delta support something called "[sync from now](https://docs.microsoft.com/en-us/graph/delta-query-overview?view=graph-rest-beta#use-delta-query-to-track-changes-in-a-resource-collection)".
> Sync from now saves customers the initial round of sync-ing data to the local store from the remote store. In the case of messages, even if one wants only changes of a certain type, the initial round still syncs down all the data from the remote store, is that right?

Yes, the initial round of sync cannot be avoided even when only syncing changes of a certain type.

2022-08-19 06:26 UTC, opbld31 commented
Docs Build status updates of commit _[82a243b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82a243bdc79a6dfc02cd080176b03d3fc47bbfab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-177d7caa)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-177d7caa"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 06:32 UTC, abheek-das commented on api-reference/beta/api/message-delta.md
> +| changeType | string | A custom query filter to filter the delta response based on the changeType. Supported values are `created`, `updated` or `deleted`.|
Makes sense. I actually just changed "...based on the changeType..." to "...based on the type of change..." to make it a bit more clearer.

2022-08-19 06:36 UTC, opbld31 commented
Docs Build status updates of commit _[40baa36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40baa360db4f6bf0d36eb429f980da90d999947d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-442a5c17)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-442a5c17"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 06:38 UTC, opbld34 commented
Docs Build status updates of commit _[cfe613e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfe613e7745eba220f6b7847d7909e4f766e1c6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-58a82ffa)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-58a82ffa"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 07:56 UTC, angelgolfer-ms commented on concepts/known-issues.md
>    * When using the `$count=true` query string when querying against directory resources, the `@odata.count` property will be present only in the first page of the paged data.
Lines 511-512:
This comment is about listing this behavior as a known issue.
The behavior that the item types in an Exchange Online folder are not homogenous (not all items are of the same type) has existed for at least two decades. Assuming there's no plan to change that behavior, then this behavior should not be in the known issues topic; known issues are described as such only if there's a plan to fix the issue in a semester. Otherwise the behavior should be considered as default behavior and described in the corresponding topics where the behavior crops up.

2022-08-19 08:04 UTC, opbld31 commented
Docs Build status updates of commit _[eddd5b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eddd5b9bb83c367073018ab8d5802e6969d6340c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-3dcb3c52)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-3dcb3c52"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 08:04 UTC, abheek-das commented on api-reference/beta/resources/itemattachment.md
> +|contentType|String|The content type of the attachment. Optional. Returned as `null` by default, when not set explicitly.|
Fixed for both intemattachment & referenceattachment and in both beta & v1.0 version of docs.

2022-08-19 08:06 UTC, opbld30 commented
Docs Build status updates of commit _[3601c2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3601c2e081ee8d196125089e871f888a5fdf7567)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-f6a6a49c)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-f6a6a49c"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 08:10 UTC, angelgolfer-ms commented on concepts/known-issues.md
>    * When using the `$count=true` query string when querying against directory resources, the `@odata.count` property will be present only in the first page of the paged data.
About the following sentence in line 512:
"To avoid this, it's recommended to use $top with a specific mailFolder (like `/me/mailFolders/Inbox/messages`) which *usually* contains only messages as opposed to `/me/messages` which tries to get messages from the entire mailbox."
Respectfully, I don't think we should suggest that usually message folders contain only email messages. It depends. 
Because Outlook/Exchange allows folders to contain more than one message type, for example, some organizations can run add-ins take advantage of this characteristic and can create heterogeneous folders.

2022-08-19 08:10 UTC, abheek-das commented on changelog/Microsoft.Exchange.json
> +        {
Fixed.

2022-08-19 08:13 UTC, opbld30 commented
Docs Build status updates of commit _[741a871](https://github.com/microsoftgraph/microsoft-graph-docs/commits/741a871fbacd89a43229065312a1aaaad78f9cf3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-0cddaac1)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-0cddaac1"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 08:17 UTC, angelgolfer-ms commented on concepts/known-issues.md
>    * When using the `$count=true` query string when querying against directory resources, the `@odata.count` property will be present only in the first page of the paged data.
Instead, I suggest to add a paragraph to an "include" file, and expose that paragraph in a few topics where this is relevant:

- query-parameters.md (under the [top](https://docs.microsoft.com/en-us/graph/query-parameters#top-parameter) parameter section)
- paging.md (in the last bullet list of the topic)
- user-list-messages.md (after the 4th paragraph)
- message-delta.md

The paragraph goes like this:
"If you include `$top` to control the page size when getting multiple messages, it's possible that the response contains fewer messages than the page size. This is because item types are not necessarily homogenous in folders on Exchange Online. The same folder can contain messages and other item types. If the operation returns an @odata.nextlink, continue calling the operation using the URL in the latest @odata.nextlink until the operation no longer returns an @odata.nextlink."

2022-08-19 08:25 UTC, abheek-das commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
@angelgolfer-ms Hmm, yeah I get the ambiguity here. So - 
- None of the createdDateTime, lastModifiedDateTime, sentDateTime, receivedDateTime is impacted because of adding this header & are unchanged.
- However, in the Reply's "Send Date: XXXX" is modified as per the specified time zone. See highlighted in the examples below:
  - With Prefer: outlook.timezone=**"IndianStandard Time"**
    
![image](https://user-images.githubusercontent.com/65342232/185570592-c3168da4-89ea-457f-a22f-9f9094e24a7e.png)

   - With Prefer: outlook.timezone=**"Eastern Standard Time"**
 
![image](https://user-images.githubusercontent.com/65342232/185570670-05b858ac-9bfc-4c9f-a331-a10ab04fa696.png)

- So I think I should probably change the description as - "Sets the _Sent Date_ in the desired time zone format while replying to a message. Values can be any of the outlook [supportedTimeZones](outlookuser-supportedtimezones.md). If the header is not specified, by default UTC timezone is followed. Optional."

2022-08-19 09:44 UTC, abheek-das commented on concepts/known-issues.md
>    * When using the `$count=true` query string when querying against directory resources, the `@odata.count` property will be present only in the first page of the paged data.
So, this is a bit interesting. 

1. You are right that the Exchange folders are not homogenous, and that behavior will not change.
2. The issue here was that, because of this behavior when someone specifies let's say, $top=500 and the mailbox contain a lot of non-message items, the request used to time out because MS Graph times out before Exchange can complete the request. So as per the new behavior, in such cases we'll just send a next link to avoid the timeout and exit gracefully. 
3. In parallel, I checked with the engineering team, to solve for this we are trying another fix which would send the query to the Exchange store with appropriate filters to get only a certain item type. This would potentially solve this issue, but it's not confirmed yet.

So, for now - I am reverting this change in the known issues page. Based on #2 or #3, whichever way we decide to go, we will make the doc updates at a later stage.

2022-08-19 18:51 UTC, opbld31 commented
Docs Build status updates of commit _[5c088bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c088bf20c86fb0ec49feb211e44d7cb743d7dc4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-d05a39ff)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-d05a39ff"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-19 21:44 UTC, angelgolfer-ms commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
Hi @abheek-das , if that's what the Prefer header does - sets the "Sent" field of the reply draft or reply message (depending on the API whether it's createReply, createReplyAll vs reply, replyAll) - should we say:

"Sets the time zone for the `Sent` field of the reply message (use "reply draft" if this description appears in createReply or createReplyAll) that this API creates based on the request body. The value can be any of the [supportedTimeZones](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17356/outlookuser-supportedtimezones.md) configured for the user. If not specified, that `Sent` field is in UTC. Optional."

2022-08-19 22:12 UTC, angelgolfer-ms commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
Pointing out a few things:

1. Would createReplyAll be in scope for this change too?
2. The Prefer header sets the time zone, not time zone format, right? The format is whatever ISO 8601 supports.

3. I wanted to make the description clear that the Prefer header acts on the one message (or draft) that the API call creates as a reply. Setting that Prefer header doesn't change the time zone in the Sent fields of any earlier messages in an email thread that the API is replying to, is that the behavior?

If we look at the [first example in createReplyAll](https://docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&tabs=http#example-1-create-a-draft-in-json-format-to-reply-all-to-an-existing-message) by opening the file message-createreplyall.md in VS Code, and search for "sent", the example response body has a body/content property specifying an email thread consisting of 2 messages. Only the first Sent field would be impacted by the Prefer header, is that right?

4. And is it true that if the Content/type of the API is set to text/plain, then the Prefer header doesn't do anything?
The response has the body/content property in text format, not HTML, so there's no Sent field to be impacted?
If this is true, then the description for the Prefer header should be 2 paragraphs like below:

"Sets the time zone for the `Sent` field of the reply message in HTML (use "reply draft" if this description appears in createReply or createReplyAll) that this API creates based on the request body. The value can be any of the [supportedTimeZones](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17356/outlookuser-supportedtimezones.md) configured for the user. If not specified, that `Sent` field is in UTC. 

Use this header only if you're specifying the `Content-Type: application/json` header to create the reply message (or "reply draft" if this description appears in createReply or createReplyAll) in HTML. If you use the `Content-Type: text/plain` header, this `Prefer` header does not have any effect. Optional."

2022-08-19 22:19 UTC, angelgolfer-ms commented on concepts/known-issues.md
>    * When using the `$count=true` query string when querying against directory resources, the `@odata.count` property will be present only in the first page of the paged data.
#3 in your last message sounds good!
Do nothing in the docs for now sounds good too!

2022-08-19 22:52 UTC, angelgolfer-ms commented on concepts/delta-query-messages.md
@abheek-das , thanks for incorporating my feedback to the above two paragraphs.

Per our Teams chat, yes, it would be helpful for customers if you can add one more example to show using the changeType header. You can please model the existing example, like using $select to get fewer properties, and a Prefer: odata.maxpagesize=2, so that it's easier for customers to see the big picture (nextLink, deltaLink, "borders" of each message), and not be distracted by extraneous data.

I suggest a simple case where we'll state the folder starts with having 4 messages, and after the first round, 2 more messages get created. Albeit other updates or deletions, the second round would show only what's been created. :-)

Round 1 - syncs down entire folder of 4 messages:
Initial call specifying the changeType, returning a nextLink. Syncs down 2 messages.
Second call using the last nextLink, returning a deltaLink. Syncs down remaining 2 messages.
Round 2:
One call using the last deltaLink, returning only the 2 newly created messages.

Please enhance where you see fit :-)
(All

2022-08-20 01:50 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +Sending email is a multi-step process. Most of the steps take place after the sendMail Microsoft Graph call has returned. Here is a simple summary of what typically
Lines 9-21:
Just want to be sure - we say "sendMail" and not "sending mail" to exclude the other APIs that sends a message or a draft, like the send, reply, replyAll, and forward actions?

2022-08-20 02:13 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +Microsoft Graph creates a new message (typically in the sender's Drafts folder), copies message content, recipients, and attachments from the JSON request to it, and
Line 14:
It would be correct if I say Outlook instead of "Microsoft Graph" as the subject, right?
Microsoft Graph is a developer platform which exposes a common REST API endpoint for developers to access Microsoft 365 services, including Outlook. It's Outlook that creates the message in the Drafts folder, and so on. Is that right?
Please adjust the text if that's not correct.

2022-08-20 07:11 UTC, opbld34 commented
Docs Build status updates of commit _[9f3dea7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f3dea7f9e045849131f6c1e3a861897588c24bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-35209d2f)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-35209d2f"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 42, Column 155**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 33**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 42, Column 155**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's [...]

2022-08-20 07:53 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +
Line 15:
For the 4 methods - sendMail, reply, replyAll, forward - that create a message and send it, we document in each of those topics that they return 202 Accepted if successful. So why do we say 2xx status here?
Is it in reality, they can return some other "successful" status code other than 202? If this is the case, that should be clarified in the docs.
Or, should line 15 say specifically 202 Accepted?

2022-08-20 08:28 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +moves it from the Drafts folder to the Sent Items folder. (Depending on optional message properties, it may move to a different folder or delete the message instead.)
Line 35:
"... Exchange store updates the message and..." - update how? If we mention update, then we should be clearer please.

Also, if this article is specifically about sendMail, then the next phrase about moving the message from the Drafts folder to the Sent Items folder should not use the indefinite "typically".
Is it true that (only) if the saveToSentItems parameter of sendMail is set to false would the store deletes the message?

As for "... move to a different folder", what optional message properties are we referring to? For the properties we expose, I don't see anyone we have described that would save the message in some other folder after sending. If we're not pointing out which optional properties, then we should just not mention moving to a folder other than Sent Items or Deleted Items.

2022-08-20 08:46 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +the recipient and attachment tables. When complete, the sendMail API returns a 2xx status.
Line 17:
What is the significance of mentioning that Outlook copies the MIME content to a "single property", if we're not naming it? Can we skip that and just say "Outlook parses the MIME content and copies the corresponding content to message properties, and to recipients and attachments tables.

Also, about the "2xx" status code again - we have documented success returning 202 Accepted. Now the vagueness of "2xx" can make customers doubt our docs (if that's indeed a reality and some customers don't know yet). Can you clarify what the actual behavior can be and we can see what needs to be changed?

2022-08-20 08:53 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +case, the sendMail API returns a 4xx or 5xx status.
Line 20:
"exotic" as an adjective for reasons for messaging to fail doesn't seem to be an appropriate word, and besides, it's vague. 
I think we should leave that out. Stating the first two as _examples_ (implying there are other reasons not listed here) is sufficient.

2022-08-20 08:57 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +
Line 26:
Can I say "Outlook" instead of "Microsoft 365" (we don't use "M365" in external communication, that's breaking the brand)?

2022-08-20 09:10 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +
Line 46:
Again, is it accurate to refer to "Microsoft 365 transport" as Exchange Online?
To me, the Marketing messaging for "Microsoft 365" is a collection of products and services. Are customers supposed to visualize transport as a layer across all services in Microsoft 365?

2022-08-20 09:12 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +
For the second instance of "M365 mailbox", can we be more specific and say "Exchange Online mailboxes"?

2022-08-20 09:31 UTC, angelgolfer-ms requested changes
HI @abheek-das , FYI I finished reviewing all the topics in this PR. Please see my latest comments and direct commits in the concept topic.

2022-08-20 09:31 UTC, opbld30 commented
Docs Build status updates of commit _[3b35697](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b35697ff2e36578a6cdbd20ae6246f9bd8b7f36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-b9561fb7)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-b9561fb7"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 41, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 41, Column 149**: **[S [...]

2022-08-21 09:28 UTC, opbld33 commented
Docs Build status updates of commit _[8cc1d19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cc1d19bd7b93dc27c996bac8b20d10c0f6c6e1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-e224c1b3)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-e224c1b3"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 41, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 41, Column 149**: **[S [...]

2022-08-21 09:29 UTC, abheek-das commented on concepts/known-issues.md
>    * When using the `$count=true` query string when querying against directory resources, the `@odata.count` property will be present only in the first page of the paged data.
Okay great. Reverted the changes!

2022-08-21 09:31 UTC, opbld31 commented
Docs Build status updates of commit _[7084765](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7084765b2c967fd8058173e70b83edfc6e95c223)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-389ca5f0)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-389ca5f0"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 41, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 41, Column 149**: **[S [...]

2022-08-21 10:39 UTC, abheek-das commented on concepts/delta-query-messages.md
@angelgolfer-ms  - Added another example. Please take a look!

2022-08-21 10:39 UTC, opbld31 commented
Docs Build status updates of commit _[dda5b38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dda5b3802f0571b86639fb43b445326b5d829318)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) | [Details](#user-content-a508539a56129daaa32228efb312033d-173d0352)
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-173d0352)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="a508539a56129daaa32228efb312033d-173d0352"></a>
### [concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md)
 - **Line 42, Column 9**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#example-synchronize-messages-in-a-folder' in 'delta-query-messages.md', did you mean '#example-1-synchronize-messages-in-a-folder'?`````
 - **Line 490, Column 39**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#sample_second_request_specifying_changetype' in 'delta-query-messages.md'.`````

<a id="d6c249516094b2593b528b2399d648af-173d0352"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 41, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 14 [...]

2022-08-21 10:47 UTC, opbld33 commented
Docs Build status updates of commit _[4963913](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4963913ca1cc27f85325dfddce28673846f9050b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-2e833f7a)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-2e833f7a"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 41, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 41, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recomme [...]

2022-08-21 10:51 UTC, abheek-das commented on concepts/outlook-things-to-know-about-send-mail.md
> +
We can make it `202 Accepted`. Made the change!

2022-08-21 11:02 UTC, abheek-das commented on concepts/outlook-things-to-know-about-send-mail.md
> +the recipient and attachment tables. When complete, the sendMail API returns a 2xx status.
Agreed with above. `202 Accepted` makes sense to me.

2022-08-21 11:10 UTC, abheek-das commented on concepts/outlook-things-to-know-about-send-mail.md
> +
I made it "Exchange Online". I've changed "Outlook"/"M35=65" to "Exchange Online" as well throughout the doc. Please review!

2022-08-21 11:14 UTC, opbld30 commented
Docs Build status updates of commit _[a4efd15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4efd15626f832cd474448fb42cdc23543f58f9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-b32bc8b1)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-b32bc8b1"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 40, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recomme [...]

2022-08-21 12:09 UTC, abheek-das commented on concepts/outlook-things-to-know-about-send-mail.md
> +moves it from the Drafts folder to the Sent Items folder. (Depending on optional message properties, it may move to a different folder or delete the message instead.)
`"After all of this succeeds..." - is it accurate if we say "if step 3 succeeds"? Or if you're not just referring to step 3, and step 2 can fail, then should we make it clear in step 2 what happens if step 2 fails?`
Changed it to - "After step 3 succeeds, ..."

`"... Exchange store updates the message and..." - update how? If we mention update, then we should be clearer please.`
Changed it to - "In response, the Exchange store updates the draft state and internet message headers associated with the message and moves it from the Drafts folder to the Sent Items folder."

`Is it true that (only) if the saveToSentItems parameter of sendMail is set to false would the store deletes the message?`
Yes, if saveToSentItems is explicitly specifed as false, then a copy is not saved in the sent items folder. Else it is, even if this property is not mentioned explicitly.

`As for "... move to a different folder", what optional message properties are we referring to? For the properties we expose, I don't see anyone we have described that would save the message in some other folder after sending. If we're not pointing out which optional properties, then we should just not mention moving to a folder other than Sent Items or Deleted Items.` 
Modified as suggested.

2022-08-21 12:14 UTC, abheek-das commented on concepts/outlook-things-to-know-about-send-mail.md
> +Sending email is a multi-step process. Most of the steps take place after the sendMail Microsoft Graph call has returned. Here is a simple summary of what typically
@angelgolfer-ms  - I think this will be applicable to all the Graph APIs that can send mail. The backend process should be similar for all such Graph actions. In that case, what do you suggest should be an appropriate title for this article? Something like - 
_"How does sending mail works using Microsoft Graph APIs?"_

2022-08-21 15:18 UTC, abheek-das commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
`And is it true that if the Content/type of the API is set to text/plain, then the Prefer header doesn't do anything?
The response has the body/content property in text format, not HTML, so there's no Sent field to be impacted?`

I think the header only impacts when the "comment" property is used instead of "body" property to reply to the message. When using "message" --> "body" --> "content", the entire body is constructed as part of the API response, so this won't have any effect!

2022-08-21 15:50 UTC, opbld32 commented
Docs Build status updates of commit _[55e291e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55e291e8b60750e357e73141a02b45d5e0fb635b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-6ac1df8f)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-6ac1df8f"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 40, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recomme [...]

2022-08-21 15:52 UTC, opbld33 commented
Docs Build status updates of commit _[d16870b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d16870be3a10970b1223954b0ac6c086a7ad5d09)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-603e6842)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-603e6842"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 149**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' will be [...]

2022-08-21 15:54 UTC, opbld34 commented
Docs Build status updates of commit _[94da29f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94da29fb4785b2289980c377ce645bf0447965fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-29941ed1)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-29941ed1"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from lin [...]

2022-08-21 15:56 UTC, opbld32 commented
Docs Build status updates of commit _[ebb700c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebb700c3846c86aa687fb512e6dc91a3eed22acd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-7f1b2fdd)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-7f1b2fdd"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from lin [...]

2022-08-21 15:58 UTC, abheek-das commented on api-reference/beta/api/message-replyall.md
> +| Prefer: outlook.timezone | string | Sets the timezone in the email thread to the desired format while replying to an email. Values can be any of the outlook [supportedTimeZones](outlookuser-support
#1, #2, #3 & #4 are all the correct understanding! :)
Made the suggested change in all the files!

2022-08-23 04:10 UTC, opbld33 commented
Docs Build status updates of commit _[09913c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09913c7373a49de7fbb8dada14f8b4406a6b1695)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-5d0ee26a)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-5d0ee26a"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from lin [...]

2022-08-23 07:31 UTC, angelgolfer-ms commented on concepts/delta-query-messages.md
> +  "name": "get_messages_delta_4"
Line 368 and other sampleKeys lines in this example:
FYI sampleKeys is to specify ID values in the example request.
In this case, line 373 contains only one such value that indexes into the mailFolders collection.
The line should be:
"sampleKeys": ["AAMkAGUwNc4LTMzAAA="],

I'm fixing these values on your behalf to try to cut down on the review iterations.

2022-08-23 07:32 UTC, angelgolfer-ms commented on concepts/delta-query-messages.md
> +  "name": "get_messages_delta_4"
More info on sampleKeys: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211782/Set-up-for-API-Doctor-validation?anchor=id-values-in-example-requests

2022-08-23 08:03 UTC, angelgolfer-ms commented on concepts/outlook-things-to-know-about-send-mail.md
> +
HI @abheek-das ,
You seem to have made a change in line 17 but left line 15 alone, i.e., it's still the following:
"If successful, the **sendMail** method returns an HTTP response status code in the 2xx category."

I'm changing that sentence in line 15:
"If successful, the **sendMail** method returns an HTTP response `202 Accepted` status code."

2022-08-23 08:12 UTC, opbld30 commented
Docs Build status updates of commit _[946b77b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/946b77b042738751738ad55c2eeba9360b36f035)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-11dfb25c)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-11dfb25c"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from lin [...]

2022-08-23 08:16 UTC, angelgolfer-ms approved these changes
I think the PR is fine for publishing. Thanks!

2022-08-24 01:02 UTC, opbld32 commented
Docs Build status updates of commit _[71bdcca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71bdcca053e68827b4eadfd03f816fe53277a6a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-1d9334b7)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-1d9334b7"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from lin [...]

2022-08-24 01:05 UTC, opbld34 commented
Docs Build status updates of commit _[3c435c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c435c67a4344593a3d145cda6d9132424b7844e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-11e48d42)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-11e48d42"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/Exchange/mail-flow/mail-flow?view=exchserver-2019&viewFallbackFrom=exchonline-ww' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 52, Column 45**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/exchange/mail-flow/non-delivery-reports-and-bounce-messages/non-delivery-reports-and-bounce-messages?view=exchserver-2019' contains locale code 'en-us'. For localizability, remove 'en-us' from lin [...]

2022-08-24 01:54 UTC, opbld34 commented
Docs Build status updates of commit _[a0b28e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0b28e2849f9cb31219685221ed6b5ca492e13c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-2b5982c1)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-2b5982c1"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:00 UTC, opbld31 commented
Docs Build status updates of commit _[eadb0ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eadb0ed11496ae051ae9dabc3d6b9c7d281d028a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-97d20376)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-97d20376"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:03 UTC, opbld31 commented
Docs Build status updates of commit _[45db375](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45db375d62aef3a7df3cb33eb4a01a4ab186f818)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-fd20ff43)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-fd20ff43"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:05 UTC, opbld33 commented
Docs Build status updates of commit _[8c5ae20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c5ae202386948b97b8b9370a8c7807e80c3cf16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-f58617da)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-f58617da"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:08 UTC, opbld31 commented
Docs Build status updates of commit _[83405e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83405e81835963d03e052b9f59d214c9e63f5a74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-59585040)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-59585040"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:13 UTC, opbld30 commented
Docs Build status updates of commit _[6e71195](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e71195cb379f17559171d744921691b02a16655)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-a3df4fee)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-a3df4fee"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:15 UTC, opbld34 commented
Docs Build status updates of commit _[d33b74e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d33b74e0664926ba00633653e46f036c41db6ca7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-1e9c071d)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-1e9c071d"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:27 UTC, opbld30 commented
Docs Build status updates of commit _[d287d18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d287d18baf422747c5ff37a812cf981e6ae6748b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-48409b65)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-48409b65"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.mic [...]

2022-08-24 02:36 UTC, opbld34 commented
Docs Build status updates of commit _[81b9f06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81b9f06981ed403386cbae9c5cb7332381e1319e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail?branch=pr-en-us-17356) | [Details](#user-content-d6c249516094b2593b528b2399d648af-e2900afc)
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-17356) (graph-rest-beta) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/itemattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/itemattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/itemattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/resources/referenceattachment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-17356) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/delta-query-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-17356) |

<a id="d6c249516094b2593b528b2399d648af-e2900afc"></a>
### [concepts/outlook-things-to-know-about-send-mail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mail_api_doc_updates/concepts/outlook-things-to-know-about-send-mail.md)
 - **Line 40, Column 149**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You' [...]

2022-08-24 02:41 UTC, merged

2022-08-24 02:42 UTC, angelgolfer-ms reviewed
Made adjustments, completed content review, approving PR.