Team Summary v1.0 Docs changes
microsoftgraph/microsoft-graph-docs pull request #17355
Opened 2022-06-20 08:18 UTC by akhilkohlimicrosoft

2022-06-20 08:21 UTC, opbld31 commented
Docs Build status updates of commit _[27d8d96](https://github.com/akhilkohlimicrosoft/microsoft-graph-docs/commits/27d8d968f319aec77d386e04001d568b2e0014fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-17355) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-17355) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/teamsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsummary?view=graph-rest-1.0&branch=pr-en-us-17355) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/akhilkohlimicrosoft/microsoft-graph-docs/blob/main/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206200818188102-17355/BuildReport?accessString=adef7cd6b8b924f519f72f41dadcb08ab2d6f8b701ce70a3f309066ffe136345).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 11:45 UTC, shantanu1singh approved these changes
LGTM

2022-06-30 15:43 UTC, isvargasmsft commented on api-reference/v1.0/api/team-get.md
> +    "guestsCount": 4,
Please apply this same update to the create and update operations.

2022-06-30 15:46 UTC, isvargasmsft commented on api-reference/v1.0/resources/team.md
>  |messagingSettings|[teamMessagingSettings](teammessagingsettings.md) |Settings to configure messaging and mentions in the team.|
Line 42 of this document: I noticed the **Complete migration** method in the table says it returns a team object, however, the method topic says it returns a 204 No Content. Would you please verify and update accordingly? If it is the table that needs the fix, please say "None" in the Return type column.

2022-06-30 15:48 UTC, isvargasmsft requested changes
Please add the new property to the examples in the create and update methods as well and fix a minor inconsistency with the Complete migration method. 

Kind regards,

Isaac

2022-06-30 21:26 UTC, isvargasmsft commented on api-reference/v1.0/resources/team.md
> +|summary|[teamSummary](teamsummary.md)| Contains summary information about the team, including number of owners, members, and guests. |
Please order this property table alphabetically.

2022-10-14 15:27 UTC, isvargasmsft commented
Implementation delayed as per author's clarification.

2023-04-26 06:33 UTC, closed without merging