Cross tenant fields for audit logs
microsoftgraph/microsoft-graph-docs pull request #17384
Opened 2022-06-22 00:07 UTC by besiler

Added homeTenantId and homeTenantName to directory audit. We missed this when pushing the docs for https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/5102844?_a=files&path=/Changelog/5102844-SignIn-and-Audit-Updates-for-Q1-in-PROD-MC-FF/Microsoft.AAD.Reporting.json

Somehow, the changelog generated by that PR didn't pick up the changes to directoryAudit. I made up the changelog entries in this PR so please take a look at them to make sure they look OK

2022-06-22 00:10 UTC, opbld31 commented
Docs Build status updates of commit _[7b02ae8](https://github.com/besiler/microsoft-graph-docs/commits/7b02ae80747141a2083ddc7cb2c0b86b8d235d06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryaudit-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-get?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/resources/directoryaudit.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220007365291-17384/BuildReport?accessString=51f7a4348b59ad2b0b34d2390b617f1d3f390aca0d10752e63c4872640fd94ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:21 UTC, opbld30 commented
Docs Build status updates of commit _[34d27c6](https://github.com/besiler/microsoft-graph-docs/commits/34d27c69cb32f1fc54f26d43ea61a074715c8a62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryaudit-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-get?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/resources/directoryaudit.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220019039929-17384/BuildReport?accessString=b0ca09c5c0cf79ef4c5bb95be239687c41ce6f4d75f5f3cd0c66caae9dfcd9b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:34 UTC, opbld34 commented
Docs Build status updates of commit _[158047f](https://github.com/besiler/microsoft-graph-docs/commits/158047f3401d82e958985bba6d4a275623f3ddf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryaudit-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-get?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/resources/directoryaudit.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220031575326-17384/BuildReport?accessString=99ce34b0c09e0b23c08a570b88c1b2e415b0d1acf74e03ff9214964541832621).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:39 UTC, opbld30 commented
Docs Build status updates of commit _[7669160](https://github.com/besiler/microsoft-graph-docs/commits/7669160f90b8b895a9b0117a7abfd86ce1c3da43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryaudit-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-get?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/resources/directoryaudit.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220037435086-17384/BuildReport?accessString=29c670b18e8e7944761f68c4c93d54c9b0f022966014d74c9be8e3684426cdb0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 00:53 UTC, opbld33 commented
Docs Build status updates of commit _[50b76c6](https://github.com/besiler/microsoft-graph-docs/commits/50b76c67f3a1decad7f62232161b7edf7cb90647)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryaudit-get.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-get?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/api/directoryaudit-list.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/api/directoryaudit-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[api-reference/beta/resources/directoryaudit.md](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/api-reference/beta/resources/directoryaudit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-beta&branch=pr-en-us-17384) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/besiler/microsoft-graph-docs/blob/besiler-auditlogCrossTenantupdates/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206220051062254-17384/BuildReport?accessString=30c39a44f8410d4e0519dcb50548b4a1b7e70203cde2eb8a4e3ad73c6ecd175e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 17:16 UTC, FaithOmbongi requested changes
Hi @besiler - The two properties were added to the https://docs.microsoft.com/en-us/graph/api/resources/auditUserIdentity?view=graph-rest-beta complex type and they are already in the public docs. I recommend undoing the changes in directoryaudit.md and the changelog and keeping the updated examples instead.

2022-06-23 17:16 UTC, FaithOmbongi commented on api-reference/beta/resources/directoryaudit.md
> +|homeTenantName|String|The display name of the tenant that the user who initiated the auditable activity belongs to. This value is often populated in situations when an organization has granted permi
Hi @besiler - This is incorrect. The two properties were added to the **auditUserIdentity** complex type, _not_ to **directoryAudit** resource type - and you already documented them. See https://docs.microsoft.com/en-us/graph/api/resources/auditUserIdentity?view=graph-rest-beta

2022-06-23 17:31 UTC, besiler commented
@FaithOmbongi thank you so much for keeping me honest that the user properties were already added in https://docs.microsoft.com/en-us/graph/api/resources/auditUserIdentity?view=graph-rest-beta! I couldn't find those properties earlier to show the cross tenant team, so I thought I had missed it. 

I'll follow your suggestions above to keep the example but drop the new properties

2022-06-23 18:09 UTC, besiler commented on api-reference/beta/resources/directoryaudit.md
> +|homeTenantName|String|The display name of the tenant that the user who initiated the auditable activity belongs to. This value is often populated in situations when an organization has granted permi
Removed the field descriptions from directoryaudit.md and removed the changelog entry as requested by Faith

2022-06-25 02:54 UTC, merged