Update synchronization-synchronizationjob-provision-on-demand.md
microsoftgraph/microsoft-graph-docs pull request #17382
Opened 2022-06-21 22:55 UTC by ArvindHarinder1

2022-06-21 22:58 UTC, opbld33 commented
Docs Build status updates of commit _[66393d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66393d15472497c398f43e8bcec81a2c2298b0d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206212255392831-17382/BuildReport?accessString=93aa815b841a853dd7639b7904b239dd8d0b9a1ac1f30f711ab0b83f634ddf5a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 17:35 UTC, opbld31 commented
Docs Build status updates of commit _[080fa84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/080fa84599c8223fbb648d1982e6b3f12449a600)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) | [Details](#user-content-0f67082c8af2f1f1f0c132b2ba1275d2-81821231)
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[synchronizationlinkedobjects](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/synchronizationlinkedobjects) | :white_check_mark:Succeeded | |

<a id="0f67082c8af2f1f1f0c132b2ba1275d2-81821231"></a>
### [api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 21, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/synchronizationjobsubject.md'.`````
 - **Line 22, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/synchronizationjobsubject.md'.`````
 - **Line 23, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/synchronizationjobsubject.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/resources/synchronizationlinkedobjects.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221732261314-17382/BuildReport?accessString=b337a7d8c70db9f1e582307ed3db94eb531e0ad518662790181bffc0162a35cc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 17:42 UTC, opbld32 commented
Docs Build status updates of commit _[423d486](https://github.com/microsoftgraph/microsoft-graph-docs/commits/423d486b38db74a3c560b7f23730faea4da6f422)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) | [Details](#user-content-0f67082c8af2f1f1f0c132b2ba1275d2-8e5805b1)
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0f67082c8af2f1f1f0c132b2ba1275d2-8e5805b1"></a>
### [api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 21, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/synchronizationjobsubject.md'.`````
 - **Line 22, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/synchronizationjobsubject.md'.`````
 - **Line 23, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/synchronizationjobsubject.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/api/security-ediscoverycustodian-removehold.md(3,14)', 'beta/resources/synchronizationlinkedobjects.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221733209891-17382/BuildReport?accessString=f8336a075d9773a4d581dc55e610c8731271bca71a8d8dc17b4b0636f379d051).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 17:43 UTC, opbld34 commented
Docs Build status updates of commit _[f860f20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f860f202601f5a98fcb1aa7379a8374da924ded0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221739141505-17382/BuildReport?accessString=eb6800fb6ad592f88d099a21ccba3971269f628cef308dd6fd09850c07dd540b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 18:02 UTC, opbld31 commented
Docs Build status updates of commit _[42652d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42652d36c88cf9780bde86c201ccdc83ba6e76a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221759453499-17382/BuildReport?accessString=cd6c936d1b72a83e609c0d7ea995b2fb7df609941c78234d258402a589ca5dcc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-22 18:04 UTC, opbld31 commented
Docs Build status updates of commit _[7dad13e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dad13e5da7c0298645079b9210607d74469c02f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206221800156466-17382/BuildReport?accessString=f33a1c9c28203903eb234bddadd3bdab533febdd5561a62c7c3a26447084242b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 17:06 UTC, opbld31 commented
Docs Build status updates of commit _[3e85f2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e85f2a3dee3c7f70feff76ccd5bd1bd2d1d0558)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206231704225117-17382/BuildReport?accessString=c10117d10384c8a39a29b10458c6fcb151b675bbfb847f01ba0c5d930c0d7a00).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 19:49 UTC, FaithOmbongi requested changes
Thank you @ArvindHarinder1 for your work in this PR. I've left a few Qs to address and all are mostly affected by my ignorance of how the synchronization APIs work - Feel free to discard those that don't apply.

2022-06-23 19:49 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronization-synchronizationjobsubject.md
> +|links|[synchronizationLinkedObjects](../resources/synchronizationlinkedobjects.md)|Any group members that you would like to provision.|
Does this make sense?
Justification of not using "groups" - I assume this will also be dependent on the objectTypeName property which doesn't always have to be "Group".
```suggestion
|links|[synchronizationLinkedObjects](../resources/synchronizationlinkedobjects.md)|Principals that you would like to provision.|
```
```suggestion
|links|[synchronizationLinkedObjects](../resources/synchronizationlinkedobjects.md)|Any group members that you would like to provision.|
```

2022-06-23 19:49 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronization-synchronizationjobsubject.md
>  |objectTypeName|String|The type of the object to which a **synchronizationJob** is to be applied. Can be one of the following: <li>`user` for synchronization from Active Directory to Azure AD.</li><l
I see the example you've added uses **objectTypeName** of "Group". Is this value ready to be documented publicly? Yes - please add it to this description. Also, considering there are different group types, might be better to be explicit about the group type you're talking about here (if this is subject to questions).

2022-06-23 19:49 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronizationlinkedobjects.md
> +description: "Represents any references to be provisioned during on-demand provisioning."
```suggestion
description: "Represents the principals to be provisioned during on-demand provisioning."
```

2022-06-23 19:49 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronizationlinkedobjects.md
> +References that you would like to provision on-demand such as a member of a group.
(Forgive my ignorance about provisioning) Considering that even devices can be [group members](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http), should we explicitly call out the type of principals that can be provisioned? Is it user principals only?

Q2: Should we also call out the group types that are allowed?
```suggestion
The principals that you would like to provision on-demand such as specific members of a group.
```

2022-06-23 19:49 UTC, FaithOmbongi commented on api-reference/beta/resources/synchronizationlinkedobjects.md
> +|members|[synchronizationJobSubject](../resources/synchronization-synchronizationjobsubject.md) collection|Any managers of the user that you would like to provision.|
Hmm, "managers" here intentional?

2022-06-23 19:49 UTC, FaithOmbongi commented on api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
> +# [HTTP](#tab/http)
- Suggestion to tweak the title because I assume the example shows that you can decide to provision only a subset of the group members.
- `# [HTTP](#tab/http)` will be added by the snippets generator

```suggestion
### Example 3: Provision a group and two of its members on demand

#### Request

```

2022-06-23 19:51 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Directory management"
Minor fix - the Synchronization APIs lie in the "Applications" node
```suggestion
      "WorkloadArea": "Applications",
      "SubArea": ""
```

2022-06-23 22:38 UTC, ArvindHarinder1 commented on api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md
> +            ]
Only possible to specify members. Our service can't scale to provision everyone in a group.

2022-06-23 22:39 UTC, opbld32 commented
Docs Build status updates of commit _[18d03d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18d03d1ae722abd0efd59fab1c71c4b0dc348efb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232237148682-17382/BuildReport?accessString=ff59e7aff43d1a1f3fe992379565ccaf91ff6177a1f9555b556fec7a485d99b7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:40 UTC, ArvindHarinder1 commented on api-reference/beta/resources/synchronizationlinkedobjects.md
> +|members|[synchronizationJobSubject](../resources/synchronization-synchronizationjobsubject.md) collection|Any managers of the user that you would like to provision.|
Copy paste error. I'll fix. Thanks for catching.

2022-06-23 22:42 UTC, opbld32 commented
Docs Build status updates of commit _[f30a1e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f30a1e32382755a512b918e86705d9c3c9a1a684)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232239156325-17382/BuildReport?accessString=baf4fd582b9ed969adc56d92e01bcacbdd5f5d6b248bb743142273b9820089cf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:44 UTC, ArvindHarinder1 commented on api-reference/beta/resources/synchronization-synchronizationjobsubject.md
>  |objectTypeName|String|The type of the object to which a **synchronizationJob** is to be applied. Can be one of the following: <li>`user` for synchronization from Active Directory to Azure AD.</li><l
Good call. Added mention of the group. We don't have the concept of a group type here.

2022-06-23 22:44 UTC, opbld32 commented
Docs Build status updates of commit _[fe78a5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe78a5d2ee560e6a644c530acfc1d8736ae42a01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232238336238-17382/BuildReport?accessString=b21dc01f1747cca8aaecdc33e6803d8764f88ddd1f8a13f3c37e8dd776f5b35a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:45 UTC, ArvindHarinder1 commented on api-reference/beta/resources/synchronizationlinkedobjects.md
> +description: "Represents any references to be provisioned during on-demand provisioning."
I would prefer to keep it as references. We don't generally use the term principal in our experience. We call these things references (members, managers, owners). Today we support members. In the future, we will also add managers and owners.

2022-06-23 22:46 UTC, opbld32 commented
Docs Build status updates of commit _[652183e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/652183e4ed6e22cba4b383b829be860a1c1aae8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232241551180-17382/BuildReport?accessString=4ea9200e28f4e3d0a8f5b811b16fc3b429ccadfcffdbe286487c594550b67512).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:49 UTC, opbld33 commented
Docs Build status updates of commit _[9f3775a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f3775ac190cf77587fd81efff082876c7708125)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232246110215-17382/BuildReport?accessString=e0b7dd7102d2f18953365f3e2df367590183d7cb3b9a53316ee4342b867e76f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:51 UTC, opbld34 commented
Docs Build status updates of commit _[0305078](https://github.com/microsoftgraph/microsoft-graph-docs/commits/030507826830ca176adca321c2a4fe09dcc0e0e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232240264800-17382/BuildReport?accessString=661aab4e8805abed86381ecf13c0834b5bd9e4dd3e298a51f7230dc7e37f69fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:54 UTC, opbld30 commented
Docs Build status updates of commit _[49032a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49032a2294914db86b73c9a8bcc83f94d970d98d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) | [Details](#user-content-13bc4a0fb76021e66056a01bd0d5a62a-09169719)
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="13bc4a0fb76021e66056a01bd0d5a62a-09169719"></a>
### [api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md)
 - **Line 246, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232237356178-17382/BuildReport?accessString=b6dcdc9785c8066397d036c1f5da0f5010b99f1b42e3d247d4aa219654b8ee8e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 22:56 UTC, opbld31 commented
Docs Build status updates of commit _[68b607f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68b607fec5f3cb24391ccf712822590bb57d82e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206232244062585-17382/BuildReport?accessString=e7fbec6918b1c05af0f200f9605062b7f60eea8818fd11bec3dc9cf865f096fd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 08:53 UTC, FaithOmbongi approved these changes

2022-06-28 02:31 UTC, opbld32 commented
Docs Build status updates of commit _[42fd5f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42fd5f870e9e92d00052559e66cd1e2bd6bcac27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206280228486519-17382/BuildReport?accessString=fd31394ac138cc5c5b8fe79e70b6f29b3ce810fed22b92e3e01f59d35af9feea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-28 02:33 UTC, opbld31 commented
Docs Build status updates of commit _[753c612](https://github.com/microsoftgraph/microsoft-graph-docs/commits/753c612e1e8d8a6ddf341aefd651c12b1ccc1ed2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronizationlinkedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronizationlinkedobjects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronizationlinkedobjects?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[api-reference/beta/resources/synchronization-synchronizationjobsubject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/api-reference/beta/resources/synchronization-synchronizationjobsubject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/synchronization-synchronizationjobsubject?view=graph-rest-beta&branch=pr-en-us-17382) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ArvindHarinder1-patch-5/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206280229267427-17382/BuildReport?accessString=9e65b8011164ce3c63b1547661bfcfdc8e523017b0c0b0c62e41c75f1509df36).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-28 02:51 UTC, merged