Correction : URL of beta docs and adding docs for update team photo.
microsoftgraph/microsoft-graph-docs pull request #17394
Opened 2022-06-22 08:38 UTC by sumitgupta3

Identified a bug in public documents. 
Expected : Update team photo should point to API related updating the team photo.
Actual : It points to API related to updating profile photo.

Fix : created a new file for missing docs and corrected the link as well.

2022-06-22 11:46 UTC, shantanu1singh requested changes

2022-06-22 11:46 UTC, shantanu1singh commented on api-reference/beta/api/team-update-photo.md
> +|Application | GraphPermissionConstants.TeamSettingsReadWriteAll, GraphPermissionConstants.GroupReadWriteAll, GraphPermissionConstants.DirectoryReadWriteAll |
I think we have started calling out in our docs that people should move away from DirectoryReadWriteAll and GroupReadWriteAll.

See this for reference:
https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#permissionshttps://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#permissions

> **Notes**: 
> Permissions marked with ** are supported only for backward compatibility. We recommend that you update your solutions to use an alternative permission listed in the previous table and avoid using these permissions going forward. Permissions marked with * use [resource-specific consent](/microsoftteams/platform/graph-api/rsc/resource-specific-consent).

2022-06-22 11:46 UTC, shantanu1singh commented on api-reference/beta/api/team-update-photo.md
> +|Application | GraphPermissionConstants.TeamSettingsReadWriteAll, GraphPermissionConstants.GroupReadWriteAll, GraphPermissionConstants.DirectoryReadWriteAll |
You can follow the same model

2022-06-22 11:46 UTC, shantanu1singh commented on api-reference/beta/api/team-update-photo.md
> +PUT https://graph.microsoft.com/beta/teams/{id}/photo/$value
Examples should include sample IDs instead of templates. Let's change {id} to some other random guid

2022-06-23 03:48 UTC, opbld31 commented
Docs Build status updates of commit _[658fe7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/658fe7e37efc21f0ae75504a493dc0ad8b651952)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230346023237-17394/BuildReport?accessString=167ef269b530ec0a47f01d469ddc69747063025d687b91a64c5a71cd3f9080f6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 03:48 UTC, sumitgupta3 commented on api-reference/beta/api/team-update-photo.md
> +|Application | GraphPermissionConstants.TeamSettingsReadWriteAll, GraphPermissionConstants.GroupReadWriteAll, GraphPermissionConstants.DirectoryReadWriteAll |
Thanks for the guidance, sure I have taken care of this now in both beta and v1

2022-06-23 03:57 UTC, opbld30 commented
Docs Build status updates of commit _[7784ebf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7784ebfc2df241ae158a97db694a458db9ca3a0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230354446972-17394/BuildReport?accessString=f23390cb56dee558af6c1686d0ea98a6852e9761ab054831e338178e4e6e3b5d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 04:56 UTC, shantanu1singh commented on api-reference/beta/api/team-update-photo.md
> +>  This API supports admin permissions. Global admins and Microsoft Teams service admins can access teams that they are not a member of.
Do we actually support admin context? I thought you guys found that we don't?

2022-06-23 04:56 UTC, shantanu1singh commented on api-reference/beta/api/team-update-photo.md
> +|Application | TeamSettingsEditGroup*, TeamSettingsReadWriteGroup*, TeamSettingsReadWriteAll, GroupReadWriteAll**, DirectoryReadWriteAll** |
Just double check if application context actually works for this API

2022-07-05 11:33 UTC, sumitgupta3 commented on api-reference/beta/api/team-update-photo.md
> +|Application | TeamSettingsEditGroup*, TeamSettingsReadWriteGroup*, TeamSettingsReadWriteAll, GroupReadWriteAll**, DirectoryReadWriteAll** |
checked application context does not work for this. Will remove it.

2022-07-05 11:34 UTC, sumitgupta3 commented on api-reference/beta/api/team-update-photo.md
> +>  This API supports admin permissions. Global admins and Microsoft Teams service admins can access teams that they are not a member of.
Yeah checked, admin context is supported.

2022-07-05 11:40 UTC, opbld33 commented
Docs Build status updates of commit _[435da14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/435da14ddf2e6ed67582ae3cac2837123c66fbd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051136395941-17394/BuildReport?accessString=eba142639125421846c15bbff94a9a0d7e234ed8dbeba47eeebd5a75ba4f20b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 21:50 UTC, JarbasHorst commented on api-reference/beta/api/team-update-photo.md
> +Binary data of the image.
For consistency and readability, please update the text for the request body to be more descriptive. Suggested revision:

- In the request body, include the binary data of the photo.

2022-07-11 21:50 UTC, JarbasHorst commented on api-reference/beta/api/team-update-photo.md
> +---
The correct filename should be "parententitiyname-put-navigationpropertyname". In this case, please rename this file to

- api-reference/beta/api/team-put-photo.md

After renaming, please update the reference link in the toc.yml file.

2022-07-11 21:50 UTC, JarbasHorst commented on api-reference/beta/api/team-update-photo.md
> +---
Please, include an update to the changelog file to surface this new API in the Microsoft Graph Changelog.

2022-07-11 21:53 UTC, JarbasHorst commented
Hello @sumitgupta3, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [17642](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17642) into your branch to include my fixes and before addressing my new comments.

2022-07-12 01:27 UTC, opbld31 commented
Docs Build status updates of commit _[019544c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/019544c47909c022d355bbf0a324d1c4a806a0b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207120125328259-17394/BuildReport?accessString=eefbc49181844c818db4f36e295d841fdc50abcec6f954cc04f7737393ba5d1f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 07:26 UTC, sumitgupta3 commented on api-reference/beta/api/team-get-photo.md
> +GET https://graph.microsoft.com/beta/teams/172b0cce-e65d-44ce-9a49-91d9f2e8491e/photo
Yes Application context works for Get Team Photo.

2022-07-12 07:39 UTC, sumitgupta3 commented on api-reference/beta/api/team-update-photo.md
> +Binary data of the image.
added

2022-07-12 07:44 UTC, sumitgupta3 commented on api-reference/beta/api/team-update-photo.md
> +---
This is highly inconsistent in our code. 11 places we have "parententitiyname-put-navigationpropertyname" and 9 places  has "parententitiyname-update-navigationpropertyname".   This will always lead o confusion for all. Sometimes update is also made via POST/PATCH calls.  I see update as better option in convention. Think about it and please let me know.

2022-07-12 07:52 UTC, opbld30 commented
Docs Build status updates of commit _[08056e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08056e5d0973656327e0ce679e33d03cbf5572c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-17394) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207120749188444-17394/BuildReport?accessString=25855b7b6b96d60ed131e53d5423cc10e456060280aeb9d0c38af54c2568051f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 08:00 UTC, opbld34 commented
Docs Build status updates of commit _[eabacf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eabacf204e68e342c3b05a484934efd129f16e5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207120758416643-17394/BuildReport?accessString=ba99ece50e1577ba7dd5eeda002c706fc5ccf6113334f1b2fbc8f6a3a90e1e32).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 00:55 UTC, opbld32 commented
Docs Build status updates of commit _[112fea9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/112fea9df6242ea5f93291b2c77d705c5adb0ac3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-get-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-get-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/api/team-update-photo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/fixbeta/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-photo?view=graph-rest-beta&branch=pr-en-us-17394) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130052523376-17394/BuildReport?accessString=a4d3b417a58429d1dbe0a308f089a93342d096d6f7ad4231dd0b44720b81de8c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 07:13 UTC, closed without merging

2022-07-13 07:14 UTC, sumitgupta3 commented
This PR is closed and changes are tracked here : https://github.com/microsoftgraph/microsoft-graph-docs/pull/17241