update CMD onprem connection error code
microsoftgraph/microsoft-graph-docs pull request #17407
Opened 2022-06-23 03:55 UTC by wcchen101

Add new Intune error types

2022-06-23 03:57 UTC, opbld34 commented
Docs Build status updates of commit _[3478859](https://github.com/microsoftgraph/microsoft-graph-docs/commits/347885920d5ddfbe49aae1bf80eacf27e9cfe74f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230355046781-17407/BuildReport?accessString=b9016124a0ede9eddc80ae29713714ddd2d07530523006bd914ddbd2acbe95ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 04:00 UTC, opbld32 commented
Docs Build status updates of commit _[11ac723](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11ac723e538bc10aa2de603695faa66618ccb242)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230358283372-17407/BuildReport?accessString=f3f8471306fc7959d662b6cfd3620e0f872d4ce75ed5c72591cb1a93325eade3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 04:12 UTC, opbld34 commented
Docs Build status updates of commit _[0d60632](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d60632fe77e9b4f0ae55ae22ffbe62292f8191c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230410239566-17407/BuildReport?accessString=dcfff1b0adc3084ad88f26a2e42d910d5d10b325f68d77630868e7a2d7b51b61).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 05:21 UTC, RuiHou105 requested changes
@wcchen101 

1.Please update the `Microsoft.CloudManagedDesktop.json` changelog. It should include all your changes:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/77313233/176598675-c9bc32e7-757f-440f-86f2-0b4e6e0c4bff.png">

2.Please create a roadmap workitem and then attach the workitem number in this PR. Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/12472/

If you don't have access, please do this firstly to gain access:

Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
Join the Microsoft Graph Roadmap Users ([graphroadmap@microsoft.com](mailto:graphroadmap@microsoft.com)) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-07-01 02:48 UTC, opbld32 commented
Docs Build status updates of commit _[683b89a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/683b89a6c6e6d9f22c4f1869df680efe4029105d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207010246105986-17407/BuildReport?accessString=c93469a12aff8563c8cddd60d3e3e67319f350dc4a086cef6dec2aae6567695f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-01 05:01 UTC, AshleyYangSZ approved these changes

2022-07-05 03:05 UTC, RuiHou105 commented
@wcchen101  please create roadmap workitem and attach number in this PR. And then I will approve this PR :)

2022-07-05 04:42 UTC, wcchen101 commented
Roadmap work item Id: 14553

2022-07-05 05:04 UTC, RuiHou105 approved these changes

2022-07-05 05:07 UTC, RuiHou105 commented
@Lauragra , @JarbasHorst , could you please help review it as the graph schema already went alive. Thanks!

2022-07-12 22:28 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckNoIntuneReaderRoleError|Do not have sufficient Intune reader role to check Intune platform restriction settings.|
What does not have sufficient Intune reader role? The Cloud PC? If I understand this error correctly, I think that we can change this description to be:

- "The (subject??? - Cloud PC???) doesn't have sufficient permissions to check the Intune platform restriction settings. Please make sure that the (subject??? - Cloud PC???) has the *Reader (What reader permission exactly?? Cloud PC Reader??)* permissions on Intune.

2022-07-12 22:31 UTC, JarbasHorst commented
Hello @wcchen101, I reviewed your PR and left one comment. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [17662](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17662) into your branch to include my fixes and before addressing my comment.

2022-07-13 00:52 UTC, opbld33 commented
Docs Build status updates of commit _[f900aeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f900aebdd4f1188bc3e8af35e374ef69629ef0f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130050126469-17407/BuildReport?accessString=4fe943580a722c8e250d132143ccb0d1e69d22b04c332bd124f7efd80770a232).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 04:07 UTC, wcchen101 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckNoIntuneReaderRoleError|Do not have sufficient Intune reader role to check Intune platform restriction settings.|
Sure. Updated. Please check it again. Thanks.

2022-07-19 04:14 UTC, opbld33 commented
Docs Build status updates of commit _[76aea49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76aea496815072ecd2862cd9c89185e8ee22a657)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190411591232-17407/BuildReport?accessString=78d5836bf5229673c9c434950afa4778cbb341fd17cb3e37f645e6e2e85bafb6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 20:52 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [17778](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17778) into this branch to include my final edits.

2022-07-20 23:08 UTC, opbld31 commented
Docs Build status updates of commit _[9be2661](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9be266107fbf180f1375e88d1be6ff2e2563ba3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207202306402396-17407/BuildReport?accessString=648c9d106a5d921220429f11f2997fa3736e33c208921a98a55a9a4b3c3902ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 07:54 UTC, RuiHou105 commented
Hi @Lauragra , I see all comments are resolved and you also helped merge @JarbasHorst 's fix into this PR. So could you please help approve this PR as the graph schema already went alive? Thanks :)

2022-08-15 20:09 UTC, Lauragra approved these changes

2022-08-16 03:44 UTC, opbld33 commented
Docs Build status updates of commit _[743d9f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/743d9f9e4d4f36b04c636f3f4f10a59049f66d05)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fb75de9e)

<a id="fb75de9e"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 743d9f9e4d4f36b04c636f3f4f10a59049f66d05 in branch weicc/update-onprem-entity-error-codes of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 35ed234973e8bf920ceef12c86dc67baa3c50612). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160343449404-17407/BuildReport?accessString=e434fc63bddc3db356a9b00a1360340a41c755b5d00aea00d13fd9e28fe9a99c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:48 UTC, opbld33 commented
Docs Build status updates of commit _[41a928d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41a928de4b9a8ac430af73bb91691b3b3d7654e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17407) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-entity-error-codes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160346169078-17407/BuildReport?accessString=65a9e1f9ba4af4d82b1020287b3d05eccdc4eaa925ce62b4f77e6090050f1e73).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:56 UTC, merged