Add startDateTime property to a todoTask
microsoftgraph/microsoft-graph-docs pull request #17410
Opened 2022-06-23 05:32 UTC by avijityadav

2022-06-23 05:34 UTC, opbld30 commented
Docs Build status updates of commit _[62cb8f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62cb8f3d89ba7f22a20474fdd4a9e376c95086b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206230532143085-17410/BuildReport?accessString=e5d5d7fb2e8131892585dc884c7e28a8638053c5468f80bdb6366ffbb3a0fa9c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 14:22 UTC, Danielabom commented on api-reference/beta/api/todotask-update.md
> +|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone that the task is to be started.|
Please consider using the following description: The date and time at which the task is scheduled to start.

2022-06-30 14:23 UTC, Danielabom commented on api-reference/beta/resources/todotask.md
> +|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone that the task is to be started.|
Please consider using the following description: The date and time at which the task is scheduled to start.

2022-07-06 19:50 UTC, opbld32 commented
Docs Build status updates of commit _[20a40d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20a40d179c8774739c868ae39173dd293b2dc409)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207061947562705-17410/BuildReport?accessString=3ba9d1507c992d0c9619282bb8251f59a40012273d555e8b76f937096265ee33).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 20:08 UTC, opbld34 commented
Docs Build status updates of commit _[119a5d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/119a5d1c71d837eb1398ae29f855c951dba1889f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062005315157-17410/BuildReport?accessString=b103288a4badae1dfd406c08f3fddc6c4a43cd816c15381b0c912269507924aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-11 15:35 UTC, Danielabom commented on api-reference/beta/api/todotasklist-post-tasks.md
> +|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date and time at which the task is scheduled to start.|
```suggestion
|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone at which the task is scheduled to start.|
```

2022-07-11 15:35 UTC, Danielabom commented on api-reference/beta/resources/todotask.md
> +|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date and time at which the task is scheduled to start.|
```suggestion
|startDateTime|[dateTimeTimeZone](../resources/datetimetimezone.md)|The date in the specified time zone at which the task is scheduled to start.|
```

2022-07-11 15:37 UTC, Danielabom requested changes
Hi Avijit, please review my suggestions and accept them if you agree. Thanks!

2022-07-11 21:31 UTC, avijityadav commented
@Lauragra , once the changes are approved, please approve it as the code is already deployed ww. Thank!

2022-07-12 05:43 UTC, opbld34 commented
Docs Build status updates of commit _[4ee1f7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ee1f7efc4ccaf4e12b37e3f0f4f4b8018aad7bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207120540378596-17410/BuildReport?accessString=6dab360fc04160bb95077b89cdef66f07bf58daccd674488ad03d21544977db8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[88c68b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88c68b510c98dbc6606bf36b0c817f39538a10ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207120541104494-17410/BuildReport?accessString=b754019ad88392a39dfbbeeb9205965bca294d515f0c6bc53ef51129a52cc8db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 16:07 UTC, opbld30 commented
Docs Build status updates of commit _[a035153](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0351533751c0169aed6d2e659e21f7079a80106)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121605317757-17410/BuildReport?accessString=21d7a778991e57176ab7ca151b69e8df6004b9fce834fbc65540469ef0a45c1c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 18:02 UTC, Danielabom approved these changes
Changes look good. I appreciate your hard work @avijityadav.

2022-07-13 03:50 UTC, opbld30 commented
Docs Build status updates of commit _[5653df2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5653df2e6e83bfc14abf9c5c8bc75477c0ed3864)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130348406964-17410/BuildReport?accessString=daeaf551a9a2fd670b696751d923cf911b10c2f7500da1a4c194e8b9e76e81d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 03:53 UTC, opbld31 commented
Docs Build status updates of commit _[7e5a9b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e5a9b1c8a2b0624aab78777e615713120d4ee04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-17410) (graph-rest-beta) |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-startDateTime/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130349194628-17410/BuildReport?accessString=a5e67b0eee786a95eda6ab76c7d238d6a98d8563e32e1a452e1678504421b270).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 04:17 UTC, merged