Access Reviews | Expose group peer outlier insight and setting models
microsoftgraph/microsoft-graph-docs pull request #17445
Opened 2022-06-24 19:12 UTC by shubhamguptacal

2022-06-24 19:16 UTC, opbld30 commented
Docs Build status updates of commit _[627b7da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/627b7daf91fea6328a30a7641aca2d78519d88e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206241913515357-17445/BuildReport?accessString=8b301c73a4a6da1e904ef8a0f844bde7c6824d2f09fa0ff7826ff6226e7fb879).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 22:04 UTC, opbld30 commented
Docs Build status updates of commit _[aee21c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aee21c45f505e6fc1dc6750940f66d72122493d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206242202538895-17445/BuildReport?accessString=fb0d31b6190d46a9a64f0df63c1f316ef121c3deab68d341f878449926cc32b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-28 20:51 UTC, opbld33 commented
Docs Build status updates of commit _[e399831](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e39983136d5f37b0e6ab9596d7e8c8c207d41dd5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c368da3)

<a id="2c368da3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206282050205227-17445/BuildReport?accessString=f72f5d151a68d4c8ab521098307d341fda649c1a8e379a5b271f7efa27d58693).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-28 21:31 UTC, opbld34 commented
Docs Build status updates of commit _[36b3a41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36b3a4106f441fd9c16ec2922abd5f3e5d693a0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206282128547085-17445/BuildReport?accessString=386b50f2ad75590a7fb29c50a831c61f8e8b9f5fb2cafa7741a1fa08d09f29ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-04 17:56 UTC, FaithOmbongi requested changes
Thank you @shubhamguptacal for your work in this PR. I've left comments for a few fixes + the following:
- groupPeerOutlierRecommendationInsightSettings is the 2nd type that's derived from [accessReviewRecommendationInsightSetting](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewRecommendationInsightSetting?view=graph-rest-beta). Add it to the list of derived types in the 1st paragraph of the accessReviewRecommendationInsightSetting doc - otherwise it's completely undiscoverable.
- membershipOutlierInsight is the 2nd type derived from [governanceInsight](https://docs.microsoft.com/en-us/graph/api/resources/governanceInsight?view=graph-rest-beta). Add it to the list of derived types in the 1st paragraph of the governanceInsight doc - otherwise, it's completely undiscoverable.
- Changelogs - assign the same ID to the changelog objects per file.


**Unclear linkage with access reviews.**
- One thing I don't think comes out clearly in this PR: The relationship between groupPeerOutlierRecommendationInsightSettings and membershipOutlierInsight. Could you clarify how they relate to each other? 
   - How do you configure the object in the accessReviewScheduleSettings object given it doesn't have or inherit any properties? 
   - groupPeerOutlierRecommendationInsightSettings object rolls up to the settings property while membershipOutlierInsight rolls up to the insights nav property in an accessReviewInstanceDecisionItem object. How do these two connect?

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/membershipOutlierInsight.md
> +description: "In the Azure AD access reviews, the membershipOutlierInsight resource represents insights provided to reviewers based on whether a user is a peer outlier w.r.t other group members"
```suggestion
description: "In the Azure AD access reviews, the membershipOutlierInsight resource represents insights provided to reviewers based on whether a user is a peer outlier in relation to other group members."
```

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md
> +The **groupPeerOutlierRecommendationInsightSettings** allows you to configure group peer outlier insights to aid the reviewers to make decisions for an [accessReviewScheduleDefinition](accessreviewsc
```suggestion
The **groupPeerOutlierRecommendationInsightSettings** allows you to configure group peer outlier insights to aid reviewers to make decisions for an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) object.
```

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md
> +description: "In the Azure AD access reviews, the groupPeerOutlierRecommendationInsightSettings represents the settings associated with group peer outlier insights, and that is used to aid reviewers
```suggestion
description: "In the Azure AD access reviews, the groupPeerOutlierRecommendationInsightSettings represents the settings associated with group peer outlier insights, and that is used to aid reviewers to make decisions."
```

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md
> +| :---------------| :---------- | :---------- |
Replace empty table with `None.`

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/membershipOutlierInsight.md
> +Represents an insight provided to reviewers based on whether a user is a peer outlier w.r.t to other group members
```suggestion
Represents an insight provided to reviewers based on whether a user is a peer outlier in relation to other group members.
```

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/membershipOutlierInsight.md
> +| outlierMemberType | outlierMemberType | Indicates the type of outlier member. For ex: user |
Additional fixes:
+ You're missing the two properties inherited from governanceInsight.
+ Properties should be documented in alphabetical order

```suggestion
| memberId | String | Indicates the identifier of the user. |
| containerId | String | Indicates the identifier of the container, for example, a group ID. |
| outlierContainerType | outlierContainerType | Indicates the type of container. The possible values are: `group`, `unknownFutureValue`. |
| outlierMemberType | outlierMemberType | Indicates the type of outlier member. The possible values are: `user`, `unknownFutureValue`. |
```

2022-07-04 17:56 UTC, FaithOmbongi commented on api-reference/beta/resources/membershipOutlierInsight.md
> +}
The stub generated JSON representation is complete as-is
```suggestion
The following is a JSON representation of the resource.
<!-- {
  "blockType": "resource",
  "keyProperty": "id",
  "@odata.type": "microsoft.graph.membershipOutlierInsight",
  "baseType": "microsoft.graph.governanceInsight",
  "openType": false
}
-->
``` json
{
  "@odata.type": "#microsoft.graph.membershipOutlierInsight",
  "id": "String (identifier)",
  "insightCreatedDateTime": "String (timestamp)",
  "memberId": "String",
  "containerId": "String",
  "outlierContainerType": "String",
  "outlierMemberType": "String"
}
```
```

2022-07-04 17:56 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the [membershipOutlierInsight](https://docs.microsoft.com/en-us/graph/api/resources/membershipOutlierInsight?view=graph-rest-beta) resource type. Use this type to conf
Is this complex type really configurable? I thought it's read-only.

If confirmed to be read-only, just remove the second sentence from the changelog description.
```suggestion
          "Description": "Added the [membershipOutlierInsight](https://docs.microsoft.com/en-us/graph/api/resources/membershipOutlierInsight?view=graph-rest-beta) resource type. Use this type to configure insight settings based on the user's last sign-in date and time into a tenant or application.",
```

2022-07-04 17:56 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          "Description": "Added the [groupPeerOutlierRecommendationInsightSettings](https://docs.microsoft.com/en-us/graph/api/resources/groupPeerOutlierRecommendationInsightSettings?view=graph-rest-
```suggestion
          "Description": "Added the [groupPeerOutlierRecommendationInsightSettings](https://docs.microsoft.com/en-us/graph/api/resources/groupPeerOutlierRecommendationInsightSettings?view=graph-rest-beta) resource type. Use this type to configure access review insight settings based on the user's last sign-in date and time into a tenant or application.",
```

2022-07-19 11:33 UTC, FaithOmbongi commented on api-reference/beta/resources/membershipOutlierInsight.md
> +
This API highly likely exposes some methods. Please investigate and document them

2022-08-02 17:42 UTC, opbld30 commented
Docs Build status updates of commit _[ce6b85c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce6b85cc4288873f1b2dd9e52593bbe7487851c8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-75ef6a3b)

<a id="75ef6a3b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021741034736-17445/BuildReport?accessString=369a8782374849c75269b82b5be448b6da8cde279a2f5512f3f8ef482b55ddb3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[e8ad6e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8ad6e437ed25a859b2eea83190a56e14bb39a54)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-76eb8573)

<a id="76eb8573"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021822446033-17445/BuildReport?accessString=23fa293c6c7c6f878d3d34cd28391d151e9f0441c170450236e64076eab24225).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 18:41 UTC, shubhamguptacal commented on api-reference/beta/resources/membershipOutlierInsight.md
> +
At a high level, there’s no CRUD exposed for all three insight models – governanceInsight,userLastSignInsight and memberhipOutlierInsight. The way these models surface up is through the insight navigation property exposed on AccessReviewInstanceDecisionItem resource type : [accessReviewInstanceDecisionItem resource type - Microsoft Graph beta | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta#relationships). Every accessReviewInstanceDecisionItem record has a collection of insights exposed through the “insights” navigation property. A developer can call the List Decisions API and pass in an expand clause for insights which will return a list of insights for all decision items. Here’s an example API call : 

GET /identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinitionId}/instances/{accessReviewInstanceId}/decisions?$expand=insights
{
    "@odata.count": 1,
    "value": [
        {
            "id": "e6cafba0-cbf0-4748-8868-0810c7f4cc06",
            "accessReviewId": "6444d4fd-ab55-4608-8cf9-c6702d172bcc",
            "decision": "NotReviewed",
            "recommendation": "Approve",
            ....
            "insights": [
                {
                    "@odata.type": "#microsoft.graph.userSignInInsight",
                    "id": "00000000-0000-0000-0000-000000000000",
                    "insightCreatedDateTime": null,
                    "lastSignInDateTime": "2022-02-11T09:01:12Z"
                },
                {
                    "@odata.type": "#microsoft.graph.membershipOutlierInsight",
                    "id": "4e431ca4-df85-4d21-871f-77289959560e",
                    "insightCreatedDateTime": "2022-07-21T08:20:22Z",
                    "memberId": "53548fbc-bf77-48db-98e3-929a9c02197d",
                    "containerId": "98f41dad-68d5-42f6-a50f-ddd75c5c5539",
                    "outlierMemberType": "user",
                    "outlierContainerType": "group"
                }
            ]
        }
    ]
}

2022-08-02 20:02 UTC, opbld32 commented
Docs Build status updates of commit _[8883619](https://github.com/microsoftgraph/microsoft-graph-docs/commits/888361973ae05828696d4de22c3f065b89479c9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208022000151487-17445/BuildReport?accessString=6bc91aa8699474417b1d0ecc3bf99a85e7552a815f3ba121e2d7fa8a51d43cb6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 20:05 UTC, shubhamguptacal commented
> Thank you @shubhamguptacal for your work in this PR. I've left comments for a few fixes + the following:
> 
> * groupPeerOutlierRecommendationInsightSettings is the 2nd type that's derived from [accessReviewRecommendationInsightSetting](https://docs.microsoft.com/en-us/graph/api/resources/accessReviewRecommendationInsightSetting?view=graph-rest-beta). Add it to the list of derived types in the 1st paragraph of the accessReviewRecommendationInsightSetting doc - otherwise it's completely undiscoverable.
> * membershipOutlierInsight is the 2nd type derived from [governanceInsight](https://docs.microsoft.com/en-us/graph/api/resources/governanceInsight?view=graph-rest-beta). Add it to the list of derived types in the 1st paragraph of the governanceInsight doc - otherwise, it's completely undiscoverable.
> * membershipOutlierInsight needs two navigation properties - **container** and **member**. This also makes it seem like there are quite a few APIs that membershipOutlierInsight exposes?
>   
>   * If there are APIs exposed by this entity, let's also surface them in the TOC
> * Changelogs - assign the same ID to the changelog objects per file.
> 
> **Unclear linkage with access reviews.**
> 
> * One thing I don't think comes out clearly in this PR: The relationship between groupPeerOutlierRecommendationInsightSettings and membershipOutlierInsight. Could you clarify how they relate to each other?
>   
>   * How do you configure the object in the accessReviewScheduleSettings object given it doesn't have or inherit any properties?
>   * groupPeerOutlierRecommendationInsightSettings object rolls up to the settings property while membershipOutlierInsight rolls up to the insights nav property in an accessReviewInstanceDecisionItem object. How do these two connect?

At a high level, there are two functionalities that we’re exposing with this docs PR :
-	Configure peer outlier insights for access reviews recommendations – This can be done by using the “recommendationInsightSettings” property on the accessReviewScheduleDefinition object
-	Surface up peer outlier insights along with access review instance decision items – This is done by surfacing up the peerOutlierInsight model in the “insights” property on the AccessReviewInstanceDecisionItem object.


At a high level, there are different kinds of recommendation insights that a developer can enable for access review recommendations – userLastSignInRecommendationInsightSetting and groupPeerOutlierRecommendationInsightSetting. When creating a review, a developer can decide what kinds of insights they want to enable for that review. This is done by using the recommendationInsightSetting property. The recommendationInsightSetting property is a collection of insight settings. 

To enable userLastSignIn insight for recommendations, one can specify a payload like this : 

              "recommendationInsightSettings": [
            {
                "odata.type": "#microsoft.graph.userLastSignInRecommendationInsightSettings",
               "signInScope": "tenant",
               "recommendationLookBackDuration": "P30D"
            }
        ]

To enable both userLastSignIn and groupPeerOutlier insights, one can specify a payload like this : 

              "recommendationInsightSettings": [
            {
                "odata.type": "#microsoft.graph.userLastSignInRecommendationInsightSettings",
               "signInScope": "tenant",
               "recommendationLookBackDuration": "P30D"
            },
            {
                "odata.type": "#microsoft.graph.groupPeerOutlierRecommendationInsightSettings"
            }
        ]


At a high level, there’s no CRUD exposed for all three insight models – governanceInsight,userLastSignInsight and memberhipOutlierInsight. The way these models surface up is through the insight navigation property exposed on AccessReviewInstanceDecisionItem resource type : [accessReviewInstanceDecisionItem resource type - Microsoft Graph beta | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitem?view=graph-rest-beta#relationships). Every accessReviewInstanceDecisionItem record has a collection of insights exposed through the “insights” navigation property. A developer can call the List Decisions API and pass in an expand clause for insights which will return a list of insights for all decision items. Here’s an example API call : 

GET /identityGovernance/accessReviews/definitions/{accessReviewScheduleDefinitionId}/instances/{accessReviewInstanceId}/decisions?$expand=insights
{
    "@odata.count": 1,
    "value": [
        {
            "id": "e6cafba0-cbf0-4748-8868-0810c7f4cc06",
            "accessReviewId": "6444d4fd-ab55-4608-8cf9-c6702d172bcc",
            "decision": "NotReviewed",
            "recommendation": "Approve",
            ....
            "insights": [
                {
                    "@odata.type": "#microsoft.graph.userSignInInsight",
                    "id": "00000000-0000-0000-0000-000000000000",
                    "insightCreatedDateTime": null,
                    "lastSignInDateTime": "2022-02-11T09:01:12Z"
                },
                {
                    "@odata.type": "#microsoft.graph.membershipOutlierInsight",
                    "id": "4e431ca4-df85-4d21-871f-77289959560e",
                    "insightCreatedDateTime": "2022-07-21T08:20:22Z",
                    "memberId": "53548fbc-bf77-48db-98e3-929a9c02197d",
                    "containerId": "98f41dad-68d5-42f6-a50f-ddd75c5c5539",
                    "outlierMemberType": "user",
                    "outlierContainerType": "group"
                }
            ]
        }
    ]
}

2022-08-04 20:04 UTC, FaithOmbongi requested changes
Hi @shubhamguptacal - I've left suggestions for minor fixes.

**A suggestion:** Let us show customers how to configure and use these insights. 
+ You can add an example to the Create scheduleDefinition doc. Add an example 5 that has both multi-stage + recommendationInsightSettings (via stageSettings > recommendationInsightsSettings object) configured.
+ Also show an example for how to $expand the insights. You can replace [Example 2 in List decisions](https://docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&tabs=http#example-2-retrieve-all-decision-items-for-which-youre-a-reviewer-and-expand-the-definitions) with one that covers the existing scenario + expands the insights. Then you can explain what you see in the insights. I'd like customers to also see the container and members relationship.

**GAP:** 

I've gone back to the published API.md and I see this URL `https://graph.microsoft.com/beta/identityGovernance/insights/membershipOutlierInsights?$expand=member($select=id,givenName,jobTitle,mail,mobilePhone,preferredLanguage,surname,userPrincipalName)`. So it seems membershipOutlierInsights exposes at least a LIST and a GET operation to get tenant-wide insights. Please add the method docs for these operations. Let us show customers how to use these tenant-wide results.

2022-08-04 20:19 UTC, FaithOmbongi requested changes

2022-08-04 20:19 UTC, FaithOmbongi commented on api-reference/beta/resources/membershipOutlierInsight.md
> +| outlierMemberType | outlierMemberType | Indicates the type of outlier member. The possible values are: `user`, `unknownFutureValue`. |
Let's indicate which ones support $filter. I've only found references for outlierContainerType and outlierMemberType . Pleaase fill the others if they support $filter.
```suggestion
| memberId | String | Indicates the identifier of the user. |
| containerId | String | Indicates the identifier of the container, for example, a group ID. |
| outlierContainerType | outlierContainerType | Indicates the type of container. The possible values are: `group`, `unknownFutureValue`. Supports `$filter` (`eq`). |
| outlierMemberType | outlierMemberType | Indicates the type of outlier member. The possible values are: `user`, `unknownFutureValue`. Supports `$filter` (`eq`). |
```

2022-08-11 17:16 UTC, shubhamguptacal commented on api-reference/beta/resources/membershipOutlierInsight.md
> +| outlierMemberType | outlierMemberType | Indicates the type of outlier member. The possible values are: `user`, `unknownFutureValue`. |
Currently $filter is not supported for any of these properties

2022-08-11 20:59 UTC, opbld32 commented
Docs Build status updates of commit _[3fdbe26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fdbe263d4f93cc3ce7ab9c0386cd876f53ee895)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208112056531242-17445/BuildReport?accessString=9d56cd8d5998548ff40d54ccf156b3a964db62bf3d76df4533b38a5b8275c1d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 21:12 UTC, shubhamguptacal commented
> Hi @shubhamguptacal - I've left suggestions for minor fixes.
> 
> **A suggestion:** Let us show customers how to configure and use these insights.
> 
> * You can add an example to the Create scheduleDefinition doc. Add an example 5 that has both multi-stage + recommendationInsightSettings (via stageSettings > recommendationInsightsSettings object) configured.
> * Also show an example for how to $expand the insights. You can replace [Example 2 in List decisions](https://docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&tabs=http#example-2-retrieve-all-decision-items-for-which-youre-a-reviewer-and-expand-the-definitions) with one that covers the existing scenario + expands the insights. Then you can explain what you see in the insights. I'd like customers to also see the container and members relationship.
> 
> **GAP:**
> 
> I've gone back to the published API.md and I see this URL `https://graph.microsoft.com/beta/identityGovernance/insights/membershipOutlierInsights?$expand=member($select=id,givenName,jobTitle,mail,mobilePhone,preferredLanguage,surname,userPrincipalName)`. So it seems membershipOutlierInsights exposes at least a LIST and a GET operation to get tenant-wide insights. Please add the method docs for these operations. Let us show customers how to use these tenant-wide results.

Hi @FaithOmbongi 

Thanks for your feedback! I've updated the PR based on your feedback. The gap that you listed is an API listed in the API.md file but it's not exposed through the schema at this time(Here's a PR for the schema exposed today : https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6248969). That's why that API is not documented in this PR

2022-08-12 13:18 UTC, opbld32 commented
Docs Build status updates of commit _[384f3a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/384f3a51132a0dc441044aeb1c93b80d9835bdc2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) | [Details](#user-content-4b4cde67ab6990d14f4f235249feffee-ccc6374b)
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="4b4cde67ab6990d14f4f235249feffee-ccc6374b"></a>
### [api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md)
 - **Line 292, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121316193020-17445/BuildReport?accessString=02b39816ee44895e3eff28888b0419834ed0b8c104bcdc814c1139ffb29a1803).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 13:35 UTC, opbld34 commented
Docs Build status updates of commit _[cfd120d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfd120d091ee16f741d81a4fd4a449e76f03e693)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) | [Details](#user-content-4b4cde67ab6990d14f4f235249feffee-72ddb6b8)
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="4b4cde67ab6990d14f4f235249feffee-72ddb6b8"></a>
### [api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md)
 - **Line 292, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121332409332-17445/BuildReport?accessString=615440bd926b7bcaed7cdc5765c8a7ba4faffb21fa1c0395acff640a24aa695a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 13:48 UTC, opbld32 commented
Docs Build status updates of commit _[6f1ca03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f1ca031bd6c3f10484f9b00d06288b352908423)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121345371024-17445/BuildReport?accessString=60312e2b25486a3a790988a8427ac8c79f843bebda3d5c944927c09247c083fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 19:45 UTC, opbld31 commented
Docs Build status updates of commit _[418c4a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/418c4a553a55c2dc5b837b251bf383246404edf3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208221941442537-17445/BuildReport?accessString=c7ca28701edf1ff1e897f2ea46a704b268839e6e92b4a6b1c67275654c81b1f8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 13:40 UTC, FaithOmbongi approved these changes
Hi @shubhamguptacal  - Approving this PR as the actual content review is complete. I think the only pending thing was resolving the bug that affected the use of groupPeerOutlierRecommendationInsightSetting.

Feel free to push this PR to the merge queue is the bug has been resolved.

2022-08-25 13:43 UTC, opbld34 commented
Docs Build status updates of commit _[e4fe154](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4fe154f4171f553556c1c66096fe8f9de05d90a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251341444024-17445/BuildReport?accessString=dd1e80d777b6bd2e604e15ac808a88933ba80c60f2ffd3b58ca632c0d6c892ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 02:19 UTC, opbld31 commented
Docs Build status updates of commit _[14ae514](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14ae51494c1d50f0ea2687c7c260cd1e861ec185)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300216576182-17445/BuildReport?accessString=663bdc3264a98a2eb6d2cd56c2a001c468573eed34dc960054bd66c01ed61b78).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 02:21 UTC, opbld32 commented
Docs Build status updates of commit _[ab8201b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab8201be9eb4662c1631cafa2b54e17beb343777)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewinstance-list-decisions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewinstance-list-decisions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewinstance-list-decisions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/api/accessreviewset-post-definitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/governanceinsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/governanceinsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/governanceinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/grouppeeroutlierrecommendationinsightsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/grouppeeroutlierrecommendationinsightsettings?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/membershipOutlierInsight.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/membershipOutlierInsight.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membershipoutlierinsight?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/api-reference/beta/resources/userlastsignInrecommendationinsightsetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userlastsigninrecommendationinsightsetting?view=graph-rest-beta&branch=pr-en-us-17445) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/arpeeroutlier/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300218230967-17445/BuildReport?accessString=e7b5df2865c05a24d87b479b2ba4f594808ccb253f87cd12a9abe6a51fb7ffa1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 02:24 UTC, merged