Add link to samples in TOC
microsoftgraph/microsoft-graph-docs pull request #17508
Opened 2022-06-29 19:09 UTC by jasonjoh

2022-06-29 19:14 UTC, opbld33 commented
Docs Build status updates of commit _[9410881](https://github.com/microsoftgraph/microsoft-graph-docs/commits/941088196ab893ccf206f9fe5c568e3364406bf1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jasonjoh-samples-toc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-17508) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202206291912077544-17508/BuildReport?accessString=7ec659fee2cb4bf67ebf09e0db9b168990ea35f2e85ad9d9a591da29cc15feac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-29 20:50 UTC, jasonjoh commented
@angelgolfer-ms Steve and I wanted to try adding a samples link in the TOC. Take a look at where I put it and let me know if you think there's a better place for it.

2022-06-30 02:44 UTC, Lauragra commented on concepts/toc.yml
> +      - name: Samples
I'm not sure if this is the right location to surface this, since this is the "Explore" part of the user journey. Do we think that the point when they will want to browse samples would be the "Develop" part of the journey? In which case, we would add this link somewhere in the Develop section. Also, it does take them out of the context of the docs. with no easy way back, so we might not want to send them away at this point in their journey through the docs.

2022-06-30 07:38 UTC, angelgolfer-ms commented on concepts/toc.yml
> +      - name: Samples
+1 - similar opinion as Laura's regarding the location of the new TOC item "Samples". Let's not break the developer's journey laid out as Explore -> Learn -> Develop.

Related is the use of the term "Tutorials", even though the original purpose of this PR is not about that TOC node. Please see my next comment.

2022-06-30 08:11 UTC, angelgolfer-ms commented on concepts/toc.yml
>            - name: TypeScript
This comment applies to line 35, regarding the developer's journey.

In the "Explore" section, can we qualify the node "Tutorials" as "Getting-started tutorials" or some other term we can brainstorm on, to better differentiate this set of content with Quick start? Doesn't seem to me at the TOC label level we're clearly differentiating between "Quiek start" and these tutorials.

In general, the term tutorials is not limited to the getting started "Explore" stage, but applicable to the "Learn" stage as well. We know there's a need to group and better expose existing tutorial-type content for discovery. That would also encourage API producers to grow this content type. However, to-date, we haven't done that partly because the "Tutorials" node is used in the "Explore" section.

2022-06-30 08:11 UTC, angelgolfer-ms requested changes
Please see my comments. Thanks.

2022-07-01 13:50 UTC, jasonjoh commented on concepts/toc.yml
>            - name: TypeScript
How do you feel about "Build your first app"?

2022-07-01 13:53 UTC, jasonjoh commented on concepts/toc.yml
> +      - name: Samples
If we push this down into the Develop node, we sort of lose what we were trying to do :D. Essentially we're seeing two things: 

- No one is clicking the "Code Samples" link in the top nav bar.
- Said link goes to the samples browser with no filters, so it's not just Graph samples.

The hypothesis that @SteveWilkins1123 and I had was that folks aren't looking to that top-level nav because it's too generic, and that the TOC gets more eyes on.

2022-07-01 18:55 UTC, Lauragra commented on concepts/toc.yml
> +      - name: Samples
The Develop section in the reference TOCs is a little less consolidated, what if you add an entry there (in addition to in the concepts TOC but it will be more buried there), something like "Explore samples", next to Use SDKs, Use the toolkit?
<img width="209" alt="image" src="https://user-images.githubusercontent.com/8648854/176954341-fd2e629d-b7e9-428c-a2e3-f14ae84c4990.png">

2023-04-14 13:24 UTC, closed without merging