Add enableMemAutoEnroll property
microsoftgraph/microsoft-graph-docs pull request #17551
Opened 2022-07-04 06:08 UTC by Litersam

2022-07-04 06:12 UTC, opbld31 commented
Docs Build status updates of commit _[cfc7416](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfc7416a2784274583fcbd8c96ce8824ce2fcd4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207040610285152-17551/BuildReport?accessString=6b02969e58b5328c909454b4a3710b9e23afe7df2360b582012da851900f1892).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 03:50 UTC, opbld31 commented
Docs Build status updates of commit _[d8bc10a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8bc10a9bf9312fa82735b6a1dd481ee395a8826)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050348300325-17551/BuildReport?accessString=e6811e5d6283b0240de893cf20316c8decb9deff406963afd7f4b73c79fba1b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 04:16 UTC, opbld34 commented
Docs Build status updates of commit _[3e65e17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e65e1705f7c7917a4c12f25ff209d09b968bf91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050407487743-17551/BuildReport?accessString=e1cf5c08d8f52432e7ed456a4c0641e338b3286ddec73aa14888fc367a5fe5dc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 05:45 UTC, opbld31 commented
Docs Build status updates of commit _[c9c1ad7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9c1ad74ad0eb4a4dd74fcb66987757b85fcf53e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050541340924-17551/BuildReport?accessString=130f4dc585967f30270344ab2e525937081854701aac541192b5762c6f961168).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 05:49 UTC, opbld34 commented
Docs Build status updates of commit _[8549644](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85496444a5f15b47f506211d2f203a70b0a8dab2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050547103698-17551/BuildReport?accessString=16501822fbfae1d0298f79f7a07c7d2c4a02e77cbba0a562fcbe7cc1d14bb281).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 07:17 UTC, opbld33 commented
Docs Build status updates of commit _[fc34c5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc34c5a663ab67d7ab01b19cddceffc0411579e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050715406268-17551/BuildReport?accessString=9cc17a39f2ad299a56bac12d6b01b36970959daba7be635480af789d97fd7a1f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 07:45 UTC, opbld34 commented
Docs Build status updates of commit _[093c10f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/093c10f45e025500c97f9d5e9bf47836814de1d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207050743133865-17551/BuildReport?accessString=1adc27f5885deb30f147d406099f7eba385f9e229bad2202a90a864fd672b401).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-05 10:12 UTC, opbld33 commented
Docs Build status updates of commit _[1339404](https://github.com/microsoftgraph/microsoft-graph-docs/commits/133940418e106051e693ced45f810df9a2711adb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207051009455115-17551/BuildReport?accessString=cb24afb2e102f229946b664557c88351fe99b225ac24d068a6373fd8ba7d4672).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 07:32 UTC, AshleyYangSZ commented
Please create a roadmap worktem and then attach the workitem number in this PR. Here is an example: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/

If you don't have access, please do this firstly:

Request access via [Improved ADO Access - 1ES Wikirequest to join](https://www.1eswiki.com/wiki/Improved_ADO_Access) .
Join the Microsoft Graph Roadmap Users ([[[1]](mailto:graphroadmap@microsoft.com%7Cgraphroadmap@microsoft.com)]) security group on [idweb](https://idwebelements/GroupManagement.aspx?Group=graphroadmap&Operation=join) .

2022-07-11 03:21 UTC, AshleyYangSZ approved these changes

2022-07-11 03:45 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpcorganizationsettings.md
> +|enableMEMAutoEnroll|Boolean|Specifies whether new Cloud PCs will be automatically enrolled in Microsoft Endpoint Manager(MEM). The default value is `false`.|
One convention for graph public doc is: we'd better sort the properties alphabetically. So here in this table, please place the new property before` id`. Thanks.

2022-07-11 03:47 UTC, RuiHou105 requested changes
Left a minor comment. Please help resolve. Thanks.

2022-07-11 06:27 UTC, opbld33 commented
Docs Build status updates of commit _[c571fa8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c571fa8e586e6ec76698ffe5743927ea160df3a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207110625007921-17551/BuildReport?accessString=db30033a284c8e06f449a56ace65fae71e69936731326ddc5cbdb8ea449050df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 02:50 UTC, RuiHou105 approved these changes

2022-07-15 15:02 UTC, isvargasmsft commented
Hi @RuiHou105, @AshleyYangSZ what is the status of this PR? Is it ready for review? I noticed you removed the "ready for content review" label.

2022-07-19 07:01 UTC, AshleyYangSZ commented
> Hi @RuiHou105, @AshleyYangSZ what is the status of this PR? Is it ready for review? I noticed you removed the "ready for content review" label.

Hi @isvargasmsft this change doesn't go alive now, it's still bake in our testing env. Not sure shall we start review now or after the schema reach prod?

2022-07-19 20:28 UTC, isvargasmsft commented
> > Hi @RuiHou105, @AshleyYangSZ what is the status of this PR? Is it ready for review? I noticed you removed the "ready for content review" label.
> 
> Hi @isvargasmsft this change doesn't go alive now, it's still bake in our testing env. Not sure shall we start review now or after the schema reach prod?

@AshleyYangSZ we can start once you have an schema PR approved :)

2022-08-01 01:21 UTC, Guoan-Tang requested changes
cloudpcorganizationsettings-get.md should be update too

2022-08-04 07:12 UTC, Litersam commented
Already updated.

2022-08-04 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[c571fa8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c571fa8e586e6ec76698ffe5743927ea160df3a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208040712335551-17551/BuildReport?accessString=210b463ab3ce372d4893cc934bcf860ef650a0e233bcafc529622984ef68fa79).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 07:15 UTC, Litersam commented
> cloudpcorganizationsettings-get.md should be update too

Already updated.

2022-08-05 02:49 UTC, Guoan-Tang approved these changes

2022-08-05 03:02 UTC, Litersam commented
roadmap work item:
14794 [DEVICES AND APPS][CLOUD PC] Add auto enroll MEM property to organizationSettings
https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14794

2022-08-12 18:46 UTC, isvargasmsft approved these changes

2022-08-15 07:59 UTC, RuiHou105 commented
Hi @Lauragra , this PR is ready for final review and the graph schema already went alive. So please help review/ approve it when you got time. Thanks!

2022-08-16 04:00 UTC, opbld33 commented
Docs Build status updates of commit _[6ce248b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ce248b2f3e5cb068bbb844ac1bffd69ac7daf80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcorganizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-get?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/api/cloudpcorganizationsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/api/cloudpcorganizationsettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcorganizationsettings-update?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcorganizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/api-reference/beta/resources/cloudpcorganizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcorganizationsettings?view=graph-rest-beta&branch=pr-en-us-17551) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/qiqi/add-autoEnrollMem/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160358238195-17551/BuildReport?accessString=806146a71b9bc56ce50221d07707e4384d343313991b3c279ed92f01c39e8cb5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 04:05 UTC, merged