Cloud Site List Management API Docs
microsoftgraph/microsoft-graph-docs pull request #17566
Opened 2022-07-05 16:50 UTC by edward-day-vii

This PR is the documentation for the upcoming Cloud Site List Management Graph APIs.

2022-07-05 16:53 UTC, opbld32 commented
Docs Build status updates of commit _[f3893ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3893ae2c1629fddbcd05fc086af8c5f33317228)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-2c8b8f3d90c93fdd3317abf8b1f899f9-c8e1f7fc)
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-809bf309b2c03796aee7531bf47fe9ce-c8e1f7fc)
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-ce179c0e1daebd544eefbabc7766b78d-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-92552a2893c1f2cfab05beefd31b79f3-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-686ad2eeedc5cc9887217bad37f098aa-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-8f5a705f4b512306b3e56ee5d7c4940d-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-312573adbdc58d296cb9e50910d5ca87-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-57be0a56ac36c6424793f6d539472b73-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-39929447cb6b8f28f5934c2f557259d2-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-c1d757e34522537f5b2933aed83333d9-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-f4a74679a3e4edec42a894937ab49ed4-c8e1f7fc)
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-1936f163adf7a5015dfefd4bb58e9791-c8e1f7fc)
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-f119bf231d3997f1061aa309c9a845e5-c8e1f7fc)
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-c7b63efe88301f09dcaedd7d08f3d9e0-c8e1f7fc)
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-892bfcdb507993120e79c9232f1ad869-c8e1f7fc)
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-e9cfc9a48683ad3bbcfe1a0d7c736f68-c8e1f7fc)
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-3ebbd9fe2cda83219eb0bd62393e08a8-c8e1f7fc)
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :warning:Warning | [View](https://r [...]

2022-07-05 17:25 UTC, opbld30 commented
Docs Build status updates of commit _[8186e22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8186e22c87225658adb2531a8aaa7a9405b0466e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-f69b46c0)
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https:/ [...]

2022-07-05 17:29 UTC, opbld33 commented
Docs Build status updates of commit _[b839363](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b839363d28afb84d3c246a18223a861fca6af78b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersitehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitelist.md](https: [...]

2022-07-05 18:37 UTC, opbld34 commented
Docs Build status updates of commit _[c1175eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1175eb14fdaf8324e235b1894b1b7e8ee3aca27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersitehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitelist.md](https: [...]

2022-07-05 18:50 UTC, opbld33 commented
Docs Build status updates of commit _[cf08d8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf08d8c90132ea0332d6bf8f522edc650eef8c43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersitehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitelist.md](https: [...]

2022-07-05 19:10 UTC, opbld30 commented
Docs Build status updates of commit _[052c12b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/052c12b422de32b4373b44f80d6655df25f93e8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersitehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitelist.md](https: [...]

2022-07-05 19:15 UTC, opbld31 commented
Docs Build status updates of commit _[52e5528](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52e552864c58b5afd82b1801978e21a41e945583)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersitehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitelist.md](https: [...]

2022-07-05 19:35 UTC, opbld33 commented
Docs Build status updates of commit _[5b88c01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b88c0144cdbc1910e70b80be684d061e962ea3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsof [...]

2022-07-06 15:09 UTC, thanhtruongmsft commented
Do we need add "Overview"?

2022-07-06 15:11 UTC, edward-day-vii commented
>

2022-07-06 15:15 UTC, opbld30 commented
Docs Build status updates of commit _[5b88c01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b88c0144cdbc1910e70b80be684d061e962ea3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsof [...]

2022-07-06 15:28 UTC, thanhtruongmsft commented on api-reference/v1.0/resources/browsersharedcookie.md
> +|[Update browserSharedCookie](../api/browsersharedcookie-update.md)|[browserSharedCookie](../resources/browsersharedcookie.md)|Update the properties of a [browserSharedCookie](../resources/browsersha
Does the method return data?

2022-07-11 14:49 UTC, edward-day-vii commented on api-reference/v1.0/resources/browsersharedcookie.md
> +|[Update browserSharedCookie](../api/browsersharedcookie-update.md)|[browserSharedCookie](../resources/browsersharedcookie.md)|Update the properties of a [browserSharedCookie](../resources/browsersha
Fixed

2022-07-11 14:54 UTC, opbld30 commented
Docs Build status updates of commit _[da105ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da105accf75b304af5dc6fdc00b291d5e69c49bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-11 15:29 UTC, thanhtruongmsft requested changes

2022-07-11 15:29 UTC, thanhtruongmsft commented on api-reference/beta/api/browsersitelist-update.md
> +If successful, this method returns a `200 OK` response code and an updated [browserSiteList](../resources/browsersitelist.md) object in the response body.
Returning 204 - no content?

2022-07-11 15:29 UTC, thanhtruongmsft commented on api-reference/beta/api/browsersite-update.md
> +If successful, this method returns a `200 OK` response code and an updated [browserSite](../resources/browsersite.md) object in the response body.
204 no-content

2022-07-11 15:29 UTC, thanhtruongmsft commented on api-reference/beta/resources/browsersite.md
> +|[Update browserSite](../api/browsersite-update.md)|[browserSite](../resources/browsersite.md)|Update the properties of a [browserSite](../resources/browsersite.md) object.|
Return no-content

2022-07-11 15:29 UTC, thanhtruongmsft commented on api-reference/beta/resources/browsersitelist.md
> +|[Update browserSiteList](../api/browsersitelist-update.md)|[browserSiteList](../resources/browsersitelist.md)|Update the properties of a [browserSiteList](../resources/browsersitelist.md) object.|
Return no-content

2022-07-11 16:08 UTC, edward-day-vii commented on api-reference/beta/api/browsersite-update.md
> +If successful, this method returns a `200 OK` response code and an updated [browserSite](../resources/browsersite.md) object in the response body.
Updated

2022-07-11 16:08 UTC, edward-day-vii commented on api-reference/beta/api/browsersharedcookie-update.md
> +|hostOrDomain|String|The URL of the cookie. Required.|
Updated

2022-07-11 16:08 UTC, opbld32 commented
Docs Build status updates of commit _[7a27869](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a2786944068e6b6ed614c70b55e227d48c676ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-11 16:09 UTC, edward-day-vii commented on api-reference/beta/resources/browsersitelist.md
> +|[Update browserSiteList](../api/browsersitelist-update.md)|[browserSiteList](../resources/browsersitelist.md)|Update the properties of a [browserSiteList](../resources/browsersitelist.md) object.|
Updated

2022-07-11 16:09 UTC, edward-day-vii commented on api-reference/beta/resources/browsersite.md
> +|[Update browserSite](../api/browsersite-update.md)|[browserSite](../resources/browsersite.md)|Update the properties of a [browserSite](../resources/browsersite.md) object.|
Updated

2022-07-11 16:14 UTC, thanhtruongmsft approved these changes

2022-07-13 13:24 UTC, opbld32 commented
Docs Build status updates of commit _[8acc8ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8acc8ba3ed060a788f95438a4cb3b781f48754e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-20 18:50 UTC, opbld34 commented
Docs Build status updates of commit _[68c92c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68c92c37227314114611a950fe190869487abd94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersharedcookie-update.md
> +In the request body, supply the values for relevant fields that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated
For consistency, please replace this paragraph with the following boilerplate:

- \[!INCLUDE \[table-intro\](../../includes/update-property-table-intro.md)\]

Please, apply this change also here:
- api-reference/beta/api/browsersite-update.md
- api-reference/beta/api/browsersitelist-update.md

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersharedcookie-update.md
> +If successful, this method returns a `204 No Content` response code and an updated [browserSharedCookie](../resources/browsersharedcookie.md) object in the response body.
I think this text is wrong because the 204 response code will not return any response body. If the response code is correct, then you can remove the second sentence. Suggested revision:

- If successful, this method returns a \`204 No Content\` response code.

Please, apply this change also here:
- api-reference/beta/api/browsersite-update.md
- api-reference/beta/api/browsersitelist-update.md

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersite-get.md
> +Read the properties and relationships of a [browserSite](../resources/browsersite.md) object.
For clarity, I recommend you to rephrase this sentence. Suggested revision:

- Get a \[browserSite\](../resources/browsersite.md) that is in \[Internet Explorer mode\](/deployedge/edge-ie-mode).

Please, use this description also in line 3. In case of line 3, you don't have to add the reference links.

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersharedcookie-update.md
> +
In the following example, please replace "micrsoftEdge" with "microsoftEdge"

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersharedcookie-update.md
> +|hostOrDomain|String|The URL of the cookie.|
GLOBAL: For consistency and to improve scanning, properties in a table should be in alphabetical order. Please, alphabetize the list.

Please, apply this change also here:
- api-reference/beta/api/browsersite-update.md
- api-reference/beta/api/browsersitelist-post-sharedcookies.md
- api-reference/beta/api/browsersitelist-post-sites.md
- api-reference/beta/api/browsersitelist-publish.md

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersite-update.md
> +|allowRedirect|Boolean|Boolean attribute that controls the behavior of redirected sites.|
Does this property control whether sites can be redirected? If yes, I recommend the following revision for this description:

- If \`true\`, indicates that a site can be redirected to...

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersitelist-delete-sharedcookies.md
> +
For simplicity, I recommend the following revision for the last sentence:

- You must publish the shared cookie to fully remove it from the site list.

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersitelist-delete-sharedcookies.md
> +#### Response
For clarity, I recommend the following revision for the last sentence:

- The following is an example of the response where the status has changed to 
\`pendingDelete\` but the shared cookie is still published. You must publish the shared cookie to fully remove it from the site list.

2022-07-28 22:58 UTC, JarbasHorst commented on api-reference/beta/api/browsersitelist-delete-sharedcookies.md
> +
For clarity, I recommend you to add more details to this description. Suggested revision:

- Delete a \[browserSharedCookie\](../resources/browsersharedcookie.md) from the site list.

Please, use this description also in line 3. In case of line 3, you don't have to add the reference link.

2022-07-28 23:00 UTC, JarbasHorst commented
Hello @edward-day-vii, I reviewed your PR and left some comments. Please, take a look when you will have time.

**Also, to avoid merge conflicts, please merge PR [17896](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17896) into your branch to include my fixes and before addressing my comments.**

Can you please replace the label "ready for content review" with "content review in progress"? Thanks!

2022-07-29 13:32 UTC, opbld33 commented
Docs Build status updates of commit _[7478108](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7478108cd21cd5bf691d68bdd2e4a586b6ba1c19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-29 20:35 UTC, opbld31 commented
Docs Build status updates of commit _[42178f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42178f6ca97ffb0c5f3ab86db13ac73989694a02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-29 20:54 UTC, edward-day-vii commented on api-reference/beta/api/browsersite-get.md
> +Read the properties and relationships of a [browserSite](../resources/browsersite.md) object.
Where should the link /deployedge/edge-ie-mode go? I don't see any page in the current docs with that name. Should we link to our application official docs here: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt?

2022-07-29 20:54 UTC, edward-day-vii commented on api-reference/beta/api/browsersite-update.md
> +|allowRedirect|Boolean|Boolean attribute that controls the behavior of redirected sites.|
I added a little more description about what this field means.

2022-07-29 20:56 UTC, edward-day-vii commented on api-reference/beta/api/browsersitelist-delete-sharedcookies.md
> +#### Response
perfect, I updated this for the delete site as well.

2022-07-29 21:00 UTC, opbld33 commented
Docs Build status updates of commit _[3a3dc9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a3dc9e1c1999cf83b8edf516ddf1da95918d222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-29 21:03 UTC, opbld31 commented
Docs Build status updates of commit _[2631ba2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2631ba27ac956d581f9e6e54d300925634b865c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-07-30 17:18 UTC, edward-day-vii commented on api-reference/beta/api/browsersite-get.md
> +Read the properties and relationships of a [browserSite](../resources/browsersite.md) object.
I see, it looks like we want to link to this page: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode.

2022-08-01 15:14 UTC, opbld31 commented
Docs Build status updates of commit _[da6e80b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da6e80bb221357d144f1c5f2fa3c72ed69c3f017)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-f7591cf1)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-f7591cf1)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[ap [...]

2022-08-01 21:18 UTC, JarbasHorst commented on api-reference/beta/api/browsersite-get.md
> +Read the properties and relationships of a [browserSite](../resources/browsersite.md) object.
Yes, the link should go to this page: https://docs.microsoft.com/en-us/deployedge/edge-ie-mode. In our documentation, we just use relative links. Absolute links can broken in isolated environments.

2022-08-01 23:27 UTC, JarbasHorst commented on api-reference/beta/resources/browsersharedcookie.md
> +  "id": "String (identifier)",
GLOBAL: Please show the properties here in alphabetical order. You don't need to change the position of @odata.type…

Please, apply this change to all resource topics in your PR.

2022-08-01 23:27 UTC, JarbasHorst commented on api-reference/beta/resources/browsersite.md
> +description: "Represents a IE mode site that resides on a site list."
For clarity, I recommend the following revision:

- Represents a site to use in Internet Explorer mode that resides on a site list.

2022-08-01 23:27 UTC, JarbasHorst commented on api-reference/beta/resources/browsersite.md
> +A `browserSite` represents a IE mode site that resides on a site list.
For clarity, I recommend the following revision:

- Represents a site to use in \[Internet Explorer mode\](/deployedge/edge-ie-mode) that resides on a \[site list\](../resources/browsersitelist.md).

2022-08-01 23:27 UTC, JarbasHorst commented on api-reference/beta/api/browsersitelist-delete-sharedcookies.md
> +
In the last sentence, please add a reference link to the publish API topic. Suggested revision:

- You must publish (for example, via the \[browserSiteList: publish\](../api/browsersitelist-publish.md) API) the shared cookie to fully remove it from the site list.

Please, apply this change also here:
- api-reference/beta/api/browsersitelist-delete-sites.md

2022-08-01 23:27 UTC, JarbasHorst commented
Hi @edward-day-vii, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time. I will continue with the content review work tomorrow.

Also, to avoid merge conflicts, please merge PR [17914](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17914) into your branch to include my fixes and before addressing my new comments.

2022-08-02 02:24 UTC, opbld34 commented
Docs Build status updates of commit _[b13cc84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b13cc84134d33cd6f783818d05a73e3cded3abfa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-08-02 13:11 UTC, edward-day-vii commented on api-reference/beta/api/browsersite-get.md
> +Read the properties and relationships of a [browserSite](../resources/browsersite.md) object.
Got it, I tried the relative link and it broke the build pipeline. It gave me `Broken links written as relative paths are included in the above build report`. Since the `/deployedge/edge-ie-mode` is not inside this repo, is there something special I need to do? Or do I just include the relative link anyways and it will be fixed when it gets fully deployed?

2022-08-02 14:59 UTC, edward-day-vii commented on api-reference/beta/api/browsersite-get.md
> +Read the properties and relationships of a [browserSite](../resources/browsersite.md) object.
I see, it looks like I can just ignore that warning.

2022-08-02 16:22 UTC, edward-day-vii commented on api-reference/beta/api/browsersharedcookie-update.md
> +|Delegated (work or school account)|BrowserSiteLists.ReadWrite.All|
Our permissions are still in the process of being rolled out. Should we go ahead and update the docs, or wait until that process is complete?

2022-08-02 16:51 UTC, edward-day-vii commented on api-reference/beta/api/browsersitelist-publish.md
> +
Yes it does, good catch. I will check the other files as well.

2022-08-02 17:17 UTC, opbld30 commented
Docs Build status updates of commit _[ff1d024](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff1d0245e035c691990c34e1b3e4c9f3b8fb9834)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-08-02 21:51 UTC, JarbasHorst commented on api-reference/beta/api/browsersharedcookie-update.md
> +|Delegated (work or school account)|BrowserSiteLists.ReadWrite.All|
Hi @edward-day-vii, please go ahead and document the new permissions. I will contact you via email with details.

2022-08-02 23:40 UTC, JarbasHorst commented
Hi @edward-day-vii, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [17925](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17925) into your branch to include my fixes and before addressing my new comments.

2022-08-03 01:26 UTC, opbld30 commented
Docs Build status updates of commit _[c6dd306](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6dd306d405e190865764735bf5cb952de2ba68b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersitehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ed [...]

2022-08-03 21:40 UTC, JarbasHorst commented
Hi @edward-day-vii, I checked your PR again and fixed the position of the TOC items because they should be surfaced under the Sites and lists node. Also, the relative links to https://docs.microsoft.com/deployedge/edge-ie-mode should be correct but the API Doctor can't validate them. For now, I have replaced all relative URLs with absolute URLs. I hope this will at least fix those API Doctor errors. 

Please, take a look at the existing comments when you will have time.

2022-08-03 21:42 UTC, JarbasHorst commented on api-reference/beta/api/browsersharedcookie-update.md
> +|Delegated (work or school account)|BrowserSiteLists.ReadWrite.All|
> Readding this comment so it won't get lost.

Hi @edward-day-vii, please go ahead and document the new permissions. I will contact you via email with details.

2022-08-04 03:40 UTC, opbld32 commented
Docs Build status updates of commit _[217f384](https://github.com/microsoftgraph/microsoft-graph-docs/commits/217f3842deea709ba4ac75bfad62d19ae4389228)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bbe95ff4)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-bbe95ff4)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-bbe95ff4)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d78548160635aa0a6b0afb391aa02029-bbe95ff4)
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d4871ba93dcc65e10616b7e7955295e1-bbe95ff4)
[api-reference/beta/resources/browsersitelist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersitelist.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitelist?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-158108636861f76cbd2d02ce6fef7160-bbe95ff4)
[api-reference/beta/resources/edge.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/edge.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/edge?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9d8c4cef23dab8679ee0b3cc1042e6f1-bbe95ff4)
[api-reference/beta/resources/internetexplorermode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/internetexplorermode.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internetexplorermode?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4447fb03fed8f4d26a9170fe76d7d52d-bbe95ff4)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-upda [...]

2022-08-09 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[6946e49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6946e4919c79f3ea251852ce46a62f36efd309cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-0c8c75f1)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-0c8c75f1)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d78548160635aa0a6b0afb391aa02029-0c8c75f1)
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d4871ba93dcc65e10616b7e7955295e1-0c8c75f1)
[api-reference/beta/resources/browsersitelist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersitelist.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitelist?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-158108636861f76cbd2d02ce6fef7160-0c8c75f1)
[api-reference/beta/resources/edge.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/edge.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/edge?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9d8c4cef23dab8679ee0b3cc1042e6f1-0c8c75f1)
[api-reference/beta/resources/internetexplorermode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/internetexplorermode.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internetexplorermode?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4447fb03fed8f4d26a9170fe76d7d52d-0c8c75f1)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplore [...]

2022-08-09 02:48 UTC, opbld31 commented
Docs Build status updates of commit _[4eda4fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4eda4fc3aecfc8700223eced4998fc7b8a58a239)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-13cf1846)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d78548160635aa0a6b0afb391aa02029-13cf1846)
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d4871ba93dcc65e10616b7e7955295e1-13cf1846)
[api-reference/beta/resources/browsersitelist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersitelist.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitelist?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-158108636861f76cbd2d02ce6fef7160-13cf1846)
[api-reference/beta/resources/edge.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/edge.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/edge?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9d8c4cef23dab8679ee0b3cc1042e6f1-13cf1846)
[api-reference/beta/resources/internetexplorermode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/internetexplorermode.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internetexplorermode?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4447fb03fed8f4d26a9170fe76d7d52d-13cf1846)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded [...]

2022-08-09 02:51 UTC, opbld31 commented
Docs Build status updates of commit _[6a51b2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a51b2cffa0b6443351b0a164779728b6460b0ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d4871ba93dcc65e10616b7e7955295e1-44b01773)
[api-reference/beta/resources/browsersitelist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersitelist.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersitelist?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-158108636861f76cbd2d02ce6fef7160-44b01773)
[api-reference/beta/resources/edge.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/edge.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/edge?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9d8c4cef23dab8679ee0b3cc1042e6f1-44b01773)
[api-reference/beta/resources/internetexplorermode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/internetexplorermode.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internetexplorermode?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4447fb03fed8f4d26a9170fe76d7d52d-44b01773)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-pos [...]

2022-08-09 02:53 UTC, opbld34 commented
Docs Build status updates of commit _[7c29a41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c29a41239434406bd3fb3b906ea49bc0552becb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersite?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d4871ba93dcc65e10616b7e7955295e1-76cac5ce)
[api-reference/beta/resources/edge.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/edge.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/edge?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9d8c4cef23dab8679ee0b3cc1042e6f1-76cac5ce)
[api-reference/beta/resources/internetexplorermode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/internetexplorermode.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internetexplorermode?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4447fb03fed8f4d26a9170fe76d7d52d-76cac5ce)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vi [...]

2022-08-09 02:56 UTC, opbld30 commented
Docs Build status updates of commit _[3bdd76b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bdd76b7a68f6aabd68aaaee8fd1f73a3242d31a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/edge.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/edge.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/edge?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9d8c4cef23dab8679ee0b3cc1042e6f1-4ff512af)
[api-reference/beta/resources/internetexplorermode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/internetexplorermode.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/internetexplorermode?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4447fb03fed8f4d26a9170fe76d7d52d-4ff512af)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedc [...]

2022-08-09 02:58 UTC, opbld32 commented
Docs Build status updates of commit _[b382b64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b382b6462050e48290596a5fefee6e733f911c57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.d [...]

2022-08-24 18:50 UTC, opbld32 commented
Docs Build status updates of commit _[ec88602](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec88602d5af31961cf021f8f145ec1860baa5d0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.d [...]

2022-08-24 19:05 UTC, edward-day-vii commented
> Hi @edward-day-vii, I checked your PR again and fixed the position of the TOC items because they should be surfaced under the Sites and lists node. Also, the relative links to https://docs.microsoft.com/deployedge/edge-ie-mode should be correct but the API Doctor can't validate them. For now, I have replaced all relative URLs with absolute URLs. I hope this will at least fix those API Doctor errors.
> 
> Please, take a look at the existing comments when you will have time.

@JarbasHorst Just checking to make sure that we are putting this workload under the correct node. I originally put it under "Sites and lists" because I couldn't figure out a better spot, but I wasn't sure if that was correct. I thought that it might be reserved for Sharepoint sites and lists. But if that's not the case then we are good to go. Just wanted to call out that we are not associated with anything Sharepoint related.

2022-08-24 19:29 UTC, opbld32 commented
Docs Build status updates of commit _[5389a1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5389a1e02e458e6985ab801ef715319fe74322cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [View](https://review.d [...]

2022-08-29 13:17 UTC, opbld34 commented
Docs Build status updates of commit _[6a4dc88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a4dc8816b37a7505da13458f23b6dd391e4dc33)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-533e9a75)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-08-29 13:20 UTC, opbld33 commented
Docs Build status updates of commit _[ade30bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ade30bf72b124f7928736486d6751ea7e2f5dd81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8d70be0a)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-09-07 12:55 UTC, opbld34 commented
Docs Build status updates of commit _[6c68a1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c68a1e9dabc9f1b826ca3d2386439a4b8b61ec8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-dea51b49)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-09-08 17:53 UTC, opbld33 commented
Docs Build status updates of commit _[be26956](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be269563860125b515d6f36b69768f36b235abea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8ea571f2)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review [...]

2022-09-28 04:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/enums.md
> -### outlierMemberType values
@edward-day-vii , just happened to see this while looking for a file, not meaning to do a review of your PR - it looks like you have removed the definitions for outlierMemberType and outlierContainerType here in enums.md. This will cause API Doctor errors the next time somebody rebuilds the files that reference these enums.
Can you clarify why, or add them back if that was unintentional?

2022-09-28 04:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/browsersite.md
> +|targetEnvironment|browserSiteTargetEnvironment|The target environment that the site should open in. The possible values are: `internetExplorerMode`, `internetExplorer11`, `microsoftEdge`, `configura
Line 41:
According to this [section](https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-policies#enable-internet-explorer-integration-using-group-policy) in the admin docs, after 6/15/2022 when Microsoft no longer supports IE 11, Edge would open in IE mode in an Edge browser any site that has been specified in a site list to open in IE 11.
It seems to me in the context of targetEnvironment, it's relevant to add a separate sentence about this behavior even if the property value is set to `internetExplorer11`. To make this sentence more noticeable, please style it in a separate paragraph in the table cell, by preceding the sentence with `<br /><br />`.

Can you please also do the same in the description for the targetEnvironment property in browsersitehistory.md as well?

2022-09-28 04:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/browsersitehistory.md
> +|targetEnvironment|browserSiteTargetEnvironment|The target environment that the site should open in. The possible values are: `internetExplorerMode`, `internetExplorer11`, `microsoftEdge`, `configura
Line 27:
@edward-day-vii , please see my [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17566/files#r981930180) about clarifying the behavior if setting this property to `internetExplorer11`.

2022-09-28 04:58 UTC, angelgolfer-ms commented on api-reference/beta/resources/browsersitelist.md
> +Represents a site list for [Internet Explorer mode](/deployedge/edge-ie-mode) that contains one or more [browserSite](../resources/browsersite.md) and [browserSharedCookie](../resources/browsershared
Line 16:
@edward-day-vii , to tie your API set better with what admin customers may be familiar with, is a "site list" in your API what we refer to as "enterprise site list" for organizations on the [Marketing page for IE mode in Edge](https://www.microsoft.com/en-us/edge/business/ie-mode)?
And for Microsoft Graph API, does this site list always reside in the cloud?

Assuming some or all of the above is true, can we please roll that info in to provide more context for a site list please? I can suggest the following sentence as the first sentence in the description; please edit where applicable. 

"Represents an enterprise site list in a compliant cloud location that specifies sites to be opened in [Internet Explorer mode](/deployedge/edge-ie-mode) for an organization. The site contains one or more browserSite..."

Since browerSite and browserSiteList are the main resources for this set of API, I'd also suggest adding a H2 "See also" section, and include a link to the Marketing site (https://www.microsoft.com/en-us/edge/business/ie-mode), followed by the first topic in the admin docs for IE mode in Edge (https://learn.microsoft.com/en-us/deployedge/edge-ie-mode).

2022-09-28 05:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/browsersharedcookie.md
> +
Line 16:
@edward-day-vii , can you provide more context about session cookies for IE mode?
Are these cookies to streamline Single Sign on authentication when going from a site that opens in an Edge session to another site that opens in IE mode, and vice versa, eliminating the need for reauthentication?

After adding more context, then can you please add a sentence that says "For more details, see {a link to this admin topic at https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-add-guidance-cookieshare}."

2022-09-28 07:01 UTC, angelgolfer-ms requested changes
Hi @edward-day-vii , I was looking through this PR to understand the API set you're releasing, so to determine the appropriate TOC entry point. As a side-effect, I noticed a few issues and hence commented. If you have specific questions about my comments, please feel free to ping me on Teams and include @Jarbas-MSFT . I don't intend to be a reviewer for this PR in its entirety; @Jarbas-MSFT continues to be the content reviewer for this PR and will follow up on completing the content review, including making sure my comments are closed appropriately.

I wanted to also quickly mention the necessity to add a service-level conceptual overview and an API overview for your debut PR. Please see the details in my email.

Thank you!

2022-09-28 12:14 UTC, opbld31 commented
Learn Build status updates of commit _[bef5d10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bef5d100347c618dba47de84d48d8eace2b5a522)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-09-28 12:28 UTC, edward-day-vii commented on api-reference/beta/resources/browsersitelist.md
> +Represents a site list for [Internet Explorer mode](/deployedge/edge-ie-mode) that contains one or more [browserSite](../resources/browsersite.md) and [browserSharedCookie](../resources/browsershared
What you said above is correct and true. They are "enterprise site lists" that reside always in the cloud. I will make these adjustments.

2022-09-28 12:40 UTC, edward-day-vii commented on api-reference/beta/resources/browsersitelist.md
> +Represents a site list for [Internet Explorer mode](/deployedge/edge-ie-mode) that contains one or more [browserSite](../resources/browsersite.md) and [browserSharedCookie](../resources/browsershared
@angelgolfer-ms if it's okay with you, I also added a link to this page: https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt, under the "See also" because it is the documentation for this specific application. Let me know if that's not okay and I can remove it.

2022-09-28 12:45 UTC, edward-day-vii commented on api-reference/beta/resources/enums.md
> -### outlierMemberType values
Fixed this. Sorry about that.

2022-09-28 12:47 UTC, opbld32 commented
Learn Build status updates of commit _[4caf1f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4caf1f4a975610c46c39d868e465332792bbfe77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-09-28 12:47 UTC, edward-day-vii commented on api-reference/beta/resources/browsersharedcookie.md
> +
Added some more context. Feel free to wordsmith me a little on this. I'm not the best technical writer.

2022-09-28 17:02 UTC, opbld31 commented
Learn Build status updates of commit _[07352b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07352b0daad96bae199eec054ed8725b4ebd5d03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-09-28 18:42 UTC, opbld32 commented
Learn Build status updates of commit _[9481cc5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9481cc535c1c1681d3339725602ae0a56b2525ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-09-28 18:44 UTC, opbld32 commented
Learn Build status updates of commit _[1c978e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c978e9b3a811ef098940b4b781a595e310a125e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-09-29 22:02 UTC, JarbasHorst commented on api-reference/beta/resources/browsersitelist.md
> +Represents a site list for [Internet Explorer mode](/deployedge/edge-ie-mode) that contains one or more [browserSite](../resources/browsersite.md) and [browserSharedCookie](../resources/browsershared
If you consider this extra link relevant to your audience, then it is OK to include it. I have added the "See also" section also to the browserSite topic.

2022-09-29 22:56 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +|   Permission    |  Display String   |  Description | Admin Consent Required |
For consistency, please include the column "Microsoft Account supported" and the corresponding values to this and the following tables?

2022-09-29 22:59 UTC, JarbasHorst commented
Hi @edward-day-vii, thanks for addressing our previous comments. I left one additional comment. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [18700](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18700) into your branch to include my fixes and before addressing my new comment.

2022-09-30 03:08 UTC, opbld31 commented
Learn Build status updates of commit _[5e7fe40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e7fe4079aa4893226f8a1d564c5c8ba47e13390)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/applicationsignindetailedsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/applicationsignindetailedsummary.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/applicationsignindetailedsummary?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-3b92899c1b00854519db9c63d2ff929f-ac0e78a0)
[api-reference/beta/resources/applicationsigninsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/applicationsigninsummary.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/applicationsigninsummary?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-4eaf47da97db5391c7b4ce96bfb5441d-ac0e78a0)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/micro [...]

2022-09-30 17:23 UTC, opbld30 commented
Learn Build status updates of commit _[72f0658](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72f0658dd6f7a36aace75237a272c803b4eae2ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-09-30 17:31 UTC, opbld34 commented
Learn Build status updates of commit _[834a668](https://github.com/microsoftgraph/microsoft-graph-docs/commits/834a6683e6ae48c7d480c77c76c8fc3805d9f147)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-10-04 20:52 UTC, JarbasHorst commented
Hi @edward-day-vii, I have reworked both concept topics. Please, take a look when you will have time and consider applying fixes if needed.

2022-10-05 03:13 UTC, opbld33 commented
Learn Build status updates of commit _[f85ca8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f85ca8f36aba021a64037eb72b2b91e6721a1eac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/printer-delete?view=graph-rest-1.0&branch=pr-en-us-17566) (>= graph-rest-1.0) | [Details](#user-content-8ce873d3ea28e735701f253ce8e0e4a0-7c02e566)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_chec [...]

2022-10-05 04:09 UTC, opbld30 commented
Learn Build status updates of commit _[bc60950](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc60950f641614828390cbaa2cbe1c1c739fb096)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookiehistory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookiehistory.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookiehistory?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersite.md) | :white_check_mark:Succeeded | [Vi [...]

2022-10-05 04:26 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        displayName: Cloud site list management for Internet Explorer (IE) mode APIs
Line 15510:
FYI the values for displayName are actually search terms. They don't get displayed anywhere. It's a misleading name.
So I'm changing these values to match what we think customers are likely going to use when they search for this set of APIs. Feel free to add more.

2022-10-05 06:19 UTC, angelgolfer-ms commented on api-reference/beta/api/browsersharedcookie-get.md
> +ms.prod: "sites-and-lists"
GLOBAL:
@edward-day-vii , I got confirmation that ms.prod for your topics should use "browser-management".
Can you please change that value for all the topics specific to your workload?
Thanks!

2022-10-05 06:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloud-ie-mode-site-lists-api-overview.md
> +Microsoft Graph gives your app authorized access to your organization's Cloud Site Lists for Internet Explorer (IE) mode, allowing you to manage the same data available in the Microsoft 365 admin cen
Line 12 and GLOBAL:
Please use sentence case for "cloud site lists".
Please see the  guidelines for capitalization is here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357
Please follow the guidance, and when in doubt, use lower case. Please do not assume that docs on the learn platform always use the appropriate capitalization (e.g., the admin [topic](https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-cloud-site-list-mgmt) is likely not correct, as compared with the guidance and the M365 admin center).

2022-10-05 07:12 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +## BrowserSiteLists resource permissions
Line 357:
FYI the section title should use a friendly name, not the prefix for the permission name.
Also, to accommodate possible future permission names for the Edge API to manage browsers, I'm going to use the section title "Browser management permissions".
FYI over time, for lack of oversight, the level of granularity of each H2 section has unfortunately gone too low. For example, for the Teams chat and channel related permissions, there shouldn't be separate H2 sections for each permission name prefix.

2022-10-05 09:16 UTC, angelgolfer-ms commented on concepts/browser-edge-concept-overview.md
> +The Microsoft Graph APIs for managing cloud site lists retain the same core functionality that is currently offered in the Microsoft 365 admin center. Administrators can automate common tasks such as
Line 27:
FYI when linking between the conceptual section and reference section, we have to use site-relative links.
Each such section is considered as its own doc set.
More info here: https://review.learn.microsoft.com/en-us/help/platform/links-how-to?branch=main#links-to-articles-in-other-repos-or-docsets

2022-10-05 09:17 UTC, opbld33 commented
Learn Build status updates of commit _[ebbd373](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebbd373ac4e89fdb0b301fcd24f5175326db29cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-c38da35b)
[concepts/browser-edge-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/concepts/browser-edge-concept-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/browser-edge-concept-overview?branch=pr-en-us-17566) | [Details](#user-content-fd726d16a413d97b3d0c635dbb36028f-c38da35b)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/brow [...]

2022-10-05 09:22 UTC, opbld32 commented
Learn Build status updates of commit _[6d424ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d424ec2608f76fbce8f72429dff85ab3081c980)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-e4b08f1f)
[concepts/browser-edge-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/concepts/browser-edge-concept-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/browser-edge-concept-overview?branch=pr-en-us-17566) | [Details](#user-content-fd726d16a413d97b3d0c635dbb36028f-e4b08f1f)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/brow [...]

2022-10-05 09:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/browser-edge-api-overview.md
> +|Use case|Request| See also |
@Jarbas-MSFT , I need your help here - can you please help, or help guide @edward-day-vii to reorganize this use case table to model that in the [Outlook mail API overview](https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta#common-use-cases)?

We never designed the table to show query URLs, which tend to take up disproportionately very wide cells and present table display issues. Besides, the level of depth in an API overview is also inappropriate; individual query URLs should belong in respective API topics only. 

I know over time, there's misinterpretation what should go into the use cases table and there exist API-level overviews that are similar to the one in this topic, serving as negative examples for other overviews.

2022-10-05 09:49 UTC, opbld31 commented
Learn Build status updates of commit _[098acf8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/098acf82a8518b6e8d2ba5c0d437698b9ce24074)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-640f743d)
[concepts/browser-edge-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/concepts/browser-edge-concept-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/browser-edge-concept-overview?branch=pr-en-us-17566) | [Details](#user-content-fd726d16a413d97b3d0c635dbb36028f-640f743d)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/brow [...]

2022-10-05 09:50 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Browser site list
Lines 1933, 1935, 1949, 1951:
Please note I added "Browser" to these TOC labels so to better differentiate them from the pre-existing SharePoint resources that are commonly and casually referred to as "site" and "site list".
These terms caused some confusion to a few internal folks earlier, so it's better to avoid ambituity.

2022-10-05 10:06 UTC, opbld34 commented
Learn Build status updates of commit _[af30531](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af3053194e7ae6232e987db6fd667b1c11b50345)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-07b33e6d)
[concepts/browser-edge-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/concepts/browser-edge-concept-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/browser-edge-concept-overview?branch=pr-en-us-17566) | [Details](#user-content-fd726d16a413d97b3d0c635dbb36028f-07b33e6d)
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/config/link-validation-config.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/config/link-validation-config.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/admin.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/admin?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) |
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/brow [...]

2022-10-05 10:08 UTC, angelgolfer-ms requested changes
Hi @edward-day-vii , @JarbasHorst , I made some updates to the PR, added a few comments for your info, and a few others for your follow-up. 
Please take a look at the comments and our email thread. Thank you!

2022-10-05 14:37 UTC, opbld34 commented
Learn Build status updates of commit _[7997513](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7997513ed19162795935916e5152c06f3f264f7d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-c1d26a9f)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-c1d26a9f)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-c1d26a9f)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-c1d26a9f)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-c1d26a9f)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-c1d26a9f)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-c1d26a9f)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-c1d26a9f)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-c1d26a9f)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-c1d26a9f)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-c1d26a9f)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-c1d26a9f)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-c1d26a9f)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-c1d26a9f)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-c1d26a9f)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-c1d26a9f)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-c1d26a9f)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-05 14:43 UTC, opbld30 commented
Learn Build status updates of commit _[dd29f06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd29f06c85fcbad4da6e0aa9b637e426ef96d04e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-190b1d20)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-190b1d20)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-190b1d20)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-190b1d20)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-190b1d20)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-190b1d20)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-190b1d20)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-190b1d20)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-190b1d20)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-190b1d20)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-190b1d20)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-190b1d20)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-190b1d20)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-190b1d20)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-190b1d20)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-190b1d20)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-190b1d20)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-05 21:32 UTC, JarbasHorst commented
@angelgolfer-ms, @edward-day-vii, I had a few minutes today, so I checked some of your comments and fixed some small issues. I will continue tomorrow with the review work.

2022-10-06 03:15 UTC, opbld31 commented
Learn Build status updates of commit _[0163b51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0163b514022a59fb35ace928f93e41ba242da7f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-897b2970)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-897b2970)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-897b2970)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-897b2970)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-897b2970)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-897b2970)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-897b2970)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-897b2970)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-897b2970)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-897b2970)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-897b2970)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-897b2970)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-897b2970)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-897b2970)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-897b2970)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-897b2970)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-897b2970)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-06 04:48 UTC, opbld31 commented
Learn Build status updates of commit _[c2b084c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2b084cb4ad828d171a0fce4fbf0f000dbca934c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-95fd86ea)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-95fd86ea)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-95fd86ea)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-95fd86ea)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-95fd86ea)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-95fd86ea)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-95fd86ea)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-95fd86ea)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-95fd86ea)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-95fd86ea)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-95fd86ea)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-95fd86ea)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-95fd86ea)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-95fd86ea)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-95fd86ea)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-95fd86ea)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-95fd86ea)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-06 04:51 UTC, opbld33 commented
Learn Build status updates of commit _[cc66e1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc66e1e16c308cd62ceefca1cafaab9083455c13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-62f0b49f)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-62f0b49f)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-62f0b49f)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-62f0b49f)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-62f0b49f)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-62f0b49f)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-62f0b49f)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-62f0b49f)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-62f0b49f)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-62f0b49f)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-62f0b49f)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-62f0b49f)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-62f0b49f)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-62f0b49f)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-62f0b49f)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-62f0b49f)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-62f0b49f)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-06 04:53 UTC, opbld34 commented
Learn Build status updates of commit _[67e1f8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67e1f8a464fb987d6c2658019f79c3c9357a2ee9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-18ee3111)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-18ee3111)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-18ee3111)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-18ee3111)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-18ee3111)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-18ee3111)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-18ee3111)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-18ee3111)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-18ee3111)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-18ee3111)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-18ee3111)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-18ee3111)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-18ee3111)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-18ee3111)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-18ee3111)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-18ee3111)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-18ee3111)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-06 06:06 UTC, angelgolfer-ms commented
@edward-day-vii , @JarbasHorst , I fixed the API Doctor error in the API overview topic. The major services table row addition looks good, thanks!

2022-10-06 21:26 UTC, opbld30 commented
Learn Build status updates of commit _[a0827f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0827f516b6b16ecf436520293cda906804822a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-a14defe4)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-a14defe4)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-a14defe4)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-a14defe4)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-a14defe4)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-a14defe4)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-a14defe4)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-a14defe4)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-a14defe4)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-a14defe4)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-a14defe4)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-a14defe4)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-a14defe4)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-a14defe4)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-a14defe4)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-a14defe4)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-a14defe4)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:05 UTC, opbld32 commented
Learn Build status updates of commit _[a28d4f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a28d4f80c86210b6d3031a067f67f0a7c8f4d42b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-41592508)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-41592508)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-41592508)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-41592508)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-41592508)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-41592508)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-41592508)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-41592508)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-41592508)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-41592508)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-41592508)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-41592508)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-41592508)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-41592508)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-41592508)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-41592508)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-41592508)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:19 UTC, opbld31 commented
Learn Build status updates of commit _[5dc3bdc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dc3bdc16cc3c3e213fcaa11bf0f45048b88711a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-6ba7e701)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-6ba7e701)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-6ba7e701)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-6ba7e701)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-6ba7e701)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-6ba7e701)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-6ba7e701)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-6ba7e701)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-6ba7e701)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-6ba7e701)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-6ba7e701)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-6ba7e701)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-6ba7e701)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-6ba7e701)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-6ba7e701)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-6ba7e701)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-6ba7e701)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:30 UTC, opbld33 commented
Learn Build status updates of commit _[e40ca4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e40ca4af94ea65580da00c0ca90a4a294de59c32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-6db7dc23)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-6db7dc23)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-6db7dc23)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-6db7dc23)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-6db7dc23)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-6db7dc23)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-6db7dc23)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-6db7dc23)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-6db7dc23)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-6db7dc23)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-6db7dc23)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-6db7dc23)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-6db7dc23)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-6db7dc23)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-6db7dc23)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-6db7dc23)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-6db7dc23)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:33 UTC, opbld31 commented
Learn Build status updates of commit _[fefec41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fefec41f0a8b77c454176a4c3d749583a4ca13c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-143c4064)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-143c4064)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-143c4064)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-143c4064)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-143c4064)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-143c4064)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-143c4064)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-143c4064)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-143c4064)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-143c4064)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-143c4064)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-143c4064)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-143c4064)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-143c4064)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-143c4064)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-143c4064)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-143c4064)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:41 UTC, opbld31 commented
Learn Build status updates of commit _[f83bb21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f83bb213f91276a5da6bb2e0c4c4526a23c3abd5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-df73cb12)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-df73cb12)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-df73cb12)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-df73cb12)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-df73cb12)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-df73cb12)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-df73cb12)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-df73cb12)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-df73cb12)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-df73cb12)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-df73cb12)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-df73cb12)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-df73cb12)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-df73cb12)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-df73cb12)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-df73cb12)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-df73cb12)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:44 UTC, opbld34 commented
Learn Build status updates of commit _[5e8db06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e8db06495414fde27bd891c45251aada8e497fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-fa1b8f06)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-fa1b8f06)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-fa1b8f06)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-fa1b8f06)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-fa1b8f06)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-fa1b8f06)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-fa1b8f06)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-fa1b8f06)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-fa1b8f06)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-fa1b8f06)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-fa1b8f06)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-fa1b8f06)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-fa1b8f06)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-fa1b8f06)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-fa1b8f06)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-fa1b8f06)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-fa1b8f06)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:47 UTC, opbld33 commented
Learn Build status updates of commit _[90bfc62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90bfc620be00c22b1cb3637b25c576e89b202638)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-96632807)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-96632807)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-96632807)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-96632807)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-96632807)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-96632807)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-96632807)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-96632807)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-96632807)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-96632807)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-96632807)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-96632807)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-96632807)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-96632807)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-96632807)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-96632807)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-96632807)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 19:56 UTC, opbld34 commented
Learn Build status updates of commit _[3325db0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3325db0cbf77674ac013c8ab587bb2ed749f0fe9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-7514a591)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-7514a591)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-7514a591)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-7514a591)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-7514a591)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-7514a591)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-7514a591)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-7514a591)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-7514a591)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-7514a591)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-7514a591)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-7514a591)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-7514a591)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-7514a591)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-7514a591)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-7514a591)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-7514a591)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 20:15 UTC, opbld30 commented
Learn Build status updates of commit _[5cd0c59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cd0c599159d78c3101544c6c7b510a4e8d849d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-9dcb80c7)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-9dcb80c7)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-9dcb80c7)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-9dcb80c7)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-9dcb80c7)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-9dcb80c7)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-9dcb80c7)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-9dcb80c7)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-9dcb80c7)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-9dcb80c7)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-9dcb80c7)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-9dcb80c7)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-9dcb80c7)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-9dcb80c7)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-9dcb80c7)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-9dcb80c7)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-9dcb80c7)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 20:20 UTC, opbld33 commented
Learn Build status updates of commit _[01f9b32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01f9b320ab59a3ddd4a7276ede16b70057e23347)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-36c0b0b9)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-36c0b0b9)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-36c0b0b9)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-36c0b0b9)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-36c0b0b9)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-36c0b0b9)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-36c0b0b9)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-36c0b0b9)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-36c0b0b9)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-36c0b0b9)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-36c0b0b9)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-36c0b0b9)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-36c0b0b9)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-36c0b0b9)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-36c0b0b9)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-36c0b0b9)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-36c0b0b9)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-10-07 20:23 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2022-11-03 02:20 UTC, opbld33 commented
Learn Build status updates of commit _[8958563](https://github.com/microsoftgraph/microsoft-graph-docs/commits/895856316497992ec288253a015369aa92fd67ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-6b562870)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-6b562870)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-6b562870)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-6b562870)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-6b562870)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-6b562870)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-6b562870)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-6b562870)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-6b562870)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-6b562870)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-6b562870)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-6b562870)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-6b562870)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-6b562870)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-6b562870)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-6b562870)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-6b562870)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-11-03 02:31 UTC, opbld33 commented
Learn Build status updates of commit _[0068767](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0068767eb098bb58c2da9585ed813e6d5f0bbf1f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-ffd34c94)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-ffd34c94)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-ffd34c94)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-ffd34c94)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-ffd34c94)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-ffd34c94)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-ffd34c94)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-ffd34c94)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-ffd34c94)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-ffd34c94)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-ffd34c94)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-ffd34c94)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-ffd34c94)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-ffd34c94)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-ffd34c94)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-ffd34c94)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-ffd34c94)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-11-03 02:42 UTC, opbld31 commented
Learn Build status updates of commit _[5322646](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5322646fe61596f789a923305ed5afe4a4d73b6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-4dd9b21c)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-4dd9b21c)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-4dd9b21c)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-4dd9b21c)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-4dd9b21c)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-4dd9b21c)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-4dd9b21c)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-4dd9b21c)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-4dd9b21c)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-4dd9b21c)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-4dd9b21c)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-4dd9b21c)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-4dd9b21c)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-4dd9b21c)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-4dd9b21c)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-4dd9b21c)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17566) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-4dd9b21c)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward-day-vii-cloudslim-docs/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](http [...]

2022-11-03 02:57 UTC, Lauragra approved these changes

2022-11-03 02:59 UTC, merged