teamworkcommunications merge
microsoftgraph/microsoft-graph-docs pull request #17576
Opened 2022-07-06 05:24 UTC by MariaWissler

2022-07-06 05:27 UTC, opbld33 commented
Docs Build status updates of commit _[361d5a6](https://github.com/MariaWissler/microsoft-graph-docs/commits/361d5a659921d6b14cf1937962703bf8476837ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207060524578400-17576/BuildReport?accessString=09f7adf5bed8a043adce98841c9726b51ff2aade8bc9ee71b78fbc5265da7fd9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 05:55 UTC, opbld34 commented
Docs Build status updates of commit _[37a4954](https://github.com/MariaWissler/microsoft-graph-docs/commits/37a4954ea32b43cc35fc0b87ba0922e12694d602)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207060553153411-17576/BuildReport?accessString=59a436fe35759fd45a16ab8c4feae493941beb2ed7589de8093f31ff4f4071df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 06:04 UTC, opbld30 commented
Docs Build status updates of commit _[34e9404](https://github.com/MariaWissler/microsoft-graph-docs/commits/34e9404fb430c7d00d46f3aeeb559b88460b77cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207060601473981-17576/BuildReport?accessString=280bc39fc59f3f331ff3029e550f45347ba6c42a77f823d02217ea81031de94e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-08 07:12 UTC, angelgolfer-ms commented on api-reference/beta/resources/teams-api-overview.md
The following comment applies to the ordering of the children topics and _children folders_ under each parent node. 

For children topics:
I think in most cases for the original topics under "Teamwork", you have the ordering consistent with our ordering guidelines as described here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=guidelines-and-examples

And I guess you might be just following the existing ordering of children topics from what's already published to this PR anyway.

But just so we are aware of, there are cases under the existing "Teamwork" and "Cloud communications" nodes that don't follow the guidelines for ordering children topics. And I am assuming for this PR, we're just targeting combining those two nodes under the new "Teamwork and communications" node. We can and shall deal with those cases in a separate PR.

For children folders under a parent node:
Can you order the new children folders you added to this PR alphabetically please?
Specifically, under the "Apps" folder.
We can really use that guideline for the "Shift management" folder too; that order (or the lack of an apparent order) is a pre-existing issue. But if you think we need to loop in more folks for that, then I would suggest we do that in a separate PR, after we merge this PR first.
The same reason applies - we can't help customers set expectations what comes next as they scan that section of the TOC, because there isn't an intuitive order such as alphabetical order.
Even when customers are re-visiting, it's less likely they'll be able to zoom into the child folder they need without going over the ones above them at that level of the TOC.

2022-07-08 07:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/teams-api-overview.md
Can you please elevate that "Pinned chat message" node by one level?
I think placing it under the "Messaging" subnode is better, instead of making the navigation like this: "Messaging" >> "Chat message" >> "Pinned chat message".
Technically right under "Messaging" is already a level 4 node.
If we push it down one more level, it's a level 5 node:
"API beta reference" >> "Teamwork and communications" >> "Messaging" >> "Chat message" >> "Pinned chat message"

The DevRel guidance for max TOC nesting is 3 levels: https://review.docs.microsoft.com/en-us/help/contribute/navigation-toc-overview?toc=%2Fhelp%2Fplatform%2Ftoc.json&bc=%2Fhelp%2Fplatform%2Fbreadcrumb%2Ftoc.json&branch=main#toc-size

2022-07-08 08:05 UTC, angelgolfer-ms commented on api-reference/beta/resources/teams-api-overview.md
> +- Create and manage Teams, Groups and Channels.
Lines 16-23:
If Nick and Chris, or appropriate folks on Teams and the cloud coms team (IC3?) have reviewed this list and confirm the list is representative of the current main capabilities and use cases, then I have the following suggestions:

(a) Remove the "Key resources in Microsoft Teams" section including its table. After all, the structure of an API-level overview topic (like this one) is to have a table that leads with use cases, representing common customer tasks, with the related resources on a right-side column as related info. (See this example in the mail API overview. CDK guidance [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211743/Conceptual-topics?anchor=but%2C-what%27s-the-difference-between-a-service-overview-vs-an-api-overview-in-the-reference-section%3F).)  Besides, the table in lines 27-44 basically aggregates what's in the TOC and what in the method table for each of those entities. Rather than trying to upkeep something like that, we should highlight the common use cases as described in the

(b) In each of the list items in lines 16-23, add links to terms that are represented as resources in the API. For example, "tabs" should have a link to the tab resource topic. (Please make sure to use sentence case. That is, only the first letter in a sentence should be in capital case.)

2022-07-08 08:07 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/teams-api-overview.md
> +Using Microsoft graph:
Please see comments in the beta version of the API-level overview.

2022-07-08 08:08 UTC, angelgolfer-ms requested changes
Thanks for persistently working on this task, @MariaWissler !
Please see my comments.

2022-07-15 19:36 UTC, angelgolfer-ms commented on api-reference/beta/resources/teams-api-overview.md
@MariaWissler , I noticed one thing we have overlooked:
When we combine the Teams and cloud communications APIs under the same node "Teamwork and communications" in the reference section, the conceptual section (under "Learn" in the TOC).
On the live site, the conceptual section has "[Cloud communications](https://docs.microsoft.com/en-us/graph/cloud-communications-concept-overview)" and "[Teamwork](https://docs.microsoft.com/en-us/graph/teams-concept-overview)" as two separate nodes. In general, the top-level node organization is meant to be the same between the conceptual section and reference section.

2022-07-19 05:06 UTC, opbld34 commented
Docs Build status updates of commit _[b038fad](https://github.com/MariaWissler/microsoft-graph-docs/commits/b038fad56ef3f6eb428ade2795e807f8c6c3fad1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-86163ccc)

<a id="86163ccc"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190506181178-17576/BuildReport?accessString=2963d8b867cbad19157b29e6fbe9ce50559e75a847dd3cf4faefe8ccc2c3572d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 06:09 UTC, opbld31 commented
Docs Build status updates of commit _[7d4cac8](https://github.com/MariaWissler/microsoft-graph-docs/commits/7d4cac82e3ef68485ca9cbd15c87082d53100aae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-7f0404436449ca8c39f5db4d4669959b-bb9c1513)
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bb9c1513)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |

<a id="7f0404436449ca8c39f5db4d4669959b-bb9c1513"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md)
 - **Line 18, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="0817dce4456c16725d5333633847d38f-bb9c1513"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 15732, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/team-get-photo.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207200605560112-17576/BuildReport?accessString=c7834c17cb6a68a6e45a5bab09007fe997bc8bc5ab2fd57222e296e5fd7a0eb4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 21:27 UTC, opbld33 commented
Docs Build status updates of commit _[9166e2f](https://github.com/MariaWissler/microsoft-graph-docs/commits/9166e2f4f26a78a7b6e89f306f3c9f0d6952d6e7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9bc86244)

<a id="9bc86244"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207252126439583-17576/BuildReport?accessString=7c730955b3a5bdc03f024b04b71e3d53f1bcf36c89791629c861ea471224cb87).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[62f2309](https://github.com/MariaWissler/microsoft-graph-docs/commits/62f2309b818df65a9f990e9219252fde0bca0232)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aac3903d)

<a id="aac3903d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292349034946-17576/BuildReport?accessString=c5ea0081fb8f4061eed48dcd69abcfb957eb7f684a601811fe1a75963f19bf45).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-30 00:09 UTC, opbld33 commented
Docs Build status updates of commit _[b481ce7](https://github.com/MariaWissler/microsoft-graph-docs/commits/b481ce7c1a703b2d6f8fd97314510fcd3d57616d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9498514a)
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-0817dce4456c16725d5333633847d38f-9498514a)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | | [Details](#user-content-46f72d0f0e32855fbc763025e376d98b-9498514a)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :bulb:Suggestion | | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-9498514a)

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-9498514a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml)
 - **Line 6816, Column 15**: **[Error: yaml-syntax-error]** `````While scanning a multiline plain scalar, found invalid mapping.`````

<a id="0817dce4456c16725d5333633847d38f-9498514a"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 15718, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/team-get-photo.md'.`````
 - **Line 15789, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/call-logteleconferencedevicequality.m'.`````

<a id="46f72d0f0e32855fbc763025e376d98b-9498514a"></a>
### [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md)
 - **Line 16, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 26, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< HEAD
| Use cases | REST resources | See also |
:-----------|:--------|:--------|
| Create and manage Teams, Groups and Channels | Create team, list your teams, create | Team, channel, group |
| Add tabs, manage or install apps in the Microsoft Teams app catalog | Create tab, list tabs, list apps| TeamsTab, teamsAppInstallation |
| Create channels and chats to send and receive chat messages |Create channel, list, send |Channel, chat, chatMessage|
| Create and receive calls, call records or retrieve meeting coordinates |Answer, invite participants | Call, call records |
| Connect bots to calls and implement interactive voice response (IVR) |  | IVR scenarios|
| Create and retrieve online meetings or check users presence and activity |Create online meeting, attendance report|Online meetings, presence |
| Create and manage workforce integration with shifts, schedules, time cards or time off in your organization | Create workforceIntegration, create schedule, create shift, create timeOff | WorkforceIntegration, schedule, shift, timeOff, timeOffReason|') are not allowed. You can only have one top-level heading.
`````

<a id="0145254ad8730abd76d1b4a84c0b3904-9498514a"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 101, Column 1**: **[Suggestion: heading-empty - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/heading-empty?branch=main)]** `````Empty H2. Headings must have content.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207300007162913-17576/BuildReport?accessString=2eab4406c00324c67a2245e8926b1455e8b352dd5116d21c0063d0f0769a3b2a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 02:55 UTC, opbld34 commented
Docs Build status updates of commit _[a5fe2df](https://github.com/MariaWissler/microsoft-graph-docs/commits/a5fe2df71775cb5cbc06603e1d90d98e5bac3479)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c5fd30f8)
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) | [Details](#user-content-46f72d0f0e32855fbc763025e376d98b-c5fd30f8)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-c5fd30f8"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 15718, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/team-get-photo.md'.`````

<a id="46f72d0f0e32855fbc763025e376d98b-c5fd30f8"></a>
### [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md)
 - **Line 16, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 26, Column 1**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< HEAD
| Use cases | REST resources | See also |
:-----------|:--------|:--------|
| Create and manage Teams, Groups and Channels | Create team, list your teams, create | Team, channel, group |
| Add tabs, manage or install apps in the Microsoft Teams app catalog | Create tab, list tabs, list apps| TeamsTab, teamsAppInstallation |
| Create channels and chats to send and receive chat messages |Create channel, list, send |Channel, chat, chatMessage|
| Create and receive calls, call records or retrieve meeting coordinates |Answer, invite participants | Call, call records |
| Connect bots to call [...]

2022-08-01 03:23 UTC, opbld31 commented
Docs Build status updates of commit _[684eccb](https://github.com/MariaWissler/microsoft-graph-docs/commits/684eccb2a20cc2fd5cee1e7cdbf5a7ce56f44cfa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208010319447272-17576/BuildReport?accessString=310bb73786d850c5c55ff65be933dd3984979bf4532eac50bd9ba78770828b12).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 00:16 UTC, opbld32 commented
Docs Build status updates of commit _[826b53a](https://github.com/MariaWissler/microsoft-graph-docs/commits/826b53a5bd8973000e5caa4808980c9054d04728)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-3d8dd027)

<a id="0817dce4456c16725d5333633847d38f-3d8dd027"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 1546, Column 1**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030014271859-17576/BuildReport?accessString=2830927ab5a5ae26d1393f620104bf925b2c3b90c5bf3a88fb301b8f0c24441a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 19:17 UTC, opbld31 commented
Docs Build status updates of commit _[1800291](https://github.com/MariaWissler/microsoft-graph-docs/commits/180029108af5e557567d35165d0e253178ffe3e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9b33a9bb)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-9b33a9bb"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 14891, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031915043639-17576/BuildReport?accessString=afb3b03f0c1a85594b5c1859593b750bfb0c6ba7d327a743479242daf226d0da).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q [...]

2022-08-03 19:32 UTC, opbld34 commented
Docs Build status updates of commit _[06c878a](https://github.com/MariaWissler/microsoft-graph-docs/commits/06c878afc360e57310ce0da589cbc287b015c918)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7ba046c9)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-7ba046c9"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 14891, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031930321748-17576/BuildReport?accessString=0d2b0c15bbb088f571ebdcb08da8d03d80999ac311bb631f97c7d5dc24f72e6f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q [...]

2022-08-04 22:01 UTC, opbld30 commented
Docs Build status updates of commit _[a29c398](https://github.com/MariaWissler/microsoft-graph-docs/commits/a29c3980acc3b531cd22a4c2d6b6a43b7cbcd2d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208042158194419-17576/BuildReport?accessString=62844443e40bea8233b2a71247f23940eba38e3e6c55dc8b50b21e4ab738dd02).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 23:33 UTC, eddie-lee-msft commented on concepts/teams-concept-overview.md
> +Whether scheduling a meeting between a doctor and a patient or between a user and their direct reports, is possible to build solutions that create meetings that users can rely on. For added flexibili
Whether scheduling a meeting between a doctor and a patient or between a user and their direct reports, _**it**_ is

2022-08-09 23:33 UTC, eddie-lee-msft commented on concepts/teams-concept-overview.md
> +To enable users to receive reminders for an appointment or a payment deadline that is approaching, you can have a bot call a customer automatically. <!--If a customer misses the call, the bot will le
Double period at the end

2022-08-09 23:33 UTC, eddie-lee-msft commented on api-reference/beta/resources/teams-api-overview.md
> +| Create and manage Teams, Groups and Channels | [Create team](../api/team-put-teams.md), [list your teams](../api/user-list-joinedteams.md), [create](../api/channel-post.md) | [Team](../resources/te
Should Teams, Groups and Channels be lowercase?

2022-08-09 23:33 UTC, eddie-lee-msft commented on api-reference/beta/resources/teams-api-overview.md
> +| Create and manage Teams, Groups and Channels | [Create team](../api/team-put-teams.md), [list your teams](../api/user-list-joinedteams.md), [create](../api/channel-post.md) | [Team](../resources/te
Create is duplicated at the end under REST resources

2022-08-09 23:33 UTC, eddie-lee-msft commented on api-reference/beta/resources/teams-api-overview.md
> +| Create channels and chats to send and receive chat messages |[Create channel](../api/channel-post.md),   [list](../api/channel-list.md), [send](../api/chatmessage-post.md) |[Channel](../resources/c
I'm seeing in multiple places in this table where there's a verb, like 'list' or 'send' without an object after it. Is there a reason that this is being done this way? I feel it may be clearer, especially in this row, to spell out exactly what each link brings you to. So, 'Create channel', 'list channels', and 'send message', something like that.

2022-08-09 23:33 UTC, eddie-lee-msft commented on api-reference/beta/resources/teams-api-overview.md
> +| Use Tags to classify users or groups based on common attributes whitin a team | [List](../api/teamworkTag-list.md), [create](../api/teamworkTag-post.md) | [Tag](../resources/teamworkTag.md), [tagMe
within

2022-08-09 23:33 UTC, eddie-lee-msft commented on api-reference/beta/resources/teams-api-overview.md
> +| Use Tags to classify users or groups based on common attributes whitin a team | [List](../api/teamworkTag-list.md), [create](../api/teamworkTag-post.md) | [Tag](../resources/teamworkTag.md), [tagMe
need to capitalize Tags?

2022-08-10 22:34 UTC, angelgolfer-ms commented on api-reference/beta/resources/teams-api-overview.md
> +| Use cases | REST resources | See also |
This comment applies to the table that starts in line 18:
The middle column is for resources, so methods should go to the right column.

2022-08-19 19:52 UTC, opbld30 commented
Docs Build status updates of commit _[28a4621](https://github.com/MariaWissler/microsoft-graph-docs/commits/28a4621c135f946e66785b0d3cda41497945e305)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-94b9b0a3)

<a id="0817dce4456c16725d5333633847d38f-94b9b0a3"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 1565, Column 17**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1563, Column 11**: **[Warning: yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208191951061698-17576/BuildReport?accessString=74c42e285a4f5ad355c402a6d0e22929f9e9a1b58d920910d8b9a905939553da).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 20:48 UTC, opbld31 commented
Docs Build status updates of commit _[7716238](https://github.com/MariaWissler/microsoft-graph-docs/commits/77162381cf8eb9a86a3527dc33dff607d2daa489)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208192045524189-17576/BuildReport?accessString=19c7674d988e23618883177d8edb6e147016aa9d9f13c386048a20ef7c5b800f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 22:51 UTC, opbld32 commented
Docs Build status updates of commit _[d782113](https://github.com/MariaWissler/microsoft-graph-docs/commits/d7821135f31e795226b039be733df1458d997f01)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :x:Error | | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-b3c7807b)

<a id="d6641161fd46c78dd4128bccd65500b6-b3c7807b"></a>
### [concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml)
 - **Line 482, Column 18**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208192249115117-17576/BuildReport?accessString=5440213e3d190fa15ac0bb7ab23a2304163994d1e3fd160c8f0edc1bc64882a7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 22:58 UTC, opbld34 commented
Docs Build status updates of commit _[c2ca9ad](https://github.com/MariaWissler/microsoft-graph-docs/commits/c2ca9ad9bdb3a6329afd0e404f968afc8da23e66)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :x:Error | | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-1a988eb3)

<a id="d6641161fd46c78dd4128bccd65500b6-1a988eb3"></a>
### [concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml)
 - **Line 516, Column 18**: **[Error: yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208192256489316-17576/BuildReport?accessString=9507ecedec34bac467da4c3e469ad70c4a89e1e6cc4971fb56a1dd626ce3e517).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 23:04 UTC, opbld31 commented
Docs Build status updates of commit _[cf4cb59](https://github.com/MariaWissler/microsoft-graph-docs/commits/cf4cb59c9405cbb38d08d3349fe708f1b88de7ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208192301513217-17576/BuildReport?accessString=8274e89e409e272e7943ffd81e1d16b836c9b672f521b556d8ac178bafbdd7bf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 17:36 UTC, opbld33 commented
Docs Build status updates of commit _[ff668f0](https://github.com/MariaWissler/microsoft-graph-docs/commits/ff668f0aeaed54b3cba81c48de726d4863d0dbc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208221734168632-17576/BuildReport?accessString=8893868140f1417c64774cc90804735a7a14d34e0dc47545e57fa2e4583349c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 20:42 UTC, opbld33 commented
Docs Build status updates of commit _[43b3b8e](https://github.com/MariaWissler/microsoft-graph-docs/commits/43b3b8ef41d42f442e24324ae13326bd9b7b7576)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208242039561660-17576/BuildReport?accessString=2a11e7deee1464483971d9db49cf3abf50b521d621ee8c367156e5394ea28c17).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 00:02 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
> +      "Teamwork and communications": "Prod",
@MariaWissler , FYI I can fix the errors like this one in line 71, where you had inadvertently replaced a line that should be:
"Cloud": "Prod",
by this:
"Teamwork and communications": "Prod",

This broke the JSON schema (because there is no key that's named "Teamwork and communications" in that schema),  and hence the error in your last build.

2022-08-25 00:05 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
> +      "WorkloadArea": "Teamwork communications",
@MariaWissler , FYI I can also fix the errors like the one in line 74, where you had inadvertently misnamed the value for "WorkloadArea" as "Teamwork communications", instead of "Teamwork and communications" (you missed the "and").

FYI WorkloadArea is the name of a top-level node like "Users", "Groups", "Calendar", etc.

2022-08-25 00:12 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Shifts.json
>            "SubArea":"Shifts"
In this changelog JSON file for the shifts API, the SubArea should be changed to "Shifts management". 
Since there are only 2 instances, I can fix them.

2022-08-25 00:20 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
>      },
@MariaWissler , line 75 is an example of the third type of errors in this changelog JSON file for cloud communications API - "SubArea" is the second level TOC node label, under the top-level TOC label "Teamwork and communications". 

In this case, assuming that all the cloud com APIs went under the second level TOC node "Meetings and calling", then "SubArea" should be that string. In the reconfigured TOC, there's no more second level TOC node under "Teamwork and communications" that's called "Call". That's become another 2 levels below "Meetings and calling".

2022-08-25 00:21 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
>      },
I can fix this type of errors as well, based on the assumption that all the cloud com APIs are now under the second level TOC node "Meetings and calling".
If that is actually not correct, please let me know.

2022-08-25 01:50 UTC, opbld30 commented
Docs Build status updates of commit _[5f47c5b](https://github.com/MariaWissler/microsoft-graph-docs/commits/5f47c5b47ad65d686b7a016f45e575faca6de18c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250148070924-17576/BuildReport?accessString=7e4112bc6b008f6b8519f562376e8dbd7483d82aee12fbece0b5ff6abb57bd06).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 01:57 UTC, opbld31 commented
Docs Build status updates of commit _[995ac21](https://github.com/MariaWissler/microsoft-graph-docs/commits/995ac21d3e40b58f6d54ef1e8d96cd305eb43fe6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250155165617-17576/BuildReport?accessString=f29a987fba3986f51f91ed11c7e9fde465945274fb7401846ecfd3bc42a62ddf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 08:36 UTC, angelgolfer-ms commented on concepts/teams-concept-overview.md
Lines 101-103:
@nkramer , @MariaWissler , FYI I am removing this section "Get notified about changes" from this service-level overview topic.
Per [guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211743/Conceptual-topics?anchor=what-to-write-for-your-service-overview%3F), this topic is about proposing value and should list the features that developers would create an app for. While change notifications is a very useful tool, developers use this feature to help them implement their scenario more efficiently. They don't create an app just to get change notifications.

2022-08-26 02:31 UTC, opbld31 commented
Docs Build status updates of commit _[313fb88](https://github.com/MariaWissler/microsoft-graph-docs/commits/313fb88b33574943e611d75e3f2e6896ce6be3f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-d8e95231)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0145254ad8730abd76d1b4a84c0b3904-d8e95231"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 34, Column 1**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260227081856-17576/BuildReport?accessString=1152a423bb5bfb3ce19ec2b83a1d42d65d67887cf3b63843befbef2736ece8f1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-chan [...]

2022-08-26 02:33 UTC, opbld31 commented
Docs Build status updates of commit _[a36f618](https://github.com/MariaWissler/microsoft-graph-docs/commits/a36f6180d66a7a5846123af8a96346f274cff977)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-24cc2359)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0145254ad8730abd76d1b4a84c0b3904-24cc2359"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 34, Column 1**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260228305912-17576/BuildReport?accessString=b46810cb505689df043d8680ddd1033e09acfe98a9446b47e13b6d433dbb2266).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-chan [...]

2022-08-26 02:47 UTC, opbld31 commented
Docs Build status updates of commit _[1f00962](https://github.com/MariaWissler/microsoft-graph-docs/commits/1f00962c5456b63f0c743430da42bae6bf99d3ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-8f1a4daf)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-8f1a4daf)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="a46d7d876f80d17c571e10a97f1ac07c-8f1a4daf"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-8f1a4daf"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 28, Column 1**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````
 - **Line 36, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260245086544-17576/BuildReport?accessString=fe518d762afe6f2cec3f17605cb6ec2febe145a922d201abfce598b9bb7b9d4a).

If you see build warnin [...]

2022-08-26 06:11 UTC, opbld30 commented
Docs Build status updates of commit _[c0b15ad](https://github.com/MariaWissler/microsoft-graph-docs/commits/c0b15adae7d6d605bbc540c2bc3e3a97ed06c002)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-fc5c33f7)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-fc5c33f7)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="a46d7d876f80d17c571e10a97f1ac07c-fc5c33f7"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-fc5c33f7"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 28, Column 1**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````
 - **Line 36, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260609016302-17576/BuildReport?accessString=d3ab6d7748fabdb84497ade5b747254f4f908243cf207e7e885ecc9cfc6a66ee).

If you see build warnin [...]

2022-08-26 06:20 UTC, opbld30 commented
Docs Build status updates of commit _[3ecd7ff](https://github.com/MariaWissler/microsoft-graph-docs/commits/3ecd7ff8861cc0f22c3587b376b7bfe4ac2b7217)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-898c1ffb)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-898c1ffb)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="a46d7d876f80d17c571e10a97f1ac07c-898c1ffb"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-898c1ffb"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 28, Column 1**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````
 - **Line 36, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260618282041-17576/BuildReport?accessString=894f9fc9be2add9a8eb2c4d5e7208901c1f4f9428e63b3ec359ec9dd407f4191).

If you see build warnin [...]

2022-08-26 06:23 UTC, opbld31 commented
Docs Build status updates of commit _[ce7c307](https://github.com/MariaWissler/microsoft-graph-docs/commits/ce7c3074281c95e5de6d66fae2bd84c20e07e800)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-988d84c1)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-988d84c1)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="a46d7d876f80d17c571e10a97f1ac07c-988d84c1"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-988d84c1"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 28, Column 1**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````
 - **Line 36, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260618503066-17576/BuildReport?accessString=aeb93756ed1ccc9c324d07d5c3651f54347ee529ffcefee62290510e4052c5a8).

If you see build warnin [...]

2022-08-26 07:01 UTC, opbld30 commented
Docs Build status updates of commit _[3b75d28](https://github.com/MariaWissler/microsoft-graph-docs/commits/3b75d283534ec2a195cc369888b61bed6a0e2e21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-bb2a5062)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-bb2a5062)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="a46d7d876f80d17c571e10a97f1ac07c-bb2a5062"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 60, Column 354**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#call-or-meet-collaboratively' in 'teams-concept-overview.md'.`````
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-bb2a5062"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 36, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260658523578-17576/BuildReport?accessString=4b4e8ed1265a7d0913e011d0115ed514cb60c90d6541cfc109131f9a552f1bfc).

If you see build warn [...]

2022-08-26 07:07 UTC, opbld32 commented
Docs Build status updates of commit _[f87c814](https://github.com/MariaWissler/microsoft-graph-docs/commits/f87c8141f1ba5b28af3f069fac4ef862c585854a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-a5fad6b9)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-a5fad6b9)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="a46d7d876f80d17c571e10a97f1ac07c-a5fad6b9"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-a5fad6b9"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 36, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260704588143-17576/BuildReport?accessString=f11144220203f8e4f8e0314a1587441636f04dc584f149e6dcff2a0d7e35de56).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](ht [...]

2022-08-26 07:25 UTC, angelgolfer-ms approved these changes
Thank you for your work, @MariaWissler . @nkramer , I have done what I can before my break to reorganize the conceptual overview, and browsed through to review the rest of the PR. 

Specifically, please take a look at the [conceptual overview on the staging site](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?view=graph-rest-beta&branch=pr-en-us-17576). Two main things I did there: 

(a) Clarify "Teamwork" is Teams and the 2 apps surfaced on Teams (Shifts and Viva Learning). Especially at the API level, their APIs and Teams API are independent of one another. I didn't think it was appropriate to give the impression that their APIs were part of the Teams API.

(b) Organizing the H2 sections originally pulled in from the teamwork overview and cloud communications overview into 3 buckets - "Automate workflows", "Call or meet virtually", and "Cultivate workforce". There were just too many H2 sections after the initial merge of the 2 concept overviews. I got the idea for the 3 new H2 titles from the Marketing site for Teams. BTW the Shifts API seems to have been understated all this time. It was missing in the Teams conceptual overview. I referenced the Marketing pages and created a section for it in the Teamwork conceptual overview. Since it's already available in v1, it's high time to give it the right level of exposure, at parity with how the Marketing site does it relative to Teams.

My request for @MariaWissler , before you set this PR to ready to merge, please make sure in both the conceptual section and reference sections (v1 and beta), there are no late additions to the TOC on the live site that your PR is missing.

Thanks!

2022-08-31 21:33 UTC, opbld30 commented
Docs Build status updates of commit _[e1f8a48](https://github.com/MariaWissler/microsoft-graph-docs/commits/e1f8a482be89bc9e170053d45a13c1384cf1d4ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9e6a032a)

<a id="9e6a032a"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit e1f8a482be89bc9e170053d45a13c1384cf1d4ab in branch toc-merge-teamwork_and_communications of repository https://github.com/MariaWissler/microsoft-graph-docs into branch main (commit f1947e2d691398c835eac081a2c1012d66e093f1). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312133033208-17576/BuildReport?accessString=0924c22bf5b60c3b53f00c87a0c56622c5534b8963e1eae156beb85fe8acd0fe).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 21:48 UTC, opbld33 commented
Docs Build status updates of commit _[2248ffd](https://github.com/MariaWissler/microsoft-graph-docs/commits/2248ffdc2191669c72af653ab7166385729e5cb7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0e40a1db)

<a id="0e40a1db"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 2248ffdc2191669c72af653ab7166385729e5cb7 in branch toc-merge-teamwork_and_communications of repository https://github.com/MariaWissler/microsoft-graph-docs into branch main (commit f1947e2d691398c835eac081a2c1012d66e093f1). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312147487942-17576/BuildReport?accessString=37bb3a24659e5dfe478a8cea8bd223080b5fdcbf0ec7fbd151005bc49c51649c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 21:54 UTC, opbld34 commented
Docs Build status updates of commit _[6d52eda](https://github.com/MariaWissler/microsoft-graph-docs/commits/6d52eda8a2a0b49445813d5477a80290afb778b1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1fd8013c)

<a id="1fd8013c"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 6d52eda8a2a0b49445813d5477a80290afb778b1 in branch toc-merge-teamwork_and_communications of repository https://github.com/MariaWissler/microsoft-graph-docs into branch main (commit f1947e2d691398c835eac081a2c1012d66e093f1). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312153454857-17576/BuildReport?accessString=506237f69bc04cf958985141f89bf474659d61e41c36ffe60d5a5a929635adb6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 22:30 UTC, opbld30 commented
Docs Build status updates of commit _[590e765](https://github.com/MariaWissler/microsoft-graph-docs/commits/590e765f77662d432ebb2059447c80d3e9c7cb23)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-439f00b9)

<a id="439f00b9"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 590e765f77662d432ebb2059447c80d3e9c7cb23 in branch toc-merge-teamwork_and_communications of repository https://github.com/MariaWissler/microsoft-graph-docs into branch main (commit f1947e2d691398c835eac081a2c1012d66e093f1). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312229363664-17576/BuildReport?accessString=477381f9ec6c8a2f54fe5fb1a2b4cecbf700a87e266cd83399e8918c493e9412).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 22:34 UTC, opbld31 commented
Docs Build status updates of commit _[590e765](https://github.com/MariaWissler/microsoft-graph-docs/commits/590e765f77662d432ebb2059447c80d3e9c7cb23)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8f961609)

<a id="8f961609"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 590e765f77662d432ebb2059447c80d3e9c7cb23 in branch toc-merge-teamwork_and_communications of repository https://github.com/MariaWissler/microsoft-graph-docs into branch main (commit f1947e2d691398c835eac081a2c1012d66e093f1). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312233507896-17576/BuildReport?accessString=bbf5f627fdb92b69176ee3758c69278ef568294bf0edf7fa4fe7c89aa56f00da).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 23:10 UTC, opbld32 commented
Docs Build status updates of commit _[e868b71](https://github.com/MariaWissler/microsoft-graph-docs/commits/e868b71698fa266bef2e1c86281c7695c9bb73d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5632198f)

<a id="5632198f"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit e868b71698fa266bef2e1c86281c7695c9bb73d2 in branch toc-merge-teamwork_and_communications of repository https://github.com/MariaWissler/microsoft-graph-docs into branch main (commit f1947e2d691398c835eac081a2c1012d66e093f1). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312310071527-17576/BuildReport?accessString=4683c4d8b6b3a6f0e9b92076a65086f6ac8ebfc1899b57cfcfc7bbeeb3151f5f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 23:33 UTC, opbld31 commented
Docs Build status updates of commit _[9197b37](https://github.com/MariaWissler/microsoft-graph-docs/commits/9197b3758c34d2bd9a18e8213b20282b52c413d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6420aa7f)
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-6420aa7f)
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) | [Details](#user-content-0145254ad8730abd76d1b4a84c0b3904-6420aa7f)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-6420aa7f"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

<a id="a46d7d876f80d17c571e10a97f1ac07c-6420aa7f"></a>
### [concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md)
 - **Line 64, Column 328**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#enable-employee-learning-using-the-collaborative-capabilities-in-teams' in 'teams-concept-overview.md'.`````

<a id="0145254ad8730abd76d1b4a84c0b3904-6420aa7f"></a>
### [concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md)
 - **Line 37, Column 3**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#ena [...]

2022-09-01 00:48 UTC, opbld34 commented
Docs Build status updates of commit _[96de73d](https://github.com/MariaWissler/microsoft-graph-docs/commits/96de73d65cb1f24e9603a784c15b2b95f0fb5c05)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3c6316f2)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-3c6316f2"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209010045583445-17576/BuildReport?accessString=5ec9dcbf1a635eb0864c224ddbbd0dd644fdafd059eb32cc35da30db0d40f3a7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-01 01:19 UTC, opbld33 commented
Docs Build status updates of commit _[cb9f539](https://github.com/MariaWissler/microsoft-graph-docs/commits/cb9f539cf3c19dcd976464c9c21be36c8f185bcc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-d9d5aecf)

<a id="0817dce4456c16725d5333633847d38f-d9d5aecf"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 199, Column 7**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209010116577644-17576/BuildReport?accessString=8432c2a2bf726a0dfeceb430a887c087d81ac1fb9a8aa5db952f710bf5568321).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 01:49 UTC, opbld30 commented
Docs Build status updates of commit _[44e4185](https://github.com/MariaWissler/microsoft-graph-docs/commits/44e4185f044e256e7a7b55e761a9aa54b8cc502c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-78e4f7c7)

<a id="0817dce4456c16725d5333633847d38f-78e4f7c7"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 199, Column 7**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209010147407684-17576/BuildReport?accessString=ded775585c984f9400b721b328163cf85081d5d807d5c15b27edf0b3570783de).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 04:05 UTC, opbld33 commented
Docs Build status updates of commit _[ec26aa7](https://github.com/MariaWissler/microsoft-graph-docs/commits/ec26aa70271ab4608b55252c660517aad1342c9e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-e19e13b2)

<a id="0817dce4456c16725d5333633847d38f-e19e13b2"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 216, Column 7**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209010403195511-17576/BuildReport?accessString=ad2d215ddc69da2894a6d24b0a1e97c36a3b78d88b1354acd57031bbdd4ec729).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 05:13 UTC, opbld32 commented
Docs Build status updates of commit _[624af3c](https://github.com/MariaWissler/microsoft-graph-docs/commits/624af3c3a2c7595dc05658567749a5058be957c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d06a52f5)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-d06a52f5"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209010511220462-17576/BuildReport?accessString=e8b48c38a7b890bd5019f216dedc990d755ce68477d535c4b78af15b152db031).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 02:46 UTC, opbld33 commented
Docs Build status updates of commit _[bfb4a40](https://github.com/MariaWissler/microsoft-graph-docs/commits/bfb4a40f7877346199ccea7b46aa9b220f7c6e46)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-16ccd12b)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-16ccd12b"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020243343577-17576/BuildReport?accessString=08c1a898346c6d6ea6fbdcc48fe46aad7bfda2e12b644e4bbc0ced68ee0b60e9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 02:48 UTC, opbld33 commented
Docs Build status updates of commit _[93ab321](https://github.com/MariaWissler/microsoft-graph-docs/commits/93ab3216865218deced1ac5b20c876235ebd4a8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5dbd22a7)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-5dbd22a7"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020245103246-17576/BuildReport?accessString=40693ddfbf70a2c9727760d3798ad3b0966a11a82144f94ed0842b738830f3e8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 08:31 UTC, opbld31 commented
Docs Build status updates of commit _[d06d36f](https://github.com/MariaWissler/microsoft-graph-docs/commits/d06d36fa41e8f1d65dbdcfa8aab099b64435ac48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5926296a)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-5926296a"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020828353301-17576/BuildReport?accessString=146565d3c541fc9ada0814bb3ab05f9623c42da166eafaf7adbb87f08476a8b3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 09:25 UTC, opbld33 commented
Docs Build status updates of commit _[7c84822](https://github.com/MariaWissler/microsoft-graph-docs/commits/7c848222f88cced40090beb77417ba6848a8cb16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8e5b5f0c)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-8e5b5f0c"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020922369257-17576/BuildReport?accessString=faa268d03a301945eb60cea4fe961eca0336ea387f27b1fab5aff3aeb6c74b1e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 09:40 UTC, opbld32 commented
Docs Build status updates of commit _[883e9fd](https://github.com/MariaWissler/microsoft-graph-docs/commits/883e9fdfb112b4bae88a7a14ae352df8f92387d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-42ad4fb3)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-42ad4fb3"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020936523202-17576/BuildReport?accessString=cf5bc2d0b800d100af3bf63e78a9f2d0fd3f7294298af0dc74092306c87c7945).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 10:07 UTC, opbld34 commented
Docs Build status updates of commit _[1314fd1](https://github.com/MariaWissler/microsoft-graph-docs/commits/1314fd1d00077827edf10faf111b6ac814f967db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e15393a6)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-17576) (graph-rest-beta) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-17576) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Core.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Teams.Shifts.json](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/changelog/Microsoft.Teams.Shifts.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communication-online-meeting-application-access-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |
[concepts/cloud-communications-callrecords.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-17576) |
[concepts/cloud-communications-calls.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-calls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-calls?branch=pr-en-us-17576) |
[concepts/cloud-communications-get-started.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-get-started?branch=pr-en-us-17576) |
[concepts/cloud-communications-identifylargegalleryview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-identifylargegalleryview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-identifylargegalleryview?branch=pr-en-us-17576) |
[concepts/cloud-communications-media.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-media.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-media?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meeting-artifacts.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meeting-artifacts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meeting-artifacts?branch=pr-en-us-17576) |
[concepts/cloud-communications-online-meetings.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-online-meetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-online-meetings?branch=pr-en-us-17576) |
[concepts/cloud-communications-phone-number.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/cloud-communications-phone-number.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-phone-number?branch=pr-en-us-17576) |
[concepts/overview-major-services.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/overview-major-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-17576) |
[concepts/teams-concept-overview.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/teams-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-17576) |
[concepts/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy?branch=pr-en-us-17576) |

<a id="0817dce4456c16725d5333633847d38f-e15393a6"></a>
### [api-reference/beta/toc.yml](https://github.com/MariaWissler/microsoft-graph-docs/blob/toc-merge-teamwork_and_communications/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021004157993-17576/BuildReport?accessString=89f26db5fdea2fff89985c07daf85ea94170986ca7832efdc4e03d27c27be369).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Y [...]

2022-09-02 10:14 UTC, merged