Updating Authentication Methods Policy beta branch with new feature settings changes.
microsoftgraph/microsoft-graph-docs pull request #17588
Opened 2022-07-06 21:21 UTC by mjsantani

Schema PR: 6296208

2022-07-06 21:23 UTC, opbld34 commented
Docs Build status updates of commit _[36e41c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36e41c3e01c6b068c0da966d2bcc6d4d5de84116)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) | [Details](#user-content-18f0161a60fbf7d23acb69ffc11c9567-c2ec91be)
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) | [Details](#user-content-49d196376c58ad018beeaa2524f68a9d-c2ec91be)
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) | [Details](#user-content-c29bfb369f5bcb84f2c41b771e60cf8a-c2ec91be)
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |

<a id="18f0161a60fbf7d23acb69ffc11c9567-c2ec91be"></a>
### [api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 16**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="49d196376c58ad018beeaa2524f68a9d-c2ec91be"></a>
### [api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 16**: **[Warning: yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="c29bfb369f5bcb84f2c41b771e60cf8a-c2ec91be"></a>
### [api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'mcmla, mjsantani' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062121209826-17588/BuildReport?accessString=9dc0d849cf935965b86df9d1d682689bc6d0f99318b43249ff35784d590e52c2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 21:43 UTC, opbld33 commented
Docs Build status updates of commit _[3458b49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3458b49da8f1a6a4027bc95b364de12fcbce64e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062141293147-17588/BuildReport?accessString=e29b3a5c7c2da895e12c5532f1f1d1313165a2ad4cf2bd13099e8be34f3f587b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 22:15 UTC, opbld33 commented
Docs Build status updates of commit _[06caae1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06caae12fbc55286e46644b901a3df7ca6e71450)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062213455181-17588/BuildReport?accessString=c4ea470cd8df3e1ed711e0e5ec205d9712b3e55a4996108664f7d19b995537b4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 22:20 UTC, opbld31 commented
Docs Build status updates of commit _[184c03d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/184c03d065942d8a3cf1d3a0f4734ef426c3131d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062217466807-17588/BuildReport?accessString=e9172adc65b0976a61c5d8eaa88a657eedb734e41e5bf86c931202ec21127c12).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 22:49 UTC, opbld32 commented
Docs Build status updates of commit _[36750b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36750b7051c0670222200a0e1e44d370aa45b3e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207062247140869-17588/BuildReport?accessString=217ad99aedc3648eaed396d7354f65455387003173b067a630d96281ecd51384).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-06 23:20 UTC, andres-canello approved these changes

2022-07-07 19:16 UTC, mjsantani commented
Adding the following context for Graph reviewers: 
Internal Roadmap Number: 14596
Purpose of the PR: We are updating the Authenticator app's admin policies and are changing how admins enable/disable features. We are also splitting out the application context feature policy into two: application context and location context.

2022-07-22 22:11 UTC, opbld34 commented
Docs Build status updates of commit _[45883d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45883d641debf7b520016bb51aad57af6cc1e22c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207222208403916-17588/BuildReport?accessString=e28feb3516de944dc363bb0da303f34859e7ff8b4691e6789e5724795240ec54).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 23:04 UTC, opbld31 commented
Docs Build status updates of commit _[d9cbbeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9cbbeb3e3cc14e47e952eb8de5fbdb7fb4dfa26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207222302119417-17588/BuildReport?accessString=796edaa5620ec0c40e2ec55340a8c77ac0b63c7d6483afed454c7291b1d7ddd4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 07:06 UTC, FaithOmbongi requested changes
Hi @mjsantani - I've left feedback on the PR. A major concern is the differences between your schema PR and your API.md. For example, 
- featureSettings is a relationship in the approved API.md, but a property in the schema PR and the live payload. 
- The featureConfiguration complex type's name changed to authenticationMethodFeatureConfiguration. 
- All the properties of the microsoftAuthenticatorFeatureSettings complex types are also differently named.

These are just samples but it seems everything that's downstream to featureSettings is differently named. Can you align the API.md and the schema PR so we know the doc matches both?

2022-07-26 07:06 UTC, FaithOmbongi commented on api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md
> -|displayAppInformationRequiredState|advancedConfigState|Determines whether the user is shown additional context in their Authenticator app notification. In the body of the Authenticator notification,
The public metadata/schema shows differently
<img width="670" alt="image" src="https://user-images.githubusercontent.com/14026935/180943799-29a85d02-2f06-4337-bfe3-0c4c9149f498.png">

2022-07-26 07:06 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    {
I haven't reviewed the changelog because it's possible the schema will change. Please replace this object with the new autogenerated changelog.

2022-08-02 18:00 UTC, opbld33 commented
Docs Build status updates of commit _[b4e6d10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4e6d101b1172ad17667628db1955ffc225ca161)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021758129093-17588/BuildReport?accessString=401307013d7898e206de60176a2217aa92ecf34d9f6899c9d4d1804d7fffa7aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 18:03 UTC, opbld31 commented
Docs Build status updates of commit _[26bf0d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26bf0d1b8ce78c514ac8c221fe85b845cadc0d60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021801301280-17588/BuildReport?accessString=fc268c385637b6580f74e7f10c36d58c1d44c1b8371e33db62548c38519e2d80).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 18:54 UTC, opbld30 commented
Docs Build status updates of commit _[4e1dec5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e1dec542360999ae49dae27fe8203ff961ab56f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021852429416-17588/BuildReport?accessString=0cb71a06d1cab82a1d7de19cd779e1c4fa1e262c42954a64ade6b176bf95bb1c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 19:02 UTC, opbld31 commented
Docs Build status updates of commit _[6c48790](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c48790675bcf9b2b90cc8c0b160bee20f546fb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021900063287-17588/BuildReport?accessString=9215439dece4dd6d340645b54a63d19a6bb5dfafca8ca0ea117ae3c1062ffeac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 19:04 UTC, opbld34 commented
Docs Build status updates of commit _[601ea11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/601ea1149dfcc171d504bcceac8335f3670fbe8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021901144226-17588/BuildReport?accessString=0a41f3ed78372497692340a265a88fcf53976fff6508c32f6d164991a4454afa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 19:05 UTC, mjsantani commented on api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md
> +}
The property names here are right. Found the PR where the api.md file was updated: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/commit/bbb7e99b7d871f8f4edb7b61c06dfe1af7c30133?refName=refs%2Fheads%2Fmaster&path=%2Freviews%2F3027-auth-method-policy%2Fapi.md&_a=contents

2022-08-02 19:39 UTC, opbld32 commented
Docs Build status updates of commit _[8f60f16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f60f16f4dfd79dd7d0e77961c63ba6ed9102666)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021937060194-17588/BuildReport?accessString=c5ff66209fcd7a4b29a3d5db9874b2e13d65e9f18a9467c32a51d4e7b0db57c7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 19:31 UTC, FaithOmbongi requested changes
Hi @mjsantani - I've left comments inline + the following gaps:
+ We confirmed featureSettings is a property, not a relationship
+ Document companionAppAllowedState property in microsoftAuthenticatorFeatureSettings. It has already been exposed to the public payload
+ Once you document **companionAppAllowedState**, add its respective changelog object.
+ For the two properties deprecated from microsoftauthenticatorauthenticationmethodtarget, mark them as deprecated, **do not delete them**. For example, "_numberMatchingRequiredState (deprecated)_" in the property table. Once the schema is updated, copy the two deprecation changelist records and add them to your changelog.
+ So for the changelog - you need three new objects. 1 new property + 2 deprecated properties.

Please share with me (internally) your new schema PR. Once it's approved, I'll use it to compare with this docs PR as a pre-approval step.

2022-08-04 19:31 UTC, FaithOmbongi commented on api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md
> +|featureSettings|[microsoftAuthenticatorFeatureSettings](../resources/microsoftauthenticatorfeaturesettings.md)|A collection of Microsoft Authenticator settings such as number matching and location c
This has moved to be a property, not a relationship.

2022-08-04 19:31 UTC, FaithOmbongi commented on api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md
> +|displayLocationInformationRequiredState|[authenticationMethodFeatureConfiguration](../resources/authenticationmethodfeatureconfiguration.md)|Determines whether the user's Authenticator app will show
1. Properties in alphabetical order please.
2. Document the **companionAppAllowedState** property. It has already been exposed to the public payload

2022-08-04 19:31 UTC, FaithOmbongi commented on api-reference/beta/resources/featuretarget.md
> +|id|String|The ID of the entity that's targeted in the include or exclude rule.|
I see also `all_users` is a valid value. Do we have `all_groups` or `all_administrativeunits`? Please indicate in this description other values apart from the ID.

2022-08-04 19:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [microsoftAuthenticatorFeatureSettings](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorFeatureSettings?view=graph-rest-beta) resource",
stub generator bugs
```suggestion
          "Description": "Added the [featureTargetType](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource.",
          "Target": "featureTargetType"
        },
        {
          "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
          "ApiChange": "Resource",
          "ChangedApiName": "authenticationMethodFeatureConfiguration",
          "ChangeType": "Addition",
          "Description": "Added the [authenticationMethodFeatureConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodFeatureConfiguration?view=graph-rest-beta) resource.",
          "Target": "authenticationMethodFeatureConfiguration"
        },
        {
          "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
          "ApiChange": "Resource",
          "ChangedApiName": "featureTarget",
          "ChangeType": "Addition",
          "Description": "Added the [featureTarget](https://docs.microsoft.com/en-us/graph/api/resources/featureTarget?view=graph-rest-beta) resource.",
          "Target": "featureTarget"
        },
        {
          "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
          "ApiChange": "Resource",
          "ChangedApiName": "microsoftAuthenticatorFeatureSettings",
          "ChangeType": "Addition",
          "Description": "Added the [microsoftAuthenticatorFeatureSettings](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorFeatureSettings?view=graph-rest-beta) resource.",
```

2022-08-04 19:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [featureSettings](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta) resource",
Stu generator bugs + suggested enhancement to the **featureSettings** description
```suggestion
          "Description": "Added the **displayAppInformationRequiredState** property to the [microsoftAuthenticatorFeatureSettings](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorFeatureSettings?view=graph-rest-beta) resource.",
          "Target": "microsoftAuthenticatorFeatureSettings"
        },
        {
          "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
          "ApiChange": "Property",
          "ChangedApiName": "displayLocationInformationRequiredState",
          "ChangeType": "Addition",
          "Description": "Added the **displayLocationInformationRequiredState** property to the [microsoftAuthenticatorFeatureSettings](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorFeatureSettings?view=graph-rest-beta) resource.",
          "Target": "microsoftAuthenticatorFeatureSettings"
        },
        {
          "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
          "ApiChange": "Property",
          "ChangedApiName": "numberMatchingRequiredState",
          "ChangeType": "Addition",
          "Description": "Added the **numberMatchingRequiredState** property to the [microsoftAuthenticatorFeatureSettings](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorFeatureSettings?view=graph-rest-beta) resource.",
          "Target": "microsoftAuthenticatorFeatureSettings"
        },
        {
          "Id": "448b4105-a8c6-46d6-b2ae-9dee9e9b5f14",
          "ApiChange": "Property",
          "ChangedApiName": "featureSettings",
          "ChangeType": "Addition",
          "Description": "Added the **featureSettings** property to the [microsoftAuthenticatorAuthenticationMethodConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/microsoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta) resource. This property allows you to configure Microsoft Authenticator settings such as number matching and location context, and whether they are enabled for all users or specific users only.",
```

2022-08-04 19:31 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      ],
Your changelog will need three new objects - 1 new property (**companionAppAllowedState**) and 2 properties (**displayAppInformationRequiredState** and **numberMatchingRequiredState**) deprecated from microsoftAuthenticatorAuthenticationMethodTarget. Please copy them from your schema PR once it's updated and refreshed.

2022-08-05 22:56 UTC, opbld34 commented
Docs Build status updates of commit _[7fce491](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fce491344763a33cf569dd9b45946fe801135d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208052253405432-17588/BuildReport?accessString=bca1ecb2063e48ab2b8736b1a796c1a47e5476f9e35b8d05edc4497fd9443728).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 23:03 UTC, opbld33 commented
Docs Build status updates of commit _[d5b5f01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5b5f017ee9906bb847a23122319de5a1cf48b92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208052300477311-17588/BuildReport?accessString=c980f5a0efc74d6c89d2ef14bb2d8e7c77774ad01b121cf74460f63cc96c1782).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-05 23:05 UTC, opbld34 commented
Docs Build status updates of commit _[eb10908](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb10908ad9f14e33fc8b2803af2a0a250bda0060)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208052301123326-17588/BuildReport?accessString=6bbb99150afbe55ce6362fb04f5066c6c8344dacbb49bd70f4b4df6c8cf2d52a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 19:58 UTC, opbld30 commented
Docs Build status updates of commit _[7e6560b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e6560b2b6c83a9dda281d5803a771ba034340bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208121956538902-17588/BuildReport?accessString=b514843b2d203c201875c800fdd8dbcd6363d129337911f8dcee25d7f80daa1d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 18:35 UTC, opbld33 commented
Docs Build status updates of commit _[82b7dbb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82b7dbbbea47814165e014806fe1f27e61590839)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.AuthenticationMethodsPolicy.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.AuthenticationMethodsPolicy.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208151834061999-17588/BuildReport?accessString=5d5ac18c54568e685cfc69109b0c1ae3ab39173787b9fe1b746222b8aab73f37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 18:43 UTC, FaithOmbongi approved these changes
Hi @mjsantani - I've pushed a commit for some minor fixes and approved.

2022-09-02 01:19 UTC, opbld30 commented
Docs Build status updates of commit _[aea4a10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aea4a1048b14ad06f1a60d2150886b874c554d71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) | [Details](#user-content-604cbaf4397f0b861fc48da0ae99981b-fc36be57)
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.AuthenticationMethodsPolicy.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.AuthenticationMethodsPolicy.json) | :white_check_mark:Succeeded | |

<a id="604cbaf4397f0b861fc48da0ae99981b-fc36be57"></a>
### [api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'currenmehta' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020117032002-17588/BuildReport?accessString=818167abca1239218a2d3424f1b834fc16e1ae8d4b571b55b2b14a009f9a0557).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 01:21 UTC, opbld34 commented
Docs Build status updates of commit _[fcb29d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcb29d1af0296cbe7ec69cfb254a9a342d97dac3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-customaccesspackageworkflowextensions?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) | [Details](#user-content-604cbaf4397f0b861fc48da0ae99981b-382a53f9)
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodfeatureconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/authenticationmethodfeatureconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodfeatureconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/featuretarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/featuretarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/featuretarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/resources/microsoftauthenticatorfeaturesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoftauthenticatorfeaturesettings?view=graph-rest-beta&branch=pr-en-us-17588) (graph-rest-beta) |
[changelog/Microsoft.AuthenticationMethodsPolicy.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/changelog/Microsoft.AuthenticationMethodsPolicy.json) | :white_check_mark:Succeeded | |

<a id="604cbaf4397f0b861fc48da0ae99981b-382a53f9"></a>
### [api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/beta-codeMatchContext/api-reference/beta/api/accesspackagecatalog-list-customaccesspackageworkflowextensions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'currenmehta' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020118428338-17588/BuildReport?accessString=92e3fcf68b4c5e49fa9586e0afc53dac1405d9aa9ff7c18dca4d3c7a03ac8bf7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 23:53 UTC, merged