Graph Explorer docs update
microsoftgraph/microsoft-graph-docs pull request #17622
Opened 2022-07-08 18:41 UTC by RabebOthmani

This PR contains changes to the documentation related to Graph Explorer so it is up to date with the latest modifications on the product. I'd appreciate any editorial feedback and suggestions.

2022-07-08 18:43 UTC, opbld30 commented
Docs Build status updates of commit _[79b8c5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79b8c5d4f8c52a07c19e7834ea8ce5901863a239)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) | [Details](#user-content-8d1dc93de8e8f9028aa77fbba51cd1bc-ebd4b825)
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen .png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen%20.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/graph-explorer-screen%20.png?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
<a id="8d1dc93de8e8f9028aa77fbba51cd1bc-ebd4b825"></a>
### [concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md)
 - **Line 14, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/graph-explorer-screen.png'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207081841191005 [...]

2022-07-12 15:26 UTC, opbld32 commented
Docs Build status updates of commit _[d37eb27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d37eb274e98bab111cbc11105572a478f40467b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207121524393838-17622/BuildReport?accessString=d2b578df01afd289035239108f64ef42d42cf8a23c2b3112f0c4c82b9f05f2cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-07-22 18:27 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-overview.md
> +With Graph Explorer, you can make requests to the Microsoft Graph APIs to retrieve, add, delete and update data. Your requests can send parameters, authorization details, and any body data you requir
"... and any body data you require." This phrase may be hard to understand for non-native speakers. 

Suggestion:
```suggestion
With Graph Explorer, you can make requests to the Microsoft Graph APIs to retrieve, add, delete and update data. Your requests can send parameters, authorization details, and any object you require.
```

2022-07-22 18:34 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-overview.md
> +:::image type="content" source="./images/request-headers.png" alt-text="Screenshot of request headers in Graph Explorer." border="true":::
GLOBAL: What is the goal of adding the image to the document? Consider this when composing the alt text. The alt text should meet the same goal as the image. If the objective is to illustrate the operation, ask yourself if the alt text is providing enough clarity to meet that objective.

2022-07-22 18:38 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-overview.md
> +To run a GET request in Graph Explorer, you don't have to be signed in. You can retrieve sample data from the default sample tenant.
In general, we avoid passive voice when possible. Guidance here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523

```suggestion
To run a GET request in Graph Explorer, you don't have to sign in. You can retrieve sample data from the default sample tenant.
```

2022-07-22 18:43 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-overview.md
> +To create the request, you can either select a sample query which fills in the query field or you can choose to manually type your request in the field.
Guide your user as if it were their first time in the tool. Example:
```suggestion
To create the request, you can either select a sample query from the menu at the left, which fills in the query field, or you can choose to manually type your request in the field.
```

2022-07-22 20:14 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +The user or administrator must grant Graph Explorer the correct permissions by using a consent process to access data in Microsoft Graph. You can consent to permissions in Graph Explorer by choosing
Line 28: The last sentence can be misleading. A reader could interpret that they need all the permissions listed, and request all of them. Could we clarify that the tab lists the permissions from least to most privileged and remind users to use the least privileged when possible.

2022-07-22 20:16 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +![Screenshot of Graph Explorer with the steps to consent to permissions highlighted](./images/modify-permissions-screenshot.png)
Please add alt text to all images in this topic. Some of the images precede a paragraph that provides a good explanation so, in those cases a simple alt text would be enough.

2022-07-22 20:19 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +- [History](#store-and-share-queries)
Sidebar section: Could you please elaborate a bit more and/or add a screenshot of the sidebar. For a user whose not familiar with the UI the section is not providing enough guidance to understand what the sidebar is, where to find it and what is it for.

2022-07-22 20:20 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +To get started with Microsoft Graph and get yourself familiar with using Graph Explorer, the **Sample queries** feature provides a set of queries categorized by service that you can select and run.
Suggestion for simplicity:
```suggestion
To get started with Microsoft Graph and get yourself familiar with Graph Explorer, the **Sample queries** feature provides a set of queries categorized by service that you can select and run.
```

2022-07-22 20:23 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +The Resources feature allows you to explore the resources on Microsoft Graph in their entirety, on both v1.0 and beta versions . Navigate the tree to view a specific resource or alternatively, you ca
Suggestion for voice:
```suggestion
The Resources feature allows you to explore the resources on Microsoft Graph in their entirety, on both v1.0 and beta versions. Navigate the tree to browse for a specific resource or, alternatively, use the search bar to find it.
```

2022-07-22 20:36 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +With Resources Explorer, you can export a collection of resources you are interested in, into a Postman collection:
Line 68: In general, we avoid capitalizing names that are not TMd brands. Adding a suggestion for simplicity also:
```suggestion
With the **Resources** tab you can export a collection of resources into a Postman collection:
```

2022-07-22 20:39 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +1. Click on the **Download Postman collection** to download your collection.
Edit:
```suggestion
1. Click on **Download Postman collection** to download your collection.
```

2022-07-22 20:41 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +Queries that are run in Graph Explorer are saved for 30 days on the **History** tab. On the **History** tab, you can:
Edit for simplicity:
```suggestion
All queries you run in Graph Explorer are saved for 30 days in the **History** tab. In the **History** tab, you can:
```

2022-07-22 20:44 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +To share queries that you run, select the **Share** button situated next to the Run query button, and then select **Copy**. This copies a link to share that allows others to see your query and the re
Edit:
```suggestion
To share queries that you run, select the **Share** button situated next to the Run query button, and then select **Copy**. This copies a shareable link that allows others to see your query and the results.
```

2022-07-22 20:47 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +This area is where you will be spending most of your time on Graph Explorer. This area has everything you need to run a request:
Line 96: What if I spend most of my time creating resource collections for Postman? 😆 
Can we rephrase this intro sentence to make it more focused on the value of the section?

2022-07-22 20:53 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +- **Access token**: this tab shows your access token when you're signed in. You can copy the token if you need to use it in your favorite REST client application.
Lines 98 to 102: In general we try to apply the principles of parallel writing. That means, for a list of sentences related, we try to compose them using a similar format. For example, if we start with infinitive, all the other should too. If we start with a verb in 3rd person present, the others should too. In this case, I'd suggest starting in 3rd person present. For example (just an example to illustrate parallel writing, you can choose the way you prefer):
- Allows you to manually build a query. 
- Lists all the HTTP methods. 
- Indicates the API version for the request.

2022-07-22 20:54 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +- **Modify permissions**: you need to consent to the right permissions to be able to run a query. Read more about [consenting to permissions](#consent-to-permissions).
Edit for voice:
```suggestion
- **Modify permissions**: you need to consent to the right permissions to be able to run a query. For details, see [consenting to permissions](#consent-to-permissions).
```

2022-07-22 21:01 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +- **Response headers**: You can see the response headers here.
Lines 106 to 109: Could you please elaborate a bit more? This section is not providing enough guidance and it is quite important. For example, you can start with an H3 Visualize the response, and explain a bit further what to expect from the response preview and response headers tabs. Talk about the format, how to read the response, and how to interact with it. A user may or may not know that the response preview comes in JSON format and doesn't include the headers, which go in the headers tab. And I also noticed you can expand and collapse sections of the response body with the small arrows at the left. 

All of these is material for the section :)

2022-07-22 21:05 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +- **Response headers**: You can see the response headers here.
In addition, the other tabs are receiving their own H3s. If the intention of this topic is to give readers a tour by the product, it is a bit of a broken experience to give a different level of attention to tabs in the same category (visually speaking at least).

2022-07-22 21:08 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +Graph Explorer allows you to see Microsoft Graph Toolkit components that correspond to the API queries. A blue dot on the **Toolkit component** tab indicates that the Toolkit provides a component for
Edits:
```suggestion
Graph Explorer allows you to visualize Microsoft Graph Toolkit components that correspond to the API queries. A blue dot on the **Toolkit component** tab indicates that the Toolkit provides a component for the currently specified REST API query in Graph Explorer. You can conveniently copy the code for the component to your app.
```

In addition, for accessibility purposes, could you mention that at the right you have the code for the component and a visualization of how the component renders at the left?

2022-07-22 21:12 UTC, isvargasmsft commented on concepts/graph-explorer/graph-explorer-features.md
> +[Adaptive cards](https://adaptivecards.io/) are platform-agnostic snippets of UI, authored in JSON, that apps and services can openly exchange. When you run a query and an adaptive card is available,
In general, we avoid attributing animated behavior to non-animated objects. In this case, saying that something "appears".
```suggestion
[Adaptive cards](https://adaptivecards.io/) are platform-agnostic snippets of UI, authored in JSON, that apps and services can openly exchange. A blue dot on the **Adaptive cards** tab indicates that an adaptive card is available for the selected query.
```

2022-07-22 21:14 UTC, isvargasmsft requested changes
Hello @RabebOthmani, 

Great work in this PR. Thank you very much for the updates. 

Please take a look at a few suggestions I left regarding voice and style. Feel free to ping me on the side if you have questions. 

Here to help!

Isaac

2022-07-29 15:16 UTC, RabebOthmani commented on concepts/graph-explorer/graph-explorer-overview.md
> +With Graph Explorer, you can make requests to the Microsoft Graph APIs to retrieve, add, delete and update data. Your requests can send parameters, authorization details, and any body data you requir
@isvargasmsft what's referred to here is the request body so it is data specific to that body not just any object.

2022-07-29 15:19 UTC, opbld30 commented
Docs Build status updates of commit _[96a44d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96a44d42589f865f28091aa8b05f5a6318f82c86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207291517187339-17622/BuildReport?accessString=0914564614c4fa610a2173c00468fd3399960854f04fb3b3ea7c324ccfb67bad).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:27 UTC, opbld33 commented
Docs Build status updates of commit _[4152319](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4152319b5082d04f724162dff4efb7a7690be7d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011724171731-17622/BuildReport?accessString=47e0c2262f4a359e4eb087ba4762acfda7b66cd6db799a085943aa5dfbdb3cac).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:31 UTC, opbld34 commented
Docs Build status updates of commit _[95e2070](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95e2070af3b00d03e80164c58d1966ceaf3ae446)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011726220863-17622/BuildReport?accessString=ad97b8fc5be512a4d5befdee2fee95e90cf3458a7cb27494346d4529fae423a3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:33 UTC, opbld31 commented
Docs Build status updates of commit _[a9acf41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9acf41f94787bcc00e1ab515477bc60ee99b1d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011730028612-17622/BuildReport?accessString=c132951dde299534e5419b6cde0abbece0bf471f920e0f12247b5b42b93608f7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:35 UTC, opbld33 commented
Docs Build status updates of commit _[2a7250b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a7250b5b8cefdbdda110aaedbb101838dfafe44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011732363243-17622/BuildReport?accessString=a18c34651ee69140b679fc2a95112d4a881b2ebc35ffe5756436b167d8c91894).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:37 UTC, opbld32 commented
Docs Build status updates of commit _[5af4119](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5af4119ca093c8f41ffc68fcefff07ba5b67ede7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011734140729-17622/BuildReport?accessString=11f2defbfe15fa193b08e8a0584bfa6595fa0b55679ef1bddcb49be1cb3d9106).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:40 UTC, opbld31 commented
Docs Build status updates of commit _[732e8d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/732e8d5ed6481a2ce3beabf8b6467f17cf3cf836)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011737174345-17622/BuildReport?accessString=389894fb825b985c4247ea731939923ada9437f40201ddef46cf6c8da92232fd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-01 17:52 UTC, RabebOthmani commented on concepts/graph-explorer/graph-explorer-features.md
> +The user or administrator must grant Graph Explorer the correct permissions by using a consent process to access data in Microsoft Graph. You can consent to permissions in Graph Explorer by choosing
Done

2022-08-17 14:47 UTC, RabebOthmani commented on concepts/graph-explorer/graph-explorer-features.md
> +![Screenshot of Graph Explorer with the steps to consent to permissions highlighted](./images/modify-permissions-screenshot.png)
@isvargasmsft I'm not clear on this. All images are presented as ![ALT TEXT](image) , isn't that enough

2022-08-18 14:57 UTC, opbld34 commented
Docs Build status updates of commit _[06fad78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06fad78302129432da9ba4f07d072d791fe5746c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208181455461756-17622/BuildReport?accessString=bf5e6a8567bd703004263453946b78f626eb25fce7d54a0873354e87a2496cb3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post you [...]

2022-08-18 15:07 UTC, isvargasmsft approved these changes

2022-09-14 01:37 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +[Graph Explorer](https://developer.microsoft.com/graph/graph-explorer/) is a developer tool that lets you learn about Microsoft Graph APIs. It has a variety of features to help you on your journey. T
I suggest that we revise the last sentence as follows:

This article describes some of the important features of Graph Explorer and how to use them.

2022-09-14 01:38 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +The user or administrator must grant Graph Explorer the correct permissions by using a consent process to access data in Microsoft Graph. You can consent to permissions in Graph Explorer by choosing
The use of "might" here adds some ambiguity; can we change it to "will"?

2022-09-14 01:48 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +1. Go the avatar gear and choose the **Consent to permissions** option. This option contains the list of all available permissions.
What is the "avatar gear"?

2022-09-14 02:21 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +## Sidebar
Is the the correct term? Seems like a more standard term for this part of the tool would be "Left pane".

2022-09-14 02:29 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +### Consent to permissions
The structure of the article is currently a bit confusing, as we seem to have H2 headings for noun phrases that represent some element of the UI, and task-based H3 subsections. We need to think about a structure that makes the intent of the article clear to the reader. Either its a description of the UI elements and what they do, or it's a how-to article about using the tool to perform tasks. I recommend keeping it as the latter, which is the structure of the currently published topic and reflects the title "Work with Graph Explorer". Will readers use GE section by section, like go to the Header, then the Sidebar, etc., or will they want to complete a task and follow the UI to do so?

2022-09-14 02:31 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +The header allows you to sign in, view the tenant you are using and access your settings, helpful links and the survey to provide feedback for the tool.
If you keep this section, revise the text: "From the top navigation, you can sign in, view the tenant you're using, access your settings, and find helpful links and a feedback mechanism." The current sentence structure anthropomorphizes "header". Also we should refer to it as "top navigation". A header is like an H1, H2, etc. in an article.

2022-09-14 02:31 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- [History](#store-and-share-queries)
Per Isaac's comment, I think it will be more clear to refer to it as the left pane.

2022-09-14 02:33 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- [Sample queries](#get-started-with-microsoft-graph-apis)
If you're going to have jump links within the article, the link text should match the heading that its linking too. Currently this is an unclear experience and makes the reader think that the link is going to the wrong destination - the relationship between the link text and the target isn't clear.

2022-09-14 02:35 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +To get started with Microsoft Graph and get yourself familiar with Graph Explorer, the **Sample queries** feature provides a set of queries categorized by service that you can select and run.
Revise as: "The **Sample queries** tab provides a set of queries categorized by service that you can select and run to help you get started with Microsoft Graph API calls."

2022-09-14 22:20 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +The query box will be populated by the selected query. You can then make the request by clicking the Run query button.
Revise this text as:
"When you select a query, the selected query populates the query box. To try the request, choose **Run query**.

2022-09-14 22:21 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +### Explore all of the Microsoft Graph resources
Revise as "Explore resources".

2022-09-14 22:23 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +The Resources feature allows you to explore the resources on Microsoft Graph in their entirety, on both v1.0 and beta versions. Navigate the tree to browse for a specific resource or, alternatively,
Revise as: "Use the **Resources** tab to explore Microsoft Graph resources in the beta and v1.0 endpoints. Browse the list of resources or use the search bar to search for a specific resource."

2022-09-14 22:44 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +With the **Resources** tab you can export a collection of resources into a Postman collection:
Revise as: "From the **Resources** tab, you can export a collection of resources into a Postman collection by doing the following:".

2022-09-14 22:45 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +1. Once you complete adding resources, click on the **Preview collection** button.
Revise as: "When you're finished adding resources, choose **Preview collection**.

2022-09-14 22:47 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +1. From the collection view, you can review the resources and remove any if you chose to.
Revise as: "From the collection view, you can review the resources you selected and remove any if you choose."

2022-09-14 22:48 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +1. Click on **Download Postman collection** to download your collection.
Revise as: "Choose **Download Postman collection**."

2022-09-14 22:49 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +All queries you run in Graph Explorer are saved for 30 days in the **History** tab. In the **History** tab, you can:
In the second sentence, change "In" to "From".

2022-09-14 22:53 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +## Main work area
Can we call this something a little bit more clear, like "Query pain"?

2022-09-14 22:59 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +This area is where you will be spending most of your time on Graph Explorer. This area has everything you need to run a request:
Revise as: Use the query pane to run requests and see the responses. The query pane includes the following elements:".

We shouldn't imply that we know where our audience is going to be spending their time. ;)

2022-09-14 23:01 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- **Query box**: you can manually build your query.
The text after the colons in this bulleted list should consistently be capitalized. Also, please make the descriptions consistent, either noun or verb phrases. Here, the description seems incomplete - they can manually specify a query, but it also gets autopopulated if they select a query, right?

2022-09-14 23:03 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- **HTTP verbs**: a dropdown list of the HTTP methods.
So for example, if you wanted to consistently use verb phrases, you can revise this to say "Choose the HTTP verb from the dropdown list." Also, hmm, the UI element isn't actually called "HTTP verbs", so you need a different way to describe this; otherwise it's going to mislead the reader.

2022-09-14 23:04 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- **API version**: a dropdown list of the API versions available publicly.
This also isn't the the name of the UI element.

2022-09-14 23:05 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- **Modify permissions**: you need to consent to the right permissions to be able to run a query. For details, see [consenting to permissions](#consent-to-permissions).
For completeness, should we also include Request body and Request headers?

2022-09-14 23:06 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> + ![Screenshot of Graph Explorer highlighting the main work area](./images/run-query-tabs-screenshot.png)
Change "main work area" to "query pane" here too.

2022-09-14 23:08 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +This is also where you see:
This is kind of repetitive. Can we revise as something like: "When you run a query, you will see a **Response preview** and **Response headers** in the response pane." And then remove the two bullets.

2022-09-14 23:09 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +On top of query related features, the main work area also contains:
Revise as: "In addition to the response, this pane also includes:".

2022-09-14 23:10 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- [Microsoft Graph Toolkit Adaptive cards integration](#microsoft-graph-toolkit-integration)
I think we need to remove "Adaptive cards" from the link text here.

2022-09-14 23:11 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +- [Code snippets](#leverage-the-power-of-the-client-libraries)
We should following the order of the UI from left to right, so put code snippets first, and also rearrange the corresponding H3 sections to use the same order.

2022-09-14 23:11 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +Graph Explorer allows you to visualize Microsoft Graph Toolkit components that correspond to the API queries. A blue dot on the **Toolkit component** tab indicates that the Toolkit provides a compone
When we refer to the toolkit instead of Microsoft Graph Toolkit, toolkit is lowercase.

2022-10-14 15:28 UTC, opbld31 commented
Learn Build status updates of commit _[f3102d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3102d3960bbd2415332e27b3b69dcd600d46fd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210141525531467-17622/BuildReport?accessString=3d16939573c31c243a7dccf8b0f998e1e956784780d79b21fae119aa00b55716).

**Not [...]

2022-11-02 16:20 UTC, opbld30 commented
Learn Build status updates of commit _[2191ec7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2191ec7615dadc43c6fa083f69f44a8b9389a3dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211021609465297-17622/BuildReport?accessString=cc65326fbf7c6251088f267cb3f335a316e5b214d62a97516ff8e62cc2f2bfc3).

**Not [...]

2022-11-02 16:23 UTC, opbld31 commented
Learn Build status updates of commit _[868ad00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/868ad0038c06587806e944069d9aed082224db08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211021619572763-17622/BuildReport?accessString=11a8cd1d3cd8f43fa15373e1c7b3b0284637117fc06331a3cf2856c81fe8badf).

**Not [...]

2022-11-02 16:31 UTC, opbld34 commented
Learn Build status updates of commit _[7dc01b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dc01b9884f0a68674819827d93c24d7f47bf16d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211021627272803-17622/BuildReport?accessString=916535cffe0be346de9a91a6ab3c7f3aee09e772b6c854133386b84b979c32d0).

**Not [...]

2022-11-02 16:48 UTC, opbld32 commented
Learn Build status updates of commit _[13b2f4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13b2f4eba2ac1e8674c709621ac4d30904f86a0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/adaptive-cards-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adaptive-cards-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/code-snippets-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/code-snippets-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/consent-permissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/download-collection-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/download-collection-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-graph-toolkit-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-graph-toolkit-card.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/get-request.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/get-request.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/graph-explorer-screen.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-explorer-screen.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/header-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/header-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/history-tab-screenshot.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/history-tab-screenshot.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-17622) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |

This comment lists only the first 25 files in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211021634110478-17622/BuildReport?accessString=cf77b4f3bd234635b19d541bd72af75cbdaea48cb8d62159141e60d031bfa911).

**Not [...]

2022-11-02 16:54 UTC, isvargasmsft approved these changes

2022-11-03 03:16 UTC, opbld31 commented
Learn Build status updates of commit _[b3277c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3277c136c212a054a8a9e09bcaa9ad297ce5cfa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/browsersharedcookie-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersharedcookie-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-get?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-d262c1099fb7505d0e564a76cf3f0e4d-0cd28a49)
[api-reference/beta/api/browsersharedcookie-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersharedcookie-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersharedcookie-update?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-ad2f75aafd04def7e04c7dcf394fa08c-0cd28a49)
[api-reference/beta/api/browsersite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersite-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-get?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-05ce1c0bb5d99ab2316cd7dc47695a31-0cd28a49)
[api-reference/beta/api/browsersitelist-delete-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-delete-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-cc7363d8959dbf7931a60842f690fafa-0cd28a49)
[api-reference/beta/api/browsersitelist-delete-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-delete-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-delete-sites?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-175934e0c805d64c6cb5dd5b11028c03-0cd28a49)
[api-reference/beta/api/browsersitelist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-get?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-c29ebab833372aff1baa5472699e7e26-0cd28a49)
[api-reference/beta/api/browsersitelist-list-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-list-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-5d563f3370c61292bda9a1bd199c74f7-0cd28a49)
[api-reference/beta/api/browsersitelist-list-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-list-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-list-sites?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-743a1c4a7a89f1dd21a9ded0d8e76616-0cd28a49)
[api-reference/beta/api/browsersitelist-post-sharedcookies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-post-sharedcookies.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sharedcookies?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-a84dbb7542ac47f10dc911ceb5fff9cc-0cd28a49)
[api-reference/beta/api/browsersitelist-post-sites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-post-sites.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-post-sites?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-c4441169fb880ad1ee393058c4e6bc3b-0cd28a49)
[api-reference/beta/api/browsersitelist-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-publish.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-publish?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-e5de0ee02ab814bd1e5c429c99b8a992-0cd28a49)
[api-reference/beta/api/browsersitelist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersitelist-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersitelist-update?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-75cdf49be2624f09f663c73670494e61-0cd28a49)
[api-reference/beta/api/browsersite-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/browsersite-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/browsersite-update?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-b6b85083ee65851f75fdf7acf8c29cc8-0cd28a49)
[api-reference/beta/api/internetexplorermode-delete-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/internetexplorermode-delete-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-delete-sitelists?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-9a5ff5423ae5e6ff0f0fbdc9cdc6ded6-0cd28a49)
[api-reference/beta/api/internetexplorermode-list-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/internetexplorermode-list-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-list-sitelists?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-70383cf967207b65801e80b6f4b71354-0cd28a49)
[api-reference/beta/api/internetexplorermode-post-sitelists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/api/internetexplorermode-post-sitelists.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/internetexplorermode-post-sitelists?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-86e047ad6a55ea1081be87efec9846b8-0cd28a49)
[api-reference/beta/resources/browser-edge-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/resources/browser-edge-api-overview.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta&branch=pr-en-us-17622) (graph-rest-beta) | [Details](#user-content-def463297d97a1ac4378a0225dd532de-0cd28a49)
[api-reference/beta/resources/browsersharedcookie.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/RabebOthmani-GEUpdates/api-reference/beta/resources/browsersharedcookie.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/browsersharedcookie?view=graph-rest-beta&branch=pr-en-us-17622) (grap [...]

2022-11-03 03:31 UTC, merged