Adding alternate key support for app entity
microsoftgraph/microsoft-graph-docs pull request #17677
Opened 2022-07-13 20:05 UTC by aricrowe57

2022-07-13 20:09 UTC, opbld31 commented
Docs Build status updates of commit _[cc0aadf](https://github.com/aricrowe57/microsoft-graph-docs/commits/cc0aadfaba44f8d08f6b2f279daeb0c8a993c15b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207132007349912-17677/BuildReport?accessString=cf5f7e67e4a1efd46315f6bc22229a421d8fc751c262b40a6102978173f0dd05).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 20:29 UTC, opbld30 commented
Docs Build status updates of commit _[c2bdd8e](https://github.com/aricrowe57/microsoft-graph-docs/commits/c2bdd8ef063d440abb51825c657d05c7a501eca1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-update.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/resources/application.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207132027507153-17677/BuildReport?accessString=f7ad2c6eb6a503028b100ddcdfb8090f280ba4150d8e492ed94f4b419aa43629).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 20:31 UTC, aricrowe57 commented
Hi @FaithOmbongi , we are adding 'alternate key support' for the application entity, so the appId can be used as an alternate key (instead of just object ID).  Hopefully this docs PR is explanatory enough of what that is.

This PR is still in draft state, but I'm hoping to get a few questions answered before progressing any further on it. 

1. Do you think the example HTTP requests, where I show making the same HTTP call with the primary key syntax and alternate key syntax, should be replicated across all application methods (i.e., should I also add similar info to 'addKey' and 'removeKey', etc.)
2. If so, are you able to review what I have so I don't replicate some bad updates across various different articles?
3. Any other comments on what we have so far?

Thanks!

2022-07-19 08:13 UTC, FaithOmbongi commented on api-reference/beta/api/application-delete.md
> +DELETE /applications/(appId='{appId}')
Hi @aricrowe57 - A globally applicable suggestion to make the block shorter.
```suggestion
You can address the application using either its **id** or **appId**. **id** and **appId** are referred to as the **Object ID** and **Application (Client) ID** respectively, in the Azure portal.
<!-- { "blockType": "ignored" } -->
```http
DELETE /applications/{id}
DELETE /applications/(appId='{appId}')
```

2022-07-19 08:14 UTC, FaithOmbongi commented
> Hi @FaithOmbongi , we are adding 'alternate key support' for the application entity, so the appId can be used as an alternate key (instead of just object ID). Hopefully this docs PR is explanatory enough of what that is.
> 
> This PR is still in draft state, but I'm hoping to get a few questions answered before progressing any further on it.
> 
> 1. Do you think the example HTTP requests, where I show making the same HTTP call with the primary key syntax and alternate key syntax, should be replicated across all application methods (i.e., should I also add similar info to 'addKey' and 'removeKey', etc.)
> 2. If so, are you able to review what I have so I don't replicate some bad updates across various different articles?
> 3. Any other comments on what we have so far?
> 
> Thanks!

Hi @aricrowe57

1.) Yes - the HTTP request syntax should be replicated in all docs that support it. 
           Q: Is this for both beta & v1.0 or is the capability for beta only?

2,3.) I also recommend adding a changelog so this capability doesn't pass under the radar. A suggested changelog object 👇🏾. If this capability applies to v1.0 as well, please add another object referencing v1.0 (use a different ID GUID).

```json
{
    "ChangeList": [
      {
        "Id": "b1b69af7-630f-4183-a152-ebffa1a4bf27",
        "ApiChange": "Property",
        "ChangedApiName": "appId",
        "ChangeType": "Addition",
        "Description": "Added support for addressing an [application](https://docs.microsoft.com/graph/api/resources/application?view=graph-rest-beta) using the application **appId** as the alternate key. You can now address an application via either the primary key **id** or the alternate key **appId** as the path parameter.",
        "Target": "application"
      }
    ],
    "Id": "b1b69af7-630f-4183-a152-ebffa1a4bf27",
    "Cloud": "Prod",
    "Version": "beta",
    "CreatedDateTime": "2021-08-19T00:00:00.077762Z",
    "WorkloadArea": "Application",
    "SubArea": ""
}
```

2022-08-03 16:45 UTC, opbld30 commented
Docs Build status updates of commit _[c9481bd](https://github.com/aricrowe57/microsoft-graph-docs/commits/c9481bd2aebdd0210780c65eda0a14c8aea534a2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-911b77d7)

<a id="911b77d7"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031645012424-17677/BuildReport?accessString=22569ee4455353cc3ea925209fec2cb09c9e4a9645c819b56cc6a40d7829fa8f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 16:54 UTC, opbld31 commented
Docs Build status updates of commit _[5397f95](https://github.com/aricrowe57/microsoft-graph-docs/commits/5397f95b91cbc33aecb59726a102fc002b9da52b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-addkey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-addpassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removekey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-removekey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removepassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removepassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-removepassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-setverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-setverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-setverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-unsetverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-unsetverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-unsetverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-update.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-s [...]

2022-08-03 17:00 UTC, opbld33 commented
Docs Build status updates of commit _[0f78b8a](https://github.com/aricrowe57/microsoft-graph-docs/commits/0f78b8a11bc6cafb3c902b43a37f5a0333e03b65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-addkey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-addpassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-delete-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removekey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removekey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-removekey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removepassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removepassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-removepassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-setverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-setverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-setverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-unsetverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-unsetverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-unsetverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-update.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-s [...]

2022-08-03 17:02 UTC, aricrowe57 commented
@FaithOmbongi , to answer your question above - this is just for /beta for now.  Will do another PR for /v1.0 soon.  This is ready for review.  Thanks!

2022-08-17 19:03 UTC, FaithOmbongi requested changes
Hi @aricrowe57 - Just minor fixes/oversights to fix.

I notice this capability hasn't yet been deployed to beta so we can't test. The schema PR also related to PPE, not Prod-beta. Please only merge the PR when the capability and schema are live.

2022-08-29 11:33 UTC, FaithOmbongi commented
Hi @aricrowe57 - This PR has review feedback yet to be addressed, all minor fixes. Please look at addressing them. Meanwhile, your PR is attracting merge conflicts in the changelog.

2022-09-08 14:51 UTC, FaithOmbongi commented
Hi @aricrowe57 - I realize I'd requested the wrong changes in my previous review, confusing application docs with serviceprincipal docs. My bad 🤦🏾‍♀️. Only one comment remains valid and your PR will be good to go once the capability is live.

PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/18260#pullrequestreview-1100873635 introduces changes to service principals.

2022-09-09 18:06 UTC, FaithOmbongi commented
Heads up @aricrowe57 - I see the schema changes are now live.

```
 <Annotation Term="OData.Community.Keys.V1.AlternateKeys">
          <Collection>
            <Record Type="OData.Community.Keys.V1.AlternateKey">
              <PropertyValue Property="Key">
                <Collection>
                  <Record Type="OData.Community.Keys.V1.PropertyRef">
                    <PropertyValue Property="Alias" String="appId" />
                    <PropertyValue Property="Name" PropertyPath="appId" />
                  </Record>
                </Collection>
              </PropertyValue>
            </Record>
          </Collection>
        </Annotation>
```

Please get this PR ready to merge. Thank you.

2022-11-29 09:55 UTC, opbld30 commented
Learn Build status updates of commit _[d5df174](https://github.com/aricrowe57/microsoft-graph-docs/commits/d5df1747339ba6be8a703df7b791b60b1d64bf0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-addkey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addkey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-addpassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removekey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removekey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-removekey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removepassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removepassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-removepassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-setverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-setverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-setverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-unsetverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-unsetverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-unsetverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-update.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/aricrowe57/microsoft-grap [...]

2022-11-29 09:59 UTC, FaithOmbongi approved these changes
Pushed commits to:

- Fix syntax
- Update changelog date

2022-11-29 10:13 UTC, opbld32 commented
Learn Build status updates of commit _[23896db](https://github.com/aricrowe57/microsoft-graph-docs/commits/23896db6d05f892524089fb91725819d290049da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-addkey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addkey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-addpassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removekey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removekey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-removekey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removepassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removepassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-removepassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-setverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-setverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-setverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-unsetverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-unsetverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-unsetverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-update.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/aricrowe57/microsoft-grap [...]

2022-11-29 10:23 UTC, opbld32 commented
Learn Build status updates of commit _[fc593b8](https://github.com/aricrowe57/microsoft-graph-docs/commits/fc593b8105c49266357ab67a47d453db49063988)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-addkey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addkey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-addpassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-delete-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-delete-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-delete-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-get.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-list-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-list-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-list-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-federatedidentitycredentials.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-federatedidentitycredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-federatedidentitycredentials?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-owners.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenissuancepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenissuancepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-tokenissuancepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-post-tokenlifetimepolicies.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-post-tokenlifetimepolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removekey.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removekey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-removekey?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-removepassword.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-removepassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-removepassword?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-setverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-setverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-setverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-unsetverifiedpublisher.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-unsetverifiedpublisher.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-unsetverifiedpublisher?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/application-update.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/application-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-delete.md](https://github.com/aricrowe57/microsoft-graph-docs/blob/alt-key-syntax-for-apps/api-reference/beta/api/federatedidentitycredential-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/federatedidentitycredential-delete?view=graph-rest-beta&branch=pr-en-us-17677) (graph-rest-beta) |
[api-reference/beta/api/federatedidentitycredential-get.md](https://github.com/aricrowe57/microsoft-grap [...]

2022-11-29 15:58 UTC, aricrowe57 commented
#sign-off

2022-11-30 03:13 UTC, merged