Monetization update draft
microsoftgraph/microsoft-graph-docs pull request #17672
Opened 2022-07-13 07:47 UTC by MariaWissler

2022-07-13 07:47 UTC, opbld31 commented
Docs Build status updates of commit _[0f5ab26](https://github.com/MariaWissler/microsoft-graph-docs/commits/0f5ab26cba1d6373bf436d6907150f4048580e83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bf17e83d)

<a id="bf17e83d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130747052272-17672/BuildReport?accessString=f7f9596ebdc6332701c4af20e9ffb9ff56614843c6ebb1467fa111711967f7bf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 07:50 UTC, opbld33 commented
Docs Build status updates of commit _[af004ff](https://github.com/MariaWissler/microsoft-graph-docs/commits/af004ff8df5c495a735a9860099dddd8948b6737)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6f06f814)

<a id="6f06f814"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207130749416302-17672/BuildReport?accessString=e248a3a6721040cbaddf33df73e51c25ecbdad8daa878aa402dae2abb7729032).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 17:46 UTC, opbld33 commented
Docs Build status updates of commit _[5a27980](https://github.com/MariaWissler/microsoft-graph-docs/commits/5a27980e98de534496e8826343a5e4f701edab25)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-8db43c03)

<a id="ca725731463f0a3f3162bbc2579e6e5a-8db43c03"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 39, Column 100**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#recent-updates-and-price-for-additional-use' in 'teams-licenses.md'.`````
 - **Line 51, Column 100**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#recent-updates-and-price-for-additional-use' in 'teams-licenses.md'.`````
 - **Line 60, Column 84**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#recent-updates-and-price-for-additional-use' in 'teams-licenses.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131744281415-17672/BuildReport?accessString=f9bf656adc71b79d444cdd9770a9df6d26deed3fd5005612bd95f9b36aea3309).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 17:53 UTC, opbld30 commented
Docs Build status updates of commit _[1d9120d](https://github.com/MariaWissler/microsoft-graph-docs/commits/1d9120d4259202201b6e2e423e2d75462f42abf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131749519546-17672/BuildReport?accessString=cc2f65327198a8ac7c4ebc209483f410b92963f1d88de8442afb7e956308244a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 17:55 UTC, opbld33 commented
Docs Build status updates of commit _[6cc50bf](https://github.com/MariaWissler/microsoft-graph-docs/commits/6cc50bf4e6fe5577db46c462a77f85338b05a4b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131753439745-17672/BuildReport?accessString=597cd10706dc75aafb0d97155be94de85ffe9fa161711fbde3fa775e257fef66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 18:00 UTC, opbld31 commented
Docs Build status updates of commit _[a8b8df4](https://github.com/MariaWissler/microsoft-graph-docs/commits/a8b8df469d159af37dc8520116b4d855a261dab4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131758046773-17672/BuildReport?accessString=05145c3c3ce64cf955c9fe8cb669ed243f68c566a1c740bc9b470355845dbfee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 18:05 UTC, opbld32 commented
Docs Build status updates of commit _[ca29479](https://github.com/MariaWissler/microsoft-graph-docs/commits/ca294790b1db42fd40bc5190eab2295cb3dadad8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131802450168-17672/BuildReport?accessString=ea67f63065656b5600c147c4358b5067c787bcb020415d59f89861ec5c05c792).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 18:08 UTC, opbld34 commented
Docs Build status updates of commit _[173005e](https://github.com/MariaWissler/microsoft-graph-docs/commits/173005efe7dafbadae443b1bb49603964fa15842)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207131806047440-17672/BuildReport?accessString=afb3d94b9d726198710eba134b704791f5e09aa38c00e1ac85eda2dbb4f2ceb3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 20:19 UTC, opbld32 commented
Docs Build status updates of commit _[22f82da](https://github.com/MariaWissler/microsoft-graph-docs/commits/22f82dacbb8767bd68caed18552ecffbd2121633)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207132016599251-17672/BuildReport?accessString=0b6a07ca22a98d12eba1ea96523c67c95ad8537778126d051206de5355beb68c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 21:50 UTC, opbld30 commented
Docs Build status updates of commit _[2fc844d](https://github.com/MariaWissler/microsoft-graph-docs/commits/2fc844da4eac65b5308dd5918059795115c71c71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207132148350587-17672/BuildReport?accessString=1d92f08883909c274360798fae5416bc9c3207466882a55a92d73c7a83a304df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-13 21:53 UTC, opbld34 commented
Docs Build status updates of commit _[fd0e4f6](https://github.com/MariaWissler/microsoft-graph-docs/commits/fd0e4f664fb65192e30cab94b9ea3eb8b4a4377a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207132151022963-17672/BuildReport?accessString=216ddf6d1905654817103e9e4f7bc2c15db09bfaf49d18704d0fe2893792b00c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 20:23 UTC, nkramer commented on concepts/teams-licenses.md
> +* [Change notifications: chatMessage](/graph/api/subscription-post-subscriptions)
We also charge for change notifications for conversationMember

2022-07-14 20:23 UTC, nkramer commented on concepts/teams-licenses.md
> +| [Get messages across all channels](/graph/api/channel-getallmessages)| Any team member | 1600 messages per user per month per app | $0.00075 per message |  Charge of 1 message per API request.Seede
"Charge of 1 message per API request." -> "To discourage frequent polling, API requests that return an empty list of messages will charge one message." Okay, that's not perfect either, but hopefully that helps.

2022-07-14 20:23 UTC, nkramer commented on concepts/teams-licenses.md
> +| Model | Sample functions | License required | Azure subscription required |
Since the title of the section is "licensing and seeded capacity", I would expect the table to talk about seeded capacity. To simplify the table, for model A maybe you just say "Some; see below for details" since the capacity varies by API.

2022-07-14 20:55 UTC, opbld33 commented
Docs Build status updates of commit _[1f2d83a](https://github.com/MariaWissler/microsoft-graph-docs/commits/1f2d83af921d6b1a4cdea415b2636261ba374a8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207142052417882-17672/BuildReport?accessString=cb218c9e6560b4283e627ec00d9fc80df8ea2a4e553abb70ca3feda7d0c44b53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 05:37 UTC, opbld34 commented
Docs Build status updates of commit _[db8d312](https://github.com/MariaWissler/microsoft-graph-docs/commits/db8d312910621c2d14bc435bee3768ccabcce20b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-82612e66)

<a id="ca725731463f0a3f3162bbc2579e6e5a-82612e66"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 148, Column 191**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'cost-management-billing/manage/programmatically-create-subscription'.`````
 - **Line 152, Column 525**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cost-management-billing/'.`````
 - **Line 154, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 15, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 16, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 151, Column 97**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207150535289247-17672/BuildReport?accessString=c71a42e943f2858aa2d306ee014e5669d6fdc809ec05cc9c17305a70432d9fda).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 22:38 UTC, opbld31 commented
Docs Build status updates of commit _[48a465e](https://github.com/MariaWissler/microsoft-graph-docs/commits/48a465e8a720436d00cdcd5f1b42cd691113824f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-04c98bd5)

<a id="ca725731463f0a3f3162bbc2579e6e5a-04c98bd5"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 148, Column 191**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'cost-management-billing/manage/programmatically-create-subscription'.`````
 - **Line 152, Column 525**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cost-management-billing/'.`````
 - **Line 154, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 15, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 16, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 151, Column 97**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207152236534658-17672/BuildReport?accessString=58ca3eba936ead9d38c4431a431563ec59c4728b25db82b7b3c3cbe2f49b28b4).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 23:43 UTC, opbld30 commented
Docs Build status updates of commit _[9a77344](https://github.com/MariaWissler/microsoft-graph-docs/commits/9a7734421212a04449e161a5d16f4ac02080789a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-992e7657)

<a id="ca725731463f0a3f3162bbc2579e6e5a-992e7657"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 137, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 147, Column 191**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'cost-management-billing/manage/programmatically-create-subscription'.`````
 - **Line 150, Column 525**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cost-management-billing/'.`````
 - **Line 152, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 18, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 19, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 149, Column 97**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207152341245026-17672/BuildReport?accessString=cfeb02408206b2f843a1a4bb0ebf0a1489249c9bcbe0d039ada0a9f8d239cf4e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 23:53 UTC, opbld34 commented
Docs Build status updates of commit _[ffc4a4c](https://github.com/MariaWissler/microsoft-graph-docs/commits/ffc4a4ca5c93d8e0647c31a866658b5e14d8f230)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-52ac1d00)

<a id="ca725731463f0a3f3162bbc2579e6e5a-52ac1d00"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 145, Column 525**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cost-management-billing/'.`````
 - **Line 147, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 18, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 19, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 144, Column 97**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207152351443265-17672/BuildReport?accessString=f54168b259f7796294cf1586c559430523911bad4c79a3335406d333e32dc8a2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 05:23 UTC, opbld34 commented
Docs Build status updates of commit _[ce27939](https://github.com/MariaWissler/microsoft-graph-docs/commits/ce279395b69244e599f6c9ec273fce2560b87c03)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-dc64cc33)

<a id="ca725731463f0a3f3162bbc2579e6e5a-dc64cc33"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 145, Column 525**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure/cost-management-billing/'.`````
 - **Line 147, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 18, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 19, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 144, Column 97**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160521035096-17672/BuildReport?accessString=9182defa6e293fefe1ab7242517e6d4cdd2037b3921c5a80c2fc375b11134a83).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 06:22 UTC, opbld34 commented
Docs Build status updates of commit _[e061c4c](https://github.com/MariaWissler/microsoft-graph-docs/commits/e061c4c7955510efe1023d534df09ddaeda45d96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-d8403bbd)

<a id="ca725731463f0a3f3162bbc2579e6e5a-d8403bbd"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 137, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 152, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 18, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 19, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 149, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160620296677-17672/BuildReport?accessString=83078da017ebbf26f27caa9f05602070bf730ea3d7c56e53c63f472c197755f6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 06:38 UTC, opbld34 commented
Docs Build status updates of commit _[824b8ad](https://github.com/MariaWissler/microsoft-graph-docs/commits/824b8ad74711790fda6c70d9c99be8f9689047a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) | [Details](#user-content-ca725731463f0a3f3162bbc2579e6e5a-39cf6b17)

<a id="ca725731463f0a3f3162bbc2579e6e5a-39cf6b17"></a>
### [concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md)
 - **Line 146, Column 30**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'azure-consumption-commitment-enrollment'.`````
 - **Line 18, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#chatmessage`````
 - **Line 19, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#conversationmember`````
 - **Line 143, Column 92**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/teams-api-overview?view=graph-rest-beta#polling-requirements`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160636191637-17672/BuildReport?accessString=35b73b776cb2642a96cb675a869c825b60b711a2de8cf88dd9f60add99f63d89).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 07:05 UTC, opbld34 commented
Docs Build status updates of commit _[c11e150](https://github.com/MariaWissler/microsoft-graph-docs/commits/c11e1506275c9bda10c07c63dcd71e2586b8e055)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160701274323-17672/BuildReport?accessString=1eb7d84c16a751259ef4bb6096e7332b87a9251aa3a173ff2b6d03db943e0720).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-16 07:07 UTC, opbld30 commented
Docs Build status updates of commit _[09aba48](https://github.com/MariaWissler/microsoft-graph-docs/commits/09aba48b061eea82b98ba27c43807231a04edd7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207160703348359-17672/BuildReport?accessString=2b8df09cbe3e05bfea00c505741c4479bf555a7be3f2387cb0d64c7bb6c9c07d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 03:56 UTC, opbld32 commented
Docs Build status updates of commit _[7a5c8d4](https://github.com/MariaWissler/microsoft-graph-docs/commits/7a5c8d42c765aabe97cd9991ece53972a4a189ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190354246710-17672/BuildReport?accessString=91a64f78cb229ae906af0dfe8b5def2b7412777ada69d3274ab8bd815e33926c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 04:10 UTC, opbld34 commented
Docs Build status updates of commit _[3e99a99](https://github.com/MariaWissler/microsoft-graph-docs/commits/3e99a993bda29798c9119e9301c325e3fd7f4ff9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190407551887-17672/BuildReport?accessString=c627abdc2100faf736626e5014c23a948378944762a18728a35984a99a71aff7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 04:15 UTC, opbld32 commented
Docs Build status updates of commit _[56bb13b](https://github.com/MariaWissler/microsoft-graph-docs/commits/56bb13b8a24c2ce3f851face2942119a918d2eb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207190412483202-17672/BuildReport?accessString=b0fcbbe0cf4e0387a008088efec30d1579909e82297ebfdb49f622a77037abad).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 18:27 UTC, opbld32 commented
Docs Build status updates of commit _[9c1de56](https://github.com/MariaWissler/microsoft-graph-docs/commits/9c1de5681d95bafff60299dd4dc6d9744fe84290)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207201824550294-17672/BuildReport?accessString=47d54a1b6f3a00bc5d95ac9f5db51af4b05e35869f54775cf7dc2daad6244230).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 21:41 UTC, opbld33 commented
Docs Build status updates of commit _[d4febed](https://github.com/MariaWissler/microsoft-graph-docs/commits/d4febedd90c6b9c44e208c44fa65a1f54f0b4024)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207252139586060-17672/BuildReport?accessString=c23e121f205b52bf68aacab6a16afa1916335760af36cc87f070845f225ae261).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 17:11 UTC, opbld31 commented
Docs Build status updates of commit _[8b21d26](https://github.com/MariaWissler/microsoft-graph-docs/commits/8b21d269314200acfa5110e5f8fe5d34655f15e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207261709285438-17672/BuildReport?accessString=3c547a88f58e4af081f4e0eb89284d17ae899305c33a1f4d93406a0665384fd1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 19:58 UTC, Danielabom commented on concepts/teams-licenses.md
> +> Active pricing events for these APIs started on July 5 2022. We require applications to complete this [form](https://aka.ms/teamsgraph/protectedApis_az) to provide an active Azure subscription for
```suggestion
> Active pricing events for these APIs started on July 5, 2022. We require applications to complete this [form](https://aka.ms/teamsgraph/protectedApis_az) to provide an active Azure subscription for billing purposes. For more details, see [Payment and billing updates] (#payment-and-billing-updates).
```

2022-07-26 20:01 UTC, Danielabom commented on concepts/teams-licenses.md
> +| [Get messages across all channels](/graph/api/channel-getallmessages)| Any team member | 1600 messages per user per month per app | $0.00075 per message | Requests returning an empty list, will be
```suggestion
| [Get messages across all channels] (/graph/api/channel-getallmessages)| Any team member | 1600 messages per user per month per app | $0.00075 per message | Requests returning an empty list will be charged one message. Seeded capacity is shared with chat export. |
```

2022-07-26 20:02 UTC, opbld34 commented
Docs Build status updates of commit _[679f1a7](https://github.com/MariaWissler/microsoft-graph-docs/commits/679f1a77cb8f873509210420b491fd7f78d7b958)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262000056752-17672/BuildReport?accessString=eff636027190fe9b95bbe44430e5c4cdb0c98b8029d26040525d51ef209aee5e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 20:04 UTC, opbld34 commented
Docs Build status updates of commit _[3e02ab3](https://github.com/MariaWissler/microsoft-graph-docs/commits/3e02ab390e481be49e85e972effbc27a6c021a5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262002099839-17672/BuildReport?accessString=bf4672e042613944479d81940d156c0f02aae2a9a497305294af6175be14044e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 20:09 UTC, Danielabom commented on concepts/teams-licenses.md
> +In October 2021 we [communicated](https://devblogs.microsoft.com/microsoft365dev/announcing-general-availability-of-microsoft-graph-export-api-for-microsoft-teams-messages/#license-requirements-for-m
```suggestion
In October 2021 we [communicated](https://devblogs.microsoft.com/microsoft365dev/announcing-general-availability-of-microsoft-graph-export-api-for-microsoft-teams-messages/#license-requirements-for-microsoft-graph-api-for-teams-export-and-dlp) upcoming charges for the consumption of these APIs; on July 5, 2022, these prices take effect as [previously announced] (https://devblogs.microsoft.com/microsoft365dev/upcoming-billing-changes-for-microsoft-graph-apis-for-teams-messages/). 
```

2022-07-26 20:12 UTC, opbld34 commented
Docs Build status updates of commit _[21ef2ea](https://github.com/MariaWissler/microsoft-graph-docs/commits/21ef2ea5ed03cca1e11389852a2ae730aae696fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262010126969-17672/BuildReport?accessString=b519a3588e0bb4a8522fb62fa22c0a6fe9d25b0a3310a7051d6121c7ad7f4f2b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 20:13 UTC, Danielabom commented on concepts/teams-licenses.md
> +| What should I expect after providing an Azure subscription ? | You can continue calling these metered APIs, we will contact the email provided in the request form to onboard the registered applicat
```suggestion
| What should I expect after providing an Azure subscription? | ou can continue calling these metered APIs; we will contact the email provided in the request form to onboard the registered application to billing. |
```

2022-07-26 20:15 UTC, Danielabom commented on concepts/teams-licenses.md
> +| Do I need to provide an Azure suscription if my application is not calling metered APIs ? | No. If you need to call other APIs please refer to the request form in [protected APIs](/graph/teams-prot
```suggestion
| Do I need to provide an Azure subscription if my application is not calling metered APIs? | No. If you need to call other APIs, please refer to the request form in [protected APIs] (/graph/teams-protected-apis). |
```

2022-07-26 20:22 UTC, Danielabom commented on concepts/teams-licenses.md
> +| What happens if no Azure subscription is provided ? | •  No payment related errors if the application is not calling metered APIs. <br> •  If no model is being passed, `evaluation model` will be us
```suggestion
| What happens if no Azure subscription is provided? | • No payment-related errors if the application is not calling metered APIs. <br> • If no model is being passed, the `evaluation model` value will be used by default. <br> • If calling a metered API passing `model=A` a Microsoft 365 E5 eligible license and Azure subscription should be provided. <br> • If passing `model=B` when calling metered APIs, an active Azure subscription should be provided. <br> |
```

2022-07-26 20:25 UTC, Danielabom commented on concepts/teams-licenses.md
> +| Who is responsible for the payment in case of multitenat apps ? | The organization that owns the app registration. |
```suggestion
| Who is responsible for the payment in the case of multitenant apps? | The organization that owns the app registration. |
```

2022-07-26 20:26 UTC, Danielabom commented on concepts/teams-licenses.md
> +| Is there a charge when no message is returned using any model ? | To discourage frequent [polling](/graph/api/resources/teams-api-overview), API requests that return an empty list of messages will
```suggestion
| Is there a charge when no message is returned using any model ? | To discourage frequent [polling](/graph/api/resources/teams-api-overview), API requests that return an empty list of messages will be charged one message. In the case of `evaluation model`, the call will count towards the 500 messages per month per app allowed. | 
```

2022-07-26 20:28 UTC, Danielabom requested changes
Hi @MariaWissler , I committed some small changes, please review them. Thanks.

2022-07-26 21:53 UTC, opbld34 commented
Docs Build status updates of commit _[6ce1528](https://github.com/MariaWissler/microsoft-graph-docs/commits/6ce15283e39ccefd1fd87601943be52c244e097d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262151527867-17672/BuildReport?accessString=82d15f246e8d64f92a835c73a6bcb1c0c31544ad44f07f76ce0decea30cf8790).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 22:11 UTC, opbld31 commented
Docs Build status updates of commit _[4107e22](https://github.com/MariaWissler/microsoft-graph-docs/commits/4107e228a0162bc0513030918294cf9d4c03bb63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262210003060-17672/BuildReport?accessString=d28c96e1f86522487bff1edcf31cdeb1d9e64b81f9c0514bc2fdfdaf87ef1d8f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 22:18 UTC, opbld31 commented
Docs Build status updates of commit _[f9215b3](https://github.com/MariaWissler/microsoft-graph-docs/commits/f9215b3437501ee0a392ec68b8776b8e250d36c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262215231112-17672/BuildReport?accessString=98602e6c6d330b6d161f4a189f319d67906a14d8add09240110003c7fd08ced0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 22:20 UTC, opbld31 commented
Docs Build status updates of commit _[1af0e01](https://github.com/MariaWissler/microsoft-graph-docs/commits/1af0e010d5def80498b164d48bc4fc092b591cc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262216031979-17672/BuildReport?accessString=b7e18c38b6add985c1283d46f6e8f1d40505dd8f5abafeac67ddda1aca67e6e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 00:11 UTC, opbld30 commented
Docs Build status updates of commit _[a658442](https://github.com/MariaWissler/microsoft-graph-docs/commits/a658442277326e14724e62d71a883cb5cd4c3ed9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207270008207947-17672/BuildReport?accessString=4cd0dc92b56ed426f626b3e4a728b9d4e26549dc79cf289037542aa471ea0faa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 17:21 UTC, opbld34 commented
Docs Build status updates of commit _[fde26e8](https://github.com/MariaWissler/microsoft-graph-docs/commits/fde26e83cb78585f0563000d2c0849b498b770bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-licenses.md](https://github.com/MariaWissler/microsoft-graph-docs/blob/monetization_updates/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17672) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207271718091945-17672/BuildReport?accessString=f474d5464c4523a43ffce0bc2568508420fe9e525e9063169702e5ad404b2d75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 16:16 UTC, Danielabom approved these changes
The changes requested are in place. Thanks

2022-08-02 04:34 UTC, merged