Release teams message in graph beta endpoint
microsoftgraph/microsoft-graph-docs pull request #17686
Opened 2022-07-14 08:49 UTC by yiwenwang-ms

2022-07-14 08:51 UTC, opbld30 commented
Docs Build status updates of commit _[6df255a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6df255a97efd21b21917f89bd2b94023129a084c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) | [Details](#user-content-3df07db36f540b94b746b72c8fbf80f5-c617c5db)
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |

<a id="3df07db36f540b94b746b72c8fbf80f5-c617c5db"></a>
### [concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md)
 - **Line 9, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Use the Microsoft Search API to search Outlook messages' is duplicated with other articles: 'search-concept-chat-messages.md(9,1), search-concept-messages.md(9,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207140849414842-17686/BuildReport?accessString=1603f711e2987a7c3d7924082783f5d637e6257b7ced642c84ef739502c3493a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 16:31 UTC, isvargasmsft commented on concepts/search-concept-chat-messages.md
> +---
Please add this new concept topic to the conceptual TOC, under Search.

2022-08-01 17:20 UTC, isvargasmsft commented on concepts/search-concept-chat-messages.md
> +```
Would you be so kind to add the response to this example, please?

2022-08-01 17:23 UTC, isvargasmsft commented on concepts/search-concept-chat-messages.md
> +
Would you please provide context to this table? Please explain what these scopes are, the value they provide and how to use them. 
In addition, is this the best place in the article for this?

2022-08-01 17:24 UTC, opbld32 commented
Docs Build status updates of commit _[8840c03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8840c03b728e5aa36745c75970667ebbffb7e24d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208011720444168-17686/BuildReport?accessString=ff5c2dcc71c7f1b5811da09c420fcf1aec3147f87b4044b8082879ff21f092d5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 17:26 UTC, isvargasmsft commented on concepts/search-concept-chat-messages.md
> +### Example 3: Search Teams Message with KQL
What does KQL stand for?

2022-08-01 19:53 UTC, isvargasmsft requested changes
Hello @yiwenwang-ms, 

Thank you very much for your work in this PR. I left a few comments. My main concern is finding an optimal way to present the table of supported scope terms. 

Please ping me on the side if you have questions. 

Kind regards, 

Isaac

2022-08-03 04:59 UTC, yiwenwang-ms commented on concepts/search-concept-chat-messages.md
> +---
Done

2022-08-03 05:01 UTC, opbld34 commented
Docs Build status updates of commit _[7030d91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7030d911abc67856e70bb578a4c0f846322df915)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030458577424-17686/BuildReport?accessString=c856a1609a404cefaaaa0635705f81ec67f92df4d78513643d021477a08e3efe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 05:02 UTC, yiwenwang-ms commented on concepts/search-concept-chat-messages.md
> +### Example 3: Search Teams Message with KQL
Added a reference to the introduction of KQL

2022-08-03 05:05 UTC, yiwenwang-ms commented on concepts/search-concept-chat-messages.md
> +```
Done

2022-08-03 05:11 UTC, yiwenwang-ms commented on concepts/search-concept-chat-messages.md
> +
They are the scope terms that supported for Teams message search in the KQL as the queryString under the Example3.

2022-08-03 05:15 UTC, opbld32 commented
Docs Build status updates of commit _[0fbdf90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fbdf90681fb47208c48193e59f2c60a683ae8bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) | [Details](#user-content-3df07db36f540b94b746b72c8fbf80f5-fe3b07c6)
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

<a id="3df07db36f540b94b746b72c8fbf80f5-fe3b07c6"></a>
### [concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md)
 - **Line 247, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030513232093-17686/BuildReport?accessString=47f985feb00548be8ed598794f6ee18f1bda14cb260aab5818fb24011d43a582).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 05:21 UTC, opbld30 commented
Docs Build status updates of commit _[af4181f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af4181fdd0365218db2f871cc66255fa0cb269a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208080519074187-17686/BuildReport?accessString=d5b0196985258b3afc433c80279d4b7b0a18ef649b9c3648035f5d5c7061348f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 22:27 UTC, Danielabom commented
@yiwenwang-ms Hi Yiwen, I noticed you added the label "review feedback addressed" today. I checked @isvargasmsft comments and your changes, and everything seems to be in place. I'll ask Isaac to run a final review as soon as possible. Isaac was kind enough to take over this PR while I was OOF so I need his final approval.

2022-08-10 13:25 UTC, opbld33 commented
Docs Build status updates of commit _[0c8787a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c8787ac7c1e2af55d0d6feed131955e9df24aa8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101323528521-17686/BuildReport?accessString=74220841e6c3f2f6d05e26c1cf45c7f11ab889d4b9aafca220e714a9f510588c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 15:54 UTC, opbld32 commented
Docs Build status updates of commit _[5c8b8d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c8b8d271761cda40bdcdd78613a797960d69b29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101551452780-17686/BuildReport?accessString=670a93393491caf69091675d9357af79365bfa2690f2890efaf2b7aef92d1612).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 15:58 UTC, opbld30 commented
Docs Build status updates of commit _[63c8ef9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63c8ef98e88fb70a9082ac6f6c6b7ea7ca4171a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101557049862-17686/BuildReport?accessString=9a7b5dc8f096d76a213073d60885ac2e68cae82dfc25181a8e04e37fc7477b76).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 16:01 UTC, isvargasmsft approved these changes

2022-08-10 16:03 UTC, opbld34 commented
Docs Build status updates of commit _[530be79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/530be7997c338bad73b611d3d0c5545fe44723ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101601224758-17686/BuildReport?accessString=8dfcc5d8f0d432a67b2a2901de7c478d549c306e1e19424c09db10cdd27ba0c0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 01:57 UTC, opbld31 commented
Docs Build status updates of commit _[1f4cdc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f4cdc25fc05a1c2bd228533f1f57568ae66d46d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208120155046053-17686/BuildReport?accessString=d2ea9d1fe41d5d9436659b9d7643027c6bdd39e93158a2c960189648e529aa3f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 02:04 UTC, opbld30 commented
Docs Build status updates of commit _[74db96a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74db96a6b529eee96d2c3fd1e543aa89b2f9d246)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208120202175656-17686/BuildReport?accessString=0b0ac99211eb301969dbd762a925651d9d1c3719e652dd3edfca2de03b9d9ccd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 02:21 UTC, opbld33 commented
Docs Build status updates of commit _[13b10f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13b10f1f6d2bbacae8aefcc24183376d8cf5ef5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-17686) (graph-rest-beta) |
[concepts/search-concept-chat-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/search-concept-chat-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/07-14-SupportTeamsMessageSearchInGraph/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-chat-messages?branch=pr-en-us-17686) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208120219181985-17686/BuildReport?accessString=a946478e5a9b29dcff47fc645e52a5368419fa0ead73ad3965817db2b354d3a7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 04:32 UTC, merged