Update search-concept-aggregation.md
microsoftgraph/microsoft-graph-docs pull request #17702
Opened 2022-07-15 10:12 UTC by ZChristine

2022-07-15 10:14 UTC, opbld31 commented
Docs Build status updates of commit _[0d01c3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d01c3db620418a961b5e56cefd1e3dfddc95fcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-17702) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207151012193729-17702/BuildReport?accessString=67204ed5e34c4528b6462e4cf3e9aa8d220e592a0f8a0f4534e296e9136d4dcc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 21:00 UTC, opbld32 commented
Docs Build status updates of commit _[eb7efb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb7efb421a9764e7c8e5124c5267ced0f9aad3ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-17702) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207192058278154-17702/BuildReport?accessString=40b7a4f84c3054c6acb4fdd32d50a4049c70bcc61053bc16337a06959921a293).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 21:20 UTC, isvargasmsft commented on concepts/search-concept-aggregation.md
> +Aggregations are supported only for SharePoint, OneDrive or External items. They are not supported for **message** or **event**.
The API Overview topics in the beta and v1 reference docs also have sections related to limitations. Would you be so kind to update those as well, please?

Documents:
https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0#known-limitations

https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta#known-limitations

2022-07-19 21:21 UTC, isvargasmsft requested changes
Hello @ZChristine, 

Thank you very much for these updates. 

Please take a second to add the update to the API Overview topics as well. 

Kind regards, 

Isaac

2022-07-20 07:23 UTC, ZChristine commented on concepts/search-concept-aggregation.md
> +Aggregations are supported only for SharePoint, OneDrive or External items. They are not supported for **message** or **event**.
the limitations seems not in the above documents?
![image](https://user-images.githubusercontent.com/33659566/179921709-61652b89-18a2-479d-b55e-c6cd144c1667.png)

2022-07-20 07:26 UTC, ZChristine commented
> Hello @ZChristine,
> 
> Thank you very much for these updates.
> 
> Please take a second to add the update to the API Overview topics as well.
> 
> Kind regards,
> 
> Isaac

could you help evaluate about "add the update to the API Overview topics "?

2022-07-20 17:14 UTC, isvargasmsft approved these changes

2022-08-01 23:32 UTC, Lauragra approved these changes

2022-08-01 23:36 UTC, opbld34 commented
Docs Build status updates of commit _[b15f70f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b15f70f7acf7ceee11e0b91b388ef41d678ec6fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-17702) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208012332476082-17702/BuildReport?accessString=317dcb720a057af30ed47e59ab8c9f254e4d50d80a728f8a6365f620265ed17a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 04:33 UTC, merged