Add Supported Region supported solution parameter
microsoftgraph/microsoft-graph-docs pull request #17712
Opened 2022-07-18 01:43 UTC by Meadow201317

Add supported region supported solution parameter.

2022-07-18 01:47 UTC, opbld34 commented
Docs Build status updates of commit _[d0b7dda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0b7dda3c8d218ed5d86abbc82569395816f5747)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207180143297070-17712/BuildReport?accessString=7320541810ed46e30eaeea4d8e58eb1210b58c32d3ba9d97b8fac4c5b8248b90).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 02:46 UTC, AshleyYangSZ requested changes

2022-07-18 02:46 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|supportedSolution|String|The supported services or solutions for the region. Read-only.|
The type is `cloudPcManagementService`.
And add `The possible values are: `windows365`, `devBox`, `unknownFutureValue` `to the description please.

2022-07-18 06:24 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
> +|supportedSolution|String|The supported services or solutions for the region. Read-only.|
Updated, thx!

2022-07-18 06:27 UTC, opbld34 commented
Docs Build status updates of commit _[42b2e11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42b2e110242a3ed127cfed950cbff2e9f5b8124f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207180624483444-17712/BuildReport?accessString=9176a09c3424bc244baa4486b09897acc5672aadc6bdcdffd64c421c5ee81d5b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 07:04 UTC, AshleyYangSZ commented
@Meadow201317 Please add change-log for Microsoft.CloudManagedDesktop.json as well.

2022-07-19 07:46 UTC, Shaowei-Dong approved these changes

2022-08-04 08:12 UTC, Meadow201317 commented
> @Meadow201317 Please add change-log for Microsoft.CloudManagedDesktop.json as well.

Have updated, thx!

2022-08-04 08:14 UTC, opbld32 commented
Docs Build status updates of commit _[c9c5bc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9c5bc8ebb2e6d142396e1087e6447a4c468f2b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208040812186017-17712/BuildReport?accessString=5accd280cc3cd6830ad82c8710deb9634b7753b1079c47bfcd754e97befbb0ff).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 08:11 UTC, RuiHou105 requested changes
@Meadow201317  please create a roadmap woritem and attach the workitem number in comment. Thanks!

2022-08-15 08:11 UTC, RuiHou105 commented
@JarbasHorst , @Lauragra , as the graph schema already went alive,  please help review it when you got time. Thanks

2022-08-15 08:45 UTC, Meadow201317 commented
Here is the roadmap workitem: https://microsoftgraph.visualstudio.com/Roadmap/_workitems/edit/14460/?workitem=14845

2022-08-15 10:19 UTC, RuiHou105 approved these changes

2022-08-15 21:32 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpcsupportedregion.md
>  |:---|:---|:---|
Hi @Meadow201317, I think that you should change the description for the supportedSolution property. The current description implies that this property takes one or more values = "The supported services or solutions". Since this property only supports one value, either windows365 or devBox, I recommend you to rephrase this description:

- The supported service or solution for the region. The possible values...

2022-08-15 21:34 UTC, JarbasHorst commented
Hello @Meadow201317, I reviewed your PR and left one comment. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PRs [18047](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18047) and [18048](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18048) into your branch to include my fixes and before addressing my comment.

2022-08-16 03:00 UTC, opbld30 commented
Docs Build status updates of commit _[5cb1da3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cb1da3cd77431668ee99f3919fda9f0f9f65cea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160257380266-17712/BuildReport?accessString=85f6d56b24ce73c1590a6a4a64485407473485640a1da8eacafc9a174bde4b31).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 03:02 UTC, opbld31 commented
Docs Build status updates of commit _[48f4383](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48f43831d14c1e60f072d4760c18866460877c14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208160257576880-17712/BuildReport?accessString=26e720814ec114c1ef73adf254fdd02c72b8c61f9799716a2e78260f123ad835).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 07:33 UTC, AshleyYangSZ approved these changes

2022-08-29 07:44 UTC, opbld33 commented
Docs Build status updates of commit _[02950d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02950d4bc993f4d1823fbe0529369f8a74d2acc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208290741566888-17712/BuildReport?accessString=d781ef86038bc4fd9b4a297e147f1bd484b657d6d226c8afef308a97e3e5e888).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 07:58 UTC, opbld31 commented
Docs Build status updates of commit _[23e9ec9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23e9ec9e689ea667a6e0ee42bd6b256791dfe4ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208290755550554-17712/BuildReport?accessString=765d24593ee4894e027b3bd129846a79d9e5c56352731a8c02ff5297492b4b16).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 07:59 UTC, Meadow201317 commented on api-reference/beta/resources/cloudpcsupportedregion.md
>  |:---|:---|:---|
Changed, thanks!

2022-08-29 20:52 UTC, JarbasHorst commented
Hi @Meadow201317, thanks for addressing my previous comment.

@Lauragra this PR is ready for final review.

2022-08-30 01:06 UTC, Lauragra approved these changes

2022-08-30 01:08 UTC, opbld31 commented
Docs Build status updates of commit _[a78357e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a78357eeca7623764b1f4f22bd3306b4fb4fa5b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300106328263-17712/BuildReport?accessString=31cd021b136629aa41812ec129e3a1b278e286b1b83bcbc33ed9ccb4a76a7d02).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 00:55 UTC, opbld31 commented
Docs Build status updates of commit _[2c56d2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c56d2c73bdc198722aa405a4cc2b786556c09b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310053063172-17712/BuildReport?accessString=e3388914b871771433e90f92986f9a5fffd5be4e02c5e8e839aa93927bbb5ca7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 01:11 UTC, opbld34 commented
Docs Build status updates of commit _[d9df1f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9df1f4507cf3716c2539b73ebd47f603ce08b98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/virtualendpoint-list-supportedregions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/api/virtualendpoint-list-supportedregions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-supportedregions?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcsupportedregion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/api-reference/beta/resources/cloudpcsupportedregion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcsupportedregion?view=graph-rest-beta&branch=pr-en-us-17712) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bizhao/suportedRegionV2/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310109269498-17712/BuildReport?accessString=cfd92d72dcacf5445043dab2d312b23c226cef75c64f6351224aa8a6e9a0e719).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 01:16 UTC, merged