requestSignatureVerification property added to Application Page
microsoftgraph/microsoft-graph-docs pull request #17743
Opened 2022-07-19 15:38 UTC by rahul-nagraj

2022-07-19 15:40 UTC, opbld30 commented
Docs Build status updates of commit _[e3ef6e6](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/e3ef6e68a7483a7725e70585a2235329cad5970b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) | [Details](#user-content-c01a16270b2da8e012466ab966709b8b-609f41de)
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

<a id="c01a16270b2da8e012466ab966709b8b-609f41de"></a>
### [api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md)
 - **Line 23, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207191538253952-17743/BuildReport?accessString=a37cec145552deefa74deffc4515f8185d7a6a2110b654b63fabc01645ae1fe6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 19:26 UTC, opbld33 commented
Docs Build status updates of commit _[ac36b75](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/ac36b75fc4d7ee11f9ba59a440c64c24715fca7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) | [Details](#user-content-c01a16270b2da8e012466ab966709b8b-2b3af594)
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

<a id="c01a16270b2da8e012466ab966709b8b-2b3af594"></a>
### [api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md)
 - **Line 23, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207201924177405-17743/BuildReport?accessString=97f2d97d1da9ce0c600f662bab632204e374626a60c9d55d8c12cb8f4d1cf6fd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 19:40 UTC, opbld30 commented
Docs Build status updates of commit _[2188187](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/2188187a5392d183f19826ee302eeee9f625d4a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-7289e619)
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-7289e619"></a>
### [api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml)
 - **Line 882, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/requestsignatureverification.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207201938431732-17743/BuildReport?accessString=1c4410257156595a6325867023935ac23c2bd4d28fbc236263a716619f5fb911).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-20 19:50 UTC, opbld33 commented
Docs Build status updates of commit _[9df44d2](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/9df44d2e30fe62980421182f8722a9be18fdc6ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207201946014112-17743/BuildReport?accessString=21513a43123254065717743a450a98a1c3ba729a9e69d826c31102f353a0d115).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 08:29 UTC, opbld33 commented
Docs Build status updates of commit _[d1948fd](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/d1948fd67a0650dee53e78cc34674be2c32f358e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207210825415678-17743/BuildReport?accessString=653745d346b5752f35f9f2ca62786cc7a439addeef9dcf013b777e9235097950).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:16 UTC, opbld34 commented
Docs Build status updates of commit _[b4d09e7](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/b4d09e7d5651cfd0807da3ad65e6972850103b21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211203522946-17743/BuildReport?accessString=c962270f0e8b1e6838e614f90b854d8039ffb400e0553e3c04b3330d31bc8e31).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:31 UTC, opbld33 commented
Docs Build status updates of commit _[ff6c8b9](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/ff6c8b960572eb242a1125628e89ea5e719bfc93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211228030394-17743/BuildReport?accessString=c6f451f6cca55bbce181aa7493cd83419de629aa49ad5cdd41d4a18d2dabadae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:47 UTC, opbld34 commented
Docs Build status updates of commit _[92c5b8c](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/92c5b8cbd5991440dc351f354e179dfe96f9c3d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211245261314-17743/BuildReport?accessString=e4b18749ed9c2995e8f1919d0ca4ad569897805236c2ee28cb08be1a5078d633).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:59 UTC, opbld32 commented
Docs Build status updates of commit _[45ad240](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/45ad24020b2cc18bf3bbf58b792fc31e80923403)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211256206168-17743/BuildReport?accessString=fa039c74f43da80868ade33d1ecfce512c4cf9e781e3fac9b562d0e5ef0c28b3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 13:06 UTC, opbld34 commented
Docs Build status updates of commit _[1875d05](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/1875d0508a20b5f2660dd0c581c834d3c78d0276)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207211304564448-17743/BuildReport?accessString=9103cf0b68790ac3f72420a80563e675858eb66d63a79eaa09d041d5a0db6388).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 10:48 UTC, opbld34 commented
Docs Build status updates of commit _[cd664d6](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/cd664d66736f804b7236507c9e3c16478327f270)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207221045430443-17743/BuildReport?accessString=a8c879dd8264eb0fa249a6503213f9a352eb9d9fca40ce61349f09f43ffd1ea6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 10:59 UTC, opbld30 commented
Docs Build status updates of commit _[8078fcf](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/8078fcfaa287080bf8cdd7fada94a04f51785fe3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207221057269580-17743/BuildReport?accessString=a5fb690421b2dea5e440d32ab035efbc7c4ae9e41f20605187d81e1439ece149).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 11:58 UTC, opbld30 commented
Docs Build status updates of commit _[116719a](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/116719a59863c36d1d2ff5f69beb4f4e529b3b79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-17743) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207221156031377-17743/BuildReport?accessString=948dbe1c7aaaeb048b5ac5fa64b6b1e537ac9c7a6d36b2b1aa3ed00861443cb8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 16:53 UTC, opbld31 commented
Docs Build status updates of commit _[120ef58](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/120ef58612dd101f718ea30af521dd90f0541892)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-157066fe)
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-157066fe)
[api-reference/beta/resources/requestsignaturevalidation.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignaturevalidation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignaturevalidation?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-157066fe"></a>
### [api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md)
 - **Line 111, Column 34**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'requestsignatureverification.md'.`````

<a id="0817dce4456c16725d5333633847d38f-157066fe"></a>
### [api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
 - **Line 956, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/requestsignatureverification.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207221651253712-17743/BuildReport?accessString=c0d5dfa08c849729782556323bd694da69b628c0961817000e19c385553259ab).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 17:45 UTC, opbld30 commented
Docs Build status updates of commit _[ecd325e](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/ecd325ebe9d2d1dc002cc098ef72816e453f7755)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207221743237457-17743/BuildReport?accessString=7d88d38ef718a40eae56e94a36c1682c1ed5d47ddd04c25c7473cf48321f2266).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-24 17:32 UTC, opbld31 commented
Docs Build status updates of commit _[a384c6b](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/a384c6b23af859a5638c59f0925f5e2e98dfbdb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207241730353214-17743/BuildReport?accessString=a874de7d4519a45ad1204f9fdda896e9ecd13aa995cf29bebb774162e5b687c3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-24 17:48 UTC, opbld30 commented
Docs Build status updates of commit _[e9775f8](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/e9775f8df16be8405bfda7bde2af0435aadbea48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207241746104205-17743/BuildReport?accessString=624f4c8c9007ad74095f608f85383be40247ec3132a7daaf1f51b4d026a133a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 10:29 UTC, opbld33 commented
Docs Build status updates of commit _[19cd096](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/19cd096a495d0a1695c57526241bc3db5cc3f30a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207251027154265-17743/BuildReport?accessString=2fda95fd33e371d8ab68c6e471bee6a47d012fef9c7f523645192c0ab3837457).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 10:52 UTC, opbld30 commented
Docs Build status updates of commit _[24c7956](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/24c7956009a0fbc9d36f8291ad0c73e954e374eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207251048091893-17743/BuildReport?accessString=7d7bc7208e5380212ba10a20200cc1e4654eb38deb4fd9669e2670f235d697af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 11:09 UTC, opbld32 commented
Docs Build status updates of commit _[d10a4f8](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/d10a4f8f3ae9a57f9fee7b8c01b4abaef39fabc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207251106178306-17743/BuildReport?accessString=1d4b79bfa799b982f32568a43111bcfe85995df90c15d3ea2fa0a764ed0782fc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-07 12:37 UTC, opbld32 commented
Docs Build status updates of commit _[81a44c7](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/81a44c77d32bdb98fee08bd995082bd3de9647bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208071234463287-17743/BuildReport?accessString=50dbf6df6b943aae3bba7cb499f1f86fb3673c097feaff3924be4b88bcc3b35e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 11:42 UTC, opbld30 commented
Docs Build status updates of commit _[5e8ad9c](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/5e8ad9c0bebad00cbf02ab38f6a769f6f23b5380)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101141192693-17743/BuildReport?accessString=b110ccf69e7a43a901b681b386e8d7c77001d98526840d40b5cf8a94bae87617).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 18:03 UTC, FaithOmbongi requested changes
Hi @rahul-nagraj - I've left comments and suggestions for minor issues to address.

2022-08-10 18:03 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [weakAlgorithms](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
Fixing a stub generator issue
```suggestion
          "Description": "Added the [weakAlgorithms](https://docs.microsoft.com/en-us/?view=graph-rest-beta) enumeration type.",
```

2022-08-10 18:03 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [requestSignatureVerification](https://docs.microsoft.com/en-us/graph/api/resources/requestSignatureVerification?view=graph-rest-beta) resource",
```suggestion
          "Description": "Added the [requestSignatureVerification](https://docs.microsoft.com/en-us/graph/api/resources/requestSignatureVerification?view=graph-rest-beta) resource.",
```

2022-08-10 18:03 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [requestSignatureVerification](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta) resource",
Fixing a stub generator issue
```suggestion
          "Description": "Added the **requestSignatureVerification** property to the [application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta) resource.",
```

2022-08-10 18:03 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Directory management"
```suggestion
      "WorkloadArea": "Applications",
      "SubArea": ""
```

2022-08-26 09:54 UTC, opbld31 commented
Docs Build status updates of commit _[1daef6f](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/1daef6f672bf07347308dbb151d31eab25c66542)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260952221876-17743/BuildReport?accessString=44103bfdf288770f517abc319752ce6578eee046d0dcebfaa818b597d7fa88d9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 09:57 UTC, opbld33 commented
Docs Build status updates of commit _[1ffedb2](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/1ffedb242848a0cbd7d43f9a2c184a2f88c037a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260954560561-17743/BuildReport?accessString=7889d72029a7bd6ecff480d852e753067908960e44987fad262c2fedf1920413).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 10:04 UTC, opbld33 commented
Docs Build status updates of commit _[289df13](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/289df138859cabcfd4b51389d91e3d9c36b91bc2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260957143774-17743/BuildReport?accessString=282c34b4cd3d067930d41e22f76421c0870a171a9c2b8aa2096c6e12a724f8d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 10:08 UTC, opbld31 commented
Docs Build status updates of commit _[a947826](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/a947826a51c781a9c6b438f404d652a05c08965a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208261005444441-17743/BuildReport?accessString=694dcd7344632bd46f80f9b311d9999d15978bba13421fc7c22ea7797174745a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 10:13 UTC, rahul-nagraj commented
> Hi @rahul-nagraj - I've left comments and suggestions for minor issues to address.

Hi @FaithOmbongi, I have addressed all the review comments. Let me know if this looks good now

2022-08-26 10:14 UTC, rahul-nagraj commented
#sign-off

2022-08-26 13:07 UTC, FaithOmbongi approved these changes

2022-08-26 13:08 UTC, opbld31 commented
Docs Build status updates of commit _[aee0ad2](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/aee0ad29e3bcca9b5dec23b94cb21c8149866268)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208261306093873-17743/BuildReport?accessString=0dccc30252b8a9ec06592c98e2f39ecb4d471457f811a93ef34d14651e4df74f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 13:49 UTC, opbld33 commented
Docs Build status updates of commit _[76d1608](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/76d1608344a982344341047d73e440715f6abaf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208261345308914-17743/BuildReport?accessString=e20f45ec34ed77efe5372044c950708a5e01f7b365caaa05fc07db813b2f75c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-27 01:58 UTC, opbld31 commented
Docs Build status updates of commit _[91d8cc0](https://github.com/rahul-nagraj/microsoft-graph-docs/commits/91d8cc05916d8f95676a91d5dc887321b84b6c07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/application.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[api-reference/beta/resources/requestsignatureverification.md](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/api-reference/beta/resources/requestsignatureverification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/requestsignatureverification?view=graph-rest-beta&branch=pr-en-us-17743) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rahul-nagraj/microsoft-graph-docs/blob/main/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208270156388937-17743/BuildReport?accessString=4e7c0f53835eaac3a87f32fc625755efff0b9cd0b88d401e0d0919e183a8346a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-27 02:04 UTC, merged