Update learningcontent-get.md
microsoftgraph/microsoft-graph-docs pull request #17789
Opened 2022-07-21 06:23 UTC by SritejaKampara

Updating the Right URL for Learning Content GET Api

Co-Authored-By: roymalabika <108811446+roymalabika@users.noreply.github.com>
Co-Authored-By: hemashar <108335902+hemashar@users.noreply.github.com>

2022-07-21 06:25 UTC, opbld33 commented
Docs Build status updates of commit _[510907d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/510907d61f62aa08b96c92a51328c9e2c466c9c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/vivalearningdocumentationchange1/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17789) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-c8d49e3a)

<a id="918e8ad4b2b68411fec8a7195724b710-c8d49e3a"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/vivalearningdocumentationchange1/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207210623348090-17789/BuildReport?accessString=d47a5053a13201a1ae07c74b3e35ba321131ae366326d815561c6832bf19f661).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 10:23 UTC, opbld32 commented
Docs Build status updates of commit _[7ea9620](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ea96209679e5087f0137308616e52e1581b746e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/vivalearningdocumentationchange1/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17789) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-c3eedb53)
[api-reference/beta/resources/viva-learning-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/vivalearningdocumentationchange1/api-reference/beta/resources/viva-learning-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/viva-learning-api-overview?view=graph-rest-beta&branch=pr-en-us-17789) (graph-rest-beta) | [Details](#user-content-518e60108d366d627559e637ca45d33f-c3eedb53)

<a id="918e8ad4b2b68411fec8a7195724b710-c3eedb53"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/vivalearningdocumentationchange1/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="518e60108d366d627559e637ca45d33f-c3eedb53"></a>
### [api-reference/beta/resources/viva-learning-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/vivalearningdocumentationchange1/api-reference/beta/resources/viva-learning-api-overview.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101020469581-17789/BuildReport?accessString=ea18fb819e0130052384820456ed3bd6976b84faf4ab6565134cf4d9687291bd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 17:11 UTC, SteveWilkins1123 submitted a review, later dismissed

2022-08-10 17:29 UTC, SteveWilkins1123 reviewed
## Allowlisting <What is this a permission?>
As part of Registration, we are going to Allow list your AppId for the tenant. <what do you mean by we are going to allow? Not now; in the future? If so then you cannot mention anything about a feature that will be available in the future.

To enable content ingestion from Partner for the tenant. You should provide your App Id https://aka.ms/contentsync 
<What is the reference to aka.ms.contentsync.> 


Do you want to say
To enable ingestion of content by partners from a tenant, as part of Registration, listing AppId for a tenant will be enabled by default.

2022-08-10 20:11 UTC, angelgolfer-ms commented on api-reference/beta/api/learningcontent-get.md
> +GET /employeeExperience/learningProviders/{learningProviderId}/learningContents(externalId='{externalId}')
Line 33:
Can one of the authors please confirm if there was a schema change to make externalId a parameter in the query?

Or is learningContents still a nav property of learningProvider? If that's the case, can you confirm if the following should work without explicitly specifying the property name externalId, and where {externalId} is a value for the externalId property? (Like you noticed, Graph Explorer doesn’t support your API right now.)

GET /employeeExperience/learningProviders/{learningProviderId}/learningContents(‘{externalId}’)

In general, if there’s a schema change that entailed an API review, please include the internal roadmap item # at the top of the Conversation tab in GitHub for your PR. More info in step #6 in the [workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=workflow-for-internal-contributors-to-add-new-content-or-update-content) section.

2022-08-10 20:19 UTC, angelgolfer-ms commented on api-reference/beta/api/learningcontent-get.md
This comment applies to all the example queries for the learningProvider and learningContent API topics:

Unlike the "HTTP request" section, example request should always specify the fully qualified URL including the domain name. For example, the GET request for learningContent should be:

`GET https://graph.microsoft.com/beta/employeeExperience/learningProviders/13727311-e7bb-470d-8b20-6a23d9030d70`

Can you please update all the example queries in your API set?

BTW, can you confirm if Graph Studio generated these example requests without fully qualified query URLs?

2022-08-10 20:28 UTC, angelgolfer-ms requested changes
I entered a couple of comments when your request came in and one of us started responding. 

In general, it would be good if your PR can follow our [content workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=workflow-for-internal-contributors-to-add-new-content-or-update-content) so that a reviewer can dedicate their attention while reviewing your PR. Otherwise there can be oversights that affect the customer experience for your API, and general expectations that take concerted efforts across the docs to build.

I myself have a few PRs and other tasks on hand, so I'll likely let someone else follow up on this PR and complete the review as it moves up the review queue.

2022-08-10 21:03 UTC, angelgolfer-ms commented on api-reference/beta/api/learningcontent-get.md
> +GET /employeeExperience/learningProviders/{learningProviderId}/learningContents(externalId='{externalId}')
On the other hand, if learningContents is now redefined as a function, then we should document the function parameter in a different way. See more info in [Parameters](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211760/Parameters), and an example for the [reminderView](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211760/Parameters) function.

2022-08-10 22:28 UTC, SteveWilkins1123 commented on api-reference/beta/resources/viva-learning-api-overview.md
> +## Allowlisting
What is AllowListing? Is it a permission?

2022-08-10 22:31 UTC, SteveWilkins1123 commented on api-reference/beta/resources/viva-learning-api-overview.md
> +As part of Registration, we are going to Allow list your AppId for the tenant. To enable content ingestion from Partner for the tenant. You should provide your App Id https://aka.ms/contentsync
Going to allow implies that this will be done at some point in the future. We should not talk about features that are coming soon. 

I would rephrase as
To enable partners to ingest content from a tenant, as part of Registration, listing the AppId for a tenant will be enabled by default.  

I am not sure what "You should provide your App Id https://aka.ms/contentsync" this has to do with the rest of the information

2022-08-17 12:15 UTC, roymalabika commented on api-reference/beta/resources/viva-learning-api-overview.md
> +## Allowlisting
Hi Steve , We are currently allowing specific Application id to connect to our Graph API. The form is provided to enter the Application id by the Provider

2022-08-18 17:14 UTC, SteveWilkins1123 commented on api-reference/beta/resources/viva-learning-api-overview.md
> +## Allowlisting
So you may want to say something like this:
To enable the ingestion of partner content from a tenant, as part of Registration, providers can call this API to register their Application IDs with the tenant.

So if a provider registers an AppID with a tenant they are allowed to ingest content from the tenant even if it is owned by someone else? Or does the owner of a tenant call this API to register a provider APPID?

2022-08-30 20:12 UTC, isvargasmsft commented on api-reference/beta/resources/viva-learning-api-overview.md
> +As part of Registration, we are going to Allow list your AppId for the tenant. To enable content ingestion from Partner for the tenant. You should provide your App Id https://aka.ms/contentsync
Lines 44 and 45: Following Steve's comments, Could you please expand this description? We can chat on the side for efficiency, I'd like to understand better what is Allowlisting and how it works from both the developer and IT admin perspective.

2022-08-30 20:14 UTC, isvargasmsft commented on api-reference/beta/api/learningcontent-get.md
> +GET /employeeExperience/learningProviders/{learningProviderId}/learningContents(externalId='{externalId}')
Could you please clarify if this change also applies to the List operation? If not, could you please clarify the difference? If it does, please update the List topic as well.

2022-08-30 20:17 UTC, isvargasmsft requested changes
Hello @SritejaKampara, 

Thank you very much for your work in this PR. 

Please take a look at Angela and Steve's comments as well as a couple of additional comments I left. I am also reaching out to you on the side to chat a bit more about the Allowlisting feature. 

Thank you!

Isaac Vargas

2022-09-15 08:35 UTC, SritejaKampara commented
This PR is no more applicable as allowlisting is removed now, and also the change to learningcontent-get.md is included in https://github.com/microsoftgraph/microsoft-graph-docs/pull/17997/commits

2022-09-15 08:35 UTC, closed without merging