add aad and locale error type doc on on-prem entity
microsoftgraph/microsoft-graph-docs pull request #17790
Opened 2022-07-21 08:12 UTC by wcchen101

2022-07-21 08:15 UTC, opbld31 commented
Docs Build status updates of commit _[c87b522](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c87b5221974f925530769d577dc6c299d16c2a8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17790) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207210812146080-17790/BuildReport?accessString=a0e95c9e817c4113be5f92273c4d3b53694d290dc6e8f282e96e88fe07f0d2c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-21 12:15 UTC, AshleyYangSZ commented
@wcchen101 Please do remember the change-log and roadmap workitem id.

2022-07-21 12:16 UTC, AshleyYangSZ requested changes
Could you please add the change-log and the roadmap workitem id for this PR?

2022-07-26 03:04 UTC, RuiHou105 requested changes
Please add roadmap work item number and update the changelog. Thanks!

2022-07-26 03:14 UTC, wcchen101 commented
Roadmap id: 14724

2022-07-26 03:39 UTC, opbld30 commented
Docs Build status updates of commit _[daa6d9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/daa6d9f637a4b035ccb1326c3b5becce2660f7cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17790) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207260336577908-17790/BuildReport?accessString=05161dff059f96de80c13123551d23d6fb68850575854c9414d0446dd7508d21).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 02:45 UTC, AshleyYangSZ approved these changes

2022-08-04 02:47 UTC, RuiHou105 approved these changes

2022-08-15 08:34 UTC, RuiHou105 commented
@Lauragra , @JarbasHorst , could you please help review this PR? The graph schema already went alive. Thanks!

2022-08-16 22:04 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
>  |endpointConnectivityCheckIntuneUrlNotAllowListed|During provisioning, one or more required Intune URLs couldn’t be contacted. Please make sure that all of the required URLs are allowed through the f
Instead of using "visit our docs and learn more", please provide a link to a specific article. Suggested revision:

- For a list or required URLs, see [hyperlink to an article that contains the list of required URLs].

2022-08-16 22:06 UTC, JarbasHorst commented
Hello @wcchen101, I reviewed your PR and left one comment. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [18062](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18062) into your branch to include my fixes and before addressing my comment.

2022-08-17 02:11 UTC, opbld34 commented
Docs Build status updates of commit _[80d8e25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80d8e251990261e2e434679e92309526a390cc7f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0179c6de)

<a id="0179c6de"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 80d8e251990261e2e434679e92309526a390cc7f in branch weicc/update-onprem-error-aad-locale of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 0b6a47963bd38dbee12673e302acd77028f1c678). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208170211174828-17790/BuildReport?accessString=625e9b19db168e27931b51dad96a0d886c7e910c1d97077548985169e584e643).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 08:56 UTC, opbld31 commented
Docs Build status updates of commit _[e8bf9b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8bf9b7984fcc636575346f31eb05921480c5da2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e25eb053)

<a id="e25eb053"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit e8bf9b7984fcc636575346f31eb05921480c5da2 in branch weicc/update-onprem-error-aad-locale of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 0b6a47963bd38dbee12673e302acd77028f1c678). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190856072587-17790/BuildReport?accessString=a9764cebde3c86afc1729b1717d0b993e3b3a544e2a579c49eb952fecfada922).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 09:01 UTC, wcchen101 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
>  |endpointConnectivityCheckIntuneUrlNotAllowListed|During provisioning, one or more required Intune URLs couldn’t be contacted. Please make sure that all of the required URLs are allowed through the f
Thanks. I have updated the description based on your suggestion.

2022-08-19 09:16 UTC, opbld31 commented
Docs Build status updates of commit _[7f814eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f814eb500fcfc4467711ab5f44926b07f1ef412)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa5f1337)

<a id="aa5f1337"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 7f814eb500fcfc4467711ab5f44926b07f1ef412 in branch weicc/update-onprem-error-aad-locale of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 0b6a47963bd38dbee12673e302acd77028f1c678). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190914133815-17790/BuildReport?accessString=433c88e2093fb22c0270d7eaf8849c1964f6a3343f54ff2cfb66b85c4fd0b62a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 09:23 UTC, opbld33 commented
Docs Build status updates of commit _[10fb2aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10fb2aa02ef610c32ee110424568e179dd00c61e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17790) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190919560588-17790/BuildReport?accessString=f9131e39c768ef3f6eb48fd2101c5cdec37443057d9f5fc7f9058ca93a9d4d33).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 15:22 UTC, JarbasHorst commented
Hi @wcchen101, thanks for addressing my previous comment. 

@Lauragra this PR is ready for final review. Please, merge PR [18124](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18124) into this branch to include my final edits.

2022-08-22 20:18 UTC, opbld30 commented
Docs Build status updates of commit _[a455fd9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a455fd96a1fad71d594ce05aeee12b68fe445292)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17790) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208222010262789-17790/BuildReport?accessString=7c460ee97fba2bf850c84cab719d8455a5a03e5d0820828da0327913f471bd41).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 02:43 UTC, Lauragra approved these changes

2022-08-25 02:47 UTC, opbld32 commented
Docs Build status updates of commit _[6d7e950](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d7e950cac5fae51291781bc4654657592fd0214)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-17790) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/weicc/update-onprem-error-aad-locale/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250243001135-17790/BuildReport?accessString=ef7444cddb741c8fbd2d1ef2e26bbcb6ddd29b071e55b98c8b628dd978469a16).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 02:51 UTC, merged