Updating attacksimulation api's permission
microsoftgraph/microsoft-graph-docs pull request #17808
Opened 2022-07-22 05:35 UTC by yadavgaurav121

Updating permission to AttackSimulation.Read.All for all AttackSimulation api's

2022-07-22 05:37 UTC, opbld33 commented
Docs Build status updates of commit _[6738b1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6738b1d3f1c1c1a5b0f834f85c3c2c064a763690)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-a8580eed)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-a8580eed)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-a8580eed)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-a8580eed"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-a8580eed"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-a8580eed"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207220535059244-17808/BuildReport?accessString=e35994ee828b30ee2eee5111c135e508d364a476bf2c2f2111f3227186062d6a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-22 05:50 UTC, opbld34 commented
Docs Build status updates of commit _[9141657](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9141657f265ab7172ad0bb5dec9dc8b462539dc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-ad1c76c6)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-ad1c76c6)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-ad1c76c6)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |

<a id="fb24c015ea72b88830889422e69d89cf-ad1c76c6"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-ad1c76c6"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-ad1c76c6"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207220547405378-17808/BuildReport?accessString=4839857252b9a67a91b04ba80034d3eda1ece9bcbaa188ebf31494950e46eb0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 21:12 UTC, angelgolfer-ms commented on api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
>  | Permission type                        | Permissions (from least to most privileged) |
This comment is not about this file but about the following 2 files:
- simulationautomation-list-runs.md
- simulationrerportoverview-get.md

Do their permissions need to be updated from the current SecurityEvents.Read.All to AttackSimulation.Read.All as well?

2022-07-25 21:16 UTC, angelgolfer-ms commented on api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
>  |:---------------------------------------|:--------------------------------------------|
This comment is about permissions-reference.md:
Please add AttackSimulation.Read.All to that topic, under the existing [Security permissions](https://docs.microsoft.com/en-us/graph/permissions-reference?view=graph-rest-beta#security-permissions) section.
Please follow existing conventions in that topic, e.g., insert AttackSimulation.Read.All to the tables in alphabetical order and provide applicable information.

2022-07-25 21:45 UTC, angelgolfer-ms requested changes
Hi @yadavgaurav121 , I entered a few comments, please take a look.

Looks like you already have AttackSimulation.Read.All in the Azure portal with appropriate descriptions. Thanks.

FYI, in general, to request a content review initially, please use the GitHub label "Ready for content review". Otherwise your PR wouldn't get on the PR review queue. For details, please see the CDK table and workflow diagram here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=workflow-for-internal-contributors-to-add-new-content-or-update-content

2022-07-26 04:08 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
>  | Permission type                        | Permissions (from least to most privileged) |
yes its a miss, thanks. 
Updated it.

2022-07-26 04:26 UTC, yadavgaurav121 commented on api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
>  |:---------------------------------------|:--------------------------------------------|
updated

2022-07-26 04:30 UTC, opbld31 commented
Docs Build status updates of commit _[459683c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/459683c2d25dc6a1a732d170d7df76fc870ea52a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-f27b7b75)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-f27b7b75)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-f27b7b75)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationrepeatoffenders.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationsimulationusercoverage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportroot-getattacksimulationtrainingusercoverage.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/simulationautomation-list-runs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationautomation-list-runs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationautomation-list-runs?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17808) |

<a id="fb24c015ea72b88830889422e69d89cf-f27b7b75"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-f27b7b75"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-f27b7b75"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207260427299216-17808/BuildReport?accessString=edda7f72999f8fbe3dd230fec8e5879031f0ebf59837291bd9ccb6957dea44cc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 04:51 UTC, opbld32 commented
Docs Build status updates of commit _[1a75bc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a75bc15a38618452f9b2c0bac62c870ae5c43d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-e2e408f3)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-e2e408f3)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-e2e408f3)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-e2e408f3)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-e2e408f3)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-e2e408f3)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationautomation-list-runs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationautomation-list-runs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationautomation-list-runs?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17808) |

<a id="fb24c015ea72b88830889422e69d89cf-e2e408f3"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-e2e408f3"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-e2e408f3"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="595e76f17ce [...]

2022-07-28 05:58 UTC, yadavgaurav121 commented
#feedback-addressed

2022-07-28 20:06 UTC, opbld34 commented
Docs Build status updates of commit _[9bfc631](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bfc6318f283bf58432cecd0b1490f6792a9a566)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-f99b21e1)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-f99b21e1)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-f99b21e1)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-f99b21e1)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-f99b21e1)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-f99b21e1)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationautomation-list-runs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationautomation-list-runs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationautomation-list-runs?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17808) |

<a id="fb24c015ea72b88830889422e69d89cf-f99b21e1"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-f99b21e1"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-f99b21e1"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="595e76f17ce [...]

2022-07-28 20:08 UTC, angelgolfer-ms commented on api-reference/beta/api/attacksimulationroot-list-simulationautomations.md
>  |:---------------------------------------|:--------------------------------------------|
Hi @yadavgaurav121 , instead of adding a new H2 section to the permissions-reference.md file, can you please add the table rows for AttackSimulation.Read.All (delegated and application permissions table rows) under the existing H2 section, [Security permissions](https://docs.microsoft.com/en-us/graph/permissions-reference?view=graph-rest-beta#security-permissions) section?

The permissions-reference.md file is way too long and over time, partner teams have added H2 sections at too low a granularity level. Now even the right-side TOC of that file is too long to be usable.

Thanks.

2022-07-28 20:10 UTC, angelgolfer-ms requested changes
Thanks, @yadavgaurav121 , can you please combine the table rows in permissions-reference.md for AttackSimilation.Read.All to go under the existing H2 section [Security permissions](https://docs.microsoft.com/en-us/graph/permissions-reference?view=graph-rest-beta#security-permissions)? Please see my comment.
After that, we should be good to complete the content review.

2022-07-29 04:01 UTC, opbld32 commented
Docs Build status updates of commit _[02e0226](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02e0226b6ea41ed1d1262311e0e3b2832ff99ef1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-a7ce77a7)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-a7ce77a7)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-a7ce77a7)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-a7ce77a7)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-a7ce77a7)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-a7ce77a7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17808) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-a7ce77a7)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationautomation-list-runs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationautomation-list-runs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationautomation-list-runs?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |

<a id="fb24c015ea72b88830889422e69d89cf-a7ce77a7"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-a7ce77a7"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-a7ce77a7"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulation [...]

2022-07-29 04:06 UTC, yadavgaurav121 commented
#feedback-addressed

2022-07-29 19:57 UTC, opbld32 commented
Docs Build status updates of commit _[7fd358a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fd358ab778745dc2456ccbf6a8fd03b3c0c8c3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-fb24c015ea72b88830889422e69d89cf-37482ee3)
[api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-3e197371ece25b644d2591b0dc62f62c-37482ee3)
[api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-9b565730b362495b6ed9d6a0b3f6e7dd-37482ee3)
[api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationrepeatoffenders?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-595e76f17ce825cdc41a083fb6920c74-37482ee3)
[api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationsimulationusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-16e75ade0dd13df69d52323c327d0f8d-37482ee3)
[api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/securityreportsroot-getattacksimulationtrainingusercoverage?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) | [Details](#user-content-f9934af15d8bbafc3b75351f2eed8e3b-37482ee3)
[api-reference/beta/api/attacksimulationroot-list-simulationautomations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulationautomations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulationautomations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/attacksimulationroot-list-simulations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/attacksimulationroot-list-simulations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attacksimulationroot-list-simulations?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationautomation-list-runs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationautomation-list-runs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationautomation-list-runs?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/simulationreportoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/simulationreportoverview-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/simulationreportoverview-get?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[api-reference/beta/api/usersimulationdetails-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/usersimulationdetails-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersimulationdetails-list?view=graph-rest-beta&branch=pr-en-us-17808) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17808) |

<a id="fb24c015ea72b88830889422e69d89cf-37482ee3"></a>
### [api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationrepeatoffenders.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List repeat offender users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationrepeatoffenders.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationrepeatoffenders.md(3,14)'.`````

<a id="3e197371ece25b644d2591b0dc62f62c-37482ee3"></a>
### [api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationsimulationusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List simulation coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationsimulationusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationsimulationusercoverage.md(3,14)'.`````

<a id="9b565730b362495b6ed9d6a0b3f6e7dd-37482ee3"></a>
### [api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ast-permission-changes/api-reference/beta/api/reportroot-getattacksimulationtrainingusercoverage.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List training coverage for users of a tenant in attack simulation and training campaigns.' is duplicated in 'beta/api/reportroot-getattacksimulationtrainingusercoverage.md(3,14)', 'beta/api/securityreportsroot-getattacksimulationtrainingusercoverage.md(3,14)'.`````

<a id="595e76f17ce [...]

2022-07-29 20:26 UTC, angelgolfer-ms approved these changes
Thanks, @yadavgaurav121 . FYI I reorganized the two tables in permissions-reference.md to follow alphabetical order, and removed a straying column right-most column you had left behind in the applications permissions table. I think the PR can be published when you label the PR ready to merge, following step 8 of the [workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=workflow-for-internal-contributors-to-add-new-content-or-update-content).

2022-08-03 04:13 UTC, yadavgaurav121 commented
> Thanks, @yadavgaurav121 . FYI I reorganized the two tables in permissions-reference.md to follow alphabetical order, and removed a straying column right-most column you had left behind in the applications permissions table. I think the PR can be published when you label the PR ready to merge, following step 8 of the [workflow](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow?anchor=workflow-for-internal-contributors-to-add-new-content-or-update-content).

Updated ready to merge label

2022-08-04 03:46 UTC, merged