Supporting Application Context for List Chats API in v1.0
microsoftgraph/microsoft-graph-docs pull request #17837
Opened 2022-07-25 20:48 UTC by evanypark

Application Context has been enabled for v1.0 List Chats API.

2022-07-25 20:52 UTC, opbld32 commented
Docs Build status updates of commit _[2d95d5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d95d5b418c8c567307bea4ed79819ee68ffdde8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207252048594864-17837/BuildReport?accessString=9ea5032265dc58bd9335ec91e1777844f9c78c83161dc209abfecfdb094ed4df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 21:04 UTC, opbld32 commented
Docs Build status updates of commit _[3e18496](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e18496048948705587158b877c462d280014572)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207252101282901-17837/BuildReport?accessString=1dcea29a1882b40268cc048832df8bd1ba3e4fedd750b46d9eeca0847d1d704f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-25 21:38 UTC, RamjotSingh approved these changes

2022-07-27 07:01 UTC, angelgolfer-ms commented on api-reference/v1.0/api/chat-list.md
I have a compound comment that applies to lines 14, 24, and 30-32:
(a) For line 14, the description says "... that the user is part of". That implies somewhere the REST query specifies a user. However, line 32 doesn't specify a user.
Please confirm if line 14 is accurate with respect to line 32. If line 14 is accurate, I think it's still worthwhile to call out that line 32 returns all the chats that (which?) user is part of - signed in user, specified user?

Can you apply any clarification to both the beta topic and v1 topic?

(b) Line 24:
What is that asterisk for? In the beta topic, topic, there's a line that follows the permissions table that says:
>>
* This scenario is only supported for the following call: GET /users/{user-id | user-principal-name}/chats

2022-07-27 07:02 UTC, angelgolfer-ms requested changes
@evanypark , please see my comment/questions.

2022-07-27 21:22 UTC, evanypark commented on api-reference/v1.0/api/chat-list.md
(a) When accessing this API using application context, it will return all chats in tenant that the AAD application can access. With Application context being enabled, I think it should be like "retrieve the list of chats that the user is part of or application has access to"

(b) For asterisk, we should add below, similar to what we are showing for /beta API, where application context has been enabled earlier.
* This scenario is only supported for the following call: GET /users/{user-id | user-principal-name}/chats

2022-07-27 21:31 UTC, opbld30 commented
Docs Build status updates of commit _[83ae5e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83ae5e48f6698bd081819b1d56ec70f16c80a9e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-17837) (graph-rest-beta) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207272124070099-17837/BuildReport?accessString=0c7e39eca96b0c7ad0d116f85b3b85afa97918e17709e838b93f96324c64a36a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-28 19:27 UTC, angelgolfer-ms commented on api-reference/v1.0/api/chat-list.md
@evanypark , sorry, I still don't get it. If the note for application permissions is accurate and says:
>>
* This scenario is only supported for the following call: GET /users/{user-id | user-principal-name}/chats

Then that means application permissions _don't_ apply to this syntax line (line 32):
GET /chats

So that means only delegated permissions are supported for GET /chats.
But there's no user indicated there.
So what would GET /chats return?

2022-07-29 20:11 UTC, evanypark commented on api-reference/v1.0/api/chat-list.md
@angelgolfer-ms Sorry about the confusion. you're correct.
Application context is only supported when user id is specified.
I think it should have description like, "List chat operation in application-only context is only allowed when listing chats for a specific user.", which is the error message we throw when user id is not specified with application context

2022-07-29 20:14 UTC, evanypark commented on api-reference/v1.0/api/chat-list.md
I think with the added notes under asterisk, it should make sense to the users?

2022-07-29 20:17 UTC, opbld32 commented
Docs Build status updates of commit _[42e8913](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42e8913db7a870c7b76c27398aab5099a2fc083e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207292015163176-17837/BuildReport?accessString=24388524d8a3a8aef97be74700bcbdcf9b5dc14514a87ade9f96b16f792e5ff0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 08:49 UTC, angelgolfer-ms commented on api-reference/v1.0/api/chat-list.md
@evanypark , let's try again. My question is what does GET /chats do.

There are 3 syntax lines for the list chats operation:
(1) GET /me/chats
Get the chats for the signed-in user in a tenant. Supports delegated or application permissions.

(2) GET /users/{user-id | user-principal-name}/chats
Get the chats for the specified user in a tenant. Supports delegated or application permissions.

(3) GET /chats
What does this query do?
Does this query support only delegated permissions (because there's this note:
This scenario is only supported for the following call: GET /users/{user-id | user-principal-name}/chats)?
But which would be the user for delegated permissions in this case? There's no user specified in the query URL.

2022-08-02 23:50 UTC, opbld34 commented
Docs Build status updates of commit _[c8cdcc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8cdcc95bc9495b8ca7f4fdcbc80637df95797e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208022347527102-17837/BuildReport?accessString=746aee31bebd557165295a573b16e717a36c99bd220864539f2c516dd9fb591a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 23:54 UTC, angelgolfer-ms commented on api-reference/v1.0/api/chat-list.md
Per Teams chat with @evanypark , GET /chats returns the signed-in user's chats in the organization. It supports only delegated permissions.

2022-08-03 01:34 UTC, opbld33 commented
Docs Build status updates of commit _[4ba226b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ba226b2a6cf776b867d861114ec37138843f621)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-17837) (graph-rest-beta) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030133009254-17837/BuildReport?accessString=57aadbea9fa565a2e1c03e5b374717c120bede8e416a4f415f3a5bf856a068d5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 01:40 UTC, evanypark commented
> @evanypark , please see my comment/questions.

2022-08-03 01:42 UTC, opbld33 commented
Docs Build status updates of commit _[b2ad2ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2ad2ad633c91b587a392447a7e05204f1f8ecfa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-17837) (graph-rest-beta) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030140343429-17837/BuildReport?accessString=501a07df3f557b370ef99287be03a913a904aa74edef9af2485cc218be4ea94d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 01:44 UTC, opbld30 commented
Docs Build status updates of commit _[7df645c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7df645c4bb2c4646598bfaeff727251c808b2b86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-17837) (graph-rest-beta) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030143002948-17837/BuildReport?accessString=99fd306db922ac1f7b4af876e859bc20374e3da6a938584eaa3204a21a7aec3f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 01:47 UTC, angelgolfer-ms approved these changes
Updates are good for publishing, thanks.

2022-08-03 19:08 UTC, opbld31 commented
Docs Build status updates of commit _[4e9849e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e9849e20a5dc058fd29111a3ef9b8c5448da86a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-17837) (graph-rest-beta) |
[api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/api-reference/v1.0/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&branch=pr-en-us-17837) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/yopa/2022-07-25-list-chats-v1.0-appContext/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208031906447204-17837/BuildReport?accessString=c89cb9192f6857cd3a0fbbeeb512da4837d9ab478e8ae74671d5d1d5ecaa2fa1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 03:47 UTC, merged