Tutorial - Build One Productivity Hub app by using Microsoft Graph Toolkit
microsoftgraph/microsoft-graph-docs pull request #17843
Opened 2022-07-26 07:35 UTC by aycabas

Added the following files to create the new tutorial:
  yml file:
  - concepts/graph-toolkit-building-one-productivity-hub.yml
  markdown files:
  - concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
  - concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
  - concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
  - concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
  - concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
  - concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
  images folder:
  - concepts/images/mgt-one-productivity-hub

2022-07-26 07:37 UTC, opbld32 commented
Docs Build status updates of commit _[67d00ad](https://github.com/aycabas/microsoft-graph-docs/commits/67d00add38ee2428ef4e431a7b9ce750d1799cdd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-sign-in.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-sign-in.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207260735331102-17843/BuildReport?accessString=159f42e69454d7d6315938b164b801e6b598ab393a2a3bf32949e9f6a44f95a8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 15:24 UTC, sebastienlevert requested changes

2022-07-26 15:24 UTC, sebastienlevert commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +<script src="https://unpkg.com/@microsoft/mgt@2.5.1/dist/bundle/mgt-loader.js"></script>
Please the latest 2.6.0 version!

2022-07-26 15:24 UTC, sebastienlevert commented on concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
> +## Next steps
Should we invite them to integrate more components that weren't included in the tutorial?

2022-07-26 15:24 UTC, sebastienlevert commented on concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
> +To find out more about Microsoft Graph Toolkit, visit [Microsoft Graph Toolkit overview](https://docs.microsoft.com/en-us/graph/toolkit/overview).
Maybe a link to the MS Learn module?

2022-07-26 15:24 UTC, sebastienlevert commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +Microsoft Graph Toolkit is a collection of web components and authentication providers for connecting apps to Microsoft 365 data and intelligence.
Should we add a link to the "finished" tutorial repo?

2022-07-27 10:37 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +<script src="https://unpkg.com/@microsoft/mgt@2.5.1/dist/bundle/mgt-loader.js"></script>
@sebastienlevert Login component doesn't initiate the authentication in version 2.6.0 and 2.5.2, tested in Chrome & Edge. UI is there but it's not clickable. 2.5.1 works stable with Login component and MSAL2 Provider. Should we proceed with this one right now, and update it after fixing the issue? Shall I report this bug for MGT?

2022-07-27 10:40 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
> +To find out more about Microsoft Graph Toolkit, visit [Microsoft Graph Toolkit overview](https://docs.microsoft.com/en-us/graph/toolkit/overview).
Great idea, done!

2022-07-27 10:44 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +Microsoft Graph Toolkit is a collection of web components and authentication providers for connecting apps to Microsoft 365 data and intelligence.
This tutorial contains everthing available in the official OfficeDev repo right now except the project itself. Maybe I can remove the readme files from the repo and only share the solution files to avoid confusion?

2022-07-27 10:47 UTC, opbld30 commented
Docs Build status updates of commit _[88a3372](https://github.com/aycabas/microsoft-graph-docs/commits/88a3372272a9f789220e9c2f3659fa40e3b3518b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-sign-in.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-sign-in.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207271045428440-17843/BuildReport?accessString=a56e8f88a39322add4421e354fc61352072a82c3c7d8e70ac98f9630dc13309e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 11:07 UTC, opbld34 commented
Docs Build status updates of commit _[956f9fd](https://github.com/aycabas/microsoft-graph-docs/commits/956f9fd5c566bfb4402fbb73045fc05a28fb427f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-sign-in.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-sign-in.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207271105047538-17843/BuildReport?accessString=f739ddb7110ddcd9b65bbab5b9b14872a2bb7e2267a33ec38a4a69900230bf5c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-28 14:21 UTC, opbld34 commented
Docs Build status updates of commit _[b6929fe](https://github.com/aycabas/microsoft-graph-docs/commits/b6929fe04146dfacdf55c21766246b61308f48ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-sign-in.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-sign-in.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207281419316858-17843/BuildReport?accessString=885cfa7c82c11bbd9433caafc2a4bf90be5552c06a3674342ffe0849269dd9eb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-28 14:23 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +<script src="https://unpkg.com/@microsoft/mgt@2.5.1/dist/bundle/mgt-loader.js"></script>
updated the code as suggested and changed the version to 2.6.0.

2022-08-02 07:44 UTC, opbld34 commented
Docs Build status updates of commit _[5b2544e](https://github.com/aycabas/microsoft-graph-docs/commits/5b2544e5fed067e10973e5f25f516856c19c9c77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-sign-in.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-sign-in.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020742336860-17843/BuildReport?accessString=dd5205b6e32a01716ada8d787fe899cb1ecfdd0c5c3dedf7917538751c736528).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 08:09 UTC, opbld30 commented
Docs Build status updates of commit _[2e994e9](https://github.com/aycabas/microsoft-graph-docs/commits/2e994e98c7d8c51847d696475aab64ae96df6759)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-consent-permissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/run-app-sign-in.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/run-app-sign-in.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208020807088737-17843/BuildReport?accessString=f60ec1dc230dfbe41306f1113296c61a78d7995e0b5f7eb2dacf353c814dde1e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 17:32 UTC, jasonjoh requested changes

2022-08-02 17:32 UTC, jasonjoh commented on concepts/graph-toolkit-building-one-productivity-hub.yml
> +title: Build One Productivity Hub app by using Microsoft Graph Toolkit
"One Productivity Hub" is the name of the sample app you created, is that right? I'm wondering if we should change the title to something more universal, like "Build productivity apps by using...". I'm just concerned that "Build One Productivity Hub" at a glance just raises the question "What is One Productivity Hub?" :D

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +
Combine these two sentences into one paragraph.

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +This sample creates a web app that consumes Microsoft Graph Toolkit MSAL2 provider to enable authentication through Azure Active Directory and uses UI components to demonstrate calendar events, to-do
"out of the box" may not translate well. I'd rephrase this to "...look and feel like a native Microsoft experience."

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
> +After all the prerequisites are in place, you will be able to register an application in the Azure Active Directory. The registration is necessary in order to authenticate the application through Mic
I'd rephrase this a bit with a more active voice. You don't need all the pre-reqs to register an app :D.

"Register an application in the Azure Active Directory to enable user authentication for your application."

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
> +    ![Screenshot showing the new app registration form](../images/mgt-one-productivity-hub/aad-new-app-registration-form.png)
The Docs guidelines recommend when doing multiple screenshots from a website, you have the first one show a full browser window, but subsequent ones can be smaller snips. Not a crucial thing, but you may want to trim this second screenshot down a bit.

I'd also recommend removing the redlines on this screenshot - it's a pretty linear page flow so I don't think user needs that visual guidance.

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +To use the Microsoft Graph Toolkit via mgt-loader, add the following reference in **index.html** under the `<body></body>` section:
I would suggest removing the H3 below and adding this into the numbered list.

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +    <mgt-msal2-provider
Some of these scopes are redundant, though I don't know if maybe there's some MGT requirement of doing it this way. 

- Files.Read should be included in Files.Read.All (I believe)
- Tasks.Read should be included in Tasks.ReadWrite
- User.ReadBasic.All is listed twice

2022-08-02 17:32 UTC, jasonjoh commented on concepts/graph-toolkit-building-one-productivity-hub.yml
> +  - title: Build the application
I'd change this to "Create the application"

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +In **index.html** inside the `<body></body>`, create `<div></div>` right under the provider and add the Login component inside the div:
I'd add the <div> into your code block below.

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +  <mgt-login></mgt-login>
Can this be simplified as `<mgt-login/>`?

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +In this step, you will build and run the sample. This code sample be initialized by Live Server and One Productivity Hub page will pop up in your browser.
I think there's a typo or missing word in the second sentence.

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +1. Consent the required permissions to use the application features such as viewing calendar events,to-do tasks and file folders.
Three things on this one:

- "Consent to the required..."
- missing space after comma
- Missing that Oxford comma (per MS style guide)

2022-08-02 17:32 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +    ![Screenshot showing the One Productivity Hub initial page](../images/mgt-one-productivity-hub/run-app-sign-in.png)
Overall this page is very screenshot heavy with single sentences between. I would recommend cutting all but the last one.

2022-08-02 17:33 UTC, jasonjoh commented
Thanks for doing this Ayca!

2022-08-03 06:11 UTC, aycabas commented on concepts/graph-toolkit-building-one-productivity-hub.yml
> +title: Build One Productivity Hub app by using Microsoft Graph Toolkit
Makes more sense. Updated the title as "Build productivity apps by using Microsoft Graph Toolkit".

2022-08-03 06:11 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +
Done.

2022-08-03 06:12 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +This sample creates a web app that consumes Microsoft Graph Toolkit MSAL2 provider to enable authentication through Azure Active Directory and uses UI components to demonstrate calendar events, to-do
Done.

2022-08-03 06:13 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
> +After all the prerequisites are in place, you will be able to register an application in the Azure Active Directory. The registration is necessary in order to authenticate the application through Mic
Done :)

2022-08-03 06:17 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
> +    ![Screenshot showing the new app registration form](../images/mgt-one-productivity-hub/aad-new-app-registration-form.png)
Updated the screenshot.

2022-08-03 06:19 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +To use the Microsoft Graph Toolkit via mgt-loader, add the following reference in **index.html** under the `<body></body>` section:
Done.

2022-08-03 06:22 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +    <mgt-msal2-provider
Updated.

2022-08-03 06:23 UTC, aycabas commented on concepts/graph-toolkit-building-one-productivity-hub.yml
> +  - title: Build the application
Done

2022-08-03 06:24 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +In **index.html** inside the `<body></body>`, create `<div></div>` right under the provider and add the Login component inside the div:
done

2022-08-03 06:27 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +  <mgt-login></mgt-login>
Unfortunately, we need to use the component as `<mgt-login></mgt-login>`. Tested the suggested way, UI doesn't appear.

2022-08-03 06:30 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +In this step, you will build and run the sample. This code sample be initialized by Live Server and One Productivity Hub page will pop up in your browser.
Updated the sentences.

2022-08-03 06:32 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +1. Consent the required permissions to use the application features such as viewing calendar events,to-do tasks and file folders.
Updated.

2022-08-03 06:34 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +    ![Screenshot showing the One Productivity Hub initial page](../images/mgt-one-productivity-hub/run-app-sign-in.png)
Removed images for *Sign in* and *Permissions* processes.

2022-08-03 06:43 UTC, opbld30 commented
Docs Build status updates of commit _[6ef0c50](https://github.com/aycabas/microsoft-graph-docs/commits/6ef0c505b8c4622e37946bf5a8ef47d923700fab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030641222083-17843/BuildReport?accessString=db11446f2b0e8ce8daab993061e5bcfd92d90237ec80a780fa1af3e1428cd58f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 06:59 UTC, aycabas commented
Thanks for all the comments @jasonjoh, updated the tutorial accordingly. Please review the final version and let me know if you recommend any other changes. Thank you!

2022-08-04 13:52 UTC, jasonjoh requested changes
Some fit-and-finish stuff but I also found a pretty major issue with Live Server and the auth. I added a few suggestions on how to handle it.

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +```HTML
indent this block so it lines up with the last step

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +    > The following scopes defined in the provider will be shown as a list of required permissions to request user's consent during the authentication process: `User.Read, User.ReadBasic.All, Calenda
Update the list of permissions here to match the code above.

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +1. Enable authentication with the Microsoft Graph Toolkit via mgt-loader, add the following reference in **index.html** under the `<body></body>` section:
I would change to "inside the `<body></body>`"

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +     <mgt-msal2-provider
can you fix the alignment? the `mgt-msal2-provider` element is off

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +In **index.html** inside the `<body></body>`, create `<div></div>` right under the provider and add the Login component inside the div:
Doh, just realized what I typed there didn't render :D. I meant to add the `<div>` bit into the code block.

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +In **index.html** inside the `<body></body>`, create `<div></div>` right under the provider and add the Login component inside the div into your code block below:
My previous comment didn't render properly, so recommenting here. I was sugesting moving the `<div>` bit into the code block.

```suggestion
In **index.html** inside the `<body></body>`, add the following code under the provider.

````html
<div>
  <mgt-login></mgt-login>
</div>
````
```

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +1. Create **index.css** file under your project and add below CCS code:
"add the following CSS code" (typo in CCS)

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +1. In **index.html** under `<head></head>`, define the stylesheet link `href` as **index.css**:
"inside `<head></head>`"

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +  <mgt-login></mgt-login>
I was able to get it to work for this and all of the MGT components. The key is there should be a space before the `/`, so `<mgt-login />`

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
> +   * **Redirect URI**: Select **Single-page application (SPA)** as a type of redirect URI and place `http://localhost:3000/index.html` as a redirect URI to test locally.
I got an authentication error based on wrong redirect URI. It seems that my Live Server install (which I just installed, so no changing of defaults) opens on port 5500, and it uses `127.0.0.1` instead of `localhost`. AAD requires it to match exactly (so it doesn't consider `127.0.0.1` and `localhost` to be the same).

This could get very complicated if we try to account for everyone's custom settings, but if we just assume the default, it won't work for some people. I suggest two options:

One way to do it would be to use the default value for the registration instructions (`http://127.0.0.1:5500/index.html`) and add a NOTE telling the dev if they've configured a different host and port they need to update the value accordingly.

Another way to do it would be to leave the redirect as it is and add an instruction in "creating the app" to add local settings, like this:

1. CTRL+SHIFT+P, select **Preferences: Open Workspace Settings (JSON)**.
2. In the **settings.json** file that opens, add the following code:

    ```json
    {
        "liveServer.settings.host": "localhost",
        "liveServer.settings.port": 3000
    }
    ```

Error message:

```
AADSTS50011: The redirect URI 'http://127.0.0.1:5500/index.html' specified in the request does not match the redirect URIs configured for the application '617f5aea-c443-4510-ae31-085242c3d568'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
```

2022-08-04 13:52 UTC, jasonjoh commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +    > The following scopes defined in the provider will be shown as a list of required permissions to request user's consent during the authentication process: `User.Read, User.ReadBasic.All, Calenda
Hmm maybe we were too hasty here. I just ran it this way and I ended up getting three consent prompts. It seems the task list explicitly wants `Tasks.Read` and the file list explicitly wants `Files.Read`.

2022-08-04 16:35 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +```HTML
done

2022-08-04 16:35 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +    > The following scopes defined in the provider will be shown as a list of required permissions to request user's consent during the authentication process: `User.Read, User.ReadBasic.All, Calenda
I am adding `Tasks.Read` and `Files.Read` back in the list.

2022-08-04 16:37 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +    > The following scopes defined in the provider will be shown as a list of required permissions to request user's consent during the authentication process: `User.Read, User.ReadBasic.All, Calenda
Also updated the **Important** part: removed duplicate `User.ReadBasic.All`.

2022-08-04 16:38 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +1. Enable authentication with the Microsoft Graph Toolkit via mgt-loader, add the following reference in **index.html** under the `<body></body>` section:
done

2022-08-04 16:39 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md
> +     <mgt-msal2-provider
done

2022-08-04 16:42 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +In **index.html** inside the `<body></body>`, create `<div></div>` right under the provider and add the Login component inside the div:
commited your suggestion there. Apologies I didn't understand in the first place :)

2022-08-04 16:43 UTC, opbld32 commented
Docs Build status updates of commit _[a787995](https://github.com/aycabas/microsoft-graph-docs/commits/a787995dcb4de4ee75661c2774b6126e78bf6771)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208041641328566-17843/BuildReport?accessString=c27eacdd2f8aedf8a573b8ea93c3ed161ba214079930f2e52bc2fb1796f894ee).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 16:44 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +1. Create **index.css** file under your project and add below CCS code:
Done

2022-08-04 16:44 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md
> +1. In **index.html** under `<head></head>`, define the stylesheet link `href` as **index.css**:
done

2022-08-04 16:59 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md
> +   * **Redirect URI**: Select **Single-page application (SPA)** as a type of redirect URI and place `http://localhost:3000/index.html` as a redirect URI to test locally.
Great point, I added the second suggestion inside the run-app.md, so devs can setup settings.json before they run the app.

2022-08-04 17:20 UTC, opbld31 commented
Docs Build status updates of commit _[cb0b10d](https://github.com/aycabas/microsoft-graph-docs/commits/cb0b10d8046a14148f638048484e9dbb493d77ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208041718204620-17843/BuildReport?accessString=dd8b5cf0024c7859b640ba18c972fb55b62c0c35af7e9126121fc33e27cc8790).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 19:25 UTC, opbld32 commented
Docs Build status updates of commit _[9342f54](https://github.com/aycabas/microsoft-graph-docs/commits/9342f54f8bd01ef50fb2b7531e133b74e24b1349)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101923299080-17843/BuildReport?accessString=5f8bebb2cac64bc51c88dfc30da1db8860559dc25ffb68621547f5d3abc59809).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 19:42 UTC, opbld31 commented
Docs Build status updates of commit _[9fcd0c6](https://github.com/aycabas/microsoft-graph-docs/commits/9fcd0c6af7e3ddc4fb535df8980499d302fd6b6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208101939542748-17843/BuildReport?accessString=02f8f00e19fee29804f88737014e2d82a46184918144f074b31b7c30c4b602fd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 19:46 UTC, jasonjoh approved these changes

2022-08-22 14:07 UTC, opbld30 commented
Docs Build status updates of commit _[a7ba744](https://github.com/aycabas/microsoft-graph-docs/commits/a7ba744590707c0cde82351e4f4d972ba2e54f88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208221405088062-17843/BuildReport?accessString=6b0eef76e82dde4b9b101344f1a2017f01ee87c1b232ad8f0aa5c47a03904438).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 19:48 UTC, Lauragra commented
> @Lauragra We completed Jason's review for this tutorial. Is there anything else needed for publishing?

@aycabas , @jasonjoh , this PR is still set to content review. If we're ready to publish, please se the ready to merge label. Or do we need an editorial review of the content? I can take a look. Thanks.

2022-08-23 12:58 UTC, aycabas commented
> > @Lauragra We completed Jason's review for this tutorial. Is there anything else needed for publishing?
> 
> @aycabas , @jasonjoh , this PR is still set to content review. If we're ready to publish, please se the ready to merge label. Or do we need an editorial review of the content? I can take a look. Thanks.

That would be great to get your review @Lauragra, let me know if there are any more changes needed and I can update the tutorial.

2022-08-24 16:57 UTC, isvargasmsft approved these changes

2022-08-25 03:00 UTC, Lauragra commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +This sample creates a web app that consumes Microsoft Graph Toolkit MSAL2 provider to enable authentication through Azure Active Directory and uses UI components to demonstrate calendar events, to-do
What do we mean by "demonstrate" calendar events and so on? Does the web app "render" those items? Is it the sample or the web app that is the subject of the verb "demonstrate"? Please help to clarify this sentence.

2022-08-25 03:03 UTC, opbld31 commented
Docs Build status updates of commit _[6e4995f](https://github.com/aycabas/microsoft-graph-docs/commits/6e4995fdc26bf1480c3a6d5fd675d0777b77bb49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250257559945-17843/BuildReport?accessString=6b09db5a0db90b511a0153e2f6adb0e8b1bea1cd89b04880c41e40a6bb021573).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:07 UTC, opbld32 commented
Docs Build status updates of commit _[68cd00e](https://github.com/aycabas/microsoft-graph-docs/commits/68cd00eb01c7ae772ef865f8a2aeed75f9bf09d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250305144732-17843/BuildReport?accessString=fbc5612c9f1c58fce3813716a93053ca1211d89cf25c9a974fd95da7a8d762c8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:11 UTC, opbld30 commented
Docs Build status updates of commit _[0bc8d68](https://github.com/aycabas/microsoft-graph-docs/commits/0bc8d682e09e3052fbbac51c2e11764428975a1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250308021857-17843/BuildReport?accessString=7eea1acaeb189be363ac9ab7e94be329b8e92f4793a2025dec2ca88b8449383f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:14 UTC, opbld30 commented
Docs Build status updates of commit _[7be2a35](https://github.com/aycabas/microsoft-graph-docs/commits/7be2a357956b62d655ba97a9cb86bc42c605444a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250312486139-17843/BuildReport?accessString=7ce004b6aa7b72c2322e4ea373bc2dffe7546c5ad3b334ec2940c9cc4aac435d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:17 UTC, Lauragra commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +1. `CTRL + SHIFT + P`, type and select `Preferences: Open Workspace Settings (JSON)`.
Are we missing something that they need to type, or do they just select something? The phrase "type and select" is a little unclear.

2022-08-25 03:18 UTC, opbld33 commented
Docs Build status updates of commit _[fd3d66e](https://github.com/aycabas/microsoft-graph-docs/commits/fd3d66eaeb778f3e78d0f07a145f55cb50d1764f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250316490253-17843/BuildReport?accessString=c091928d215ffb2dfe4ec0595498e8eca75301cbe27dce27e1035985df5e6fe5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:24 UTC, Lauragra reviewed
Thanks for creating this tutorial; looks good! Please see my review comments and clarify as appropriate. Thanks!

2022-08-25 03:24 UTC, Lauragra commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +1. Select `CTRL + SHIFT + P` to open the panel in Visual Studio Code, type and choose `Live Server: Open with Live Server`. Live Server will run the app in your browser.
Here we say "type and choose", it's not clear if they type something or just choose something.

2022-08-25 03:24 UTC, Lauragra commented on concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
> +You have successfully completed the Build One Productivity Hub app by using Microsoft Graph Toolkit tutorial: you created a web app and consumed Microsoft Graph Toolkit MSAL2 provider and UI componen
Let's revise this sentence to be more clear. Suggested revision:

You have successfully built your One Productivity Hub sample app using Microsoft Graph Toolkit. In this tutorial, you created a web app and consumed the Microsoft Graph Toolkit MSAL2 provider and UI components.

2022-08-25 03:26 UTC, opbld34 commented
Docs Build status updates of commit _[1717140](https://github.com/aycabas/microsoft-graph-docs/commits/1717140544c072a35d5db60d4d477f699e48520c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250324017751-17843/BuildReport?accessString=e8a09fce2eee38b8c596467b21d2b8c0bf4770b1e5d7d17fa9f2b93766860795).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 09:11 UTC, opbld32 commented
Docs Build status updates of commit _[0b6475e](https://github.com/aycabas/microsoft-graph-docs/commits/0b6475ebb1e8809f4712219f90db917863b3f568)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250909340319-17843/BuildReport?accessString=8a683a467813537bae7f14e3cfe0c61fcda1a80cbce84aecaadb847602a96d94).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 09:17 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md
> +This sample creates a web app that consumes Microsoft Graph Toolkit MSAL2 provider to enable authentication through Azure Active Directory and uses UI components to demonstrate calendar events, to-do
I updated the word "demonstrate" with "render". The sample renders calendar events, todo tasks and files.

2022-08-25 09:20 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +1. `CTRL + SHIFT + P`, type and select `Preferences: Open Workspace Settings (JSON)`.
updated the sentences as "Select `CTRL + SHIFT + P` to open the panel in Visual Studio Code, type and select `Preferences: Open Workspace Settings (JSON)`.
".  

We need to type on the panel to find the preferences and then select.

2022-08-25 09:36 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md
> +1. Select `CTRL + SHIFT + P` to open the panel in Visual Studio Code, type and choose `Live Server: Open with Live Server`. Live Server will run the app in your browser.
Updated this part as >> Select `CTRL + SHIFT + P` to open the panel in Visual Studio Code, type `Live Server` on the panel and select `Live Server: Open with Live Server`.

2022-08-25 09:37 UTC, aycabas commented on concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md
> +You have successfully completed the Build One Productivity Hub app by using Microsoft Graph Toolkit tutorial: you created a web app and consumed Microsoft Graph Toolkit MSAL2 provider and UI componen
Updated as per your suggestion :)

2022-08-25 09:44 UTC, aycabas commented
#feedback-addressed

2022-08-25 10:03 UTC, opbld32 commented
Docs Build status updates of commit _[c4e1b9c](https://github.com/aycabas/microsoft-graph-docs/commits/c4e1b9c3c18e61a537176b518d41221955c184a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-toolkit-building-one-productivity-hub.yml](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/graph-toolkit-building-one-productivity-hub.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-app-registration.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-app-registration.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/aad-new-app-registration-form.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/images/mgt-one-productivity-hub/one-productivity-hub-overview.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-01-intro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-02-register-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-03-build-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-04-design-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-05-run-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |
[concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md](https://github.com/aycabas/microsoft-graph-docs/blob/2022-07-25-aycabas-mgt-tutorial/concepts/includes/graph-toolkit-building-one-productivity-hub-06-summary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-toolkit-building-one-productivity-hub?branch=pr-en-us-17843) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250959257812-17843/BuildReport?accessString=af527ed626bcf4f67c4948afee454fdc8c980b3c5780a8b165f7d74a72020597).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 17:08 UTC, Lauragra approved these changes

2022-08-26 03:02 UTC, merged