adding list app-role assigned resources
microsoftgraph/microsoft-graph-docs pull request #17847
Opened 2022-07-26 14:28 UTC by eringreenlee

2022-07-26 14:31 UTC, opbld33 commented
Docs Build status updates of commit _[f0b1893](https://github.com/eringreenlee/microsoft-graph-docs/commits/f0b1893c148eb5f33f2061a6401ae7fbc30718c4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-fa1908a44488127d37866d1470ac5487-f2a0c9de)

<a id="fa1908a44488127d37866d1470ac5487-f2a0c9de"></a>
### [api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md)
 - **Line 1, Column 1**: **[Warning: title-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 14, Column 1**: **[Warning: h1-not-first - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'List service principals that a user has an appRoleAssignment for'.`````
 - **Line 1, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207261428362667-17847/BuildReport?accessString=91f78c6474d22d3dc0232b307bf1d217fbc6eb5cd587b0786d5ba1645a5edd70).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 15:08 UTC, opbld30 commented
Docs Build status updates of commit _[24fd56e](https://github.com/eringreenlee/microsoft-graph-docs/commits/24fd56e209e7794e89046b70f542805b0d622b95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207261505489431-17847/BuildReport?accessString=2d7f9dc3fc407a00692d1c4af0adbe1689b623eb4159faf1f3884a0e54ef1c5f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 09:53 UTC, FaithOmbongi commented
Trigger re-build

2022-08-22 09:54 UTC, opbld31 commented
Docs Build status updates of commit _[24fd56e](https://github.com/eringreenlee/microsoft-graph-docs/commits/24fd56e209e7794e89046b70f542805b0d622b95)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-50428ceb)

<a id="50428ceb"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 24fd56e209e7794e89046b70f542805b0d622b95 in branch approleassignedresources of repository https://github.com/eringreenlee/microsoft-graph-docs into branch main (commit 76f51a44c7771f1526dc412c1c79a51a59070726). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208220953405124-17847/BuildReport?accessString=d845930328756b6d2536fbcb69918dcc996228187ea9173bfcc86f4d289eede3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 10:38 UTC, FaithOmbongi requested changes
Hi @eringreenlee - Thank you for your work on this PR.

I've left a few suggestions for fixes. In addtion:
1. Add the **appRoleAssignedResources** relationship to the list of relationships for the user resource type.
2. Surface this API in the TOC

Please reach out internally if you have any questions.

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +title: "List appRoleAssignments granted to a user"
- The result is technically not an [appRoleAssignment](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0) but a [SP](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0) object instead.
- Suggestion to maintain the default title as per titling convention but add the description in brackets

```suggestion
title: "List appRoleAssignedResources (service principals that a user has appRoleAssignments to)"
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +description: "Get the servicePrincipal resources from the appRoleAssignedResources navigation property."
Suggestion to make is a user-friendly description for SEO
```suggestion
description: "Get the service principals to which the user has an app role assignment either directly or through group membership."
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +# List appRoleAssignments granted to a user
```suggestion
# List appRoleAssignedResources (service principals that a user has appRoleAssignments to)
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +Get the servicePrincipal resources from the appRoleAssignedResources navigation property.
Align this description with the user-friendly description you apply in the "description" metadata

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +|Application|**TODO: Provide applicable permissions.**|
Please specify the required permissions

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +GET /users/{usersId}/appRoleAssignedResources
I think this API is specially indexed for [advanced query capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries?view=graph-rest-1.0)?
```suggestion
GET /me/appRoleAssignedResources?$count=true
ConsistencyLevel: eventual

GET /users/{usersId}/appRoleAssignedResources?$count=true
ConsistencyLevel: eventual
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Please document the supported OData query parameters. I see many are specified in your API.md but not all seem to be work.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/14026935/185898806-4f6564ef-c380-4c6d-9072-cbb7f3c8aaa8.png">

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +|Authorization|Bearer {token}. Required.|
I believe that ConsistencyLevel is a required header?
```suggestion
|Authorization|Bearer {token}. Required.|
| ConsistencyLevel | eventual. This header and `$count` are required when calling this API. For more information about the use of **ConsistencyLevel** and `$count`, see [Advanced query capabilities on Azure AD directory objects](/graph/aad-advanced-queries). |
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +If successful, this method returns a `200 OK` response code and a collection of [servicePrincipal](../resources/serviceprincipal.md) objects in the response body.
Doesn't hurt to add this error code.
However, I recommend that you update your error messaging to be more intuitive, telling the user that the API doesn't work without the advanced query capabilities. I've tagged you on bug 1861337 to take this up with the engineering team.
```suggestion
If successful, this method returns a `200 OK` response code and a collection of [servicePrincipal](../resources/serviceprincipal.md) objects in the response body. If you don't specify the `$count` query parameter and set the **ConsistencyLevel** header to `eventual`, this API returns  `404 Not Found error`.
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +  "name": "list_serviceprincipal"
Unique name to avoid conflicts
```suggestion
  "name": "list_appRoleAssignedResources_users"
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +GET https://graph.microsoft.com/beta/me/appRoleAssignedResources
```suggestion
GET https://graph.microsoft.com/beta/me/appRoleAssignedResources?$count=true
ConsistencyLevel: eventual
```

2022-08-22 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/user-list-approleassignedresources.md
> +{
Please replace this JSON with an actual SP object.

2022-09-13 16:41 UTC, opbld34 commented
Docs Build status updates of commit _[faa652c](https://github.com/eringreenlee/microsoft-graph-docs/commits/faa652c6cee8903e31017407393fb2e7e9b7c60b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209131639288475-17847/BuildReport?accessString=992fa91b217e33343006200cf61756c66cc54dba65bb3f9f492e33af86be25df).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 16:43 UTC, opbld34 commented
Docs Build status updates of commit _[1a9976c](https://github.com/eringreenlee/microsoft-graph-docs/commits/1a9976c4a11762d692dbd271a5be490b126ebdaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209131640078174-17847/BuildReport?accessString=b461ba088862a8277d435fea3fb1421369facbd7fab265ebf75e0e7043e3e07c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 16:46 UTC, opbld30 commented
Docs Build status updates of commit _[b60e44d](https://github.com/eringreenlee/microsoft-graph-docs/commits/b60e44d29dfc3b370c4c89902e6b2c08155b9fe3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209131644040853-17847/BuildReport?accessString=a0d3c6ed1e9e096b298d8c0f10b00089b39fb94fd07edaac139677017d6274cd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 16:48 UTC, opbld33 commented
Docs Build status updates of commit _[4f99bb4](https://github.com/eringreenlee/microsoft-graph-docs/commits/4f99bb493efd83c369b561782bf9801522e3f2e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209131644301062-17847/BuildReport?accessString=c5a00c0b91a83d418399b7416afdaa2aed028bda437ecc3dad6c4391394b2b75).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 20:14 UTC, opbld34 commented
Docs Build status updates of commit _[13e9f70](https://github.com/eringreenlee/microsoft-graph-docs/commits/13e9f704ffaf1dc1fb94b04c49405d4fcc279ea8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-fa1908a44488127d37866d1470ac5487-d4b3c3ba)
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="fa1908a44488127d37866d1470ac5487-d4b3c3ba"></a>
### [api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md)
 - **Line 84, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152010204907-17847/BuildReport?accessString=b6462099653e872976bcf3e9bdaf36d9f3d5828eebfa168282429f030c5cfb49).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 20:16 UTC, opbld30 commented
Docs Build status updates of commit _[510b4b4](https://github.com/eringreenlee/microsoft-graph-docs/commits/510b4b48cf13819e3d5209006e7585e01c45b9ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-fa1908a44488127d37866d1470ac5487-8c56e187)
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="fa1908a44488127d37866d1470ac5487-8c56e187"></a>
### [api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md)
 - **Line 84, Column 1**: **[Warning: code-block-unclosed - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152013190770-17847/BuildReport?accessString=cbdb3c5c679dddf370ff3a0fc0bdd7bf7ea49a994015f20e415207e8105e88b9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 20:24 UTC, opbld32 commented
Docs Build status updates of commit _[dd4d310](https://github.com/eringreenlee/microsoft-graph-docs/commits/dd4d310117ea924357be43f43beea21fd9eb7132)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152015359125-17847/BuildReport?accessString=b8b5e7e980961d9dd16e443931ef21c04a235694af0fed306af3286b82fcdaa7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 20:44 UTC, opbld33 commented
Docs Build status updates of commit _[eb09f10](https://github.com/eringreenlee/microsoft-graph-docs/commits/eb09f104840d57bf692064bbda420cd4aec4c345)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152041263735-17847/BuildReport?accessString=44b9db7cf586e55e31df77c37c80b33c294857b31b28e08f5134cc5a7f369576).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 20:52 UTC, opbld34 commented
Docs Build status updates of commit _[f544917](https://github.com/eringreenlee/microsoft-graph-docs/commits/f54491750e5cdd87d832ee3dff309176abd18c74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8bab98a4)
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-8bab98a4"></a>
### [api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml)
 - **Line 9974, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152047540803-17847/BuildReport?accessString=de4ac4f59ec66cd0be38bd7793fe970503201607c8fc41561e84bd8f45f118f7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 21:14 UTC, eringreenlee commented
#sign-off

2022-09-15 21:14 UTC, Licantrop0 requested changes

2022-09-15 21:14 UTC, Licantrop0 commented on api-reference/beta/api/user-list-approleassignedresources.md
> +GET https://graph.microsoft.com/beta/me/appRoleAssignedResources?$count=true
let's add `$select=displayName,accountEnabled,servicePrincipalType,signInAudience` to reflect the output.

2022-09-15 21:14 UTC, Licantrop0 commented on api-reference/beta/api/user-list-approleassignedresources.md
> +This method supports the `$count`, `$expand`, `$filter`, `$orderBy`, `$select`, and `$top` [OData query parameters](/graph/query-parameters) to help customize the response. The default and maximum pa
"The default and maximum page sizes are 100 and 999 service principal objects respectively."

This is not true. We support returning all service principals even if they are > than 999
/cc @joaopprado

2022-09-15 21:18 UTC, opbld30 commented
Docs Build status updates of commit _[8b7a4e6](https://github.com/eringreenlee/microsoft-graph-docs/commits/8b7a4e6a1607a73d911911e52c3efa1e85721eb3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-580103b2)
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-580103b2"></a>
### [api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml)
 - **Line 9974, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152116089108-17847/BuildReport?accessString=385f002f515f362fb80ac6dd2fc8052bcc670171a0a111a2d5dad07291a31b99).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 15:34 UTC, opbld31 commented
Docs Build status updates of commit _[8228ced](https://github.com/eringreenlee/microsoft-graph-docs/commits/8228ceda452cf598d1670e5d936f19caa1897e80)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5939bd57)
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-5939bd57"></a>
### [api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml)
 - **Line 9974, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209161532381880-17847/BuildReport?accessString=c5ad3598561f55ad70d2cbb844e731731ac3638c12e72e69346a09fdc075a063).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 16:18 UTC, opbld32 commented
Docs Build status updates of commit _[a34ea9a](https://github.com/eringreenlee/microsoft-graph-docs/commits/a34ea9acc0980c5fb358c8373413b6aeee84d70d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9e6246f3)
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-9e6246f3"></a>
### [api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml)
 - **Line 9974, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209191614530815-17847/BuildReport?accessString=7c1d980fa9ccc7c4cf3c8c96d637c593dfaaf0a4ecfd18b69a0434f28e44989a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 17:06 UTC, Licantrop0 commented on api-reference/beta/api/user-list-approleassignedresources.md
> +| Application.Read.All, Directory.Read.All | Delegated (personal MSFT account)) | **Not supported**  |
```suggestion
| Permission type                        | Permissions (from least to most privileged)                             |
| :------------------------------------- | :---------------------------------------------------------------------- |
| Delegated (work or school account)     | User.ReadBasic.All, Directory.Read.All, AppRoleAssignment.ReadWrite.All |
| Delegated (personal Microsoft account) | Not supported.                                                          |
| Application                            | Directory.Read.All, AppRoleAssignment.ReadWrite.All                     |
```

Permissions needs to include also user, as the original [appRoleAssignments](https://learn.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http#permissions)

2022-09-22 17:08 UTC, Licantrop0 approved these changes

2022-09-22 17:10 UTC, Licantrop0 commented
@joaopprado updated permissions, please check if they are ok now.
@FaithOmbongi: after Joao approval, can you please validate and merge?

2022-09-22 17:10 UTC, opbld31 commented
Docs Build status updates of commit _[3f49063](https://github.com/eringreenlee/microsoft-graph-docs/commits/3f490631e4053f735ee1350fc4ba619a77a360f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a0629599)
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a0629599"></a>
### [api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml)
 - **Line 9974, Column 21**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221707202280-17847/BuildReport?accessString=2cd5b7aec6c03eb51ec84d579cdde13040b17594ec2060458a8fdc3b85461a0d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 09:57 UTC, opbld30 commented
Docs Build status updates of commit _[2e7386e](https://github.com/eringreenlee/microsoft-graph-docs/commits/2e7386e613aaef81c2f9d134b148d02bfa58dd47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-approleassignedresources.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/api/user-list-approleassignedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-approleassignedresources?view=graph-rest-beta&branch=pr-en-us-17847) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/eringreenlee/microsoft-graph-docs/blob/approleassignedresources/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209260954364314-17847/BuildReport?accessString=97e62f6b4ebd1b256227c26e6e2d7607d892c132c48e6d76a6e28e3e40e5d236).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 18:11 UTC, eringreenlee commented
#sign-off

2022-09-27 03:32 UTC, merged