Adding role specific details to the document educationSubmission:submit/unsubmit
microsoftgraph/microsoft-graph-docs pull request #17853
Opened 2022-07-26 22:05 UTC by sgoarla

A teacher can submit or unsubmit on behalf of a student. This documentation changes is to add the expected submission state when the logged in account is as teacher or student.
The story for this change is: https://dev.azure.com/1edu/Homeroom/_workitems/edit/146732

Here is the current version of the docs for graph beta: 
educationSubmission: submit - https://docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&tabs=http
educationSubmission: unsubmit - https://docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&tabs=http

As discussed, added a tabular section for roles for better readability - please review.

2022-07-26 22:08 UTC, opbld31 commented
Docs Build status updates of commit _[d44779e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d44779ec1c70f27b81eded143d4a73e649038f35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262205469078-17853/BuildReport?accessString=50a1a12d8d434bf0c0f565ab7d3a2d0139718c6675502e81cdb6b9304df2b426).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 03:55 UTC, opbld34 commented
Docs Build status updates of commit _[e4b09e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4b09e971cf03835a5ad5229e64c73e1595f8b60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207270353572550-17853/BuildReport?accessString=cad7927bcd9f64c82080fb9a959d8ccfe34a703cc3663f2e4e9a9e2bdd9221bd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-28 17:10 UTC, cristobal-buenrostro approved these changes

2022-08-02 16:37 UTC, sgoarla commented
@JarbasHorst / @Lauragra  - can one of you look at this changeset too.. Thanks

2022-08-31 14:34 UTC, isvargasmsft commented on api-reference/beta/api/educationsubmission-unsubmit.md
> +
GENERAL: 

Would you please give us a bit more information about these roles? Are they formally defined roles or is it natural language? 
What permission should a student use to submit then? 

If we just need to clarify that teachers can submit on behalf of a student, I believe adding that to the first paragraph of the topic should be enough. We avoid adding additional H2s for consistency across the reference documentation.

2022-08-31 14:34 UTC, isvargasmsft requested changes
Hello @sgoarla, 

Please give us more context on how these roles work and what is the intention of the feature. 

Kind regards,

Isaac

2022-08-31 23:24 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-unsubmit.md
> +
Hi @isvargasmsft 

the role is defined on how the user is added into the class, but for doc purposes we are using natural language.

Shanthan was following up this topic with Laura (about to use a new table or just simply mention in the paragraph. 
Her feedback was that using a table is easier to read.

You can find this conversation in the email subject "Graph documentation - Role details".
Adding screenshot for reference.

![image](https://user-images.githubusercontent.com/87383938/187801906-9c5cbb07-6d21-4ae7-bde6-a1cb41632187.png)

2022-09-01 00:15 UTC, JarbasHorst commented on api-reference/beta/api/educationsubmission-unsubmit.md
> +
@cristobal-buenrostro, please don't expose internal communication on GitHub. In this case, I recommend you to edit this comment and remove this image. Please, share this image with Isaac via Teams.

2022-09-01 01:16 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-unsubmit.md
> +
done, sorry about that

2022-09-01 16:08 UTC, opbld32 commented
Docs Build status updates of commit _[c7539c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7539c6ecb0713f317b00219d41e5b4e2fce5539)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209011606337286-17853/BuildReport?accessString=ae5068a44d55df96fcba35879178b9ef63975d8f90ae15d0b417c4f8356a0fdb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 16:23 UTC, opbld34 commented
Docs Build status updates of commit _[8922418](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89224184fef4f5c474287a80383b87550d2949e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209011622078079-17853/BuildReport?accessString=e3146580e3b4e3129d5613ec81445df9f02735c7175a69c241d9e5931d662d53).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 16:37 UTC, isvargasmsft approved these changes

2022-09-03 00:01 UTC, opbld31 commented
Docs Build status updates of commit _[c20ef90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c20ef90830c94f068635d10694b29476fc7dec3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209022359022061-17853/BuildReport?accessString=8148941930d96687cc24fa35c04d3650ec549c3a6b2c689e4b0c70e4d12912a7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-03 00:04 UTC, Lauragra commented on api-reference/beta/api/educationsubmission-unsubmit.md
> +This method changes the status of the submission from `submitted` to `working`. During the submit process, all the resources are copied from **submittedResources** to  **workingResources**. The teach
Should we delete the last sentence? It seems to contradict the same statement in the submit method topic. It seems to me that a teacher would not look at an "unsubmitted" resource for grading.

2022-09-03 00:05 UTC, opbld34 commented
Docs Build status updates of commit _[de5eb10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de5eb100829d57489bbdf5a2321a90c46f7378ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209030002513580-17853/BuildReport?accessString=35e270fd2d95fedda2fab3e67007ef219ca43b539df573667f9eb9f482d7a179).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-03 00:09 UTC, Lauragra commented on api-reference/v1.0/api/educationsubmission-unsubmit.md
> +This method changes the status of the submission from `submitted` to `working`. During the submit process, all the resources are copied from **submittedResources** to  **workingResources**. The teach
Same comment here - delete the last sentence?

2022-09-03 00:16 UTC, opbld30 commented
Docs Build status updates of commit _[4b9ad8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b9ad8e9323a3438abe7d0f90681b4c6bf537dcf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209030007396993-17853/BuildReport?accessString=4c235cbc22c4d40df5db4d846c77a315e8e61f48109acd4a8352d7d5016deebb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-03 00:19 UTC, opbld33 commented
Docs Build status updates of commit _[0abb965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0abb965e10c1db125063ed6664a87f5f3bd74e8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/beta/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-beta&branch=pr-en-us-17853) (graph-rest-beta) |
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-submit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-submit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sgoarla/SubmitUnsubmitRoleChanges146732/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-unsubmit?view=graph-rest-1.0&branch=pr-en-us-17853) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209030009153844-17853/BuildReport?accessString=1503c64251f75fa4470c4e2db9df5d1a7a2801098c8e3212f92b0b19ad789f07).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 20:30 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmission-unsubmit.md
> +This method changes the status of the submission from `submitted` to `working`. During the submit process, all the resources are copied from **submittedResources** to  **workingResources**. The teach
Noup, teacher can grade the submission even after it was unsubmitted.

2022-09-07 20:31 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationsubmission-unsubmit.md
> +This method changes the status of the submission from `submitted` to `working`. During the submit process, all the resources are copied from **submittedResources** to  **workingResources**. The teach
Noup, teacher can grade the submission even after it was unsubmitted.

2022-09-08 03:33 UTC, Lauragra approved these changes

2022-09-08 03:33 UTC, merged