Adding assign sensitivity label api documentation
microsoftgraph/microsoft-graph-docs pull request #17854
Opened 2022-07-26 22:21 UTC by jaLuthra

Our team is planning to expose a new Graph API which will allow users to assign sensitivity label asynchronously on a given drive item
This PR will document the API.

2022-07-26 22:23 UTC, opbld32 commented
Docs Build status updates of commit _[adfe907](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adfe9073cb0d4b9ea454da783be65d2ab8e686c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-36862f27)

<a id="5461856f432f509c445d97f27159c15d-36862f27"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 51, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262221395352-17854/BuildReport?accessString=2b8fac805dbd390c4915c147f5fc1d415313d94a3e664f005ce414645eda552c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 22:41 UTC, opbld34 commented
Docs Build status updates of commit _[6ed7fa8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ed7fa823b9272cc72b79b14aa15b4b75ceec86d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262239209488-17854/BuildReport?accessString=00f2720cb8612b7139193b171cfdef4d502458f54673678248fe047e2b17f239).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 23:00 UTC, opbld32 commented
Docs Build status updates of commit _[2f4c8ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f4c8ffc53b8f4b04c20c77310fc5ec4f4544ea7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262258308237-17854/BuildReport?accessString=134ccbd92f0da8832fe7e329e091a90e702de80a3d6eb06cd9621aa29178687a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 23:13 UTC, opbld34 commented
Docs Build status updates of commit _[a2e2f4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2e2f4ec7bc335494ed8d2ce69ea78b0ab685e19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207262311316574-17854/BuildReport?accessString=99ab96436a6b87eebaada9e840989140b0c72c4779ca255d049d2ecf0bca610e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 06:03 UTC, opbld31 commented
Docs Build status updates of commit _[3d175d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d175d8b298f3773cf5cdbb208b184de986e103a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-69702b39)
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-69702b39"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml)
 - **Line 11327, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/driveitem-assignsensitivitylabel.md.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207290601185119-17854/BuildReport?accessString=6746609537c016b2788163f302f19b79b58a8e86e9d07bc13556dd67125168f1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-29 06:11 UTC, opbld32 commented
Docs Build status updates of commit _[fa68075](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa680751e99951b6bb9cbdda888f7c6cb8310d7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207290609014616-17854/BuildReport?accessString=fb8613277809d5f488f12d86d5d3118c855782ed0c5fe63a0ef199cc6a5db598).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 19:06 UTC, opbld32 commented
Docs Build status updates of commit _[c0553d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0553d2a2dafbd7a790d1dc803e1b4fbfb0599ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021904055360-17854/BuildReport?accessString=ff9130f0be20e7402c4de12c1665ed9e351e68d09317bf3da8182d429ce69108).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 19:14 UTC, opbld30 commented
Docs Build status updates of commit _[6c5cab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c5cab9bfe8fdeb211ddec60044260ec4f9abec5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208021912028110-17854/BuildReport?accessString=f91cc6de1609fff935a0e3e3ffed7ec0cb6468cc6ac4e485672bd7e61e8d1bda).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 15:42 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +| unknownFutureValue | Evolvable enumeration sentinel value. Do not use.|
Why are we defining this enumeration here? This enum is already defined in [its parent topic here](https://docs.microsoft.com/en-us/graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta).

2022-08-08 15:44 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +| justificationText   | string                            | Optional. Justification text for audit purposes. Required when downgrading/removing label.                          |
Please add an intro sentence to this table. For example: 
```suggestion
In the request body, provide a JSON object with the following parameters.

| Name                | Value                             |Description                                                                                                          |
|:--------------------|:----------------------------------|:--------------------------------------------------------------------------------------------------------------------|
| sensitivityLabelId  | string                            | Required. Id of the sensitivity label to be assigned, or empty string to remove the sensitivity label.              |
| assignmentMethod    | sensitivityLabelAssignmentMethod  | Optional. The assignment method of the label on the document. Whether the assignment of the label was done automatically, standard or as a privileged operation (The equivalent to an administrator operation).                                                                            |
| justificationText   | string                            | Optional. Justification text for audit purposes. Required when downgrading/removing label.                          |
```

2022-08-08 17:32 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +If successful, the API returns details about how to [monitor the progress](/graph/long-running-actions-overview) of the assign sensitivity label operation, upon accepting the request.
Please mention the response code that is returned with the operation, the headers and a clarification that it doesn't return anything in the response body if applicable.

2022-08-08 17:33 UTC, opbld34 commented
Docs Build status updates of commit _[e7e1c9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7e1c9f9d774d09722875542274746dc6dc5f6f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208081730178149-17854/BuildReport?accessString=b7129299c04868de3d2a4ab6ab5e8068b6641fecc7bd7aef40096c8a482a517a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 17:49 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +POST /users/{user-id}/drive/root:/{item-path}/assignSensitivitylabel
According to the CSDL PR, the name of the operation has the L capitalized: assignSensitivityLabel.
```suggestion
POST /drives/{drive-id}/items/{item-id}/assignSensitivityLabel
POST /drives/{drive-id}/root:/{item-path}/assignSensitivityLabel
POST /groups/{group-id}/drive/items/{item-id}/assignSensitivityLabel
POST /groups/{group-id}/drive/root:/{item-path}/assignSensitivityLabel
POST /me/drive/items/{item-id}/assignSensitivityLabel
POST /me/drive/root:/{item-path}/assignSensitivityLabel
POST /sites/{site-id}/drive/items/{item-id}/assignSensitivityLabel
POST /sites/{site-id}/drive/root:/{item-path}/assignSensitivityLabel
POST /users/{user-id}/drive/items/{item-id}/assignSensitivityLabel
POST /users/{user-id}/drive/root:/{item-path}/assignSensitivityLabel
```

2022-08-08 17:51 UTC, opbld32 commented
Docs Build status updates of commit _[7c608be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c608be294f50c1762898cc25441bb7e6b633432)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208081747382837-17854/BuildReport?accessString=30837d43e89025bfda3112ad858599e0ce9e127c81a70c754702b1cadb45c499).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-08 17:51 UTC, isvargasmsft requested changes
Hello @jaLuthra, 

Thank you very much for your work in this PR. Please take a look at a few comments I made.
 
Kind regards, 

Isaac

2022-08-19 18:08 UTC, opbld30 commented
Docs Build status updates of commit _[09328eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09328ebafeb257d811147d200f63e25b91adce96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-29ac6870)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="5461856f432f509c445d97f27159c15d-29ac6870"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 54, Column 25**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/sensitivitylabelassignment'.`````
 - **Line 54, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208191804523421-17854/BuildReport?accessString=6f9992649f67fa01b1e2eb34fcecfca6f654cfc89e0e3f9aff330eda5c984c8c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[846a9a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/846a9a53ce527a5e8c9f800c90458d83af142308)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-2f1e632e)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="5461856f432f509c445d97f27159c15d-2f1e632e"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 54, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208191827281575-17854/BuildReport?accessString=9e9054e1947888770095f30a27522d864d598afe95136f816ae544c0895cb81b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 18:31 UTC, jaLuthra commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +POST /users/{user-id}/drive/root:/{item-path}/assignSensitivitylabel
fixed

2022-08-19 18:31 UTC, jaLuthra commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +If successful, the API returns details about how to [monitor the progress](/graph/long-running-actions-overview) of the assign sensitivity label operation, upon accepting the request.
updated

2022-08-19 18:40 UTC, jaLuthra commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +| justificationText   | string                            | Optional. Justification text for audit purposes. Required when downgrading/removing label.                          |
updated.

2022-08-19 18:40 UTC, jaLuthra commented on api-reference/beta/api/driveitem-assignsensitivitylabel.md
> +| unknownFutureValue | Evolvable enumeration sentinel value. Do not use.|
it's not directly a parent topic, sensitivityLabelAssignment is a resourceType which is part of return response of https://docs.microsoft.com/en-us/graph/api/driveitem-extractsensitivitylabels?view=graph-rest-beta&tabs=http. But in this API sensitivityLabelAssignment is not part of response. But I do get your point of not repeating same definition again. I have updated this with link to enum definition. Please have a look

2022-08-19 18:42 UTC, opbld31 commented
Docs Build status updates of commit _[a13e2c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a13e2c174ddecf88ec68826e81d8604862aba366)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-d4e57732)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="5461856f432f509c445d97f27159c15d-d4e57732"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 51, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 55, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208191841039729-17854/BuildReport?accessString=6a6ac6f36091b130f0465c1fb807be65fc0660587e04c52309030586082c9b0b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 18:44 UTC, jaLuthra commented
@isvargasmsft 
I have resolved your comments please have a re-look into this.

2022-08-19 19:57 UTC, opbld34 commented
Docs Build status updates of commit _[2149b9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2149b9b2f497cedd5638f1000f529edc68fb2874)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-dfe20870)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="5461856f432f509c445d97f27159c15d-dfe20870"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 56, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208191943025559-17854/BuildReport?accessString=cc8a73174c3a1473f2a360edb35e75f6665e16306ab9fc5afadd1fc2f3b6d867).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 19:59 UTC, opbld33 commented
Docs Build status updates of commit _[0de0cb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0de0cb5fa9cfb91cfe31f25280df6c2aa55f6764)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-3f64df54)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="5461856f432f509c445d97f27159c15d-3f64df54"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 56, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208191943366664-17854/BuildReport?accessString=5e9082f0fc65d337dd8367e0fdbaa3ddf7336502f8362963593640068f002018).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 20:04 UTC, isvargasmsft approved these changes

2022-08-20 06:30 UTC, opbld33 commented
Docs Build status updates of commit _[e407819](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4078195b6e064da2dfb6be1e3ead47d81371421)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-32ad5c2e)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="5461856f432f509c445d97f27159c15d-32ad5c2e"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 56, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208200628106018-17854/BuildReport?accessString=012bb005c145584569a0d0dc6ea5ce01588469c0cb5d8a67a16c9639de12ab83).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-03 00:26 UTC, opbld30 commented
Docs Build status updates of commit _[65703f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65703f57466d16538de7262c59d205e2024fec6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ed632f62)
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-ed632f62)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-ed632f62"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

<a id="5461856f432f509c445d97f27159c15d-ed632f62"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 56, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209030024177307-17854/BuildReport?accessString=e632244899d18436fe1f50942e7fb01d486256bcebc92ff4f57f79fccee33756).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-03 00:31 UTC, opbld32 commented
Docs Build status updates of commit _[d0d570a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0d570ab2be578924a9d178d16cae1534287c6fb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2dea1fed)
[api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-assignsensitivitylabel?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) | [Details](#user-content-5461856f432f509c445d97f27159c15d-2dea1fed)
[api-reference/beta/resources/driveitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/resources/driveitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-beta&branch=pr-en-us-17854) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-2dea1fed"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/toc.yml)
 - **Line 9960, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

<a id="5461856f432f509c445d97f27159c15d-2dea1fed"></a>
### [api-reference/beta/api/driveitem-assignsensitivitylabel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jaluthra-exposeAssignSensitivityLabel/api-reference/beta/api/driveitem-assignsensitivitylabel.md)
 - **Line 56, Column 25**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/resources/sensitivitylabelassignment?view=graph-rest-beta#sensitivitylabelassignmentmethod-values`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209030025093592-17854/BuildReport?accessString=6aa5ba2c7e1524ecad98e6a9d6ec4d0a436cd98226da2e581bf9b3c2652a837c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-03 00:37 UTC, merged