entitlement management: introduce SOD relationships to v1.0
microsoftgraph/microsoft-graph-docs pull request #17871
Opened 2022-07-27 21:11 UTC by markwahl-msft

Separation of duties with incompatible access packages and groups is an existing feature of entitlement management that previously has only been surfaced in the beta API.

2022-07-27 21:17 UTC, opbld31 commented
Docs Build status updates of commit _[36e7e52](https://github.com/markwahl-msft/microsoft-graph-docs/commits/36e7e52fef192d77aaac27ee7e8552c365499351)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207272111049823-17871/BuildReport?accessString=e3692da9642f7dce225aa2b13799b2c16b494d1111509c96c14cfc87e6492e9c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 22:50 UTC, opbld30 commented
Docs Build status updates of commit _[d69f20f](https://github.com/markwahl-msft/microsoft-graph-docs/commits/d69f20ffdcdba31a040fd916eaae210e9c5b87b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202207272247410366-17871/BuildReport?accessString=fe58cc800bb8c244862e4b8df4f36463b251b2f2a1d801736aee0dce47282d95).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 18:55 UTC, opbld34 commented
Docs Build status updates of commit _[c09e9fc](https://github.com/markwahl-msft/microsoft-graph-docs/commits/c09e9fcc21ac6949ec1579f36bdb3122ca7019c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209061852524717-17871/BuildReport?accessString=7db6edfb3b1415bec5fa2201d88a0623d537b315b290b4fa232508f30b380023).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 00:11 UTC, opbld31 commented
Docs Build status updates of commit _[2ef7ec2](https://github.com/markwahl-msft/microsoft-graph-docs/commits/2ef7ec24317e997767022f1646d9323eb00f57da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209200006509965-17871/BuildReport?accessString=c7e8d27005ff0d2b6a16ef8d03ac6136259d311a48465ac4c17549548eba08b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 15:23 UTC, opbld34 commented
Docs Build status updates of commit _[b12806b](https://github.com/markwahl-msft/microsoft-graph-docs/commits/b12806bc793556d89fece963ab0aa4d4da89af27)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 23:52 UTC, opbld30 commented
Docs Build status updates of commit _[a120a8c](https://github.com/markwahl-msft/microsoft-graph-docs/commits/a120a8c422966fd14ab4a6760f714e7d3b378717)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209222349070631-17871/BuildReport?accessString=ed9b86a097e7115b4411fe9d91bfd9a07e3c81d522dacfca8c6079c4b3a7ea67).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 22:16 UTC, opbld33 commented
Learn Build status updates of commit _[aedfbe1](https://github.com/markwahl-msft/microsoft-graph-docs/commits/aedfbe15718ea521de3493f34e92c47daa911ffa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209282157277792-17871/BuildReport?accessString=fd7ed4a097409dd1405e15dcb441eea60a6ef18db1e9fb93057d68a86f437448).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 11:09 UTC, FaithOmbongi requested changes
Hi @markwahl-msft - Thank you for your work on this PR.

Review feedback:
- Surface the additionalAccess method in the methods table of https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0
- Document the 7 APIs that relate to the 3 new relationships in acecsspackage.md. Surafce them in the methods table of the accessPackage resource doc and TOC as well.

2022-09-29 11:09 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +            - name: Additional access
Precede with a verb
```suggestion
            - name: Check additional access
```

2022-09-29 11:09 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackageassignment-additionalaccess.md
> +# [HTTP](#tab/http)
Will be inserted by the snippets generator. Currently distorts the page.
```suggestion
```

2022-09-29 11:09 UTC, FaithOmbongi commented on changelog/Microsoft.IGAELM.json
> +        "Description": "Added the **incompatibleGroups** navigation property on [accessPackage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackage?view=graph-rest-1.0) resource.",
nit
```suggestion
        "Description": "Added the **incompatibleAccessPackages** relationship to the [accessPackage](https://docs.microsoft.com/graph/api/resources/accesspackage?view=graph-rest-1.0) resource.",
        "Target": "accessPackage"
      },
      {
        "Id": "9b5a17bc-343d-4381-a7d3-6cd7224df1f1",
        "ApiChange": "Relationship",
        "ChangedApiName": "accessPackagesIncompatibleWith",
        "ChangeType": "Addition",
        "Description": "Added the **accessPackagesIncompatibleWith** relationship to the [accessPackage](https://docs.microsoft.com/graph/api/resources/accesspackage?view=graph-rest-1.0) resource.",
        "Target": "accessPackage"
      },
      {
        "Id": "9b5a17bc-343d-4381-a7d3-6cd7224df1f1",
        "ApiChange": "Relationship",
        "ChangedApiName": "incompatibleGroups",
        "ChangeType": "Addition",
        "Description": "Added the **incompatibleGroups** relationship on [accessPackage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackage?view=graph-rest-1.0) resource.",
```

2022-09-30 16:36 UTC, opbld32 commented
Learn Build status updates of commit _[901780c](https://github.com/markwahl-msft/microsoft-graph-docs/commits/901780cd391194cc23b81099718d1855613c4605)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301633279913-17871/BuildReport?accessString=6aa3f77d75b37f17c725f172a7da348f35bc48abf598f2bfd029509267a8ef4b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-30 16:38 UTC, opbld34 commented
Learn Build status updates of commit _[f6a83fd](https://github.com/markwahl-msft/microsoft-graph-docs/commits/f6a83fda2a59500f3126795188263937b44ce9e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209301634450719-17871/BuildReport?accessString=096dfaed3d33ca0879ffe164242579449a3f73e9e63180acb39c68f6f3ee6ddd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 20:35 UTC, opbld30 commented
Learn Build status updates of commit _[baa0775](https://github.com/markwahl-msft/microsoft-graph-docs/commits/baa0775ce90397a55fa76618773536abd1129065)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210042032577336-17871/BuildReport?accessString=fb1cfb69016595f43e166f07e412d525f767a99020f77e6fd13eb9e5a6f14525).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 14:52 UTC, opbld31 commented
Learn Build status updates of commit _[f8787d7](https://github.com/markwahl-msft/microsoft-graph-docs/commits/f8787d75b7f0838933e732f2914dd5b69bc032dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051449359996-17871/BuildReport?accessString=e8eb3e7c83eeb98248be2bb8a7b44da4eebf0744543bcfc565442c0270d691fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 16:16 UTC, opbld31 commented
Learn Build status updates of commit _[2d105e0](https://github.com/markwahl-msft/microsoft-graph-docs/commits/2d105e01a0bc0d56a0f1af12a356871ebbfe71e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051614157713-17871/BuildReport?accessString=a4f2b48efb5bcb45702288f5a6642b7ec60938f881d633e903609e33d92a5b35).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 16:19 UTC, opbld33 commented
Learn Build status updates of commit _[2d105e0](https://github.com/markwahl-msft/microsoft-graph-docs/commits/2d105e01a0bc0d56a0f1af12a356871ebbfe71e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051614387333-17871/BuildReport?accessString=99065d7aeba59c5d7b04ef71c24c2af943a0dcbe2fa016d42d91aca1718ae4b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 19:25 UTC, opbld30 commented
Learn Build status updates of commit _[414b285](https://github.com/markwahl-msft/microsoft-graph-docs/commits/414b28527b9303150ab365f6b972580ac2896abd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210051922517402-17871/BuildReport?accessString=3177f6456936d1c2f3bb2b2826e735c076e0a1a61d2b506d24ab27ac9dbc7cd1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-05 23:22 UTC, opbld34 commented
Learn Build status updates of commit _[5a4fd56](https://github.com/markwahl-msft/microsoft-graph-docs/commits/5a4fd5634c5f6eaecd621df32e8a00a0fe26b40f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210052319384579-17871/BuildReport?accessString=23521766ac11da9c242dae91a60d4e48c8eecdf50dfcc1a0f3d5fd7f525e43e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 18:36 UTC, FaithOmbongi approved these changes
Approved with suggestions.

2022-10-06 18:36 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accesspackage.md
> +|incompatibleGroups | [group](group.md) collection | The groups whose members are ineligible to be assigned this access package. |
nit: alphabetical order for easy scanning

2022-10-06 18:36 UTC, FaithOmbongi commented on api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md
> +DELETE https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages/{id}/incompatibleAccessPackages/{id}/$ref
GLOBAL: actual IDs.

2022-10-10 23:16 UTC, markwahl-msft commented on api-reference/v1.0/resources/accesspackage.md
> +|incompatibleGroups | [group](group.md) collection | The groups whose members are ineligible to be assigned this access package. |
updated

2022-10-11 02:19 UTC, opbld30 commented
Learn Build status updates of commit _[09b8f8b](https://github.com/markwahl-msft/microsoft-graph-docs/commits/09b8f8b48ef161e0837cc265d06eaca0fef5b1f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/accesspackageassignment-additionalaccess.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackageassignment-additionalaccess.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accesspackageassignment.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/entitlementmanagement-overview.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/resources/entitlementmanagement-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-1.0&branch=pr-en-us-17871) (>= graph-rest-1.0) |
[changelog/Microsoft.IGAELM.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210110216572254-17871/BuildReport?accessString=270accd852d499901613ab961a5a0f3dd56c8d28b3488015c0d4717fd3fd70b3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 02:21 UTC, merged