Application permission- rectifying for some APIs
microsoftgraph/microsoft-graph-docs pull request #17928
Opened 2022-08-03 06:30 UTC by Altamish-MS

Application permission incorrectly documented for 1 API and missing for 2 APIs

2022-08-03 06:32 UTC, opbld34 commented
Docs Build status updates of commit _[d605807](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d605807d82fe6415e168c2e158fb45808dd8444d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/v1.0/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-1.0&branch=pr-en-us-17928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/v1.0/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-1.0&branch=pr-en-us-17928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/v1.0/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-1.0&branch=pr-en-us-17928) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208030630213776-17928/BuildReport?accessString=9d7b638c2193eace5f9eb30753cbc829ebc849fb901fbee744bc1af367e998d2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 21:05 UTC, isvargasmsft requested changes
Hello @Altamish-MS, 

Thank you very much for these fixes. 

I noticed the beta topic of bookingcustomerquestion-get.md shows not supported for Application permissions. Please take time to update the beta topic as well. 

Thank you!

Isaac Vargas

2022-08-03 21:05 UTC, isvargasmsft commented on api-reference/v1.0/api/bookingcustomquestion-get.md
> +| Application   | BookingsAppointment.ReadWrite.All, Bookings.Read.All  |
Would you be so kind to fix this in the beta topic as well, please?

2022-08-09 06:37 UTC, Altamish-MS commented on api-reference/v1.0/api/bookingcustomquestion-get.md
> +| Application   | BookingsAppointment.ReadWrite.All, Bookings.Read.All  |
Resolved in latest iteration

2022-08-09 06:38 UTC, opbld31 commented
Docs Build status updates of commit _[89a5950](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89a59505a2b79f730cbfa33c922ba0f9c0fb1a76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/beta/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-beta&branch=pr-en-us-17928) (graph-rest-beta) |
[api-reference/v1.0/api/bookingappointment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/v1.0/api/bookingappointment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingappointment-delete?view=graph-rest-1.0&branch=pr-en-us-17928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/bookingbusiness-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/v1.0/api/bookingbusiness-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingbusiness-list?view=graph-rest-1.0&branch=pr-en-us-17928) (>= graph-rest-1.0) |
[api-reference/v1.0/api/bookingcustomquestion-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mybranch/api-reference/v1.0/api/bookingcustomquestion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/bookingcustomquestion-get?view=graph-rest-1.0&branch=pr-en-us-17928) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208090637087875-17928/BuildReport?accessString=bcefbb45fc68e4b0401d463b2e0bec4f70a3001493afbc0d379c31fe171f0818).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 14:25 UTC, isvargasmsft approved these changes

2022-08-11 02:53 UTC, merged