Document filter and order by properties for each endpoint -queryparameters
microsoftgraph/microsoft-graph-docs pull request #17933
Opened 2022-08-03 15:49 UTC by Sureshpadimi88

2022-08-03 15:52 UTC, opbld33 commented
Docs Build status updates of commit _[c89a801](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c89a8016ad190104e88ff2088abe4ec52cb3140f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-b1dfbccdb53463132d676f8a4ac93928-22e77715)
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-b795957b6bda6e539377a54d97ea2f5c-22e77715)
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-5b6da964b277285cc6ac8fee55c38127-22e77715)
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-81fcb7e3ceea2c528466a9c5be9260b4-22e77715)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-22e77715)
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-d9ae4fcb879baef35c4ab21c90c86832-22e77715)
[api-reference/v1.0/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationclass-list-categories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-a6a82041db71df98bada7f294dea26ff-22e77715)
[api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationsubmission-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-d7f10f00a6d3e3a0274cfd0c0958266a-22e77715)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-22e77715)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-22e77715)

<a id="b1dfbccdb53463132d676f8a4ac93928-22e77715"></a>
### [api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Suresh-Padimi' is not a valid GitHub ID.`````

<a id="b795957b6bda6e539377a54d97ea2f5c-22e77715"></a>
### [api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'suresh-padimi' is not a valid GitHub ID.`````

<a id="5b6da964b277285cc6ac8fee55c38127-22e77715"></a>
### [api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'suresh-padimi' is not a valid GitHub ID.`````

<a id="81fcb7e3ceea2c528466a9c5be9260b4-22e77715"></a>
### [api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'suresh-padimi' is not a valid GitHub ID.`````

<a id="0817dce4456c16725d5333633847d38f-22e77715"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml)
 - **Line 15112, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

<a id="d9ae4fcb879baef35c4ab21c90c86832-22e77715"></a>
### [api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Suresh-Padimi' is not a valid GitHub ID.`````

<a id="a6a82041db71df98bada7f294dea26ff-22e77715"></a>
### [api-reference/v1.0/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationclass-list-categories.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found [...]

2022-08-04 15:53 UTC, opbld30 commented
Docs Build status updates of commit _[6ac3d5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ac3d5ef0f784268416843cdeccc25d936e1a9bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-07eaf9b0)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-07eaf9b0)
[api-reference/v1.0/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationclass-list-categories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-a6a82041db71df98bada7f294dea26ff-07eaf9b0)
[api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationsubmission-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-d7f10f00a6d3e3a0274cfd0c0958266a-07eaf9b0)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-07eaf9b0)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-07eaf9b0)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |

<a id="0817dce4456c16725d5333633847d38f-07eaf9b0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml)
 - **Line 15119, Column 17**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/security-informationprotectionpolicysetting-get.md'.`````

<a id="bfd8c19de3575aa712e64aac5152826f-07eaf9b0"></a>
### [api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Sureshpadii88' is not a valid GitHub ID.`````

<a id="a6a82041db71df98bada7f294dea26ff-07eaf9b0"></a>
### [api-reference/v1.0/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationclass-list-categories.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'suresh-padimi' is not a valid GitHub ID.`````

<a id="d7f10f00a6d3e3a0274cfd0c0958266a-07eaf9b0"></a>
### [api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationsubmission-list-resources.md)
 [...]

2022-08-09 12:25 UTC, opbld34 commented
Docs Build status updates of commit _[69ef2d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69ef2d7ad7c3ab45fe391f45a2336970db655f54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-17f809ed)
[api-reference/v1.0/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationclass-list-categories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-a6a82041db71df98bada7f294dea26ff-17f809ed)
[api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationsubmission-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-d7f10f00a6d3e3a0274cfd0c0958266a-17f809ed)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-17f809ed)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-17f809ed)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educ [...]

2022-08-09 13:37 UTC, opbld30 commented
Docs Build status updates of commit _[dc62022](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc6202205cc09892596e23de43f59af14c620020)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-ab25f678)
[api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationsubmission-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-d7f10f00a6d3e3a0274cfd0c0958266a-ab25f678)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-ab25f678)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-ab25f678)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&bra [...]

2022-08-10 14:52 UTC, opbld30 commented
Docs Build status updates of commit _[75de6b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75de6b04cfb788f2867dc31161b12dbeb77accc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-f6a58fec)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-f6a58fec)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-f6a58fec)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-f6a58fec)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch= [...]

2022-08-10 15:12 UTC, opbld33 commented
Docs Build status updates of commit _[b25bcd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b25bcd01c05d120d6147151e834dfbb5799224d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-83cdd635)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-83cdd635)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-83cdd635)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-83cdd635)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch= [...]

2022-08-11 15:29 UTC, opbld33 commented
Docs Build status updates of commit _[875f28e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/875f28ecef56800d6d07349765ef9e109d3c1e97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-57f10ee1)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-57f10ee1)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-57f10ee1)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-57f10ee1)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/ [...]

2022-08-11 15:31 UTC, opbld32 commented
Docs Build status updates of commit _[99c4b1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99c4b1e6dd320fcebc92776b23d67908a494a56a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-0bdff749)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-0bdff749)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-0bdff749)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-0bdff749)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/ [...]

2022-08-11 15:33 UTC, opbld32 commented
Docs Build status updates of commit _[a8bcde7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8bcde797f497c99d7cebdbc8263b56c3ed4706a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-05362252)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-05362252)
[concepts/education-upload-feedback-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-feedback-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-feedback-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-5691228c62b131fc8432d9847112b665-05362252)
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-17933) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-05362252)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/ [...]

2022-08-11 15:36 UTC, opbld34 commented
Docs Build status updates of commit _[c4b46a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4b46a6b783aa28d3b3e84baf59e2d4fb5cdd9c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-ab48901a)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-ab48901a)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en [...]

2022-08-11 17:32 UTC, opbld32 commented
Docs Build status updates of commit _[499e970](https://github.com/microsoftgraph/microsoft-graph-docs/commits/499e9709deb13f6ca30d00161bc4b814f8a4c1cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-bb4e8386)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-bb4e8386)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branc [...]

2022-08-12 11:40 UTC, opbld32 commented
Docs Build status updates of commit _[b9d0205](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9d0205bb45eb97bc5fe22b52253e9a30820aa07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-2e3d33b6)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-2e3d33b6)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) ( [...]

2022-08-16 14:29 UTC, opbld30 commented
Docs Build status updates of commit _[fec339b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fec339b211d3cf28709a1e6586e0e3b8f3b928bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-153d05de)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-153d05de)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=gra [...]

2022-08-16 15:24 UTC, opbld34 commented
Docs Build status updates of commit _[04ff108](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04ff1084fd569cbbe7a07b59c055df5721e5e07d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-f29afd8e)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-f29afd8e)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmitteds [...]

2022-08-19 15:06 UTC, opbld33 commented
Docs Build status updates of commit _[5bcc005](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bcc005a2e1851ef3380c1277e0acdbe34272b12)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-319dec77)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-319dec77)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmitteds [...]

2022-09-01 22:48 UTC, cristobal-buenrostro requested changes

2022-09-01 22:48 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationrubric-get.md
> +```## Optional query parameters
remove the **```** at the beginning and leave one empty space line before.

2022-09-01 22:48 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-get-rubric.md
>  ## Request headers
make sure you leave empty lines before and after the "Optional query parameters" block.

please verify and change for ALL pages if needed.

2022-09-01 22:48 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationrubric-get.md
> +```## Optional query parameters
**## Optional query parameters** must start in the next line.

2022-09-02 06:21 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationassignment-get-rubric.md
>  ## Request headers
changes done

2022-09-02 06:21 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationrubric-get.md
> +```## Optional query parameters
changes done

2022-09-02 06:26 UTC, opbld30 commented
Docs Build status updates of commit _[981c3cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/981c3cbaf4c0461100e99f030e08b9c1ebc723d5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-471a622c)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-submissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-471a622c)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmitteds [...]

2022-09-07 17:38 UTC, cristobal-buenrostro requested changes

2022-09-07 17:38 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-get-rubric.md
> +
don't remove the ```, it is needed to specify the end of the http block.

2022-09-07 17:38 UTC, cristobal-buenrostro commented on api-reference/v1.0/api/educationrubric-get.md
> +
same here, don't remove the ```

2022-09-07 17:38 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationrubric-get.md
> +```## Optional query parameters
**## Optional query parameters** must be in the next line.

2022-09-09 07:27 UTC, opbld33 commented
Docs Build status updates of commit _[5f9bcbb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f9bcbbd3dd88ed9cdebf75e90a61d559707bc4b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b744ce7)

<a id="7b744ce7"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 5f9bcbbd3dd88ed9cdebf75e90a61d559707bc4b in branch spadimi/queryparameters of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit a152ac9dbfa2de89967d5c68dddbb50e737ad8cc). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209090726592650-17933/BuildReport?accessString=ad27f88d39b9a32b5e175339cfdd991f37eaee82bf59e3e889ff7bf81cd86e6a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 07:29 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationassignment-get-rubric.md
> +
Resolved

2022-09-09 07:29 UTC, Sureshpadimi88 commented on api-reference/v1.0/api/educationrubric-get.md
> +
Resolved

2022-09-09 07:29 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationrubric-get.md
> +```## Optional query parameters
Changes done

2022-09-09 07:30 UTC, Sureshpadimi88 commented
Resolved

2022-09-09 15:47 UTC, cristobal-buenrostro requested changes
New comments, please take a look

2022-09-09 15:47 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationrubric-get.md
>  ```## Optional query parameters
remove the three apostrophes from this line

2022-09-09 15:47 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationsubmittedsubmissionresource-get.md
> +```## Optional query parameters
remove the three apostrophes from this line

2022-09-09 15:47 UTC, cristobal-buenrostro commented on concepts/permissions-reference.md
> +| _EduRoster.ReadBasic.All_            | Read a limited subset of the organization's roster. | Allows the app to read a limited subset of both the structure of schools and classes in an organization'
you can try this git command

**git checkout HEAD~1 concepts/permissions-reference.md**
try this command increasing the number ~1 until you get a success message.

after that, use the same git commands flow.
git status
git add .
git commit -m "reverting changes"
git push

2022-09-09 15:58 UTC, opbld31 commented
Docs Build status updates of commit _[b444068](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b444068788c7a58612f9e3ade2ae291dd1e6e1b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-aca21692)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-09 16:04 UTC, opbld33 commented
Docs Build status updates of commit _[a24cc03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a24cc03480f29acae62cca5b38a7b4b66c9748af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-279ef395)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-09 16:45 UTC, opbld31 commented
Docs Build status updates of commit _[1c66683](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c66683949be68f0df388080fd199442520cb96a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-45018a05)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-09 17:58 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationrubric-get.md
>  ```## Optional query parameters
changes done

2022-09-09 17:59 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationsubmittedsubmissionresource-get.md
> +```## Optional query parameters
changes done

2022-09-09 21:37 UTC, bivasmaiti26 requested changes
Please double check all the endpoints for the query params and make the changes.

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/beta/api/educationsubmission-get.md
> +This method supports the `$filter`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Single entity shouldn't support $filter, please double check

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/beta/api/educationsubmission-list-outcomes.md
> +## Optional query parameters
we support $filter (at least for FeedbackResources we support `isof`)

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/beta/api/educationsubmission-list-resources.md
> +This method supports the `$top` and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
I think we support $filter and $orderby, please double check.

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/beta/api/educationsubmission-list-submittedresources.md
> +This method supports the `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
please double check if we support $filter, $orderby, $top

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/beta/api/educationsubmissionresource-get.md
> +This method supports the `$top`, `$filter`, and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Single entity shouldn't support $top, $filter.

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/beta/api/educationsubmittedsubmissionresource-get.md
> +description: "Returns a submitted resource. This will be available to a teacher or an application with application permissions after a student has submitted, and will be available to the student afte
Can you put "retrieve" instead of "return" since return has so many meanings.

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationassignment-get-rubric.md
> +This method supports the `$top`,and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
We allow only 1 rubric per assignment here, so don't think we should put $top here

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationassignment-list-resources.md
> +This method supports the`$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
We should support $filter, $orderby $top here as well

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationassignment-list-submissions.md
> +This method supports the`$filter`, and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
$top is also supported

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationassignmentresource-get.md
> +This method supports the `$top`,and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
$top shouldn't be supported, please double check

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationclass-get.md
>  title: "Get educationClass"
This isn't our API should we change it @sharad-sharma-msft ?

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationclass-get.md
> +This method supports the `$top`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
$top shouldn't be supported for single entity

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationclass-list-categories.md
> +This method supports the `$top`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Please double check if we support $filter

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationclass-list-schools.md
>  ---
not our endpoint, please check with @sharad-sharma-msft

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationclass-list.md
>  ---
not our endpoint, please check with @sharad-sharma-msft

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationrubric-get.md
> +This method supports the `$top`, `$filter`, `$orderBy`, and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-paramet
$top, $filter and $orderby shouldn't work for single entity, please double check

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationsubmission-get.md
> +This method supports the `$filter`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
$filter shouldn't work for single entity

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationsubmission-list-resources.md
> +This method supports the `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
$top, $filter and $orderby should work, please double check and update..

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationsubmission-list-submittedresources.md
> +
$top, $filter and $orderby should work, please double check

2022-09-09 21:37 UTC, bivasmaiti26 commented on api-reference/v1.0/api/educationsubmissionresource-get.md
> +
$top and $filter shouldn't work for single entity

2022-09-09 21:37 UTC, bivasmaiti26 commented on concepts/permissions-reference.md
>  | :---------------------------------- | :-------------------------------------------------- | :--------------------------------------------------------------------------------------------------------
Not sure what changes are we making here. @sharad-sharma-msft  can you please check this?

2022-09-12 09:39 UTC, Sureshpadimi88 commented on api-reference/v1.0/api/educationsubmission-list-submittedresources.md
> +
updated details

2022-09-12 09:57 UTC, Sureshpadimi88 commented on api-reference/v1.0/api/educationsubmissionresource-get.md
> +
resolved

2022-09-12 09:58 UTC, Sureshpadimi88 commented on api-reference/v1.0/api/educationsubmission-list-resources.md
> +This method supports the `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
resolved

2022-09-12 09:59 UTC, Sureshpadimi88 commented on api-reference/v1.0/api/educationsubmission-get.md
> +This method supports the `$filter`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
resolved the comments

2022-09-12 10:02 UTC, opbld34 commented
Docs Build status updates of commit _[cdcf412](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cdcf4124179bb8be92383f78d32787916ac9f0a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-15a36698)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 13:10 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationassignmentresource-get.md
> +This method supports the `$top`, and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Changes done

2022-09-12 13:11 UTC, opbld32 commented
Docs Build status updates of commit _[7702062](https://github.com/microsoftgraph/microsoft-graph-docs/commits/770206262a20e288312ff61c07fe3ee7d9def29f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-0cf7360d)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 15:47 UTC, opbld31 commented
Docs Build status updates of commit _[e79ca0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e79ca0be2283c7d604f9c375a998da65e39ac51f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-8bf071e7)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 15:57 UTC, opbld32 commented
Docs Build status updates of commit _[cc16b00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc16b00c31de85185ef19f5998d70af8dadf8e01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-850ed27e)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 16:01 UTC, Sureshpadimi88 commented on concepts/permissions-reference.md
>  | :---------------------------------- | :-------------------------------------------------- | :--------------------------------------------------------------------------------------------------------
Christobal was helping to exclude the file.

2022-09-12 16:03 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationassignment-list-submissions.md
> +This method supports the `$filter`, and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
changes updated

2022-09-12 16:11 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationclass-get-group.md
> +This method supports the `$top`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
discussed with  christobal  he conforms to remove $top from the optional query parameters

2022-09-12 16:19 UTC, opbld31 commented
Docs Build status updates of commit _[52a5ab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52a5ab98b1426e521b03f2f89c285906954ada81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-1ae9d5ce)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 19:38 UTC, opbld34 commented
Docs Build status updates of commit _[beeab0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beeab0ba902114c18fc6dea3dd0b54bcb2d945ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-ba027ce8)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 19:43 UTC, opbld33 commented
Docs Build status updates of commit _[799c6d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/799c6d66b78a4b5db4c2cea546476365daa3afe8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) | [Details](#user-content-a86839a0da12ac8895fa2ddb60390b58-87341921)
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-re [...]

2022-09-12 19:43 UTC, cristobal-buenrostro commented on concepts/permissions-reference.md
>  | :---------------------------------- | :-------------------------------------------------- | :--------------------------------------------------------------------------------------------------------
@bivasmaiti26 and @Sureshpadimi88 
the file has been excluded from this PR

2022-09-13 08:18 UTC, Sureshpadimi88 commented on api-reference/beta/api/educationassignment-list-resources.md
>  This method supports the [OData Query Parameters](/graph/query-parameters) to help customize the response.
changes updated

2022-09-13 08:19 UTC, Sureshpadimi88 commented on api-reference/v1.0/api/educationsubmission-list-resources.md
> +This method supports the  `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
changes updated

2022-09-14 15:47 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationassignment-list-submissions.md
> +This method supports the `$filter`, and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
done

2022-09-14 15:49 UTC, cristobal-buenrostro commented on api-reference/beta/api/educationclass-get-group.md
> +This method supports the `$top`, `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
done

2022-09-14 17:15 UTC, opbld33 commented
Docs Build status updates of commit _[2c24348](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c24348d57e5dfd8b6e88bb891d0f7e421946764)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser- [...]

2022-09-14 17:17 UTC, opbld30 commented
Docs Build status updates of commit _[bc35b30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc35b3007beafe1274e6f1ce05725cd8ee68a4cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser- [...]

2022-09-15 16:14 UTC, opbld32 commented
Docs Build status updates of commit _[ca212ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca212efda5deac5872d323874387bb56060c6b1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser- [...]

2022-09-15 16:18 UTC, cristobal-buenrostro requested changes

2022-09-22 20:32 UTC, opbld34 commented
Docs Build status updates of commit _[c872c2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c872c2f79a26a63391037abf1c2c118cc88c034a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-referen [...]

2022-09-22 20:35 UTC, opbld34 commented
Docs Build status updates of commit _[eb7aa1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb7aa1b7755fbf1a3a3eaec9489a343f57bcd023)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-referen [...]

2022-09-22 20:38 UTC, opbld33 commented
Docs Build status updates of commit _[4a7c2ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a7c2ec777f99d3ea81101ff809b1e4584ed720a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0 [...]

2022-09-22 20:40 UTC, opbld32 commented
Docs Build status updates of commit _[211115f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/211115f3833c96c612a2cf02399cce130850231c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationclass-list-schools.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>=  [...]

2022-09-22 20:46 UTC, opbld34 commented
Docs Build status updates of commit _[1ab4689](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ab468932af454885e1ec158db35d56fb290ff81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branc [...]

2022-09-22 20:49 UTC, opbld34 commented
Docs Build status updates of commit _[b2e48a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2e48a92f26873e0a2f5ffbd854e9021ccb7a7ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branc [...]

2022-09-27 22:19 UTC, bivasmaiti26 approved these changes

2022-10-04 21:15 UTC, isvargasmsft approved these changes

2022-10-04 21:16 UTC, opbld32 commented
Learn Build status updates of commit _[958bfd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/958bfd50a774d0acad05eb2f0179bb7bd8fe642a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationrubric-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationrubric-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-outcomes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-outcomes?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationsubmittedsubmissionresource-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/beta/api/educationuser-list-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationuser-list-rubrics?view=graph-rest-beta&branch=pr-en-us-17933) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-17933) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spadimi/queryparameters/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&bran [...]

2022-10-05 04:10 UTC, merged