Adding graph API doc for Tenant Restrictions
microsoftgraph/microsoft-graph-docs pull request #17975
Opened 2022-08-08 23:37 UTC by vimrang

2022-08-08 23:40 UTC, opbld34 commented
Docs Build status updates of commit _[4a0f766](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a0f76634937bf4423ca3d9d804578635e4e8941)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-6dfb935d796a2196bd0f372d1f9e3fd8-089b97b7)
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-09a51ad075b6dba561e75d6a93fbd379-089b97b7)
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-089b97b7)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="6dfb935d796a2196bd0f372d1f9e3fd8-089b97b7"></a>
### [api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md)
 - **Line 68, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="09a51ad075b6dba561e75d6a93fbd379-089b97b7"></a>
### [api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md)
 - **Line 18, Column 15**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/crosstenantaccesspolicyb2bsettings.md'.`````

<a id="391bdffcd7eafd78c028f5e6cfc0429b-089b97b7"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 60, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208082338023624-17975/BuildReport?accessString=1671e74f3d99d0961f749ad21555396f9345a84781e91aee3c596d40c294efa6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 00:06 UTC, opbld31 commented
Docs Build status updates of commit _[f2212ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2212efdcd953ebf23bf1f8d640c22e8f3fc013d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-c6451fd1)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-c6451fd1"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 60, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208090002511895-17975/BuildReport?accessString=4b2d3177bf9eb30c73b0b9d787cb7b73e277fa932cfe3ff6c507c5d7b9b6cc15).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 16:11 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
>  ### Response
@vimrang - you are missing the tenantRestrictions property in the example response.

2022-08-09 16:14 UTC, jkdouglas commented
@vimrang - it also looks like you missed updating crosstenantaccesspolicyconfigurationpartner-create.md with the new tenant restrictions property and the example response.

2022-08-09 22:45 UTC, vimrang commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
>  ### Response
Fixed with the commit [f244582](https://github.com/microsoftgraph/microsoft-graph-docs/pull/17975/commits/f2445829fe38f32ea31855f845e5f68ae8b01132)

2022-08-09 22:46 UTC, opbld32 commented
Docs Build status updates of commit _[f244582](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2445829fe38f32ea31855f845e5f68ae8b01132)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-c8c9e1a4)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-c8c9e1a4"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 60, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092244237416-17975/BuildReport?accessString=9078369042266baae62a14bee97adcfdd81c9b378e6f9ec6d867ae26eb013bbc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 18:38 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +  "tenantRestrictions":
You need to fix this example response. It should be 

"tenantRestrictions": null,

2022-08-10 18:41 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
> +      "tenantRestrictions":
You need to fix this example response. It should be

"tenantRestrictions": null,

2022-08-10 20:07 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-list-partners.md
> +      "tenantRestrictions":
Nevermind. I see what you are doing here. Ignore me.

2022-08-10 20:08 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +  "tenantRestrictions":
There is an issue with this response somehow (according to API doctor). Check and make sure all the formatting is correct.

2022-08-12 09:05 UTC, FaithOmbongi requested changes
Hi @vimrang - I've left suggestions for minor fixes to descriptions. In addition:
- Document the crossTenantAccessPolicyTargetType enumeration in the api-reference/beta/resources/enums.md.
- **GLOBAL:** I recommend regenerating all the examples so that the JSONs can be properly formatted and easier to inspect. Of note: Please delete these two objects from all payloads crossCloudMeetingConfiguration and tenantRestrictions>devices.
- Also delete the `# [HTTP](#tab/http)` lines just before the request URLs. This line will also be included when the new snippets are generated.
- In the Overview article, add a See also section (`## See also`) and a link to the admin doc: https://docs.microsoft.com/en-us/azure/active-directory/external-identities/cross-tenant-access-overview

2022-08-12 09:05 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **TenantRestictions** property to the [crossTenantAccessPolicyConfigurationPartner](https://docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicycon
```suggestion
          "ChangedApiName": "tenantRestictions",
          "ChangeType": "Addition",
          "Description": "Added the **tenantRestictions** property to the [crossTenantAccessPolicyConfigurationPartner](https://docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta) resource.",
```

2022-08-14 17:50 UTC, vimrang commented
> Hi @vimrang - I've left suggestions for minor fixes to descriptions. In addition:
> 
> * Document the crossTenantAccessPolicyTargetType enumeration in the api-reference/beta/resources/enums.md.
> * **GLOBAL:** I recommend regenerating all the examples so that the JSONs can be properly formatted and easier to inspect. Of note: Please delete these two objects from all payloads crossCloudMeetingConfiguration and tenantRestrictions>devices.
> * Also delete the `# [HTTP](#tab/http)` lines just before the request URLs. This line will also be included when the new snippets are generated.
> * In the Overview article, add a See also section (`## See also`) and a link to the admin doc: https://docs.microsoft.com/en-us/azure/active-directory/external-identities/cross-tenant-access-overview
> 
> BTW - Please ensure that the tenantRestrictions>devices property is kept hidden in the schema if you don't intend for it to be part of this release.

2022-08-14 18:13 UTC, vimrang commented
> * Document the crossTenantAccessPolicyTargetType enumeration in the api-reference/beta/resources/enums.md.

This is already there in enums.md 

> *In the Overview article, add a See also section (## See also) and a link to the admin doc: https://docs.microsoft.com/en-us/azure/active-directory/external-identities/cross-tenant-access-overview

This is already listed under ## Next steps as documentation link

>*Also delete the # [HTTP](#tab/http) lines just before the request URLs. This line will also be included when the new snippets are generated.
Deleted and regenerated

2022-08-14 18:16 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
> +description: "The default configuration defined for inbound and outbound settings of Azure AD B2B collaboration and B2B direct connect and Tenant Restrictions settings."
Yes, it is part of the same policy but a different settings

2022-08-14 18:18 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
> +| tenantRestrictions  |[crossTenantAccessPolicyTenantRestrictions](../resources/crosstenantaccesspolicytenantrestrictions.md) | Defines your default tenant restrictions configuration for your organiz
Corrected it

2022-08-14 18:19 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +description: "Defines how to configure Azure AD Tenant Restrictions settings for your organization users accessing external organizations using external idenities on your network or devices.Settings
Corrected it

2022-08-14 18:19 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +Defines how to target your cross-tenant access policy tenant restrictions settings. Settings can be targeted to specific users, groups, or applications. You can also use keywords to target specific g
corrected it

2022-08-14 18:25 UTC, vimrang commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **TenantRestictions** property to the [crossTenantAccessPolicyConfigurationPartner](https://docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicycon
corrected

2022-08-14 19:20 UTC, opbld30 commented
Docs Build status updates of commit _[f866b44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f866b44e351284da6d43fe7f8dd4d5980232c8cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9431a2f2)

<a id="9431a2f2"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit f866b44e351284da6d43fe7f8dd4d5980232c8cf in branch trv2doc of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit ffe29cfe004992202a99de1720d7caf000dc0271). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208141920334477-17975/BuildReport?accessString=5944b37fe856b1321bceffd500bac7348315f3eabedff8113a3777fcea4a18c8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-14 19:36 UTC, opbld30 commented
Docs Build status updates of commit _[64a6665](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64a666524c882a1a36c9cb5bc622a96e9d9b9bc3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cf6cc7e1)

<a id="cf6cc7e1"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 64a666524c882a1a36c9cb5bc622a96e9d9b9bc3 in branch trv2doc of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit ffe29cfe004992202a99de1720d7caf000dc0271). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208141935534002-17975/BuildReport?accessString=993671546de3bad1bcd8c7f6e842ae807cfc3c1b3d88996aedfb147d46bcd7b0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 16:35 UTC, opbld34 commented
Docs Build status updates of commit _[e169557](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e169557f144fad98d42a23deab59e455c9f30c12)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-093e1539)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&branch=pr-en-us-17975) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-1.0&branch=pr-en-us-17975) (>= graph-rest-1.0) |
[api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/v1.0/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-1.0&branch=pr-en-us-17975) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-17975) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-17975) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](htt [...]

2022-09-07 16:51 UTC, opbld34 commented
Docs Build status updates of commit _[f2d38c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2d38c0ec2f1d6ab57f9da6085e29fdc8670d05b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-802a65d9)

<a id="802a65d9"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209071648157648-17975/BuildReport?accessString=6d8173c7294364b94df1d61ead5897a1a191521c474c34f1c4bbb7abb30ba87d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 00:37 UTC, opbld34 commented
Docs Build status updates of commit _[9e8c451](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e8c451d62861ccce088a7815a0a23f4a92cc285)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-b6e240d5)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-b6e240d5"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 62, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080035468368-17975/BuildReport?accessString=808619e74596c72319db7340693179400c9f1af2a2f0e265220193c4e881fad2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47"> [...]

2022-09-08 00:50 UTC, opbld33 commented
Docs Build status updates of commit _[da7d39a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da7d39ae4d9394707686f13e1a5e6de766e969ca)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-ef5e7ae3)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-ef5e7ae3"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 62, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080048186157-17975/BuildReport?accessString=4aaccc62a887eb8c612c42b2e6840a9d6047b3cd6b30dbe442025721fa71d5b2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47"> [...]

2022-09-09 16:06 UTC, vimrang commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +  "tenantRestrictions":
Fixed this.

2022-09-09 16:17 UTC, vimrang commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md
> +| tenantRestrictions  |[crossTenantAccessPolicyTenantRestrictions](../resources/crosstenantaccesspolicytenantrestrictions.md) | Defines your default tenant restrictions configuration for your organiz
I made sure the descriptions are the same

2022-09-09 16:17 UTC, vimrang commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +| tenantRestrictions  |[crossTenantAccessPolicyTenantRestrictions](../resources/crosstenantaccesspolicytenantrestrictions.md) | Defines the partner-specific tenant restrictions configuration for your
I made sure the descriptions are the same

2022-09-09 16:21 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +The cross-tenant access settings API can be used to set up multiple configurations for allowing or blocking access to and from your organization. The following table highlights scenarios, shows an ex
fixed this

2022-09-09 16:27 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
> +description: "The partner-specific configuration that is defined for inbound and outbound settings of Azure AD B2B collaboration and B2B direct connect and Tenant Restrictions settings."
Corrected it

2022-09-09 16:28 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md
> +| tenantRestrictions | [crossTenantAccessPolicyTenantRestrictions](../resources/crosstenantaccesspolicytenantrestrictions.md) | Defines the partner-specific tenant restrictions configuration for your
fixed

2022-09-09 16:29 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +| Office365 | Includes the applications mentioned as part of the [Office365](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365) suite. |
fixed

2022-09-09 16:39 UTC, opbld33 commented
Docs Build status updates of commit _[02f6666](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02f6666e9922f62a7720d084e5695e5fe796d120)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-e6bb221e)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-e6bb221e"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 62, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091637146079-17975/BuildReport?accessString=962348933840a37833c77f5d666b3a7ab37ce9bb51f1211dfacbe1428244aa7f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross rep [...]

2022-09-09 16:51 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +The cross-tenant access settings API can be used to set up multiple configurations for allowing or blocking access to and from your organization. The following table highlights scenarios, shows an ex
minor
```suggestion
The cross-tenant access settings API can be used to set up multiple configurations for allowing or blocking access to and from your organization. The following table highlights scenarios, shows an example of the API response, and what the interpretation should be of that response. **b2bSetting** is used as a placeholder for any B2B inbound (**b2bCollaborationInbound** or **b2bDirectConnectInbound**) or outbound (**b2bCollaborationOutbound** or **b2bDirectConnectOutbound**) or  tenant restrictions (**tenantRestrictions**) configuration.
```

2022-09-09 16:54 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicytarget.md
> +| target | String | Can be one of the following values: <li> The unique identifier of the user, group, or application <li> `AllUsers` <li> `AllApplications`  <li> `Office365` - Includes the applicati
Oversight
```suggestion
| target | String | Can be one of the following values: <li> The unique identifier of the user, group, or application <li> `AllUsers` <li> `AllApplications` - Refers to any [Microsoft cloud application](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#microsoft-cloud-applications). <li> `Office365` - Includes the applications mentioned as part of the [Office365](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365) suite. |
```

2022-09-09 16:54 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicytarget.md
>  ### Reserved values for targets that are applications
Delete Lines 25-31 because we're putting that info within the property description above

2022-09-09 16:55 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +| target | String | Can be one of the following values: <li> The unique identifier of the user, group, or application <li> `AllUsers` <li> `AllApplications`  <li> `Office365` - Includes the applicati
Let's have the description inline. Delete lines 27-33 below.
```suggestion
| target | String | Can be one of the following values: <li> The unique identifier of the user, group, or application <li> `AllUsers` <li> `AllApplications` - Refers to any [Microsoft cloud application](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#microsoft-cloud-applications). <li> `Office365` - Includes the applications mentioned as part of the [Office365](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365) suite |
```

2022-09-09 16:56 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +| Office365 | Includes the applications mentioned as part of the [Office365](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365) suite. |
Is redundant after updating the property description above. Delete.

2022-09-09 17:00 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +
The **devices** property was exposed though we'd assumed it wouldn't be.  Please document it as well. If customers can;'t use it, add the "Not implemented." statement.

2022-09-09 17:01 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicy-overview.md
> +Granular controls let you determine the users, groups, and apps, both in your organization and in external organizations, that can participate in Azure AD B2B collaboration and Azure AD B2B direct co
Updated overview page

2022-09-09 17:02 UTC, opbld31 commented
Docs Build status updates of commit _[0c5f43d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c5f43dc134551bb33bf62cf8ad92e98705545f6)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-132bee2d)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-132bee2d"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 66, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091700563051-17975/BuildReport?accessString=d495ef05ed2dfdbee2b5ffe58d034faf1dc9e5d4e6e057e7b69627fb5152907f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross rep [...]

2022-09-09 17:09 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +}
Add the inherited properties  + devicesFilter
```suggestion
{
  "@odata.type": "#microsoft.graph.crossTenantAccessPolicyTenantRestrictions",
  "usersAndGroups": {
    "@odata.type": "microsoft.graph.crossTenantAccessPolicyTargetConfiguration"
  },
  "applications": {
    "@odata.type": "microsoft.graph.crossTenantAccessPolicyTargetConfiguration"
  },
  "devices": {
    "@odata.type": "microsoft.graph.devicesFilter"
  }
}
```

2022-09-09 17:18 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytarget.md
>  ### Reserved values for targets that are applications
deleted

2022-09-09 17:18 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytarget.md
> +| target | String | Can be one of the following values: <li> The unique identifier of the user, group, or application <li> `AllUsers` <li> `AllApplications`  <li> `Office365` - Includes the applicati
corrected it

2022-09-09 17:19 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +| target | String | Can be one of the following values: <li> The unique identifier of the user, group, or application <li> `AllUsers` <li> `AllApplications`  <li> `Office365` - Includes the applicati
deleted and corrected target

2022-09-09 17:20 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +| Office365 | Includes the applications mentioned as part of the [Office365](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#office-365) suite. |
Deleted

2022-09-09 17:59 UTC, vimrang commented on api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md
> +}
Corrected and added a devicesFilter type as well

2022-09-09 18:01 UTC, opbld34 commented
Docs Build status updates of commit _[04b17ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04b17cab41311825c83a852f90c8d69c686cb991)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) | [Details](#user-content-391bdffcd7eafd78c028f5e6cfc0429b-2fcd446f)
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/devicesFilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/devicesFilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicesfilter?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="391bdffcd7eafd78c028f5e6cfc0429b-2fcd446f"></a>
### [api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md)
 - **Line 66, Column 18**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/external-identities/cross-cloud-settings' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091759057449-17975/BuildReport?accessString=d6abfd92cd27e400dd10934df4cff7ceb835183bb311e98621ea5bd964c8b07e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2022-09-09 18:32 UTC, FaithOmbongi approved these changes

2022-09-09 18:36 UTC, opbld31 commented
Docs Build status updates of commit _[83cc480](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83cc480924d7a0c8ae61ff7eaf84a8a45cf34d6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-resettosystemdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-delete?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicy-overview?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytarget?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/crosstenantaccesspolicytenantrestrictions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicytenantrestrictions?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/devicesFilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/devicesFilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicesfilter?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-17975) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/trv2doc/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091833552794-17975/BuildReport?accessString=2b4d5d82a3ea48558bf7b6755bad27474f98fe9f2b23ff3969b3f8790781f5b3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-11 02:12 UTC, Lauragra commented
@vimrang , if you would like to publish this PR, please remove the **do not merge** label and add **ready to merge**.

2023-03-04 01:43 UTC, Lauragra commented
@vimrang , our data shows that the APIs associated with this PR have shipped but we didn't merge the PR. Can you please take care of the merge conflicts so we can merge this PR?

2023-03-08 02:37 UTC, Lauragra commented
@vimrang , @FaithOmbongi , can you please resolve the merge conflicts in this PR? Thanks.

2023-03-08 08:26 UTC, FaithOmbongi commented
> @vimrang , our data shows that the APIs associated with this PR have shipped but we didn't merge the PR. Can you please take care of the merge conflicts so we can merge this PR?

Hi @Lauragra - As per @vimrang, we're looking at April for the feature to be deployed.

2023-05-22 17:47 UTC, FaithOmbongi commented
Close and reopen to trigger fresh changelog link validation.

2023-05-26 01:02 UTC, merged