Updates to the doc
microsoftgraph/microsoft-graph-docs pull request #17974
Opened 2022-08-08 19:52 UTC by charlieforce

Adding a new navigation property to teams resource

2022-08-08 19:54 UTC, opbld33 commented
Docs Build status updates of commit _[c40d153](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c40d153f47ff23cfa70ae83c82922ae6541daebc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CharlieKB-updates_to_doc/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-17974) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CharlieKB-updates_to_doc/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208081952377099-17974/BuildReport?accessString=3be86b49801c78f12c0c4d754f84dfe0992c524c7db62b13885227db25e61413).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 20:27 UTC, Danielabom commented
Hi @charlieforce, I'll be working on this PR. Please ping me once you get back from your PTO; thanks.

2022-08-16 19:53 UTC, Danielabom requested changes
Hi @charlieforce , thank you for working on this PR. I only have one comment, is there an operation associated with this property? Please confirm.

2022-08-24 14:43 UTC, Danielabom commented
Hi @paoladelhierro, Charlie reached out and told me that he has not been feeling well but that you would step up and continue the review. I'll appreciate it if you could address my comments. Thanks!

2022-08-24 15:12 UTC, paoladelhierro commented
> Hi @charlieforce , thank you for working on this PR. I only have one comment, is there an operation associated with this property? Please confirm.

Hi @Danielabom, yes this adds a new navigation property (templateDefinition) to the CreateTeam request body. Users can now use template@odata.bind or templateDefinition@odata.bind to create a Team from a template. Using the latter will allow the user to create a Team from a non-english template

2022-08-26 03:37 UTC, Danielabom commented
Hi @paagarwal123 and @charlieforce. As per Paola's comments there is a "create" operation but I do not see the file in the PR. Please follow-up; thanks!

2022-09-07 22:44 UTC, Danielabom approved these changes

2023-03-03 03:50 UTC, Lauragra commented on api-reference/beta/resources/team.md
> +| templateDefinition | [teamtemplatedefinition](teamtemplatedefinition.md)| Generic representation of a team template definition for a team with a specific structure and configuration.|
@charlieforce , FYI, I fixed the casing of the Type column here to match how it is specified in the teamtemplatedefinition resource topic, so that the PR will pass validation. We are working on merging PRs that are associated with APIs for which the schema is already live so I plan to merge this one. Can you please, in a follow-up PR, fix the casing in the teamtemplatedefinition to use lower camel case per the Graph standard, and fix in any other topics that reference the type? So you'll want to change "microsoft.graph.teamtemplatedefinition" to "microsoft.graph.teamTemplateDefinition". Thanks.

2023-03-03 03:52 UTC, merged