PR to add API doc for tenant contact settings
microsoftgraph/microsoft-graph-docs pull request #17981
Opened 2022-08-09 08:22 UTC by rogoy

2022-08-09 08:24 UTC, opbld34 commented
Docs Build status updates of commit _[09d1e86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09d1e8687a06e047c16e5156c28ca5a36eec5d44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-b63ce05c)
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-c384fc9fd46f6a27259bb0869d992790-b63ce05c)
[api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactinsightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0c592c2bc15a287f07f7735a5ba25a82-b63ce05c)
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-497fe498f324a7aa20dddc2120f9105e-b63ce05c)
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="cf8c554185c2e57a10ab4165b8c08ec3-b63ce05c"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="c384fc9fd46f6a27259bb0869d992790-b63ce05c"></a>
### [api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0c592c2bc15a287f07f7735a5ba25a82-b63ce05c"></a>
### [api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

<a id="497fe498f324a7aa20dddc2120f9105e-b63ce05c"></a>
### [api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208090822158895-17981/BuildReport?accessString=e2a0604356133782ecf34157029487905d52e550b074fa35d209cdcd5df4dcff).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in [...]

2022-08-09 13:52 UTC, opbld30 commented
Docs Build status updates of commit _[e7b9989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7b99890c2e7acbcd2868469835d6d8d0d97fe66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-305ac5cf)
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-c384fc9fd46f6a27259bb0869d992790-305ac5cf)
[api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactinsightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0c592c2bc15a287f07f7735a5ba25a82-305ac5cf)
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-497fe498f324a7aa20dddc2120f9105e-305ac5cf)
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="cf8c554185c2e57a10ab4165b8c08ec3-305ac5cf"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="c384fc9fd46f6a27259bb0869d992790-305ac5cf"></a>
### [api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0c592c2bc15a287f07f7735a5ba25a82-305ac5cf"></a>
### [api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

<a id="497fe498f324a7aa20dddc2120f9105e-305ac5cf"></a>
### [api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091350147907-17981/BuildReport?accessString=29b72cc94c8bea8ea04df858c03553b5782b744738f324188b94389c31dc05cd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in [...]

2022-08-09 14:01 UTC, opbld30 commented
Docs Build status updates of commit _[2daa856](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2daa856fa19d722022b1c4d15190af95cd68f152)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-efddb317)
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-c384fc9fd46f6a27259bb0869d992790-efddb317)
[api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactinsightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0c592c2bc15a287f07f7735a5ba25a82-efddb317)
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-497fe498f324a7aa20dddc2120f9105e-efddb317)
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="cf8c554185c2e57a10ab4165b8c08ec3-efddb317"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="c384fc9fd46f6a27259bb0869d992790-efddb317"></a>
### [api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0c592c2bc15a287f07f7735a5ba25a82-efddb317"></a>
### [api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

<a id="497fe498f324a7aa20dddc2120f9105e-efddb317"></a>
### [api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091359213184-17981/BuildReport?accessString=2f093d4e584762753ad058b8178c98c7ed64dfc1f77acef137a55337cae9d12d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in [...]

2022-08-09 14:14 UTC, opbld34 commented
Docs Build status updates of commit _[bd936f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd936f2dd0f68ff58334005d4a0e89f11c4c0f59)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-854e398d)
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-c384fc9fd46f6a27259bb0869d992790-854e398d)
[api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactinsightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0c592c2bc15a287f07f7735a5ba25a82-854e398d)
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-497fe498f324a7aa20dddc2120f9105e-854e398d)
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="cf8c554185c2e57a10ab4165b8c08ec3-854e398d"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="c384fc9fd46f6a27259bb0869d992790-854e398d"></a>
### [api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0c592c2bc15a287f07f7735a5ba25a82-854e398d"></a>
### [api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

<a id="497fe498f324a7aa20dddc2120f9105e-854e398d"></a>
### [api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091412343856-17981/BuildReport?accessString=26e38b24d7625714be6260084039200b1bbfa406076707d7789b57639700f471).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in [...]

2022-08-09 14:20 UTC, opbld32 commented
Docs Build status updates of commit _[9114ca4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9114ca41591f23fd739899b180ff70d5c0cbc301)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-0000b5eb)
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-c384fc9fd46f6a27259bb0869d992790-0000b5eb)
[api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactinsightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0c592c2bc15a287f07f7735a5ba25a82-0000b5eb)
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-497fe498f324a7aa20dddc2120f9105e-0000b5eb)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="cf8c554185c2e57a10ab4165b8c08ec3-0000b5eb"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="c384fc9fd46f6a27259bb0869d992790-0000b5eb"></a>
### [api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0c592c2bc15a287f07f7735a5ba25a82-0000b5eb"></a>
### [api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

<a id="497fe498f324a7aa20dddc2120f9105e-0000b5eb"></a>
### [api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'insightsSettings resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/insightssettings.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091418334455-17981/BuildReport?accessString=53bce4076329d79c4f81753eaab674004f301ed60c481143b19b3e2226dd2602).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the [...]

2022-08-10 06:05 UTC, opbld30 commented
Docs Build status updates of commit _[01dcc96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01dcc96bcb46af0db670786886446fb10126d7f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-81a393c8)
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-c384fc9fd46f6a27259bb0869d992790-81a393c8)
[api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactinsightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0c592c2bc15a287f07f7735a5ba25a82-81a393c8)
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-194267c81ecbbe8a27b471e5ad429604-81a393c8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="cf8c554185c2e57a10ab4165b8c08ec3-81a393c8"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="c384fc9fd46f6a27259bb0869d992790-81a393c8"></a>
### [api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="0c592c2bc15a287f07f7735a5ba25a82-81a393c8"></a>
### [api-reference/beta/resources/contactinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactinsightssettings.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'contactMergeSuggestions resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents privacy settings for insights.' is duplicated in 'beta/resources/contactinsightssettings.md(3,14)', 'beta/resources/insightssettings.md(3,14)'.`````

<a id="194267c81ecbbe8a27b471e5ad429604-81a393c8"></a>
### [api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'contactMergeSuggestions resource type' is duplicated with other articles: 'beta/resources/contactinsightssettings.md(10,1), beta/resources/contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208100603149179-17981/BuildReport?accessString=8178c44e1163081f2d4cfd330024ea00d459b97b824b515572915eb519e70e17).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-m [...]

2022-08-10 06:39 UTC, opbld32 commented
Docs Build status updates of commit _[67ea769](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67ea7699b52d9ad55c23c01e58bc70de64e84ab1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-426cf1f8325e35e31054d31a9546ed2a-1f563327)
[api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73f492c02056d2dfd94bbc9415fd4b93-1f563327)
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-194267c81ecbbe8a27b471e5ad429604-1f563327)
[api-reference/beta/resources/organizationcontactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-21e34bc8fc3029b86bd6f08c90596f54-1f563327)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1f563327)
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="426cf1f8325e35e31054d31a9546ed2a-1f563327"></a>
### [api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="73f492c02056d2dfd94bbc9415fd4b93-1f563327"></a>
### [api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="194267c81ecbbe8a27b471e5ad429604-1f563327"></a>
### [api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'contactMergeSuggestions resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/contactmergesuggestions.md(2,8), beta/resources/organizationcontactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'contactMergeSuggestions resource type' is duplicated with other articles: 'beta/resources/contactmergesuggestions.md(10,1), beta/resources/organizationcontactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="21e34bc8fc3029b86bd6f08c90596f54-1f563327"></a>
### [api-reference/beta/resources/organizationcontactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactmergesuggestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'contactMergeSuggestions resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/contactmergesuggestions.md(2,8), beta/resources/organizationcontactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'contactMergeSuggestions resource type' is duplicated with other articles: 'beta/resources/contactmergesuggestions.md(10,1), beta/resources/organizationcontactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0817dce4456c16725d5333633847d38f-1f563327"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 422, Column 19**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/organizationsettings-list-contactinsights.md'.`````
 - **Line 424, Column 19**: **[Warning: file-not-found - [See documentation] [...]

2022-08-10 06:49 UTC, opbld32 commented
Docs Build status updates of commit _[571b306](https://github.com/microsoftgraph/microsoft-graph-docs/commits/571b3060b94b2f590ef1ac33b88ed1b77eec0adb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-44850b91)
[api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-426cf1f8325e35e31054d31a9546ed2a-44850b91)
[api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73f492c02056d2dfd94bbc9415fd4b93-44850b91)
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-194267c81ecbbe8a27b471e5ad429604-44850b91)
[api-reference/beta/resources/organizationcontactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-21e34bc8fc3029b86bd6f08c90596f54-44850b91)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="3bb1f9a698692f441083446cb3d31a46-44850b91"></a>
### [api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/contactmergesuggestions-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get contactMergeSuggestions - Microsoft Graph beta' is duplicated in: 'beta/api/contactmergesuggestions-get.md(2,8), beta/api/organizationsettings-list-contactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get contactMergeSuggestions' is duplicated with other articles: 'beta/api/contactmergesuggestions-get.md(10,1), beta/api/organizationsettings-list-contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="426cf1f8325e35e31054d31a9546ed2a-44850b91"></a>
### [api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get contactMergeSuggestions - Microsoft Graph beta' is duplicated in: 'beta/api/contactmergesuggestions-get.md(2,8), beta/api/organizationsettings-list-contactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get contactMergeSuggestions' is duplicated with other articles: 'beta/api/contactmergesuggestions-get.md(10,1), beta/api/organizationsettings-list-contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="73f492c02056d2dfd94bbc9415fd4b93-44850b91"></a>
### [api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md)
 - **Line 4, Column 9**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://aka.ms/msgo?pagePath=Document-APIs/Guidelines/Metadata)**'.`````

<a id="194267c81ecbbe8a27b471e5ad429604-44850b91"></a>
### [api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'contactMergeSuggestions resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/contactmergesuggestions.md(2,8), beta/resources/organizationcontactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'contactMergeSuggestions resource type' is duplicated with other articles: 'beta/resources/contactmergesuggestions.md(10,1), beta/resources/organizationcontactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="21e34bc8fc3029b86bd6f08c90596f54-44850b91"></a>
### [api-reference/beta/resource [...]

2022-08-10 07:17 UTC, opbld34 commented
Docs Build status updates of commit _[e690b0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e690b0e7073eab0a9491ecdac2a918410dbfa4ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/contactmergesuggestions-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-get?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-3bb1f9a698692f441083446cb3d31a46-d0db0175)
[api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/contactmergesuggestions-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/contactmergesuggestions-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-f8f3702874260569eab0d768f0cba1fa-d0db0175)
[api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-426cf1f8325e35e31054d31a9546ed2a-d0db0175)
[api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73f492c02056d2dfd94bbc9415fd4b93-d0db0175)
[api-reference/beta/resources/contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/contactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-194267c81ecbbe8a27b471e5ad429604-d0db0175)
[api-reference/beta/resources/organizationcontactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactmergesuggestions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-21e34bc8fc3029b86bd6f08c90596f54-d0db0175)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="3bb1f9a698692f441083446cb3d31a46-d0db0175"></a>
### [api-reference/beta/api/contactmergesuggestions-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/contactmergesuggestions-get.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get contactMergeSuggestions - Microsoft Graph beta' is duplicated in: 'beta/api/contactmergesuggestions-get.md(2,8), beta/api/organizationsettings-list-contactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get contactMergeSuggestions' is duplicated with other articles: 'beta/api/contactmergesuggestions-get.md(10,1), beta/api/organizationsettings-list-contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f8f3702874260569eab0d768f0cba1fa-d0db0175"></a>
### [api-reference/beta/api/contactmergesuggestions-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/contactmergesuggestions-update.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update contactMergeSuggestions - Microsoft Graph beta' is duplicated in: 'beta/api/contactmergesuggestions-update.md(2,8), beta/api/organizationsettings-update-contactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update contactMergeSuggestions' is duplicated with other articles: 'beta/api/contactmergesuggestions-update.md(10,1), beta/api/organizationsettings-update-contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="426cf1f8325e35e31054d31a9546ed2a-d0db0175"></a>
### [api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get contactMergeSuggestions - Microsoft Graph beta' is duplicated in: 'beta/api/contactmergesuggestions-get.md(2,8), beta/api/organizationsettings-list-contactmergesuggestions.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get contactMergeSuggestions' is duplicated with other articles: 'beta/api/contactmergesuggestions-get.md(10,1), beta/api/organizationsettings-list-contactmergesuggestions.md(10,1)'. First level headings must be unique within a docset.`````

<a id="73f492c02056d2dfd94bbc9415fd4b93-d0db0175"></a>
### [api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md)
 - **Line 2, Column 8**: **[Warning: duplicate-titles - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update contactMergeSuggestions - Microsoft Graph beta' is duplicated in: 'beta/api/contactmergesuggestions-update.md(2,8), beta/api/organizationse [...]

2022-08-10 15:14 UTC, Danielabom commented
I reached out to @rohitgoyal7 but he's currently enjoying some time off.

2022-08-16 22:17 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: User Contact merge suggestions
Line 409:
@rogoy , please don't remove the "preview" designation for contact merge suggestions here. 
In the docs TOC, "(preview)" is to identify API sets, or individual API topics, that are applicable to only beta and not to v1.
In the case of (user) contact merge suggestions, that designation applies at that level of the TOC.

2022-08-16 23:58 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationcontactmergesuggestions.md
> +title: "contactMergeSuggestions resource type"
Lines 2 and 10:
I haven't seen your api.md and CSDL files, but based on your file name, if your resource is organizationContactMergeSuggestion, your topic title (and the TOC title which I'm commenting in detail in a separate email) should reflect that. Based on that assumption, please change the topic title to organizationContactMergeSuggestion resource type.

2022-08-17 00:02 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md
> +---
@Danielabom , please make sure to review the CSDL when you get it and determine the file name. 
Without the CSDL, it looks to me this filename doesn't follow our filenaming guidance.

@rogoy , did you use the files generated by Graph Studio?
If so, depending on the CSDL definition, there might be a bug.

2022-08-17 00:03 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md
> +Update the properties of a [contactMergeSuggestions](../resources/organizationcontactmergesuggestions.md) object.
Line 15:
The link text to the resource should be the same name as the resource.
Is the resource named organizationContactMergeSuggestion? (We can only tell after you point us to the CSDL offline, not in Github please.)

2022-08-17 00:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationcontactmergesuggestions.md
> +title: "contactMergeSuggestions resource type"
GLOBAL:
Please also make sure in all the topics pertaining to this feature, if you're referring to this resource, use the name organizationContactMergeSuggestion, not contactMergeSuggestions. I'm noticing in various places you have used the latter and that's misleading.

2022-08-17 00:17 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md
> +  "@odata.type": "Collection(microsoft.graph.insightsSettings)"
Line 72:
Without the CSDL, this is even more confusing - where does insightsSettings come from in relation to your API?

And if your topic is supposed to get a single instance, then your response body wouldn't be a collection either.

2022-08-17 00:21 UTC, angelgolfer-ms commented on changelog/Microsoft.People.json
> +			"ChangeList": [
@Danielabom , please make sure to guide @rogoy to get the appropriate changelog JSON in place. @rogoy , did you use Graph Studio to generate the JSON.

2022-08-17 00:23 UTC, angelgolfer-ms commented on api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md
> +PATCH /organization/{organizationId}/settings/contactInsights
If your API added a nav property to organizationSettings, please make sure to update that topic appropriately. (I can't tell as I don't have your API.md and CSDL files.)

2022-08-17 02:18 UTC, angelgolfer-ms requested changes
@rogoy , per my email with you (and @Danielabom and a couple others), I gave you some feedback about the TOC for your API. Along the way to give that feedback, I had to look at your PR and made a few comments in GitHub. Please take a look.
Per @Danielabom 's comment, she needs some more info from you to proceed with content review for the rest of the PR. She will remain the content reviewer.
If you have any questions about the TOC, please respond to the email thread I started. I don't intend to follow the progress of this PR in GitHub; Dani is your person for all the non-TOC issues, including the GitHub comments from me. Thank you.

2022-08-22 10:25 UTC, opbld30 commented
Docs Build status updates of commit _[628202e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/628202e85a9537fa12f8fbb15581252124b2b5a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationcontactmergesuggestions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactmergesuggestions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactmergesuggestions?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208221022534241-17981/BuildReport?accessString=3f337f6c4c78a48d84ac3dfcc2c911982039d31f38df89aa58835432f6fd2e16).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 10:38 UTC, opbld32 commented
Docs Build status updates of commit _[f0c9a26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0c9a266a9102a9b65edd732ef14517760d31ddf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-update-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-update-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-update-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationcontactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208231036066337-17981/BuildReport?accessString=9104d1a5a6356466b6ab5ab6fb4adf0857da1eea057b7c7c163332527c94e874).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 00:15 UTC, Danielabom commented on api-reference/beta/resources/organizationcontactinsights.md
> +|isEnabledInOrganization|Boolean| `true` if contact insights are enabled for the organization; `false` if it is disabled for all users without exceptions. Default is `true`. Optional.|
```suggestion
|isEnabledInOrganization|Boolean| If set to `true`, contact insights are enabled for the organization. If `false` contact insights are disabled for all users without exceptions. Default value is `true`. Optional. |

2022-08-24 00:22 UTC, Danielabom commented on api-reference/beta/resources/organizationcontactinsights.md
> +Represents _settings_ to manage the audience in an organization for whom intelligent features related to contact management (e.g. duplicate contact merge suggestions) are enabled in M365. The feature
```suggestion
Represents _settings_ to manage the audience in an organization in which intelligent features related to contact management (e.g. duplicate contact merge suggestions) are enabled in Microsoft 365. The feature availability can be controlled at the organization level (i.e., Tenant) or at a security group level (i.e., a subset of the organization). 
```

2022-08-24 00:28 UTC, Danielabom commented on changelog/Microsoft.People.json
> +				"ApiChange": "Resource",
Based on the Api.md and the CSDL files, "contact insights" is a nav property. If that's the case, the correct ApiChange is "Relationship".

2022-08-24 00:33 UTC, Danielabom commented on changelog/Microsoft.People.json
> +				"Description": "Added the [contactInsights](https://docs.microsoft.com/en-us/graph/api/resources/organizationSettings?view=graph-rest-beta) resource",
Based on the api.md and the CSDL files, "contact insights" is a navigation property. If that's the case, the correct description should be "Added the **contactInsights** navigation property to the .... 
Please follow example #3 of this wiki: [(https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)](url)

2022-08-24 00:36 UTC, Danielabom commented on api-reference/beta/resources/organizationcontactinsights.md
> +
Based on the api.md and the CSDL files, "contact insights" is a navigation property. If that's the case, could you please add the Relationships table to this file?

2022-08-24 00:47 UTC, Danielabom commented on api-reference/beta/api/organizationsettings-list-contactinsights.md
> +title: "Get organizationContactInsights"
Please clarify if this is a "Get" operation or a "List" operation. 
I presume that it is a "List" operation. If so, please follow the example Template for a List operation
 [Reference topic templates - Overview (azure.com)](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/344038/Reference-topic-templates?anchor=template-for-a-complex-type)

2022-08-24 01:05 UTC, Danielabom commented on api-reference/beta/api/organizationsettings-update-contactinsights.md
> +---
Please review the file name of this operation. For more information, see [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211751/File-naming](url)

2022-08-24 01:08 UTC, Danielabom commented on api-reference/beta/api/organizationsettings-update-contactinsights.md
> +# Update organizationContactInsights
Global comment for this operation: Please review "Template for an Update operation" [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/344038/Reference-topic-templates?anchor=template-for-an-update-operation](url)

2022-08-24 01:10 UTC, Danielabom commented on api-reference/beta/toc.yml
> +          - name: Get
Is this a "List" or a "Get" operation? Please see my comments here: [https://github.com/microsoftgraph/microsoft-graph-docs/pull/17981/files#diff-41558ccfc2857ae510ab4165b8c08ec3747750c249a2c9a08dc20b46b9752f4f](url)

2022-08-24 01:11 UTC, Danielabom requested changes
@rohitgoyal7, Thank you for working on this PR. Please review my comments. Thanks

2022-08-24 04:33 UTC, opbld31 commented
Docs Build status updates of commit _[04b888b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04b888b02210cd52d0a41a99ae6a8a8d9a83ce2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationcontactinsights-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationcontactinsights-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationcontactinsights-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationcontactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationcontactinsights-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208240430432736-17981/BuildReport?accessString=e636983b9b6957338bef7f7ed87bf96194f8799139c300f0fc513a39d273cd3e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 22:07 UTC, Danielabom commented on api-reference/beta/resources/organizationcontactinsights.md
> +---
@rohitgoyal7, we need to step back compare what you have in the CSDL, the info on the api.md and the files attached to the PR.
You are trying to add a new nav property/relationship called "contactInsights" that belongs to an entity called "organizationSettings". 
Question #1. Why was the file organizationContactInsights added to the PR? 
The resource "organizationSettings" has a relationship/nav property called "insightsSettings". 
Question #2: why was the "insightsSettings" file not included in the PR?
In my opinion, the file organizationContactInsights should be removed.

2022-08-24 22:22 UTC, Danielabom commented on api-reference/beta/resources/organizationcontactinsights.md
> +title: "organizationContactInsights resource type"
As stated before: 
We have a new nav property called "contactInsights" that will belong to a resource called organizationSettings.
The CSDL does not mention a resource called organizationContactInsights. The name organizationContactInsights is mentioned throughout the entire file and it should be fixed. 
Where should this operation be listed? I will be able to comment on the TOC until we solve this issue.

2022-08-24 22:23 UTC, Danielabom commented on api-reference/beta/api/organizationcontactinsights-update.md
> +title: "Update organizationContactInsights"
As stated before:
We have a new nav property called "contactInsights" that will belong to a resource called organizationSettings.
The CSDL does not mention a resource called organizationContactInsights. The name organizationContactInsights is mentioned throughout the entire file and it should be fixed.
Where should this operation be listed? I will be able to comment on the TOC until we solve this issue.

2022-08-24 22:24 UTC, Danielabom commented on api-reference/beta/api/organizationsettings-list-contactinsights.md
> +title: "List organizationContactInsights"
As stated before:
We have a new nav property called "contactInsights" that will belong to a resource called organizationSettings.
The CSDL does not mention a resource called organizationContactInsights. The name organizationContactInsights is mentioned throughout the entire file and it should be fixed.
Where should this operation be listed? I will be able to comment on the TOC until we solve this issue.

2022-08-24 22:32 UTC, Danielabom commented on api-reference/beta/api/organizationsettings-list-contactinsights.md
> +  "@odata.type": "microsoft.graph.insightsSettings"
If this is indeed a List operation, the "@odata.type" should be: "Collection(microsoft.graph.insightsSettings)"

2022-08-24 22:51 UTC, Danielabom commented on api-reference/beta/api/organizationcontactinsights-update.md
> +---
There is an Update insightsSettings operation [Update insights - Microsoft Graph beta | Microsoft [Docs]]((https://docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&tabs=http)) that includes itemInsights and peopleInsights? Should contactInsights be added here? Please check.

2022-08-25 10:04 UTC, opbld34 commented
Docs Build status updates of commit _[a3d1829](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3d18298a395f33862752cc8f671066fccf36846)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationcontactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactinsights.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationcontactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-1935bfd5010fc0d8d4395e74c815fbd3-bfdbcdba)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="1935bfd5010fc0d8d4395e74c815fbd3-bfdbcdba"></a>
### [api-reference/beta/resources/organizationcontactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationcontactinsights.md)
 - **Line 22, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/organizationcontactinsights-update.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251002160019-17981/BuildReport?accessString=47be0066c80c0f4a009390a70d0f33dfb9dd81c057c13780fd4d1dca0c0fe5eb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 10:25 UTC, opbld34 commented
Docs Build status updates of commit _[a104cea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a104cead345f2ce2a0d44b7feb84bf63b4dd2634)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-406e4f41)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-cf8c554185c2e57a10ab4165b8c08ec3-406e4f41)
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-406e4f41"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cf8c554185c2e57a10ab4165b8c08ec3-406e4f41"></a>
### [api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve properties of insightsSettings object for displaying or returning item insights in an organization.' is duplicated in 'beta/api/organizationsettings-list-contactinsights.md(3,14)', 'beta/api/organizationsettings-list-iteminsights.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251021055461-17981/BuildReport?accessString=3d9db8b2c557b750854383fa5328d9d42e96b9fdf088127a12b18024d12320f0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 11:55 UTC, opbld34 commented
Docs Build status updates of commit _[6354f1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6354f1cf239c4c138d89f6f699b5f38412f9d12e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-953e59c3)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-953e59c3"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251151381905-17981/BuildReport?accessString=4a48ffc6953f98d3b6b6f7679c0379fec9e1c1374cc5a7318d6595dcac339b22).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 12:14 UTC, opbld33 commented
Docs Build status updates of commit _[5a72ba3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a72ba356ce9fcb27ace9bd72100d8d21d0582a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-b54c7ef7)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-b54c7ef7"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251159141018-17981/BuildReport?accessString=286e66b7a268f82b13b3c8bc039cf8583b9f23988206b3c0b7209278586b346a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 15:00 UTC, opbld34 commented
Docs Build status updates of commit _[d5a55ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5a55ffb1e2a1e8571617e8c1fd50d1ab02eb60c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-c830f869)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-c830f869"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251457263405-17981/BuildReport?accessString=ee4eb8dbc345a4ac9fb03f457d58e56cdb7a043bd41c50683272f2d413107514).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 15:13 UTC, opbld33 commented
Docs Build status updates of commit _[11bfb1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11bfb1c29c3d2598a36b360ffbd49db48f5c9fe0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-4d597865)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-4d597865"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251509187839-17981/BuildReport?accessString=2fa4bf1ee4be0386927e15ec4be9db215b71a2fbb2d04c2e0030b2409d7efb59).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 18:19 UTC, opbld30 commented
Docs Build status updates of commit _[9bf0f77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bf0f77360f726ac2798657d0f88726201d8633e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-e9b04480)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-e9b04480"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251815505858-17981/BuildReport?accessString=ab2cae85499e8d75cdffc4b38faabea2b307c3071ac172ea458d66901db74a27).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 03:06 UTC, Danielabom commented on api-reference/beta/api/insightssettings-update.md
> +The following is an example of a request that shows how an admin updates "**disabledForGroup**" privacy setting in order to prohibit displaying contact insights of users in a particular Azure AD grou
```suggestion
The following is an example of a request that shows how an admin updates "**disabledForGroup**" privacy setting to prohibit displaying users' contact insights in a particular Azure AD group.

2022-08-26 03:21 UTC, Danielabom commented on changelog/Microsoft.People.json
> +			"SubArea": "People"
Hi @rohitgoyal7, I believe that we are missing the list operation. Thanks

2022-08-26 03:23 UTC, Danielabom requested changes
Hi @rohitgoyal7, most changes are in place. I just added a comment to the changelog, and @angelgolfer-ms, our principal writer, will help us review the TOC

2022-08-26 04:58 UTC, opbld33 commented
Docs Build status updates of commit _[f0bf976](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0bf976e8c9b8087edbcb2ff3dc83a63cdb7392f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-07dd2c04)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-07dd2c04"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 224, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208260457032839-17981/BuildReport?accessString=4eaa3fdfa6813c9605694de1d64dcd798cff6823c50526e0e0f01ed4d0b8ece2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 17:16 UTC, Danielabom commented on changelog/Microsoft.People.json
> +			"ChangeList": [
Dear @angelgolfer-ms, my content review is complete, in case you are ready to go through the TOC.

2022-09-07 05:01 UTC, opbld34 commented
Docs Build status updates of commit _[1a87287](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a87287bdf2cf225ecdf9552aa2376d43323d062)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d768230b)

<a id="d768230b"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 1a87287bdf2cf225ecdf9552aa2376d43323d062 in branch user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 3f1d533511c9de70511a80d49e47c6b2869b019e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070500407632-17981/BuildReport?accessString=83c3393b8ce0182e5d16961ba168cce6adc610f58c82c35359a2a38d74c7a7eb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 05:12 UTC, opbld34 commented
Docs Build status updates of commit _[f739dbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f739dbd93f1970308c7b273847f3b165cc024c16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-73a4d6063741a352a709ce059195e324-aac705f0)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-aac705f0)
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="73a4d6063741a352a709ce059195e324-aac705f0"></a>
### [api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md)
 - **Line 242, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="0817dce4456c16725d5333633847d38f-aac705f0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9999, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070510223783-17981/BuildReport?accessString=99b2374afefa5aa28724f8f0c09fd17b3950a6e425a4f1204dcfdca0b03e6a98).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 07:18 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Org control for contact insights (preview)
Lines 427-434:
FYI I am moving these lines to go under the node "Users" >> "Personal contacts", after the "Contact merge suggestions (preview)" node under "Personal contacts".

2022-09-07 07:19 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: api/contactmergesuggestions-update.md
Lines 406-426:
Since "Users" >> "Contacts" now is "Users" >> "Personal contacts" on the live site, FYI I'm going to remove these lines.

2022-09-07 07:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/organizationsettings.md
> +| [List contactInsights](../api/organizationsettings-list-contactinsights.md) | [insightsSettings](insightssettings.md) | Get the properties of an [insightsSettings](insightssettings.md) object for d
Lines 32-40 in the "Relationships" section:
Your API requires adding a nav property contactInsights to organizationSettings.
To reduce the back and forth for this PR, FYI I am adding that new nav property to that section, with the following description:
"Contains the properties that are configured by an administrator as a tenant-level privacy control whether to identify duplicate contacts among a user's contact list and suggest the user to merge those contacts to have a cleaner contact list."

@rohitgoyal7 , once I merge my updates later tonight, can you take a look at that description and make any necessary updates to it?

2022-09-07 08:00 UTC, angelgolfer-ms commented on api-reference/beta/api/insightssettings-update.md
> +<!-- {
FYI I am removing line 242 on your behalf just so we can wrap this PR up without incurring another iteration of review.

2022-09-07 08:22 UTC, opbld34 commented
Docs Build status updates of commit _[b38cf81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b38cf816b00e61b763c8b1be8f2e27bba4488127)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b0a8eb2c)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-b0a8eb2c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9978, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070820086823-17981/BuildReport?accessString=a0f7c95913b5ffc5dc9108c83516d70199f86c3b85574f011c222ec5d79ac5cb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 08:52 UTC, opbld31 commented
Docs Build status updates of commit _[11464f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11464f299db82ea1d55454bd185489755ae1c4f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4254009c)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-4254009c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9978, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209070848069526-17981/BuildReport?accessString=62c273dff93f54f19c9c8bae468a8be5affa2b4ff5965196e51579e1e32fc23e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 20:40 UTC, opbld34 commented
Docs Build status updates of commit _[e81a3f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e81a3f9867456340f1707a0e0da70f7b333e1efe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5ea53b83)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-5ea53b83"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9980, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209072033309536-17981/BuildReport?accessString=05045bd4fad5116a33b30a13f3ed8990309a3aa567941e9ac8adba558305ef4a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 21:19 UTC, opbld30 commented
Docs Build status updates of commit _[819734e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/819734e5a9834faf699e2e264df9aa83a0a67ce8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9e1d8c81)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-9e1d8c81"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9980, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209072117359773-17981/BuildReport?accessString=bd58318ce311426131455fa97099034e639fb2345df0c3e65963ee052950c37a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 21:25 UTC, angelgolfer-ms commented on changelog/Microsoft.People.json
> +					"Description": "Added a [list](https://docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&tabs=http) operation to the [insightsSettings](https://do
Lines 120 and 121:
@rogoy , @Danielabom , FYI the Description and Target property values are not correct:
Description: "Added the list operation to the organizationSettings resource."
Target: organziationSettings.


We added another list operation to the insightsSettings resource. What we get back from the list operation is of the insightsSettings type.
Just like when we say, the list operation of message, that operation returns a collection of message resources.
If we say the list operation of organizationSettings, that operation would return the type (or a collection of the type)  organizationSettings. And that's not what we're doing; that list operation doesn't return organizationSettings.

I fixed both lines.

2022-09-07 21:27 UTC, angelgolfer-ms approved these changes
Per my communication with @rogoy , I made some updates to the content in various files, including the changelog and TOC.
This PR looks good to me.

2022-09-08 08:58 UTC, opbld31 commented
Docs Build status updates of commit _[618a6ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/618a6ffa6162fe2ea18f0a9cbe7a79dcc4e4c012)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-23d298a2)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-23d298a2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9980, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080854251845-17981/BuildReport?accessString=e796c4ab3f48e8feb2b5038c83cd9dfbc3d72e7873e311968dbd29cad3dadf84).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 09:01 UTC, opbld33 commented
Docs Build status updates of commit _[02ed4b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02ed4b534dc0a0c86136361d5a6607916ebe0e8d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7b877153)
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-7b877153"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml)
 - **Line 9980, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080856037288-17981/BuildReport?accessString=ff70471a5dac35c492840e39be6c40b9002beea665be6a02787aaada21df8da3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-03 18:47 UTC, opbld30 commented
Learn Build status updates of commit _[894eeed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/894eeed6a88696bccc8b6301cc3539cf106211e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210031844006347-17981/BuildReport?accessString=778fe885bb40505dfc4b7e6c3734abd6459ff4a9121cec828956482e7ee8c290).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-03 18:52 UTC, angelgolfer-ms commented
Per @rogoy 's request on Teams, the PR is ready for merging. Communicated the usual protocol for author to set the ready to merge label. To save us overhead as we're in Ignite crunch, I reviewed the last updates and set that label this time.

2022-10-04 02:22 UTC, opbld30 commented
Learn Build status updates of commit _[0d0302e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d0302ecf93f9bce972ef95f10e9c9fef3677a1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/insightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/insightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/api/organizationsettings-list-contactinsights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/api/organizationsettings-list-contactinsights.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/organizationsettings-list-contactinsights?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/insightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/insightssettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/insightssettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/resources/organizationsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/resources/organizationsettings.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/organizationsettings?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/insightssettings-update?view=graph-rest-beta&branch=pr-en-us-17981) (graph-rest-beta) |
[changelog/Microsoft.People.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/user/rogoy/adding-gragh-API-doc-for-tenant-contact-settings/changelog/Microsoft.People.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040220205712-17981/BuildReport?accessString=fd46381f0c8f53e482659847dc2f28fdf2351ff124cb37f59663ec30f3933786).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 02:29 UTC, merged