Introduction of Id in Learning Content for Viva Learning Workload
microsoftgraph/microsoft-graph-docs pull request #17997
Opened 2022-08-10 06:45 UTC by SritejaKampara

2022-08-10 06:47 UTC, opbld34 commented
Docs Build status updates of commit _[e80534a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e80534ad6437dae9cc04b9b6268443d895c9fd10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208100645186297-17997/BuildReport?accessString=41366318969316f388ce69858f58b7853416ed6f8c9ac9ae2fc83c97a193e7ec).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 09:28 UTC, opbld34 commented
Docs Build status updates of commit _[3593e45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3593e458a4ecbaf6853ab3aab435291de8523ae0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-97e98a4e)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-97e98a4e)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-97e98a4e)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-97e98a4e)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-97e98a4e)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-97e98a4e"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-97e98a4e"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-97e98a4e"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-97e98a4e"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-97e98a4e"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190927012590-17997/BuildReport?accessString=00f6534649f8f9aaa78185f7ed6c2db707962b343785c3176c2b03f2cdd01d1e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 09:31 UTC, opbld31 commented
Docs Build status updates of commit _[03a3275](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03a32756f59f668b264b1179677f929f2a11535d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-f94d7503)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-f94d7503)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-f94d7503)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-f94d7503)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-f94d7503)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-f94d7503"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-f94d7503"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-f94d7503"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-f94d7503"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-f94d7503"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190929173102-17997/BuildReport?accessString=d73684d0ccda22e537819470ac5c8b99e47fdb0382249bb3805cde11dde1d3b5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 09:35 UTC, opbld30 commented
Docs Build status updates of commit _[47e2a43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47e2a436b66bd06f3b3069c682d3b24820921792)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-f023ee76)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-f023ee76)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-f023ee76)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-f023ee76)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-f023ee76)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-f023ee76"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-f023ee76"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-f023ee76"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-f023ee76"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-f023ee76"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190930055226-17997/BuildReport?accessString=64ae1ea3c2535e93068c60a36544e45ea95751be1a5c206a19ae952e6b0712a3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 15:12 UTC, isvargasmsft commented on api-reference/beta/api/learningcontent-get.md
> +
General:
In PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/17789 we are modifying the HTTP request format. Could you please explain this additional HTTP format? Are these changes articulated?

2022-09-01 16:55 UTC, isvargasmsft commented on api-reference/beta/api/learningcontent-update.md
> +    "id": "77029588-a660-46b6-ba58-3ce4d21d5678",
Was there a schema change regarding the id properties of the learningContent resource? If so, would you be so kind to share the CSDL PR on the side, please?

2022-09-01 17:10 UTC, isvargasmsft requested changes
Hello @SritejaKampara, 

Thank you very much for your work in this PR. 

Just a few questions and suggestions:
1. Please clarify if this additional HTTP request format is articulated in any way with the change introduced in PR 17789. Does this operation has 2 possible HTTP request formats?
2. Please clarify if there was an schema change regarding the ID properties of the learningContent resource. If so, please share the CSDL PR with me on the side (Teams). 
3. Related to the changelog entries: please follow the guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-properties

Feel free to ping me on the side if you have any questions. 

Here to help!

Isaac Vargas

2022-09-02 11:27 UTC, isvargasmsft commented on changelog/Microsoft.Viva.Learning.json
> +        },
I am yet to see the CSDL PR with these schema changes (please share them on the side) but, from what I can deduce, these 2 entries are not using the best format. 

Were these changelog entries generated or manually created? 

Guidance to changelog entries here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-properties

2022-09-07 12:10 UTC, SritejaKampara commented on api-reference/beta/api/learningcontent-update.md
> +    "id": "77029588-a660-46b6-ba58-3ce4d21d5678",
https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/6558309

2022-09-13 07:54 UTC, opbld31 commented
Docs Build status updates of commit _[4aba692](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4aba692e8d770f7012cab8ff7b5bab6dcd4a0b11)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d2a663ad)

<a id="d2a663ad"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 4aba692e8d770f7012cab8ff7b5bab6dcd4a0b11 in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit aacb431a9150dd5dcbeb9430f0095af7df357ac9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209130754096324-17997/BuildReport?accessString=ae3e354db3b78935455e00fd5025c8af5cb356734cf7d882138975b35db205b9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 07:56 UTC, opbld33 commented
Docs Build status updates of commit _[4a6132e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a6132e3e9c72a6cd050c5589ca3d1b51d800572)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b91debfc)

<a id="b91debfc"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 4a6132e3e9c72a6cd050c5589ca3d1b51d800572 in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit aacb431a9150dd5dcbeb9430f0095af7df357ac9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209130755447623-17997/BuildReport?accessString=7644187d2a112ea0601ab4e9c8566de452822228ef1ca368e729bf2f0e6a13d3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 07:58 UTC, opbld31 commented
Docs Build status updates of commit _[8d86a1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d86a1a3e6c7a4e0c20ad139c3763c700d226f5a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e7394830)

<a id="e7394830"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 8d86a1a3e6c7a4e0c20ad139c3763c700d226f5a in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit aacb431a9150dd5dcbeb9430f0095af7df357ac9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209130757322500-17997/BuildReport?accessString=143c75a92cefee6c7926823d3e0c9fa9028bbad287ba714debf8e3c16aa8d9a2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 00:38 UTC, angelgolfer-ms commented on changelog/Microsoft.Viva.Learning.json
> +        },
@SritejaKampara , I was browsing your PR and saw this reply from you. FYI I will copy your response in an email to let @isvargasmsft know, and then remove the URL you provided that points to an internal location for the CSDL.

2022-09-15 04:33 UTC, opbld33 commented
Docs Build status updates of commit _[8c14d37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c14d3797c75313ae3f426f60e9c26e69fb37e1d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-eea67f7c)

<a id="eea67f7c"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 8c14d3797c75313ae3f426f60e9c26e69fb37e1d in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit aacb431a9150dd5dcbeb9430f0095af7df357ac9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150432366421-17997/BuildReport?accessString=a769a535bd1340e7a47e56623fbfb6e01b8c75b93c938b0c7b407dcffb8177ac).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 04:35 UTC, SritejaKampara commented on api-reference/beta/api/learningcontent-get.md
> +
That PR is no more needed. The change is required as externalId is now an alternate key and id would be the primary Key, so externalId='externalId' would be the way of calling it correctly.

2022-09-15 20:12 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [18513](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18513) into this branch to include my final edits.

To avoid confusion, I removed from this PR (17997) changes that will be introduced with PR #18134.

2022-09-15 22:31 UTC, opbld34 commented
Docs Build status updates of commit _[de768ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de768cefa38794289cbe150e982cb4aa7aabc663)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-65cbef5b)

<a id="65cbef5b"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit de768cefa38794289cbe150e982cb4aa7aabc663 in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit aacb431a9150dd5dcbeb9430f0095af7df357ac9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152230495063-17997/BuildReport?accessString=5df521c47e5629ea50caae6f3f4b98031982e7632ffda42799095b4449f9be47).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 22:37 UTC, opbld33 commented
Docs Build status updates of commit _[26998a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26998a4c3a2483426b17e69fb8fd4fd962c18b8e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-91cd20d7)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-91cd20d7)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-91cd20d7)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-91cd20d7)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-91cd20d7)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-91cd20d7"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-91cd20d7"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-91cd20d7"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-91cd20d7"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-91cd20d7"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152235160706-17997/BuildReport?accessString=ce4b702101019ce79c90acd9cd51f5696a468b75718c26de4e7acde61ca50833).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 22:39 UTC, opbld34 commented
Docs Build status updates of commit _[3388a8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3388a8e606fe9d7042970f58d07fca5a70eb805a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-86f1927e)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-86f1927e)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-86f1927e)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-86f1927e)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-86f1927e)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-86f1927e"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-86f1927e"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-86f1927e"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-86f1927e"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-86f1927e"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209152237486653-17997/BuildReport?accessString=f1fd90812024ad6ac1c5473468d052e4b40dbf746c0e1ebd1137942f8fef223e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 00:21 UTC, opbld30 commented
Docs Build status updates of commit _[91739ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91739ef3b895764afa1959e2e9fd8a2281d71a0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-cec2b7da)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-cec2b7da)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-cec2b7da)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-cec2b7da)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-cec2b7da)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-cec2b7da"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-cec2b7da"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-cec2b7da"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-cec2b7da"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-cec2b7da"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160017357529-17997/BuildReport?accessString=e4817c788db150dcf5cf7058d1638e944a90d8b589f31d3cbadfb67d4e5c268c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 00:33 UTC, opbld31 commented
Docs Build status updates of commit _[62005ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62005cec81e2ff96cf27280ffd5416940495ed1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-39840aa5)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-39840aa5)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-39840aa5)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-39840aa5)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-39840aa5)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-39840aa5"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-39840aa5"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-39840aa5"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-39840aa5"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-39840aa5"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160029432370-17997/BuildReport?accessString=73b5fb82fbbf1a18247bcb7c770b02158f5834ae4ed6f386250af4210683be85).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 01:18 UTC, Lauragra approved these changes

2022-09-16 01:28 UTC, opbld34 commented
Docs Build status updates of commit _[6d7e493](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d7e49361ff275d7903f54cc9d687066703d9557)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-c1e9e06f)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-c1e9e06f)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-c1e9e06f)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-c1e9e06f)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-c1e9e06f)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-c1e9e06f"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-c1e9e06f"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-c1e9e06f"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-c1e9e06f"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-c1e9e06f"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160126402557-17997/BuildReport?accessString=ce1584aac55ec9a77e80a08d8ec3778ed1164526cd6cbc30f9348feb1020ff32).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 04:22 UTC, opbld31 commented
Docs Build status updates of commit _[7a6fe49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a6fe4920bedf1445570e98ebc3eb8dc7eaa1e5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-e5737f99)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-e5737f99)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-e5737f99)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-e5737f99)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-e5737f99)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-e5737f99"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-e5737f99"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-e5737f99"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-e5737f99"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-e5737f99"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160420269566-17997/BuildReport?accessString=ab8226724b81806442f200d256dddc58050102110a2f9d559215a38d126223be).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-04 21:14 UTC, opbld32 commented
Learn Build status updates of commit _[7c8408c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c8408c366b38470e41b9f96666acb538ea0688e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7081dde6)

<a id="7081dde6"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 7c8408c366b38470e41b9f96666acb538ea0688e in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 15c1feedb539d6225fa830791be34c70b73d675e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210042113383513-17997/BuildReport?accessString=52f0fcd279e97e80555712271fbffe44ecf9c13e8436a4206ebdcb8412719199).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 20:24 UTC, opbld30 commented
Learn Build status updates of commit _[6db919b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6db919b6f2fa39e48ca0fe314e3af403ae72872b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-577039e7)

<a id="577039e7"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 6db919b6f2fa39e48ca0fe314e3af403ae72872b in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 15c1feedb539d6225fa830791be34c70b73d675e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210062024208245-17997/BuildReport?accessString=b376b8e3bd52d7615675c1b7ca0cf963baac9ddd40792ba86a5574f41a3bdd64).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 20:28 UTC, opbld30 commented
Learn Build status updates of commit _[0fc0299](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fc0299f26f67442618cda08165d07af7352f02f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6752d886)

<a id="6752d886"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 0fc0299f26f67442618cda08165d07af7352f02f in branch users/kasritej/VLContentLOIDChange of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 15c1feedb539d6225fa830791be34c70b73d675e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210062027339237-17997/BuildReport?accessString=f3b1f0a6b58bb0b70e904db2807388ad7980bdaab19ea02f7bbb3764bc7ac529).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 20:45 UTC, opbld30 commented
Learn Build status updates of commit _[513ef66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/513ef661e808bfaf09b4a21c1740f13215da5793)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-1d37da24)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-1d37da24)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-1d37da24)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-1d37da24)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-1d37da24)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-1d37da24"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-1d37da24"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-1d37da24"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-1d37da24"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-1d37da24"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210062043100008-17997/BuildReport?accessString=73cb7ac6d224ab5dd4f90aaa1a5425cad57efbfaba4dec273cf0024da2945dca).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 20:47 UTC, opbld30 commented
Learn Build status updates of commit _[fda5b1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fda5b1b4917fa074a907d83c512e332673b21f99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-ba56c153)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-ba56c153)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-ba56c153)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-ba56c153)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-ba56c153)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-ba56c153"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-ba56c153"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-ba56c153"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-ba56c153"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-ba56c153"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210062043520153-17997/BuildReport?accessString=df9465012b5bef5d21b44e19415c69976d13c49fadc18a86f1b04649d19c2970).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:20 UTC, opbld31 commented
Learn Build status updates of commit _[12aed3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12aed3e2e26aad6dec8d7152bdea1962b2256f10)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningcontent-get?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-918e8ad4b2b68411fec8a7195724b710-ff4d4923)
[api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningcontent-update?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-47843f227808dd4f4bff5f95d6a3ad0f-ff4d4923)
[api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningprovider-delete-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-193ea3668bd1324c75c2c5eaaf3feea0-ff4d4923)
[api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/learningprovider-list-learningcontents?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-bf309f51afa604ca93197c6e5e8428fe-ff4d4923)
[api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/learningcontent?view=graph-rest-beta&branch=pr-en-us-17997) (graph-rest-beta) | [Details](#user-content-6078e9b4de4a5fd60d0839f2d1de0761-ff4d4923)
[changelog/Microsoft.Viva.Learning.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/changelog/Microsoft.Viva.Learning.json) | :white_check_mark:Succeeded | |

<a id="918e8ad4b2b68411fec8a7195724b710-ff4d4923"></a>
### [api-reference/beta/api/learningcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-get.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="47843f227808dd4f4bff5f95d6a3ad0f-ff4d4923"></a>
### [api-reference/beta/api/learningcontent-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningcontent-update.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="193ea3668bd1324c75c2c5eaaf3feea0-ff4d4923"></a>
### [api-reference/beta/api/learningprovider-delete-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-delete-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="bf309f51afa604ca93197c6e5e8428fe-ff4d4923"></a>
### [api-reference/beta/api/learningprovider-list-learningcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/api/learningprovider-list-learningcontents.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

<a id="6078e9b4de4a5fd60d0839f2d1de0761-ff4d4923"></a>
### [api-reference/beta/resources/learningcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/kasritej/VLContentLOIDChange/api-reference/beta/resources/learningcontent.md)
 - **Line 6, Column 10**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'employee-learning'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210070317599648-17997/BuildReport?accessString=39fff0483efc9c5ece7b1c2c28fd1366671d520d5f9c0031ccae5ba0c2a02c2a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:24 UTC, merged