App-scoped chat subscriptions
microsoftgraph/microsoft-graph-docs pull request #17990
Opened 2022-08-09 19:55 UTC by eddie-lee-msft

Documentation for introducing app-scoped chat subscription resources + the new permissions required to access them.

2022-08-09 19:56 UTC, opbld34 commented
Docs Build status updates of commit _[dc5c07e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc5c07e1d4877a764371685f081b0368e58e4f90)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7f1af192)

<a id="7f1af192"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208091956020023-17990/BuildReport?accessString=1727c9f5c38641071e79fb9c40b51b67b76f10f8efb28f27d710046af2882eb2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 20:04 UTC, opbld32 commented
Docs Build status updates of commit _[12acdda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12acdda7bebd9e3144143e78b3ff23b5e23bedb8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-07c625db)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |

<a id="eea99bea355d0a4253064eefdbbe7005-07c625db"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md)
 - **Line 28, Column 508**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 508**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092002247146-17990/BuildReport?accessString=6218b8eee5e3c26b1c1b1a883b56ad8a2e0eacd0daa5f0cd753b84f4d62961e9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 20:30 UTC, opbld33 commented
Docs Build status updates of commit _[f599d3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f599d3efcde9f4f9087e35c7096737a80733031b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092027588542-17990/BuildReport?accessString=e6a60180c0f5dd386a2ac9428c4b8126feba30d7c2ed3a8aec481a96700415f9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 20:34 UTC, opbld31 commented
Docs Build status updates of commit _[8317623](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83176230884c3bf532eb5faaddea7c9f8989aac5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092031440134-17990/BuildReport?accessString=ea80efc92c8ff0b3c9767e2bcf633b8dbefe9f1507d504af4754426e8d4e83ab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-09 20:39 UTC, opbld34 commented
Docs Build status updates of commit _[dfc8cac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfc8cac50893b875d4d3f1e448e64b7668a12693)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208092035056967-17990/BuildReport?accessString=f9a31a34df179dfcb930eb3ffb38943740509c87cd477a50974a7e78ded39616).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-10 19:43 UTC, jessiechan27 commented on api-reference/beta/resources/webhooks.md
> +| Teams [chat][] | Changes to any chat in the tenant:<br>`/chats` <br>Changes to a specific chat:<br>`/chats/{id}`<br>Changes to any chat in the tenant a particular Teams app is installed to:<br>`/ap
typo: installedToChats

2022-08-10 19:51 UTC, jessiechan27 commented on changelog/Microsoft.Teams.Core.json
>      }
You'll need to manually add changelog entries for the new permissions as well

2022-08-10 23:40 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
>      }
Oops, good call. I'll add them.

2022-08-11 19:56 UTC, opbld33 commented
Docs Build status updates of commit _[22a497e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22a497e1812f98a05189f831b80b684ff6036422)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208111954158085-17990/BuildReport?accessString=b1d4cbe86a7564719f8aff9f883501cc85e0e489a8d002e34c3f4dd5eff768b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[8111765](https://github.com/microsoftgraph/microsoft-graph-docs/commits/811176547affe8dccbba516521b5473e00c4f3e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208161821584154-17990/BuildReport?accessString=2fd1b51d8d054aeccbfc9aaa2ee3abf098fb1595bc6a36d812a858a9321e7f0a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 23:20 UTC, opbld30 commented
Docs Build status updates of commit _[9f2466b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f2466bc4aa043c24c72139a765fa5e891399b01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208242317576237-17990/BuildReport?accessString=ac3ba093dcf5b32c98fe8e998b1cbf79b3377bb799941d8d968ee67446da3473).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 15:06 UTC, Danielabom commented on concepts/permissions-reference.md
> +* **WhereInstalled** grants permission for the app to perform the operations on all of the resources where the associated Teams application has been installed. For example *Chat.Read.WhereInstalled*
A minor sugesstion in case you want to make shorter sentences:
```suggestion
* **WhereInstalled**grants permission for the app to perform the operations on all the resources where the associated Teams application is installed. For example, *Chat.Read.WhereInstalled* grants the app privileges to read all chat messages for all chats where the associated Teams application is installed. There is usually a one-to-one mapping between an app (Azure AD application) and a Teams application. The *webApplicationInfo* ection of the [Teams app manifest](/microsoftteams/platform/resources/schema/manifest-schema) of a Teams app specifies the Azure AD application Id.

2022-08-25 15:50 UTC, Danielabom commented on concepts/permissions-reference.md
> +|_Chat.ReadWrite.All_ |Read and write all chat messages |Allows an app to read and write all one-to-one and group chats in Microsoft Teams, without a signed-in user. Does not allow sending messages.
```suggestion
|_Chat.ReadWrite.All_ |Read and write all chat messages. |Allows an app to read and write all one-to-one and group chats in Microsoft Teams, without a signed-in user. Does not allow sending messages. | Yes | No |
```

2022-08-25 15:51 UTC, Danielabom commented on concepts/permissions-reference.md
> +#### Delegated permissions
Global comment: Please make sure to add punctuation add the end of every sentence. Thanks.

2022-08-25 15:51 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _ChatMember.Read_      | Read the members of chats         | Read the members of chats, on behalf of the signed-in user.  | Yes                    | No                          |
Global comment: Please make sure to add punctuation add the end of every sentence. Thanks.
```suggestion
| _ChatMember.Read_      | Read the members of chats.         | Read the members of chats, on behalf of the signed-in user.  | Yes                    | No                          |
```

2022-08-25 15:52 UTC, Danielabom commented on concepts/permissions-reference.md
> +#### Application permissions
Global comment: Please make sure to add punctuation add the end of every sentence. Thanks.

2022-08-25 15:52 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _ChatMember.ReadWrite.All_            | Add and remove members of all chats                          | Read names and members of all chat threads.                  | Yes                    | No
```suggestion
| _ChatMember.ReadWrite.All_            | Add and remove members of all chats.                          | Read names and members of all chat threads.                  | Yes                    | No                          |
```

2022-08-25 15:57 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _ChatMember.Read_      | Read the members of chats         | Read the members of chats, on behalf of the signed-in user.  | Yes                    | No                          |
```suggestion
| _ChatMember.Read_      | Read the members of chats         | Read the members of chats on behalf of the signed-in user.  | Yes                    | No                          |
```

2022-08-25 15:57 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _ChatMember.ReadWrite_ | Add and remove members from chats | Add and remove members from chats, on behalf of the signed-in user. | Yes                    | No                          |
```suggestion
| _ChatMember.ReadWrite_ | Add and remove members from chats | Add and remove members from chats on behalf of the signed-in user. | Yes                    | No                          |
```

2022-08-25 15:58 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _ChatMember.Read.WhereInstalled_      | Read the members of all chats where the associated Teams application is installed. | Allows the app to read the members of all chats where the associated Tea
```suggestion
| _ChatMember.Read.WhereInstalled_      | Read the members of all chats where the associated Teams application is installed. | Allows the app to read the members of all chats where the associated Teams application is installed, without a signed-in user. | Yes                    | No                          |
```

2022-08-25 15:58 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _ChatMember.Read.All_                 | Read the members of all chats                                | Allows the app to read all 1:1 or group chat messages in Microsoft Teams, without a signed-in
```suggestion
| _ChatMember.Read.All_                 | Read the members of all chats.                                | Allows the app to read all 1:1 or group chat messages in Microsoft Teams without a signed-in user. | Yes                    | No                          |
```

2022-08-25 16:00 UTC, Danielabom commented on concepts/permissions-reference.md
>  #### Application permissions
Global comment: Please make sure to add punctuation at the end of every sentence. Thanks.

2022-08-25 16:02 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _SearchConfiguration.Read.All_ | Read your organization's search configuration | Allows the app to read search configurations, without a signed-in user. | Yes |
```suggestion
| _SearchConfiguration.Read.All_ | Read your organization's search configuration. | Allows the app to read search configurations without a signed-in user. | Yes |
```

2022-08-25 16:02 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _SearchConfiguration.ReadWrite.All_ | Read and write your organization's search configuration | Allows the app to read and write search configurations, without a signed-in user. | Yes |
```suggestion
| _SearchConfiguration.ReadWrite.All_ | Read and write your organization's search configuration. | Allows the app to read and write search configurations without a signed-in user. | Yes |
```

2022-08-25 16:12 UTC, Danielabom commented on concepts/teams-changenotifications-chat.md
> +To get change notifications for all changes related to any chat in a tenant where a specific Teams app is installed, subscribe to `/appCatalogs/teamsApps/{teams-app-id}/installedToChats`. This resour
```suggestion
To get change notifications for all changes related to any chat in a tenant where a specific Teams app is installed, subscribe to `/appCatalogs/teamsApps/{teams-app-id}/installedToChats.` This resource supports [including resource data](webhooks-with-resource-data.md) in the notification.
```

2022-08-25 17:35 UTC, eddie-lee-msft commented on concepts/permissions-reference.md
> +| _SearchConfiguration.Read.All_ | Read your organization's search configuration | Allows the app to read search configurations, without a signed-in user. | Yes |
Not really in the scope of this PR, but I will make the fix.

2022-08-25 17:35 UTC, eddie-lee-msft commented on concepts/permissions-reference.md
> +| _SearchConfiguration.ReadWrite.All_ | Read and write your organization's search configuration | Allows the app to read and write search configurations, without a signed-in user. | Yes |
Out of scope, but I will make the fix.

2022-08-25 17:37 UTC, eddie-lee-msft commented on concepts/teams-changenotifications-chat.md
> +To get change notifications for all changes related to any chat in a tenant where a specific Teams app is installed, subscribe to `/appCatalogs/teamsApps/{teams-app-id}/installedToChats`. This resour
I actually think keep the ` after the . would make more sense here. The pair of `` highlights the resource string. A period shouldn't be part of the resource string.

2022-08-25 17:41 UTC, opbld32 commented
Docs Build status updates of commit _[d7ca634](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7ca6346d67d808461ad71c2f4881627d0e26164)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208251739047406-17990/BuildReport?accessString=90c75e522cdc8640f56c0c3ff2a6bbec1699062d39c4bd2130deb28406c5d245).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 17:48 UTC, Danielabom commented on api-reference/beta/api/subscription-delete.md
> +|[chat](../resources/chat.md) (/appCatalogs/teamsApps/{id}/installedToChats) | Not supported | Not supported | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled |
Global comment: please make sure to add punctuation at the end of phrases and sentences. 
```suggestion
|[chat](../resources/chat.md) (/appCatalogs/teamsApps/{id}/installedToChats) | Not supported. | Not supported. | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled |
```

2022-08-25 17:51 UTC, Danielabom commented on api-reference/beta/api/subscription-delete.md
> +|[conversationMember](../resources/conversationmember.md) (/appCatalogs/teamsApps/{id}/installedToChats/getAllMembers) | Not supported | Not supported | ChatMember.Read.WhereInstalled, ChatMember.Rea
Global comment: please make sure to add punctuation at the end of phrases and sentences.

2022-08-25 17:53 UTC, Danielabom commented on api-reference/beta/api/subscription-get.md
> +|[chat](../resources/chat.md) (/appCatalogs/teamsApps/{id}/installedToChats) | Not supported | Not supported | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled |
Global comment: please make sure to add punctuation at the end of phrases and sentences.

2022-08-25 17:54 UTC, Danielabom commented on api-reference/beta/api/subscription-list.md
> +|[chat](../resources/chat.md) (/appCatalogs/teamsApps/{id}/installedToChats) | Not supported | Not supported | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled |
Global comment: please make sure to add punctuation at the end of phrases and sentences.

2022-08-25 17:54 UTC, Danielabom commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[chat](../resources/chat.md) (/appCatalogs/teamsApps/{id}/installedToChats) | Not supported | Not supported | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled |
Global comment: please make sure to add punctuation at the end of phrases and sentences.

2022-08-25 17:55 UTC, Danielabom commented on api-reference/beta/api/subscription-update.md
> +|[chat](../resources/chat.md) (/appCatalogs/teamsApps/{id}/installedToChats) | Not supported | Not supported | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled |
Global comment: please make sure to add punctuation at the end of phrases and sentences.

2022-08-25 21:20 UTC, angelgolfer-ms commented on concepts/teams-change-notification-in-microsoft-teams-overview.md
The additional sentences in lines 34 and 35:
Hi @eddie-lee-msft , @Danielabom asked me a question about this PR and that's why I'm looking at it :-)
Please correct me if I'm missing something, 'cos I'm just looking at this PR and am not aware of any internal roadmap item noted for this PR where I'll normally look into for the api.md and CSDL files. So bear with me - this PR is about adding support for a Teams app installed for a specific tenant, to subscribe to change notifications indicated by the 3 new sentences in lines 33, 34, and 35, right?
That's changes to (a) any chat in that tenant, (b) any chat messages in any chat in the tenant, and (c) any conversation member in any chat in the tenant.

Assuming I got it correct, then for lines 34 and 35, please rephrase to specify the tenant before the "where", as shown bolded below:
"Changes to chat messages in **all the chats in the tenant** where a particular Teams app is installed..."
"Changes to membership in **all the chats in the tenant** where a particular Teams app is installed..."

2022-08-25 21:27 UTC, eddie-lee-msft commented on concepts/teams-change-notification-in-microsoft-teams-overview.md
Yep. Basically these new subscription types will send change notifications about chat messages, chat membership changes, or chat changes for all the chats in the tenant where a specific Teams app is installed.

2022-08-25 21:41 UTC, angelgolfer-ms commented on concepts/teams-change-notification-in-microsoft-teams-overview.md
My other comments are:
Your team should have documented appCatalogs. The Microsoft Graph docs have set up the expectations that, if the developer has a need to, they can find info in the docs about each segment that appears in a query URL, or, in this case, a string that they need to specify as a value for the resource property when creating a subscription.

Just to illustrate with an example why the docs have set the above expectations - that's my experience just now trying to verify if I understood what "chats where a particular Teams app is installed" meant, as it wasn't clear to me how an app can be installed in a chat, according to that phrase.
I started looking for appCatalogs in the beta CSDL, but there's no doc topic for it. Then I looked for teamsApp to try to understand what installedToChats meant. I was expecting that to be a nav property for teamsApp but your PR doesn't include an update for teamsApp. Then I looked in the beta CSDL for the current definitions of getAllMessages, I couldn't be sure which of the 4 definitions I should use, I wasn't sure of the type of the bindingParameter applicable here. 
So those strings in lines 33 to 35 that involve `/appCatalogs/teamsApps/{id}/installedToChats` are kind of opaque to me at this point. That's not the doc experience we want :-)

Request for action:
(a) If installedToChats is new for this release, would you please include the relevant docs for it?

(b) And if you don't mind, can you or somebody you identify on your team create the v1 and beta topics for appCatalogs as well, even though that was an oversight from the past?

2022-08-25 21:47 UTC, eddie-lee-msft commented on concepts/teams-change-notification-in-microsoft-teams-overview.md
For a), I explained to Dani that installedToChats is a hidden property that nobody should be using outside of the context of these new subscription resources. In other words, we are not exposing an API like "GET /appCatalogs/teamsApps/app-id/installedToChats". Only the corresponding subscription resource will be allowed, hence hiding the property for now. Exposing this hidden property was also something approved by the API review board. Given this, is it still appropriate to expose the 'installedToChats' in the 'teamsApp' type in the docs?

b) Sure, I will let someone know.

2022-08-25 21:51 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-chat.md
> +## Subscribe to changes in any chat where a specific Teams app is installed (preview)
Line 148:
Please clarify the section title (like your line 150):
"Subscribe to changes in any chat in a tenant where a Teams app is installed (preview)"

2022-08-25 21:53 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-chatMembership.md
> +## Subscribe to changes in membership of any chat where a specific Teams app is installed (preview)
Line 78:
Similar comment about the section title - please add the tenant into the context to clarify. Like your line 80.

2022-08-25 21:53 UTC, angelgolfer-ms commented on concepts/teams-changenotifications-chatmessage.md
> +
Line 290:
Please clarify the title and add the context of a tenant, like your line 292.

2022-08-25 22:08 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Enabled change notifications support to [create](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&preserve-view=true&tabs=http
Lines 5552 and 5570:
2 comments about the descriptions for these changelist records:
(a) The link at the end of the description should be to the specific section in that topic, like this:
[{link text}](https://docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?view=graph-rest-beta#subscribe-to-messages-in-any-chat-where-a-specific-teams-app-is-installed-preview)

(b) Technically, each description links only to the topic teams-changenotifications-chat.md where you explained subscribing to changes in any chat in the tenant where the app is installed, but doesn't allude to changes in any chat messages in any chat, or changes to any members of any chat, which are in the other 2 concept topics (teams-changenotifications-chatmessage.md and teams-changenotifications-chatmembership.md).

Without adding links in the changelog descriptions to the other 2 concept topics, another way to handle this is, in this [section](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?view=graph-rest-beta&branch=pr-en-us-17990#subscribe-to-messages-in-any-chat-where-a-specific-teams-app-is-installed-preview), make customers aware of the other 2 cases as well and link to those 2 sections in the corresponding concept topics.

And then do the same in the other 2 concept topics as well.

I think that approach in itself is actually helpful, not just because we have to handle the completeness of the changelog. That way, customers viewing one of the 3 concept topics should become aware of related support in the other 2 concept topics.

2022-08-25 22:14 UTC, angelgolfer-ms requested changes
Hi @eddie-lee-msft , your reviewer @Danielabom asked me a question which led me reading this PR. I entered a few comments, please take a look. If I have misunderstood something, please let me know. Ping me on Teams if you don't mind. Otherwise @Danielabom will continue to follow up on this PR from this point on.

2022-08-25 23:25 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Enabled change notifications support to [create](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&preserve-view=true&tabs=http
That's a great idea. I will do that.

2022-08-25 23:47 UTC, opbld32 commented
Docs Build status updates of commit _[0e0e78e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e0e78e7c6915a585a99e19069bca1aba709ef1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208252345319948-17990/BuildReport?accessString=a2064c76d9f3beaa065b462917bde509d6d3001550c0e64528050d96dd2f7018).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 23:50 UTC, opbld34 commented
Docs Build status updates of commit _[5a6584a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a6584ac897bd818f6fc0ea1ce91fc7d31741eee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208252348087680-17990/BuildReport?accessString=2efa29a04c0b357b051d95d1944787ea99e5981dc10fa3fea3e2adcb5366532e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-26 01:01 UTC, angelgolfer-ms commented on concepts/teams-change-notification-in-microsoft-teams-overview.md
Thanks, @eddie-lee-msft . Let's continue to talk about (a) on Teams :-)

2022-08-26 02:56 UTC, Danielabom requested changes
Hi @eddie-lee-msft, please take a look at @angelgolfer-ms's comments. Thanks.

2022-08-26 17:32 UTC, opbld30 commented
Docs Build status updates of commit _[5a6c2b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a6c2b4c1f486b8c8b237a39eb22074e1ef0d43b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208261730057884-17990/BuildReport?accessString=2111254f78c7e6da88f2fc001c68e440c440be9db8020ec70e2273876ec0a1d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 05:40 UTC, opbld30 commented
Docs Build status updates of commit _[8103ae3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8103ae31fba846f57fe662cbed17791d92d0cabc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080537537907-17990/BuildReport?accessString=b3be7404efd9112abdcbc244ab59e13efdbc78ab8b7b158f245f618ec655443f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 06:05 UTC, angelgolfer-ms commented on concepts/teams-change-notification-in-microsoft-teams-overview.md
As we discussed on Teams with @RamjotSingh and @Danielabom , the action we can take at this point to address (a) is on me in a separate PR to clarify preceding the table that lists all the supported resource paths what to do with a resource path and their type. There are at least 4 overview kind of topics that have such tables. In addition, I'll add more links among the concept topics for change notifications for discoverability and SEO.

2022-09-09 06:44 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +        {
Lines 5763-5769:
@eddie-lee-msft , can you please take a look at example 15 in the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog?anchor=changelist-record-examples) CDK topic?

The design for the changelog schema expects only one value for ChangedApiName and one  value for Target in each changelist record. So for adding the support for those 5 permissions, you'll have 5 changelist records, one for each permission. For example:

"ChangeList": [
  {
    "Id": "2c7e3e75-3f61-46d9-b0fc-a4b090c71cef",
    "ApiChange": "Permission",
    "ChangedApiName": "Chat.ReadBasic.WhereInstalled",
    "ChangeType": "Addition",
    "Description": "Added support for the application permission of `Chat.ReadBasic.WhereInstalled` to the [create](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta) operation of [subscription](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta).",
    "Target": "subscription"
  },
  {
    ...
  }
]

2022-09-09 06:54 UTC, angelgolfer-ms requested changes
Hi @eddie-lee-msft , I went over again my comments and your incorporation from a couple of weeks back, thanks for taking action.
I just noticed one other thing about the changelist record that you added for the new permissions. I commented and provided an example to show how to do that. Please take a look.
Other than that, I don't have other comments.

@Danielabom , can you please follow up on this one comment from me, and see if the rest of the PR is good to go  per your earlier review?

As soon as @eddie-lee-msft addresses my latest comment about the changelog JSON for the new perms, @Danielabom  and @eddie-lee-msft can please follow the [content workflow ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211773/Content-workflow) and get this PR on the publishing queue. Thanks!

2022-09-09 07:01 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +      "WorkloadArea": "Teamwork",
All lines where you added "WorkloadArea": "Teamwork":
Please make sure you rename that line as:
"WorkloadArea": "Teamwork and communications",

Last week we merged a PR which renamed the top-level node as "Teamwork and communications, and combined what used to be under "Cloud communications" with what used to be under "Teamwork".

2022-09-09 14:53 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +      "WorkloadArea": "Teamwork",
done

2022-09-09 14:54 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.Core.json
> +        {
done

2022-09-09 14:57 UTC, opbld33 commented
Docs Build status updates of commit _[15217f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15217f8f6ecb06853456c7235dffaac6090bae41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091454502993-17990/BuildReport?accessString=420d1606658d26fd802e4c454efd98b0ad874c0514b4e44878e1ad2abd322996).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 15:02 UTC, opbld34 commented
Docs Build status updates of commit _[88df72a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88df72a44c8f9d5d6626f311fd30a159a632c669)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091459177894-17990/BuildReport?accessString=83941b88c4b4812f6c1152918b575554ab64c87472790428fa88bb7f01dcc70e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 04:11 UTC, angelgolfer-ms commented on changelog/Microsoft.Teams.Core.json
> +        {
(Unresolved just so it's easier for you to read this comment.)
Looks like you forgot all changelist records in the same changelist should have the same GUID for the Id property.

I'll change them on your behalf.

2022-09-10 04:37 UTC, angelgolfer-ms commented on api-reference/beta/api/subscription-list.md
>  |[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read, Chat.ReadWrite, Subscription.Read.All | Not supported | ChatSettings.Read.Chat*, ChatSettings.ReadWrite.Chat*, Chat.Manage.Cha
@eddie-lee-msft , this comment is an FYI, using line 34 as an example, for the similar updates you made to the permissions tables in the CRUD topics for subscription.
I see your good intentions where you added a description to those cases where we cannot fully document the resource paths.
This is what I did further:

- I added a lead-in paragraph to explain why in the context of permissions, we include a resource path for some but not all the resources that support change notifications.

  For unfamiliar customers, they might wonder if the other resources even entail a resource path. 

- I made sure to include a resource path and a description to each resource that appears in more than one table row.

  Some customers may not be aware why we further explain only some but not all resource paths in that table.

- To make the resource paths and descriptions more readable (per Microsoft Voice, we write for scanning), I formatted those cells in the first column to display the resource path and description in each of their own rows within the cell. Without the formatting, there are table cells that look like the below:

<html>
<body>
<!--StartFragment-->

chat (/appCatalogs/teamsApps/{id}/installedToChats) -- all chats in an organization where a particular Teams app is installed | Not supported | Not supported | Chat.ReadBasic.WhereInstalled, Chat.Read.WhereInstalled, Chat.ReadWrite.WhereInstalled
-- | -- | -- | --


<!--EndFragment-->
</body>
</html>

You can take a look at the permissions table in any of these 5 CRUD topics for the subscription resource to get a better idea of what I mean above.  So in the future, in case your team adds more complexity to these tables, you can take the above into consideration.

2022-09-10 04:48 UTC, opbld31 commented
Docs Build status updates of commit _[d9338b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9338b430a2e82194c7b78658a29d6e887493510)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209100446335859-17990/BuildReport?accessString=3d81503b153257beeae9a42f9042527be2d11d3de86357430bf4ac80a3541522).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 04:51 UTC, opbld33 commented
Docs Build status updates of commit _[0608932](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06089325dac5d58e9b98902a0799584a7111c854)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209100447586390-17990/BuildReport?accessString=a52e053b793e3adddad36c323f71c763654021beea094325e858e6ba80db270b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 06:28 UTC, opbld33 commented
Docs Build status updates of commit _[4082d3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4082d3bf7cf5fa3a8d6aec8a4eebcaa24907faae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209100626233503-17990/BuildReport?accessString=2cee4c5444dcdb3dca52301cd348391dddf3b50727f372994489100e127a6d50).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 06:43 UTC, opbld34 commented
Docs Build status updates of commit _[018a778](https://github.com/microsoftgraph/microsoft-graph-docs/commits/018a7785ab3a1a780cab62e2989cf7ce63b181f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209100640054134-17990/BuildReport?accessString=0d447e387f705a47972f76a67e69daee5f1635e4ff655a9d443e39aae308c198).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 06:53 UTC, opbld32 commented
Docs Build status updates of commit _[e978c12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e978c12883671f9e385d8d19e6ee8ae6fccfd743)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209100650523267-17990/BuildReport?accessString=c6aaa0dffdfada930a664a2f29f36572a81adcf3c86b38e4afbecb8ef4ecdb12).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 08:22 UTC, opbld32 commented
Docs Build status updates of commit _[61c3e8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61c3e8a8f4be223eb6bb91cf86dd58966286812b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/includes/teams-subscription-notes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/includes/teams-subscription-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-17990) (graph-rest-beta) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-17990) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-17990) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-17990) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-17990) |
[concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/AppLevelSubscriptionsDocs/concepts/teams-licenses.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-licenses?branch=pr-en-us-17990) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209100821064281-17990/BuildReport?accessString=d4ea5a857307d3b481454254caaee8ef5932514c8343b9c57daae30cc2a4ead5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-10 08:41 UTC, angelgolfer-ms approved these changes
Thanks to @eddie-lee-msft for incorporating my feedback from yesterday. I made a couple updates, and implemented what I had mentioned in Teams yesterday in your PR as well. I gathered your team would like to have this PR published as soon as it's ready, so in the interest of time, I'll skip the rest of the workflow and publish the PR before the weekend starts (for me).

In case @Danielabom as the content reviewer for this PR sees any other issue, please follow up after publishing.

2022-09-10 08:43 UTC, merged