Initial IndustryData documenation
microsoftgraph/microsoft-graph-docs pull request #18043
Opened 2022-08-15 16:19 UTC by mlafleur

Documentation for upcoming public preview of new IndustryData APIs
Workload PM: vfranks

2022-08-15 16:23 UTC, opbld33 commented
Docs Build status updates of commit _[9ab710d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ab710d9efb2542b8b1fa4f0d0232d0dc0a07679)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-490a419f)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-490a419f)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-490a419f)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-490a419f)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-490a419f)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-490a419f)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-490a419f)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-490a419f)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-490a419f)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-490a419f)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-490a419f)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-490a419f)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-490a419f)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-490a419f)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-490a419f)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-490a419f)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c575ff9ae16c775009-49 [...]

2022-09-02 20:30 UTC, opbld34 commented
Docs Build status updates of commit _[8d3e381](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d3e3817b6fc21db2abe40b030fe08122282b7cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-a2c791d2)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-a2c791d2)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-a2c791d2)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-a2c791d2)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-a2c791d2)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-a2c791d2)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-a2c791d2)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-a2c791d2)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-a2c791d2)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-a2c791d2)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-a2c791d2)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-a2c791d2)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-a2c791d2)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-a2c791d2)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-a2c791d2)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-a2c791d2)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c575ff9ae16c775009-a2 [...]

2022-09-06 23:57 UTC, Lauragra commented
@mlafleur , can you please ping me internally with a pointer to the api.md and CSDL files? Thanks.

2022-10-11 21:47 UTC, opbld32 commented
Learn Build status updates of commit _[0239dfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0239dfa64c625021528762f87886d2603fe8dad5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-41d3117e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-41d3117e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-41d3117e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-41d3117e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-41d3117e)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-41d3117e)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-41d3117e)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-41d3117e)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-41d3117e)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-41d3117e)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-41d3117e)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-41d3117e)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-41d3117e)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-41d3117e)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-41d3117e)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-41d3117e)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-12 22:52 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-identifiertypereferencevalue.md
> +description: "Represents a RefIdentifierType typed ReferenceDefinition."
Please, provide a description that is more descriptive.

Please, apply this change also to line 16.

2022-10-12 22:52 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-inboundfileflow.md
> +  "displayName": "String",
GLOBAL: Please apply this change to all resource topics.

For consistency, please show the properties here in alphabetical order. You don't need to change the position of @odata.type…

2022-10-12 22:52 UTC, JarbasHorst commented
Hello @mlafleur, I reviewed your PR and left some comments. Please, take a look when you will have time.

2022-10-12 22:53 UTC, opbld34 commented
Learn Build status updates of commit _[9c0d86e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c0d86e5e0ec16ec0e33e375e0ca2ccaf64e4835)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-0b00f1b8)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-0b00f1b8)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-0b00f1b8)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-0b00f1b8)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-0b00f1b8)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-0b00f1b8)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-0b00f1b8)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-0b00f1b8)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-0b00f1b8)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-0b00f1b8)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-0b00f1b8)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-0b00f1b8)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-0b00f1b8)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-0b00f1b8)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-0b00f1b8)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-0b00f1b8)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-12 22:55 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-filevalidateoperation.md
> +| createdDateTime    | DateTimeOffset                                                        | **TODO: Add Description** Inherited from [longRunningOperation](../resources/longrunningoperation.md).
GLOBAL: Please add all missing descriptions.

**TODO: Add Description**

2022-10-12 22:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +
GLOBAL: Please apply this change to all API topics:

Please, add the missing HTTP request URL.

2022-10-12 22:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +
GLOBAL: Please apply this change to all API topics:

Please, add the missing example request URL.

2022-10-13 22:42 UTC, opbld32 commented
Learn Build status updates of commit _[dbb185f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbb185fa9581aeeee09f08fbaf3bd2311c289087)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-780f7980)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-780f7980)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-780f7980)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-780f7980)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-780f7980)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-780f7980)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-780f7980)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-780f7980)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-780f7980)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-780f7980)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-780f7980)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-780f7980)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-780f7980)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-780f7980)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-780f7980)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-780f7980)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydatarunactivity.md
> +Status:
How are the following statuses related to this resource? Please, provide a sentence to introduce this part.

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydatarunentitycountmetric.md
> +| active   | Int32 | Count of the entity marked as Active.   |
For clarity, I recommend the following revision for this description:
- The count of entries for the entity marked as \`Active\`.

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydatarunentitycountmetric.md
> +| inactive | Int32 | Count of the entity marked as Inactive. |
For clarity, I recommend the following revision for this description:
- The count of entries for the entity marked as \`Inactive\`.

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +| Delegated (work or school account)     | EduAdministration.Read, EduAdministration.ReadWrite         |
According to the api.md file, industryData introduces a new permissions scope. Please, add all new permissions to the [Microsoft Graph permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference).

Also, why are we not using any of the new industryData permissions in the API topics?

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydataroot.md
> +| inboundFlows         | [microsoft.graph.industryData.inboundFlow](../resources/industrydata-inboundflow.md) collection                           | Set of data import flow processes to bring data in
What preposition should come after data? For example, "Set of data from..."

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydataroot.md
> +| roleGroups           | [microsoft.graph.industryData.roleGroup](../resources/industrydata-rolegroup.md) collection                               | Set of groups of individual roles that makes role-
"...role-based admin..." do you mean administration?

2022-10-13 22:46 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydataroot.md
> +| sourceSystems        | [microsoft.graph.industryData.sourceSystemDefinition](../resources/industrydata-sourcesystemdefinition.md) collection     | The set of systems that represents real work exter
What are "real work external systems"? Please rephrase this sentence to make it more clear.

2022-10-16 20:22 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-azuredatalakeconnector.md
> +| Method                                                                                | Return type
According to the API.md file, this resource also supports a POST operation. Please, include the missing API topic to this documentation and update this Methods table.

2022-10-16 20:22 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-filedataconnector-update.md
> +If successful, this method returns a `200 OK` response code and an updated [fileDataConnector](../resources/industrydata-filedataconnector.md) object in the response body.
According to the API.md file, the PATCH API for the fileDataConnector resource returns 204 and not 200. Please, update this documentation with the correct response code = lines 56 and 87.

2022-10-16 20:22 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-filedataconnector-validate.md
> +If successful, this action returns a `204 No Content` response code.
According to the API.md file, a validation operation is a long-running operation that returns 202. Please, update this documentation with the correct information.

2022-10-16 20:25 UTC, opbld32 commented
Learn Build status updates of commit _[f61c3a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f61c3a9bff499b4819df8c733807a39c213a8d2e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-3bb66a42)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-3bb66a42)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-3bb66a42)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-3bb66a42)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-3bb66a42)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-3bb66a42)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-3bb66a42)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-3bb66a42)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-3bb66a42)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-3bb66a42)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-3bb66a42)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-3bb66a42)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-3bb66a42)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-3bb66a42)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-3bb66a42)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-3bb66a42)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-17 20:03 UTC, opbld31 commented
Learn Build status updates of commit _[10bbfa5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10bbfa59ccc98c64d725e0e34f8341e53d37dd7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-6a4a7557)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-6a4a7557)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-6a4a7557)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-6a4a7557)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-6a4a7557)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-6a4a7557)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-6a4a7557)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-6a4a7557)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-6a4a7557)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-6a4a7557)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-6a4a7557)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-6a4a7557)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-6a4a7557)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-6a4a7557)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-6a4a7557)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-6a4a7557)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-17 21:32 UTC, opbld34 commented
Learn Build status updates of commit _[ab85646](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab85646ebeaf246ff27318d41dd6a2dd31f265b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-06fbed30)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-06fbed30)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-06fbed30)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-06fbed30)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-06fbed30)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-06fbed30)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-06fbed30)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-06fbed30)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-06fbed30)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-06fbed30)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-06fbed30)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-06fbed30)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-06fbed30)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-06fbed30)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-06fbed30)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-06fbed30)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-22 19:34 UTC, opbld30 commented
Learn Build status updates of commit _[8f735b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f735b849f1f80555cffc3c2fa749d905fdb7595)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-070700e9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-070700e9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-070700e9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-070700e9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-070700e9)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-070700e9)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-070700e9)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-070700e9)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-070700e9)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-070700e9)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-070700e9)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-070700e9)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-070700e9)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-070700e9)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-070700e9)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-070700e9)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-24 21:48 UTC, opbld33 commented
Learn Build status updates of commit _[6a8a978](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a8a978bcf3d2a1f7fdb5a2032b3e9a175d848fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-a34c7aa1)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-a34c7aa1)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-a34c7aa1)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-a34c7aa1)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-a34c7aa1)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-a34c7aa1)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-a34c7aa1)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-a34c7aa1)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-a34c7aa1)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-a34c7aa1)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-a34c7aa1)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-a34c7aa1)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-a34c7aa1)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-a34c7aa1)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-a34c7aa1)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-a34c7aa1)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-24 22:00 UTC, opbld32 commented
Learn Build status updates of commit _[b4ef813](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4ef8137dfe973a74f38418dddabb27acbabfbf0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-8a4f89a7)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-8a4f89a7)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-8a4f89a7)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-8a4f89a7)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-8a4f89a7)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-8a4f89a7)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-8a4f89a7)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-8a4f89a7)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-8a4f89a7)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-8a4f89a7)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-8a4f89a7)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-8a4f89a7)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-8a4f89a7)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-8a4f89a7)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-8a4f89a7)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-8a4f89a7)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-10-28 15:42 UTC, opbld31 commented
Learn Build status updates of commit _[eaa2815](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaa28156f91c4b80617b08fd4fcc3e36ec066c4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-c74f40e3)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-c74f40e3)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-c74f40e3)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-c74f40e3)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-c74f40e3)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-c74f40e3)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-c74f40e3)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-c74f40e3)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-c74f40e3)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-c74f40e3)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-c74f40e3)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-c74f40e3)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-c74f40e3)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-c74f40e3)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-c74f40e3)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559bf9-c74f40e3)
[api-reference/beta/api/industrydata-industrydataactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-industrydataactivity-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-industrydataactivity-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5f290a599f7218c57 [...]

2022-11-11 17:04 UTC, opbld34 commented
Learn Build status updates of commit _[24e49bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24e49bbe1622a398831eb1172a8f3c82e5e5b179)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-6e9b011e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-6e9b011e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-6e9b011e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-6e9b011e)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-6e9b011e)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-6e9b011e)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-6e9b011e)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-6e9b011e)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-6e9b011e)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-6e9b011e)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-6e9b011e)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-6e9b011e)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-6e9b011e)
[api-reference/beta/api/industrydata-inboundfileflow-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-post.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-post?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-2a16279413b7c39ce189be6706625596-6e9b011e)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-6e9b011e)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-6e9b011e)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559 [...]

2022-11-24 00:23 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +title: "Delete azureDataLakeConnector"
Hello @vfrankson, your APIs are debuting on Microsoft Graph, so you'll need to please create two additional topics:
* A service-level conceptual topic to let admin/developer customers discover or recognize the value of these APIs. Think what value and scenarios that your APIs serve, that would allow admin/developer customers to match your APIs to their scenarios. For an example, see https://learn.microsoft.com/en-us/graph/browser-edge-concept-overview.
* An API-overview topic to describe the use cases. For an example, see https://learn.microsoft.com/en-us/graph/api/resources/browser-edge-api-overview?view=graph-rest-beta.

2022-12-02 20:33 UTC, vfrankson commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +title: "Delete azureDataLakeConnector"
Is this what you are referring to [industrydata-overview.md]?: https://github.com/microsoftgraph/microsoft-graph-docs/pull/18043/files#diff-832a79823a333caa0c09d7a484810f662d004a17c0768b127b2dcb2c61fc60ce

2022-12-02 20:35 UTC, vfrankson commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
@mlafleur - Can you help with this request?

2022-12-02 23:05 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-filevalidateoperation.md
> +Loop through the list to upload the latest CSV files in preparation for basic file validation. Once the files have been uploaded, call `validate()` to validate the uploaded files and finalize the upl
What is the correct validate method:
- api-reference/beta/api/industrydata-filedataconnector-validate.md
- api-reference/beta/api/industrydata-industrydataconnector-validate.md

Please, add a reference link to the corresponding validate method. Same for line 20.

2022-12-02 23:05 UTC, opbld31 commented
Learn Build status updates of commit _[7e646f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e646f840fc1455591e74a144b978adbe1c6f8e2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-ca08ad60)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-ca08ad60)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-ca08ad60)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-ca08ad60)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-ca08ad60)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-ca08ad60)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-ca08ad60)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-ca08ad60)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-ca08ad60)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-ca08ad60)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-ca08ad60)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-ca08ad60)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-ca08ad60)
[api-reference/beta/api/industrydata-inboundfileflow-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-post.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-post?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-2a16279413b7c39ce189be6706625596-ca08ad60)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-ca08ad60)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-ca08ad60)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559 [...]

2022-12-02 23:11 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +title: "Delete azureDataLakeConnector"
@vfrankson, the industrydata-overview is the API reference topic. That is great! However, we still need a service-level conceptual topic. I will send you a link via Teams to provide more details.

2022-12-05 23:27 UTC, JarbasHorst commented on api-reference/beta/toc.yml
> +    - name: Industry data ingestion
Please, include to the TOC also the APIs for

- api-reference/beta/resources/industrydata-azuredatalakeconnector.md
- api-reference/beta/resources/industrydata-industrydataroot.md
- api-reference/beta/resources/industrydata-industrydatarunactivity.md

2022-12-05 23:27 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-overview.md
> +When the run starts, it'll connect to the **sourceSystemDefinition** and **dataConnector** of the inbound flow, and perform basic validation. Basic validation ensures that the connection is correct,
I have added a reference link to OneRoster API. In case this link is wrong, please either remove or update it.

2022-12-05 23:29 UTC, opbld31 commented
Learn Build status updates of commit _[57998bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57998bcb49b535fe79caea0a65b1f9838eba6a1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-d909331d9e164337a22514c88be77981-31d979f9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5bebd08285dd278ec00153fdc28d499a-31d979f9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-getuploadsession.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-getuploadsession?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-092c8bc987305fbe61ee46942a7e8ff4-31d979f9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-9a56aea8d6343474644ac7d41b1179f3-31d979f9)
[api-reference/beta/api/industrydata-azuredatalakeconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-azuredatalakeconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-azuredatalakeconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a58b089358909841316136adaac560b3-31d979f9)
[api-reference/beta/api/industrydata-filedataconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-03faff32e8bf68da08920e91c15eabda-31d979f9)
[api-reference/beta/api/industrydata-filedataconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-12df96042613a7f0933737ac39edfa6e-31d979f9)
[api-reference/beta/api/industrydata-filedataconnector-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-6a8e45a93c3429d1e739be19436e28f6-31d979f9)
[api-reference/beta/api/industrydata-filedataconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-a33fd9700d5712720e4b68fd103f3ff5-31d979f9)
[api-reference/beta/api/industrydata-filedataconnector-validate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-filedataconnector-validate.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-filedataconnector-validate?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-572073350364ddb9ef0ea28177132699-31d979f9)
[api-reference/beta/api/industrydata-inboundfileflow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-delete.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-delete?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-b738890cd7c142b3e5682dccaff1413b-31d979f9)
[api-reference/beta/api/industrydata-inboundfileflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-bd123f9a393a5e6d581dbd22168d2333-31d979f9)
[api-reference/beta/api/industrydata-inboundfileflow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-list.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-list?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-5c0b2d1082a2952f3506496ba60b90dd-31d979f9)
[api-reference/beta/api/industrydata-inboundfileflow-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-post.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-post?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-2a16279413b7c39ce189be6706625596-31d979f9)
[api-reference/beta/api/industrydata-inboundfileflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundfileflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundfileflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-567e01bd3d556a6da2b926304b56ea79-31d979f9)
[api-reference/beta/api/industrydata-inboundflow-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-get.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-get?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-dfa0129d58a027bc7ce7464e3eb57fb5-31d979f9)
[api-reference/beta/api/industrydata-inboundflow-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edu/industryData/api-reference/beta/api/industrydata-inboundflow-update.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/industrydata-inboundflow-update?view=graph-rest-beta&branch=pr-en-us-18043) (graph-rest-beta) | [Details](#user-content-117120233f9b7824a92963930a559 [...]

2022-12-14 17:20 UTC, mlafleur commented on api-reference/beta/toc.yml
> +    - name: Industry data ingestion
`industryDataRoot` is purely a navigation container. Should We simply remove this file from resources?

2022-12-14 17:32 UTC, mlafleur commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +| Delegated (work or school account)     | EduAdministration.Read, EduAdministration.ReadWrite         |
These are in progress with AAD. We didn't want to add them until they were out of test/preview and selectable via the registration portable.

2022-12-14 18:00 UTC, mlafleur commented on api-reference/beta/api/industrydata-filedataconnector-update.md
> +If successful, this method returns a `200 OK` response code and an updated [fileDataConnector](../resources/industrydata-filedataconnector.md) object in the response body.
I've noticed other abstract types do not provide pages for API operations. I'm assuming we shouldn't be including them either. I'll remove them for the time being and add them back if I'm misinterpreting something.

2022-12-14 20:34 UTC, mlafleur commented on api-reference/beta/resources/industrydata-inboundfileflow.md
> +  "displayName": "String",
I'm not sure I understand. This `@` places it first alphabetically and matches the property order returned by the API.

2022-12-14 20:46 UTC, mlafleur commented on api-reference/beta/resources/industrydata-filevalidateoperation.md
> +Loop through the list to upload the latest CSV files in preparation for basic file validation. Once the files have been uploaded, call `validate()` to validate the uploaded files and finalize the upl
`fileDataConnector` is an abstract type derived from the abstract `industryDataConnector`. The `validate()` method is bound to `industryDataConnector`.

2022-12-16 05:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +![industryData overview](../../concepts/images/industryData-overview-1.png)
In addition, @mlafleur :
Please make sure the image displays properly. It doesn't right now on the staging site.
Please rename "M365" as "Microsoft 365" in the image, even if that breaks into 2 lines. This is a branding issue which we cannot disregard.
In general, please use sentence case. For example, "Date Ingestion" -> "Data ingestion". @Jarbas-MSFT , can you please help guide @mlafleur with the casing per [Microsoft Cloud + AI guidance](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357)?

2022-12-16 06:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +# Use the industry data APIs in Microsoft Graph (preview)
Line 10 topic title:
For this debut release, I strongly recommend the topic title to include keywords that indicate this set of API currently works for the education industry. This IMO would be the main conduit to channel customers to find practicality and value to this new industry API.

I suggest something like "Use the industry data API in Microsoft Graph to import and transform education data (preview)". 
@mlafleur can please suggest more appropriate verbs for "import and transform", taking into consideration those are words that customers would use to search.

2022-12-16 08:54 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +
Line 26 + GLOBAL:
Please use present tense in documentation. Even if the context involves a sequence of events that don't all happen at the same time, it's important  to stick to present tense.
The use of future tense (e.g., "will" or its abbreviations) can be ambiguous - does the tense indicate this behavior or feature doesn't exist yet but will exist at some point in the future? Please see the Microsoft Writing Style Guide here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523

2022-12-16 09:09 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +Industry data APIs power the [Microsoft School Data Sync](https://sds.microsoft.com) (SDS) platform to help automate the process of importing and synchronizing organizations, users and users associat
Before line 16:
@mlafleur , if we proceed with letting the industry API go under a new top-level node like "Industry data ingestion", then I think this overview topic should start by being clearer that "this set of API is intended to be a multi-vertical, cross-industry platform. In the current release, it is highly tailored to the education industry, powering the Microsoft School Data Sync (SDS) platform to help..."

2022-12-20 17:37 UTC, mlafleur commented on api-reference/beta/resources/industrydata-overview.md
> +Industry data APIs power the [Microsoft School Data Sync](https://sds.microsoft.com) (SDS) platform to help automate the process of importing and synchronizing organizations, users and users associat
@vfrankson

2022-12-21 19:21 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
> +Industry data APIs power the [Microsoft School Data Sync](https://sds.microsoft.com) (SDS) platform to help automate the process of importing and synchronizing organizations, users and users associat
@mlafleur 
I have uploaded changes based on the email exchange to this page. I see there is some build error for a merge conflict but unsure what it raising the conflict.

2023-01-04 20:12 UTC, mlafleur commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
@JarbasHorst, is there a tool for generating the initial change log for new workloads? I've been unable to generate one via Graph Studio,

2023-01-05 19:58 UTC, Lauragra commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
@mlafleur , the changelog file should be generated as part of the schema PR; can you take a look? Otherwise, you can theoretically add manually but that would be painstaking. ;)

2023-01-09 00:32 UTC, mlafleur commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
@Lauragra  I copied the file from the PR, but it is quite sparse and seems to be breaking the docs buid.

2023-01-09 19:57 UTC, mlafleur commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +| Delegated (work or school account)     | EduAdministration.Read, EduAdministration.ReadWrite         |
Updated

2023-01-09 20:43 UTC, mlafleur commented on api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
> +    "displayName": "String"
Could you clarify, should we remove the JSON Representation or should we change the JSON to mirror a GET response?

2023-01-09 20:49 UTC, Lauragra commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
@mlafleur , yes, something doesn't look right. The changelog should list every new resource, action, and function defined in the metadata. Are you sure that you got the right generated file?

2023-01-10 00:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-inboundfileflow-delete.md
> +DELETE https://graph.microsoft.com/beta/external/industryData/inboundFlows/{inboundFlowId}
In line 36, the request URL contains "/$ref" after the {inboundFlowId}. Please, ensure that the request URL is correct. Also, please replace the {inboundFlowId} placeholder with a real-looking value.

2023-01-10 00:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-inboundfileflow-post.md
> +  "displayName": "String",
Please, replace the values "String", "String (timestamp)", and so on, with real-looking values. Also, should a customer provide "@odata.type": "#microsoft.graph.industryData.inboundFileFlow" when sending this post request?

Please, update the values for the response object (lines 115-122).


Same here:
- api-reference/beta/api/industrydata-inboundfileflow-update.md

2023-01-10 00:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-inboundflow-update.md
> +PATCH https://graph.microsoft.com/beta/external/industryData/inboundFlows/{inboundFlowId}
Please, replace {inboundFlowId} with a real-looking value. Also, please replace the "String" and "String (timestamp)"  with real-looking values. 

Should a customer provide the @odata.type when requesting this operation?

2023-01-10 00:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-industrydataroot-delete-sourcesystems.md
> +### Response
This API topic has two response sections for the same example. Please remove the response section that is not related to this example.

Same for:
- api-reference/beta/api/industrydata-industrydataroot-delete-years.md

2023-01-10 00:55 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-industrydataroot-delete-sourcesystems.md
> +POST /external/industryData/sourceSystems
Please, ensure you have the correct HTTP request URL here!

Same for:
- api-reference/beta/api/industrydata-industrydataroot-delete-years.md

2023-01-12 22:52 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
> +    "displayName": "String"
This change isn't needed anymore.

2023-01-12 22:52 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-azuredatalakeconnector.md
> +## Scenarios
(Scenarios) We don't support non-standard H2s. Please, incorporate that information into the api-reference/beta/resources/industrydata-overview.md concept topic under "Scenarios".

After you will have moved the content to the mentioned overview topic, you can add a reference link to this summary section to point to the corresponding section in the industry data API reference overview topic (api-reference/beta/resources/industrydata-overview.md).

2023-01-12 22:52 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-referencevalue.md
> +#### Example Usage
A resource topic begins with a 1-2 sentence summary and may contain additional paragraphs and H3s before the first H2 section. In any case, this section should not contain H4s and JSON code samples. 

Since a very similar content already exists here (api-reference/beta/resources/industrydata-overview.md), I recommend you to move the content from this H4 section into the "Example usage" section of the industry data API reference overview topic.

After you will have moved the content to the mentioned overview topic, you can add a reference link to this summary section to point to the corresponding section in the industry data API reference overview topic (api-reference/beta/resources/industrydata-overview.md).

2023-01-12 22:52 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-overview.md
> +The following articles are to help with some basics that are specific to industry data APIs.
According to this sentence, a list of articles should come after this line. If that is still the plan, please include the missing list; otherwise, rephrase this sentence. Or do you mean the following sections, like Data domain or Reference  Definitions?

2023-01-12 22:52 UTC, JarbasHorst commented on changelog/Microsoft.IndustryData.json
> +﻿{
This PR introduces new enums but they haven't been documented. Please document all new enums that are added via this PR.

2023-01-13 19:16 UTC, mlafleur commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
This is a new workload and we've only rolled out a single schema version

2023-01-17 16:03 UTC, mlafleur commented on api-reference/beta/resources/industrydata-inboundflow.md
> +A **industryDataInboundFlow** represents an activity that gets executed by the service. The `dataDomain` property defines the type of data being imported and is used determine the common data model f
I've confirmed that all references to industryDataInboundFlow have been corrected.

2023-01-21 06:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +
Line 16:
@vfrankson , @mlafleur , 
does this phrase "and synchronizing organizations, users and users associations, and groups with Azure Active Directory (Azure AD) and Office 365" refer to the part of the architecture diagram that I had brought up in our email thread (on 12/16/2022) and that @vfrankson had removed from the image in his Github [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18043#discussion_r1054758908) on 12/21?

In other words, if I understand that phrase correctly, then we should also leave that out in the debut release as it's not going to be included then.

In the interest of time, I'm going to comment that phrase out in the topic. When that phrase becomes applicable in a future release, you can conveniently have the verbiage available in the MD file to include it then.

2023-01-21 07:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +
Lines 16, 20, and 22:
I'm going to reorganize and further refine the introduction in these few lines, hopefully to better differentiate on debut, there's this concept of a multi-vertical platform even though it's closely tied to the education industry.

2023-01-21 07:18 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +    - name: Industry data ETL
@mlafleur , can you please move this "Industry data ETL" node to follow alphabetical order at that level of the TOC, and insert it between the 2 nodes "Identity and access" and "Mail"?

That being said, honestly, I still think while the API debuts with education as the only industry it supports, putting it under the "Education" node makes this functionality much more discoverable by your existing EDU customers. There are a couple of other sets of APIs that recently published and serve only one workload for the time being, We apply other designs to prioritize at debut, exposing their value to those customers who can use those APIs now. If you're interested in exploring that, we can discuss that more offline.

2023-01-21 07:29 UTC, angelgolfer-ms requested changes
Hi @mlafleur , @vfrankson , thanks for incorporating my earlier feedback from the email thread.
FYI I reorganized the beginning of the topic and the first paragraph of the first subsection a bit. I entered a few comments to explain what I did, and the TOC organization, please take a look.

If you do decide to have the TOC node as a top level node (as a peer to "Education" rather than as a child to "Education"), then there are two other tasks for you:
(a) Create a service-level conceptual overview. Please see more info, in particular, the structure and the value proposition that should go into that topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211743/Conceptual-topics?anchor=what-to-write-for-your-service-overview%3F

(b) Update the [major services](https://learn.microsoft.com/en-us/graph/overview-major-services?view=graph-rest-beta#education) topic by adding a table row to the "Education" table. You can refer to the existing tables and follow what goes into which table columns.

Please ping me on Teams if you have questions about the 2 tasks.

2023-01-23 20:16 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
> +
Sounds good. Thanks.

2023-01-23 20:19 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
> +
Got it, thanks.

2023-01-23 22:14 UTC, vfrankson commented on api-reference/beta/toc.yml
> +    - name: Industry data ETL
@angelgolfer-ms updated TOC per feedback.

2023-01-23 22:23 UTC, vfrankson commented on api-reference/beta/toc.yml
> +    - name: Industry data ETL
@angelgolfer-ms added the conceptual overview, updated major services, and updated TOC's as needed

2023-01-24 01:59 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Data connectors
This comment is for the child nodes under "Industry data ETL" (line 22035):
I just happened to notice this as my part for this PR was the TOC node (and I read some of the existing topics to get educated about this API), so please excuse me for bringing this up rather close to the target date.

@vfrankson or @mlafleur , @Jarbas-MSFT , I have a couple pieces of feedback about the reference TOC:
- Can you please order the children nodes alphabetically? You can pick one node which is the "main" node representative of this feature, and list that as the first child node. Then please order the rest of the resource nodes alphabetically. Please see this CDK topic, the table row for "Resource": https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211766/ToC-and-topic-title?anchor=guidelines-and-examples
- For the resource industryDataConnector, can you please include the word "Industry" as the first word in the TOC node? This is to better disambiguate for customers who might be browsing manually. "Data Connect" and "connectors" are prominent features in Microsoft Graph and many customers use them. On the other hand, customers have already complained these terms are just too similar and can create unintended miscommunication. So as your API debuts, please use "Industry data connector" as the TOC node label.
- For each TOC node associated with a resource, can you please express the TOC node label as a friendly name but with the same words in the resource name, and in the same singular or plural form of the word? So for example, instead of a node called "Activities", can you please rename the TOC node title as "Industry data run", and apply the same to the resource topic TOC title and topic title? This would alleviate an extra level of confusion for some customers. As you might be aware, in the Microsoft Graph API, some resources (with names in the singular form) are associated with navigation properties for other resources, and the nav properties are expressed in the plural form of the name. So in general, we want to keep the TOC and topic titles matching, so to reduce any miscommunication.

2023-01-24 02:57 UTC, angelgolfer-ms commented on concepts/overview-major-services.md
> +| Industry Data | Education        | Provides information relevant for education scenarios, including schools, classes, students, teachers, insights and analytics scenarios. Enables ISVs to build app
Line 124:
To avoid confusion from having the same first sentence in both table rows, I'm going to replace the first sentence in the second table row with the following:
A multi-vertical, cross-industry, ETL (Extract-Transform-Load) platform that includes support for the education sector, enabling applications to manage and move user and roster data from a student information system (SIS).

2023-01-24 03:10 UTC, angelgolfer-ms commented on concepts/toc.yml
> +            displayName: industry data
Line 419:
@vfrankson , FYI "displayName" actually is about search terms that you think customers may enter in the search box above the TOC in the docs site, that you want those search terms to map to this set of industry data API. So for example, for the "Mail" TOC node, there's a an "Overview" topic in line 438, and there we entered "Outlook, Outlook mail, ..." as possible search terms that we want the docs site to map to this topic if a customers enters the search term "Outlook mail".
It's not necessary to enter "industry data" as a search term because that's the name of the TOC node on line 415. You can add more search terms you can think of though.

2023-01-24 04:18 UTC, angelgolfer-ms commented on concepts/toc.yml
> +          - name: Set up an EDU development environment
Lines 420 - 435:
@vfrankson , I guess you inserted this set of EDU topics under the node for the industry API in the conceptual section because you'd like customers to proceed to trying out the EDU APIs in Graph Explorer?

IMO a better way of doing this is in the "Next steps" section of the conceptual overview (industrydata-concept-overview.md). There you can add more lead-in text to explain what customers can expect before they click those EDU topics. Otherwise, without the lead-in text, newer customers may not realize how it is that they just read a couple of paragraphs in the industry data API conceptual overview and the next thing they see in the TOC is setting up a demo tenant for the EDU API.

In the interest of time, I have updated the "Next steps" section in the conceptual overview (industrydata-concept-overview.md. I'm also going to remove these few lines in the TOC here.

2023-01-24 04:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
>  The API provides resources that you can use to retrieve statistics after the data is processed, and assist with monitoring and troubleshooting.
Line 26:
@vfrankson , can you please figure out why your image is not being displayed in the staged topic now?

If you view this topic on the staging site (https://review.learn.microsoft.com/en-us/graph/api/resources/industrydata-overview?view=graph-rest-beta&branch=pr-en-us-18043), the image is not displayed anymore.

2023-01-24 05:05 UTC, angelgolfer-ms requested changes
Hi @vfrankson ,
Thanks for incorporating my feedback from before the weekend! 

FYI I made some updates to the PR to make the conceptual and API overview more cohesive, and follow a few existing guidelines.

I noticed a few other issues that I'd appreciate you to follow up - 
- The TOC titles of some reference topics.
- Ordering of TOC children nodes in the reference section.
- Architecture image in the API overview now seemingly not displayed on the staging site.
- A bunch of API Doctor errors. 

@Jarbas-MSFT , do you mind helping @vfrankson  if he has questions on these issues?
Can you also please follow up on any other remaining issues for this PR?

Thanks!

2023-01-24 18:51 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
>  The API provides resources that you can use to retrieve statistics after the data is processed, and assist with monitoring and troubleshooting.
@angelgolfer-ms I am not sure why, when I look at the rendering in Visual Studio Code in Preview it shows as expected. 

@Jarbas-MSFT any ideas?

![image](https://user-images.githubusercontent.com/12256809/214381765-e949d0e8-4736-4c8b-8fcd-a3569c280c82.png)

2023-01-24 19:05 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
>  The API provides resources that you can use to retrieve statistics after the data is processed, and assist with monitoring and troubleshooting.
I found this message in the latest build report... not sure what this means / how to remediate 🤷‍♂️

Line 24: [Warning] File '../concepts/images/industrydata-overview.png' referenced by link '../../../concepts/images/industrydata-overview.png' will not be built because it is not included in build scope

2023-01-24 21:01 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
>  The API provides resources that you can use to retrieve statistics after the data is processed, and assist with monitoring and troubleshooting.
Forced an update on the image and submitted changes for next build to complete. Hopefully this unwedges this...

2023-01-24 21:07 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
>  The API provides resources that you can use to retrieve statistics after the data is processed, and assist with monitoring and troubleshooting.
Still getting the same message in the build log, even though I see with the following commit the updated image file in the path.

Line 24: [Warning] File '../concepts/images/industrydata-overview.png' referenced by link '../../../concepts/images/industrydata-overview.png' will not be built because it is not included in build scope

https://github.com/microsoftgraph/microsoft-graph-docs/pull/18043/commits/817e2811cbc10f21d124c25c7ee93d7883df8ec4

2023-01-24 21:14 UTC, vfrankson commented on api-reference/beta/resources/industrydata-overview.md
>  The API provides resources that you can use to retrieve statistics after the data is processed, and assist with monitoring and troubleshooting.
@angelgolfer-ms Jarbas has not been online since 1/19. I believe that Marc and I have addressed the remaining issues you mentioned in your last comment with the 4 items, minus item 3 with the info the above re: the image not being in the build scope. Not sure how to remediate this.

2023-01-25 22:49 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| _IndustryData.ReadBasic.All_                | View basic service and resource information               | Allows the app to read basic service and resource information without a signed-in user. | N
Based on the deployed permissions in Microsoft Azure, this permission requires admin consent. If this is correct, please update the value of the Admin Consent column.

2023-01-25 22:49 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-overview.md
> +Once all CSV data has been successfully uploaded, the data must be validated before any inbound data flows can being processing the data. This is accomplished by calling the [validate](../api/industr
For clarity, should "can being processing" be replaced with "can process"?

2023-01-25 22:49 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-industrydatarun-getstatistics.md
> +GET https://graph.microsoft.com/beta/external/industryData/runs/918d4a8f-599b-4f6a-b409-e892855db534/getStatistics
The HTTP request URL contains () after getStatistics (line 36). Please, ensure that the request URL is correct.

2023-01-26 15:07 UTC, mlafleur commented on concepts/permissions-reference.md
> +#### Delegated permissions
These were approved but are currently hidden in AAD until the corresponding functionality is available on the API.

2023-01-26 15:08 UTC, mlafleur commented on concepts/permissions-reference.md
> +#### Application permissions
This is currently hidden in AAD until the functionality it enabled is available on Graph. This isn't expected until Q2.

2023-01-27 00:27 UTC, Jarbas-MSFT commented on api-reference/beta/api/industrydata-azuredatalakeconnector-delete.md
> +---
@mlafleur, as explained by Laura, the changelog should list every new resource, enum, action, and function defined in the metadata. This applies even for new workloads. Just to clarify, the changelog entries are needed before we can publish the PR.

2023-01-27 01:26 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-industrydatarunactivity.md
> +
For clarity, please add an introductory sentence before listing the possible statuses. For example:

- ...a single \[industryDataRun\](industrydata-industrydatarun.md). Possible status are:

2023-01-27 01:26 UTC, JarbasHorst commented on api-reference/beta/resources/industrydata-longrunningoperation.md
> +---
@mlafleur, we should remove the industrydata-longrunningoperation from this PR as this resource already exists in Microsoft Graph.

We are wondering how to present the industrydata-longrunningoperation-get and industry-longrunningoperation-list in the TOC. Are these files related to the fileValidateOperation resource topic? If yes, we need to add there the Methods table to list the supported methods. Also, if both API topics are related to the fileValidateOperation resource, then I believe they should be rename to reflect the correct resource type: industrydata-filevalidateoperation-get and so on.

2023-01-27 19:01 UTC, mlafleur commented on api-reference/beta/resources/industrydata-longrunningoperation.md
> +---
Our API includes a `/operations` endpoint. This returns a collection of `longRunningOperation` entities. 

A `fileDownloadOperation` is but one potential type included in this collection, The majority of long-running operations in our API use the base `longRunningOperation` type.  

The `fileDownloadOperation` is similar to the [authenticationMethod](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationmethod) resource from the StrongAuthenticationAPI workload. The primary difference being our workload's `/operations` endpoint returns `Collection(longRunningOperation)` where `/authentication/methods` returns ``Collection(softwareOathAuthenticationMethod)``

2023-01-27 19:17 UTC, mlafleur commented on concepts/permissions-reference.md
> +| _IndustryData.ReadBasic.All_                | View basic service and resource information               | Allows the app to read basic service and resource information without a signed-in user. | N
I've double checked in the deployed scopes. The delegated `IndustryData.ReadBasic.All` scope does not require Admin Consent. 

![image](https://user-images.githubusercontent.com/3802472/215176837-18a849de-90bd-4f72-8593-65ebabc7039f.png)

2023-01-27 20:07 UTC, mlafleur commented on api-reference/beta/api/industrydata-industrydataconnector-post.md
> +    "@odata.type": "#microsoft.graph.industryData.azureDataLakeConnector",
Since `industryDataConnector` is an abstract type, it isn't possible to post an instance of one.  I went used `azureDataLakeConnector` to provide a usable example.

2023-01-27 20:32 UTC, mlafleur commented on api-reference/beta/api/industrydata-yeartimeperioddefinition-list.md
> +      "endDate": "2023-06-15",
This is in the correct format. Both `startDate` and `endDate` use the `Edm.Date` primitive type from [OData 4](http://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html#_Toc366145496)

2023-01-27 20:34 UTC, mlafleur commented on api-reference/beta/api/industrydata-yeartimeperioddefinition-get.md
> +  "endDate": "2023-06-15",
This seems to be an API Doctor issue because it is properly formatted. Both `startDate` and `endDate` use the `Edm.Date` primitive type from [OData 4](http://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html#_Toc366145496)

2023-01-27 20:34 UTC, mlafleur commented on api-reference/beta/api/industrydata-yeartimeperioddefinition-post.md
> +  "endDate": "2023-06-15",
This seems to be an API Doctor issue because it is properly formatted. Both `startDate` and `endDate` use the `Edm.Date` primitive type from [OData 4](http://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html#_Toc366145496)

2023-01-27 20:35 UTC, mlafleur commented on api-reference/beta/resources/industrydata-longrunningoperation.md
> +---
I'd added get/list API pages for fileDownloadOperation.

2023-01-31 05:09 UTC, angelgolfer-ms commented on api-reference/beta/resources/industrydata-overview.md
> +
Line 22:
@vfrankson , @mlafleur , @Jarbas-MSFT , 
Per the above comment - "synchronizing organizations, users and users associations, and groups with Azure Active Directory (Azure AD) and Office 365" is not in scope for the debut release, is that still the case?

I guess it is, because those features are appropriately excluded from the architecture image for the upcoming debut release.

Earlier I had commented out the following part of the sentence in line 22, instead of deleting that part of the sentence:
"and synchronizing organizations, users and users associations, and groups with Azure Active Directory (Azure AD) and Office 365"
I thought that would make it more convenient later on to remove the comment characters to add the text back into the topic. 

But somehow line 22 includes that part of the sentence now.

In the interest of time, I am going ahead to remove that part of the sentence, so not to allude to unsupported features .

Please let me know on Teams if I overlooked anything here.

2023-02-01 09:20 UTC, JarbasHorst commented on api-reference/beta/api/industrydata-inboundfileflow-post.md
> +### Request
The API Doctor throws the following exception for this example:
"Error: create_inboundflow_from_/dataConnector:
Referenced type microsoft.graph.industryDataConnector is not defined in the doc set! Potential suggestion: microsoft.graph.industryData.industryDataConnector"

Same also for the year.

Please, ensure the values used in the request example are correct.

2023-02-01 10:51 UTC, JarbasHorst commented
Hi, thanks for addressing my previous comments. I left one additional comment that is related to an API Doctor issue. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [20086](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20086) into your branch to include my fixes and before addressing my new comment.

Regarding the longRunningOperation topic: If your API includes an `/operations` endpoint and if they return **microsoft.graph.longRunningOperation** objects, then we don't need to have extra topics for this scenario, because the longRunningOperation BETA already exits under the Graph namespace.

For clarity, I removed the following topics from this PR. We can readd them if needed.
- api-reference/beta/resources/industrydata-longrunningoperation.md and its methods
- api-reference/beta/api/industrydata-validateOperation-get.md and api-reference/beta/api/industrydata-validateOperation-list.md: It should be enough to have only the LIST and GET operations for the fileValidateOperation resource type.

2023-02-01 22:09 UTC, mlafleur commented on api-reference/beta/api/industrydata-inboundfileflow-post.md
> +### Request
I've confirmed they are correct.

2023-02-03 01:32 UTC, JarbasHorst commented
Hi @mlafleur, I added one comment to your PR. Please, take a look when you will have time. I fixed some API Doctor issues about the Edm.Date type. I will check with Laura if we can find a solution for the two remaining API Doctor issues.

2023-02-09 16:09 UTC, mlafleur commented on api-reference/beta/api/industrydata-inboundfileflow-post.md
> +POST /external/industryData/inboundFlows
It is correct. The reason it looks a little strange is because only one entity derived from `inboundFlow` is supported in this initial release. 

In a forthcoming release we will be adding a `inboundApiFlow` entity which also derives from `inboundFlow`. At this point `/industryData/inboundFlows` will return a mixed collection of `inboundApiFlow` and `inboundFileFlow` resources. To return a single resource type, callers would use an `IsOf` filter:
```
/industryData/inboundFlows?$filter=IsOf('microsoft.graph.industryData.inboundFileFlow')
```

I've had similar questions regarding abstract types, The EducationDataSync workload relies on abstract types and it has always presented a challenge. In several places, EducationDataSync uses the abstract page as a ["landing page"](https://learn.microsoft.com/en-us/graph/api/resources/educationidentitysynchronizationconfiguration?view=graph-rest-beta) with links to the derived resources. This can help with discoverability as the abstract name is typically the colloquial name for the broader set, but it is miles from ideal.

2023-02-14 00:27 UTC, JarbasHorst commented
@Lauragra, this PR is ready for final review.

2023-03-07 04:24 UTC, Lauragra commented on api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
> +If successful, this method returns a `200 OK` response code and an [azureDataLakeConnector](../resources/industrydata-azuredatalakeconnector.md) object in the response body.
Global: Please be sure to specify the subnamespace anywhere that we list a return type. It looks like we're primarily missing it where we list and link to types in Response sections. So, this would be microsoft.graph.industryData.azureDataLakeConnector.

2023-03-09 06:01 UTC, Jarbas-MSFT commented on api-reference/beta/api/industrydata-azuredatalakeconnector-get.md
> +If successful, this method returns a `200 OK` response code and an [azureDataLakeConnector](../resources/industrydata-azuredatalakeconnector.md) object in the response body.
Comment addressed via PR [20514](https://github.com/microsoftgraph/microsoft-graph-docs/pull/20514).

2023-03-13 15:55 UTC, Lauragra approved these changes

2023-03-14 02:28 UTC, merged