Update conditionalaccessusers.md
microsoftgraph/microsoft-graph-docs pull request #18080
Opened 2022-08-17 15:56 UTC by SanDeo-MSFT

2022-08-17 15:58 UTC, opbld31 commented
Docs Build status updates of commit _[0fa336f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fa336ff0d2676c876ff0810c4b7d7e2d6ecf38b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-e42202205362c595b448ff2195f68fba-69e3a803)

<a id="e42202205362c595b448ff2195f68fba-69e3a803"></a>
### [api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md)
 - **Line 24, Column 34**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'conditionalAccessGuestsOrExternalUsers.md'.`````
 - **Line 25, Column 34**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'conditionalAccessGuestsOrExternalUsers.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171556143763-18080/BuildReport?accessString=5439923e4e3c60bf5916d6c47fe7dcc169491120e77fa12e5a158c89a65daa11).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:04 UTC, opbld30 commented
Docs Build status updates of commit _[1710c29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1710c2955ec080b9b290c7cb0f1281b1d392e941)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171601583881-18080/BuildReport?accessString=c43d6dd423f0958b4935d581c4d93849fa881da3c9669e6f8dbc7a63f8864162).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:15 UTC, opbld33 commented
Docs Build status updates of commit _[9ef3dfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ef3dfba10f675940d09a523ccc1c61dae1cc92a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171613021339-18080/BuildReport?accessString=9aabd3f2e0bed197cd4c530c03ed28b4da9d20cd8bfd0d185e2759bbba7ba340).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:28 UTC, opbld32 commented
Docs Build status updates of commit _[32416d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32416d05649c854aea5fa3996a4baeacf487eb14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestorexternalusertypes?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171626150828-18080/BuildReport?accessString=f139b2d00ab6c2ab03f0ee12c84944919dac55b7380afef5517b54ce150d7136).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:33 UTC, opbld30 commented
Docs Build status updates of commit _[98411ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98411ab52c69f0ada7a9592010a0a580b0b8dc8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestorexternalusertypes?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171631095577-18080/BuildReport?accessString=2b9ab2e21de515419bb5d36917b81c4f3c3424cc5ef0daa3e4ce372f1cfed2c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:35 UTC, opbld32 commented
Docs Build status updates of commit _[d3bfa8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3bfa8a981d68f895eb67111f047fb02a56135fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestorexternalusertypes?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171632170433-18080/BuildReport?accessString=a139d0f35fa25c9f49e125b9332ca519ad4dba032f2ab98b3409d2224b46489b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:45 UTC, opbld34 commented
Docs Build status updates of commit _[1c8c82b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c8c82b6a6d8669fedcaa5141e6590aab1d34e37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestOrExternalUserTypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestorexternalusertypes?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171642408341-18080/BuildReport?accessString=617c18e45a3b71b67dccc913342743a1dbb142cce535577264de8a930e143ef4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:49 UTC, opbld30 commented
Docs Build status updates of commit _[92eed8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92eed8b9babd127acac6f4371330b9f6839e9144)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208171647387940-18080/BuildReport?accessString=f2e5a7c28f1a0087787bca1c1a61b9157fa5da91cb5aab4358f1be065dcdffa5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 09:56 UTC, FaithOmbongi commented
Hi @SanDeo-MSFT - Can you provide the ID of the schema PR? Just the ID, not the full URL.

2022-08-18 17:18 UTC, FaithOmbongi commented
Assigning this to you @Danielabom to help me out. Thank you.

2022-08-18 17:20 UTC, opbld30 commented
Docs Build status updates of commit _[7883015](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78830151d667fff13b37c78130a107f4ff9bb639)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208181718355883-18080/BuildReport?accessString=321caac86d674d8233feebaea4a86baf619ac139f3033de99d155be3d5acb43c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 17:22 UTC, opbld33 commented
Docs Build status updates of commit _[f13a766](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f13a766729dd963f4f573407194a702447112739)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208181720449383-18080/BuildReport?accessString=6e26e77da30ec3f66570918ef5dc0cd2c2a328a44f673c85555843c22f48fc70).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 18:18 UTC, SanDeo-MSFT commented
> Hi @SanDeo-MSFT - Can you provide the ID of the schema PR? Just the ID, not the full URL.

6605397

2022-08-18 23:41 UTC, opbld32 commented
Docs Build status updates of commit _[5637fac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5637facb142059b725765884df1dc3a842ee9434)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208182339360179-18080/BuildReport?accessString=b767677f9ee4f389ffb606fb8e08475700158be9d1d7d1059871fe2a55b648db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 23:43 UTC, opbld33 commented
Docs Build status updates of commit _[65362e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65362e85a533afe2f1ea9b8d135ba3abb7ab67cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208182340357375-18080/BuildReport?accessString=e2879156f24a1bd0779f89992565d0a8e32be60adf609cb5ca70e1e6147f0d1f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 15:55 UTC, Danielabom commented on api-reference/beta/resources/includes/conditionalAccessExternalTenants.md
> +| membershipKind |conditionalAccessExternalTenantsMembershipKind collection | Enum types represent the membership kind. Supported values include `all`, `enumerated` and `unknownFutureValue`. |
```suggestion
| membershipKind |conditionalAccessExternalTenantsMembershipKind collection | Represents the membership kind. Supported values are: `all`, `enumerated` and `unknownFutureValue`. |
```

2022-08-19 15:57 UTC, Danielabom commented on api-reference/beta/resources/includes/conditionalAccessExternalTenants.md
> +---
Is there a particular reason why the location of this file is 
api-reference/beta/resources/includes and not 
api-reference/beta/resources
Will this file turn into automated content when called?

2022-08-19 21:57 UTC, Danielabom commented on api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md
> +| members | String collection | A collection of tenant ids that the selected guests or external users are from. |
This sentence is somehow misleading. Can you provide details so we can build a better description together?

2022-08-19 22:14 UTC, Danielabom commented on api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md
> +| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes collection | Flagged enum of the types of internal guests or external users. Supported values include `b2bCollaborationGuest`, `
Please review the suggestion, I would like to change the form of the verb, would you mind providing more details about the property? ```suggestion
| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes collection | Flag enum representing the types of internal guests or external users. Supported values are:  `b2bCollaborationGuest`, `b2bCollaborationMember`, `b2bDirectConnectUser`, `internalGuest`, `OtherExternalUser`, `serviceProvider` and `unknownFutureValue`. |
```

2022-08-19 22:15 UTC, Danielabom commented on api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md
> +| externalTenants | conditionalAccessExternalTenants | The tenant ids of selected types of external users. It could be either all b2b tenants, or a collection of tenant ids. External tenants can be s
```suggestion
| externalTenants | conditionalAccessExternalTenants | The tenant ids of the selected types of external users. It could be either all b2b tenant, or a collection of tenant ids. External tenants can be specified only when `guestOrExternalUserTypes` is not null or an empty string. |
```

2022-08-19 22:24 UTC, Danielabom commented on api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md
> +| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes collection | Flagged enum of the types of internal guests or external users. Supported values include `b2bCollaborationGuest`, `
Line 22: The api.md file does not mention the member "service provider", but it is mentioned here.
Line 22. The api.md file does mention the member "none", but it is not mentioned here.

2022-08-22 00:37 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "ApiChange": "Enumeration",
The ApiChange value should be: Enum type.

2022-08-22 00:39 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the [conditionalAccessExternalTenantsMembershipKind](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
instead of resource. It should be "enumeration".

2022-08-22 00:43 UTC, Danielabom requested changes
@SanDeo-MSFT, thank you for working on this PR. Please review my comments. Thanks

2022-08-24 16:18 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the [conditionalAccessExternalTenantsMembershipKind](https://docs.microsoft.com/en-us/?view=graph-rest-beta) resource",
This is a Graph studio issue, please replace with my suggestion. Thanks.
```suggestion
			  "Description": "Added the **conditionalAccessExternalTenantsMembershipKind** enumeration.",
```

2022-08-24 22:59 UTC, Danielabom commented on api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md
> +---
Global comment: All tha files should be named in lower cases.

2022-09-02 18:39 UTC, opbld32 commented
Docs Build status updates of commit _[d9b3bb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9b3bb0a6d5138b5b9c700a403974f173acf806b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021836558817-18080/BuildReport?accessString=7229c5b170bc4146c892331549fc1a0c27b764800db5b25109fbccf28a023c21).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 18:43 UTC, opbld34 commented
Docs Build status updates of commit _[12ddfaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12ddfaa08118b561a05bfbb67ce274222af8eafa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021841111134-18080/BuildReport?accessString=5df4869d03c6bbf32352970492dd6b15edab46b9759ad3e6c1f5abe0aa2e1aa6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 18:46 UTC, SanDeo-MSFT commented on api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md
> +| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes collection | Flagged enum of the types of internal guests or external users. Supported values include `b2bCollaborationGuest`, `
Service provider is included in the API md.

2022-09-02 18:50 UTC, opbld30 commented
Docs Build status updates of commit _[670770b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/670770b18a5819610251d33606d95f19c11ee7f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021848314902-18080/BuildReport?accessString=38280bd7e1d1ee79c27c4f9b46475a0ad933f6557cd4b1d62807c93a173cbe82).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 18:53 UTC, opbld33 commented
Docs Build status updates of commit _[5fe0c63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fe0c63231e3de3b3859508d4fa8bae937e4590b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessEnumeratedExternalTenants.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalAccessGuestsOrExternalUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalAccessExternalTenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalAccessExternalTenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021849357480-18080/BuildReport?accessString=ef0ae136bf2674a42d03f50359af28fad1b4c43f2cb1e7cdd4e91cad52e211c3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 18:55 UTC, opbld34 commented
Docs Build status updates of commit _[c828cb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c828cb89f4e69878b1a400f33b8ad78c0a5e1f9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021852370274-18080/BuildReport?accessString=0977512a692dc422494fe015fcc3e0677fb5bbe5be37d08965d26264b43e2327).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 18:58 UTC, opbld32 commented
Docs Build status updates of commit _[6694d64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6694d649b306dd0b4607d9ad61a7fb4df8db03f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021856451033-18080/BuildReport?accessString=689744e1848ed2841948f7d4f16978347f02ac3180e6bb712ff294deae5650ec).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 19:12 UTC, opbld30 commented
Docs Build status updates of commit _[fab6663](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fab66632d55e4811fdf9f5c4f8251f71466ca128)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/includes/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/includes/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021910359430-18080/BuildReport?accessString=492b270edfa1dfdc0515d65849e056a067b99638d3635afe429ff9b353eb6205).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 19:15 UTC, opbld31 commented
Docs Build status updates of commit _[18fb54d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18fb54dee71d5637a40adf56dfe6fff40494544c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021910494000-18080/BuildReport?accessString=c0eef4d5e04e5d8950ea28c271c8c50d9a3676f6fe78f9173af242e80ccfc940).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 19:18 UTC, opbld30 commented
Docs Build status updates of commit _[39ca5b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39ca5b220380232d9ac63f2e31db11535cef7e6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021913454208-18080/BuildReport?accessString=bd3b6f74368666bdc190139e91f7e52b3a1ca705c18a47e1e52592a0fce1f88c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 19:22 UTC, opbld33 commented
Docs Build status updates of commit _[30cc50c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30cc50c57376f156751a337ad0dfd2b6c50a735f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021920081056-18080/BuildReport?accessString=9381acd809969ebc07fe66d67e03383836a4a05e75a5947facf3fbaeab997d4a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 19:24 UTC, opbld30 commented
Docs Build status updates of commit _[9caad68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9caad683a3f029aa1853b3909815f45b80986aa3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021921392186-18080/BuildReport?accessString=7a445a8135f47d2c084d61ae7ed4d5b51f22a329b1dfbf298b5f5a1a40d0583f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 23:07 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md
> +description: "Represents list of external tenants in the policy scope."
```suggestion
description: "Represents a list of external tenants in the policy scope."
```

2022-09-07 23:08 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md
> +Represents list of external tenants in the policy scope.
```suggestion
Represents a list of external tenants in the policy scope.
```

2022-09-07 23:09 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md
> +| members | String collection | This represents a collection of tenant ids in scope of Conditional Access for guest and external users policy targeting. |
```suggestion
| members | String collection | Rrepresents a collection of tenant ids in scope of Conditional Access for guest and external users policy targeting. |
```

2022-09-07 23:32 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the [excludeGuestsOrExternalUsers](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessUsers?view=graph-rest-beta) resource",
Global comment for properties: Please review the format of the description. Follow example 2 from this topic: [Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2022-09-07 23:32 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the [includeGuestsOrExternalUsers](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessUsers?view=graph-rest-beta) resource",
Global comment for properties: Please review the format of the description. Follow example 2 from this topic: [Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2022-09-07 23:39 UTC, Danielabom requested changes
Hi @SanDeo-MSFT, thank you for working on this PR. Please review my comments and accept my suggestions if you agree with them.

2022-09-12 21:45 UTC, Danielabom commented
Hi @SanDeo-MSFT , just wanted to follow up on this PR. Let me know if you have any questions. Thanks.

2022-09-12 22:19 UTC, opbld34 commented
Docs Build status updates of commit _[fe82226](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe8222656934e142f3c8ed2d2fdcf2aa9617e7f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209122217186759-18080/BuildReport?accessString=c7d136a7c3450aef553645acbcc698b70b6bae359750c8fe645c6d60c9fd2078).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 22:22 UTC, opbld33 commented
Docs Build status updates of commit _[6f162d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f162d27b4960b81986619d50d8b04f17893a69d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209122218404901-18080/BuildReport?accessString=1dd3da5ab4539d74468808a55c96b05ab1e8e666860e3bee9db291a29070a830).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 22:33 UTC, opbld34 commented
Docs Build status updates of commit _[1272473](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12724730cb1deb3295906a9711102835d81ed47a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209122231026041-18080/BuildReport?accessString=e6e13053d9267584925403cef5310939c9c9fc4642c5504a2cdc8d031ef9bcf4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 22:35 UTC, opbld31 commented
Docs Build status updates of commit _[eb390fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb390fb42dfbb7fd41f920b484472133b0a6f326)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209122231378470-18080/BuildReport?accessString=282ac927d4e7ceb905c5302ec90b960a8b34b13b1acea2f2f60d2e993261e011).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 20:36 UTC, opbld33 commented
Docs Build status updates of commit _[7e78138](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e781382ed1b2f701dcbcb6d80e65292eff7301b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209132034551331-18080/BuildReport?accessString=a1c0dd7ed46597128829dc68143da23575ec3f2248f6a7eccf2c1068d3599298).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 22:59 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **excludeGuestsOrExternalUsers** resource type.",
Please use the same format for the other property added to the changelog:
```suggestion
			  "Description": "Added the **excludeGuestsOrExternalUsers** property to the [conditionalaccessusers](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta) resource type.",
```

2022-09-13 23:10 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessGuestsOrExternalUsers** resource type.",
```suggestion
			  "Description": "Added the [conditionalAccessGuestsOrExternalUsers](Added the [cloudPC](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessGuestsOrExternalUsers?view=graph-rest-beta) resource).",
```

2022-09-13 23:18 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "ApiChange": "Enumeration",
@SanDeo-MSFT, please review the [https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog) on how to document members of an enumeration.

2022-09-13 23:19 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "ApiChange": "Enumeration",
@SanDeo-MSFT, please review the https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog on how to document members of an enumeration.

2022-09-13 23:22 UTC, Danielabom reviewed
Dear @SanDeo-MSFT, I need to check some things with @FaithOmbongi before completing the review. I'll keep you posted.

2022-09-15 03:11 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessguestsorexternalusers.md
> +| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes collection | Enum flag representing the types of internal guests or external users. Supported values are: `b2bCollaborationGuest
@SanDeo-MSFT, please **add the enums to the enums.md file.** 
Changes I've made:
- The CSDL file does not mention that this is a collection. It is a flagged enum. Change applied.
- The members in the CSDL file are different from the ones listed here. Change applied. 
```suggestion
| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes | Represents internal guests or external user types. This is a multi-value extended property. Supported values are: `none`, `internalGuest`, `b2bCollaborationGuest`, `b2bCollaborationMember`, `b2bDirectConnectUser`, `otherExternalUser`, `serviceProvider`, and `unknownFutureValue`. |
```

2022-09-15 03:43 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessexternaltenants.md
> +## JSON representation
Please update the JSON representation. Since this is an enum, the return type should be a string.

2022-09-15 03:43 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessguestsorexternalusers.md
> +## JSON representation
Please update the JSON representation. Since this is an enum, the return type should be a string.

2022-09-15 03:44 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessexternaltenants.md
> +| membershipKind |conditionalAccessExternalTenantsMembershipKind collection | Represents the membership kind. Supported values are: `all`, [`enumerated`](conditionalaccessenumeratedexternaltenants.md
```suggestion
| membershipKind |conditionalAccessExternalTenantsMembershipKind | Represents the membership kind. Supported values are: `all`, [`enumerated`](conditionalaccessenumeratedexternaltenants.md) and `unknownFutureValue`. |
```

2022-09-15 03:53 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessexternaltenants.md
> +Represents external tenants in the policy scope.
@SanDeo-MSFT:
- This is an abstract type. 
- Please consider updating the description to example below: 
An abstract type that represents external tenants in the policy scope. This abstract type is inherited by conditionalAccessAllExternalTenants. 
- Please add the file conditionalAccessAllExternalTenants.

2022-09-15 04:13 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessEnumeratedExternalTenants** resource type.",
Global comment, please update the description of each resource accordingly.

2022-09-15 04:13 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessExternalTenants** resource type.",
Global comment, please update the description of each resource accordingly.

2022-09-15 04:20 UTC, Danielabom requested changes
Hi @SanDeo-MSFT . Please approve/decline my suggestions and review my comments. Feel free to reach out if you have any questions.

2022-09-20 18:13 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessExternalTenantsMembershipKind** enumeration type.",
```suggestion
			  "Description": "Added the **conditionalAccessExternalTenantsMembershipKind** enumeration.",
```

2022-09-20 18:16 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessGuestOrExternalUserTypes** enumeration type.",
```suggestion
			  "Description": "Added the **conditionalAccessGuestOrExternalUserTypes** enumeration.",
```

2022-09-20 18:23 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessAllExternalTenants** resource type.",
```suggestion
			  "Description": "Added the [conditionalAccessAllExternalTenants] (https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessAllExternalTenants?view=graph-rest-beta) resource.",
```

2022-09-20 18:29 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessEnumeratedExternalTenants** resource type.",
```suggestion
			  "Description": "Added the [conditionalAccessEnumeratedExternalTenants] (https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessEnumeratedExternalTenants?view=graph-rest-beta) resource.",
```

2022-09-20 18:30 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **conditionalAccessExternalTenants** resource type.",
```suggestion
			  "Description": "Added the [conditionalAccessExternalTenants] (https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessExternalTenants?view=graph-rest-beta)  resource.",
```

2022-09-20 19:49 UTC, Danielabom commented on changelog/Microsoft.IdentityProtectionServices.json
> +			  "Description": "Added the **includeGuestsOrExternalUsers** resource type",
```suggestion
			  "Description": "Added the **includeGuestsOrExternalUsers** property to the [conditionalaccessusers](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta) resource. ",
```

2022-09-20 21:12 UTC, opbld30 commented
Docs Build status updates of commit _[1306516](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13065168d10c9575e7d44a3470ae605d5d9c2bb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202108004765-18080/BuildReport?accessString=bd80f8c19e24fb37ea4ef4706861291356f480b9720390086a0226e6b112394c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 21:15 UTC, opbld34 commented
Docs Build status updates of commit _[af5b0cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af5b0cccc5cd5cd40223a69d91ec29ba98590c27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202110247189-18080/BuildReport?accessString=fb70c71874f17a5a3f92c0476086bcde16e360cacb032260b46d45041f79f509).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 21:26 UTC, opbld32 commented
Docs Build status updates of commit _[c249122](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2491225094a5b98c3a7a2a0b452e01e3c95872f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-d08ca4e160096a2a81468fea219ca52d-3f6ffbbf)
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-71128b0c0aa088b0ed462f7f56512acf-3f6ffbbf)
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="d08ca4e160096a2a81468fea219ca52d-3f6ffbbf"></a>
### [api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md)
 - **Line 16, Column 15**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'conditonalaccessexternaltenants.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents external tenants in the policy scope.' is duplicated in 'beta/resources/conditionalaccessallexternaltenants.md(3,14)', 'beta/resources/conditionalaccessexternaltenants.md(3,14)'.`````

<a id="71128b0c0aa088b0ed462f7f56512acf-3f6ffbbf"></a>
### [api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents external tenants in the policy scope.' is duplicated in 'beta/resources/conditionalaccessallexternaltenants.md(3,14)', 'beta/resources/conditionalaccessexternaltenants.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202123347154-18080/BuildReport?accessString=1b095a3d61d97ec9c7db0b2082032089cfab55ff2fb7f220eca3cacb48ae2099).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 21:28 UTC, opbld30 commented
Docs Build status updates of commit _[5e91679](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e9167905e60cdabbd85709311271a217916d55b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-d08ca4e160096a2a81468fea219ca52d-0e89bb32)
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-71128b0c0aa088b0ed462f7f56512acf-0e89bb32)
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="d08ca4e160096a2a81468fea219ca52d-0e89bb32"></a>
### [api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md)
 - **Line 16, Column 15**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'conditonalaccessexternaltenants.md'.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents external tenants in the policy scope.' is duplicated in 'beta/resources/conditionalaccessallexternaltenants.md(3,14)', 'beta/resources/conditionalaccessexternaltenants.md(3,14)'.`````

<a id="71128b0c0aa088b0ed462f7f56512acf-0e89bb32"></a>
### [api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents external tenants in the policy scope.' is duplicated in 'beta/resources/conditionalaccessallexternaltenants.md(3,14)', 'beta/resources/conditionalaccessexternaltenants.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202124333324-18080/BuildReport?accessString=3bec874f18f9c1b591ae81bb435ddc1f9ecfb89b2d45c548cb2f07433ade9cbb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 21:32 UTC, opbld31 commented
Docs Build status updates of commit _[bc021f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc021f750b78216a3532101ac4f3729b66c0c925)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-d08ca4e160096a2a81468fea219ca52d-af71cb37)
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) | [Details](#user-content-71128b0c0aa088b0ed462f7f56512acf-af71cb37)
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="d08ca4e160096a2a81468fea219ca52d-af71cb37"></a>
### [api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents external tenants in the policy scope.' is duplicated in 'beta/resources/conditionalaccessallexternaltenants.md(3,14)', 'beta/resources/conditionalaccessexternaltenants.md(3,14)'.`````

<a id="71128b0c0aa088b0ed462f7f56512acf-af71cb37"></a>
### [api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md)
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents external tenants in the policy scope.' is duplicated in 'beta/resources/conditionalaccessallexternaltenants.md(3,14)', 'beta/resources/conditionalaccessexternaltenants.md(3,14)'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202129344840-18080/BuildReport?accessString=d51950bb33e1bf87c4c705f0a9a607f7e8597edeb89075b8d52abc3dae6b3a88).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 21:53 UTC, opbld32 commented
Docs Build status updates of commit _[62cc3f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62cc3f42a0bdbdfefac64116a45be9bca4b3f49e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202151298680-18080/BuildReport?accessString=1806984a213feb66a0287b3331bd470197a4b861c4e235f2fd082822efeb3f44).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[d67497f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d67497f712799e8091cdafaf21808a0dbc2ddda8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202154059761-18080/BuildReport?accessString=31b5f8d80002d566901cfa82878d135cac94ff9aa2d2ccb5e42176dca59c0c29).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 22:06 UTC, opbld30 commented
Docs Build status updates of commit _[264dbd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/264dbd0b858c68d7cea0a884a3be1f0c4b2239d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209202204274610-18080/BuildReport?accessString=604911763651b5fdd57c4e909f71928e544aab0e97dc8c098148bf23f1b81f6d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 17:01 UTC, opbld31 commented
Docs Build status updates of commit _[fbd1d81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbd1d81b5affe85f9d0d45d5a91b4b990bb81fd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209211656265412-18080/BuildReport?accessString=d826fc14e079515262611b5b6dd60ecfb9a89cd18c2c8a120bbfe577113c7231).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 15:03 UTC, opbld34 commented
Docs Build status updates of commit _[e4ad03f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4ad03fbf04259892a122e9b38b766450b55df77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221459357640-18080/BuildReport?accessString=3f0eeb3118dca0e79d3ab06fdec8499a947e4f1fd704631536cb046c40d1589e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 15:07 UTC, opbld34 commented
Docs Build status updates of commit _[ad4e55f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad4e55f5702001d65cd590b0b28ab222949055b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221502551549-18080/BuildReport?accessString=4ee80f86ce28db42e6420bdf9dfcb9d50d5c28c591da44671d805e4fa8c7b18b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 15:10 UTC, opbld33 commented
Docs Build status updates of commit _[3ffdfd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ffdfd0a24e0ead1912112e5ee9bac9a3f34e208)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221507206588-18080/BuildReport?accessString=3cf00a3b0a9c1c5b9f9f8a5ceee89979277e1410e61ad054de4ac559875944fc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 15:14 UTC, opbld32 commented
Docs Build status updates of commit _[0b7f5b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b7f5b14c6915998da6c336e2aa7b48e42fbfe36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209221507267042-18080/BuildReport?accessString=084fc14a70301efe067e0fecc35da725fd53b03320fd330cb85c67d71e5ae400).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 23:49 UTC, opbld32 commented
Docs Build status updates of commit _[7dda97d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dda97df0669dfa8dee997ed85a59c4ad530a905)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209232347000992-18080/BuildReport?accessString=30541a59e4e206cedb44c5c1f0fa1c33006260e537ce0e60d6133c640ea79748).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-24 00:01 UTC, opbld31 commented
Docs Build status updates of commit _[cb5315b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb5315bd298817cbb6d851502f79453d43908cb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209232357153930-18080/BuildReport?accessString=99aa3071058d75fb07ea489d52ec2287f4f48401217328424f7e1f863034881b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-24 00:09 UTC, opbld32 commented
Docs Build status updates of commit _[f876cd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f876cd293fa9af1e95595d5e2402a0e307433e2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209240006127843-18080/BuildReport?accessString=027a6b9a800ffaae7add5ab30019aa9d5faf9e695213b232bb3ff21d164810e7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 16:45 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessexternaltenants.md
> +Represents external tenants in the policy scope.
An abstract type that represents external tenants in the policy scope. This abstract type is inherited by conditionalAccessAllExternalTenants and conditionalAccessEnumeratedExternalTenants.

2022-09-26 16:46 UTC, Danielabom commented on api-reference/beta/resources/conditionalaccessexternaltenants.md
> +Represents external tenants in the policy scope.
```suggestion
An abstract type that represents external tenants in the policy scope. This abstract type is inherited by conditionalAccessAllExternalTenants and conditionalAccessEnumeratedExternalTenants.
```

2022-09-26 16:49 UTC, opbld34 commented
Docs Build status updates of commit _[385c420](https://github.com/microsoftgraph/microsoft-graph-docs/commits/385c420e21e4d5616c463afe3deb61288f00dc20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209261646372197-18080/BuildReport?accessString=5ec93da993629c935e6656da135b903f9940c7188d6f1b04f67641381f69455f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 07:38 UTC, opbld32 commented
Learn Build status updates of commit _[5e8b4ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e8b4ad3cacfa230cb5c43bc43316f5bcfbe8f02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209280726494405-18080/BuildReport?accessString=3081cdf396badfb5f5eb18f8420b530a285e4c55f503d98375de21fe5714e40e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-28 08:06 UTC, opbld34 commented
Learn Build status updates of commit _[91c3ea2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91c3ea258dfdcdd81e27ce5ee003f76b16ca30ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209280802126496-18080/BuildReport?accessString=83908094a1c3a75184cf5cf6ff879a3d3421ed33a396d8b658ca8b84c66b1606).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-28 08:23 UTC, opbld32 commented
Learn Build status updates of commit _[94abb97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94abb976129167c38e2d3314493c7c5ac777c3bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209280820184544-18080/BuildReport?accessString=7f618008181b86924f5031db626093dc495692383e8ea7e00d2d0f02f4c097d6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-28 15:22 UTC, millicentachieng commented on api-reference/beta/resources/conditionalaccessusers.md
> +  "@odata.type": "microsoft.graph.conditionalAccessGuestsOrExternalUsers",
Only one type is allowed. In this case, remove line 52.

2022-09-28 15:22 UTC, millicentachieng commented on api-reference/beta/resources/conditionalaccessallexternaltenants.md
> +| membershipKind |conditionalAccessExternalTenantsMembershipKind collection | Represents the membership kind. Supported values are: `all`, [`enumerated`](conditionalaccessenumeratedexternaltenants.md
`conditionalAccessExternalTenantsMembershipKind` needs to be defined in the `enums.md` file.

2022-09-28 15:22 UTC, millicentachieng commented on api-reference/beta/resources/conditionalaccessguestsorexternalusers.md
> +| guestOrExternalUserTypes | conditionalAccessGuestOrExternalUserTypes | Represents internal guests or external user types. This is a multi-valued property. Supported values are: `b2bCollaborationGue
`conditionalAccessGuestOrExternalUserTypes` needs to be defined in the `enums.md` file

2022-09-28 21:50 UTC, opbld30 commented
Learn Build status updates of commit _[0e734a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e734a7130106910acbd6d66dee94f62e59ffc4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209282147085139-18080/BuildReport?accessString=98044c1a5c2dc9a8197860cf170b8e7d894365ffa2f729dfb9b94f6d8f2ad348).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 04:22 UTC, opbld34 commented
Learn Build status updates of commit _[66a7500](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66a750086376ff15dacdbb72cc528ae67d8c15cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessallexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessallexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessallexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessenumeratedexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessenumeratedexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessexternaltenants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessexternaltenants.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessguestsorexternalusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessguestsorexternalusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/conditionalaccessusers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessusers?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18080) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanDeo-MSFT-patch-5-1/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209290418213935-18080/BuildReport?accessString=0f8e7bed37dd5a0975ae9eeb604c094544defb46160cfd4269a92649a8d2a316).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-09-29 04:33 UTC, merged