GA teamworkTag
microsoftgraph/microsoft-graph-docs pull request #18085
Opened 2022-08-17 20:28 UTC by jessiechan27

Taking teamworkTag resource and API's from beta to GA. All changes are existing in beta.
previous beta PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/11071

2022-08-17 20:30 UTC, opbld32 commented
Docs Build status updates of commit _[0445f69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0445f6952669bf85e50e52e9421197180e69579a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208172028195065-18085/BuildReport?accessString=d70a6bbd6757cd7bc558afc02b13fdf372b64badd088949a889bbf72dd26b373).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 21:15 UTC, opbld34 commented
Docs Build status updates of commit _[49853f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49853f781a555dd4a6d50302e06cadc1ba3ee61e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208172113465358-18085/BuildReport?accessString=5cec8319a0295c824b7c41b26c19661fe7be2e4c95ac46920e05d282cb654b2a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db4 [...]

2022-08-17 21:34 UTC, opbld31 commented
Docs Build status updates of commit _[47fcaac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47fcaac3bb0dd8ed3c6717400365f019e7af8b6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-f5ec270ca33c8191f6c6bd6c59774c9d-25906741)
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-4fa374cf60f8e5a63f3d3adad7ba1212-25906741)
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-e0dcb857b87ccc63c8a260833ba9af37-25906741)
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-5e2a206c0c6255720b3c6dc3a07f11fa-25906741)
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-bf8d400396385c6875f3c471e6742f61-25906741)
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-3cafa4cc75d462ad66fb69544fd29c20-25906741)
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-2b8a29bf7784a749b6f21edc3e0aa722-25906741)
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-59108766b209bdfed6b947b28f4077ca-25906741)
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-b7e10659674a46382fe63225c0a0b11f-25906741)
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-0dc14476039f775fc5296a4c79b72955-25906741)
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-01d356d0933c6391cdefa221fcfc95a0-25906741)
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-6ed1a9f9c6f23a8324671ca789c0a284-25906741)
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-8c3e22246f7a3ec550b6fab6a21a4ba9-25906741)
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-486ed68d734b05c8da26ea1a8724db9b-25906741)
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-1f434b7107d428d271e319c879b74b66-25906741)
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-61c8b3e39727bab386222c52c3611558-25906741)
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-bf4ba26b9fe0a0b14232e4b45e168051-25906741)
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-664cf767641156a9907a2d3feb7a5613-25906741)
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-c4433ef8935c25af07b0dc7ff4b91b2d-25906741 [...]

2022-08-17 22:28 UTC, opbld32 commented
Docs Build status updates of commit _[7f4b0b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f4b0b9e228af1d18126dc0d9b937fa892ca3695)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-f5ec270ca33c8191f6c6bd6c59774c9d-ca9b658b)
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-4fa374cf60f8e5a63f3d3adad7ba1212-ca9b658b)
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-e0dcb857b87ccc63c8a260833ba9af37-ca9b658b)
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-5e2a206c0c6255720b3c6dc3a07f11fa-ca9b658b)
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-bf8d400396385c6875f3c471e6742f61-ca9b658b)
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-3cafa4cc75d462ad66fb69544fd29c20-ca9b658b)
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-2b8a29bf7784a749b6f21edc3e0aa722-ca9b658b)
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-59108766b209bdfed6b947b28f4077ca-ca9b658b)
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-b7e10659674a46382fe63225c0a0b11f-ca9b658b)
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-0dc14476039f775fc5296a4c79b72955-ca9b658b)
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-01d356d0933c6391cdefa221fcfc95a0-ca9b658b)
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-6ed1a9f9c6f23a8324671ca789c0a284-ca9b658b)
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-8c3e22246f7a3ec550b6fab6a21a4ba9-ca9b658b)
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-486ed68d734b05c8da26ea1a8724db9b-ca9b658b)
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-1f434b7107d428d271e319c879b74b66-ca9b658b)
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-61c8b3e39727bab386222c52c3611558-ca9b658b)
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-bf4ba26b9fe0a0b14232e4b45e168051-ca9b658b)
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-664cf767641156a9907a2d3feb7a5613-ca9b658b)
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-c4433ef8935c25af07b0dc7ff4b91b2d-ca9b658b [...]

2022-08-18 17:29 UTC, seankeating approved these changes
Thanks, looks good.

2022-08-18 17:30 UTC, RamjotSingh requested changes

2022-08-18 17:30 UTC, RamjotSingh commented on api-reference/beta/api/teamworktagmember-get.md
> -# [C#](#tab/csharp)
We can retain examples right? since we didnt really change them.

2022-08-18 17:30 UTC, RamjotSingh commented on api-reference/v1.0/resources/teamworktagmember.md
> +  "userID": "String"
Id and not ID, everywhere.

2022-08-18 19:25 UTC, opbld30 commented
Docs Build status updates of commit _[84a7968](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84a7968d4cca7962e3f316267b3ea7107af60511)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md [...]

2022-08-18 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[0532fd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0532fd17780ba800219cf449f0024c5610e252cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md [...]

2022-08-18 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[a00c78c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a00c78c23510467452bb00a46efb4a2c14c5d068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md [...]

2022-08-18 19:40 UTC, opbld31 commented
Docs Build status updates of commit _[1c72394](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c723948eae5890b8028857c78f0a6ac8505a3e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md [...]

2022-08-18 22:12 UTC, RamjotSingh approved these changes

2022-08-22 22:05 UTC, JarbasHorst commented
Hello @jessiechan27, I started the content review work for your PR and left some comments. Please, take a look when you will have time.

2022-08-23 01:57 UTC, opbld32 commented
Docs Build status updates of commit _[e6daa84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6daa84bca37a00fccda3d6b16f97f995364bcd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md] [...]

2022-08-23 22:34 UTC, JarbasHorst commented
Hi @jessiechan27, I continued with the content review work and left additional comments. Please, take a look when you will have time and address the comments, so we can continue with the content review work.

Also, to avoid merge conflicts, please merge PR [18159](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18159) into your branch to include my fixes and before addressing my new comments.

2022-08-23 23:33 UTC, opbld32 commented
Docs Build status updates of commit _[da4c084](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da4c0841499715dc02030cc5fe372f1e9ad776df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teams-api-overview.md] [...]

2022-08-23 23:35 UTC, opbld30 commented
Docs Build status updates of commit _[e3b02c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3b02c85c126008d17c1db04e13bc7fedec99542)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) | [Details](#user-content-0dc14476039f775fc5296a4c79b72955-df3ede7a)
[api-reference/v1.0/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) | [Details](#user-content-7f24deb87e63cb80c6ccf7818375555b-df3ede7a)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkta [...]

2022-08-24 16:56 UTC, seankeating commented on api-reference/v1.0/api/teamworktag-post.md
> +|:---|:---|:---|
This is a limitation in the request.  A max of 25 members can be added in a single tag creation request.

2022-08-24 22:41 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [18159](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18159) into this branch to include my final edits.

2022-08-25 02:39 UTC, opbld31 commented
Docs Build status updates of commit _[5a1b209](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a1b209c73c5cc0803441f19fc53934c22e2274e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-32852d6a)

<a id="32852d6a"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 5a1b209c73c5cc0803441f19fc53934c22e2274e in branch jecha/GA-teamworkTag of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 4b0727893c848c26243ee0f3e4426b459632e9de). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208250238475337-18085/BuildReport?accessString=36ce4dff567c64d7d0a1c1f9596c090c33022b54407f9fe8f156ea5e410ec254).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 05:18 UTC, opbld31 commented
Docs Build status updates of commit _[b59f534](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b59f534ffeec5568b658bb52e624754332796b15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](h [...]

2022-08-25 05:28 UTC, opbld31 commented
Docs Build status updates of commit _[6d46d34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d46d348cdff2f0b6256e2941aa4e72c7bba2bac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](h [...]

2022-10-04 21:18 UTC, opbld30 commented
Learn Build status updates of commit _[c5d3b01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5d3b01e1b0a3946bca49c24df565d14df2759ee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ab88e52d)

<a id="ab88e52d"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit c5d3b01e1b0a3946bca49c24df565d14df2759ee in branch jecha/GA-teamworkTag of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 3f1d533511c9de70511a80d49e47c6b2869b019e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210042117590770-18085/BuildReport?accessString=b82f96590f8700a311006405eedbd96d8ab8280ec94fdbfc43b071bf6d6ababb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 12:46 UTC, opbld31 commented
Learn Build status updates of commit _[f52f25d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f52f25d9c4061aa5c77a3f117953f9081f1747ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2eac6ccb)

<a id="2eac6ccb"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit f52f25d9c4061aa5c77a3f117953f9081f1747ec in branch jecha/GA-teamworkTag of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 3f1d533511c9de70511a80d49e47c6b2869b019e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210061245561899-18085/BuildReport?accessString=328f3c06184f3c7d7f923dfc81f63a436de223b6dac2f99237d1dfdc393b79d9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 12:58 UTC, opbld32 commented
Learn Build status updates of commit _[0f7c25f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f7c25f711a5359a32bf203e3340c1488b80175f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources [...]

2022-10-06 13:07 UTC, opbld32 commented
Learn Build status updates of commit _[d5f7a9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5f7a9c0cf4708a5812c067280b0b724766361fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https:/ [...]

2022-10-06 13:12 UTC, opbld31 commented
Learn Build status updates of commit _[3b9f7d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b9f7d872b154c8c52f3b4c4529c2b3a0ebd7c7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https:/ [...]

2022-10-06 19:56 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [18770](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18770) into this branch to include my final edits.

2022-10-07 03:15 UTC, opbld30 commented
Learn Build status updates of commit _[4e45b76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e45b763b20fee3bfa09453ef939c22350470769)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/t [...]

2022-10-07 03:20 UTC, Lauragra commented on api-reference/beta/api/teamworktag-get.md
> -## Optional query parameters
Why did we delete this section? It's standard for GET/List operation topics. If the method doesn't support query parameters, we should state that in this section instead of deleting the section.

2022-10-07 03:21 UTC, Lauragra commented on api-reference/beta/api/teamworktagmember-get.md
> -## Optional query parameters
Why are we deleting this? If query parameters aren't supported, we should state that here.

2022-10-07 17:06 UTC, opbld31 commented
Learn Build status updates of commit _[6efd3ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6efd3ed138b6a1b6c5f464f54eacc1c57aec6199)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/t [...]

2022-10-07 17:08 UTC, opbld33 commented
Learn Build status updates of commit _[0d58513](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d58513f170a6c4b272ca8209637b36ceec3b927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/t [...]

2022-10-08 00:57 UTC, Lauragra approved these changes

2022-10-08 00:59 UTC, opbld30 commented
Learn Build status updates of commit _[8d60d1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d60d1c41d45160c843b68bed1355167daad86c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-18085) (graph-rest-beta) |
[api-reference/v1.0/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktagmember-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktagmember-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktagmember-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/GA-teamworkTag/api-reference/v1.0/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0&branch=pr-en-us-18085) (>= graph-rest-1.0) |
[api-reference/v1.0/api/t [...]

2022-10-08 01:12 UTC, merged