Update defaultuserrolepermissions.md
microsoftgraph/microsoft-graph-docs pull request #18099
Opened 2022-08-19 01:11 UTC by purishd

Updating the property and Json representation for Tenant creation lockdown feature

2022-08-19 01:13 UTC, opbld32 commented
Docs Build status updates of commit _[628fc25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/628fc2571f2c0b4b66a15e298d523f6f944c76c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/defaultuserrolepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/purishd-patch-1/api-reference/beta/resources/defaultuserrolepermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultuserrolepermissions?view=graph-rest-beta&branch=pr-en-us-18099) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208190111063690-18099/BuildReport?accessString=12448af9b0462ec9b702c7d1f580e6191c431eaa9a460078ad9a32f928973f8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 02:50 UTC, purishd commented
#label:"ready for content review"

2022-08-30 15:37 UTC, isvargasmsft commented on api-reference/beta/resources/defaultuserrolepermissions.md
> +| allowedToCreateTenants | Boolean | Indicates whether the default user role can create tenants. |
Missing in this PR: Changelog entry for the new property.

2022-08-30 15:38 UTC, isvargasmsft commented on api-reference/beta/resources/defaultuserrolepermissions.md
GENERAL: Is DougKirschner still the main point of contact for this article?

2022-08-30 15:41 UTC, isvargasmsft requested changes
Hello @purishd, 

Thank you very much for your work in this PR. 

I noticed you are on vacations, so I am just leaving a couple of comments by now. Please share with me the review documents on the side once you are back.

Kind regards, 

Isaac

2022-09-29 01:17 UTC, opbld34 commented
Learn Build status updates of commit _[ecc86cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecc86cc9762aa1deee57731187d7543867af6e3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/defaultuserrolepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/purishd-patch-1/api-reference/beta/resources/defaultuserrolepermissions.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/defaultuserrolepermissions?view=graph-rest-beta&branch=pr-en-us-18099) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209290114418890-18099/BuildReport?accessString=1b17e6111af825e46a0bb66e169dde15f2b2b8a14234fab40e9e24b5c7f1aac9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 15:23 UTC, isvargasmsft commented
Awating for review files (CSDL PR for beta endpoint).

2022-11-29 06:12 UTC, purishd commented
@isvargasmsft I'm unsure of what changes have been requested. Can you please ping me on Teams about what I need to change on this?

2022-11-29 14:16 UTC, isvargasmsft commented on api-reference/beta/resources/defaultuserrolepermissions.md
@purishd FYI

2023-02-04 15:01 UTC, closed without merging