GA pinned and pinned apis and event messages
microsoftgraph/microsoft-graph-docs pull request #18119
Opened 2022-08-22 04:44 UTC by sumanac

2022-08-22 04:46 UTC, opbld32 commented
Docs Build status updates of commit _[bdd58f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdd58f3adc1f993a16976193f16094c2b976a621)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :x:Error | | [Details](#user-content-34d57f52bdba8883907557a5f4a79f54-7323f6f6)

<a id="34d57f52bdba8883907557a5f4a79f54-7323f6f6"></a>
### [api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md)
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/list-pinnedchatmessageinfo-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/list-pinnedchatmessageinfo-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/list-pinnedchatmessageinfo-java-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/list-pinnedchatmessageinfo-go-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/list-pinnedchatmessageinfo-powershell-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/list-pinnedchatmessageinfo-php-snippets.md'.`````
 - **Line 129, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208220444427273-18119/BuildReport?accessString=c9a46eab5dc7dc4d691a8394a5bc38a015623b8b73055f086053c6a9ea8c02ec).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 20:42 UTC, opbld32 commented
Docs Build status updates of commit _[59fbac2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59fbac20ef2efe9c97e872563d245f678f4ce4bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) | [Details](#user-content-34d57f52bdba8883907557a5f4a79f54-28628537)
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |

<a id="34d57f52bdba8883907557a5f4a79f54-28628537"></a>
### [api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md)
 - **Line 57, Column 1**: **[Warning: invalid-tab-group - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208292037414985-18119/BuildReport?accessString=f287ca04eda450c02b759be0c3925424ecfad5e73ad7aa1cd216d1e505374b1b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 00:03 UTC, opbld34 commented
Docs Build status updates of commit _[ed06b66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed06b66b726e6af0d59b73982762defabab6d818)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208300000543260-18119/BuildReport?accessString=54de58edfe75e899dde71ac83518d28c4cbe2c3e2a01fc4078109279c5a46b84).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 16:26 UTC, RamjotSingh requested changes

2022-08-30 16:26 UTC, RamjotSingh commented on api-reference/v1.0/toc.yml
> +          href: api/chat-delete-pinnedmessages.md
Let's add these under chat and under chat message as well

2022-08-30 16:26 UTC, RamjotSingh commented on api-reference/v1.0/toc.yml
> +          href: api/chat-delete-pinnedmessages.md
Do the same for beta as well

2022-08-30 20:13 UTC, opbld34 commented
Docs Build status updates of commit _[1c1ab2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c1ab2b815f8bff4f65e11432f1ba89682ef6b7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208302009291902-18119/BuildReport?accessString=e784ce56a1d0c112f5f5ccc9a136724493d468fa26803970244a96e6836618e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 20:17 UTC, opbld34 commented
Docs Build status updates of commit _[8570f1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8570f1ca341d4f0ee2eb7599ce316d6622f60aec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ff1c0433)
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-ff1c0433"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208302011347113-18119/BuildReport?accessString=b11f0fd8c1029b511348220dcaa688709166569b86781a6ab08d1b83a6c081f6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 20:35 UTC, opbld34 commented
Docs Build status updates of commit _[d71e6a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d71e6a62c606a6f299d2c7e1437c1a2f055f755e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208302033533976-18119/BuildReport?accessString=b7c13a0dd322d50b4c587e9021281ff2093db6fa7ddcc33fbdcbfc92997aef89).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 20:49 UTC, sumanac commented on api-reference/v1.0/toc.yml
> +          href: api/chat-delete-pinnedmessages.md
pinned message related changes are already under "Chat". I added for "Chat message" for both beta and v1.0

2022-09-07 22:11 UTC, opbld34 commented
Docs Build status updates of commit _[0eb8e73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0eb8e73edad82ca9f7a266c2b4e4c5eb98356019)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-985e8425)
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-985e8425"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209072209144880-18119/BuildReport?accessString=31cea89c155187a184b47bd666f46dd4047720328495546fe1afbe6c2153fd29).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 22:23 UTC, opbld31 commented
Docs Build status updates of commit _[25ff45b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25ff45b84df6581f78444a8019daf81d92c21fdf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209072221201293-18119/BuildReport?accessString=a816ff9c6eeb81b9452c23f5bd87f6a6e2fb49dcaf0496254f8bd518a1d9dd70).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 17:19 UTC, opbld34 commented
Docs Build status updates of commit _[d99f7bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d99f7bd56f736c5a950f22d22ed9f196f6ec4a35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081717403013-18119/BuildReport?accessString=8c3e29d29c689bdb82d27d5b4793c7d76b9b22d91c26b134dbc1c13f715ddf90).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 01:56 UTC, RamjotSingh approved these changes

2022-09-09 01:56 UTC, RamjotSingh commented on api-reference/v1.0/api/chat-delete-pinnedmessages.md
> +DELETE /chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfoId}
{pinnedChatMessageId} everywhere.

2022-09-09 17:46 UTC, sumanac commented
@Lauragra - Could you please help review and merge this PR?

2022-09-09 17:50 UTC, opbld32 commented
Docs Build status updates of commit _[7b472e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b472e20ba8f216f64083b4abbab80b68173e3fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-additionalaccess?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209091746138171-18119/BuildReport?accessString=cfa20ed65dedd45e4035188d5ba600e552bd336a6d179c06c60ba37282ce4c1b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 20:42 UTC, JarbasHorst commented
Hello @sumanac, we will start the content review work for this PR on Monday.

2022-09-12 15:19 UTC, opbld34 commented
Docs Build status updates of commit _[ca68181](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca681813eea2c1dc17db771dd9aa7deff6ae05a2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3baab999)

<a id="3baab999"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ca681813eea2c1dc17db771dd9aa7deff6ae05a2 in branch sumanac/gapinnedmessage of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 4002491ea4ade783fe0e544ae3e181fb386ff9f8). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209121519294786-18119/BuildReport?accessString=c7832af55740e0d208b2633964aa6ff9ac949293381f93eb1a27160e1b7e542d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 15:23 UTC, sumanac commented on api-reference/v1.0/api/chat-delete-pinnedmessages.md
> +DELETE /chats/{chat-id}/pinnedMessages/{pinnedChatMessageInfoId}
updated in both beta and v1.0

2022-09-12 15:31 UTC, opbld34 commented
Docs Build status updates of commit _[7c6b94e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c6b94eb32f2c3b5ae2cc3161362b5844b4a95c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209121529313817-18119/BuildReport?accessString=e2bfecfce04321e9b3c32d022dc0958539ad3e6737c6f925cee38cab210a1d59).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 21:59 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **pinnedMessages** relationship to the [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0) resource.",
Please, add the Pinned messages section to the Methods table in the chat resource topic (v1.0).

2022-09-12 21:59 UTC, JarbasHorst commented on api-reference/v1.0/api/chat-list-pinnedmessages.md
> +title: "List pinned messages in a chat"
For consistency, the correct title for this API topic should be "List + navigation property name". The current title breaks our titling guidelines. To keep your titling style while also partially complaining with our guidelines, please update the title in lines 2 and 10 to be: 

- List pinnedChatMessage in a chat

Please, apply this change also to the corresponding beta topic.

2022-09-12 22:03 UTC, JarbasHorst commented
Hello @sumanac, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [18424](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18424) into your branch to include my fixes and before addressing my new comments.

2022-09-13 02:34 UTC, opbld30 commented
Docs Build status updates of commit _[2891fac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2891fac713825d1345b8ea90b7694233c1757fee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a2c89b9d)

<a id="a2c89b9d"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 2891fac713825d1345b8ea90b7694233c1757fee in branch sumanac/gapinnedmessage of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 0d4499051914b2a2d9a71ba707904b661abeb880). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209130234201591-18119/BuildReport?accessString=e60bb20199c1ef76f9ac998d347fee29f12aec46a4fd994b759baaac0a61e7c2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 22:50 UTC, opbld34 commented
Docs Build status updates of commit _[734323f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/734323fcd5d114b9faa779b84cb76a081c5f2846)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209132248111897-18119/BuildReport?accessString=734454032d6e43c40ef67e0ceebfce4ece0c7019ecc1a0d18062a98c0cfe2aa6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 16:41 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [18477](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18477) into this branch to include my final edits.

2022-09-15 03:15 UTC, opbld34 commented
Docs Build status updates of commit _[0a8ce1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a8ce1d091f28c6391784317ce4d8498c35e6ae4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150313057796-18119/BuildReport?accessString=bbd5022750e8863f3c3da8293b82dd8068fa04e69b7033d757bfcb90243c7ee5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 17:29 UTC, opbld33 commented
Docs Build status updates of commit _[2f5d5df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f5d5df3063cba6b16da49bf7207d7e0a5ef366e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209151727280454-18119/BuildReport?accessString=783644afb6e57e952068808f32983130ee16f3197750c264d60ed916b4940104).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-17 00:37 UTC, opbld30 commented
Docs Build status updates of commit _[3b83c4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b83c4ab4bbcadf6cae76f9bb6c5662134596bd5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209170035235399-18119/BuildReport?accessString=ab5313054769270f2cd5075fcf88d0ac4ab292dfaa137b059024dacee204cfc5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-17 00:40 UTC, opbld34 commented
Docs Build status updates of commit _[9743a22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9743a22dffd52d43acc0cb75467fbc604c1a6158)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209170036109996-18119/BuildReport?accessString=d1cb96c11f24effab3de03e8ac0a79883c5f81a64a96977e5a73853c8227c14d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-17 00:40 UTC, Lauragra approved these changes

2022-09-19 16:39 UTC, opbld31 commented
Docs Build status updates of commit _[f9d6205](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9d62059d6a652ffd1549749c143b4fa85974fd5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209191634470896-18119/BuildReport?accessString=e63de7850c4034761544e37dd9d4bf2a06a38d338c1439d9e829f74cd4270494).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 22:47 UTC, sumanac commented
@Jarbas-MSFT - Could you please merge this PR if there is no other changes needed?

2022-09-20 22:49 UTC, opbld34 commented
Docs Build status updates of commit _[2863583](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28635839db3a56637bad894e6bec239a303938df)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 23:01 UTC, JarbasHorst commented
Hi @sumanac, the content review work is completed for this PR. After the APIs are live, please set the ready to merge label to signal that your PR is ready to publish.

2022-09-23 01:51 UTC, opbld34 commented
Docs Build status updates of commit _[276da1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/276da1a878005f4504cbc195f3c232b8479b3ccb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209230149034069-18119/BuildReport?accessString=229e3dde20c052c2e06ff93d19dd0315a99cb2d5d8288056c4c1d3a0ef52ff15).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 01:55 UTC, opbld30 commented
Docs Build status updates of commit _[685f078](https://github.com/microsoftgraph/microsoft-graph-docs/commits/685f078ad49dcbb49e6d448806e228d6b6f6208e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-beta&branch=pr-en-us-18119) (graph-rest-beta) |
[api-reference/v1.0/api/chat-delete-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-delete-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-list-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-list-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post-pinnedmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/api/chat-post-pinnedmessages.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-post-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/eventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/eventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/eventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messagepinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messagepinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/messagepinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/messageunpinnedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/messageunpinnedeventmessagedetail?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/pinnedchatmessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/resources/pinnedchatmessageinfo.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/pinnedchatmessageinfo?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/chat-delete-pinnedmessages?view=graph-rest-1.0&branch=pr-en-us-18119) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumanac/gapinnedmessage/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209230150353055-18119/BuildReport?accessString=7c6b6790db6a38a1177b35098bc8bb1f399bcbae3193239d332634ecbb49bdfc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 01:57 UTC, merged