Added Support for editing properties of message in user context for v1.0
microsoftgraph/microsoft-graph-docs pull request #18147
Opened 2022-08-23 12:47 UTC by sumitgupta3

Support for editing message from beta to v1.0

2022-08-23 12:51 UTC, opbld30 commented
Docs Build status updates of commit _[7e805f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e805f32f1a59fc9b9768f4530c51370b8ea9ae5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208231247248143-18147/BuildReport?accessString=959ef4715c2c29f3a79dfe0e0678ca3538e698473fb94456235eb9262bf2083c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 21:00 UTC, opbld34 commented
Docs Build status updates of commit _[ec7eb3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec7eb3cc10d7f1ecb692ef936c17fce0b4c55914)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208242057573589-18147/BuildReport?accessString=993e138ea121cf090b9dd78d9629bb63f21b6116e991f0ed76c183c467485289).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 20:02 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
> +      "displayName": "Sumit Gupta",
Line 176: Please use [CELA approved fictitious names](https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/trademarks-fictitious-names.aspx) in your examples.

2022-08-25 20:02 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
> +      "displayName": "Sumit Gupta",
Line 230: Please use fictitous names.

2022-08-25 20:03 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
> +          "displayName": "Raghav Mankad",
Line 249: Please use fictitious names.

2022-08-25 20:03 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
> +      "displayName": "Sumit Gupta",
Line 309: Names.

2022-08-25 20:05 UTC, isvargasmsft requested changes
Hello @sumitgupta3, 

Thank you very much for your work in this PR. 

Just leaving a few comments regarding the use of names in the examples. 

Please ping me on the side if you have any questions. 

Kind regards, 

Isaac

2022-08-25 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[26d35e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26d35e695ccf24271a78851129f8451ea1cbc3b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208252138033572-18147/BuildReport?accessString=55fc0245c3dbf5badbffe853685d7eb9c98f8623fe60a0af754b6d31b40e6c83).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 21:47 UTC, opbld31 commented
Docs Build status updates of commit _[cbed945](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbed94550ba8edc1d9cd8bc81a3dab9dcc96281f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208252144025088-18147/BuildReport?accessString=b2d2f539eafaff46905a06bd02018e9c5d3d6063ae52153ef612217f57194bf1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 22:02 UTC, isvargasmsft commented on api-reference/v1.0/api/chatmessage-update.md
> +      "displayName": "Sumit Gupta",
Please also edit these names in the beta topic.

2022-08-25 22:03 UTC, opbld32 commented
Docs Build status updates of commit _[139730b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/139730baad4c624d1103db0272e3bc08ee9dab3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18147) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208252201554957-18147/BuildReport?accessString=bcabc28e98f438a9ba0a9f665d98a1669271abeeaae08c22b9efc230006b1d50).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 11:27 UTC, opbld30 commented
Docs Build status updates of commit _[5edf981](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5edf9818c4bd452811ed0267a49430d5af1b8ea9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18147) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209021120125462-18147/BuildReport?accessString=40a7e3ae58ace15e793ed985dd03c4cdc18f360f98a0bbf7b474a3060841b3f6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 07:34 UTC, sumitgupta3 commented on api-reference/v1.0/api/chatmessage-update.md
> +      "displayName": "Sumit Gupta",
used Lam Cong now. Got it from CELA Tool.

2022-09-08 07:34 UTC, sumitgupta3 commented on api-reference/v1.0/api/chatmessage-update.md
> +      "displayName": "Sumit Gupta",
used Lam Cong now. Got it from CELA Tool.

2022-09-08 07:38 UTC, opbld33 commented
Docs Build status updates of commit _[65c84b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65c84b3c3d63b32ac08644ad999c07439bc33a27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18147) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080735518641-18147/BuildReport?accessString=e23ae312fab8103eea5b8074fd9de9968a677a9549d3efab54aebe47ba17d578).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 07:40 UTC, opbld32 commented
Docs Build status updates of commit _[580a430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/580a430af558a510c583e9579d38dabaff95e6be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18147) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209080736543010-18147/BuildReport?accessString=18eccbdea938e3235d438b3fe55baef5aff5f237c35d28a28f25b8b34f0dc724).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-08 15:50 UTC, opbld34 commented
Docs Build status updates of commit _[ba47476](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba47476febc81185ea9ed00f73856b5aee9f6a56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/beta/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&branch=pr-en-us-18147) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sumit/editV1/api-reference/v1.0/api/chatmessage-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&branch=pr-en-us-18147) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209081545430656-18147/BuildReport?accessString=813907ee23da9ad96527ebf85425251e634b99b234f1716143bf1494a0dfd380).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-11 02:13 UTC, Lauragra commented
@sumitgupta3 , if you would like to publish this PR, please remove the **do not merge** label and add **ready to merge**.

2023-01-20 04:04 UTC, merged