Document automaticUserConsentSettings in XTAP
microsoftgraph/microsoft-graph-docs pull request #18162
Opened 2022-08-23 22:56 UTC by jkdouglas

2022-08-23 22:58 UTC, opbld30 commented
Docs Build status updates of commit _[b89e843](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b89e8438400e1efa5825c1c5cf2f88c04eccb4b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/inboundoutboundpolicyconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/inboundoutboundpolicyconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208232256142440-18162/BuildReport?accessString=8d510dc220774db41f5f5d793d45d8f26de1710f1ad48320881554a9bc7921f3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 01:40 UTC, jkdouglas commented
API review pr link: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11482

2022-08-24 16:08 UTC, opbld31 commented
Docs Build status updates of commit _[43aaca8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43aaca80469243b00e064442835db25a7a18a9d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/inboundoutboundpolicyconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/inboundoutboundpolicyconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208241606101762-18162/BuildReport?accessString=91cf56f8b603a19d088afadb716232d027c3b99b93430dc28d844c087ea451ba).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-20 16:17 UTC, opbld33 commented
Learn Build status updates of commit _[6cddcaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cddcafff4dd9f45165279cc95d98537dd58354f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/inboundoutboundpolicyconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/inboundoutboundpolicyconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210201614307594-18162/BuildReport?accessString=97fe9e1a76cd70b8035d5aea736f2a6ebdd34851cb3594006ae98deb29b96bb9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 18:20 UTC, opbld34 commented
Learn Build status updates of commit _[fd0ce1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd0ce1eb7532b148af54bee80e0e705dd8756cb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/inboundoutboundpolicyconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/inboundoutboundpolicyconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210261817502124-18162/BuildReport?accessString=a06dcf12a755f489eda3aedfcd92d09b1bb8cde6aa1b2363fb2bb9b329c9a530).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-02 07:16 UTC, FaithOmbongi commented
Hi @jkdouglas - I see from the related schema (Krunal's schema PR # 6711944) that this feature is still in private preview. I'm putting this PR in the content review backlog and will review it when your team is ready to release the feature to public preview.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/14026935/199423997-4e07ddb3-f5f3-498a-8c34-d64b382f2f44.png">

2022-11-15 21:21 UTC, opbld30 commented
Learn Build status updates of commit _[5cf4acf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cf4acf261741e0b32daf94c2475a5e7acccb94b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationdefault-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-get?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationpartner-update?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-list-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-list-partners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-list-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/api/crosstenantaccesspolicy-post-partners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/api/crosstenantaccesspolicy-post-partners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicy-post-partners?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/crosstenantaccesspolicyconfigurationpartner.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationpartner?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[api-reference/beta/resources/inboundoutboundpolicyconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/api-reference/beta/resources/inboundoutboundpolicyconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta&branch=pr-en-us-18162) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/xtap-automaticUserConsentSettings/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202211152119206747-18162/BuildReport?accessString=d4734f900866bafd84ab55e84d684201264e9c33c34aaf8b8207634195283f37).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-10 16:00 UTC, jkdouglas commented
@FaithOmbongi - here is the PR to unhide the schema. Can you help review this now?

https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/7422721

2023-01-11 14:11 UTC, FaithOmbongi requested changes
Thank you @jkdouglas for your work on this PR. I've left suggestions for minor fixes - maintaining the alphabetical order of the properties tables, shortening the titles for the examples, and changelog fixes.

2023-01-11 14:11 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
I suggest shortening the title and instead adding a description to give context for the example that follows.
```suggestion
### Example 1: Configure inbound trust settings

The following example configures the partner-specific policy by setting the inbound trust settings to accept MFA, compliant, and Hybrid Azure AD Joined devices from the partner tenant.

```

2023-01-11 14:11 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
Same suggestion as previous
```suggestion
### Example 2: Configure automaticUserConsent settings 

The following example configures the partner-specific policy by consenting for B2B collaboration on behalf of your users and accepting admin consent for the partner's users.

```

2023-01-11 14:11 UTC, FaithOmbongi commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
> +| automaticUserConsentSettings | [inboundOutboundPolicyConfiguration](../resources/inboundoutboundpolicyconfiguration.md) | Determines the default configuration for automatic user consent settings. `
Move to top of table

2023-01-11 14:11 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +| automaticUserConsentSettings | [inboundOutboundPolicyConfiguration](../resources/inboundoutboundpolicyconfiguration.md) | Determines the partner-specific configuration for automatic user consent se
Move to top of table

2023-01-11 14:11 UTC, FaithOmbongi commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +| automaticUserConsentSettings | [inboundOutboundPolicyConfiguration](../resources/inboundoutboundpolicyconfiguration.md) | Determines the partner-specific configuration for automatic user consent se
Move to top of table

2023-01-11 14:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Property",
```

2023-01-11 14:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ApiChange": "Resource",
```suggestion
          "ApiChange": "Property",
```

2023-01-11 14:13 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [inboundOutboundPolicyConfiguration](https://docs.microsoft.com/graph/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta) resource.",
This should fix your changelog error
```suggestion
          "Description": "Added the [inboundOutboundPolicyConfiguration](https://docs.microsoft.com/graph/api/resources/inboundoutboundpolicyconfiguration?view=graph-rest-beta) resource.",
```

2023-01-13 23:21 UTC, jkdouglas commented on api-reference/beta/resources/crosstenantaccesspolicyconfigurationdefault.md
> +| automaticUserConsentSettings | [inboundOutboundPolicyConfiguration](../resources/inboundoutboundpolicyconfiguration.md) | Determines the default configuration for automatic user consent settings. `
Fixed.

2023-01-13 23:21 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicy-post-partners.md
> +| automaticUserConsentSettings | [inboundOutboundPolicyConfiguration](../resources/inboundoutboundpolicyconfiguration.md) | Determines the partner-specific configuration for automatic user consent se
Fixed.

2023-01-13 23:22 UTC, jkdouglas commented on api-reference/beta/api/crosstenantaccesspolicyconfigurationpartner-update.md
> +| automaticUserConsentSettings | [inboundOutboundPolicyConfiguration](../resources/inboundoutboundpolicyconfiguration.md) | Determines the partner-specific configuration for automatic user consent se
Fixed.

2023-01-16 09:24 UTC, FaithOmbongi approved these changes

2023-01-24 02:37 UTC, merged