Authentication Strengths documentation
microsoftgraph/microsoft-graph-docs pull request #18164
Opened 2022-08-23 23:52 UTC by mmcla

2022-08-23 23:56 UTC, opbld31 commented
Docs Build status updates of commit _[bc03561](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc035610e2f355e5136b91f210e2ea9b2f601c34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-8f0ebd226b8013275e12e4709f98bce6-4849a96c)
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-3314cc623982b6632dcee2360b8f4c6f-4849a96c)
[api-reference/beta/resources/conditionalaccessgrantcontrols.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/conditionalaccessgrantcontrols.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessgrantcontrols?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-d6cd2d8b340e75db8d2fe6009ee09613-4849a96c)
[api-reference/beta/resources/fido2combinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/fido2combinationconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/fido2combinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-a74c7c2d031f7f46b6e261cf1083b44c-4849a96c)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check [...]

2022-08-24 15:27 UTC, opbld30 commented
Docs Build status updates of commit _[3aeeca7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3aeeca783423547fc0560a1efc05691bc61c86ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-8f0ebd226b8013275e12e4709f98bce6-2f3ec642)
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-3314cc623982b6632dcee2360b8f4c6f-2f3ec642)
[api-reference/beta/resources/conditionalaccessgrantcontrols.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/conditionalaccessgrantcontrols.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessgrantcontrols?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-d6cd2d8b340e75db8d2fe6009ee09613-2f3ec642)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/gra [...]

2022-08-24 15:34 UTC, opbld30 commented
Docs Build status updates of commit _[a3691d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3691d17e810904f53f6c581ff1b5f2759fe06bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-24 15:39 UTC, opbld33 commented
Docs Build status updates of commit _[a11551b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a11551bd82c449317bef4ec37659d5b206f8d4b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-24 20:00 UTC, FaithOmbongi requested changes
Hi @mmcla, @InbarckMS - I've only made a quick pass to make sure all files are in the PR based on your schema changes. Will do a comprehensive review later as agreed.

**Missing info (blocking for schema publication):**
+ authenticationStrengths relationship in the [conditionalAccessRoot](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessRoot?view=graph-rest-beta) doc.
+ authenticationstrengthroot.md file => Contains 1 property and 2 relationships.
+ Add the authenticationStrengthPolicies relationship in the [policyRoot](https://docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta) resource doc
+ Add real example responses for all API docs. I think this will also help you to resolve the API doctor error which is flagged against the examples in the file.
+ Missing fido2CombinationConfiguration resource and associated methods
+ Missing changelogs (updates in both Microsoft.AuthenticationMethodsPolicy.json, Microsoft.IdentityProtectionServices.json


**Content review specific: (blocking)**
+ authenticationCombinationConfiguration resource doc - ~Do abstract types expose methods? I thought not as per OData. Though I do see your approved API.md shows methods are supported 🤔~ I correct myself. I understand that the methods should be related to the derived type. Will check closely during review.
+ For EntityType resources, any properties that support query parameters should indicate the supported query parameters. For $filter, you should also  indicate which operators. See the user resource doc for guidance.
+ The "Optional query parameters" section should be updated with the list of all supported OData query operators. In addition, all resource docs for Entity Types should indicate the query operators supported by properties, where applicable. I'm concerned that your API.md doesn't indicate the properties that support query parameters.
+ All examples must be real examples. The example requests must contain real ID values; Request bodes must be real values; Response payloads must be real payloads - including the @odata.context - as would be returned if you ran the queries in Graph Studio; not the pseudos that are autogenerated by Graph Studio.
+ I think the API doctor error is also because of the example in authenticationstrengthroot-list-authenticationmethodmodes.md. Try documenting a real example we see if it resolves the error.
+ We need an Overview article for Authentication Strengths.

2022-08-26 20:39 UTC, opbld32 commented
Docs Build status updates of commit _[4a2a39d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a2a39de3de14b9a859aa7baf911b40adfd7b9af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/conditionalaccessroot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-fbe3e3147346e4809725a21dc1a8d1c1-11515112)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/au [...]

2022-08-26 20:48 UTC, opbld31 commented
Docs Build status updates of commit _[9279452](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92794520b34755e334646641cbddd3a8a4c70e3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 21:35 UTC, opbld34 commented
Docs Build status updates of commit _[10e7975](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10e7975a7908f71ac853913095b16a8ac70eddf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 21:52 UTC, opbld30 commented
Docs Build status updates of commit _[579477d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/579477d4c31f79d9ebc21bdf1d5aacddee4bc44c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 21:59 UTC, opbld30 commented
Docs Build status updates of commit _[dfe3060](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfe306056534b92fe90c12d3354f65e596af6f8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 22:09 UTC, opbld32 commented
Docs Build status updates of commit _[8d6f0bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d6f0bdc34436265cb4b9d63c1aa615756fb2d3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 22:22 UTC, opbld30 commented
Docs Build status updates of commit _[a2c79bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2c79bf76dd9f6ee5acf3b225fd33184db120df2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 23:14 UTC, opbld30 commented
Docs Build status updates of commit _[2a01915](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a019152de08fa6aac189bcd023f438a754f6194)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrengths-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengths-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengths-overview?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-bfb1d5e8d42b2de6652621ddc2db3147-026e4fc3)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [...]

2022-08-26 23:21 UTC, opbld30 commented
Docs Build status updates of commit _[3ff5f8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ff5f8bc883ece745c541da712ce6ad01a30dda6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationcombinationconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcombinationconfiguration?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/ [...]

2022-08-26 23:46 UTC, mmcla commented
@FaithOmbongi - I've gone through and addressed most of the items above:

* Added the authenticationStrengths relationship to CA root
* updated the authenticationStrengthRoot.md
* Added the authenticationStrengthPolicies relationship to policyRoot
* Added examples for all APIs
* Added the FIDO2combinationconfiguration resource
* Added the changelog
* Added an overview (with TOC update)

A couple of things are unresolved:

* Need to work with our devs on which query parameters are available; it wasn't immediately clear to me from the spec.

Things I need your help with:

### First issue: API doctor error.

The API doctor error isn't resolved. I'm fairly certain it's coming from this line in [authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18164/files#diff-22bd0e8f806b27135e12e4709f98bce618330aa175989e735626a26314b079cc): `"@odata.type": "Collection(microsoft.graph.authenticationMethodModes)"`. 

Note that authenticationMethodModes is an enum, which I've added to the enum.md file. Maybe that's the issue here?

### Second issue: authenticationCombinationConfiguration and fido2CombinationConfiguration 

authenticationCombinationConfiguration is an abstract type; fido2CombinationConfiguration inherits from authenticationCombinationConfiguration. The API is designed in such a way that there is no endpoint that only works with fido2CombinationConfiguration - all POST, GET, DELETE, PATCH are called on the generic /combinationConfigurations endpoint that works with any child of authenticationCombinationConfiguration.

Given all of that, where should I defined the methods - on authenticationCombinationConfiguration or fido2CombinationConfiguration?

2022-08-29 17:44 UTC, FaithOmbongi commented
Hi @mmcla -
> ### First issue: API doctor error.
> The API doctor error isn't resolved. I'm fairly certain it's coming from this line in [authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18164/files#diff-22bd0e8f806b27135e12e4709f98bce618330aa175989e735626a26314b079cc): `"@odata.type": "Collection(microsoft.graph.authenticationMethodModes)"`.
> 
> Note that authenticationMethodModes is an enum, which I've added to the enum.md file. Maybe that's the issue here?

Yeah, that's definitely the source. I've looked at _authenticationstrengthroot-list-authenticationcombinations.md_ to try to understand your validation error and I'd like to point out a couple of things:
1. I don't think that's a valid file. Reason:
     a. I see it wasn't autogenerated in the schema PR 6619553.
     c. It conflates two different objects: authenticationMethodModeDetail and authenticationCombinations > authenticationMethodModes
     b. authenticationCombinations is not a relationship in the schema, it's a structural property. AFAIK, the only way you can have such file with that naming pattern is if authenticationCombinations were a relationship in authenticationStrengthRoot. 

    BUT, `/identity/conditionalAccess/authenticationStrengths/authenticationCombinations` is a valid a URL as per your API.md. IDK that you can call a property (in this case authenticationCombinations) like this in the URL path. I thought you should only be able to reference using query parameters or as an ID. I haven't seen a pattern similar to yours in Graph so will need to confirm with Dan on this.

2. For the response object specifically, can you re-run the request in Graph Explorer to see the response payload? I doubt it can be `"value': [ collection of values"]` as per the response in the doc, it can only be `"value": [ "property" : "collection of values"]` or something close to that. A property must always be returned to store the values.

-------------------------------------------------------------------------------------
> ### Second issue: authenticationCombinationConfiguration and fido2CombinationConfiguration
> authenticationCombinationConfiguration is an abstract type; fido2CombinationConfiguration inherits from authenticationCombinationConfiguration. The API is designed in such a way that there is no endpoint that only works with fido2CombinationConfiguration - all POST, GET, DELETE, PATCH are called on the generic /combinationConfigurations endpoint that works with any child of authenticationCombinationConfiguration.
> 
> Given all of that, where should I defined the methods - on authenticationCombinationConfiguration or fido2CombinationConfiguration?

Document the methods in authenticationCombinationConfiguration. Please see [identityProviderBase resource type](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0) which has a similar behavior.


The first one raises more questions than gives answers but I hope this helps.

2022-08-29 23:18 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthpolicy-update.md
> +Update the properties of an [authenticationStrengthPolicy](../resources/authenticationstrengthpolicy.md) object.
Is it worth noting here that you *cannot* update the allowedCombinations (and providing a link to the correct `updateAllowedCombinations` API)?

2022-08-29 23:19 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
> +**TODO: Add Description**
```suggestion
Update the allowedCombinations property of an [authenticationStrengthPolicy](../resources/authenticationstrengthpolicy.md) object.
```

2022-08-29 23:19 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
> +**TODO: Add Description**
Same question as above, consider adding a link to the generic PATCH doc?

2022-08-29 23:20 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md
> +}
[nit] I don't know how much it matters, but do you want to fix the whitespace here?
```suggestion
{
  "@odata.type" : "#microsoft.graph.updateAllowedCombinationsResult",
  "previousCombinations": [
    "fido2",
    "password, voice"
  ],
  "currentCombinations": [
    "password, voice"
  ],
  "conditionalAccessReferences": [
    "53a3968a-ae2c-4b82-a313-091d10c52bfa"
  ],
  "additionalInformation": "You have lowered the security of the My Custom Strength authentication strength by adding a lower security combination. This Authentication Strength is referenced by one or more Conditional Access policies. Review conditionalAccessReferences to understand which Conditional Access policies were impacted by this change. To reverse your changes back, use updateAllowedCombinations action with the previousCombinations values."
}
```

2022-08-29 23:20 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthroot-delete-policies.md
> +DELETE /policies/authenticationStrengthPolicies/{authenticationStrengthPolicyId}/$ref
`$ref`?

2022-08-29 23:22 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md
> +>**Note:** The response object shown here might be shortened for readability.
I'm not sure if this is just standard graph language, but it doesn't look like it was shortened.

2022-08-29 23:22 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +        "id" : "x509CertificateMultiFactor",
```suggestion
        "id": "x509CertificateMultiFactor",
```
[nit] Whitespace consistency? Not sure how much it matters.

2022-08-29 23:23 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthroot-list-policies.md
> +      ]
```suggestion
      "allowedCombinations": [
        "x509CertificateSingleFactor, fido2",
        "fido2"
      ],
      "combinationConfigurations": [
        {
          "@odata.type" : "fido2CombinationConfiguration",
          "id": "675ff4e1-7c6d-4a7f-9803-ad084d1b45b3",
          "allowedAAGUIDs": [
            "2ac80ddb-17bd-4575-b41c-0dc37ae3290d"
          ],
          "appliesToCombinations": ["fido2"]
        }
      ]
```
Looks like this had 4-space tabs for some reason.

2022-08-29 23:24 UTC, jbzdarkid commented on api-reference/beta/api/authenticationstrengthroot-post-policies.md
> +|allowedCombinations|authenticationMethodModes collection|The authentication method combinations allowed by this authentication strength policy. The possible values of this flag enum are: `password`,
It might be worth linking to the allowedCombinations API here?

2022-08-29 23:25 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengthpolicy.md
> +## Methods
I don't see the /usage API in here, did you forget it?

2022-08-29 23:26 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengthroot.md
> +            "id" : "federatedMultiFactor",
```suggestion
            "id": "federatedMultiFactor",
```
[nit] Again, not sure about what the whitespace conventions are, or if we need to be consistent between different files.

2022-08-29 23:27 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengthroot.md
> +```
[nit] Something bad happened to this whitespace.

2022-08-29 23:27 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengths-overview.md
> +Authentication strengths allow administrators to require specific combinations of [authentication methods](authenticationmethods-overview.md) to access a resource. Each authentication strength compri
```suggestion
Authentication strengths allow administrators to require specific combinations of [authentication methods](authenticationmethods-overview.md) to access a resource. Each authentication strength comprises one or more combinations of authentication methods, where each combination is one or more authentication methods. When the strength is applied to a scenario as a [grant control](conditionalaccessgrantcontrols.md) in [Conditional Access](conditionalaccesspolicy.md), a user in scope of the policy is required to satisfy one of those allowed combinations to sign in. As part of Conditional Access, authentication strengths can also be paired with other Conditional Access controls such as user risk and location.
```
Future-proof the wording a bit?

2022-08-29 23:29 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengths-overview.md
> +When creating a Conditional Access policy with the 'Require authentication strength' control, administrators can choose from three built-in Authentication strengths policies. Administrators may also
```suggestion
When creating a Conditional Access policy with the 'Require authentication strength' control, administrators can choose from three built-in Authentication strengths policies. Administrators may also create their own custom Authentication strength policies using only the authentication methods combinations they would like to allow. Using custom authentication strengths, certain auth methods allow even further restriction, limiting users to only certain instances of an authentication method. Today, this is limited to restricting which FIDO2 security keys can be used during authentication, to allow only keys with certain Authenticator Attestation GUIDs (AAGUIDs).
```
[nit] wording, re-ordered phrases.

2022-08-29 23:30 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengths-overview.md
> +The [authentication combinations](../api/authenticationstrengthroot-list-authenticationcombinations.md) API allows the caller to retrieve a read-only list of all supported authentication method combi
```suggestion
The [authentication combinations](../api/authenticationstrengthroot-list-authenticationcombinations.md) API allows the caller to retrieve a read-only list of all supported authentication method combinations. Each combination comprises one or more comma-separated [authentication method modes](authenticationmethodmodedetail.md), and each combination is a part of a built-in authentication strength and may be used in custom authentication strengths.
```
[nit] Again, future proof wording?

2022-08-29 23:31 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengths-overview.md
> +* "password, softwareOath"
```suggestion
* `"FIDO2"`
* `"password, microsoftAuthenticatorPush"`
* `"password, softwareOath"`
```
Suggestion: Use `` to indicate "this is code"?

2022-08-29 23:32 UTC, jbzdarkid commented on api-reference/beta/resources/authenticationstrengths-overview.md
> +* passwordless multifactor authenticators such as FIDO2 and x509 certificate authentication
```suggestion
* passwordless multifactor authenticators such as FIDO2 and Windows Hello for Business
```
x509 can be single factor, maybe this is a better example?

2022-09-06 17:45 UTC, opbld31 commented
Docs Build status updates of commit _[178305a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/178305adbc496ddf8c604b69c8b5d4ac57313db3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1ac8d5f0)

<a id="1ac8d5f0"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 178305adbc496ddf8c604b69c8b5d4ac57313db3 in branch mmcla-auth-strengths of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 327b975dec87619340b0b8ef3778c46e25b65ffe). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209061745224834-18164/BuildReport?accessString=90f01c194c3cf9c86874f61a8a592ac621782b6c4edd96f0766806dd20aeb298).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 18:29 UTC, opbld31 commented
Docs Build status updates of commit _[2fc32e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fc32e8fcfbd35b74cff2d5a8082b8271fd8ad7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1f5d4335)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](ht [...]

2022-09-06 20:30 UTC, FaithOmbongi requested changes
Hi @mmcla, @InbarckMS - I've left some inline suggestions + the following feedback:
+ Add authenticationstrengthpolicy-usage.md file + include it in the Methods table of authenticationstrengthpolicy.md
+ I need to confirm whether the LIST and POST files should be what you've used or policyroot-list/post-authenticationstrengthpolicies.md; though the LIST file wasn't autogenerated; This is because authenticationStrengthPolicy is the return type of navigation properties for two different entities. I'll get back to you on that.
+ Do we want' to document the two endpoints for working with the authenticaitonStrengthPolicies? /policies/authenticationStrengthPolicies and /identity/conditionalAccess/authenticationStrengths/policies?
+ [My follow up] Allow me to confirm authenticationstrengthroot-list-authenticationcombinations.md. The API works as you've documented, however, API doctor _might_ be expecting a collection in the standard format. 

```json
{
  "value": [
    {
      "property" : [
              "windowsHelloForBusiness",
               "fido2",
                 ....]
    }
 ]
}
```

In addition, I need to confirm the proper file name for such scenarios because I'm seeing this scenario for the first time and it isn't covered in the guidance AFAIK.

I have some questions about authenticationStrengthRoot and the APIs that link to it. Allow me to validate with Dan before I get back to you.

**PENDING REVIEW** - The Overview article + changelog.


**On a side note:**
I'm experiencing intermitted failures when calling many of the APIs. The API may fail 3-4 x successively with a 403 Forbidden, then I wait a few minutes and retry and it succeeds. But the permissions are all granted. I've tested via both Graph Explorer and Postman and same problem.

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationstrengthroot.md
> +{
Restore this to be a JSON representation, not a real payload.

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationmethodmodedetail.md
> +description: "A specific mode of af an authentication method that operates in more than one way"
Hmm, this sounds much bigger than the resource and its related APIs seem to be/do.

The resource seems to represent a read-only "dictionary" (if I may use the comparison) that explains the values of the **authenticationMethodModes** enum (which answers one of the comments I shared while reviewing the authenticationstrengthpolicy.md.)

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationmethodmodedetail.md
> +A detail view of an authentication method mode, which is a specific mode of operation for an authentication method that operates in more than one way such as Microsoft Authenticator, which may be use
- Same comment as in the metadata applies here.
- See the suggestion if it makes sense.

```suggestion
The identifier, display name and description of the **authenticationMethodModes** objects that can be defined for the **allowedCombinations** property of the [authenticationstrengthpolicy](../resources/authenticationStrengthPolicy.md).
```

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +title: "List authenticationMethodModeDetails"
```suggestion
title: "List authenticationMethodModes"
```

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +# List authenticationMethodModeDetails
```suggestion
# List authenticationMethodModes
```

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Document the supported query parameters, if any. If none, update description to indicate so.

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationmethodmodedetail-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
......

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationmethodmodedetail.md
> +|authenticationMethod|baseAuthenticationMethod|Which authentication method this mode modifies. The possible values are: `password`, `voice`, `hardwareOath`, `softwareOath`, `sms`, `fido2`, `windowsHe
```suggestion
|authenticationMethod|baseAuthenticationMethod|The authentication method that this mode modifies. The possible values are: `password`, `voice`, `hardwareOath`, `softwareOath`, `sms`, `fido2`, `windowsHelloForBusiness`, `microsoftAuthenticator`, `temporaryAccessPass`, `email`, `x509Certificate`, `federation`, `unknownFutureValue`.|
```

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationmethodmodedetail.md
> +|id|String|The system-generated GUID for this mode. Inherited from [entity](../resources/entity.md).|
```suggestion
|id|String|The system-generated identifier for this mode. Inherited from [entity](../resources/entity.md).|
```

2022-09-06 20:30 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +            items:
List the abstract type: authenticationcombinationconfiguration.md, then the derived type fido2combinationconfiguration.md. When you support more derived types, you'll also surface them in the TOC. See "External identities node" after [identityProviderBase resource type](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0).

2022-09-07 12:38 UTC, opbld31 commented
Docs Build status updates of commit _[b5325cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5325cc74e1ca576f3ecd54339e858cf69785182)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-79c8bafc)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](ht [...]

2022-09-07 13:16 UTC, opbld32 commented
Docs Build status updates of commit _[b3baf52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3baf527aeff415771ed8c586c3c76cd9b4e0216)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-47a25179)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](ht [...]

2022-09-07 14:35 UTC, FaithOmbongi requested changes
Hi @mmcla - I've now understood the path ` /identity/conditionalAccess/authenticationStrengths/authenticationCombinations` and my siggestion:

Delete the file: api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md

In api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md, add the request path in the HTTP Request section + add an example 2.

2022-09-07 14:35 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +GET /identity/conditionalAccess/authenticationStrengths/authenticationMethodModes
```suggestion
Retrieve the collection of **authenticationMethodModes** objects and their descriptions.
<!-- {
  "blockType": "ignored"
}
-->
``` http
GET /identity/conditionalAccess/authenticationStrengths/authenticationMethodModes
```

Retrieve the flat collection of  **authenticationCombinations** objects, representing all the allowed combinations (**allowedCombinations**) in an [authenticationStrengthPolicy](../resources/authenticationstrengthpolicy.md) object.
```http
GET /identity/conditionalAccess/authenticationStrengths/authenticationCombinations
```

2022-09-07 14:35 UTC, FaithOmbongi commented on api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md
> +
Add an Example 2 and transfer the example that's currently in api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md here. Maintain the odata.type. I've talked to the API Doctor team and they will guide on on adding a suppression.

2022-09-07 14:39 UTC, opbld32 commented
Docs Build status updates of commit _[31ce590](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31ce59084a42b287a5e36db82edf203ea189ffb9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bbf646d0)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](ht [...]

2022-09-07 19:59 UTC, opbld31 commented
Docs Build status updates of commit _[3fb8293](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fb82935e0e54047008f2d1b7c48a7f2d7c4c3f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5d2d6de8)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](ht [...]

2022-09-08 14:09 UTC, FaithOmbongi requested changes
Minor additional comments

2022-09-08 15:00 UTC, FaithOmbongi commented
@mmcla - I've built on your overview article and proposed some changes to the flow of the article. You can find them here https://github.com/microsoftgraph/microsoft-graph-docs/pull/18365. Feel free to pull the branch into yours, correct the references, or make more changes.

2022-09-08 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[84f98cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84f98cf0c1065422220ca6a0b0b12ee18c617c77)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-620651e0)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-620651e0)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (g [...]

2022-09-08 23:52 UTC, opbld30 commented
Docs Build status updates of commit _[e0ea2e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0ea2e66b66fda4ecc49a0a9552afcd3439c4aa5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e746c676)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-e746c676)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (g [...]

2022-09-09 21:58 UTC, mmcla commented on api-reference/beta/api/authenticationstrengthroot-delete-policies.md
> +DELETE /policies/authenticationStrengthPolicies/{authenticationStrengthPolicyId}/$ref
Must have been added automatically.

2022-09-09 22:01 UTC, opbld30 commented
Docs Build status updates of commit _[6570daf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6570daf7d9aad7fda02df9ddd21f13f558d73d83)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-121be0ad)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-121be0ad)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (g [...]

2022-09-09 22:05 UTC, mmcla commented on api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md
> +description: "Deletes an authenticationCombinationConfiguration object."
Yes, only custom policies. Built-in can't be modified.

2022-09-09 22:09 UTC, opbld34 commented
Docs Build status updates of commit _[6abe34f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6abe34f5404943204cc3ab7d92cdad4839d04f95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-92197da5)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-92197da5)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (g [...]

2022-09-09 22:09 UTC, mmcla commented on api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md
> +**TODO: Add Description**
🤦‍♂️

2022-09-09 22:35 UTC, opbld30 commented
Docs Build status updates of commit _[551c6d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/551c6d05f907ec1ad595631556730bd9c2715547)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-8f0ebd226b8013275e12e4709f98bce6-8f583853)
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-3314cc623982b6632dcee2360b8f4c6f-8f583853)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8f583853)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-8f583853)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.micro [...]

2022-09-09 22:43 UTC, opbld30 commented
Docs Build status updates of commit _[abdc01e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abdc01eacb45ecd3a5f5f8078a0e24db6f2ef6f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-8f0ebd226b8013275e12e4709f98bce6-aa1a6551)
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-3314cc623982b6632dcee2360b8f4c6f-aa1a6551)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-aa1a6551)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-aa1a6551)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.micro [...]

2022-09-09 23:34 UTC, opbld34 commented
Docs Build status updates of commit _[f520c8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f520c8b907e29a2f2193c48fd67e036163ac415f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationcombinations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-8f0ebd226b8013275e12e4709f98bce6-0d7728bb)
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-3314cc623982b6632dcee2360b8f4c6f-0d7728bb)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0d7728bb)
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-0d7728bb)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.micro [...]

2022-09-09 23:55 UTC, opbld33 commented
Docs Build status updates of commit _[e74ef65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e74ef654c4adcb1c99c37260253c2a9678379ca8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrengths-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengths-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengths-overview?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-bfb1d5e8d42b2de6652621ddc2db3147-ee53f9a6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ee53f9a6)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md] [...]

2022-09-10 00:05 UTC, opbld33 commented
Docs Build status updates of commit _[116c4a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/116c4a355f4e07bda4468a497e10b9c5b067a916)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c53f89f1)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob [...]

2022-09-10 00:11 UTC, mmcla commented
@FaithOmbongi - thank you again for all of your hard work, we're getting close to finished! I have all of your comments addressed and integrated, and three last things I'm waiting on from you:

- Confirmation of whether authenticationstrengthroot-list-policies.md is the correct file name
- Example of including @odata.context for conditionalaccesspolicy-get.md and conditionalaccessroot-list-policies.md
- How to handle authenticationstrengthpolicy-usage.md, which wasn't autogenerated. Adapt another file? Start by hand?

Thank you!

2022-09-12 10:57 UTC, FaithOmbongi commented
> 

Hi @mmcla -

1. Yep, we'll keep that file name.
2. See snippet from a payload when I ran the GET /policies/conditionalAccessPolicies endpoint in Graph Explorer

```
"grantControls": {
                "operator": "OR",
                "builtInControls": [
                    "block"
                ],
                "customAuthenticationFactors": [],
                "termsOfUse": [],
                "authenticationStrength@odata.context": "https://graph.microsoft.com/beta/$metadata#policies/conditionalAccessPolicies('7411e485-23e5-4ebb-bb63-c9ead7e01a5b')/grantControls/authenticationStrength/$entity",
                "authenticationStrength": null
            }
```
3. See the template attached [authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/files/9547307/authenticationstrengthpolicy-usage.md)

2022-09-13 00:30 UTC, opbld30 commented
Docs Build status updates of commit _[4f75d64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f75d647d5fc78ea6b41e43ffbf4d8c89d5ccb82)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-8c82ddd5)
[api-reference/beta/resources/authenticationstrengthusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthusage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-d47568d5fd75cedc1fa78be02c7c4552-8c82ddd5)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8c82ddd5)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/ [...]

2022-09-13 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[c0549dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0549dd6f353b081770a491c4f909c0183bb53b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-ad6a9931)
[api-reference/beta/resources/authenticationstrengthusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthusage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-d47568d5fd75cedc1fa78be02c7c4552-ad6a9931)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ad6a9931)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/ [...]

2022-09-13 00:38 UTC, opbld32 commented
Docs Build status updates of commit _[f787d4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f787d4f59c21474a3242bcb8578407a539f0033a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationstrengthpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthpolicy?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0f99bafbe7367b12f5913e29072b703d-34f3613b)
[api-reference/beta/resources/authenticationstrengthusage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/resources/authenticationstrengthusage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationstrengthusage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-d47568d5fd75cedc1fa78be02c7c4552-34f3613b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-34f3613b)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/ [...]

2022-09-13 00:43 UTC, opbld32 commented
Docs Build status updates of commit _[1abfb65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1abfb65a4da18a80a945c7fd86936484d2bc776e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-679887c3)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth- [...]

2022-09-13 00:51 UTC, mmcla commented
@FaithOmbongi - last things incorporated, I think. Do we need to add anything to the changelog for the usage API?

2022-09-15 19:02 UTC, opbld31 commented
Docs Build status updates of commit _[3bbd398](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bbd3985ad3bf2d1ce3ac15fbdf58f91d9b23cad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-167cba0f)

<a id="167cba0f"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 3bbd3985ad3bf2d1ce3ac15fbdf58f91d9b23cad in branch mmcla-auth-strengths of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 8d8b862c00b04c218107dde07ec1cf2640ff9e29). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209151902161604-18164/BuildReport?accessString=f8de476d921cf597c07852aed81ccb4bcc940a41aa5ebe517137eab5638f4177).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 14:42 UTC, opbld31 commented
Docs Build status updates of commit _[7872c89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7872c8906632a27ae723cc572aff44b9d523c628)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7f304109)
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-doc [...]

2022-09-26 19:04 UTC, FaithOmbongi requested changes
Hi @mmcla - 

Re-reviewed and left suggestions for minor fixes prior to approval.

I took a stab at restructuring the flow of your Overview and created a PR here https://github.com/microsoftgraph/microsoft-graph-docs/pull/18365. Feel free to fetch the changes into your PR and make edits as required.

2022-10-06 20:55 UTC, opbld32 commented
Learn Build status updates of commit _[e7e8e1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7e8e1d5b01d52c4bc0ea60c313e9858cd4fc5f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-06 20:57 UTC, opbld31 commented
Learn Build status updates of commit _[0a4c30f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a4c30f8a18f39154c9d37e3e797e1bf1ee322d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-06 21:09 UTC, opbld32 commented
Learn Build status updates of commit _[449a04b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/449a04b140ed6ca8c262359e02c52401027409ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-06 21:13 UTC, opbld34 commented
Learn Build status updates of commit _[5ba066e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ba066ed329f1858022d838d5772647053c36e49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-07 00:04 UTC, opbld30 commented
Learn Build status updates of commit _[37dc542](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37dc542ffa63c97133be2086bfe921249e2eaaa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-07 00:25 UTC, opbld30 commented
Learn Build status updates of commit _[6b74511](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b745111a89b0e615a70458e1b6454f68782d042)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-07 00:32 UTC, opbld32 commented
Learn Build status updates of commit _[0f6107b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f6107bf6bb0b5decf036f88e5c4e3d190ef7c3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-07 16:32 UTC, opbld33 commented
Learn Build status updates of commit _[ce8dad0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce8dad0cd79b67642de6f86719f4e6b0a4cee79e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-12 04:13 UTC, opbld32 commented
Learn Build status updates of commit _[0736c91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0736c91548c73d7832ac726cc9aeccb27aa28248)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationcombinationconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcombinationconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcombinationconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcombinationconfiguration-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodmodedetail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationmethodmodedetail-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationmethodmodedetail-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-delete-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-delete-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-findbymethodmode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-findbymethodmode?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-list-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-list-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-post-combinationconfigurations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-post-combinationconfigurations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-update?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-updateallowedcombinations.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-updateallowedcombinations?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthpolicy-usage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthpolicy-usage.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthpolicy-usage?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-delete-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-delete-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-delete-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-authenticationmethodmodes.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-authenticationmethodmodes?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/authenticationstrengthroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/authenticationstrengthroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationstrengthroot-post-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-list-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mmcla-auth-strengths/api-reference/beta/api/conditionalaccessroot-list-policies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-beta&branch=pr-en-us-18164) (graph-rest-beta) |
[api-reference/beta/resources/authenticationcombinationconfiguration.md](https://github.com/microsoftg [...]

2022-10-12 07:03 UTC, FaithOmbongi approved these changes
Thank you, @mmcla, for your work on this PR. Approved.

2022-10-12 17:03 UTC, merged