Caleb b auth context ga
microsoftgraph/microsoft-graph-docs pull request #18214
Opened 2022-08-28 07:17 UTC by bakerCaleb

Publishing authenticationContextClassReference API to V1.0 endpoint. Changed from beta endpoint include 1) added delete API 2) following guidance from MS Graph review, switch create action from post to patch

2022-08-28 07:17 UTC, opbld32 commented
Docs Build status updates of commit _[56ef056](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56ef056dd01c436fb33c904637cd54d5e3ce5988)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-221c1e14)

<a id="221c1e14"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 56ef056dd01c436fb33c904637cd54d5e3ce5988 in branch CalebB-AuthContextGA of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit b009273bdd5da88d6f6d59b8d422cbc3de644a4e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208280717240089-18214/BuildReport?accessString=5b1918c95dc27b5b01f4eb8c23469646eab5bfb1c6c0dbe3970fff5136d6d24b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-28 07:46 UTC, opbld30 commented
Docs Build status updates of commit _[fd9ef13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd9ef133fde06318bf299aa1c7f1675e64c68aad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d9c529e1)

<a id="d9c529e1"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit fd9ef133fde06318bf299aa1c7f1675e64c68aad in branch CalebB-AuthContextGA of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit b009273bdd5da88d6f6d59b8d422cbc3de644a4e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208280745568000-18214/BuildReport?accessString=77711230a75145a655b683a7bfdb10cff413b578c06970b10a41de31b07cc430).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-28 07:49 UTC, opbld30 commented
Docs Build status updates of commit _[f239cc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f239cc06cfac0ef2632d36588d290d8d04163275)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d223f217)

<a id="d223f217"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit f239cc06cfac0ef2632d36588d290d8d04163275 in branch CalebB-AuthContextGA of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit b009273bdd5da88d6f6d59b8d422cbc3de644a4e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208280749012092-18214/BuildReport?accessString=2bed0eb50bf8dc25d573aec453d186effa7ef067eb8d594611ab5936ee5f18f0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-28 07:50 UTC, opbld34 commented
Docs Build status updates of commit _[c04e18d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c04e18da51edb6d994b86342efc875d41fdf0d79)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6d128218)

<a id="6d128218"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit c04e18da51edb6d994b86342efc875d41fdf0d79 in branch CalebB-AuthContextGA of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit b009273bdd5da88d6f6d59b8d422cbc3de644a4e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208280750128790-18214/BuildReport?accessString=e5cf23cd2b9f39c89d16f44bbb7f1a5547b9e084d53f2f91181be28c28baab6f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 17:36 UTC, opbld34 commented
Docs Build status updates of commit _[d1bd2d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1bd2d700d539f6225578e004c839453bf0ab961)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :x:Error | | [Details](#user-content-d5f59d6180ec3c91d3a9e4ffc9e88860-7023c6f2)
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :x:Error | | [Details](#user-content-d60e9ef3f521ad0a3ccb038df2d5c924-7023c6f2)
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :x:Error | | [Details](#user-content-86fbfe47bc96165f27244fc65c94eaca-7023c6f2)
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :x:Error | | [Details](#user-content-3c920b0ca10f64060d2234902f9cf143-7023c6f2)
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :warning:Warning | | [Details](#user-content-60b55508c03c56facb4393f8fd34c387-7023c6f2)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-7023c6f2)

<a id="d5f59d6180ec3c91d3a9e4ffc9e88860-7023c6f2"></a>
### [api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md)
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-authenticationcontextclassreference-csharp-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-authenticationcontextclassreference-javascript-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-authenticationcontextclassreference-objc-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-authenticationcontextclassreference-java-snippets.md'.`````

<a id="d60e9ef3f521ad0a3ccb038df2d5c924-7023c6f2"></a>
### [api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md)
 - **Line 71, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-authenticationcontextclassreference-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-authenticationcontextclassreference-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-authenticationcontextclassreference-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-authenticationcontextclassreference-java-snippets.md'.`````

<a id="86fbfe47bc96165f27244fc65c94eaca-7023c6f2"></a>
### [api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md)
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-authenticationcontextclassreference-javascript-snippets.md'.`````

<a id="3c920b0ca10f64060d2234902f9cf143-7023c6f2"></a>
### [api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md)
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/create-authenticationcontextclassreference-csharp-snippets.md'.`````
 - **Line 85, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/create-authenticationcontextclassreference-javascript-snippets.md'.`````
 - **Line 89, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/create-authenticationcontextclassreference-objc-snippets.md'.`````
 - **Line 93, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/create-authenticationcontextclassreference-java-snippets.md'.`````

<a id="60b55508c03c56facb4393f8fd34c387-7023c6f2"></a>
### [api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md)
 - **Line 22, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-list-authenticationcontextclassreferences.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-7023c6f2"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5161, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-list-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311730383412-18214/BuildReport?accessString=7faf558c0134e1ca6c5f2b049f927bf0165ee0a46f1db6a141d7085a8df10678).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warn [...]

2022-08-31 17:59 UTC, opbld34 commented
Docs Build status updates of commit _[e962fb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e962fb4cd303a71e8972ca15ff45c3cf1e6d277a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :x:Error | | [Details](#user-content-766e7f7e6d2c632288a3651b7003759a-90d64de4)

<a id="766e7f7e6d2c632288a3651b7003759a-90d64de4"></a>
### [api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md)
 - **Line 69, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-authenticationcontextclassreference-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-authenticationcontextclassreference-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-authenticationcontextclassreference-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-authenticationcontextclassreference-java-snippets.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311756497684-18214/BuildReport?accessString=58fc6f8116b22c6c601903fda64d6d6d058634f74cfb1adbfedc65c1e0a047ff).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 18:18 UTC, opbld33 commented
Docs Build status updates of commit _[b84353d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b84353d48fedb53758d00b202748f1ad5fff1948)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311810270736-18214/BuildReport?accessString=b01dda7754fa971bb4e50506c9eebe7db8940ff5bbfb9327cfb0a0f619ec31db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 19:11 UTC, opbld32 commented
Docs Build status updates of commit _[5a0e55f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a0e55fce42eefdf7162076013c17de6d3cab1d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311908518415-18214/BuildReport?accessString=f551986e674fb2f473e474ce6392e5e1b35e3c9c2661f5a2200e860b9076cd0c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 19:51 UTC, opbld32 commented
Docs Build status updates of commit _[bf743f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf743f2e2b6285e82ecc3f0e88fff80f9aa34f92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311949163396-18214/BuildReport?accessString=08b07f66506e99cf2990e73c60c8cb0668ef7197230087d6f2e8b4ef4e5f27fc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 17:53 UTC, vids-dev approved these changes

2022-09-09 20:59 UTC, bakerCaleb commented
Created tracking request: https://identitydivision.visualstudio.com/Technical%20Content/_workitems/edit/2063117

2022-09-14 18:50 UTC, FaithOmbongi requested changes
Hi @bakerCaleb - I've left inline suggestions for fixes and requested changes. In addition:
- I see the beta doc doesn't have a Delete operation and there are some incorrect references. I also see that some of the errors in your v1.0 docs must have been inherited from the beta docs. I'll push a commit to clean up the beta docs.
- GLOBAL: You're missing the HTTP request block. For every response, there must be a preceding request. Please see the LIST file for a sample structure and add such section for all other operations.
- GLOBAL: The author should be your GitHub alias, not MSFT alias.
- File name fix: conditionalaccessroot-patch-authenticationcontextclassreferences.md  => conditionalaccessroot-post-authenticationcontextclassreferences.md

Will be happy to work on a How-To/Tutorial for this and more CA API capabilities. Let's chat internally about this.

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
> +}-->
You're missing the HTTP request here.
PS: Make sure you add the closing backticks - GitHub makes them "disappear" in suggestions like this.
```suggestion
}-->
```msgraph-interactive
GET https://graph.microsoft.com/v1.0/identity/conditionalAccess/authenticationContextClassReferences
```

```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
> +> **Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
Template changed
```suggestion
> **Note:** The response object shown here might be shortened for readability.
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-get.md
> +This method supports the `$select` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Duplicate section.
Your API also doesn't support $select
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
> +This method supports the `$filter` and `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Your API doesn't support `$select`
```suggestion
This method supports the `$filter` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-get.md
> +If successful, this method returns a `200 OK` response code and the requested [authenticationContextClassReferences](../resources/\authenticationcontextclassreference.md) object in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and an [authenticationContextClassReference](../resources/authenticationcontextclassreference.md) object in the response body.
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-get.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-get.md
> +
Add the HTTP Request here enclosed in backticks.

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-get.md
> +> **Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
```suggestion
> **Note:** The response object shown here might be shortened for readability.
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-update.md
> +For the list of properties, see [authenticationContextClassReference](../resources/authenticationContextClassReference.md).
The beta docs are based on an old template. Use this template and update the placeholder `**TODO: Add Description**`.
```suggestion
[!INCLUDE [table-intro](../../includes/update-property-table-intro.md)]


|Property|Type|Description|
|:---|:---|:---|
|displayName|String|**TODO: Add Description**|
|description|String|**TODO: Add Description** |
|isAvailable|Boolean|**TODO: Add Description** |
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-update.md
> +# [HTTP](#tab/http)
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-update.md
> +PATCH https://graph.microsoft.com/v1.0/identity/conditionalAccess/authenticationContextClassReferences
I'm sure it should have an ID
```suggestion
PATCH https://graph.microsoft.com/v1.0/identity/conditionalAccess/authenticationContextClassReferences/c1
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-update.md
> +    "id": "c1",
Remove id from PATCH body to avoid the confusion that it can be updated
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md
> +---
File name fix: conditionalaccessroot-post-authenticationcontextclassreferences.md

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md
> +# [HTTP](#tab/http)
```suggestion

```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md
> +HTTP/1.1 200 OK
```suggestion
HTTP/1.1 201 Created
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +This method does not support optional query parameters to customize the response.
Section N/A to DELETE operations
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +This method will return an error when deleting a published authenticationContextClassReference. A published authenticationContextClassReference has has the property isAvailable is set to true. The er
```suggestion
This method will return a `403 Forbidden` error code when deleting a published authenticationContextClassReference (where **isAvailable** is set to `true`). If authenticationContextClassReference, though unpublished, is used by any Conditional Access policy, this method will return a `400 Bad Request` error code.
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +# [HTTP](#tab/http)
Add HTTP block after the HTML comment block below
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +> **Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
```suggestion
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +          - name: Authentication context class references
Maybe "Authentication context" instead - to reference the capability instead of the resource name?
```suggestion
          - name: Authentication context
```

2022-09-14 18:50 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
Corrected the changelog.
PS: Just copy the changelog record from the changelog stub instead of reusing one that's already published. See quick [demo](https://msit.microsoftstream.com/video/eac90840-98dc-bd6c-a050-f1ed04505185).
```suggestion
        {
          "Id": "0d721125-f1c0-44e7-96fa-dd4773cf2445",
          "ApiChange": "Resource",
          "ChangedApiName": "authenticationContextClassReferences",
          "ChangeType": "Addition",
          "Description": "Added the **authenticationContextClassReferences** relationship to the [conditionalAccessRoot](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessRoot?view=graph-rest-1.0) resource.",
          "Target": "conditionalAccessRoot"
        },
        {
          "Id": "0d721125-f1c0-44e7-96fa-dd4773cf2445",
          "ApiChange": "Resource",
          "ChangedApiName": "authenticationContextClassReference",
          "ChangeType": "Addition",
          "Description": "Added the [authenticationContextClassReference](https://docs.microsoft.com/en-us/graph/api/resources/authenticationContextClassReference?view=graph-rest-1.0) resource and its associated methods.",
          "Target": "authenticationContextClassReference"
        }
```

2022-09-14 18:50 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": "Conditional Access"
```suggestion
      "SubArea": "Identity and sign-in"
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md
> +In the request body, supply a JSON representation of a [authenticationContextClassReference](../resources/authenticationcontextclassreference.md) object.
```suggestion

You can specify the following properties when creating an **authenticationContextClassReference**.

|Property|Type|Description|
|:---|:---|:---|
| id | String|**TODO: Add Description** Required.|
|displayName|String|**TODO: Add Description** Optional.|
|description|String|**TODO: Add Description** Optional.|
|isAvailable|Boolean|**TODO: Add Description** Optional.|
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +Delete an [authenticationContextClassReference](../resources/authenticationcontextclassreference.md) object.
```suggestion
Delete an [authenticationContextClassReference](../resources/authenticationcontextclassreference.md) object that's not published or used by a conditional access policy.
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +description: "Delete an authenticationContextClassReference object."
```suggestion
description: "Delete an authenticationContextClassReference object that's not published or used by a conditional access policy."
```

2022-09-14 18:50 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +            - name: Authentication context class references
```suggestion
            - name: Authentication context class reference
```

2022-09-14 20:08 UTC, bakerCaleb commented on api-reference/v1.0/resources/authenticationcontextclassreference.md
> +|id|String| Identifier used to reference the authentication context class. The id is used to trigger step-up authentication for the referenced authentication requirements and is the value that will b
I'm making this change.

2022-09-14 20:08 UTC, bakerCaleb commented on api-reference/v1.0/resources/authenticationcontextclassreference.md
> +|isAvailable|boolean| Indicates whether the authenticationContextClassReference has been published by the security admin and is ready for use by apps. When it is set to `false` it should not be shown
I'm making this change.

2022-09-14 20:08 UTC, bakerCaleb commented on api-reference/v1.0/resources/authenticationcontextclassreference.md
> +      "isAvailable": "boolean",
I'm making this change.

2022-09-14 20:23 UTC, opbld30 commented
Docs Build status updates of commit _[b29f657](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b29f6574096ba4f89a0ecc06e7b527a58b80bbd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142018173623-18214/BuildReport?accessString=89138ef1d7e8d5b6ae4c26a913274b2f6103e1ac2310c777551139107955104d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 20:24 UTC, bakerCaleb commented on api-reference/v1.0/resources/authenticationcontextclassreference.md
> +|isAvailable|boolean| Indicates whether the authenticationContextClassReference has been published by the security admin and is ready for use by apps. When it is set to `false` it should not be shown
I'll also update the description to explain the authcontext is still shown in the CA admin ux, but not picker UX, built into apps.

2022-09-14 20:25 UTC, opbld33 commented
Docs Build status updates of commit _[1720e96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1720e96eb853fe11ff195a11c1f53a7f6bef0def)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142018538306-18214/BuildReport?accessString=24e19e6e2140eb98c50f27c8467ff3dff6cefb3f070dd12848382802d9abc358).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 20:48 UTC, opbld31 commented
Docs Build status updates of commit _[4a1821a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a1821ac8a9a8274f3b65ade95eb599e5ff13b74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-1195279b)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-1195279b"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142045550280-18214/BuildReport?accessString=011c9de3c3ee75e64dc5ac1ddd667c9ff3245703215b784ad27c20ae4a291f40).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 20:54 UTC, opbld34 commented
Docs Build status updates of commit _[f43abee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f43abee61efd7e991b73cc60bb98f8963ce545f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-07e6eb34)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-07e6eb34"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142052136789-18214/BuildReport?accessString=85bebf9c60be7c743b1897cc52d73548d3618a7c72e0b999139b7e9ed6100480).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 20:56 UTC, opbld34 commented
Docs Build status updates of commit _[6849772](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68497724606577147133d88eaa621b0082b8603e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-d46dc69f)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-d46dc69f"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142054318871-18214/BuildReport?accessString=d09fc73b2d4cfffc14cadea49782457bc77c3d68616b4033248d238705566fc9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 20:58 UTC, opbld30 commented
Docs Build status updates of commit _[655bd98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/655bd9857494cd0890b9fc6f45bfa06e493d6b43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-547c1c8e)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-547c1c8e"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142054460837-18214/BuildReport?accessString=89d285c88e40e087e82d788cf0c97aa52ad07a9e5c911a4a8751cf01de92e309).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:06 UTC, opbld34 commented
Docs Build status updates of commit _[8e598cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e598cc64198d5b110d46462f6bce47225dfa0f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-e406ce22)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-e406ce22"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142104246390-18214/BuildReport?accessString=e29a507984bf64157b5281fbf4d310e1ab75522dcb353bf6af1b069be1e8753b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:08 UTC, opbld31 commented
Docs Build status updates of commit _[f175ad1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f175ad194d5826dec955d79816fd6a0946ebe217)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-c359e3a9)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-c359e3a9"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142105035754-18214/BuildReport?accessString=b8f94e0931f5f770dcde4a7ba1ec1394de122efc383b796b59ea424eab8ca534).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:30 UTC, opbld32 commented
Docs Build status updates of commit _[c94c643](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c94c64372c41c0b500fc89529b9b76aaa0353edc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-61fbe232)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-61fbe232"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142127457205-18214/BuildReport?accessString=cfad9e5677b7c58a72ba23ea18d1517df3b77330f48ead3bfd5795363fbb016c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:32 UTC, opbld33 commented
Docs Build status updates of commit _[028c2df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/028c2df0f95e36e71f4868364645cc3c4a6da28d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-52739974)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-52739974"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142128171117-18214/BuildReport?accessString=82d4cee83a2b9273b84c0f432c5e294a4381bb5d1d24c2e0c192524c7541a5a7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:35 UTC, opbld32 commented
Docs Build status updates of commit _[a577eed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a577eed3e8430175c57a445a7fdb32604b283f61)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-84da7e03)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-84da7e03"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142130533087-18214/BuildReport?accessString=23c2ca4553602ffb2ca1eee4441cae7d0218c0b91d7f660e0d8db4c0ef419d17).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:39 UTC, bakerCaleb commented on api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md
> +---
The create is a PATCH. The MS Graph API review team had us switch this to a PATCH from a POST because the IDs come from a fixed set of values.

2022-09-14 21:39 UTC, opbld32 commented
Docs Build status updates of commit _[9ad85d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ad85d74de1fd8a2a63235faf50efe0f2482a303)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-2b6068c8)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-2b6068c8"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142136513169-18214/BuildReport?accessString=bfb238fc670fb0bf324e7a3e0d90a7cbb0c61b5e9c53e54087114ac35af471e8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:42 UTC, opbld32 commented
Docs Build status updates of commit _[b3f4ff4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3f4ff40de55e9d11ad8cad437e390276c5a0812)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-3c5d33a2)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-3c5d33a2"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142140377065-18214/BuildReport?accessString=d082ea6b84254cc064bbbed162a77f172e2469fd13d64ceb1827ce578c5fc750).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:46 UTC, opbld34 commented
Docs Build status updates of commit _[ea4f321](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea4f3218e31209ba84a26ff3415a2b5d9eac0f9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-84f3e2cb)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-84f3e2cb"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142144200060-18214/BuildReport?accessString=1f97d5d3d36afc29b16f47ba1b7c64e81c19c7d474451db48ca9ae0ffaa741c3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 21:50 UTC, opbld31 commented
Docs Build status updates of commit _[d1bee77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1bee77d9a958d3ce9caf3bb8e553a306ac40530)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-4e454d47)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-4e454d47"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142144372496-18214/BuildReport?accessString=94e2548a8861e35cfd460263fa716917b968f06658bedfa47c0856c7a0b5eba9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 23:29 UTC, opbld30 commented
Docs Build status updates of commit _[0bd520d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bd520db8ca0de5121e32c3abba36b24c3709a9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-f9f09d4b)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-f9f09d4b"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142327441779-18214/BuildReport?accessString=b28eebfccaf5248beab24c1249d30cffbfb5c6f4b385ca11877b9f7dada626b0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 23:42 UTC, bakerCaleb commented on api-reference/v1.0/resources/authenticationcontextclassreference.md
> +| [Delete authenticationContextClassReference](../api/authenticationcontextclassreference-delete.md) | [authenticationContextClassReference](authenticationContextClassReference.md) | Delete an authen
This should be Patch, following MS Graph API review guidance

2022-09-14 23:43 UTC, opbld30 commented
Docs Build status updates of commit _[254d68e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/254d68eb973dc3e714232f5d1ca6d30bc2b3ae39)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-9f0f4777)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-9f0f4777"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142341188941-18214/BuildReport?accessString=38791224e805a1a691d35833d5d1ab659cd6d09fe5bc48bd74878fa2304789c5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 23:45 UTC, opbld32 commented
Docs Build status updates of commit _[686bd3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/686bd3f00e1e993a84772c9f135e24b04d152894)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-ac223849)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-ac223849"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209142343231783-18214/BuildReport?accessString=7b2efea346f92cadc12ef5a523966cd194111717ad31089023603aafa06a1edd).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 00:21 UTC, opbld34 commented
Docs Build status updates of commit _[58d2618](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58d26182e304f72c0b3ce910b2968fa9739ccfd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-59f00bf7)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-patch-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-59f00bf7"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150016579179-18214/BuildReport?accessString=2bacbd5e7a8939c00191e31cd7aec810f713de3ce5c7d2e97f24e88af86e7098).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 00:23 UTC, opbld31 commented
Docs Build status updates of commit _[081a497](https://github.com/microsoftgraph/microsoft-graph-docs/commits/081a497cd451be2acf7c02edf4981872013a803a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-6e14d3ea)
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-60b55508c03c56facb4393f8fd34c387-6e14d3ea)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6e14d3ea)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-patch-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-6e14d3ea"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="60b55508c03c56facb4393f8fd34c387-6e14d3ea"></a>
### [api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md)
 - **Line 21, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-6e14d3ea"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150017446060-18214/BuildReport?accessString=397d215f073ffb92f5a169747b8d4bee19723c2fa4c7a5771b383fe417879851).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 00:25 UTC, opbld34 commented
Docs Build status updates of commit _[a65a9da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a65a9da872d3e73495fbd2419fae6a8052357446)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-31fb1eb4)
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-60b55508c03c56facb4393f8fd34c387-31fb1eb4)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-31fb1eb4)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-patch?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-31fb1eb4"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="60b55508c03c56facb4393f8fd34c387-31fb1eb4"></a>
### [api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md)
 - **Line 21, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-31fb1eb4"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150021177594-18214/BuildReport?accessString=25cee58e2ddf22b81fc4d44e581513b30c20d1f37863d4488c72f97c2163ad94).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 04:52 UTC, opbld30 commented
Docs Build status updates of commit _[783c791](https://github.com/microsoftgraph/microsoft-graph-docs/commits/783c7919b622ed998b83546c1c50dbdef9624ced)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3d3d4c81)

<a id="3d3d4c81"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 783c7919b622ed998b83546c1c50dbdef9624ced in branch CalebB-AuthContextGA of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit dd95ace388005a98d2cc157d1208aad06cfd4300). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150452168319-18214/BuildReport?accessString=a0755dd0af5a03f4c451d74d7d89591d0a736f9cc8223b450650453ee02cd614).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 05:03 UTC, opbld31 commented
Docs Build status updates of commit _[0f95377](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f95377236fd18b8740be4eeca992bc094de5bfb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8defb060)

<a id="8defb060"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 0f95377236fd18b8740be4eeca992bc094de5bfb in branch CalebB-AuthContextGA of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit dd95ace388005a98d2cc157d1208aad06cfd4300). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150503095437-18214/BuildReport?accessString=32540e8a59d93d4583d27b3bc42efa2984fd3cc96fc4a52c0cc259e5967e504e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 05:06 UTC, opbld31 commented
Docs Build status updates of commit _[36e4a69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36e4a6932037f6d18f04c1e09bd74c83fb235220)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-c6b0ca24)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-c6b0ca24)
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-patch?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-c6b0ca24"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-c6b0ca24"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150504466733-18214/BuildReport?accessString=21facd5ed244f71277ca7edfc3f114bba62f7d2057d27d8e9bca4bd4a76b9c3c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 05:25 UTC, opbld34 commented
Docs Build status updates of commit _[758cf15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/758cf15e2f12ec18f148ad2514e5c2a2679f8cbc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-5b36f75b)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-5b36f75b)
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-5b36f75b"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-5b36f75b"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5001, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccesspolicy-create.md'.`````
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150521467012-18214/BuildReport?accessString=fb23a8a9907c8d3674ff87f4059a343989ccaee73846e2c00c988ac86e7bf72c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 05:33 UTC, opbld34 commented
Docs Build status updates of commit _[eaef0bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaef0bbc5f09e41ba876c5a7f47e68b862d0c540)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) | [Details](#user-content-84351f706be61e95102727df28f589f4-35986f72)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-35986f72)
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="84351f706be61e95102727df28f589f4-35986f72"></a>
### [api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md)
 - **Line 23, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-35986f72"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5001, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccesspolicy-create.md'.`````
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150531474373-18214/BuildReport?accessString=5f0d7056bb532cebe35ff69b4f4b3a338ce8446b146f48b2e710133353a32588).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[fe0240b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe0240b811c7a9c45cd3a84d1602251c20bcd06b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d3be3b21)
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-d3be3b21"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5001, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccesspolicy-create.md'.`````
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209150544343122-18214/BuildReport?accessString=490b4fb7450e9d51c795aecfd5039c2f3557202072de07483791f5d62b3acd0c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 09:16 UTC, FaithOmbongi requested changes
Hi @bakerCaleb - Left suggestions for fixes related to the Create/POST file name + deleting the `# [HTTP](#tab/http)` line that will be added by the snippets generator when it autogenerates code snippets for your APIs on the first Tuesday after you publish this PR.

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationcontextclassreference.md
> +|isAvailable|boolean| Indicates whether the authenticationContextClassReference has been published by the security admin and is ready for use by apps. When it is set to `false`, it should not be show
```suggestion
|isAvailable|boolean| Indicates whether the authenticationContextClassReference has been published by the security admin and is ready for use by apps. When it is set to `false`, it should not be shown in the selection UX used to tag resources with authentication context class values. It will still be shown in the Conditional Access policy authoring experience. <br/> Supports `$filter` (`eq`). |
```

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-create.md
> +# [HTTP](#tab/http)
Will be added by the snippets generator
```suggestion
```

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-create.md
> +---
File name fix:

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-delete.md
> +# [HTTP](#tab/http)
Will be added by the snippets generator
```suggestion
```

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-get.md
> +# [HTTP](#tab/http)
Bump - This line will be added by the snippets generator

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/authenticationcontextclassreference-update.md
> +}
Add closing backticks after bracket.

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md
> +# [HTTP](#tab/http)
Will be added by the snippets generator
```suggestion
```

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/resources/authenticationcontextclassreference.md
> +| [Create authenticationContextClassReference](../api/authenticationcontextclassreference-create.md)) | [authenticationContextClassReference](authenticationContextClassReference.md) | Create a new au
Following the file naming guidance:

- Create operations have the syntax: {parentEntityName}-post-{navigationPropertyName}.md. Therefore, **conditionalaccessroot-post-authenticationcontextclassreferences.md**
- Update operations have the syntax - {entityName}-update.md; So line 23 is correct.

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +              href: api/conditionalaccesspolicy-create.md
Following the file naming guidance, Create operations have the syntax: {parentEntityName}-post-{navigationPropertyName}.md. Therefore, **conditionalaccessroot-post-policies.md** is correctly named.
```suggestion
              href: api/conditionalaccessroot-post-policies.md
```

2022-09-15 09:16 UTC, FaithOmbongi commented on api-reference/v1.0/toc.yml
> +              href: api/conditionalaccessroot-patch-authenticationcontextclassreferences.md
Following the file naming guidance, Create operations have the syntax: {parentEntityName}-post-{navigationPropertyName}.md. Therefore, **conditionalaccessroot-post-authenticationcontextclassreferences.md**

PATCH is handled by the -update.md file.
```suggestion
              href: api/conditionalaccessroot-post-authenticationcontextclassreferences.md
```

2022-09-16 06:39 UTC, opbld34 commented
Docs Build status updates of commit _[2dd4634](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2dd4634d93f0be3ed4bcd250441140ad5271a635)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-2d71f62f)
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-patch?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-2d71f62f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5001, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccesspolicy-create.md'.`````
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````
 - **Line 5059, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/authenticationcontextclassreference-update.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160637236397-18214/BuildReport?accessString=5a5630572f42c547f7f83544b453fc6fcacfe7034cf8d233b7994cb7760f0f91).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 07:05 UTC, opbld32 commented
Docs Build status updates of commit _[33ed3c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33ed3c5ad77c1cdd590d2adae1ee26719ed8ef50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-60b55508c03c56facb4393f8fd34c387-3a91696a)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-3a91696a)
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.changedapi.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/redirects/.openpublishing.redirection.changedapi.json) | :white_check_mark:Succeeded | |

<a id="60b55508c03c56facb4393f8fd34c387-3a91696a"></a>
### [api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md)
 - **Line 21, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authenticationcontextclassreference-patch.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-3a91696a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml)
 - **Line 5001, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccesspolicy-create.md'.`````
 - **Line 5055, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/conditionalaccessroot-patch-authenticationcontextclassreferences.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160703302395-18214/BuildReport?accessString=d71499560c1f4d9f6cba8829ce235ed832d7c69839280a52f31eec0c14082b5d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 07:19 UTC, opbld34 commented
Docs Build status updates of commit _[c3f8019](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3f8019590f23fc20c28059b4f23c10a63710e82)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-60b55508c03c56facb4393f8fd34c387-0823c6c9)
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.changedapi.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/redirects/.openpublishing.redirection.changedapi.json) | :white_check_mark:Succeeded | |

<a id="60b55508c03c56facb4393f8fd34c387-0823c6c9"></a>
### [api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md)
 - **Line 21, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authenticationcontextclassreference-patch.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160717402109-18214/BuildReport?accessString=151e2302ab6d74443487e267a9c258d172014c7ce06648c53dcf2bcf30cd4a7f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 07:49 UTC, opbld33 commented
Docs Build status updates of commit _[3e79e5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e79e5cc9fbfd3d7af696e74c92a34150b570da5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) | [Details](#user-content-60b55508c03c56facb4393f8fd34c387-0758be00)
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.changedapi.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/redirects/.openpublishing.redirection.changedapi.json) | :white_check_mark:Succeeded | |

<a id="60b55508c03c56facb4393f8fd34c387-0758be00"></a>
### [api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md)
 - **Line 21, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/authenticationcontextclassreference-patch.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160746223908-18214/BuildReport?accessString=0f6f9e71e8296ac3729aea5c11f766c55e1e42b9053e1b14f39559c16c64721a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 07:51 UTC, opbld34 commented
Docs Build status updates of commit _[96448a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96448a290efe3729b8828cd642c8c0c04785baf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.changedapi.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/redirects/.openpublishing.redirection.changedapi.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160747180081-18214/BuildReport?accessString=1b8e7f989679b8cf6d33b14882709e205f4c2946882d5e55eb4b3460d21c8f6a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 08:11 UTC, opbld31 commented
Docs Build status updates of commit _[0ee6194](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ee619446303d827167b2309a248cfc88acbe547)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationcontextclassreference-create?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.changedapi.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/redirects/.openpublishing.redirection.changedapi.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209160808582974-18214/BuildReport?accessString=fa802b8e99de8889fdd3a277f17fdb546130cf6ae45015adc477306ded8c5cb8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 08:51 UTC, FaithOmbongi approved these changes
Hi @bakerCaleb - I pushed a few commits to correct some instances, including the update file name. I gave you the wrong guidance yesterday when I asked you to update the file name to _-patch.md_. I was so out of it, sorry.

Everything looks good to go. Approved.

I'll reach out internally about something that needs to be done to prevent PowerShell cmdlets for the POST from being generated for v1.0.

2022-10-04 02:34 UTC, opbld34 commented
Learn Build status updates of commit _[2fcdc45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fcdc45afd6e8675f982f768c902637f47bf6b31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/beta/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-beta&branch=pr-en-us-18214) (graph-rest-beta) |
[api-reference/v1.0/api/authenticationcontextclassreference-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-get?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationcontextclassreference-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/authenticationcontextclassreference-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-update?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/api/conditionalaccessroot-list-authenticationcontextclassreferences.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-authenticationcontextclassreferences?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationcontextclassreference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/authenticationcontextclassreference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationcontextclassreference?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/conditionalaccessroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/resources/conditionalaccessroot.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/conditionalaccessroot?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/authenticationcontextclassreference-delete?view=graph-rest-1.0&branch=pr-en-us-18214) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[redirects/.openpublishing.redirection.changedapi.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CalebB-AuthContextGA/redirects/.openpublishing.redirection.changedapi.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040231213932-18214/BuildReport?accessString=14c36dced07b1fafeba97d80952a92cc5ad6556d4de11e59c18ab2a726bc29e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 02:52 UTC, merged