Add Bookmark.read.all And Acronym.read.all Permission
microsoftgraph/microsoft-graph-docs pull request #18220
Opened 2022-08-29 07:24 UTC by ZChristine

Add bookmark.read.all and acronym.read.all permission

2022-08-29 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[d337b52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d337b528fec29f38842855c7ce2ddd98f3e295d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208290724097968-18220/BuildReport?accessString=8d1567074178804b5621a86f3173dee4d3f040412be06d215c60c69b43a6def3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 03:18 UTC, ZChristine commented
@Danielabom Can you help review the PR as the deployment has been finished and it is ready for review based on following doc and permission request?

2022-09-21 17:03 UTC, opbld30 commented
Docs Build status updates of commit _[802232a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/802232a15a34ccaf6fcf2a27378d234baddb4323)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209211701095430-18220/BuildReport?accessString=3845c719c22a831614edd91356259a7ce92f177a697bf035e5a845d48e7c64ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-22 14:07 UTC, FaithOmbongi commented
Hi @ZChristine - I see the permissions onboarding work item shows these permissions are in their final phase of deployment. Once your permissions are deployed, they will be available in the Azure portal and in the [Microsoft Graph service principal](https://graph.microsoft.com/v1.0/servicePrincipals?$filter=displayName+eq+'Microsoft+Graph'&$select=appRoles,oauth2PermissionScopes) object. @Danielabom will review the PR after verifying that deployment. Thanks.

2022-09-23 05:55 UTC, opbld31 commented
Docs Build status updates of commit _[aeddeb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aeddeb4aba2799dee828e03d0dca8de25546f5b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209230552073443-18220/BuildReport?accessString=8e9dbdc5783b803a913252ac4e3c85c5a86f12ee0b8d33eeac7311a47bd270b3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 21:18 UTC, Danielabom approved these changes
Thank you for working on this PR. Approved.

2022-09-23 21:34 UTC, opbld34 commented
Docs Build status updates of commit _[6fc7d92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fc7d926c4d923d5711fbefa27b2c47427c4d38a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209232131198103-18220/BuildReport?accessString=e0f8ef9e2286699a41765330f854be797b123a4cd055764871c0467f53ddf3b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 21:36 UTC, Danielabom commented on concepts/permissions-reference.md
> +| _Acronym.Read.All_ | Read all acronyms | Allows the app to read all acronyms without a signed-in user. | No | No |
@tongzheng94, please update the changelog and it to the PR. For more information, see (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog)

2022-09-23 21:37 UTC, Danielabom requested changes
Please review my comments. Thanks!

2022-09-26 16:45 UTC, opbld34 commented
Docs Build status updates of commit _[f7454d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7454d4cbcb6b281da2421c9984444e97d834cb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209261638575891-18220/BuildReport?accessString=d70de7be0ce65a4791dca528b37a74b05d0108df6f386c193a968112a1043c05).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-10-04 06:09 UTC, opbld32 commented
Learn Build status updates of commit _[e23915b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e23915bdb8320943b72e3a4319699cc4059436ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040607064657-18220/BuildReport?accessString=358d51919e5923bc7eac8bbb3e8b4497f0017a8d01caf1636dddec92e174bd2a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 06:27 UTC, opbld31 commented
Learn Build status updates of commit _[3408684](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3408684f04107c5a5d53b969e5805c8ef6237142)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210040625298337-18220/BuildReport?accessString=f391c3be1128d32456098e3bd176bcff1636d7cbbae82b9870debdbc37f3a5c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 06:30 UTC, ZChristine commented on concepts/permissions-reference.md
> +| _Acronym.Read.All_ | Read all acronyms | Allows the app to read all acronyms without a signed-in user. | No | No |
yes. The strings I document match what's indicated in the "product". Also, I add the change log for the new permissions.

2022-10-04 06:31 UTC, ZChristine commented on concepts/permissions-reference.md
> +| _Acronym.Read.All_ | Read all acronyms | Allows the app to read all acronyms without a signed-in user. | No | No |
> @tongzheng94, please update the changelog and it to the PR. For more information, see (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/211742/Changelog). And a few more reminders discussed in the chat last Monday:
> 
> 1. The strings you document should match what's indicated in the "product".
> 2. You are introducing permissions without indicating/updating the APIs that use them. Which APIs use these permissions? You should update the permissions tables of the APIs/API docs. Otherwise, your hard work won't have visibility or use because the permissions aren't referenced anywhere in the docs.

yes. The strings I document match what's indicated in the "product". Also, I add the change log for the new permissions.

2022-10-05 02:05 UTC, Danielabom requested changes
Hi, the changes look good. Would you mind confirming which APIs will be using these permissions? Is it necessary to mention the new permissions somewhere?

2022-10-10 14:40 UTC, Danielabom approved these changes
Hi Tong, thank you for working on this PR. Changes approved.

2022-10-10 14:43 UTC, opbld32 commented
Learn Build status updates of commit _[4667e30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4667e3031de73843c12dc9eaec2bca70a311af24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210101441160386-18220/BuildReport?accessString=04f8fe905f6a3a679cbb9afba8d3ea6a97b4b3e8e3b9dd97baf134b7f94c82fe).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 02:26 UTC, opbld32 commented
Learn Build status updates of commit _[790e364](https://github.com/microsoftgraph/microsoft-graph-docs/commits/790e3647b3e24a6d8cbb215253ab86ed54579182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-18220) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210110224177634-18220/BuildReport?accessString=e9de0b56af4dec7111743719a4c5648bf7b1e405f1597221e48725cd65fdf9ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 02:31 UTC, merged