Cbagraphv1.0
microsoftgraph/microsoft-graph-docs pull request #18246
Opened 2022-08-30 19:01 UTC by vimrang

Creating msgraph doc for v1.0 for X509 certificate based authentication

2022-08-30 19:05 UTC, opbld33 commented
Docs Build status updates of commit _[63b38e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63b38e4aff3fc762c7f17c156131ad7328a03396)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :x:Error | | [Details](#user-content-e62dceb5b4bd6e8accd6f87702e78240-a7a75516)
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :x:Error | | [Details](#user-content-2b0c26c9a1c3b5b4e93fcc4e3a3787e7-a7a75516)
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :x:Error | | [Details](#user-content-2394cf2431e8bf3f71cdf376fb3fa362-a7a75516)
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :x:Error | | [Details](#user-content-1292cd046400f0d430a155fc312a1bb5-a7a75516)
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :x:Error | | [Details](#user-content-42f5a2379b577dee22075b417d8bb02b-a7a75516)
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :x:Error | | [Details](#user-content-eef21ebed08dc4391c1acdba36539498-a7a75516)
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :x:Error | | [Details](#user-content-8302e33c89d0aab38b2e50c6610c902c-a7a75516)

<a id="e62dceb5b4bd6e8accd6f87702e78240-a7a75516"></a>
### [api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md)
 - **Line 13, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/v1.0-disclaimer.md'.`````
 - **Line 68, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/delete-x509certificateauthenticationmethodconfiguration-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/delete-x509certificateauthenticationmethodconfiguration-javascript-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/delete-x509certificateauthenticationmethodconfiguration-java-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/delete-x509certificateauthenticationmethodconfiguration-go-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/delete-x509certificateauthenticationmethodconfiguration-powershell-snippets.md'.`````
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/delete-x509certificateauthenticationmethodconfiguration-php-snippets.md'.`````

<a id="2b0c26c9a1c3b5b4e93fcc4e3a3787e7-a7a75516"></a>
### [api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md)
 - **Line 13, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/v1.0-disclaimer.md'.`````
 - **Line 72, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-x509certificateauthenticationmethodconfiguration-csharp-snippets.md'.`````
 - **Line 76, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-x509certificateauthenticationmethodconfiguration-javascript-snippets.md'.`````
 - **Line 80, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/get-x509certificateauthenticationmethodconfiguration-java-snippets.md'.`````
 - **Line 84, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/get-x509certificateauthenticationmethodconfiguration-go-snippets.md'.`````
 - **Line 88, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/get-x509certificateauthenticationmethodconfiguration-powershell-snippets.md'.`````
 - **Line 92, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/get-x509certificateauthenticationmethodconfiguration-php-snippets.md'.`````

<a id="2394cf2431e8bf3f71cdf376fb3fa362-a7a75516"></a>
### [api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md)
 - **Line 13, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/v1.0-disclaimer.md'.`````
 - **Line 122, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-x509certificateauthenticationmethodconfiguration-javascript-snippets.md'.`````
 - **Line 126, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/java/update-x509certificateauthenticationmethodconfiguration-java-snippets.md'.`````
 - **Line 130, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/go/update-x509certificateauthenticationmethodconfiguration-go-snippets.md'.`````
 - **Line 134, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/powershell/update-x509certificateauthenticationmethodconfiguration-powershell-snippets.md'.`````
 - **Line 138, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../includes/snippets/php/update-x509certificateauthenticationmethodconfiguration-php-snippets.md'.`````

<a id="1292cd046400f0d430a155fc312a1bb5-a7a75516"></a>
### [api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md)
 - **Line 14, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/v1.0-disclaimer.md'.`````

<a id="42f5a2379b577dee22075b417d8bb02b-a7a75516"></a>
### [api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md)
 - **Line 14, Column 1**: **[Error: include-not-found]** `````Invalid include link: '../../includes/v1.0-disclaimer.md'.`````

<a id="eef21ebed08dc4391c1acdba3 [...]

2022-08-30 19:15 UTC, opbld32 commented
Docs Build status updates of commit _[4c2d192](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c2d192c87a409561c3424473673ea97c38e11c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208301911239556-18246/BuildReport?accessString=9db57eb71cce896f061c601df705d3e2d57821721a0248b467df754b3d06651d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 19:07 UTC, FaithOmbongi requested changes
Thank you @vimrang for your work in this PR. I've left a few comments for minor fixes. Two things to note:

1. For every response, there must be a request. So you must have the http request blocks immediately after the HTML comment blocks. For example, this 👇🏾 is a complete "Request" section in Markdown.

            ### Request
            
            <!-- {
            "blockType": "request",
            "name": "delete_x509certificateauthenticationmethodconfiguration"
            }
            -->
            ```
            DELETE https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/x509Certificate
            ```

2. Given this is the "policy/configuration", it's not cleear what the methods is. Also, is this API related to the [certificateBasedAuthConfiguration resource type and related methods](https://learn.microsoft.com/en-us/graph/api/resources/certificatebasedauthconfiguration?view=graph-rest-1.0). Let's follow up internally and have an end-to-end tutorial for using this new API and any related APIs.

2022-09-20 19:07 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [x509CertificateAuthenticationMethodConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationMethodConfiguration?view=graph
nit: 
```suggestion
          "Description": "Added the [x509CertificateAuthenticationMethodConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationMethodConfiguration?view=graph-rest-1.0) resource type and its associated methods. This resource represents the details of the Azure AD native Certificate-Based Authentication (CBA) in the tenant including whether the authentication method is enabled or disabled and the users and groups who are in scope for the auth method.",
```

2022-09-20 19:14 UTC, FaithOmbongi commented on api-reference/v1.0/resources/x509certificateuserbinding.md
> +|x509CertificateField|String|The field on the X.509 certificate to use for the binding. The possible values are: `PrincipalName`, `RFC822Name`.|
Your API.md shows two additional possible values. Can you verify?

2022-10-03 19:44 UTC, vimrang commented on api-reference/v1.0/resources/x509certificateuserbinding.md
> +|userProperty|String|Defines the Azure AD user property of the user object to use for the binding. The possible values are: **userPrincipalName**, `onPremisesUserPrincipalName`, `email`. Required.|
Corrected to use 4 properties for certificate field and 3 values for user object fields

2022-10-03 19:46 UTC, vimrang commented on api-reference/v1.0/toc.yml
> +              href: api/x509certificateauthenticationmethodconfiguration-delete.md
moved

2022-10-03 19:47 UTC, vimrang commented on api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md
> +
corrected

2022-10-03 19:49 UTC, vimrang commented on api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md
> +-->
corrected

2022-10-03 19:49 UTC, vimrang commented on api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md
> +# [HTTP](#tab/http)
corrected

2022-10-03 19:52 UTC, vimrang commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [x509CertificateAuthenticationMethodConfiguration](https://docs.microsoft.com/en-us/graph/api/resources/x509CertificateAuthenticationMethodConfiguration?view=graph
corrected

2022-10-03 19:53 UTC, vimrang commented on api-reference/v1.0/resources/x509certificateuserbinding.md
> +|x509CertificateField|String|The field on the X.509 certificate to use for the binding. The possible values are: `PrincipalName`, `RFC822Name`.|
corrected

2022-10-03 19:56 UTC, opbld33 commented
Learn Build status updates of commit _[6ff91c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ff91c2ba95e03e92c9c516e80a95bdf7ed3a8a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210031954137300-18246/BuildReport?accessString=932b327272731ccc81da411c95225146ccf3f56600d7a71517116ff76e20ab04).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:32 UTC, opbld31 commented
Learn Build status updates of commit _[802fbc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/802fbc75652f499c51795641dec083a63ece8a2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041529117238-18246/BuildReport?accessString=5b504de708e24799c8f4fd15ed8686f17665f59e9a254e803122323c41d42ea9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:38 UTC, opbld32 commented
Learn Build status updates of commit _[adc7bf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adc7bf1d8027f215f7851695ce818d260c92c1bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041535459211-18246/BuildReport?accessString=d79f798e3cd3252b1a7a5253cb2d2b1ef4223ad56f6bfff4ca8675482a2c2d83).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:50 UTC, opbld30 commented
Learn Build status updates of commit _[a180733](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a180733a291f5d9b64f85b3de82fe8292ef49138)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041548046311-18246/BuildReport?accessString=68d8f49b886fa079da66c62fe3c929ac39ca51637847701ffaae291df064aa67).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 15:53 UTC, opbld32 commented
Learn Build status updates of commit _[3688097](https://github.com/microsoftgraph/microsoft-graph-docs/commits/368809747e19d3c99e34c155fdeecc478a79b7e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/api/x509certificateauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmethodconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateauthenticationmodeconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateauthenticationmodeconfiguration?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificaterule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificaterule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificaterule?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/x509certificateuserbinding.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/resources/x509certificateuserbinding.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/x509certificateuserbinding?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/x509certificateauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-18246) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/cbagraphv1.0/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041548241352-18246/BuildReport?accessString=194d3dab8ad1bbe15c0d34ae21c3646e466a522c908170ff43de7a3e73bd8fd1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 02:11 UTC, Lauragra commented
@vimrang , if you would like to publish this PR, please remove the **do not merge** label and add **ready to merge**.

2022-10-12 01:32 UTC, merged