Add disk encryption type to CloudPC entity
microsoftgraph/microsoft-graph-docs pull request #18254
Opened 2022-08-31 03:54 UTC by BenxiangXiaMSFT

2022-08-31 03:57 UTC, opbld32 commented
Docs Build status updates of commit _[865ab2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/865ab2caa4abd8a37c313538d59d1ac0fb3d3b09)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-0094819f09e3340df09eb0358fea0d24-35ecfe9a)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0094819f09e3340df09eb0358fea0d24-35ecfe9a"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/resources/cloudpc.md)
 - **Line 50, Column 22**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#cloudPcDiskEncryptionState-values' in 'beta/resources/cloudpc.md', did you mean '#cloudpcdiskencryptionstate-values'?`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310354321948-18254/BuildReport?accessString=0661cc7d6806f2994b954cedecc6f39402aca1065e6960b0a48fced685b90b90).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 04:08 UTC, opbld34 commented
Docs Build status updates of commit _[6109996](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6109996ea8c52a27fbe2c8d0693a19502b9ee0a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310406502465-18254/BuildReport?accessString=18a7e16cb307eed9f3971087a4ab918dfb5a309239c8bfd38779c7e182503d77).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 05:31 UTC, RuiHou105 commented
Roadmap work item number:14978

2022-08-31 05:32 UTC, RuiHou105 approved these changes

2022-09-01 08:38 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpc-get.md
> +    "diskEncryptionState": "notAvailable"
Will this be returned by default? If so, please update list cloudpcs API example in this PR as well. Thanks a lot!

2022-09-02 03:15 UTC, opbld31 commented
Docs Build status updates of commit _[6df5c6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6df5c6a641c78d382c11223a536c9d9bb39a6f98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-95e3a185)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-95e3a185)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="8c19544f8e60e9a7f35cfc34390e88df-95e3a185"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a9854c9f614e4703ed375d736557d7fd-95e3a185"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209020311535210-18254/BuildReport?accessString=57f609db7b248ea47dcecbbb120fdf043b3527be28d1deb1bba9240f2389cdd9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 03:40 UTC, BenxiangXiaMSFT commented on api-reference/beta/api/cloudpc-get.md
> +    "diskEncryptionState": "notAvailable"
Examples updated.

2022-09-13 14:12 UTC, Danielabom commented
I contacted @BenxiangXiaMSFT, but it seems that they are not in. Today, I reached out to @RuiHou105 and @AshleyYangSZ.

2022-09-27 15:50 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|diskEncryptionState|[cloudPcDiskEncryptionState](#cloudpcdiskencryptionstate-values)|The disk encryption applied to the Cloud PC. Possible values: `notAvailable`, `notEncryped`, `encryptedUsingPlatf
```suggestion
|diskEncryptionState|[cloudPcDiskEncryptionState](#cloudpcdiskencryptionstate-values)|The disk encryption applied to the Cloud PC. Possible values: `notAvailable`, `notEncryped`, `encryptedUsingPlatformManagedKey`, `encryptedUsingCustomerManagedKey`, and `unknownFutureValue`.|
```

2022-09-27 16:23 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|notAvailable|The Cloud PC is not provisioned, or in a state that encryption is not available.|
```suggestion
|notAvailable|The Cloud PC is not provisioned, or in a state where encryption is not available.|
```

2022-10-04 16:38 UTC, opbld34 commented
Learn Build status updates of commit _[0f8ad77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f8ad77b7c4363959e258636c2bee0d76ab79833)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-eea93837)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-eea93837)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="8c19544f8e60e9a7f35cfc34390e88df-eea93837"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a9854c9f614e4703ed375d736557d7fd-eea93837"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210041636254243-18254/BuildReport?accessString=54f536af368ee28275fe8a39f63881659abade415a41cbe85accfdc4ac4a5f6f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-04 20:34 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|notEncryped|The Cloud PC should be encryped, but the encryption is not done yet (reserved, should not happen).|
```suggestion
|notEncryped|The Cloud PC should be encrypted, but the encryption is not done yet (reserved, should not happen).|
```

2022-10-05 01:15 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|encryptedUsingPlatformManagedKey|The Cloud PC is encrypted using platform managed key. This is the default if customer managed key is not enabled.|
```suggestion
|encryptedUsingPlatformManagedKey|The Cloud PC is encrypted using platform managed key. This is the default value if the customer-managed key is not enabled.|
```

2022-10-05 01:15 UTC, Danielabom commented on api-reference/beta/resources/cloudpc.md
> +|encryptedUsingCustomerManagedKey|The Cloud PC is encrypted using customer managed key.|
```suggestion
|encryptedUsingCustomerManagedKey|The Cloud PC is encrypted using customer-managed key.|
```

2022-10-05 01:23 UTC, Danielabom requested changes
Hi @BenxiangXiaMSFT, based on our conversation, the word encrypted appears misspelled several times in the PR. Please confirm whether you can address the changes in this PR or if you'll create a new one. Thanks

2022-10-08 06:53 UTC, AshleyYangSZ requested changes
@BenxiangXiaMSFT Please help update the PR according to the comments!

2022-10-11 15:40 UTC, opbld34 commented
Learn Build status updates of commit _[74c0bff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74c0bff0b6777de58363b691610ee6b2609358a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/user-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/user-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-8c19544f8e60e9a7f35cfc34390e88df-9e7c5f3c)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) | [Details](#user-content-a9854c9f614e4703ed375d736557d7fd-9e7c5f3c)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-18254) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="8c19544f8e60e9a7f35cfc34390e88df-9e7c5f3c"></a>
### [api-reference/beta/api/user-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/user-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a9854c9f614e4703ed375d736557d7fd-9e7c5f3c"></a>
### [api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/BenxiangxiaMSFT/CloudPCAddEncryptionType/api-reference/beta/api/virtualendpoint-list-cloudpcs.md)
 - **Line 10, Column 1**: **[Warning: duplicate-h1s - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List cloudPCs' is duplicated with other articles: 'beta/api/user-list-cloudpcs.md(10,1), beta/api/virtualendpoint-list-cloudpcs.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210111537519584-18254/BuildReport?accessString=f4a402cf537b7458c90ef1461cff5569bb76d0580c72a1314eeaac29289ceced).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 06:11 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpc.md
> +|diskEncryptionState|[cloudPcDiskEncryptionState](#cloudpcdiskencryptionstate-values)|The disk encryption applied to the Cloud PC. Possible values: `notAvailable`, `notEncryped`, `encryptedUsingPlatf
@BenxiangXiaMSFT Please help resolve this comment asap.

2023-01-17 22:16 UTC, Danielabom approved these changes
Changes look good . PR approved. Thanks, @BenxiangXiaMSFT.

2023-02-01 03:43 UTC, merged