Add Alert docs
microsoftgraph/microsoft-graph-docs pull request #18256
Opened 2022-08-31 07:02 UTC by zhishending

2022-08-31 07:05 UTC, opbld32 commented
Docs Build status updates of commit _[1fc58cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fc58cc33addca52da832503bcfd85c4b66dae85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-154f27e1)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-154f27e1"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310702400193-18256/BuildReport?accessString=053ca35823734b8b9dab89db579f994f695bbf81d0faefabab561ddf33fc4ba1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-a [...]

2022-08-31 07:18 UTC, opbld30 commented
Docs Build status updates of commit _[8cd3afb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cd3afb03bb552ed244386672859314ec4266fcc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ee90534b)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-ee90534b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310716487125-18256/BuildReport?accessString=32a187075ca818485077005b80b0fa91b6a7e972b4c6a0ee0d1796e13fdf53e9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-a [...]

2022-08-31 07:25 UTC, opbld34 commented
Docs Build status updates of commit _[b038a60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b038a6019973d4a8bec3122ea6b7965432ae2c96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-686b1d05)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-686b1d05"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310723072427-18256/BuildReport?accessString=c42e0ef53a7a18b4be6e20ec6291a0e57da780638692ead4af7b727e367d3c9a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-a [...]

2022-08-31 07:29 UTC, opbld30 commented
Docs Build status updates of commit _[05916d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05916d371963138a8bb55f9a56c890e4e21faa89)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7ee5de21)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-7ee5de21"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208310725007097-18256/BuildReport?accessString=7f4b2c370189d677171d13526d9fca57580db27241cfbb9cc1cfc8aa22be349f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-a [...]

2022-08-31 07:49 UTC, RuiHou105 commented
@zhishending  Please add your roadmap workitem number in comment.

2022-08-31 08:03 UTC, zhishending commented
Roadmap: 13682

2022-08-31 09:17 UTC, RuiHou105 commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +|alertRules|[microsoft.graph.deviceManagement.alertRule](../resources/devicemanagement-alertrule.md) collection|The collection of records of alert events.|
The two descriptions are mismatched

2022-08-31 09:19 UTC, RuiHou105 requested changes
One minor comment

2022-08-31 09:55 UTC, opbld32 commented
Docs Build status updates of commit _[479f952](https://github.com/microsoftgraph/microsoft-graph-docs/commits/479f952f610149cccbc8300e878f272c5ff2f365)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a4335493)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a4335493"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-08-31 09:57 UTC, zhishending commented on api-reference/beta/resources/devicemanagement-monitoring.md
> +|alertRules|[microsoft.graph.deviceManagement.alertRule](../resources/devicemanagement-alertrule.md) collection|The collection of records of alert events.|
Nice catch! Updated in new commit

2022-08-31 09:58 UTC, RuiHou105 approved these changes

2022-08-31 09:59 UTC, RuiHou105 commented
@Lauragra , @JarbasHorst , please help review this PR when you got time :)

2022-08-31 09:59 UTC, opbld34 commented
Docs Build status updates of commit _[e3f6cfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3f6cfe21dc8406a19499979b16e8f6d53498ea8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0664a31e)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-0664a31e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-08-31 10:10 UTC, opbld33 commented
Docs Build status updates of commit _[ca1196c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca1196ce7ae489ee6843dbbacb691637de2231a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6e80d766)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6e80d766"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-09-01 03:30 UTC, opbld30 commented
Docs Build status updates of commit _[793c866](https://github.com/microsoftgraph/microsoft-graph-docs/commits/793c86620b20be3eabf6c51aafffbeee371e1fa7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-731c6474)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-731c6474"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-09-01 04:04 UTC, opbld33 commented
Docs Build status updates of commit _[3817570](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38175700521167c1e6f7e7cac996ab27f1876d1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1717bf01)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-1717bf01"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 10202, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequ [...]

2022-09-14 19:48 UTC, JarbasHorst commented on api-reference/beta/api/devicemanagement-alertrecord-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/monitoring/alertRecords/{alertRecordId}
GLOBAL: Please apply this change to all API topics in this PR.

For clarity, please replace the placeholders, such as {alertRecordId}, with a real-looking ID. Examples with real-looking values in the, request URL, requests and response bodies help customers understand the API better. That's also the consistency bar for Microsoft Graph API docs.

2022-09-14 19:48 UTC, JarbasHorst commented on api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
> +title: "alertRecord: getPortalNotifications"
For clarity, I recommend you to rephrase the description in line 3. I think that "for current user" isn't possible, because this API also supports application permissions. Suggested revision:

- Get a list of all portal notifications that users can access.

Please, apply this change also to line 16.

2022-09-14 19:48 UTC, JarbasHorst commented on api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md
> +
(LINE 16) How is the sentence "You can use the portal notifications to publish Microsoft Endpoint Manager portal notifications." related to this API topic? This API is about reading data and not setting values.

2022-09-14 19:48 UTC, JarbasHorst commented on api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md
> +Set a single portal notification status to published. Will set isPortalNotificationSent property to true for current user.
How can you set the isPortalNotificationSent  property for the current (signed-in) user when making a request with application permissions? Should this sentence be rephrased?

2022-09-14 19:48 UTC, JarbasHorst commented on api-reference/beta/resources/devicemanagement-alertimpact.md
> +Represents the impact of the alert event. Consists of a number value and the aggregation type.
For simplicity, I recommend you to remove the second sentence from this summary section. The properties value and aggregation are already visible in the properties section, so this information is redundant.

2022-09-14 19:49 UTC, JarbasHorst commented
Hello @zhishending, I reviewed your PR and left some comments. Please, take a look when you will have time.

Also, to avoid merge conflicts, please merge PR [18490](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18490) into your branch to include my fixes and before addressing my comments.

2022-09-15 03:05 UTC, opbld32 commented
Docs Build status updates of commit _[367e59d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/367e59d98db92188012b8ae11306b25815eea1b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-auditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-auditevent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-auditevent-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-d315657666d6b6588053f307c5a31e37-38a68d19)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-a3efac7d723a7ec3960ad54152907495-38a68d19)
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-56364271c5659dc891565125fd2b1e91-38a68d19)
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-cloudpcoverview-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcoverview-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-19d0821738d1da4aafd5252c57f358c2-38a68d19)
[api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-conditionalaccesspolicycoverage-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-27ec0763e9b2121a922f7ba94144d1ca-38a68d19)
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-a92abbb10d0565472de1f149e30162a5-38a68d19)
[api-reference/beta/api/managedtenants-devicecompliancepolicysettingstatesummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-devicecompliancepolicysettingstatesummary-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-devicecompliancepolicysettingstatesummary-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-08ba2d63d3423a792eab1d223781adbf-38a68d19)
[api-reference/beta/api/managedtenants-manageddevicecompliance-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-manageddevicecompliance-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-manageddevicecompliance-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-df54a231eb4d15315c3623128eaf613e-38a68d19)
[api-reference/beta/api/managedtenants-manageddevicecompliancetrend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-manageddevicecompliancetrend-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-manageddevicecompliancetrend-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-afa7a451d611fa6ea420f06a555ad32d-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-aggregatedpolicycompliances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-aggregatedpolicycompliances.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-aggregatedpolicycompliances?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-854fd7bf179cb3018b54cfc38fea916f-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-auditevents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-auditevents?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-73b69ad4573590554dab1ae36e385a14-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-cloudpcconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-cloudpcconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-cloudpcconnections?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-f8dd0dba17bc3b815c7069046a72f095-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-cloudpcdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-cloudpcdevices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-cloudpcdevices?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-e1af36349215c35b5fd16f3489af4022-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-cloudpcsoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-cloudpcsoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-cloudpcsoverview?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-41f00716cb73b8a5a7363816a34a3f74-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-conditionalaccesspolicycoverages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-conditionalaccesspolicycoverages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-conditionalaccesspolicycoverages?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-f7ef13cca3e73bcade1c493ce6f52730-38a68d19)
[api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/e [...]

2022-09-19 22:51 UTC, JarbasHorst commented
Hi @zhishending, I continued with the content review work and fixed issues in 6 files. To avoid merge conflicts, please merge PR [18543](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18543) into your branch to include my fixes and before addressing my new comments.

2022-09-20 02:06 UTC, opbld34 commented
Docs Build status updates of commit _[404b6e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/404b6e2527b462b601aa7bb8307042821abc2159)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a825b9bd)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a825b9bd"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullReque [...]

2022-09-20 02:11 UTC, opbld30 commented
Docs Build status updates of commit _[0b5b3bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b5b3bde1e41a447b2e3fbcc1a034c3013947723)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b28f33f3)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-b28f33f3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullReque [...]

2022-09-20 23:41 UTC, JarbasHorst commented on api-reference/beta/resources/devicemanagement-rulethreshold.md
> +|:---|:---|
For clarity, please explain the comparison value in all cases. The operator is greater than or equal to ???

2022-09-20 23:43 UTC, JarbasHorst commented
Hello @zhishending, I am done for now with the content review work for this PR. Please, take a look at the existing comments when you will have time, so we can continue with the content review process.

2022-09-21 01:12 UTC, opbld32 commented
Docs Build status updates of commit _[b1f7c4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1f7c4d6b891114b69d95b20a74eaa300985c989)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b527eeb7)

<a id="b527eeb7"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit b1f7c4d6b891114b69d95b20a74eaa300985c989 in branch zhishending/addAlertDoc of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit f93e2f9526703c4929ad5c18f865ad249507dfff). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209210112020883-18256/BuildReport?accessString=07d66a1834377bb43621f1d6c418bf052f6ce50ef1e5683f24b00e2aa8dca2aa).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 06:00 UTC, opbld31 commented
Docs Build status updates of commit _[ddd4e2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddd4e2f60cf20bcec2a397a4c5dced3e66ef4636)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f429fab0)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-f429fab0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com [...]

2022-09-21 06:22 UTC, opbld31 commented
Docs Build status updates of commit _[5191e06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5191e06bdc02e0bffaa92ec6ec6b917e07e17da0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5bfc5ffc)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-5bfc5ffc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com [...]

2022-09-21 06:28 UTC, zhishending commented
Hi @JarbasHorst. Thanks a lot for your comments and fixes. I updated the PR based on all your suggestions. Please help review this PR again when you got time.

2022-09-21 22:26 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [18573](https://github.com/microsoftgraph/microsoft-graph-docs/pull/18573) into this branch to include my final edits.

2022-09-22 02:37 UTC, opbld34 commented
Docs Build status updates of commit _[e455ae9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e455ae980167d510e6f2d6fb9465e4c898a5a7aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6b1fd5f2)
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6b1fd5f2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml)
 - **Line 9972, Column 21**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/resources/intune-shared-devicemanagementderivedcredentialsettings.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com [...]

2022-10-04 21:22 UTC, opbld30 commented
Learn Build status updates of commit _[29c3032](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29c3032c5dde58166156489c8085f2fbd6167f26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210042116378125-18256/BuildReport?accessString=5d020faade9c0caea095d6738aad056dd3b3c019f27271f8c4409e4935c58e91).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href= [...]

2022-10-07 04:00 UTC, Lauragra commented on api-reference/beta/api/devicemanagement-alertrecord-get.md
> +If successful, this method returns a `200 OK` response code and an [alertRecord](../resources/devicemanagement-alertrecord.md) object in the response body.
Global: For APIs in subnamespaces, in the response section, we fully qualify the type name, so this should be microsoft.graph.deviceManagement.alertRecord. Please make this change in the Response sections throughout.

2022-10-09 07:15 UTC, opbld30 commented
Learn Build status updates of commit _[11ce83f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11ce83ffa837566368ecbd4123c1fb68abafb627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210090712523507-18256/BuildReport?accessString=ac2c62225d9d4b982182a9ab54e72a87a5a60488a25728406d62e51becb20c7c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href= [...]

2022-10-09 07:26 UTC, zhishending commented
@Lauragra Updated types names in the response sections for all APIs. Please help review agian. Thanks.

2022-10-11 21:04 UTC, Lauragra approved these changes

2022-10-12 02:50 UTC, AshleyYangSZ approved these changes

2022-10-12 02:53 UTC, opbld34 commented
Learn Build status updates of commit _[e3485cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3485cb08ec53897e4d090e90c5d3f3a339d8559)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120251111135-18256/BuildReport?accessString=65c75b167dc2fb8251a65cf96f1389b2b050421fb4f53b77d6da6b3a644e3936).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href= [...]

2022-10-12 04:21 UTC, opbld34 commented
Learn Build status updates of commit _[312b01a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/312b01ac3b88eb142fc78ac7ce7ed8ef0c043505)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/devicemanagement-alertrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-getportalnotifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-getportalnotifications?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrecord-setportalnotificationassent.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-setportalnotificationassent?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-list.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-list?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-post.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-post?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/api/devicemanagement-alertrule-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/api/devicemanagement-alertrule-update.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrule-update?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertimpact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertimpact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertimpact?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrecord.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrecord?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-alertrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-alertrule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-alertrule?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-monitoring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-monitoring.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-monitoring?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationchannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationchannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationchannel?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-notificationreceiver.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-notificationreceiver.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-notificationreceiver?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-portalnotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-portalnotification.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-portalnotification?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/resources/devicemanagement-rulethreshold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/resources/devicemanagement-rulethreshold.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/resources/devicemanagement-rulethreshold?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/devicemanagement-alertrecord-get?view=graph-rest-beta&branch=pr-en-us-18256) (graph-rest-beta) |
[changelog/Microsoft.DeviceManagement.Monitoring.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/zhishending/addAlertDoc/changelog/Microsoft.DeviceManagement.Monitoring.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210120418217385-18256/BuildReport?accessString=d7f7c983f0aac36b3eca2c076cba9098393ab6f5cabb754bf52f06d200728b16).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href= [...]

2022-10-12 04:27 UTC, merged