[SignIn] Adding appliedEventListeners to beta Prod, MC and FF.
microsoftgraph/microsoft-graph-docs pull request #18264
Opened 2022-08-31 23:10 UTC by junrlin

This is MSGraph Docs PR for my another PR which is to add `appliedEventListeners` in Beta Prod, MC and FF - [Pull Request 6653182](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6653182): [SignIn] Adding appliedEventListeners to beta Prod, MC and FF.

The property and whole workflow have been verified and as same as in Beta PPE, see [Pull Request 6386412](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6386412):  Adding appliedEventListeners to beta PPE. and [Pull Request 6577328: Fixing inheritance for customExtensionCalloutResult.](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/6577328).

They're based on same MSGraph onboarding updates:
(The first one the main one listed in JSON, the second one is a small update on descriptions)
Pull Request [10954](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/10954): [Reporting][SignIn] Adding appliedEventListeners to SignIn for custom extension.
Pull Request [11208](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/11208): Updating custom extension signin log type name and description.

2022-08-31 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[adf998e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adf998e5c4c941b12ae69b9743e3da728d82e9a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedauthenticationeventlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/appliedauthenticationeventlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedauthenticationeventlistener?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventhandlerresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/authenticationeventhandlerresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventhandlerresult?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/customextensioncalloutresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/customextensioncalloutresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensioncalloutresult?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208312310265418-18264/BuildReport?accessString=35304531810c0e45b88ae8c4008f62e98df628de08506a0172ba09f5c29c2756).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 23:27 UTC, besiler commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +|executedListenerId|String|ID of the Event Listener that was executed|
```suggestion
|executedListenerId|String|ID of the Event Listener that was executed.|
```

2022-08-31 23:32 UTC, besiler approved these changes
Looks good! Suggested some small tweaks and left a questino

2022-08-31 23:32 UTC, besiler commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +|eventType|authenticationEventType|The authentication event that triggered the custom extension request. The possible values are: `tokenIssuanceStart`, `pageRenderStart`, `unknownFutureValue`.|
```suggestion
|eventType|authenticationEventType|The type of authentication event that triggered the custom extension request. The possible values are: `tokenIssuanceStart`, `pageRenderStart`, `unknownFutureValue`.|
```

2022-08-31 23:32 UTC, besiler commented on api-reference/beta/resources/customextensioncalloutresult.md
> +|errorCode|Int32|Error code that's generated as a result of a failure with the API transaction of the last attempt.|
```suggestion
|errorCode|Int32|Error code that was generated as a result of a failure with the API transaction of the last attempt.|
```

2022-08-31 23:32 UTC, besiler commented on api-reference/beta/resources/signin.md
> +|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that are
```suggestion
|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that were triggered by the corresponding events in the sign-in event.|
```

2022-08-31 23:32 UTC, besiler commented on api-reference/beta/resources/signin.md
> +|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that are
@junrlin does this change make sense? I assume the authn activity is always the sign-in event represented by the signin resource

2022-09-01 22:23 UTC, junrlin commented on api-reference/beta/resources/signin.md
> +|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that are
I'd like to say we will also have events related to sign-up process, so I would keep the old sentence to describe more.

2022-09-01 22:26 UTC, opbld31 commented
Docs Build status updates of commit _[eecc766](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eecc7665c3bc3ccdec22c15cd813dffb9a2a808d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedauthenticationeventlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/appliedauthenticationeventlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedauthenticationeventlistener?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventhandlerresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/authenticationeventhandlerresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventhandlerresult?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/customextensioncalloutresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/customextensioncalloutresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/customextensioncalloutresult?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-18264) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/junrlin/add-appliedEventListeners-to-beta-prod/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209012224256949-18264/BuildReport?accessString=871ce7153a8af2c3870b488896db510052ff4e866656ccbb1ababbe8055d6e76).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 12:19 UTC, FaithOmbongi requested changes
Thank you, @junrlin, for your work in this PR. I've left inline suggestions for fixes + 
+ Global: Please update the author to the PM's alias.

2022-09-12 12:19 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationeventhandlerresult.md
> +This is an abstract type.
Align with metadata + show downstream object.
```suggestion
An abstract type that defines the result of authentication to event listeners in Azure AD sign-ins. This abstract type is inherited by the [customExtensionCalloutResult](../resources/customextensioncalloutresult.md) resource type.
```

2022-09-12 12:19 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationeventhandlerresult.md
> +|:---|:---|:---|
```suggestion
None.
```

2022-09-12 12:19 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensioncalloutresult.md
> +description: "Indicates the result of API request to the custom extension endpoint."
```suggestion
description: "Indicates the result of an API request to the custom extension endpoint. This object is used by the appliedEventListeners object of sign-ins."
```

2022-09-12 12:19 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensioncalloutresult.md
> +Indicates the result of API request to the custom extension endpoint.
```suggestion
Indicates the result of API request to the custom extension endpoint. This object is used by the **appliedEventListeners** object of [sign-ins](../resources/signin.md).
```

2022-09-12 12:19 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensioncalloutresult.md
> +|calloutDateTime|DateTimeOffset|Date and time (UTC) the API transaction was initiated. Example: midnight on Jan 1, 2014 is reported as 2014-01-01T00:00:00Z.|
```suggestion
|calloutDateTime|DateTimeOffset|When the API transaction was initiated. The date and time information uses ISO 8601 format and is always in UTC time. Example: midnight on Jan 1, 2014, is reported as `2014-01-01T00:00:00Z`.|
```

2022-09-12 12:19 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensioncalloutresult.md
> +|numberOfAttempts|Int32|The number of API calls to the customer's API.|
Could you explain **numberOfAttempts**? Especially "customer's API"?
```suggestion
|customExtensionId|String|Identifier of the custom extension that was called.|
|errorCode|Int32|Error code that was returned when the API transaction failed.|
|httpStatus|Int32|The HTTP status code that was returned by the target API endpoint.|
|numberOfAttempts|Int32|The number of API calls to the customer's API.|
```

2022-09-12 12:19 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the `appliedEventListeners` property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
```suggestion
          "Description": "Added the **appliedEventListeners** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
```

2022-09-12 21:24 UTC, junrlin commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +author: "junrlin"
Will do

2023-01-13 01:28 UTC, junrlin commented on api-reference/beta/resources/signin.md
> +|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that wer
Not limited to Azure Logic Apps, it can be Azure Functions or other ways to do the same functionality.

2023-01-13 01:29 UTC, junrlin commented on api-reference/beta/resources/authenticationeventhandlerresult.md
> +description: "Indicates the handler result of this authentication event."
I think correct

2023-01-13 01:30 UTC, junrlin commented on api-reference/beta/resources/authenticationeventhandlerresult.md
> +This is an abstract type.
Do we need to list inheritance here? because we will have more types to inherit in the future.

2023-01-13 07:02 UTC, FaithOmbongi commented on api-reference/beta/resources/authenticationeventhandlerresult.md
> +This is an abstract type.
Yes, we do. Without the link to the downstream objects, the docs and the customer drop off here, disrupting their flow.

When we have more types, we'll also add them to the list, np.

2023-01-13 07:04 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that wer
That's OK. "such as" shows it's only just Azure Logic Apps. You can also edit the sentence to "such as Azure Logic Apps and Azure Functions". The intent is to show customers what listeners are supported.

2023-01-13 22:17 UTC, AlexanderMars commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +author: "junrlin"
We don't know in a long term which PM will take it over. Suggesting to keep it as is for now.

2023-01-25 00:35 UTC, junrlin commented on api-reference/beta/resources/signin.md
> +|appliedEventListeners|[appliedAuthenticationEventListener](../resources/appliedauthenticationeventlistener.md) collection|Detailed information about the applied event listeners or listeners that wer
Got it, thanks!

2023-01-25 00:35 UTC, junrlin commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +author: "junrlin"
Will use my alias for now

2023-01-25 00:40 UTC, junrlin commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +description: "Indicates detailed information about the applied event listeners or listeners that are triggered by the corresponding events in an authentication activity."
Is this supposed to be the exact same as what it is in signin.md?

2023-01-25 00:44 UTC, junrlin commented on api-reference/beta/resources/authenticationeventhandlerresult.md
> +This is an abstract type.
got it

2023-01-25 00:50 UTC, junrlin commented on api-reference/beta/resources/customextensioncalloutresult.md
> +|numberOfAttempts|Int32|The number of API calls to the customer's API.|
So you can see we may try several times of attempting to run the external API, when we don't need to say that in errorCode and httpStatus?

2023-01-25 00:52 UTC, junrlin commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the `appliedEventListeners` property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
I think this is generated automatically? I don't remember I typed all of those, and it's changeList

2023-01-26 14:51 UTC, FaithOmbongi commented on api-reference/beta/resources/customextensioncalloutresult.md
> +|numberOfAttempts|Int32|The number of API calls to the customer's API.|
God question - Yes, add this info to errorCode and httpStatus. Assuming the value in errorCode and httpStatus are from the last attempt, then consider this suggestion:

- errorCode - Error code that was returned when the last API attempt failed.
- httpStatus - The HTTP status code that was returned by the target API endpoint after the last API attempt.

2023-01-26 14:54 UTC, FaithOmbongi commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +description: "Indicates detailed information about the applied event listeners or listeners that are triggered by the corresponding events in an authentication activity."
Not necessarily. Because in signin.md is just one property; But this is a complex type that "feeds" data into that property.

2023-01-26 14:55 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the `appliedEventListeners` property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
Unfortunately, it's a stub autogeneration inconsistency. But properties are in **Bold**.

2023-01-26 22:34 UTC, junrlin commented on changelog/Microsoft.AAD.Reporting.json
> +          "Description": "Added the `appliedEventListeners` property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
I see, actually I don't remember if I use any stub tool to generate it haha. But I remember using stub or something in Workloads repo - the CSDL one.

2023-01-26 22:37 UTC, junrlin commented on api-reference/beta/resources/customextensioncalloutresult.md
> +|numberOfAttempts|Int32|The number of API calls to the customer's API.|
Sweet, updating.

2023-01-26 22:42 UTC, junrlin commented on api-reference/beta/resources/appliedauthenticationeventlistener.md
> +description: "Indicates detailed information about the applied event listeners or listeners that are triggered by the corresponding events in an authentication activity."
Makes sense

2023-01-30 18:53 UTC, FaithOmbongi approved these changes
Thank you @junrlin for your work on this PR. Approved.

2023-01-31 04:07 UTC, merged

2023-01-31 22:23 UTC, mistermik commented
@FaithOmbongi i see the documentation is published already, but we shouldn't have done that. Can we somehow roll back those changes or is it too late ? Thanks a lot

2023-02-01 06:32 UTC, FaithOmbongi commented
Hi @mistermik - Let me follow up internally.