Add service principal get by appId docs
microsoftgraph/microsoft-graph-docs pull request #18260
Opened 2022-08-31 13:44 UTC by franqq

2022-08-31 13:47 UTC, opbld30 commented
Docs Build status updates of commit _[924bb1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/924bb1a4e1d3d37b059c17bb12a26e2be97b8a3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-get-by-appId.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get-by-appId.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get-by-appid?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311344426194-18260/BuildReport?accessString=fd96fa9d58fad6c480377e41ccd2e3e71c067f7f24b5a1880e3ed1dbf544d7db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 13:52 UTC, opbld30 commented
Docs Build status updates of commit _[3ded621](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ded621913023be9c31cc9cadc88b9f35b11a33d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-get-by-appId.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get-by-appId.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get-by-appid?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202208311347030223-18260/BuildReport?accessString=70bafdbec905bc906227437a69b98252f234dc639db6d1d15f96246a77390bb4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 20:06 UTC, opbld33 commented
Docs Build status updates of commit _[e767e9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e767e9f64fa6ab10ccccc8b9915e8354253c8d3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-get-by-appId.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get-by-appId.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get-by-appid?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202209072003563418-18260/BuildReport?accessString=c3c46eb3694c9ffe0d6b56da5524481a4bd96926dec78f527737eb4f2a905317).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 20:54 UTC, opbld31 commented
Docs Build status updates of commit _[f324c11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f324c1143a754656bf450323fa589885eb96f2bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-createpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-deletepasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get-by-appId.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get-by-appId.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get-by-appid?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-getpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignedto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-owners.md) | :white_check_ [...]

2022-09-07 20:57 UTC, opbld34 commented
Docs Build status updates of commit _[d5e8c09](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5e8c09c3710de5206a1eab0d7980c269a48d107)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-createpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-delete-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-deletepasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-getpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignedto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-post-owners?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-removekey.md) | :white_check_mark:Su [...]

2022-09-08 14:49 UTC, FaithOmbongi requested changes
Hi @franqq
+ Minor fixes to two instances. I think undoing those instances should resolve your API Doctor validation error.
+ ~Add the federated identity credentials docs as well~
+ Add changelog. Proposal 👇🏾

```
{
      "ChangeList": [
        {
          "Id": "f3fd9d42-fb5c-46d8-abad-a51ca6c31aab",
          "ApiChange": "Property",
          "ChangedApiName": "appId",
          "ChangeType": "Addition",
          "Description": "Added support for addressing an [servicePrincipal](https://docs.microsoft.com/graph/api/resources/serviceprincipal?view=graph-rest-beta) using the service principal **appId** as the alternate key. You can now address a service principal via either the primary key **id** or the alternate key **appId** as the path parameter.",
          "Target": "servicePrincipal"
        }
      ],
      "Id": "f3fd9d42-fb5c-46d8-abad-a51ca6c31aab",
      "Cloud": "Prod",
      "Version": "beta",
      "CreatedDateTime": "2021-08-19T00:00:00.077762Z",
      "WorkloadArea": "Application",
      "SubArea": ""
    },
```

2022-10-27 10:01 UTC, JohnMaina commented on api-reference/beta/api/serviceprincipal-get.md
> +GET https://graph.microsoft.com/beta/servicePrincipals(appId='{appId}')
Done

2022-10-27 10:01 UTC, JohnMaina commented on api-reference/beta/api/serviceprincipal-get.md
> +GET https://graph.microsoft.com/beta/servicePrincipals/(appId='{appId}')?$select=customSecurityAttributes
done

2022-10-27 10:04 UTC, opbld34 commented
Learn Build status updates of commit _[ebe8ff0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebe8ff0b36e1cf934dd54951c39f22cc048c35c3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b109aa3b)

<a id="b109aa3b"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ebe8ff0b36e1cf934dd54951c39f22cc048c35c3 in branch franqq-alt-key-syntax-for-service-principals of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 0ce85fe5de14a4650d24348259e41f402d38c57e). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/77e68b91-cf14-3558-43ca-0d6d735c492d/202210271003506684-18260/BuildReport?accessString=ee7c5dc83f2da7e18449f2a70c8f93839189ef1b84b91b9a2f24db705cd3b5bc).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-14 17:15 UTC, opbld32 commented
Learn Build status updates of commit _[826685f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/826685fa203abe25413f50d15131a28a779fdc6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-createpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-deletepasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-getpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignedto.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-owners?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-removekey.md) | :w [...]

2022-11-14 17:21 UTC, FaithOmbongi approved these changes

2022-11-14 17:22 UTC, opbld31 commented
Learn Build status updates of commit _[f34944d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f34944d2937a73bef20c3e2cebffc7a277e34459)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-createpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-deletepasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-getpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignedto.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-owners?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-removekey.md) | :w [...]

2022-11-14 17:24 UTC, opbld30 commented
Learn Build status updates of commit _[b427b46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b427b4678e3b06af21b962b58a2b440c7497eb1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceprincipal-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addkey.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addpassword.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addpassword?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-addtokensigningcertificate.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-addtokensigningcertificate?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-createpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-createpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-delete-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-deletepasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-deletepasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-getpasswordsinglesignoncredentials.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-getpasswordsinglesignoncredentials?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignedto.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-approleassignments.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-delegatedpermissionclassifications.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-delegatedpermissionclassifications?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-homerealmdiscoverypolicies.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-homerealmdiscoverypolicies?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-post-owners.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/graph/api/serviceprincipal-post-owners?view=graph-rest-beta&branch=pr-en-us-18260) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-removekey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/franqq-alt-key-syntax-for-service-principals/api-reference/beta/api/serviceprincipal-removekey.md) | :w [...]

2022-11-15 02:50 UTC, merged